### ISSUE TITLE
glTF geometry buffer offset issue

### ISSUE THREAD

**Issue by richtr** [assimp/assimp#1002]
I have an OBJ/MTL model that I need to convert to glTF.

The original source files are here: (OBJ format) https://github.com/richtr/three.js/tree/gh-pages/examples/models/gltf/Minion/source/. The output files from the coversion are here: (glTF format) https://github.com/richtr/three.js/tree/gh-pages/examples/models/gltf/Minion/glTF/.

I then use [`assimp`](https://github.com/assimp/assimp) to convert these files to the glTF format on the command line as follows:

`assimp export ./source/Minion.obj ./glTF/Minion.gltf`

This command completes successfully.

I can inspect the original source file and get the following:

``` bash
$> assimp info ./source/Minion.obj

Launching asset import ...           OK
Validating postprocessing flags ...  OK
Importing file ...                   OK
   import took approx. 0.20682 seconds

Memory consumption: 621408 B
Nodes:              4
Maximum depth       2
Meshes:             10
Animations:         0
Textures (embed.):  0
Materials:          9
Cameras:            0
Lights:             0
Vertices:           9259
Faces:              13572
Bones:              0
Animation Channels: 0
Primitive Types:    linestriangles
Average faces/mesh  1357
Average verts/mesh  925
Minimum point      (-4.818348 -2.837892 -5.243814)
Maximum point      (1.430433 2.149038 -2.422743)
Center point       (-1.693957 -0.344427 -3.833279)

Named Materials:
    'Detalhe'
    'Material'
    'Minion'
    'OLHOS'
    'Roupa'
    'Sapato'
    'boca'
    'fita'
    'oCULOS'

Node hierarchy:
'Minion.obj', meshes: 0
-- 'Plane', meshes: 2
-- 'Cylinder.002', meshes: 3
-- 'Sphere', meshes: 5
<--

```

However, when I run the following I get an error:

```
$> assimp info ./glTF/Minion.gltf

Launching asset import ...           OK
Validating postprocessing flags ...  OK
Assertion failed: (i*stride < accessor.bufferView->byteLength), function GetValue, file /Users/richt/Apps/assimp/code/glTFAsset.inl, line 584.
[1]    65714 abort      ./assimp info ~/glTF/Minion.gltf
```

Additionally, when I then load this glTF file via the glTF loader available in THREE.js [here](https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders/gltf) there is then an issue with the output rendering that looks to be related.

It looks like only half the triangles are being rendered from this model.

[HERE IS THE LIVE VERSION](https://richtr.github.io/three.js/examples/?q=gltf#webgl_loader_gltf)

Here's a screenshot of the current rendering issue via THREE.js:

<img width="423" alt="screen shot 2016-09-21 at 12 33 13 am" src="https://cloud.githubusercontent.com/assets/497699/18691262/06ad5718-7f93-11e6-9eed-383410f96fe7.png">

It feels like the offset or vertex stride is not being taken in to account in the glTF loader.

Any other thoughts/ideas as to the source of this issue would be welcome as I'm not sure where to begin with this.

**Comment by richtr** [comment]
The noticeable thing about the [input .obj file](https://github.com/richtr/three.js/blob/gh-pages/examples/models/gltf/Minion/source/Minion.obj) is that is uses [Vertex Normal Indices Without Texture Coordinate Indices](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_Normal_Indices_Without_Texture_Coordinate_Indices).

ping @johnmaf @otgerrogla @kimkulling as the people most likely to know what could be happening here.

**Comment by johnmaf** [comment]
Right now the glTF exporter assumes that all faces are triangular, and that all faces in a given mesh have the same number of indices. The OBJ you referenced seems to contain mostly quads, and also mixes faces with different numbers of indices. You might want to try triangulating the OBJ before sending it to the glTF exporter.

**Comment by richtr** [comment]
I've tested https://github.com/assimp/assimp/issues/1004 and it fixes both the `assimp info` and output rendering issues.

Really nice stuff and thanks for your help @johnmaf :)

I'm currently in the process of fixing up the glTF renderer within THREE.js (e.g. you need this PR to run `assimp` exported glTFs right now: https://github.com/mrdoob/three.js/pull/9726) and this fix has helped a lot!

**Comment by richtr** [comment]
I've updated the [live demo](https://richtr.github.io/three.js/examples/?q=gltf#webgl_loader_gltf) to show the fix working in https://github.com/assimp/assimp/pull/1004.

<img width="499" alt="screen shot 2016-09-21 at 6 02 31 pm" src="https://cloud.githubusercontent.com/assets/497699/18718952/9fafc80a-8025-11e6-901d-fb7333aa99ff.png">

💯 🚀

**Comment by johnmaf** [comment]
That's great to hear. Looks like we've run into similar issues with the loader. Good luck with that as well!

**Comment by kimkulling** [comment]
Thanks for the issue and thanks for the fixes.
