### ISSUE TITLE
Texture mapping issue

### ISSUE THREAD

**Issue by Tonyx97** [assimp/assimp#1010]
Hello I'm having a problem for several days and I can't figure out what's really going on. First of all I'm using as base [this](http://www.mbsoftworks.sk/index.php?page=tutorials&series=1&tutorial=23) tutorial to import assimp models and never tried to make a "complex" model that contains some meshes with different textures and now I figured out that the textures are not well mapped. For example, [THIS](https://i.gyazo.com/1e67fb46b14a90ca523f1f95e7afe13a.jpg) this model contains 2 materials so assimp split the model in 2 meshes and it's well mapped, each texture in it's material, green one and the girl another one. But trying another model happens [this](https://i.gyazo.com/184bfa7d3b26cd2119a0e1101a3077f6.png), it should be like [this](http://vignette3.wikia.nocookie.net/gtawiki/images/1/1a/BedfordPointcathedral-GTA3-westside.jpg/revision/latest?cb=20091224095159) and I think the UV are ok. I tried to load the model with several different flags but nothing. Here's the part of my source to import the model and save the buffers:

Load Models:
```
VBO.createVBO();
	glGenVertexArrays(1, &VBOID);
	glBindVertexArray(VBOID);
	VBO.bindVBO();

	FOR(j, mesh->mNumFaces)
	{
		const aiFace& face = mesh->mFaces[j];
		FOR(k, 3)
		{
			aiVector3D pos = mesh->mVertices[face.mIndices[k]];
			aiVector3D uv = mesh->mTextureCoords[0][face.mIndices[k]];
			aiVector3D normal = mesh->HasNormals() ? mesh->mNormals[face.mIndices[k]] : aiVector3D(1.f, 1.f, 1.f);
			Console::Print(DColor::Yellow, __FILE__, __FUNCTION__, "%.2f %.2f %.2f", uv.x, uv.y, uv.z);
			VertexCoords.push_back(glm::vec3(pos.x, pos.y, pos.z));			//mesh collider
			VBO.addData(&pos, sizeof(aiVector3D));
			VBO.addData(&uv, sizeof(aiVector2D));
			VBO.addData(&normal, sizeof(aiVector3D));
		}
	}

	VBO.uploadDataToGPU(GL_STATIC_DRAW);

	glEnableVertexAttribArray(0);
	glEnableVertexAttribArray(1);
	glEnableVertexAttribArray(2);

	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 2 * sizeof(aiVector3D) + sizeof(aiVector2D), 0);
	glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(aiVector3D) + sizeof(aiVector2D), (void*)sizeof(aiVector3D));
	glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, 2 * sizeof(aiVector3D) + sizeof(aiVector2D), (void*)(sizeof(aiVector3D) + sizeof(aiVector2D)));
```

Render Model:
```
void CMesh::MeshEntry::render()
{
	glBindVertexArray(VBOID);
	glBindTexture(GL_TEXTURE_2D, TextureManager::EngineTexture[TextureName].ID);

	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, Renderer->GetMagFilter());
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, Renderer->GetMinFilter());

	glDrawArrays(GL_TRIANGLES, 0, VertexSize);

	glBindVertexArray(0);
	VBO.unmapBuffer();
	VBO.releaseVBO();
}

```

This is how I exactly load the model:
```
const aiScene* scene = importer.ReadFile((std::string(_path) + std::string(filename)).c_str(), aiProcessPreset_TargetRealtime_MaxQuality);

	if (!scene) 
		printf("Unable to load mesh: %s\n", importer.GetErrorString());

	MeshEntry::theScene = scene;

	FOR(i, scene->mNumMeshes)
	{
		if (scene->mMeshes[i]->HasTextureCoords(0) && scene->mNumMaterials > 0)
		{
			RealName.clear();
			path.Clear();

			TextureFound = AI_FAILURE;
			if (scene->mMaterials[i]->GetTextureCount(aiTextureType_DIFFUSE) > 0)
				TextureFound = scene->mMaterials[i]->GetTexture(aiTextureType_DIFFUSE, 0, &path);
			if (TextureFound == AI_SUCCESS)
			{
				RealName = std::string(path.C_Str());
				RealName.erase(RealName.end() - 4, RealName.end());
			}
		}
		Meshes.push_back(new CMesh::MeshEntry((!strcmp(_texture.c_str(), "def")) ? RealName : _texture, scene->mMeshes[i], &TotalFaces, bDebug));
	}
```

I don't know where's the problem I appreciate any help, thanks for read.

**Comment by smalcom** [comment]
Can you share model?

**Comment by Tonyx97** [comment]
For sure, https://mega.nz/#!r0oSmBCT!osqLDg0S4svzVEq4RV4O06RofBRL7tuA5kp5IA7G5kk

**Comment by smalcom** [comment]
Looks like something wrong with coordinates: look at white "circles".
Screenshot from Assimp viewer:
![church](https://cloud.githubusercontent.com/assets/19540675/18979830/22e68878-86d7-11e6-8ca4-8b9fae7fa099.png)

Used DrawArrays, not VBO

**Comment by kimkulling** [comment]
Hm, need to study the code.

smalcom <notifications@github.com> schrieb am Fr., 30. Sep. 2016, 05:28:

**Comment by Tonyx97** [comment]
I didn't realize that I was using the clamp format for texture loading.. now works great with VBOs, thanks smalcom :) I just removed this, I was using this 2 lines cause I forgot to remove them when c&p my skybox loading code.

```
//glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
//glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
```
