### ISSUE TITLE
Assimp import throws StackoverflowException can't be caught by try/catch in .NET env

### ISSUE THREAD

**Issue by ytaous** [assimp/assimp#1013]
Using .NET dll (from NuGet), from time to time we are getting exception that can't be caught by try/catch. 
StackoverflowException is one example - https://msdn.microsoft.com/en-us/library/system.stackoverflowexception(v=vs.110).aspx 
You can download the mode from http://static.tf3dm.com/models/c3dc953mnm68-Colloseum-by-William.zip to repro the issue. We also found other uncaughtable exception. I'll add to this ticket once I have more details. 
Request - can all these exceptions be handled by assimp code? In our continuous process, it would stop when this kind of exception triggered.
Thanks.
-Ethan

**Comment by kimkulling** [comment]
Hi,
Do you have an idea, if we need special .net-specific handlercode? Or do we
just need to use standard try-catch?

Kim

ytaous <notifications@github.com> schrieb am So., 2. Okt. 2016, 06:43:

**Comment by ytaous** [comment]
Hi, Kim,
Per the doc link: " For example, if your app depends on recursion, use a counter or a state condition to terminate the recursive loop." There's no .net specific handler code. If the recursion logic in assimp is pure .net (no native), perhaps counter as (optional) param is one possible way. But if assimp is using native/c/c++ behind the scene, you can check if it already has try/catch around the code.  
-Ethan

**Comment by ytaous** [comment]
Another possible solution above  might be changing the recursive calls into iterative loops.

Just now I can repro another uncaughtable exception. Here is the details:

FatalExecutionEngineError occurred
  HResult=-2146233082
  Message=Exception of type 'System.ExecutionEngineException' was thrown.
  InnerException: 

http://static.tf3dm.com/models/1/b6193a6p5m2o-Glass_Sparkling_Water.rar

-Ethan

**Comment by ytaous** [comment]
Looks like I was posting to the wrong website. There's another similar dll called AssimpNet causing the issues. I am gonna test the latest dll version 3.2.0 that you guys posted. If I see the same issue, I'll let you know. Otherwise, please consider this case closed.
Thanks.

**Comment by ytaous** [comment]
In fact, I just realize the link to the AssimpNet version is the same. So I created another ticket there to track.
Thanks.
