### ISSUE TITLE
DAE, Collada: Wrong opacity material values

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#1023]
Hi Assimp team,

I imported this file through the importer: [https://storage.googleapis.com/assimp_model_error/Wrong_opacity_value.dae](https://storage.googleapis.com/assimp_model_error/Wrong_opacity_value.dae)

And the opacity values from the materials where opposite then what it should be. The opacity value was equal to zero, but in the DAE file you can see that the transparency values is equal to zero. So the opacity values should be 1.0.

Best

**Comment by kimkulling** [comment]
Should be fixed now. Please reopen when you still have issues.

Kim
