### ISSUE TITLE
3MF example files fail to load (Crash) ASSIMP 3.3

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1031]
I have been able to build 3.3 (not 3.3.1) of assimp.
Using it, I have tried to load the 4 examples of 3MF files from the 3MF
Consortiums website.  All 4 fail to load, 3 crashing at the same XML
reading code (appears there is a null pointer) and 1 at another
locations I have yet to investigate in detail.  I fixed the null pointer
issue, as it was trying to assign to a std::string a null pointer which
is illegal.
Now I it reading the file but trying to post-process it and get an error
in ComputeUVMappingProcess::Execute().
The scene flags are compared to AI_SCENE_FLAGS_NON_VERBOSE_FORMAT and
throws the DeadlyImportError exception.
I know 3ML files use the same vertices for multiple triangles so this
makes sense.  Why is ComputeVUMappingProcess throwing an exception
rather than fixing the scene formatting if that is what is required?
How does one do that anyways (I assume a prior pre-processing step)?

Has anyone else tried loading 3MF files, have you fixed the codes etc?111
## 

Thank you,
David Rivkin, PhD

**Comment by kimkulling** [comment]
Comment from ML:
I have been able to build 3.3 (not 3.3.1) of assimp.
Using it, I have tried to load the 4 examples of 3MF files from the 3MF
Consortiums website.  All 4 fail to load, 3 crashing at the same XML
reading code (appears there is a null pointer) and 1 at another
locations I have yet to investigate in detail.
Has anyone else tried loading 3MF files, have you fixed the codes etc?

**Comment by DavidARivkin** [comment]
To add a bit more information as this is really 2 bugs:
1.   The example file Torus.3mf contains a model with xmlns:m="http://schemas.microsoft.com/3dmanufacturing/material/2015/02"  With this included, the file can not be read by the XMLreader.
If you remove this line, the file continues to the next exception point.
It is a bit confusing as to how ASSIMP really works between the documentation stating that faces share vertices, and then the code (next to AI_SCENE_FLAGS_NON_VERBOSE_FORMAT) stating the opposite.
Why is the LoadFile method even having post-processing flags, this should be format specific stuff, not generic to any file format.

**Comment by DavidARivkin** [comment]
For clarity, here is my call to ReadFile using a Qt based app:
Assimp::Importer imp;
    setScene(imp.ReadFile(m_fileInfo.absoluteFilePath().toStdString(), aiProcess_Triangulate |
                                                         aiProcess_ValidateDataStructure |
                                                         aiProcess_GenUVCoords));

**Comment by kimkulling** [comment]
I tried to load some models and failed. Investigations ongoing.

**Comment by kimkulling** [comment]
Duplicate to 1128: will be fixed there!

**Comment by DavidARivkin** [comment]
Does this mean it has been fixed?

David Rivkin, PhD

**Comment by kimkulling** [comment]
Unfortunately not until now! I just started a new job and I am currently
less on time.

David Rivkin, PhD <notifications@github.com> schrieb am Mi., 8. Feb. 2017
um 13:27 Uhr:
