### ISSUE TITLE
Undefined symbols for x86_64 with iOS build

### ISSUE THREAD

**Issue by dmsurti** [assimp/assimp#1036]
Using Xcode: Version 7.3.1 (7D1014)

With the following changes to `build.sh` for iOS:

![screenshot 2016-10-17 18 29 14](https://cloud.githubusercontent.com/assets/4158417/19438605/67861e02-9498-11e6-9024-a86589d33000.png)
I built the iOS libraries with the following command:

`./build.sh --stdlib=libc++ --archs="arm64 x86_64"`

I checked the arch for the generated file which is correct as such:
```
xcrun -sdk iphoneos lipo -info libassimp-fat.
Architectures in the fat file: libassimp-fat.a are: x86_64 arm64
```

Then I create an Xcode iOS project with the following settings:

![screenshot 2016-10-17 18 27 32](https://cloud.githubusercontent.com/assets/4158417/19438610/6cd8b34c-9498-11e6-89de-65786e8b7e27.png)

I also have `-lz` in the other linker flags and C++ standard library is set to `libc++`. The harder search path is also set correctly. 

However when I build I get undefined symbols for `x86_64` but the fat lib has that arch. 

Also, the `libzlibstatic.a` is not a fat file:
```
input file libzlibstatic.a is not a fat file
Non-fat file: libzlibstatic.a is architecture: x86_64
```

Should I also add the `zlib` static file just like the assume static file or just -lz will work fine?

Any pointers?

**Comment by kimkulling** [comment]
Have you tried our cmake-based build as well? Does the error occur with generated makefiles?

**Comment by dmsurti** [comment]
@kimkulling I tried making the static file with the `CMake` Xcode project. These were the settings I used. I don't think they are right. I could not build the static file with the generated Xcode project.

![screenshot 2016-10-18 12 01 27](https://cloud.githubusercontent.com/assets/4158417/19466770/fd7396a0-952a-11e6-90b1-b43045f55618.png)

The error in the Xcode project build is: 
![screenshot 2016-10-18 12 01 53](https://cloud.githubusercontent.com/assets/4158417/19466775/0215c75a-952b-11e6-93c3-6f1159f829c9.png)

The above error is obvious as I could only specify one SDK under CMAKE_OSX_SYSROOT which does not seem right for iOS build. Sorry, I do not know CMake in depth, but a few pointers will help.

Can you let me know the correct settings/process to build the static library with CMake based build?

When I build the dynamic library earlier, I had set the `BUILD_STATIC_LIB=ON` which does generate a `libassimp.a` but that is a  static library for OS X as I could verify:

![screenshot 2016-10-18 12 08 42](https://cloud.githubusercontent.com/assets/4158417/19466888/a87c7314-952b-11e6-90b2-611b5a460117.png)

Thanks.

**Comment by dmsurti** [comment]
Finally I got this working. It was actually a matter of applying the correct the Xcode Build settings for the following, after building the static library.

I built the iOS libraries with the following command:
`./build.sh --stdlib=libc++ --archs="armv7 arm64 x86_64"` 
which generates the correct libraries, including the fat lib under `lib`.

The settings that I had to apply for the Xcode project are:

```
Enable BitCode --> NO
Other linker flags --> -lz -lstdc++
Header Search Paths --> /usr/local/include
```

It was the lack of `stdc++`linker flag and  NOT disabling bit code which were causing the undefined undefined symbols for `x86_64`  errors.

Screenshot of working project:

![screenshot 2016-10-19 16 47 07](https://cloud.githubusercontent.com/assets/4158417/19516852/b50ea7f0-961b-11e6-871f-5d10935aff35.png)

Closing this issue. @kimkulling Thanks.

**Comment by khaire1111** [comment]
I have issue pls tell me anyone

I created one custom framework for social login it's working as debug mode 
but whenever I build framework for release mode it gives error like

Undefined symbols for architecture x86_64:
"OBJC_CLASS$_Social", referenced from:
objc-class-ref in ViewController.o
objc-class-ref in DetailViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I do not understand what is happaning on release mode

I write singleton class of Social 
and it has one method as

+(instancetype)methodSocial { }

**Comment by dmsurti** [comment]
@khaire1111 From your description, this does not seem to be an issue with assimp? If yes, please provide the relevant information. 

If you are not using assimp or if this is not an assimp issue, then it is the wrong project/forum to report your problem.
