### ISSUE TITLE
LWSImporter chokes on "LightIntensity (envelope)" line.

### ISSUE THREAD

**Issue by rcane** [assimp/assimp#1044]
I have an lws file that contains the line:

`LightIntensity (envelope)`

The parser assumes that the token after _LightIntensity_ must be a number and therefor throws an exception when it finds _(envelope)_ instead. I am not familiar with the lws format so I don't know what that _(envelope)_ is supposed to mean. A quick fix for me was to just replace _(envelope)_ with a _1_. But a more general solution would certainly be better. ;-)

The lws file I am seeing this with can be found [here](https://nasa3d.arc.nasa.gov/detail/iss-hi-res). It is contained inside the zip file inside the _Scenes_ folder.

**Comment by kimkulling** [comment]
The Envelope says that the value is a function over time. This feature is currently not supported. So we need to add the support for that.

**Comment by kimkulling** [comment]
Shall work now. Unfortunately, we are not supporting animated light intensity at this moment.
