### ISSUE TITLE
Specify Configuration Properties of Importer

### ISSUE THREAD

**Issue by tportenier** [assimp/assimp#1045]
It would be nice to be able to specify properties for the importer, similar to the SetPropertyFloat, SetPropertyInteger, and SetPropertyString functions of the c++ API. Especially AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE would be handy, setting the flag aiProcess_GenSmoothNormals is useless without a reasonable value for AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE . Is there a way to do that from python? My workaround so far is to hard-code the desired value in assimp and recompile libassimp.so afterwards, not very flexible though.

**Comment by smalcom** [comment]
Agreed. As my example its a tessellation factor for X3D importer.

**Comment by kimkulling** [comment]
This is already possible in c/c++, right? We only need to export them to python, right?

**Comment by tportenier** [comment]
Yes, the c++ API provides the desired functionality!

**Comment by mvidiassov** [comment]
> This is already possible in c/c++, right? We only need to export them to python, right?

It'd be nice to export configuration properties of importer to command-line interface of the assimp utility.

**Comment by kimkulling** [comment]
Already there.
