### ISSUE TITLE
OBJ: vertex index out of range

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#1047]
Hi,

I tried to load this model: https://storage.googleapis.com/assimp_model_error/obj_vertex_out_of_bounds.obj

But it is complaining that "OBJ: vertex index out of range". But I could still open the file in MeshLab. Is it possible in some way "ignoring" the error and try the best to read it? Even though you maybe loose some vertices.

**Comment by smalcom** [comment]
Can you show import-flags? With git-version all is ok, log below

> [16:11:34] Info,  T0: Load /home/smalcom/obj_vertex_out_of_bounds.obj
> [16:11:34] Debug, T0: Assimp 3.3.190950135 amd64 gcc debug shared singlethreaded
> [16:11:34] Info,  T0: Found a matching importer for this file format: Wavefront Object Importer.
> [16:11:34] Info,  T0: Import root directory is '/home/smalcom/'
> 
> [16:11:34] Error, T0: OBJ: Unable to locate material file Struct.mtl
> [16:11:34] Info,  T0: OBJ: Opening fallback material file /home/smalcom/obj_vertex_out_of_bounds.mtl
> [16:11:34] Error, T0: OBJ: Unable to locate fallback material file Struct.mtl
> [16:11:34] Error, T0: OBJ: failed to locate material color0_1, skipping
> [16:11:34] Error, T0: OBJ: failed to locate material color1_1, skipping
> [16:11:34] Error, T0: OBJ: failed to locate material color2_1, skipping
> [16:11:34] Error, T0: OBJ: failed to locate material color3_1, skipping
> 
> [16:11:34] Debug, T0: ValidateDataStructureProcess begin
> [16:11:34] Debug, T0: ValidateDataStructureProcess end
> [16:11:34] Info,  T0: Entering post processing pipeline
> [16:11:34] Debug, T0: FlipUVsProcess begin
> [16:11:34] Debug, T0: FlipUVsProcess finished
> [16:11:34] Debug, T0: GenUVCoordsProcess begin
> [16:11:34] Debug, T0: GenUVCoordsProcess finished
> [16:11:34] Debug, T0: TransformUVCoordsProcess begin
> [16:11:34] Debug, T0: TransformUVCoordsProcess finished
> [16:11:34] Debug, T0: TriangulateProcess begin
> [16:11:34] Debug, T0: TriangulateProcess finished. There was nothing to be done.
> [16:11:34] Debug, T0: GenFaceNormalsProcess begin
> [16:11:34] Info,  T0: GenFaceNormalsProcess finished. Face normals have been calculated
> [16:11:34] Debug, T0: Generate spatially-sorted vertex cache
> [16:11:34] Info,  T0: Leaving post processing pipeline
> 
> [16:11:34] Info,  T0: Import done: /home/smalcom/obj_vertex_out_of_bounds.obj
> [16:11:34] Info,  T0: No textures for import.
> [16:11:34] Info,  T0: Scene is ready for rendering.
![oob](https://cloud.githubusercontent.com/assets/19540675/19722638/4bbb36a0-9b80-11e6-9c68-63285011fb76.png)

**Comment by fredrik955** [comment]
Here you go:

```c++
importer.SetPropertyFloat(AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE, 45.0f);
importer.SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_LINE | aiPrimitiveType_POINT);
scene = importer.ReadFile(
	filename,
	aiProcess_Triangulate           |
	aiProcess_GenUVCoords           |
	aiProcess_GenSmoothNormals      |
	aiProcess_OptimizeMeshes        |
	aiProcess_OptimizeGraph         |
	aiProcess_FixInfacingNormals    |
	aiProcess_JoinIdenticalVertices |
	aiProcess_SortByPType
);
```

**Comment by johnmaf** [comment]
Looks like the model uses homogeneous coordinates, which wasn't supported until [c3ebdc5](https://github.com/assimp/assimp/commit/c3ebdc56de425a63e7e011272ccf72e4fbd9a152)

If you pull the latest mater it should work fine.

**Comment by kimkulling** [comment]
I have checked this, this issue was fixed already. So enjoy it :-).
