### ISSUE TITLE
Compilation for Android in OSX

### ISSUE THREAD

**Issue by andrew-k-21-12** [assimp/assimp#1049]
In order to compile a library for Android (NDK 13) with NEON support (faster floating point operations) in OSX it's better to use command for cmake:

`cmake CMakeLists.txt -G 'Unix Makefiles' -DASSIMP_ANDROID_JNIIOSYSTEM=ON -DCMAKE_TOOLCHAIN_FILE=/SDK/android-sdk-macosx/cmake/3.6.3155560/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_NATIVE_API_LEVEL="android-23" -DANDROID_FORCE_ARM_BUILD=TRUE -DANDROID_NDK=/SDK/android-ndk-r13`

where `CMAKE_TOOLCHAIN_FILE` and `ANDROID_NDK` paths will be specific for your system.

We also have to add `-fexceptions` `-frtti` flags for compilation to avoid errors and make corresponding replacements:

```
 static bool match4(StreamReaderAny& stream, const char* string) {
     ai_assert( nullptr != string );
     char tmp[] = {
-        (stream).GetI1(),
-        (stream).GetI1(),
-        (stream).GetI1(),
-        (stream).GetI1()
+        (char)(stream).GetI1(),
+        (char)(stream).GetI1(),
+        (char)(stream).GetI1(),
+        (char)(stream).GetI1()
     };
     return (tmp[0]==string[0] && tmp[1]==string[1] && tmp[2]==string[2] && tmp[3]==string[3]);
 }
```

```
stream.SetCurrentPos(current.start + current.size);

     const char tmp[] = {
-        stream.GetI1(),
-        stream.GetI1(),
-        stream.GetI1(),
-        stream.GetI1()
+        (const char)stream.GetI1(),
+        (const char)stream.GetI1(),
+        (const char)stream.GetI1(),
+        (const char)stream.GetI1()
     };
     current.id = std::string(tmp,tmp[3]?4:tmp[2]?3:tmp[1]?2:1);
```

in a `code/BlenderDNA.cpp` file and

```
TEST_F( utDefaultIOStream, FileSizeTest ) {
     char buffer[ L_tmpnam ];
     tmpnam( buffer );
-    std::FILE *fs( std::fopen( buffer, "w+" ) );
-    size_t written( std::fwrite( buffer, 1, sizeof( char ) * L_tmpnam, fs ) );
-    std::fflush( fs );
+    FILE *fs( fopen( buffer, "w+" ) );
+    size_t written( fwrite( buffer, 1, sizeof( char ) * L_tmpnam, fs ) );
+    fflush( fs );

     TestDefaultIOStream myStream( fs, buffer );
     size_t size = myStream.FileSize();
```

in `test/unit/utDefaultIOStream.cpp`

And we also can make building faster with:

`make -j4`

**Comment by kimkulling** [comment]
Should be fix already.
