### ISSUE TITLE
Materials "Material.001" and "Material_001" are not distinguished when importing a collada file

### ISSUE THREAD

**Issue by Ekuju** [assimp/assimp#1050]
I have a scene with two materials, Material.001 and Material_001 on two different objects. ASSIMP seems to override one with the other.

Example of the set up:
http://imgur.com/a/aU9P4

**Comment by kimkulling** [comment]
Hu, Not good. Thanks for the report.

Trent Davies <notifications@github.com> schrieb am Sa., 29. Okt. 2016,
10:43:

**Comment by gorunovanton** [comment]
#2690

**Comment by TGEnigma** [comment]
Actually, this should have been fixed by #1821

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/1821
