### ISSUE TITLE
error LNK2001 with x64 static library

### ISSUE THREAD

**Issue by Mikez2015** [assimp/assimp#1051]
I used CMake 3.7.0-rc1, VS 2015 (no errors with dynamic library, errors only with static library)

**Code:**
const aiScene* scene = NULL;
Assimp::Importer importer;
scene = importer.ReadFile(pFile, aiProcessPreset_TargetRealtime_Quality);

**Errors:**
assimp_64.lib(FBXParser.obj) : error LNK2001: unresolved external symbol "inflate"
1>assimp_64.lib(BlenderLoader.obj) : error LNK2001: unresolved external symbol "inflate"
1>assimp_64.lib(XGLLoader.obj) : error LNK2001: unresolved external symbol "inflate"
1>assimp_64.lib(XFileParser.obj) : error LNK2001: unresolved external symbol "inflate"
1>assimp_64.lib(unzip.obj) : error LNK2001: unresolved external symbol "inflate"
1>assimp_64.lib(FBXParser.obj) : error LNK2001: unresolved external symbol "inflateEnd"
1>assimp_64.lib(BlenderLoader.obj) : error LNK2001: unresolved external symbol "inflateEnd"
1>assimp_64.lib(XGLLoader.obj) : error LNK2001: unresolved external symbol "inflateEnd"
1>assimp_64.lib(XFileParser.obj) : error LNK2001: unresolved external symbol "inflateEnd"
1>assimp_64.lib(unzip.obj) : error LNK2001: unresolved external symbol "inflateEnd"
1>assimp_64.lib(BlenderLoader.obj) : error LNK2001: unresolved external symbol "inflateInit2_"
1>assimp_64.lib(XGLLoader.obj) : error LNK2001: unresolved external symbol "inflateInit2_"
1>assimp_64.lib(XFileParser.obj) : error LNK2001: unresolved external symbol "inflateInit2_"
1>assimp_64.lib(unzip.obj) : error LNK2001: unresolved external symbol "inflateInit2_"
1>assimp_64.lib(AssbinLoader.obj) : error LNK2001: unresolved external symbol "uncompress"
1>assimp_64.lib(XFileParser.obj) : error LNK2001: unresolved external symbol "inflateSetDictionary"
1>assimp_64.lib(XFileParser.obj) : error LNK2001: unresolved external symbol "inflateReset"
1>assimp_64.lib(unzip.obj) : error LNK2001: unresolved external symbol "crc32"
1>assimp_64.lib(unzip.obj) : error LNK2001: unresolved external symbol "get_crc_table"
1>assimp_64.lib(FBXParser.obj) : error LNK2001: unresolved external symbol "inflateInit_"

**Comment by Mikez2015** [comment]
Ops, sorry, I forgot add zlibstatic.lib

**Comment by kimkulling** [comment]
No Problem 😁

Mikez2015 <notifications@github.com> schrieb am Mi., 2. Nov. 2016, 04:38:
