### ISSUE TITLE
obj parsing performance regression

### ISSUE THREAD

**Issue by jaredmulconry** [assimp/assimp#1059]
The changes merged into master as at commit 1aafe6287c8c001f7514fa541dac22e0281bec82 has resulted in a substantial slowdown of obj parsing.
An obj version of the Stanford Armadillo used to take roughly 5 seconds to import in debug mode with minimal processing flags given. After the recent changes, I haven't been able to leave my application running long enough for the importing of this model to complete.

**Comment by jaredmulconry** [comment]
Reverting back to commit 54c5acd02dcfeaba596713b32419f266aa6c5829 addresses the issue for me for now.

**Comment by jaredmulconry** [comment]
In release mode, the model takes 3 minutes and 30 seconds to import. It used to take roughly 500 milliseconds.

**Comment by jaredmulconry** [comment]
The performance issue seems to stem from the IOStreamBuffer<T>::getNextLine function calling memset for every line of the obj file.

**Comment by kimkulling** [comment]
OK, see it as well. WIll try to fix it. Thanks for the report!

**Comment by kimkulling** [comment]
Closed by 1d08c9e2e2b7cff9ed6a9b9703997a1986f73aa4
