### ISSUE TITLE
Add a docker file

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1063]
To make the usage of assimp much easier we shall provide a dockerfile to using it.

**Comment by Cgettys** [comment]
@kimkulling what did you have in mind for this? Sorry for all the comments, I'm going thru old issues and seeing if there's stuff that can be closed out/that I can knock out quickly. I've done some substantial work with docker in the past.

I assume the goal would be to provide a Linux Docker container with everything preinstalled? They're supported on both Windows and Linux iirc.

A quick search reveals that people have definitely done it in the past, though I'm not sure what exactly they did with it.
https://hub.docker.com/search/?q=assimp&type=image

**Comment by jsdtaylor** [comment]
I think I'd be great to have an "authorized" dockerfile that illustrates how it should be provisioned. I'm keen on using it too :)

**Comment by dylankenneally** [comment]
Whilst not part of _this_ repo, a Docker container is available at https://github.com/dylankenneally/assimp-docker

```bash
docker pull dylankenneally/assimp:latest
docker run --rm -v "$PWD":/usr/assets -w /usr/assets dylankenneally/assimp:latest assimp <comand>
```

To edit the container, fork https://github.com/dylankenneally/assimp-docker

@kimkulling - do you want me to add this to the assimp repo and send a PR? See https://github.com/dylankenneally/assimp-docker/blob/master/build.sh for content - it's pretty small

**Comment by kimkulling** [comment]
This would be really great! Thanks a lot for the offer.
