### ISSUE TITLE
Malformed version number on Mac OSX

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#107]
When building assimp we get the following error on Mac OSX 10.8.
Linking CXX shared library ../lib/libassimp.dylib
ld: malformed 64-bit a.b.c.d.e version number: 3.0.1264
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Changing the SV revision number in the build script from 1264 to 255 solves the problem.

see: https://sourceforge.net/p/assimp/bugs/112/

**Comment by epicstar** [comment]
The issue still happens to this day... If any of a.b.c.d.e is > 1023, the linker will fail. I'm suspecting that clang only accepts these values between 0 and 2^10 but I don't see any documentation referring to this...

**Comment by peteranny** [comment]
According to the ![source code](https://opensource.apple.com/source/ld64/ld64-274.2/src/ld/Options.cpp.auto.html), the error `"malformed 64-bit a.b.c.d.e version number: %s"` arises from `parseVersionNumber64` that gets called when `-dylib_current_version` or `-current_version` is provided in the compiler arguments.

So I tried opening my `.xcodeproj` file and deleting `CURRENT_PROJECT_VERSION` and `DYLIB_CURRENT_VERSION` manually. Compilation succeeded ✔️
