### ISSUE TITLE
Fail to build: 'assert' identifier not found

### ISSUE THREAD

**Issue by wmatyjewicz** [assimp/assimp#1076]
I am trying to build 1939aca31c3db on Windows, but I am getting errors about `assert` being undefined in `SIBImporter.cpp` and `TriangulateProcess.cpp`.

Shouldn't `assert` be replaced with `ai_assert`?

**Comment by kimkulling** [comment]
Right. I found some places where the false assert were in use and fixed that places. Unfortunately I didn't see that compile errors. Thanks a lot for the report. I will take care.

Kim
