### ISSUE TITLE
[Feature Request] add unit option to assetimporter

### ISSUE THREAD

**Issue by yushli** [assimp/assimp#1078]
E.g., some models are exported with centimeter as unit instead of meter. When importing into the game engine, we need to scale down the model. It may be convenient if a unit option can be added into assetimporter to support this.

**Comment by smalcom** [comment]
You can provide this information using metadata.

**Comment by yushli** [comment]
How can this be done? Can you point me to the document/tutorial? Thank you.

**Comment by smalcom** [comment]
Adding metadata with string type:

```
aiString cm_name("cm");
pSceneNode.mMetaData = aiMetadata::Alloc( 1 );// 1 - count of metadata values
pSceneNode.mMetaData->Set(0, "unit", cm_name);// 0 - index of metadata value.
```

In reader do in reverse order: read count of metadata in node and read them.

**Comment by yushli** [comment]
This may not be what I mean. The situation is as follows: A model is exported to a FBX file, with unit as centimeter. for example, a cube of 1 meter will be exported as 100; When assetimporter is used to load this FBX file. assetimporter should then convert 100 back to 1.

**Comment by smalcom** [comment]
Don't forget about precision. You can't just convert all coordinates to one unit. I mean - you can, but must not, because you can lost data. Thats why i proposed to use metadata. All this "things" must be ruled by reader not by library like Assimp, which is just tool for loading assets. And how to interpret and show assets must decide reader.

**Comment by kimkulling** [comment]
Until now there is no tutorial how to use Metadata with alloc. But I guess I will write a blogpost regarding this.
