### ISSUE TITLE
COLLADA export texture mapping

### ISSUE THREAD

**Issue by agerrius** [assimp/assimp#1084]
When exporting an object to COLLADA and then importing it back with Assimp the texture mappings are corrupted. I tested it with a simple COLLADA objects and the command line tool. Open3DMod does show the texture correctly on the original model, but not on the one that Assimp wrote.

I found at that it is related to this line in the COLLADA file. If I remove the TEXCOORD input in the polylist segment below the texture mapping is correct.

```
<polylist count="6" material="defaultMaterial">
          <input offset="0" semantic="VERTEX" source="#meshId0-vertices" />
          <input offset="0" semantic="TEXCOORD" source="#meshId0-tex0" set="0" />
          <vcount>4 4 4 4 4 4 </vcount>
          <p>0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 </p>
</polylist>

```
This extra TEXCOORD input was introduced in the following commit: https://github.com/assimp/assimp/commit/ad55e769bfc87d684b15ac3804c4d70775b9a9a7

I don't know the COLLADA format well enough to know if the output COLLADA file is incorrect or if the COLLADA reader does not handle this situation well.

**Comment by agerrius** [comment]
Test object (before and after included):
[dice.zip](https://github.com/assimp/assimp/files/614730/dice.zip)

Initial object in Open3DMod
![image2016-11-27 1500 44 404](https://cloud.githubusercontent.com/assets/23453644/20648872/9b0ffcb8-b4b2-11e6-83cd-c933fac5de24.jpg)

Exported object in Open3DMod
![image2016-11-27 1500 47 787](https://cloud.githubusercontent.com/assets/23453644/20648871/9b0f812a-b4b2-11e6-9c53-a6e68a073a69.jpg)

**Comment by Kvalme** [comment]
The problem seems to be in Assimp importer. 
Got same issue but found that applications that do not use assimp for collada input reads file correctly.
In my case:
Import scene to assimp from dae made in blender - ok
Export scene to dae using assimp.
In blender I see correct uv map.
In assimp I see corrupted uv map.

**Comment by agerrius** [comment]
Sorry for the delay, but the solution works fine for me as well. I just tested with a DLL build from the latest source and the issue with exporting and then importing COLLADA is solved. So this issue is fixed for me.
