### ISSUE TITLE
emscriptening this thing did not quite work

### ISSUE THREAD

**Issue by makc** [assimp/assimp#1088]
ok so I have [manually emscriptened this thing](https://github.com/makc/assimp2json) but half of models from assimp repo do not work. if anyone could come along and tell me why...

**Comment by turol** [comment]
Add -sSAFE_HEAP=1 to emscripten link command and see what you get.

**Comment by makc** [comment]
@turol thanks, that gives me a message like:
> abort("alignment fault") at jsStackTrace@file:///Users/makc/test/assimp.js:1:24064
> stackTrace@file:///Users/makc/test/assimp.js:1:24247
> abort@file:///Users/makc/test/assimp.js:18:6931
> alignfault@file:///Users/makc/test/assimp.js:1:8664
> $c@file:///Users/makc/test/assimp.js:8:1
> ...
when trying to parse 3ds file. which is quite useless, in terms of understanding how 3ds loader is different from obj loader, for example, that works perfectly.

**Comment by makc** [comment]
@turol I have only now noticed your comment on #461 saying
> Many places in the code cast char pointers to other types like int or short which have higher alignment requirements. This WILL break on emscripten

does it mean that we can't really have assimp emscriptened without heavily modifying assimp code?

**Comment by kimkulling** [comment]
Not all loaders are doing this. So when loading obj or stl you should have
not so much issues.

We can run the regression test suite for assimp for enscripten to test your
build output.

Kim

And thanks to you guys for the very useful input. I really appreciate this
very much!!!

makc <notifications@github.com> schrieb am Di., 29. Nov. 2016, 22:48:

**Comment by makc** [comment]
btw, my build uses assimp from 2 years ago (which is linked from assimp2json repo), so some one of you c++ people needs to write better build script. maybe something like [this](https://github.com/Shervanator/Engine/blob/master/scripts/cmake-emscripten.sh).

**Comment by kimkulling** [comment]
Never used enscripten. I would be really happy if you could prepare a
prototype for cmake.
Of course we can work on this together if this is ok for you. I have only
one rule: let discuss in a polite way. Thanks 😀😀😀

makc <notifications@github.com> schrieb am Di., 29. Nov. 2016, 23:05:

**Comment by makc** [comment]
I would do it, but I have no idea how to use cmake, or even install it. I downloaded one from https://cmake.org/download/ but it was some gui and not command line tool. As for emcc, it says in its docs that it accepts same args that gcc, so I just gave it a list of files and include directories, until it worked. So I am really not a right person to write build scripts.

**Comment by makc** [comment]
following [the hint from emscripten author](https://github.com/kripken/emscripten/issues/4760), I tried yet another way to compile this. it did not work, but at least I've got cmake working )

**Comment by kimkulling** [comment]
I will try to enable enscripten in our build.

**Comment by makc** [comment]
Ok, so after some further help from emscripten guy web assembly build appears to be working. However, I am running into the problem with blender parser: it tries to dump stuff into some file, I assume, because of
```c++
#if defined(_DEBUG) || ! defined(NDEBUG)
#	define ASSIMP_BUILD_DEBUG
#endif
...
#ifdef ASSIMP_BUILD_DEBUG
#	define ASSIMP_BUILD_BLENDER_DEBUG
#endif
...
#ifdef ASSIMP_BUILD_BLENDER_DEBUG
	dna.DumpToFile();
#endif
```
how do I correctly prevent this?

**Comment by kimkulling** [comment]
Let's use #1133 for tracing this.
