### ISSUE TITLE
Confused regarding how bones information is stored hierarchically

### ISSUE THREAD

**Issue by TrentWDB** [assimp/assimp#1093]
I'm attempting to import animation in JAssimp and I noticed that all the necessary animation information seems to be there (despite it saying online that JAssimp does not yet support animation.) However, I'm confused about how you can determine the hierarchy of bones. There are two things I'm questioning:

1. I noticed that all the bones for each mesh are simply returned in an array that has no hierarchical structure. Bones typically are expected to be in a tree where the transformation of each bone accumulates into its children, etc. Does this imply that the transformations have already been applied to each bone, meaning that the hierarchy is no longer relevant?

2. I noticed that some bones that are are referenced by the "AiNodeAnimation" are not in the "AiBone" list in any of the meshes. I've also noticed that the bones in question here pose no value to the program - they are not moved or rotated or anything, making them essentially useless. Are these "useless" bones just disregarded? If they are disregarded, what happens to the vertices that they are weighted to and that are affected by these bones - is this weight transferred into the parent bone (meaning I basically don't have to worry about it)?

Any guidance here would be appreciated, thanks!

**Comment by Ithamar** [comment]
I you're still wondering, I found http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html quite helpful in figuring out similar issues with bones & assimp.

**Comment by kimkulling** [comment]
Seems to be outdated. I will close this one.
