### ISSUE TITLE
Improve DXF Loading

### ISSUE THREAD

**Issue by daseyb** [assimp/assimp#1095]
Hi everyone,

I'm working as a research assistant at https://www.graphics.rwth-aachen.de/

We would like to use assimp to load DXF files, but the current supported feature set is very limited.

Is anyone working on this already? If not, would you accept pull requests that improve the DXF loader?

Cheers, Dario

**Comment by kimkulling** [comment]
We would be very happy to get pull-requests's 😀.

With best regards,
Kim Kulling

Dario Seyb <notifications@github.com> schrieb am Di., 6. Dez. 2016, 13:02:

**Comment by kimkulling** [comment]
At the moment there is not so much activity at this loader. It would be great to get some feedback what is missing as well.

**Comment by daseyb** [comment]
Right now the loader only supports the polyline object type. We would need other shapes as well. The way I would implement non-point based shapes is by approximating them by polylines.

It might take a while for me to get the changes to a production ready state, but I wanted to check in and see if anyone else is working on this :)

I'll notify you once I have something to review!

**Comment by kimkulling** [comment]
I created a test suite in our unittest suite for your work. Feel free to add some more tests for your work.
