### ISSUE TITLE
OBJ always exports material

### ISSUE THREAD

**Issue by johnmaf** [assimp/assimp#1096]
When converting to OBJ, a default material is always used, even when the original file had no such material. Since the OBJ format doesn't require materials, this is arguably incorrect behaviour.

Unfortunately changing this could cause problems for anyone who's currently assuming that OBJ export always produces a `.mtl` file, and could confuse people who are used to seeing the default material.

Is there any interest in removing this behaviour?

**Comment by kimkulling** [comment]
We could add a config switch for the importer / exporter, if anyone is interested?

**Comment by thomas-lemaire** [comment]
I added this issue #1515 and just found this one.

the .mtl file is explicitly referenced in the .obj file, so people should not expect to have always a .mtl, only if it appears in the .obj
