### ISSUE TITLE
assimp for iOS

### ISSUE THREAD

**Issue by danielZhang0601** [assimp/assimp#1101]
when i use this commit : a3a1c82380f46376787eb3351921ab29c703148a

cd ./port/iOS
./build.sh --stdlib=libc++ --archs="armv7 arm64 i386"

and then i got this error:
cmake version 3.7.1

assimp/code/AMFImporter.hpp:144:23: error: invalid use of non-static data member 'achFormatHint'
                decltype(aiTexture::achFormatHint) FormatHint;

how can i make this right way?

**Comment by kimkulling** [comment]
Could you please post your compiler version?

**Comment by danielZhang0601** [comment]
Xcode Version: Version 8.1 (8B62)

**Comment by kimkulling** [comment]
Do you know if c++11 is enabled? The decltype declaration creates the issue ( I have a workaround, so I am just curious) ?
