### ISSUE TITLE
OBJ: File name of the material is absent

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#1111]
Hi assimp,

I tried the new Assimp version (Version 3.3 -debug -shared -st (GIT commit b1e89e3)) and tried to open this file (try the assimp CLI, assimp info [file]): 
https://storage.googleapis.com/assimp_model_error/valve.obj

And got the following error: File name of the material is absent.

I know that Assimp managed to open this file in earlier versions. Is it possible to give this as a warning and not as an error and continue the import process?

**Comment by kimkulling** [comment]
Sure, thanks for the report!

fredrik955 <notifications@github.com> schrieb am Mi., 14. Dez. 2016, 15:20:
