### ISSUE TITLE
FBX transformation hierarchy wrong

### ISSUE THREAD

**Issue by Nillmo** [assimp/assimp#1112]
Hi everyone,

first of all, thanks for this great library and all the work you put into making it.
We use Assimp to load user provided content, therefore we have a wide variety of input formats and don't have much control over the input files. Most of our test data is loading fine with Assimp 3.3.1, I only have a problem with one FBX file, where the translation of some child meshes is shiftet.
The same model in Collada format loads correctly. I've attached both models in the zip file below.

[crankshaft.zip](https://github.com/assimp/assimp/files/654032/crankshaft.zip)

**Comment by kimkulling** [comment]
Thanks a lot for the report. Hopefully I will find some time to take a look onto it.

**Comment by Eirenliel** [comment]
This model have GeometricTranslation, which should not be inherited by child nodes. Assimp does not support it now.

(I can't fix it myself, cause I don't actually write on C++, but I ate a dog in FBX...)

**Comment by kimkulling** [comment]
Thanks a lot for the hint . At the moment I am trying to understand the code.

**Comment by rickomax** [comment]
Possibily related to:
#1127

**Comment by mesilliac** [comment]
Should be fixed by #1806 (i at least confirmed that converting to OBJ gives something that looks correct)
