### ISSUE TITLE
Python interface export error

### ISSUE THREAD

**Issue by ShangxuanWu** [assimp/assimp#1118]
Hi everyone, I have a problem. I can read FBX file using the python interface, but when I tried to export it to OBJ format, it always raise AssimpError('Could not export scene!'). Is there any hint? Great thanks!

**Comment by kimkulling** [comment]
Hi,

do you see any issues before this message? This seems to be some kind of import errors. When there is no model after the import, you cannot export it to another format.

**Comment by kimkulling** [comment]
Please reopen if this issue is still there.
