### ISSUE TITLE
Assimp handles FBX Pre Rotation and Post Rotation wrong

### ISSUE THREAD

**Issue by Eirenliel** [assimp/assimp#1120]
Pre Rotation and Post Rotation _always_ have XYZ rotation order. I don't know why no one knows it, even Blender have same error and I had. But it is stated in FBX documentation and I thoroughly tested it in my importer.

(I can't fix it myself, cause I don't actually write on C++, but I ate a dog in FBX...)

**Comment by SizzlingCalamari** [comment]
Hey @Eirenliel, can you provide a link to docs where it says that pre and post rotation always use XYZ rotation order?

**Comment by Eirenliel** [comment]
http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm

Here in the notes it says "The R matrix takes into account the rotation order". You can think it as "all Rs", but it is easy to disprove: you need to create a model with joint orients something like "90 -90 90" and see the difference.

**Comment by kimkulling** [comment]
Just started to look onto it.

**Comment by mlfarrell** [comment]
I've been struck with this issue today as well.

**Comment by mlfarrell** [comment]
Nevermind, my issue was unrelated.  The postRotation angle is negated for some reason.  When negating it or inverting the post rotation transforms, it fixes my issue.

**Comment by rickomax** [comment]
I've fixed this issue and can confirm @Eirenliel solution works!
I'll make a pull-request later.

**Comment by kimkulling** [comment]
Ok, I will merge them into assimp. Thanks for figuring this out.
