### ISSUE TITLE
Wavefront OBJ and normal maps

### ISSUE THREAD

**Issue by agerrius** [assimp/assimp#1121]
I have exported a model that uses normal maps to the Wavefront OBJ format, however if I import it back using assimp the texture is lost. Looking in the MTL file I do see the texture as map_bump, but that texture seems not to be imported. If I change map_bump to map_Kn it works fine.

What is the intended difference between the bump and normal maps? I'm using the .NET wrapper and at least in there I can only access normal maps in a material and no bump maps.

**Comment by kimkulling** [comment]
Official answer: I do not have a clue. I will figure it out...

Arno Gerretsen <notifications@github.com> schrieb am Sa., 24. Dez. 2016,
21:15:

**Comment by kimkulling** [comment]
The bump-mapping just descripes data, you can find how to implement normal mapping with obj here: http://computergraphicsguide.blogspot.de/2015/08/wavefront-obj-file-format-and-normal.html.

Kimmi

**Comment by agerrius** [comment]
I still think it's a bug however. If I use assimp to save an obj file that has a normal map assigned,  after importing the object with assimp again the normal map is lost. So the importer and exporter don't use the obj information consistently. I'll try to figure how I can improve this.

**Comment by kimkulling** [comment]
So do you have a model, which can be used to reproduce this issue? If yes: would be great to get it and to solve it.

**Comment by agerrius** [comment]
What I did now is create a model in code, export that and then load it again. So that means I can't really provide a model to test with, I only have some C# code.

I'll see if I can reproduce it the other way around as well (load OBJ model and then save again). That would make testing easier I think.

**Comment by No0n3Left** [comment]
Wait, so the problem is it exports normal maps as bump maps? Or that you think it should use map_bump as a aiTextureType_NORMALS?

**Comment by agerrius** [comment]
I'm not sure yet which of the two. At least I see that exporting as Wavefront OBJ and the importing again loses the normal/bump texture. So the exporter and the importer don't process them the same. 

Sorry, I still promised to find a sample, but didn't have the time for that yet.

**Comment by topblast** [comment]
I was having a similar issue, this seem to explain/resolve it #430

**Comment by Keimoj** [comment]
Depending of the way you set up the material in 3D software (for example in my case 3Ds MAX) you have to specify for the normla/bump slot if the bitmap you're using is a height or bump. And it might require an additional map/node.

I had to set my bump slot map to be "normal bump"
![Screenshot_2](https://user-images.githubusercontent.com/10116025/90863567-efbe1480-e397-11ea-8533-07b8680c5e11.png)

Then set my normal map texture to the normal slot and untick the additional bump
![Screenshot_3](https://user-images.githubusercontent.com/10116025/90863584-f8aee600-e397-11ea-9031-f442aace4b07.png)

Not sure if this helps as the mesh is generated via code for you, but this way I got it to import as normal instead height/bump
