### ISSUE TITLE
build with m$ visual studio comunity 2015

### ISSUE THREAD

**Issue by arris69** [assimp/assimp#1122]
build fails with vc 2015.
stuff from https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/
should be implemented

**Comment by kimkulling** [comment]
OK, thanks for the report!

**Comment by arris69** [comment]
for completion, cmake is here not able to generate the solution files for "Visual Studio 14 2015 Win64" so its generated for vs12 and then autoconverted by Visual Studio 2015.

**Comment by kimkulling** [comment]
Which version of cmake do you use? I am using cmake VS2015 for Windows 10 and it works perfect!

**Comment by arris69** [comment]
originally had 3.0.1 but updated to 3.4, 3.7 and 3.7.1 (finally cmake version 3.7.20161227-gf96cd)
```
cmake -G "Visual Studio 14 2015 Win64" ../..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:40 (PROJECT):
  No CMAKE_C_COMPILER could be found.
```

**Comment by kimkulling** [comment]
Just try to use 
`cmake --debug-output CMakeLists.txt `
without any VS-specification and post the output

**Comment by kimkulling** [comment]
OK I guess I understand the bug: you need to install the c++ support for vs2015 in the install process. You cando this afterwards as well.
