### ISSUE TITLE
how to load(render) 3d models .ply files from urls in my android app using this library? 

### ISSUE THREAD

**Issue by jagadish482** [assimp/assimp#1124]
i have below files of this library. can you help me how to use this library for loading 3d models in android app.

![screen shot 2016-12-27 at 11 47 31 am](https://cloud.githubusercontent.com/assets/23214629/21492643/6ad51484-cc2c-11e6-8417-24a9fcfdefb1.png)

**Comment by kimkulling** [comment]
You need to implement a http-IO-system to get the model via http.
