### ISSUE TITLE
PLY: Assertion failed + Bus error

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#1125]
Hi,

When I used the Assimp CLI to open this file: https://storage.googleapis.com/assimp_model_error/bus_error_1.ply
with the command `assimp info <file>` I got this error message:
```
assimp: .../assimp/code/ValidateDataStructure.cpp:92: void Assimp::ValidateDSProcess::ReportError(const char*, ...): Assertion `false' failed.
Aborted (core dumped)
```

When I tried to import it in my C++ program I got this error message:
```
Bus error (core dumped)
```

I am using this Assimp version: *Version 3.3 -debug -shared -st (GIT commit b1e89e3)*

**Comment by turol** [comment]
The actual error message from validation is:

```
Validation failed: aiMesh::mVertices[1] is referenced twice - second time by aiMesh::mFaces[2]::mIndices[2]
```

It's really a misfeature that the code "assert fails" before printing the error message. In any case, the failure is caused by this:
```
Invalid read of size 4
   at 0x89F1C6: Assimp::PLY::PropertyInstance::ParseValueBinary(char const*, char const**, Assimp::PLY::EDataType, Assimp::PLY::PropertyInstance::ValueUnion*, bool) (PlyParser.cpp:883)
   by 0x89EF69: Assimp::PLY::PropertyInstance::ParseInstanceBinary(char const*, char const**, Assimp::PLY::Property const*, Assimp::PLY::PropertyInstance*, bool) (PlyParser.cpp:765)
   by 0x89EC14: Assimp::PLY::ElementInstance::ParseInstanceBinary(char const*, char const**, Assimp::PLY::Element const*, Assimp::PLY::ElementInstance*, bool) (PlyParser.cpp:683)
   by 0x89E974: Assimp::PLY::ElementInstanceList::ParseInstanceListBinary(char const*, char const**, Assimp::PLY::Element const*, Assimp::PLY::ElementInstanceList*, bool) (PlyParser.cpp:626)
   by 0x89E58A: Assimp::PLY::DOM::ParseElementInstanceListsBinary(char const*, char const**, bool) (PlyParser.cpp:524)
   by 0x89E69A: Assimp::PLY::DOM::ParseInstanceBinary(char const*, Assimp::PLY::DOM*, bool) (PlyParser.cpp:544)
   by 0x896C3F: Assimp::PLYImporter::InternReadFile(std::string const&, aiScene*, Assimp::IOSystem*) (PlyLoader.cpp:186)
   by 0x49B86F: Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::string const&, Assimp::IOSystem*) (BaseImporter.cpp:95)
   by 0x7B1B17: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:674)
 Address 0x883bb31 is 0 bytes after a block of size 42,060,529 alloc'd
   at 0x4C29180: operator new(unsigned long) (vg_replace_malloc.c:324)
   by 0x44CAB9: __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) (new_allocator.h:104)
   by 0x44C635: std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) (alloc_traits.h:357)
   by 0x44BF51: std::_Vector_base<char, std::allocator<char> >::_M_allocate(unsigned long) (stl_vector.h:170)
   by 0x49FBAB: char* std::vector<char, std::allocator<char> >::_M_allocate_and_copy<std::move_iterator<char*> >(unsigned long, std::move_iterator<char*>, std::move_iterator<char*>) (stl_vector.h:1224)
   by 0x49F4AE: std::vector<char, std::allocator<char> >::reserve(unsigned long) (vector.tcc:75)
   by 0x49CF13: Assimp::BaseImporter::TextFileToBuffer(Assimp::IOStream*, std::vector<char, std::allocator<char> >&, Assimp::BaseImporter::TextFileMode) (BaseImporter.cpp:448)
   by 0x896973: Assimp::PLYImporter::InternReadFile(std::string const&, aiScene*, Assimp::IOSystem*) (PlyLoader.cpp:159)
   by 0x49B86F: Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::string const&, Assimp::IOSystem*) (BaseImporter.cpp:95)
   by 0x7B1B17: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:674)
```

It looks like the file is somehow malformed and the code doesn't check there's enough data in the buffer before reading. It then reads past the end, gets uninitialized bytes and writes junk into the data structure. This then fails validation. Also you can clearly see where the bus error is coming from, it's casting pointers to uint32_t* without caring about alignment which is UB. In practice this works on X86, are you running on ARM or something?

Just padding the file with some zero bytes might work around the issue, however the real fix is to check the buffer length and then use memcpy instead of nasty pointer casting tricks.

**Comment by fredrik955** [comment]
Hi @turol,

Thanks for confirming the problem, and for the report.
I am using a x64 machine.
I opened the file in Meshlab first and it worked there, so a problem with Assimp then.

**Comment by kimkulling** [comment]
I am not sure if a double referenced vertex should be handled as a really error? Any other opinions?

**Comment by m4c0** [comment]
The same issue happens with the classic Stanford Bunny: http://graphics.stanford.edu/pub/3Dscanrep/bunny.tar.gz

I'm using 4.0.1 from brew (OS X). Nonetheless, the "master" from GIT seems to work (although the validation code is commented out).

I don't know about the PLY file format (the reason for me to use "assimp" is to keep my ignorance over 3D file formats 😄), but it seems it would be better if the PLY importer duplicates, then a post-process de-dups. After all, removing the check for all imports may introduce bugs on other importers.

**Comment by turol** [comment]
Unable to reproduce with the Bunny model, the model provided by @fredrik955 is no longer available and I seem to have misplaced my local copy of it. This might have been fixed, please test latest.
