### ISSUE TITLE
elaborated type refers to a typedef

### ISSUE THREAD

**Issue by Whitecl4ws** [assimp/assimp#1126]
Hello, I am receiving the above error when trying to create a function that takes struct aiMatrix4x4* or any other aiStructs, I don't know why, I can my models properly, I just cannot make a function with the above struct as parameters for some odd reason, here's the code i question, I can even isolate it and it still gives me the error...

```
#include <math.h>
#include <assimp/cimport.h>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include <assimp/matrix4x4.h>

// A Bit Later in the Code

static inline void mat4x4_loadassimp(mat4x4 M, struct aiMatrix4x4* a);


```

I am using the latest assimp compiled from source... with C. Using clang as the compiler.

**Comment by kimkulling** [comment]
Which type? Does clang show you something?

**Comment by kimkulling** [comment]
And thanks for the report!

**Comment by Whitecl4ws** [comment]
Well, It doesn't really show me what type, just the above line, but I also know that if I do remove the struct tag, It tells me that I must use a struct to refer to aiMatrix4x4

I will explain my setup, I have a clang linter in my text editor, that linter basically compiles code on the fly in C or C++, and right now it's switching between these two errors:
Must Use a struct to refer to aiMatrix4x4
and
elaborated type refers to typedef
It does it for every type I try to make a function for...

**Comment by kimkulling** [comment]
I tried to reproduce your compile error with clang. I do not get the compiler warning ( for my testcase I defines an empty struct called mat4x4 ). Could you please provide a small example which reproduce the compiler error. Of course I can guess but getting it from your side will be faster I guess :-).

**Comment by kimkulling** [comment]
Any updates?

**Comment by Whitecl4ws** [comment]
Fixed it apparently it was a config error from my side, sorry for the bother

**Comment by kimkulling** [comment]
OK, thanks for the information. I will close the issue.
