### ISSUE TITLE
Do not build on Visual Studio

### ISSUE THREAD

**Issue by arkeon7** [assimp/assimp#1143]
Assimp do not build anymore on visual studio 2013 since the addChildren commit
https://github.com/assimp/assimp/commit/c6cceef867e12d6eaaa9becc722158807112216b

what it don't like in include\assimp\scene.h line 232 :
aiNode **tmp( new aiNode*[ mNumChildren ] );

correction:
aiNode **tmp = new aiNode*[ mNumChildren ];

Error	3	error C2059: syntax error : 'new' (assimp\code\AMFImporter_Postprocess.cpp)	assimp\include\assimp\scene.h	232	1	assimp

**Comment by smalcom** [comment]
step by step Assimp go to the future like using modern languages. In that case its a C++11. You can search discussion in past issues,
