### ISSUE TITLE
Assimp flipping y/z axis on different formats

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#115]
Hello,
I am using the ASSIMP command line tool to export from various file formats (.dae, .3ds, .ase, .obj) to .obj. After importing into my object viewer the shading seems to be inverted on the y/z axis. I can recreate this issue with all the described file formats except for .obj. If i export from max to obj (no matter which setting) import to assimp and export to obj again, the issue is gone. I had no look with .dae, .3ds, .ase file formats. After exporting those from assimp to o.obj i have the described problem.
I tried converting the .obj to utf8 and displayed them in webgl (using threejs) with the same effect.
http://threever.org/demos/problem/flippedaxis/utf8flippedaxis.html
Here are the links to the source files:
http://threever.org/demos/problem/flippedaxis/flippedaxis.zip

see: https://sourceforge.net/p/assimp/bugs/99/

**Comment by tkellogg** [comment]
This may be related: https://github.com/assimp/assimp/issues/849

**Comment by kimkulling** [comment]
Deprecated.
