### ISSUE TITLE
iOS assimp static library too big.

### ISSUE THREAD

**Issue by AntiMoron** [assimp/assimp#1151]
After run ```port/iOS/build.sh``` I found that the compiled binary is 141MB which is too big for iOS apps.

After all I just need few types of models to import.

Is there any way to specify the exact model type I want to compile ?

**Comment by kimkulling** [comment]
Yes, you can define this when runnning cmake via:

`cmake CMakeLists -DASSIMP_BUILD_NO_AC_IMPORTER`

for not including the AC importer. Or you can define the importers you don't wanna have by adding a define in the makefile as well. All importers/ exporters have a define to exclude them in the code.
