### ISSUE TITLE
Non-free piece of code in assimp license problem

### ISSUE THREAD

**Issue by smalcom** [assimp/assimp#1158]
Have asked to publish.

The non-free license problem has been spotted thanks to an automated check done in Debian, see:
https://lintian.debian.org/full/umlaeute@debian.org.html#assimp_3.3.1~dfsg-4
reports issues with:
contrib/ConvertUTF/ConvertUTF.c
contrib/rapidjson/license.txt
We should consider to re-implement those functions or to depend on similar implementations coming from external libraries, or in last resort remove the contribution?

Such license is not free, as:
1) it doesn't grant right to modify the code (which you did, so
technically you'd be in violation)
2) it is worded in a way that seems to limit the usage of the code,
only in works aimed at supporting the Unicode standard.

Now, apparently Unicode, Inc changed its standard licenses few years ago, and so if there is a new version of that code it might be possible to pull that version.

**Comment by kimkulling** [comment]
Thanks a lot for that report. I need to check.

**Comment by umlaeute** [comment]
this issue has now been raised as a release-critical bug in Debian (https://bugs.debian.org/#864729), which means that if it cannot be solved, assimp will be removed from Debian.

**Comment by kimkulling** [comment]
I am currently trying to solve it. The json lib will be replaced by a MIT-compliant lib and utf8: I don't have a clue. This is the last fix before 4.0.0.

**Comment by umlaeute** [comment]
the debian bug-report mentions:
> [...] a solution is to use libicu

i don't know whether this is a trivial fix or not (and how about cross-platform issues)

**Comment by kimkulling** [comment]
Great tipp, I will evaluate that. I guess updating to icu will be easy. Updating the gltf-sources to the new json libs is, as I mentioned before, currently ongoing.

**Comment by kimkulling** [comment]
Just checked https://github.com/JuliaLang/utf8proc , seems to be ok? ICU is really really big.

**Comment by umlaeute** [comment]
should be ok :-)

if possible, allow the use of system-wide installation of [libutf8proc](https://packages.debian.org/stretch/libutf8proc-dev)

**Comment by kimkulling** [comment]
see https://github.com/assimp/assimp/issues/1309

**Comment by kimkulling** [comment]
UTF8-lib is fixed, next step is to replace the json-lib. ( see c62429998e4529e7c42500570076430d07fc0894 )

**Comment by kimkulling** [comment]
Just recognized: rapidjson is licenced using MIT. Should be ok, right?

**Comment by kimkulling** [comment]
From the licence file:

If you have downloaded a copy of the RapidJSON binary from Tencent, please note that the RapidJSON binary is licensed under the MIT License.
If you have downloaded a copy of the RapidJSON source code from Tencent, please note that RapidJSON source code is licensed under the MIT License, except for the third-party components listed below which are subject to different license terms.  Your integration of RapidJSON into your own projects may require compliance with the MIT License, as well as the other licenses applicable to the third-party components included within RapidJSON. To avoid the problematic JSON license in your own projects, it's sufficient to exclude the bin/jsonchecker/ directory, as it's the only code under the JSON license.
A copy of the MIT License is included in this file.

**Comment by umlaeute** [comment]
yes. MIT should be fine.
