### ISSUE TITLE
mChannels crashes when animating

### ISSUE THREAD

**Issue by Tonyx97** [assimp/assimp#1163]
Hey! I'm using assimp for long time ago now and I can't figure out why it's crashing, I didn't make the model, a friend did but I don't know what exactly is the problem since I've been following [this](http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html) tutorial step by step but it crashes when animating the model in [this](https://gyazo.com/2a6c77cee37564fa6074ecc7f5adadb3) line, it says that mChannels was 0xDEADBEEF (a invalid address obviously). Not sure if the problem is in the model or the code, In my opinion the model is missing some data that makes the channel invalid but I'm not sure. Any ideas? [This](https://mega.nz/#!WsJTiKLQ!tqDgIiMSRRyve7947ODB9upeg3dcXRZVik1MqeA2PqE) is the model.
Thanks for read

**Comment by kimkulling** [comment]
Seems to be an issue in your code. I just tried the animation of the stick and it worked fine in our own model-viewer. 
Have you checked if the array is big enough? Or maybe the channel was released somehow. 0xDEADBEEF is a hint for that ( see http://stackoverflow.com/questions/5907614/0xdeadbeef-vs-null ).
