### ISSUE TITLE
problem with the generated bitangents

### ISSUE THREAD

**Issue by volcoma** [assimp/assimp#1165]
ok so when using the generated bitangents for normal mapping produces horrible seams like this:
![seam](https://cloud.githubusercontent.com/assets/1499411/22621305/42e6ac6e-eb29-11e6-8b00-7b3f97f5675b.png)
negating the bitangent seems to fix the issue.
![noseam](https://cloud.githubusercontent.com/assets/1499411/22621310/540279ec-eb29-11e6-81aa-200ad950bb17.png)

why should i need to negate the bitangent to get no seams. It maybe a bug in the calculation? can anyone elaborate?

**Comment by Sailsman63** [comment]
By 'negate' do you mean invert, ie. multiply by (-1)?

The model does seem to have a hard line down the center of the torso piece. (Possibly mirror-modeling, and the normal at the seam was not lined up.) But that alone does not explain the lighting issues.

Considering how the shadowing looks, I think that perhaps there is confusion in which side of the faces are in and which are out. This might perhaps go as far back as the input model. Does the input format store normals? They might be reversed. Does the format depend on winding order? Perhaps it's order is backwards from expected.

**Comment by volcoma** [comment]
yes i mean invert. It seems the normal map itself had the y component inverted which caused the issue. You can close this sory for wasting your time.

**Comment by kimkulling** [comment]
OK, thanks a lot for the update. I will close this one. Please reopen it if this is still an issue.
