### ISSUE TITLE
FBX import: Maya playback range error

### ISSUE THREAD

**Issue by leerichard42** [assimp/assimp#1166]
When importing the following animated FBX model from Maya 2016 for conversion to glTF:
https://www.dropbox.com/sh/t1quvfakr7mixva/AAAAtktFgFmmai0IOG7FkIYBa?dl=0

There is an import error "ERROR: Failed to load file: invalid vector\<T\> subscript" when the playback end time or animation end time do not align with the actual end time of the animation curve. 
The linked folder contains the .ma file, a working FBX which was exported from Maya with the entire playback range, and a broken FBX which was exported with a truncated playback range.

**Comment by kimkulling** [comment]
Ok, thanks a lot for the testfile and report. Hopefully we can help you.

leerichard42 <notifications@github.com> schrieb am Sa., 4. Feb. 2017, 22:16:

**Comment by bhaux** [comment]
Hi Kim -Thanks for this awesome tool and looking into this!

**Comment by kimkulling** [comment]
Good news, we fixed the issue.
