### ISSUE TITLE
PLY format color not working

### ISSUE THREAD

**Issue by williammc** [assimp/assimp#1167]
Assimp exports PLY file with float as vertex color property.
However, color is not rendered when visualized with MeshLab or CloudCompare.

Vertex color property should be **uchar** to comply with PLY format (http://paulbourke.net/dataformats/ply )

Attached files are two different PLY files for **uchar** color and **float** color.
Only **uchar** color file works.

[examples.zip](https://github.com/assimp/assimp/files/756984/examples.zip)

**Comment by kimkulling** [comment]
OK, thanks a lot for the hint. I will try to fix this one.
