### ISSUE TITLE
What's the correct way to associate node and lights / cameras

### ISSUE THREAD

**Issue by lamogui** [assimp/assimp#1168]
Hi 
I'm a newbie on assimp.
I want to import light and cameras from fbx and blend files. I saw the aiScene structure contains light and camera but in fbx you can have a complexe hierachy of nodes between root and node that contain the light.

In the documentation of aiLight.mPosition say:
```c++
 /** Position of the light source in space. Relative to the
     *  transformation of the node corresponding to the light.
     *
     *  The position is undefined for directional lights.
     */
```

But how I'm supposed to link my light to node because aiNode doesn't prove a mLights table

Thx by advance

**Comment by kimkulling** [comment]
You can use the name of the light to find the corresponding node with the transformation info.
