### ISSUE TITLE
the jassimp TexCoordBuffer  returned in AiMesh are uncorrect

### ISSUE THREAD

**Issue by yeguangrong** [assimp/assimp#1170]
the jassimp TexCoordBuffer  returned in AiMesh are uncorrect but positionBuffer and normalBuffer are normal

**Comment by kimkulling** [comment]
OK, thanks a lot. Any idea what went wrong?

**Comment by yeguangrong** [comment]
I have solved the problem.

**Comment by kimkulling** [comment]
Ok, then I will close the issue.
