### ISSUE TITLE
3.3.1 Qt example uses depreciated QGLWidget

### ISSUE THREAD

**Issue by DavidARivkin** [assimp/assimp#1171]
The Qt based example viewer uses the QGLWidget which has long been depreciated.
The QOpenGLWidget should be used instead. 
I believe that the just released Qt 5.8 no longer supports QGLWidget (Im usig 5.7 and get warnings)

**Comment by kimkulling** [comment]
You are right, a QML-based integration would be much more useful. Thanks for the hint!

**Comment by DavidARivkin** [comment]
No, C++ is the way to go for performance reasons, but it should use the
proper Class.
QML is going away and used only by novices.

David

**Comment by smalcom** [comment]
Agreed, QML use more resources.

**Comment by kimkulling** [comment]
No :-). QML is optimized for Embedded is highly used even for medical devices :-). 

And it brings an assimp-integration with it as well.

**Comment by DavidARivkin** [comment]
You mean for mobile, not medical.  You cant get FDA approval for QML apps.
I know, this is my industry.
QML is JavaScript+JSON and it is far from optimized.  It is about 10X
slower than C++ based examples, again based on real-world testing.
Just change the Widget to the correct one and things will be fine.
Do see the Qt documentation on the list of reasons why QGLWidget is not to
be used (may bugs) and why they switched to QOpenGLWidget.

David

**Comment by kimkulling** [comment]
Believe me, there are medical apps working on Qt-QML, I worked in this domain for 9 years. And there are webapps based on js and JSON out there as well, with a FDA-approval. For instance take a look here: https://www.qt.io/qt-in-medical/

And I worked a couple of years with QML. A comparison against QT_widgets was included. And when using QML for Multitouch-Screens ( widely in use for Automotive and Medical Devices ) QT-Widgets is not an option at all. QML wins. 

But yes, the internal Scenegraph is consuming more memory, that is right.

**Comment by DavidARivkin** [comment]
But those examples you give are not Medical Devices, they are just medical
apps.
QML is for non-professionals.
We used Multi-Touch with Qt-Widgets/C++ at Thermo-Fisher.  It worked just
fine and in fact better than QML.  We tested out both.
Its not just memory, its CPU cycles on ARM and Intel processors where QML
just fails to be viable.
I have been doing this for over 30 years.  I know well how to benchmark all
this.

David

**Comment by kimkulling** [comment]
You got me wrong, I worked for medical devices with QML :-). 

But we do not have to agree on that. If you are experienced in using Qt-Widgets: what do you think about preparing an up-to-adte example for us in a pull request? Would be great?

Kim

**Comment by DavidARivkin** [comment]
If I have time.  My priority is getting 3MF and AMF support in there, then
j3D.

David

**Comment by kimkulling** [comment]
Ok, I can help with our own 3MF-loader.

**Comment by DavidARivkin** [comment]
Also need to save, which should be easy since its very similar to the
ASSIMP format with nodes and meshes etc.

David

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/1981
