### ISSUE TITLE
Blender: Update dna to newest version

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1172]

**Comment by Rufus31415** [comment]
I am also facing this problem with new versions of Blender. Do you have a workaround or plan to support new versions ?

**Comment by kimkulling** [comment]
Investigation is ongoing.

Florent GIRAUD <notifications@github.com> schrieb am Fr., 1. Mai 2020,
19:44:

**Comment by ppinter1** [comment]
I also have this problem. I did some testing and it seems the last version of Blender that works with assimp 5.0.1 is v2.79 available [here](https://download.blender.org/release/Blender2.79/).

I lack the skill to fix this myself, so I can only thank you for your hard work - assimp is an amazing piece of work.

If I may suggest: Blender 2.83 is a LTS (Long Term Support) version. If assimp can be made to work with 2.83, that really should suffice for the forseeable future. Thanks again!

**Comment by BioAbnerUAD** [comment]
what version of blender should i be using?

**Comment by kimkulling** [comment]
Duplicate.

**Comment by jaredthirsk** [comment]
> Duplicate.

Duplicate of what issue?

**Comment by kimkulling** [comment]
Hi,

problem is that the author of the blender-support is not active any more. So I am currently trying to understand how the parsing of a blenderfile works. Gimme some more time to get a better understanding :-). Thanks!

We have a couple of open issues regarding to the belder siupport opened. At this moment I am using this one as the tracking issue:

https://github.com/assimp/assimp/issues/3316

**Comment by erasam** [comment]
I'm still having this issue with a Blender 3.1 file and CAD Assitant 1.6.1
