### ISSUE TITLE
FBX Importer: Incorrect mMaterialIndex value on each mesh

### ISSUE THREAD

**Issue by mutp** [assimp/assimp#1173]
Every mesh in a model has the same mMaterialIndex = 0. This means that I get the same material for every single mesh that is imported.

For example -
`aiMaterial* _material = scene->mMaterials[mesh->mMaterialIndex];
`
If i output to log `mesh->mMaterialIndex` it returns 0 for every single mesh. 

How do I solve this?

P.S: while importing the same model in open3mod, the meshes again are all black.

**Comment by kimkulling** [comment]
Maybe related to https://github.com/assimp/assimp/pull/1620

**Comment by kimkulling** [comment]
Already fixed by the related pull request.
