### ISSUE TITLE
glTF animation export: nodes missing skin and skeleton 

### ISSUE THREAD

**Issue by leerichard42** [assimp/assimp#1176]
When converting the animated handsWithPlane.fbx to handsWithPlane.gltf file found here: https://www.dropbox.com/sh/dvprkyj2ly782jn/AABLjwQLiOSWfr2VDdtlzjYCa?dl=0

The nodes for meshes 'mesh_0' through 'mesh_10' and 'mesh_12' through 'mesh_15' are missing a skin and skeleton, but the meshes have JOINT/WEIGHT attributes. The node 'Cube_015' for the mesh 'mesh' has the correct skin and skeleton - it seems that the skeleton/skin are only being assigned to the first child of the root node.

**Comment by bhaux** [comment]
This would be awesome to see implemented as we are looking to push character animation in gltf.
@kimkulling do you have a timeline for this one?

**Comment by kimkulling** [comment]
Shall work now on current maser Please check, if the feature does not work properly reopen the issue.
