### ISSUE TITLE
Associate Material Textures with a aiTexture index

### ISSUE THREAD

**Issue by lamogui** [assimp/assimp#1177]
Hi again

I was trying to load blender file. Theses file have internal textures. 
I see that there is a aiTexture table that contains the data but in a aiMaterial there is no way to find the corresponding index in aiTexture table

Did I miss something ?

**Comment by kimkulling** [comment]
Good question. Assimp is supporting embedded textures. From my point of view this should be the case for blender-files as well. And as a user you should not have to care if a texture was imported from an embedded source or not. 
Do you have an example which we can use to reproduce this issue?

**Comment by lamogui** [comment]
What do you mean by an example ? you want a .blend of this type ?

**Comment by kimkulling** [comment]
Exactly, just a small one to have a reproducable example for a test. Saves a lot of time for me when you need to get the fix.

**Comment by lamogui** [comment]
[cube texture packed.zip](https://github.com/assimp/assimp/files/932744/cube.texture.packed.zip) (sorry I needed to zip it because github doesn't want upload *.blend files

How to create this kind of file ? 
 - Create a new blender scene 
 - Add a cube
 - Add a material and a texture to the cube selecting an image
 - Then "File"->"External Data"->"Pack All into .blend"

**Comment by Squareys** [comment]
Just wondered about this aswell!

I could imagine code to load an embedded texture for a material to look something like this:

```cpp
aiMaterial* mat = scene->mMaterials[0];

bool isEmbedded = false;
aiString path;
int matId;

if (mat->Get(AI_MATKEY_TEXTURE(aiTextureType_DIFFUSE, 0), path) != AI_SUCCESS) {
    // No path (n/a), maybe embedded

    if (mat->Get(AI_MATKEY_TEXTURE_EMBEDDED_ID(aiTextureType_DIFFUSE, 0), matID) == AI_SUCCESS) {
        // texture is scene->mTextures[matId]
        isEmbedded = true;
    } else {
        // this material doesn't have a diffuse texture.
    }
}
```
Does that make sense or is that cumbersome? Maybe somebody else has a suggestion for a better/different approach?

**Comment by Squareys** [comment]
@kimkulling Have you already started working on this? I'd dare to give it a try, seems rather straight forward. What other importers load embedded textures?

The code proposed wouldn't *quite* work. The .blend importer *always* sets the texture path, even if the image is packed. Hence, the way to use the API would be asking for the embedded id first (what should this be called?) and if the texture is not loaded by the importer already, *then* ask for the filename and load it. Does that make sense?

**Comment by Squareys** [comment]
(Started working on this)

**Comment by Squareys** [comment]
Alright, digging into the code I found out there already is a way to do this:

AI_MATKEY_TEXTURE will return a string along the lines of `"*1234"` where `1234` in this case is a zero-based index into `aiScene->mTextures` (See the doc for the `AI_MAKE_EMBEDDED_TEXNAME` macro).

@kimkulling You can probably close this issue as a result.

**Comment by kimkulling** [comment]
OK, Done!
