### ISSUE TITLE
Old findpackage does not compatible with the current install script of cmake 

### ISSUE THREAD

**Issue by caiwan** [assimp/assimp#1179]
I'm trying to use Assimp as an external library for my project with the [old cmake module](https://github.com/assimp/assimp/blob/master/cmake-modules/Findassimp.cmake) to find its library path. 
This script is sightly outdated, dated back to Dec of 2015, the closest version tag is v3.2 which could support that. The install script of the cmake used library postfix in the filenames and platform to separate debug and release builds then, but the latest one doesn't. The latest one throws the libs into a `bin` and `lib` folder, without making the library build identical to build into another project.
Is there any way to fix the install script in the future to mach the old script in the futre, or is there any provided package info to use current one?

**Comment by kimkulling** [comment]
Hm, good point. As far as I know we don't have a test for that. I need to investigate.

**Comment by caiwan** [comment]
I made a quick and dirty fix for that in these commits: https://github.com/caiwan/assimp/commit/00553d1cf2dcb0a2452cac34c4069907834098d6 and https://github.com/caiwan/assimp/commit/21ced8bf7e0b4ebb413f90d27cd923d896f08607
Which sets debug postfix directly - becasue the expression was always false for me, and cmake will use this on debug cofiguration. At this point I have not tested on other platforms than MSVC14. The other removes the platform type from the filename.

**Comment by kimkulling** [comment]
Thanks for the tip. Hopfully I will find some time to integrate your fixes. Do you know of any side-effects?

**Comment by caiwan** [comment]
I haven't met with any yet.

**Comment by kimkulling** [comment]
Shall be fixed now.
