### ISSUE TITLE
Cann't import .dae file.

### ISSUE THREAD

**Issue by somonus** [assimp/assimp#1184]
When I use `Importer.ReadFile` to import dae file, it return NULL.

Here is my code:

```
unsigned int flags = aiProcess_CalcTangentSpace      |
        aiProcess_Triangulate           |
        aiProcess_JoinIdenticalVertices |
        aiProcess_SortByPType;

        string path = getPath(name);
        cout << "path:" << path << endl;
        
        const aiScene* ptr = Importer.ReadFile(path, flags );

if(!ptr)
        {
            std::cerr<< "CCacheResourceManager: [ERROR] could not load mesh:"<< name <<". Reason: "<<Importer.GetErrorString()<<"\n";
            return NULL;
        }
```

The error is: Collada: File came out empty. Something is wrong here.

**Comment by kimkulling** [comment]
Could you provide the dae-file, please?

Arron Zhu <notifications@github.com> schrieb am Fr., 24. Feb. 2017, 03:10:

**Comment by somonus** [comment]
I solved it. This is an xcode bug.
To prevent xCode from compiling your models, you need to tell xCode to load the file into the app Resources as a Data file. You can do this by selecting the file and open the Utilities sidebar in xCode, then under the File Inspector, you will find the Identity and Type section (the first one). The Type selector will by default be set to Digital Asset Exchange (DAE), you just need it to change this option to Data. With this, xCode will not compile the collada xml file and the model will load correctly.
