### ISSUE TITLE
LWOB loader appears broken (LWO: Unable to build a valid node graph)

### ISSUE THREAD

**Issue by darkf** [assimp/assimp#1196]
When opening any LWOB file, `LWO: Unable to build a valid node graph` is given. To reproduce, try to import (e.g. via `assimp_viewer`) the model `test/models/LWO/LWOB/ConcavePolygon.lwo` (or any other file). You will receive the error.

**Comment by turol** [comment]
The example models all seem to be very simple with only one node each.

@darkf Do you have a more complex LWOB model which you could share?

**Comment by tellypresence** [comment]
I also getting the same error on the 4 bundled LWOB test models
```
test/models/LWO/LWOB/ConcavePolygon.lwo
test/models/LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo
test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo
test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo
```

**Comment by turol** [comment]
They don't work here either. Also they leak memory so they're not currently part of the unit tests and not easy to add. Also it looks like I've tried to fix that at some point with no success...

Did these files ever work? Do they load in some other app? Can you bisect assimp itself? Better yet, can you fix either the memory leaks or the loader itself?

**Comment by Epsola** [comment]
This _still_ appears to be an issue. The test models don't work, nor do any other lightwave 5.5 models I've tried to load. Will this ever be fixed?

**Comment by tellypresence** [comment]
LWOB models loading and rendering now, some screenshots for future reference below.
(Note: [`test/models/LWO/LWOB/ConcavePolygon.lwo`](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/ConcavePolygon.lwo) loaded OK but rendered completely invisible)

<table>
<tr><th>Model</th><th>Result></th></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo">test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo</a></td><td><img src="https://user-images.githubusercontent.com/26958898/222350177-8c129b44-4465-4ec7-827c-d1e491d2acff.png" alt="QuickDraw-Laserbeam_lwo_-_assimp_commit_2023-02-27_e9033334" width=160></td></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo">test/models/LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo</a></td><td><img src="https://user-images.githubusercontent.com/26958898/222352024-64d0788b-6491-4ec7-93d8-0c89f619777d.png" alt="bluewithcylindrictexz_lwo_-_assimp_commit_2023-02-27_e9033334" width=160></td></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo">test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo</a></td><td><img src="https://user-images.githubusercontent.com/26958898/222351293-44edcac1-38dd-42c7-9237-29a65b8e4164.png" alt="sphere_with_mat_gloss_10pc_lwo_-_assimp_commit_2023-02-27_e9033334" width=160></td></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo">test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo</a></td><td><img src="https://user-images.githubusercontent.com/26958898/222351298-c1699dc2-1bd6-4ca3-ba49-59ed26378805.png" alt="sphere_with_mat_gloss_50pc_lwo_-_assimp_commit_2023-02-27_e9033334" width=160></td></tr>
</table>
