### ISSUE TITLE
Memory leak in Assimp::Collada

### ISSUE THREAD

**Issue by jiayouhu** [assimp/assimp#1199]
like this

    Assimp::Importer importer;
    const aiScene* aiscene = importer.ReadFile( filePath,
                                             aiProcess_Triangulate|               
                                             aiProcess_JoinIdenticalVertices|    
                                             aiProcess_SortByPType);

**Comment by jiayouhu** [comment]
filePath = "XXXX.dae"

**Comment by jiayouhu** [comment]
[library_animation_clips.dae.zip](https://github.com/assimp/assimp/files/824530/library_animation_clips.dae.zip)

**Comment by kimkulling** [comment]
Do you have a list  of leaking calls?

**Comment by jiayouhu** [comment]
![wx20170308-105404](https://cloud.githubusercontent.com/assets/20379911/23688199/e3361a92-03ed-11e7-9475-34e32710eb88.png)
![wx20170308-105614](https://cloud.githubusercontent.com/assets/20379911/23688200/e378f6c8-03ed-11e7-94bc-d4d0f312b6bd.png)

**Comment by jiayouhu** [comment]
Only this file caused a leak

**Comment by jiayouhu** [comment]
when i changed the file name "library_animation_clips" to "libraryanimationclips",there was nothing to leak. Is there something i missed?

**Comment by turol** [comment]
Valgrind on Linux 64-bit:

```
3,982 (672 direct, 3,310 indirect) bytes in 12 blocks are definitely lost in loss record 11 of 11 at 0x4C29180: operator new(unsigned long) (vg_replace_malloc.c:324)
   by 0x54B132: Assimp::ColladaParser::ReadAnimation(Assimp::Collada::Animation*) (ColladaParser.cpp:551)
   by 0x54A971: Assimp::ColladaParser::ReadAnimationLibrary() (ColladaParser.cpp:419)
   by 0x549A58: Assimp::ColladaParser::ReadStructure() (ColladaParser.cpp:191)
   by 0x549897: Assimp::ColladaParser::ReadContents() (ColladaParser.cpp:166)
   by 0x54921D: Assimp::ColladaParser::ColladaParser(Assimp::IOSystem*, std::string const&) (ColladaParser.cpp:106)
   by 0x52CBCB: Assimp::ColladaLoader::InternReadFile(std::string const&, aiScene*, Assimp::IOSystem*) (ColladaLoader.cpp:162)
   by 0x49C741: Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::string const&, Assimp::IOSystem*) (BaseImporter.cpp:95)
   by 0x7B967F: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:674)
```

Looks like some animations are not properly disposed. Valgrind also reports
`still reachable: 2,144 bytes in 4 blocks` but you should fix the animation leak first.

**Comment by kimkulling** [comment]
Should be fixed now.
