### ISSUE TITLE
OBJ loader does not support \ at line ends correctly

### ISSUE THREAD

**Issue by Schrompf** [assimp/assimp#1200]
A line like this:

vn -2.529290143686992e-15 -0.9848077297210693 \\
-0.1736481934785843

should yield a valid normal. But it doesn't

**Comment by kimkulling** [comment]
R

**Comment by kimkulling** [comment]
Nice finding! I will take care!

**Comment by samitc** [comment]
I ran into same problem and I created pull request #1231

**Comment by kimkulling** [comment]
Fixed by https://github.com/assimp/assimp/commit/cfe4ee020238642f9ea5e7d75c073d58465b48e0
