### ISSUE TITLE
X3D loader: comma in lines is whitespace but breaks import

### ISSUE THREAD

**Issue by Schrompf** [assimp/assimp#1202]
A line like this:

<Normal vector="-5.8201672e-016 -0 1, -5.8201672e-016 -0 1,"/>

is valid as ',' is to be treated as whitespace according to the spec, but currently fails the import.

**Comment by smalcom** [comment]
Can you show example what you mean?

**Comment by kimkulling** [comment]
Closed by 9ffc1a97c184cea9f78c4c1ede4ef9296ff2ead2
