### ISSUE TITLE
How to build with bitcode enabled

### ISSUE THREAD

**Issue by msc-** [assimp/assimp#1203]
I am building libassimp for iOS to use in an app on iOS 10. When linking my app Xcode (8.2.1) reports

```
ld: 'other_lib/ios/Debug-iphoneos/libassimp.a(Importer.cpp.o)' does not contain bitcode.
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an
updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

As described in Issue #1036, and indicated above, I can disable bitcode in my app. But what if my app ends up needing bitcode?

Is there a simple way to get port/iOS/build.sh to build libassimp with bitcode? Is there any plan to enable bitcode in the default libassimp build?

**Comment by kimkulling** [comment]
You can try to add bitcode support for iOS support on your own by adding 

`add_definitions(-DENABLE_BITCODE)`

on your own ( just add this in <assimp_folder/CMakeLists.txt> ). Try to rebuild and when it works feel free to provide a new pull request. FRom my point of view enable-bitcode would be an interesting option. Unfortunately I do not have any iOS-test environment to see if this works file.
