### ISSUE TITLE
Can't import pyassimp in Ubuntu 16.04

### ISSUE THREAD

**Issue by jlack1987** [assimp/assimp#1209]
In Ubuntu 16.04 I am unable to simply import pyassimp in a python module. I have tried this on multiple machines as well as pristine dockers and always have the same problem. Steps to reproduce are:

`sudo pip install pyassimp` OR `sudo apt-get install python-pyassimp`, either still fail
Then in an `ipython` console,
`import pyassimp`

Here is my entire ipython console output
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyassimp
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-652a73ea0321> in <module>()
----> 1 import pyassimp

/usr/lib/python2.7/dist-packages/pyassimp/__init__.py in <module>()
----> 1 from .core import *

/usr/lib/python2.7/dist-packages/pyassimp/core.py in <module>()
     27 from .formats import available_formats
     28 
---> 29 class AssimpLib(object):
     30     """
     31     Assimp-Singleton

/usr/lib/python2.7/dist-packages/pyassimp/core.py in AssimpLib()
     31     Assimp-Singleton
     32     """
---> 33     load, load_mem, release, dll = helper.search_library()
     34 _assimp_lib = AssimpLib()
     35 

ValueError: need more than 3 values to unpack
```

I have also posted [here](https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1657374?comments=all) that I have encountered the bug and it looks like i'm not the only one.

**Comment by kimkulling** [comment]
Thanks for the information. The latest version seems to be broken. Windows is working fine.

**Comment by kimkulling** [comment]
Have you tried to import pyassimp as sudo? I have installed pyassimp for my local user ( Ubuntu16.04, gcc 5.0x ) and it worked for me. The only difference seems to be that I have installed pyassimp for my local user.

**Comment by kimkulling** [comment]
Tried it with ipython wit installed pyassimp as root. Worked for me. You could check if the installed pyassimp is placed in your PYTHONPATH.
Have you used the latest version of pip? pip logged the following tip:

**You are using pip version 8.1.1, however version 9.0.1 is available**

Maybe this could cause the issue?

**Comment by jlack1987** [comment]
I will gather some more info today and get back to you. I can at least confirm that if I build `master` from source and install it, then I do not have any problems.

**Comment by jlack1987** [comment]
I should probably add that the version that causes a problem is the version from debians `apt` which is `python-pyassimp 3.2~dfsg-3`

**Comment by jlack1987** [comment]
The best way to reproduce this is to pull down the `ubuntu:xenial` docker via `docker pull ubuntu:xenial` then,

`apt-get update`
`apt-get install ipython`
`apt-get install python-pyassimp`

Then in ipython just `import pyassimp`. Using sudo won't fix it as it looks like an actual bug. From the trace it shows that line 33 in core.py which is `load, load_mem, release, dll = helper.search_library()` is looking for 4 things returned from the `search_library()` method. That method only returns 3 elements though. At line 155 in `helper.py` the return statement is `return(load, release, LIBASSIMP)`

**Comment by atomoclast** [comment]
I too am having this issue. I can't install from the debian or pip.

**Comment by kimkulling** [comment]
Ah, ok. I tried this out in a normal ubuntu installation without using a docker file. Will try it out.

**Comment by kimkulling** [comment]
Try it now and reopen the issue, if its still there. I still was not able to reproduce it.

**Comment by jlack1987** [comment]
For more info there's a thread [here](https://github.com/ros-planning/moveit/issues/86) of another package that uses `pyassimp` that has been having the same problem for some time.
