### ISSUE TITLE
Groupnames should be part of the mesh names

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#121]
The groupname defined in an obj-file should be part of the mesh name.

see: https://sourceforge.net/p/assimp/bugs/89/

**Comment by socceroos** [comment]
What part of the code did this change affect?

I'm searching for the source of a bug in the OBJ exporter that is causing the mesh names to be duplicated. This line of the code is causing the issue: https://github.com/assimp/assimp/blob/master/code/ObjExporter.cpp#L351
