### ISSUE TITLE
I get an access violation when I use Assimp::Importer importer.ReadFile

### ISSUE THREAD

**Issue by Ciarfix** [assimp/assimp#1215]
I'd like to ask a question about assimp. When I try to run my code the compiler and the linker does not give me any error but it gives me an access violation error when I use the ReadFile function, but if I comment the following part of the code the program works fine.

     `const` aiScene *scene = importer.ReadFile(path, aiProcess_Triangulate |                       aiProcess_FlipUVs);

    // Check for errors
    if (!scene || scene->mFlags == AI_SCENE_FLAGS_INCOMPLETE ||    !scene->mRootNode) // if is Not    Zero
     {
     cout << "ERROR::ASSIMP:: " << importer.GetErrorString() << endl;
     return; 
      }
     // Retrieve the directory path of the filepath

     this->directory = path.substr(0, path.find_last_of('/'));

     // Process ASSIMP's root node recursively
     this->processNode(scene->mRootNode, scene);`

The part of the main in which I create my model object:

`Model` `ourModel("Object/models/nanosuit.obj");`

I've been searching for a solution for an entire day. If someone could help me figure it out I would be really glad. If you need other parts of the code please tell me.

If you want to see the entire Model.cpp file go to [(http://stackoverflow.com/questions/43000716/my-opengl-program-stops-running-when-i-use-the-assimp-importer-readfile?noredirect=1#comment73098298_43000716) ](url)

**Comment by kimkulling** [comment]
See stackoverflow.
