### ISSUE TITLE
Android Compile Problem

### ISSUE THREAD

**Issue by redknotmiaoyuqiao** [assimp/assimp#1216]
I try to compile assimp for android ,but i am fail.

First, I cant find the android.toolchain.cmake,where should i find it?

Second,I find an android.toolchain.cmake in openCV's repository(<a href="https://github.com/opencv/opencv/blob/master/platforms/android/android.toolchain.cmake">here</a>),but when I use "make",it still didnt work.

bogon:AndroidJNI yuqiaomiao$ make
Scanning dependencies of target android_jniiosystem
[ 50%] Building CXX object CMakeFiles/android_jniiosystem.dir/AndroidJNIIOSystem.cpp.o
/Users/yuqiaomiao/assimp/port/AndroidJNI/AndroidJNIIOSystem.cpp:45:27: fatal error: assimp/config.h: No such file or directory
 #include <assimp/config.h>
                           ^
compilation terminated.
make[2]: *** [CMakeFiles/android_jniiosystem.dir/AndroidJNIIOSystem.cpp.o] Error 1
make[1]: *** [CMakeFiles/android_jniiosystem.dir/all] Error 2
make: *** [all] Error 2

**Comment by kimkulling** [comment]
The config file will be generated during the cmake run from config.h.in. So when no header-file config.h is there this si a sign that your cmake run hasn't started the assimp-related cmake run as well. Make sure that your assimp-folder was added to the root-cmake file. 
I tried this out in a cmake run with gradle and it worked file for me.
And please make sure that the include folder was added to your list with includes as well! If this is still an issue, just reopen it!
