### ISSUE TITLE
CalcTangentsProcess::ProcessMesh: division by zero

### ISSUE THREAD

**Issue by regrainb** [assimp/assimp#1219]
With Assimp 3.1.1:

In the file CalcTangentsProcess.cpp (line 191), in the function CalcTangentsProcess::ProcessMesh, we test if the 3 points are aligned instead of being at the same place. Because if they are aligned, the tangent and bitangent can't be computed.
Code:
   `if ( 0 == sx && 0 ==sy && 0 == tx && 0 == ty )`
should be replaced with:
   `if ( sx * ty == sy * tx )`

In my case, I had 2 points at the same place instead of 3, but the source of the issue is the same.

**Comment by kimkulling** [comment]
Ok, thanks for the bug report. I will fix that bug.

**Comment by kimkulling** [comment]
Fixed.
