### ISSUE TITLE
Loading IFC4 content

### ISSUE THREAD

**Issue by ehtick** [assimp/assimp#1224]
Is IFCV4 supported ?

regards Eddy

**Comment by ehtick** [comment]
It works but not 100% :(

**Comment by kimkulling** [comment]
Which features ypu need to use are broken?

**Comment by ehtick** [comment]
This very simple model is not shown. but gives an error. Solibri and others no problems
[example.zip](https://github.com/assimp/assimp/files/947244/example.zip)

**Comment by ehtick** [comment]
Other problem models in IFC.

[circular-rebar.zip](https://github.com/assimp/assimp/files/967416/circular-rebar.zip)

**Comment by kimkulling** [comment]
Just started to support it completly.

**Comment by ehtick** [comment]
Great :)

**Comment by FreakTheMighty** [comment]
@kimkulling any updates on IFC4 development?

**Comment by kimkulling** [comment]
I will use only one issue report to track this feature request.

**Comment by kimkulling** [comment]
Will be tracked in a newer issue.
