### ISSUE TITLE
Ignoring packed attribute because of unpacked non-POD field

### ISSUE THREAD

**Issue by msc-** [assimp/assimp#1225]
I pulled the latest headers to get the fix for #1057, which is also a fix for #1169, and now I get 2 warnings from GCC (6.2.0) on Linux:

```
Ignoring packed attribute because of unpacked non-POD field ‘aiVector3D aiRay::dir’
Ignoring packed attribute because of unpacked non-POD field ‘aiVector3D aiRay::pos'
```

Both are at line 153 in include/assimp/types.h.

**Comment by kimkulling** [comment]
I am currently trying to the the xcode issue and removed some pragma pack statements. that is the reason for those warnings. When having the fix for the xcode issue ready the warning shall be gone as well.

**Comment by msc-** [comment]
Please reopen this and close it when you have fixed it so I will know when to update my assimp headers.
