### ISSUE TITLE
Test process modifies tracked file

### ISSUE THREAD

**Issue by Sailsman63** [assimp/assimp#1228]
Running `test/unit` generates changes in `test/models/OBJ/spider.obj`, which is a git-tracked file. It becomes neccessary to checkout or reset before pulling new changes from the repository, as the changes block an automatic merge of new updates.

**Comment by kimkulling** [comment]
good point, I will fix that issue.

**Comment by kimkulling** [comment]
Closed by ad80f97930473c9664d083e1a1529e617e65e296
