### ISSUE TITLE
Is Assimp.Net still supported?

### ISSUE THREAD

**Issue by vpenades** [assimp/assimp#1229]
It has not been updated in the last 3 years... and it's binded to an old version of Assimp.

**Comment by kimkulling** [comment]
Yes, it will get a new release with the next 4.0 assimp release. I forgot to update the last versions.

**Comment by vpenades** [comment]
Sorry to ask in a closed issue:

I can't see why this issue has been closed, a proper Assimp.Net for Assimp 4.0 is nowhere to be found... the Net Community is still widely using Assimp 3.3.1 under the old net wrapper, [which is the only nuget package available.](https://www.nuget.org/packages/AssimpNet/) from [here](https://bitbucket.org/Starnick/assimpnet/src)

A while ago I asked at Gitter and I was pointed to this [repository](https://github.com/kebby/assimp-net/) but it's not been updated for almost half a year, so to me it looks pretty much dead.
