### ISSUE TITLE
assimp android ?

### ISSUE THREAD

**Issue by GalatasarayForever** [assimp/assimp#1230]
Hi, open3mod assimp on PC is more then great. I can even see full complex textured models. But on android there is only HD model viewer which crashes many times and loaded the textures not always or wrong. I see the assimp library always updated but I cannot see anywhere a final android apk viewer. Is there a official or unofficial assimp android viewer other then HD model viewer. Thanks a lot

**Comment by kimkulling** [comment]
I am working on a new viewer for android. Hopefully I can deliver some beta in the next couple of months.
