### ISSUE TITLE
Can't load assbin files

### ISSUE THREAD

**Issue by JelenaKB** [assimp/assimp#1240]
I can't get .assbin files to load. Using the command line tool I've created an .assibin file, immediately tired to use the info command for the resulting file, and it failed to load.

I'm using [this](https://www.turbosquid.com/FullPreview/Index.cfm/ID/876965) model

`jelenaKB$ assimp dump Eye.FBX -cfull -b 
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Importing file ...                   OK 
   import took approx. 0.00631 seconds`

`assimp dump: Wrote output dump Eye.assbin
`

`jelenaKB$ assimp info Eye.assbin
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: Validation failed: A node has no valid parent (aiNode::mParent is NULL)
assimp info: Unable to load input file Eye.assbin`

I've also tried loading it on iOS

`    NSString *modelPath = [[NSBundle mainBundle] pathForResource:@"Eye" ofType:@"assbin"];`
    `gScene = aiImportFile(modelPath.UTF8String, aiProcessPreset_TargetRealtime_MaxQuality);`

and got the following error:
`Assertion failed: (false), function ReportError, file /Users/jelenaKB/assimp/code/ValidateDataStructure.cpp, line 92.`

Are .assbin files loaded differently?

**Comment by kimkulling** [comment]
This one is already fixed.
