### ISSUE TITLE
Wrong includedir in cmake.pc.in

### ISSUE THREAD

**Issue by tgnottingham** [assimp/assimp#1241]
The includedir in cmake.pc is

@CMAKE_INSTALL_PREFIX@/@ASSIMP_INCLUDE_INSTALL_DIR@/assimp

rather than

@CMAKE_INSTALL_PREFIX@/@ASSIMP_INCLUDE_INSTALL_DIR@

This results in pkg-config reporting, for example, /usr/include/assimp instead of /usr/include for the include directory. This suggests that users use #include <scene.h> rather than #include <assimp/scene.h>, but I don't think that's intended. The [assimp documentation](http://www.assimp.org/lib_html/usage.html) uses #include <assimp/scene.h>, for example.

Is there any reason the includedir needs to have assimp on the end, or can it be changed?

**Comment by kimkulling** [comment]
Seems to be just a bug. Should be solved. Ad sorry für the late response!

**Comment by kimkulling** [comment]
Fixed.
