### ISSUE TITLE
Assimp 3.3.1 setup x64 libs

### ISSUE THREAD

**Issue by pszturmaj** [assimp/assimp#1243]
It seems that binary x64 lib is really a x86 one. I downloaded and installed assimp-sdk-3.3.1-setup_vs2017 and I'm using VS 2017 Community.

1>Engine.obj : error LNK2019: unresolved external symbol "public: __cdecl Assimp::Importer::Importer(void)" (??0Importer@Assimp@@QEAA@XZ) referenced in function main
1>Engine.obj : error LNK2019: unresolved external symbol "public: __cdecl Assimp::Importer::~Importer(void)" (??1Importer@Assimp@@QEAA@XZ) referenced in function main
1>Engine.obj : error LNK2019: unresolved external symbol "public: struct aiScene const * __cdecl Assimp::Importer::ReadFile(char const *,unsigned int)" (?ReadFile@Importer@Assimp@@QEAAPEBUaiScene@@PEBDI@Z) referenced in function main
1>Engine.obj : error LNK2019: unresolved external symbol "public: char const * __cdecl Assimp::Importer::GetErrorString(void)const " (?GetErrorString@Importer@Assimp@@QEBAPEBDXZ) referenced in function main
1>D:\Assimp\lib\x64\assimp.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'

**Comment by kimkulling** [comment]
Strange, I build it with x64 config on. Thanks for figuring this issue out!

**Comment by JiahuiCai** [comment]
Same problem here. Thank you for acknowledging this issue.

**Comment by YourPsychiatrist** [comment]
Is there a way to build for x64 now? Or would I need to use an older version?

**Comment by kimkulling** [comment]
HAve you tried this small tutorial: http://kimkulling.de/2016/05/02/build-asset-importer-lib-for-64bit-with-visual-studio-from-source-repo/?preview_id=8&preview_nonce=ca49c152a5&post_format=standard&_thumbnail_id=109&preview=true

**Comment by YourPsychiatrist** [comment]
"Sorry, you are not allowed to preview drafts."

**Comment by kimkulling** [comment]
Ops, wrong link, please try again.

**Comment by YourPsychiatrist** [comment]
I just played around with the cmake gui a bit which solved the problem in the end. Thanks! Love assimp btw. :)
