### ISSUE TITLE
Expression is always false

### ISSUE THREAD

**Issue by AppChecker** [assimp/assimp#1251]
Hi!

This [expression](https://github.com/assimp/assimp/blob/79e582abca84e85042fce7e415dbd892d72ad7fa/code/STEPFileEncoding.cpp#L338)
`   if (s[j] == '\\' && s[j] == 'X' && s[j] == '0' && s[j] == '\\') {`
is always false.
Probably, it is mistake.

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by ArcEcho** [comment]
&& means all the conditions should be established at the same time, so it is always false. I wonder if you || instead of &&.
