### ISSUE TITLE
Texture coordinates parsing problem in ply file

### ISSUE THREAD

**Issue by coskunyerli** [assimp/assimp#1270]
`mesh->mTextureCoord[0] == nullptr`  this operation returns true, but It must be false in my ply file
mesh->HasTextureCoords(0) has also return false

https://drive.google.com/file/d/0B6eCJgHeJ47eYjdjeEk4ZEVGQUk/view?usp=sharing

ply files work with texture properly in meshlab.

Please Help!

**Comment by chaitanya100100** [comment]
Similar problem with me. Did you find any solution ?
