### ISSUE TITLE
OpenGEXImporter: Does not handle comments correctly.

### ISSUE THREAD

**Issue by Squareys** [assimp/assimp#1271]
Hi everybody,

again while integrating assimp for https://github.com/mosra/magnum-plugins/, I found the OpenGEXImporter to error with invalid token on [one of our test files](https://github.com/mosra/magnum-plugins/blob/master/src/MagnumPlugins/OpenGexImporter/Test/mesh.ogex).

It cannot handle comments when they appear after a structure type, e.g. `GeometryNode /*mesh*/ {`.

The ogex specification says the following about comments (for quick reference):
```
# Comments and Whitespace

The language supports C++-style block comments and single-line comments as follows:
   • Any occurrence of /* begins a comment that ends immediately after the next occurrence of */.
     Such comments do not nest.
   • Any occurrence of // begins a comment that ends immediately after the next newline character.
     If any sequence /*, */, or // appears inside a character literal or string literal, then it is
     part of the literal value and not treated as a comment.

[...]

All characters having a value in the range [1,32] (which includes the space, tab, newline,
and carriage return characters), as well as all characters belonging to comments, are
considered to be whitespace in OpenDDL. Any arbitrarily long contiguous sequence of
whitespace characters is equivalent to a single space character.
```

Specifically the last paragraph means that whitespaces and comments can be exchanged, therefore there is no restriction on where the comments are allowed to appear, hence our file is indeed valid.

Cheers, Jonathan.

**Comment by kimkulling** [comment]
OK, thanks for the report!

**Comment by Squareys** [comment]
Awesome, thanks! 👍
