### ISSUE TITLE
Program crashs when calling GetTextureCount() or GetTexture()

### ISSUE THREAD

**Issue by phocode** [assimp/assimp#1276]
I'm using assimp 3.1.1 with the pre-built version downloaded on the website, IDE CodeBlocks.
I can't import an obj file with Importer class so I come to the C-based approche, that is using aiImportFile() function instead, this works well and I can import normals, vertices, faces... without any problems, but I can't load the materials, my program crashs whenever a call to GetTextureCount() or GetTexture() is made. Here is my simple code:
```
#include <bits/stdc++.h>

#include <assimp/cimport.h>
#include <assimp/scene.h>
#include <assimp/postprocess.h>

using namespace std;

int main()
{
    const char * obj_file_name = "nanosuit2.obj";
    const aiScene *scene = aiImportFile(obj_file_name,
                                        aiProcess_Triangulate |
                                        aiProcess_FlipUVs |
                                        aiProcess_CalcTangentSpace);

    if(!scene) {
        cout << "Could not open file" << endl;
        return 1;
    }
    cout << scene->mNumMeshes << " meshes" << endl;

    for(int i = 0 ; i < scene->mNumMeshes ; i++) {
        const aiMesh *mesh = scene->mMeshes[i];
        cout << "In mesh[" << i << "] :" << endl;
        cout << mesh->mNumVertices << " vertices" << endl;
        cout << endl;
    }
    cout << scene->mNumMaterials << " materials in the scene";
    const aiMaterial *material = scene->mMaterials[0];
    cout << material->GetTextureCount(aiTextureType_DIFFUSE) << " diffuse textures " << endl;

    aiReleaseImport(scene);
    return 0;
}
```
And some outputs until it crashs:
```
7 meshes
In mesh[0]:
7248 vertices

In mesh[1]:
156 vertices

In mesh[2]:
78 vertices

In mesh[3]:
8216 vertices

In mesh[4]:
6804 vertices

In mesh[5]:
19350 vertices

In mesh[6]:
15222 vertices

1 materials in the scene                             // CRASH AFTER THIS LINE
```

Please any help me, maybe I should rebuild the library?

**Comment by rdb** [comment]
Does it happen on any .obj file, or just the one in question?  If the latter, it might be helpful if you attached the .obj file.

**Comment by kimkulling** [comment]
Yes, would be great to get the obj-file to reproduce the issue.

**Comment by phocode** [comment]
I use the model from learnopengl.com here: 
https://learnopengl.com/#!Model-Loading/Model

But it works well after rebuilding the library.

[nanosuit.zip](https://github.com/assimp/assimp/files/1025262/nanosuit.zip)

**Comment by kimkulling** [comment]
Ok, so I have closed the issue.
