### ISSUE TITLE
How to import the stl format data file that is the size of 500M?

### ISSUE THREAD

**Issue by JasonWinston** [assimp/assimp#1277]
Importer.SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_POINT | aiPrimitiveType_LINE);
	const aiScene* pScene = Importer.ReadFile(Filename.c_str(), 
		//aiProcess_CalcTangentSpace | 
		aiProcess_GenNormals | 
		aiProcess_Triangulate | 
		aiProcess_FlipUVs |
		aiProcess_SortByPType 
		);
	/////////////////////////////////////////////////
	const char* str = Importer.GetErrorString();//the value of str is bad allocation,why?

**Comment by kimkulling** [comment]
I guess the allocation for reading the file combined with all the internal data post-processing and preparations will just kill the memory allocator. We need to take a look.

**Comment by kimkulling** [comment]
Possible, see https://github.com/assimp/assimp/pull/4630
