### ISSUE TITLE
ColladaLoader: Fails "Something is wrong here" when root node is an instance_visual_scene

### ISSUE THREAD

**Issue by Squareys** [assimp/assimp#1278]
**Hello everyone,**

When trying to load our [scene.dae test file](https://github.com/mosra/magnum-plugins/blob/master/src/MagnumPlugins/ColladaImporter/Test/ColladaImporterTestFiles/scene.dae), ColladaLoader fails with the following error:
~~~
Info,  T0: Load [...]/magnum-plugins/src/MagnumPlugins/AssimpImporter/Test/../../ColladaImporter/Test/ColladaImporterTestFiles/scene.dae
Debug, T0: Assimp 3.3.4285932784 amd64 gcc debug shared singlethreaded
Info,  T0: Found a matching importer for this file format: Collada Importer.
Info,  T0: Import root directory is '[...]/magnum-plugins/src/MagnumPlugins/AssimpImporter/Test/../../ColladaImporter/Test/ColladaImporterTestFiles/'
Debug, T0: Collada schema version is 1.4.n
Error, T0: Collada: File came out empty. Something is wrong here.
~~~
This is because this files root node is an `instance_visual_scene` which is (probably) resolved with `BuildHierarchy()` [further down the line](https://github.com/assimp/assimp/blob/master/code/ColladaLoader.cpp#L177), but at [the point](https://github.com/assimp/assimp/blob/master/code/ColladaLoader.cpp#L164) where `pScene->mRootNode` is checked it is still `nullptr`.

Moving the check to after the `BuildHierarchy()` call (or removing it completely, if scene-less collada files are valid\* (material libraries e.g.?)) should hopefully resolve this issue.

Cheers, Jonathan.

\* Checking the [Collada Specification](https://www.khronos.org/files/collada_spec_1_4.pdf), there are indeed scene-less files:

> Each COLLADA document **can** contain, at most, one \<scene\> element

**Comment by Squareys** [comment]
I was mistaken, `BuildHierarchy()` will not resolve the root node instance, since it requires a node as parameter which it resolves node instances for. This issue is probably a little harder to fix in that case.

**Comment by tellypresence** [comment]
Also getting the error `"Unable to load model: Collada: File came out empty.  Something is wrong here."` for models
``
models/Collada/cube_tristrips.dae
models/Collada/cube_UTF16LE.dae
```

**Comment by turol** [comment]
Also getting the same error for those test files. They have not changed since their introduction. @tellypresence can you bisect when this broke?

**Comment by tellypresence** [comment]
Some assimp bisecting for future reference:

[`test/models/Collada/cube_tristrips.dae`](https://github.com/assimp/assimp/blob/master/test/models/Collada/cube_tristrips.dae)

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "cube_tristrips"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th><th>Notes</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/35c506fcf863ff8e01365cb76686b2010f6bd498">35c506fc</a><br>
30 May 2021</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/Collada/cube_tristrips.dae">test/models/Collada/cube_tristrips.dae</a></td><td><img src="https://user-images.githubusercontent.com/26958898/224860397-8e1faa6c-4838-4249-8e78-f198c05f06f5.png" alt="cube_tristrips_-_assimp_commit_2021-05-30_35c506fc" width=160/></td><td>Apparently loader fixed between Jan 2020 and May 2021</td></tr>
</table>

[`test/models/Collada/cube_UTF16LE.dae`](https://github.com/assimp/assimp/blob/master/test/models/Collada/cube_UTF16LE.dae)

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "cube_UTF16LE"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th><th>Notes</th></tr>

<tr><td><a href="https://github.com/assimp/assimp/commit/35c506fcf863ff8e01365cb76686b2010f6bd498">35c506fc</a><br>
30 May 2021</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/Collada/cube_UTF16LE.dae">test/models/Collada/cube_UTF16LE.dae</a></td><td>Load fails with error: <tt>Unable to read file, malformed XML</tt></td><td>Running the xml file through a validator says "no errors"</td></tr>
</table>

**Comment by kimkulling** [comment]
Works now.
