### ISSUE TITLE
Link error: undefined symbol "irr::io::createIrrXMLReader(irr::io::IFileReadCallBack*)"

### ISSUE THREAD

**Issue by IntellectualKitty** [assimp/assimp#1283]
I just updated to the current master branch (05/25/2017) and I'm getting the following linker error in my app:

```
Undefined symbols for architecture x86_64:
  "irr::io::createIrrXMLReader(irr::io::IFileReadCallBack*)", referenced from:
      Assimp::IRRImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*) in libassimp.a(IRRLoader.o)
      Assimp::X3DImporter::ParseFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Assimp::IOSystem*) in libassimp.a(X3DImporter.o)
      Assimp::XGLImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*) in libassimp.a(XGLLoader.o)
      Assimp::D3MFImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*) in libassimp.a(D3MFImporter.o)
      Assimp::IRRMeshImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*) in libassimp.a(IRRMeshLoader.o)
      Assimp::AMFImporter::ParseFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Assimp::IOSystem*) in libassimp.a(AMFImporter.o)
      Assimp::Ogre::OgreImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*) in libassimp.a(OgreImporter.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kimkulling** [comment]
Could you please rerun your cmake build step in verbose mode and post the output here? We changed the way how to link irrXML and it seems to be the root cause for your issue.

Thanks a lot for the report!

**Comment by IntellectualKitty** [comment]
@kimkulling I haven't run CMake in verbose mode before.  From searching on the web, the only thing I found was [making Unix makefiles verbose](https://cmake.org/Wiki/CMake_FAQ#Is_there_an_option_to_produce_more_.27verbose.27_compiling.3F).  From re-reading your comment, I'm starting to suspect that that is what you meant in the first place.

I use the following commands to build Assimp using the Xcode generator:

```
cmake -G Xcode -DBUILD_SHARED_LIBS=OFF ..
xcodebuild -project Assimp.xcodeproj -target ALL_BUILD -target install
```

I use these commands as part of script that downloads the latest version of master from Github using `git pull origin master` before building.  I'd estimate that I do this roughly on a monthly basis, and I've never had a problem before.

I've gone ahead and built Assimp using the instructions from the link above and attached the output in case it's helpful ([make_output.txt](https://github.com/assimp/assimp/files/1037852/make_output.txt)).  If this isn't what you need, please let me know specifically how you would like me to build Assimp and I'll be happy to provide the output.  My schedule is pretty full for the next couple of days, but I'll try to get it to you before the end of the week.  Thank you for looking into this!

**Comment by njligames** [comment]
Hello. I am having the problem as well.

**Comment by njligames** [comment]
The library libIrrXML.a isn't being linked, for whatever reason.

**Comment by heliocastro** [comment]
Can you state your config to us ? I have a Mac machine as well and will be glad to try to reproduce and fix it.
Are you using xcode or alternative compiler through macports ?

**Comment by heliocastro** [comment]
A quick look on the logs show that symbols from lstandard c++ library are missing. Maybe for clang in specific we do need add extra linking flags.

**Comment by kimkulling** [comment]
Hi, your make using cmake was successful.  What you need to do is linking irrXml.a manually. In your build output there were no unresolved symbols at all.

I guess the symbols from irrXml.a will not be public so you need to link them again. This could be solved better.

**Comment by kimkulling** [comment]
Did it help?

**Comment by kimkulling** [comment]
PLease reopen if this is still an issue.

**Comment by IntellectualKitty** [comment]
OK.  I finally found the problem.  In Assimp 3.3.1, IrrXML is builtin, and now Assimp.xcodeproj builds libIrrXml.a as well as libassimp.a.  I wasn't aware of the change.

I tried searching the documentation, and I found this in the CHANGE notes:

    `Apply mechanism to decide use for IrrXML external or internal`

I also found this in the CMakeLists.txt:

```
# Compile internal irrXML only if system is not requested
if( NOT SYSTEM_IRRXML )
    add_subdirectory(irrXML)
endif( NOT SYSTEM_IRRXML )
```

I think it would help to add the details about this to the INSTALL notes.

**Comment by AndreAhmed** [comment]
I have the same problem while building in linux assimp as static library. Then In my software trying to link both assimp and irrxml, I get the exact linking errors above
