### ISSUE TITLE
Texture coords are wrong on a single side of the model

### ISSUE THREAD

**Issue by Ias0601** [assimp/assimp#1286]
I'm using Directx11. When I load the model, the texture coordinates of one side of the mesh is wrong. I tried using AssimpView to view my object and it shows it correctly.
I can swap the wrong side by adding aiProcess_ConvertToLeftHanded flag. I mean when I use this flag previous wrong side becomes correct and previous correct side becomes wrong.
![Screenshot](https://cloud.githubusercontent.com/assets/22124779/26547726/14ab2fdc-448e-11e7-8af5-5434ca9b8fe5.png)

My code : 

https://pastebin.com/aLeMap4f    -   Mesh.h (This is a header only class)
https://pastebin.com/8u79hkUF    -   Model.h
https://pastebin.com/weWXbvZ6  -   Model.cpp

**Comment by Ias0601** [comment]
This is not a issue of assimp. I solved it by sampler state.

**Comment by kimkulling** [comment]
Thanks a lot for the update!

**Comment by Ias0601** [comment]
Thanks a lot for making this awesome library. :)

**Comment by kimkulling** [comment]
You are welcome. But I am only one of more than 100 contributors 👍

**Comment by Ias0601** [comment]
Sir, there are no any directx sample in samples folder. May I upload a proper textured sample.(a pull request) 😊

**Comment by Ias0601** [comment]
Assimp view is based on directx 9.0 but today most are using Directx 11

**Comment by kimkulling** [comment]
Right, this is a legacy viewer.
