### ISSUE TITLE
Failing to build gltfimporter on macos.

### ISSUE THREAD

**Issue by blitz-research** [assimp/assimp#1287]
Hi,

I am unable to build assimp on macos due to rapidjson lib used by gltfimporter/gltfexporter. Error is:

contrib/rapidjson/include/rapidjson/document.h:1038:22: error: call to constructor of 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is ambiguous
        GenericValue v(value);

Also, there are some warnings in gltfimporter such as:

code/glTFAsset.h:232:76: warning: adding 'glTF::ComponentType' to a string does not append to the string [-Wstring-plus-int]
                throw DeadlyImportError("GLTF: Unsupported Component Type "+t);

Disabling gltfimporter/gltfexporter fixes this.

**Comment by kimkulling** [comment]
Which version?

**Comment by kimkulling** [comment]
Will close it, just reopen if you have a current build log.

**Comment by turol** [comment]
[glTFAsset.h line 235](https://github.com/assimp/assimp/blob/master/code/glTFAsset.h#L235)

It adds an integer to a string literal which doesn't produce anything sane. I think the fix would be:

`throw DeadlyImportError(std::string("GLTF: Unsupported Component Type ") + t);`

but I have only looked at the code, not actually tried it.
