### ISSUE TITLE
'Create' is said not defined in Subdivider.cpp 

### ISSUE THREAD

**Issue by eugenelyj** [assimp/assimp#1292]
i compile the whole assimp code, and include <assimp/Subdivision.h>,
then i use `Subdivider* sub = Subdivider::Create(Subdivider::CATMULL_CLARKE);`, which is said not undefined.
However, the following code `	sub->Subdivide(scene->mMeshes, scene->mNumMeshes,
        scene->mMeshes, num,
        true);` is OK.
who can tell me what's wrong with it, thanks.

**Comment by kimkulling** [comment]
The class is not exported to be used externally.  Do you need it? If yes: just reopen the issue.

**Comment by eugenelyj** [comment]
yes, i need it.
