### ISSUE TITLE
CMake 'Cannot find source file config.h'

### ISSUE THREAD

**Issue by diharaw** [assimp/assimp#1294]
While using assimp inside of another CMake project, it fails to locate config.h as the path is wrong. My external libs are located in an 'external' folder from the project root. My build folder is located in the project root as well, named 'build'. Below is line 62 from `assimp/code/CMakeLists.txt` where config,h is added.

`${CMAKE_BINARY_DIR}/include/assimp/config.h`

This results in ` path/to/root/build/assimp/include/assimp/config.h`. The 'external' folder is missing after 'build'. Changing the above line to  `${CMAKE_CURRENT_BINARY_DIR}/../include/assimp/config.h` 
fixes the issue. Is this a problem from my end?

**Comment by kimkulling** [comment]
Already in. Please reopen if this is still an issue for you. Thanks a lot for the report!

**Comment by iKlsR** [comment]
Still getting this or a variation thereof, my config is named config.h.in
