### ISSUE TITLE
.blend file issue removing components

### ISSUE THREAD

**Issue by sapper-trle** [assimp/assimp#1295]
I have a .blend model 163 verts, 303 faces. The UVs are all separate tris and quads, one for each face, no UV verts shared.

Assimp imports this model as having 928 verts and 303 faces.

Assimp won't remove duplicates or generate smooth normals unless I remove the UVs component.

[LionForassimp.zip](https://github.com/assimp/assimp/files/1049395/LionForassimp.zip)

**Comment by kimkulling** [comment]
Which preprocessors wer applied during import? Will the removeDuplicates-process be executed? A log would be great.

Thanks!

**Comment by kimkulling** [comment]
Seems to be the issue regarding generated render vertices. I will close it.
