### ISSUE TITLE
How to specify texture information for new aiMaterial?

### ISSUE THREAD

**Issue by zkyf** [assimp/assimp#1296]
I've been working on a model simplification project and I need to create a new model, fill it with the simplified model data, and export it to a file. What I've tried is to just do the same thing as importing models in the reverse direction, and it seems easy for vertices and faces, but I just found it difficult to set textures for the model. What should I do to aiScene::mMaterials to create textures?
I've tried this:
`
		newScene.mMaterials[i] = new aiMaterial;
		aiString fileName(model.meshes[i].textures[0].path.toStdString());
		newScene.mMaterials[i]->AddProperty(&fileName, AI_MATKEY_TEXTURE_DIFFUSE(0));
`
but this just crashes. I just need to attach a simple diffuse texture to the mesh.

**Comment by kimkulling** [comment]
aiScene::mMaterials** <- is a pointer showing to pointers, so you need to allocate it this way:
newScene.mMaterials = new aiMaterial[1];
newScene.mMaterials[0] = new aiMaterial;
... go for it!

Kim

**Comment by zkyf** [comment]
Thanks for your reply!
I in fact did this and got this problem:
`newScene.mMaterials = new aiMaterial*[model.meshes.size()];
...
newScene.mMeshes[i]->mMaterialIndex = i;
newScene.mMaterials[i] = new aiMaterial;
aiString fileName(model.meshes[i].textures[0].path.toStdString());
newScene.mMaterials[i]->AddProperty(&fileName, AI_MATKEY_TEXTURE_DIFFUSE(0));`
