### ISSUE TITLE
Support glTF 2.0 Specification

### ISSUE THREAD

**Issue by dhritzkiv** [assimp/assimp#1301]
It'd be nice to support importing (and exporting) of glTF 2.0 files.

[Khronos just released](https://www.khronos.org/news/permalink/khronos-releases-gltf-2.0-specification) the finalized [glTF 2.0 Specification.](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0) For the most part, the syntax is changed so now properties are defined as arrays instead of objects/maps, with references defined as indexes instead of keys. The spec also defined PBR-based materials.

**Comment by kimkulling** [comment]
You are right, this would be great!

**Comment by jamesgk** [comment]
I started a branch for this:
https://github.com/jamesgk/assimp/tree/gltf2-export

One issue for now is that, rather than duplicating most of the glTF 1 exporter, I modified it to export glTF 2. So on this branch it's no longer possible to export glTF 1. I also have not implemented glTF 1 importing.

**Comment by dhritzkiv** [comment]
Sweet!

I think it'd be important to still support glTF v1, for legacy reasons, especially on import. I wonder if it'd be easy to sniff the version and then choose the right Parser/Importer.

The default version for glTF export should be v2, but v1 export might be specified via the format option: `--format=gltf1`

**Comment by realvictorprm** [comment]
@dhritzkiv is this in a working state?

**Comment by dhritzkiv** [comment]
Hi @realvictorprm. I'm not working on this feature - I merely suggested it. See @jamesgk's [work on glTF 2 support](#issuecomment-311746189) so far. It likely has some work to go before being integrated into assimp

**Comment by jamesgk** [comment]
Yes, this definitely needs more work. I was just going to push some
fixes to animation exporting but then Daniel's suggestions still need
to be implemented.

**Comment by jamesgk** [comment]
An update: on a new branch I separated glTF1 and 2 into two (largely duplicated) exporters, so now at least the glTF2 exporter should be mergeable: https://github.com/jamesgk/assimp/tree/gltf2.

**Comment by realvictorprm** [comment]
Thank you for your effort. I always appreciate open source work even if I'm not working mainly in the repo. If you need any help because you have no time don't hesitate to tell me.

**Comment by jamesgk** [comment]
@realvictorprm thanks! I probably won't have time in the near future to work on glTF 2 importing. So if there's much demand for that, any help would be welcome.

**Comment by jcowles** [comment]
FYI, glTF 2.0 seems to be the only future for glTF.

New tools being developed are already starting to favor 2.0, some even lacking 1.0 support entirely.

That said, yes, 1.0 and 2.0 would be ideal.

**Comment by dhritzkiv** [comment]
Hi @jcowles. glTF2 export functionality is in assimp master, and there's some work from me to add glTF2 imports as well, here: #1423

**Comment by pjcozzi** [comment]
@dhritzkiv all of us working on the glTF spec are excited to see glTF 2.0 support in assimp!  Is there any documentation on the extent of glTF 2.0 supported, roadmap, and anything Khronos can do to help?

**Comment by dhritzkiv** [comment]
Thanks @pjcozzi!

In terms of assimp's support of glTF 2.0: much of the core parts of the spec are implemented: 

- asset
- buffers
   - except GLB - see below
- bufferViews
- scenes / scene
- nodes and meshes
- images
   - both via external uri and embedded base64-encoded data uris
   - unsure about referencing via bufferViews. I think it's in there
- textures
- materials
   - the basic properties, pbrMetallicRoughness and the pbrSpecularGlossiness extension are fully implemented.
- accessors, sort of - see next section
- I'm unsure about cameras support. I think it's in there.

What remains to be implemented/fixed is this functionality:

-  binary_glTF†
   - I started work on it [here a while ago,](https://github.com/Matter-and-Form/assimp/tree/feature/gltf2-binary) but I've not gotten far.
- animations/joints/skins/morph targets (and by extension, their accessors)
   - assimp currently outputs some data for these, but it's copied from assimp's glTF 1.0 implementation, so it's incorrect
- sparse accessors 

I didn't get around to fixing these, partly due to it not being a priority for my use cases, and partly because I'm unfamiliar with it.

Persisting `name` properties is a bit inconsistent, and `extras` properties also should be serialized and persisted.

---

glTF 2.0 extension implementations that are on the road map include:

- KHR_material_common/KHR_materials_cmnBlinnPhong
- lights
- Draco compression (to replace the now removed Open3DGC compression)

I think we'll wait until the extension specs are finalized before implementing these.

Speaking of KHR_material_common: several of us (in #1423) were unclear as to the state of KHR_material_common (or its equivalent) for glTF 2.0, partly due to to scattering of issues/PRs that address it, and the moving-target/ work-in-progress implementations in other loaders (namely three.js). As I understand it, the current plan is to implement a "common material" via KHR_materials_cmnBlinnPhong, yes? Is this the PR that we should be following:  [KhronosGroup/glTF#1075](https://github.com/KhronosGroup/glTF/pull/1075#issuecomment-328408375)?

---

As for further help, it'd be appreciated if Khronos was able to verify the correctness of the export functionality (and import too, for that matter) of glTF 2 models. I tested against most of the models from the Khronos sample repo, and most pass the glTF validator with flying colours. The ones with animations/joints/skins/morphTargets present many errors.

If there's any interest from Khronos members in contributing further code and fixes, please do!

**Comment by jcowles** [comment]
Awesome.

However, testing master with a random glTF 2.0 file I grabbed from SketchFab, I'm getting a segfault with this stack:

![image](https://user-images.githubusercontent.com/1510114/30516723-e1f6a9f8-9afb-11e7-9d51-b2ad2c3f6b62.png)

**Comment by dhritzkiv** [comment]
Mind linking that model? I could try tracking the crash down

**Comment by jcowles** [comment]
Here you go:
https://sketchfab.com/models/dded7949a3db4ba4a09ef3ddbd13f319

**Comment by dhritzkiv** [comment]
I couldn't reproduce the crash on my end. Could it be platform dependent? I think there were some recently discovered issues with MSVC builds. (In which case, I'll let those with Windows experience address that) It could also be a general memory bug that might happen to surface on your machine.

---

That being said, the model didn't export perfectly: the tires, lights, and undercarriage are missing.

![screen shot 2017-09-16 at 20 11 28](https://user-images.githubusercontent.com/1349865/30516927-537992f6-9b1b-11e7-949f-85b28e3f673b.png)

So, good test model (though, I have some simpler ones that might be easier to debug). I suspect that it may to do with having multiple primitives per mesh (a pretty glaring implementation omission on my part, if true).

**Comment by jcowles** [comment]
Well, it's odd that my glTF 1.0 and OBJ files load fine, but the new glTF 2.0 loader crashes.

Also, given that the MSVC run-time is killing the process, it definitely looks like a memory bug.

**Comment by dhritzkiv** [comment]
I'll try to take a crack at the memory bug on Monday when I'm at my workstation with better tools

**Comment by jcowles** [comment]
Alright, if I get inspired, I may take a look tonight too (doubtful though).

**Comment by jcowles** [comment]
Also, the point at which it crashes is non-deterministic, if I run my script several times, it will crash with different stacks.

**Comment by jcowles** [comment]
To to fully exclude my code, I tried this with assimp.exe and it also crashes.

**Comment by jcowles** [comment]
Ok, one last bit of information, the assimp.exe validator crashes on this:

    void ValidateDSProcess::Validate( const aiNode* pNode)
    {
        if (!pNode)ReportError("A node of the scenegraph is NULL");
        if (pNode != mScene->mRootNode && !pNode->mParent)  // < Crash here on pNode->mParent

Looks like pNode is not equal to mRootNode and it's pointing at some illegal memory location (not null).

**Comment by jcowles** [comment]
Your oversight comment above is exactly what's happening, in this code, it assumes exactly one primitive, allocates one mesh, but then proceeds to write multiple meshes, corrupting memory:

    if (node.mesh) {
        ainode->mNumMeshes = 1;
        ainode->mMeshes = new unsigned int[1];

        int k = 0;
        int idx = node.mesh.GetIndex();

        for (unsigned int j = meshOffsets[idx]; j < meshOffsets[idx + 1]; ++j, ++k) {
            ainode->mMeshes[k] = j;
        }
    }

In glTF, primitives are [effectively draw calls](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes), so it seems extremely common that meshes will have multiple primitives.

**Comment by dhritzkiv** [comment]
Got catch.

I've tracked it down to this commit: a0d97505e5a53a9aa3a734d6bd3ad790234e6e09

Reverting it works, however, now nodes reference multiple `meshes with one primitive instead of one mesh with multiple primitives. Should be an easy fix, I think, though I don't quite know where to start. Probably in glTF2Exporter::ExportMeshes. I'll take another look tomorrow.

**Comment by jcowles** [comment]
If primitives all have the same material and mode, they could be flattened into a single mesh, I think.

However, since Assimp doesn't support face material bindings, you must also support the code path where the material/pipeline state inst shared between primitives, which means having multiple meshes for a single node. This seems like a good starting point, since it has to be implemented as the fallback anyway.

**Comment by jcowles** [comment]
Oh hey, the fix is easy:

![image](https://user-images.githubusercontent.com/1510114/30523021-5c65556c-9b8e-11e7-9702-b76980b12ea8.png)

Should I send a PR?

**Comment by dhritzkiv** [comment]
@jcowles yes, please!

I've spent the last hour wracking my brain on how to flatten the meshes' primitives into a single mesh with multiple primitives, in code (I'm not too nimble with C++), so I'd love to see, and possibly use your solution.

**Comment by jcowles** [comment]
There you go!

**Comment by jcowles** [comment]
Oh, hrm, it's also kind of a bummer that this implementation throws away all the glTF node names.

**Comment by pjcozzi** [comment]
Wow, @dhritzkiv, thanks for all the details in https://github.com/assimp/assimp/issues/1301#issuecomment-329988412!

> Speaking of KHR_material_common: several of us (in #1423) were unclear as to the state of KHR_material_common (or its equivalent) for glTF 2.0, partly due to to scattering of issues/PRs that address it, and the moving-target/ work-in-progress implementations in other loaders (namely three.js). As I understand it, the current plan is to implement a "common material" via KHR_materials_cmnBlinnPhong, yes? Is this the PR that we should be following: KhronosGroup/glTF#1075?

The plan is still to separate out lights and materials from the glTF 1.0 `KHR_material_common` extension.

As for the tweaks in https://github.com/KhronosGroup/glTF/pull/1075#issuecomment-328408375 and renaming `KHR_materials_cmnBlinnPhong` to ` KHR_materials_common`, I do not know if this was confirmed.

@donmccurdy @UX3D-nopper do you know?

> As for further help, it'd be appreciated if Khronos was able to verify the correctness of the export functionality (and import too, for that matter) of glTF 2 models.

I bet we can find some help.  I will ask around!

> If there's any interest from Khronos members in contributing further code and fixes, please do!

Nice, will also ask around!

**Comment by donmccurdy** [comment]
> as for ... renaming `KHR_materials_cmnBlinnPhong` to `KHR_materials_common`, I do not know if this was confirmed.

Not sure yet; I would hold off on implementing common materials a bit. Feedback on the issue is very welcome, though!

**Comment by Warezovvv** [comment]
Where can I try assimp gltf 2.0 importer? Because now I have error that no importer found for this format, where format is .gltf

**Comment by dhritzkiv** [comment]
Are you using recent code from master on Github? The releases don’t include gltf 2 importing.

**Comment by Warezovvv** [comment]
Yeah, Im fighting with this issue right now https://github.com/assimp/assimp/issues/1566
Thats why Im tried libassimp-dev and gltf not imported.
I just downloaded assimp and build it from sources, checked in asssimp_qt_viewer and everything works.
Do you know how to solve that problem?
Thanks

**Comment by Warezovvv** [comment]
Ehm. Also main question is how to load metalrougness material?

**Comment by Tim4135** [comment]
Has it been released as a official release yet?

**Comment by m0nologuer** [comment]
This seems like a great feature! What can we do to make it happen!

**Comment by dhritzkiv** [comment]
@Tim4135 @m0nologuer This is part of at least the [4.1.0 release](https://github.com/assimp/assimp/releases/tag/v4.1.0). However, there have been more features and improvements to glTF2 features in the many commits since.

**Comment by EvilPudding** [comment]
Does external binary import glTF2 work? Do animations on glTF2 work at all right now?

**Comment by singhraj82** [comment]
Is glb for glTF2.0 supported in current assimp version? Or is it expected to be supported in 5.0 release ?
