### ISSUE TITLE
Do I need to manually flip/rotate .blend files on import?

### ISSUE THREAD

**Issue by vexe** [assimp/assimp#1303]
Greetings,

I have a simple .blend level which looks like it's flipped when importing with Assimp:

![wtf](https://user-images.githubusercontent.com/1978827/27004291-af7bb2da-4dd4-11e7-8ac4-a41668da00bc.png)

Shouldn't Assimp be handling this on its own on import? or do I need to manually rotate/flip things?

Here's how I'm loading the model, converting it to a runtime format for my engine:

    // vertices, normals and uvs
    {
        u32 VertexCount = SrcMesh->mNumVertices;
        u32 ByteCount = VertexCount * sizeof(f32) * 3;

        DstMesh->VerticesCount = VertexCount;
        DstMesh->Vertices = new vec[VertexCount];
        memcpy(DstMesh->Vertices, SrcMesh->mVertices, ByteCount);

        FAIL_IF_NOT(SrcMesh->mNormals, "Model doesn't have normals");
        DstMesh->Normals = new vec[VertexCount];
        memcpy(DstMesh->Normals, SrcMesh->mNormals, ByteCount);

        FAIL_IF_NOT(SrcMesh->mTextureCoords[0], "Model doesn't have UVs");
        DstMesh->UVs = new vec[VertexCount];
        memcpy(DstMesh->UVs, SrcMesh->mTextureCoords[0], ByteCount);
    }

    // faces
    {
        DstMesh->FacesCount = SrcMesh->mNumFaces;
        DstMesh->Faces = new mesh_face[DstMesh->FacesCount];
        For(i32, F, DstMesh->FacesCount)
        {
            aiFace *SrcFace = &SrcMesh->mFaces[F];
            mesh_face *DstFace = &DstMesh->Faces[F];
            FAIL_IF_NOT(SrcFace->mNumIndices == 3, "Model is not triangulated. Face index %d has %d indices", F, SrcFace->mNumIndices);
            memcpy(DstFace->Indices, SrcFace->mIndices, 3 * sizeof(u32));
        }
    }

Note I also tried finding the node that mesh's belong to, and transforming the vertices/normals by that node's final transform (by final I mean I recurse all the node's parents and apply their transforms and finally the node's local transform) -- But that didn't do anything because the mesh has no parent.

Here's the referenced model: https://www.dropbox.com/s/hwsyfyqip5pqhrh/StusRoom.blend?dl=0

Thanks for any help!

**Comment by kimkulling** [comment]
Did you take the transformation info stored in the corresponding node into account as well?

**Comment by vexe** [comment]
Yep, or at least I thought so. Here's what I'm doing:

        // loading code
        if (DstModel.Header.Flags & Model_Flag_Level)
        {
            aiNode *Node = FindMeshNode(SrcModel->mRootNode, 0);
            m4x4 Transform = GetNodeFinalTransform(Node);
            ForI(DstMesh->VerticesCount)
            {
                DstMesh->Vertices[i] = mul4(&Transform, DstMesh->Vertices[i]);
                DstMesh->Normals[i] = mul3(&Transform, DstMesh->Normals[i]);
            }
        }

    // functions
```
aiNode *FindMeshNode(aiNode *Node, i32 MeshIndex)
{
    aiNode *Result = 0;

    ForI(Node->mNumMeshes)
    {
        u32 It = Node->mMeshes[i];
        if (It == MeshIndex)
        {
            Result = Node;
            break;
        }
    }

    if (!Result)
    {
        ForI(Node->mNumChildren)
        {
            var Child = Node->mChildren[i];
            Result = FindMeshNode(Child, MeshIndex);
            if (Result)
            {
                break;
            }
        }
    }
        return(Result);
    }

```
m4x4 GetNodeFinalTransform(aiNode *Node)
{
    aiMatrix4x4 Result;

    aiNode *Current = Node;
    do
    {
        aiMultiplyMatrix4(&Result, &Current->mTransformation);
        Current = Current->mParent;
    }while(Current);

    return ToMat(Result);
}
```

**Comment by vexe** [comment]
Also looking at the level node transform matrix in the debugger, it's the identity matrix.

**Comment by kimkulling** [comment]
This is funny!

**Comment by vexe** [comment]
@kimkulling I'm not sure what you mean?

**Comment by kimkulling** [comment]
I do not understand the issue, a funny fact, you know ;-) ...

**Comment by vexe** [comment]
I'm not sure how else to explain it, but I'll try again...

-I'm trying to import a level mesh from Blender
-Blender uses as forward and Z as up, and there doesn't seem to be any options to change that on export
-My engine uses Y as up and Z as forward
-Upon importing with Assimp, the level transform matrix is the identity matrix, so even if I were to apply the nodes transforms to the level, it wouldn't change anything.
-As a result, when loading the level in engine it appears to be rotated/not aligned correctly.
-I have to manually rotate it 90dgs on X and 180dgx on Y (Blender's Z) upon import.
-My question is: Shouldn't Assimp handle this for me and populate the level transform matrix to align the mesh correctly?

It this clear enough, or is still funny?

**Comment by kimkulling** [comment]
What you need to do is rotate your scene into your own coordinate system. You can use aiMatrix4x4::Rotation for instance. And sorry for my late response, I lost list conversation in my e-mail-folder.
And thanks a lot for your detailed description, helped a lot to get a beter understanding of your issue.
