### ISSUE TITLE
reopen the issue assimp Subdivider

### ISSUE THREAD

**Issue by eugenelyj** [assimp/assimp#1317]
i compile the whole assimp code, and include <assimp/Subdivision.h>,
then i use `Subdivider* sub = Subdivider::Create(Subdivider::CATMULL_CLARKE);`, which is said not undefined.
However, the following code `	sub->Subdivide(scene->mMeshes, scene->mNumMeshes,
        scene->mMeshes, num,
        true);` is OK.
who can tell me what's wrong with it, thanks.

reopen issue #1292

**Comment by kimkulling** [comment]
Done!
