### ISSUE TITLE
Assimp does not compile if all exporters are disabled

### ISSUE THREAD

**Issue by nem0** [assimp/assimp#1320]
Steps to reproduce:
1. disable all exporters (define all ASSIMP_BUILD_NO_*_EXPORTER)
2. try to compile the project
3. observe following error

```
assimp\code\exporter.cpp(154): error C2466: cannot allocate an array of constant size 0
```

**Comment by nemerle** [comment]
This problem still appears in Assimp 5.0.0 ( Visual Studio 2017/15.9.6)

**Comment by AlexApps99** [comment]
I'm still getting this issue...
