### ISSUE TITLE
PLY with TextureFile reference that starts with a number breaks parsing

### ISSUE THREAD

**Issue by dhritzkiv** [assimp/assimp#1324]
This works:

`$ assimp export laurana500_with-string.ply output.obj`
 
where the ply contains this line:

```ply
comment TextureFile laurana500.png
```

Whereas this does not:

`$ assimp export laurana500_with-number.ply output2.obj`

where the ply contains this line:
```ply
comment TextureFile 5.png
```

The parser begins parsing the `5` as another type of line. I believe this behaviour was introduced in #1293

[I've attached some test files.](https://github.com/assimp/assimp/files/1107057/laurana.zip) (The actual texture files are unimportant, but are included anyway)

**Comment by kimkulling** [comment]
Hi,

thanks a lot for the report. Seems to be fixed. I tried both versions and both worked on my linux dev-box ( Ubuntu 16.04 with g++ ). I fixed a serious issue regarding the block-wise import of ply-files and this fix seems to be the solution for this issue as well.  
Could you please reopen the issue if it*s still there on your side? Thanks a lot!

**Comment by dhritzkiv** [comment]
Can confirm that this has been fixed. Thanks!

**Comment by dhritzkiv** [comment]
@kimkulling Hi. I lied about it being fixed (I had the wrong version checked out). It still produces unexpected results when the `comment TextureFile` line has a file name that starts with a number.

The results are better (actually produces some geometry, but still wrong, inserting extra vertexes).

Building 7fd9c3d on macOS with clang
