### ISSUE TITLE
Too many warnings on both gcc and clang.

### ISSUE THREAD

**Issue by volcoma** [assimp/assimp#1330]
Hi, the current state of the library has too many warnings under gcc and clang. And that is with the default flags of the compilers. It floods the compile output

**Comment by gongminmin** [comment]
Actually on msvc, too.

**Comment by joelteply** [comment]
mostly the CMAKE_FORCE_COMPILER stuff on clang for me, yeah

**Comment by kimkulling** [comment]
Ongoing...

**Comment by jaredmulconry** [comment]
@gongminmin Under the default settings, MSVC in x86 and x64 generate very few warnings at HEAD. What is the commit id that you are compiling at?

**Comment by kimkulling** [comment]
I guess I will close this one.
