### ISSUE TITLE
How can I get the real pivot position of a node?

### ISSUE THREAD

**Issue by lilysara** [assimp/assimp#1336]
How to use assimp to obtain the real position of the pivot point?

The position I got is the same with Maya Channel Box, but I want to know the true location of the pivot point when it has been changed with the key [D] in Maya or the transform has been frozen.

The node position should be the same with Transform Component in unity.

Thanks!

**Comment by kimkulling** [comment]
At the moment asset-importer-lib does not store this informatio. Is this information part of any asset-format? If yes: we can provide this as a meta information. I do not know which asset-format does provide this. Any hint where to look at would be really useful.

And sorry for my late response, I am less on free time at the moment.
