### ISSUE TITLE
Assimp 3.3.1 invalid memory write when loading mesh

### ISSUE THREAD

**Issue by Martin-Schultz** [assimp/assimp#1349]
I am Trying to use Assimp to import Meshes into OpenFlipper (http://openflipper.org/)

Unfortunately Assimp 3.3.1 frequently segfaults, because of invalid heap memory writes.

I ran Valgrind and tried to import the attached model of the stanford dragon

The output of valgrind implies a bad memory write in MaterialSystem.cpp:497 as well as invalid memory read in MaterialSystem.cpp:446

[dragon870k2..zip](https://github.com/assimp/assimp/files/1151848/dragon870k2.zip)
[valgrind_out.txt](https://github.com/assimp/assimp/files/1151854/valgrind_out.txt)

Edit: I also observed segfaults when using other file formats such as .stl 
my operating system is Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

**Comment by kimkulling** [comment]
Thanks for the report, I will take a look.

**Comment by jaredmulconry** [comment]
I've read through the output from Valgrind and compared that to the relevant lines in Assimp as of 3.3.1.
Valgrind seems to believe that mNumProperties and mNumAllocated inside of aiMaterial are both equal 0 when it comes time to allocate more space for material properties in the AddBinaryProperty method.

Unless the default constuctor for aiMaterial isn't being run, I can see no scenario where both mNumProperties and mNumAllocated could be 0. This may come from some deeper issue.

I was not able to replicate this issue with an x64 build on Windows.

**Comment by Martin-Schultz** [comment]
Thank you very much for checking.
Your hint with the default constructor made me look at the plugin again and it seems, that my predecessor and initial author did write his very own constructor for  aiMaterial. see line 56-60
https://www.graphics.rwth-aachen.de:9000/OpenFlipper-Free/OpenFlipper-Staging/blob/master/PluginCollection-FilePlugins/Plugin-Assimp/AssimpPlugin.cc

My apologies for bothering you, i should have seen that myself before.
Now i know what to do, you can probably close this issue.

**Comment by kimkulling** [comment]
@jaredmulconry: Thanks a lot for your help.

I will close the issue.
