### ISSUE TITLE
OBJExporter is duplicating mesh names

### ISSUE THREAD

**Issue by socceroos** [assimp/assimp#1351]
When running an OBJ through the OBJ exporter, the mesh names are all duplicated. If you take the output of an exported OBJ and then run it through AssImp OBJExporter again it will further duplicate the mesh names. They continue to double every time it is run through the exporter.

The line causing the issue is here: https://github.com/assimp/assimp/blob/master/code/ObjExporter.cpp#L351

I fixed this issue for us by changing the line to this: mesh.name = std::string(name.data,name.length);

**Comment by kimkulling** [comment]
Fixed, thanks a lot for the hint!
