### ISSUE TITLE
FIReader.cpp stopping compilation on Android

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#1361]
FIReader.cpp is stopping Android compilation.
The compiler won´t find std:: string methods.
I've made a workaround that allow me to compile, but I haven´t tested the reader yet:
https://pastebin.com/dANggz8i

**Comment by pdaehne** [comment]
This is a known issue of the Android SDK - see https://github.com/android-ndk/ndk/issues/82.

**Comment by rickomax** [comment]
Thanks for pointing out :)
