### ISSUE TITLE
Heap corruption in version 3 and above

### ISSUE THREAD

**Issue by rajasrijan** [assimp/assimp#1367]
While trying to export collada models I kept getting heap corruption. Even very basic code is causing corruption.

```
int main()
{
        aiScene *scene=new aiScene;
        scene->mRootNode = new aiNode();
        delete scene;
}
```

running same code on 2.0.863 dosent give any corruption.
If any more information is needed please let me know.

**Comment by kimkulling** [comment]
How did you measure the heap corruption? Valgrind? I do not get a segfault using linux.

**Comment by rajasrijan** [comment]
sorry I missed your reply, gmail filtered notification for some reason. I used AppVerifier under windows 10.

**Comment by kimkulling** [comment]
Do you have nay information like a model to reproduce this issue? I tried this under Win10 on 2 machines and the error did not occur :-( .

**Comment by rajasrijan** [comment]
Sry, no model. I was trying to make basic exporter and creating aiScene from scratch. I'll try to reproduce again under different environment.

**Comment by rajasrijan** [comment]
I've consistent crash on VS2015 Win10, but none on VS2015 Win 7 & 8.1 .
I don't have Win10 anymore so I cant attach dumps. I'll close the issue.

**Comment by rajasrijan** [comment]
That's seems like the most likely explanation.

**Comment by RumbleballTheReal** [comment]
> 
> 
> I just found this issue via Google search when trying to solve the same problem.
> 
> We had exactly the same problem, `delete` of an `aiScene` that we created ourselves (without an importer) caused heap corruption (_Critical error detected c0000374_). Turned out the problem was most likely caused by using a Release .dll of Assimp in a Debug version of our application.
> 
> **Solution:** use Release .dll with Release builds and Debug .dll with Debug builds of your own .exe

Thank you, just came across the same issue. Do you have any insight into this? Whats the difference between debug build and non debug? As the code of assimp is not related to the code of our application (UnrealEngine Probject), there shouldn't be any problem?

.dlls are still foreign territory for me.

**Comment by RumbleballTheReal** [comment]
I build the debug and release version for x64 and still get the crash with the debug, though more information.

The crash occours when deleting the aiNode::mMeshes array in the destructor

![AssimpCrash](https://user-images.githubusercontent.com/41473331/62488540-ccdcb480-b7c4-11e9-85a1-f692108568e4.png)
![AssimpCrash2](https://user-images.githubusercontent.com/41473331/62488543-cea67800-b7c4-11e9-8a9a-e2a128033953.png)

**Comment by tomasiser** [comment]
I suggest you make sure both your application and Assimp .dll are built using the same configuration. I have no idea what exactly could cause problems, but maybe you have some compiler definitions set in your application that are not set in Assimp?

More info about mixing debug/release: https://stackoverflow.com/questions/11658915/mixing-debug-and-release-library-binary-bad-practice

**Comment by RumbleballTheReal** [comment]
Thank you @tomasiser 
I created a new issue here: https://github.com/assimp/assimp/issues/2580
