### ISSUE TITLE
Write more tutorials

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1369]
Just a reminder to write some more tutorials.

**Comment by aggsol** [comment]
Idea: How to use assimp as exporter from custom 3D data? Data format, vertices, materials, UV mapping etc.

**Comment by kimkulling** [comment]
Ongoing, please check the Developer guide on our ReadTheDocs project. 

See https://assimp-docs.readthedocs.io/en/latest/developer/developer.html

And everybody can contribute their own implementations here as well!
