### ISSUE TITLE
IOStream seek prototype

### ISSUE THREAD

**Issue by doomtr666** [assimp/assimp#1372]
Hi,
In IOStream.h seek is defined as this:

`    virtual aiReturn Seek(size_t pOffset, aiOrigin pOrigin) = 0;`

pOffset can't be negative (in fseek it's a signed long int). Can this cause issues with some file types ?

**Comment by kimkulling** [comment]
Yes! Thanks for the hint!

Christophe Delacourt <notifications@github.com> schrieb am Fr., 4. Aug.
2017, 11:40:

**Comment by kimkulling** [comment]
Just checked it. Using int instead of size_t will cause a major performance issue because the file pointer must restart to go throught the file.
So using size_t is the rght chhoise for us. I will close this issue. 

Thanks a lot for figuring this out!
