### ISSUE TITLE
Node Hierarchy and mTransformation accumlation

### ISSUE THREAD

**Issue by papertype** [assimp/assimp#1373]
I don't know this is an issue, probably not, but let me ask anyway.

The sample pseudocode about The Node Hierarchy in [Data Structures page](http://assimp.org/lib_html/data.html) is accumlating mTransformation like
`transform = node.mTransformation * accTransform;`

But [this popular tutorial](http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html) is accumulating mTransformation like
`GlobalTransformation = ParentTransform * NodeTransformation;`
which is equivalent to
`transform = accTransform * node.mTransformation;`

In practice, the latter works correctly. Is the former just wrong? Am I missing something?

**Comment by kimkulling** [comment]
You have to multiply 

`transform = node.mTransformation * accTransform;`

as far as I know and as we did it in our own viewer.
