### ISSUE TITLE
[FEATURE REQUEST] Are Animation Meshes coming to Assimp

### ISSUE THREAD

**Issue by nickclark2016** [assimp/assimp#1374]
I am looking to do stuff like blendshapes/bindposes, where interpolation between meshes/vertices is preferred.  Will Assimp being adding support for aiAnimMesh in the future?  I notice that the struct is in the documentation, but it is listed as "NOT CURRENTLY IN USE".  Thanks!

**Comment by kimkulling** [comment]
Any usecase how to use it? Would help a lot! Thanks, kin

Nick Clark <notifications@github.com> schrieb am Sa., 5. Aug. 2017, 23:18:

**Comment by nickclark2016** [comment]
It would be useful for things such as facial animations.  Bones do not work well in those cases.

**Comment by kimkulling** [comment]
Good point, thanks for providing the idea.

Nick Clark <notifications@github.com> schrieb am Mi., 9. Aug. 2017, 17:19:

**Comment by nickclark2016** [comment]
Is there any update on this?

**Comment by ChenFengYe** [comment]
Is there any solution to load blendshape with assimp?

**Comment by kimkulling** [comment]
Yes, for the FBX-loader first.
