### ISSUE TITLE
How to export non-'shortened' files?

### ISSUE THREAD

**Issue by makc** [assimp/assimp#1377]
I am trying to open assimp files in three.js, but their loader does not support shortened files. Both `assimp export my.file to.assbin` and `assimp export my.file to.assimp` command lines generate shortened files. Assimp says there is `-f` option to control format, but I cannot look up its values, because chm file you have with docs does not properly open on windows machine I use (I only see toc/search but not actual content). Please advice, thanks

**Comment by kimkulling** [comment]
I guess you have to ask the three.js guys if this option is implemented
cortectly. Of course you can take the prebuild binaries from our website
and use assimp directly with the -f option.

makc <notifications@github.com> schrieb am Mi., 9. Aug. 2017, 14:28:

**Comment by makc** [comment]
right, but it was more like what should I put after -f to create non-shortened version?

**Comment by makc** [comment]
ok, nvm, seems like they have found an issue on 3js side.
