### ISSUE TITLE
import two fbx file parsing error.

### ISSUE THREAD

**Issue by qwe5788319** [assimp/assimp#1379]
[test1.fbx](http://pan.baidu.com/s/1bp1utmZ)
[test2.fbx](http://pan.baidu.com/s/1kUFaYb1)

import two fbx file parsing error.

Give you test.

**Comment by kimkulling** [comment]
Ok, thaks for the report. Which kind of error did occurr?

**Comment by qwe5788319** [comment]
[error_1](http://chuantu.biz/t5/168/1502498672x993376187.png)
[error_2](http://chuantu.biz/t5/168/1502498750x993376187.png)

**Comment by kimkulling** [comment]
Ok, thanks for the reproducable testcases.

**Comment by mesilliac** [comment]
I think this should be fixed by #1806

**Comment by kimkulling** [comment]
Ok, I will close the issue.
