### ISSUE TITLE
aarch64: c++11 narrowing error from int8_t to char initializer list

### ISSUE THREAD

**Issue by othercorey** [assimp/assimp#1386]
This issue is occurring with the aarch64 target using clang 3.8.  I am unable to reproduce it for the x64 target, and cannot explain the difference in behavior.  Hopefully, the issue is simple enough that a patch can be made regardless.

In BlenderDNA.cpp, match4() initializes a char array with int8_t values.  This triggers a c++11 narrowing in initializer list error.

`
bool match4(StreamReaderAny& stream, const char* string) {
    char tmp[] = {
        (stream).GetI1(),
        (stream).GetI1(),
        (stream).GetI1(),
        (stream).GetI1()
    };
    return (tmp[0]==string[0] && tmp[1]==string[1] && tmp[2]==string[2] && tmp[3]==string[3]);
}
`

> BlenderDNA.cpp:58:9: error: non-constant expression cannot be narrowed from type 'int8_t' (aka 'signed char') to 'char' in initializer list [-Wc++11-narrowing]

I couldn't find any explanation for this discrepancy other than a note that char and signed char are separate types according to the spec.  This would suggest x64 *should* throw the same error.

> Plain char, signed char, and unsigned char are three distinct types, collectively called narrow character types. 

If the GetI1() value was cast to char this would go away.

**Comment by turol** [comment]
That's also undefined behavior since there's no sequence points between the `GetI1()` calls. The compiler would be well within its rights to reorder them however it pleases. You should just get rid of the array completely.

**Comment by kimkulling** [comment]
I guess there are ways to fix this. We can replace the array by a different construct.

**Comment by othercoreytaylor** [comment]
You can still use an array, but don't use the initializer list.
