### ISSUE TITLE
"FBX" file importing Error : out of range in function "ToOutputVertexIndex()"

### ISSUE THREAD

**Issue by ShareZzx** [assimp/assimp#1387]
The link includes the fbx file which occurs the error of accessing the end of the m_mappings in function ToOutputVertexIndex(). I have debugged into the source file and found that some vertices were not used in geometry object. When it happends, the output vertex count is zero. I hope this description would be helpful. Thanks a lot.
 
[robot.zip](https://github.com/assimp/assimp/files/1227318/robot.zip)

**Comment by ShareZzx** [comment]
Additionally, this fbx file can be loaded into open3mod, but the animation is not correct.

**Comment by kimkulling** [comment]
I guess the animation issue depends on a wrong interpreted animation behaviour introduced by the transformation chain implemented in assimp. This will be handled in a different issue already.

Thanks for the report!

**Comment by ShareZzx** [comment]
thanks a lot.
