### ISSUE TITLE
FBX exporter feature

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1388]
We shall be able to export an aiScene to fbx ( ASCII first )<.

**Comment by undisputed-seraphim** [comment]
How about an assimp-backed Maya plugin? That way, a user can open any file that assimp supports with Maya. It is even possible to save files from Maya into any format that assimp supports.

**Comment by mesilliac** [comment]
PR for FBX export: https://github.com/assimp/assimp/pull/1804

No animations nor cameras nor lights yet, but basic model support (including bones and skinning) seems to work.

I started with binary-only, but ascii output should be fairly easy to add

**Comment by kimkulling** [comment]
Just merged to master.
