### ISSUE TITLE
Build broken "‘AI_CONFIG_IMPORT_FBX_SEARCH_EMBEDDED_TEXTURES’ was not declared in this scope"

### ISSUE THREAD

**Issue by Sailsman63** [assimp/assimp#1402]
This line breaks compilation locally for me: https://github.com/assimp/assimp/blob/3a89e36718c4c7bf151cf82f629e2b96925f2473/code/FBXImporter.cpp#L134

Full Error message: 

```
FBXImporter.cpp:134:58: error: ‘AI_CONFIG_IMPORT_FBX_SEARCH_EMBEDDED_TEXTURES’ was not declared in this scope
settings.searchEmbeddedTextures = pImp->GetPropertyBool(AI_CONFIG_IMPORT_FBX_SEARCH_EMBEDDED_TEXTURES, false);
```

Build Chain:

CMake 3.8.2
GNU Make 4.2.1 for x86_64
GCC 7.1.1 20170630

Cmake flag -DASSIMP_BUILD_ZLIB=ON

Arch Linux

**Comment by Sailsman63** [comment]
Not a CPP programmer, so I don't know what to check.

**Comment by kimkulling** [comment]
I will take take, thanks for the report.

Sailsman63 <notifications@github.com> schrieb am Do., 24. Aug. 2017 um
05:58 Uhr:

**Comment by rickomax** [comment]
Its declared on https://github.com/assimp/assimp/blob/master/include/assimp/config.h.in.
Please rebuild your project from CMAKE and try again.

**Comment by Sailsman63** [comment]
I always rebuild from CMAKE.

Due to file-system constraints (Source directory does not support sym-links) I do an out of source build (CMAKE cache, and build artifacts, in a separate root dierectory)

Every time that I rebuild, I run the following in my build directory:

```
make clean
rm CMakeCache.txt
cmake -DASSIMP_BUILD_ZLIB=ON /Path/to/Source/directory
make
```

This generates the makefiles, etc. in my preferred build directory, rather than trying for an in-source build, which is just nasty.

**Comment by Sailsman63** [comment]
Huh.... Seems to have resolved on my machine after several test builds, and a `git bisect` attempting to find where the problem began.

Closing for now.

**Comment by typhomnt** [comment]
Actually, I have the same problem as you when updating from commit 919f2a1ea969d46ac329afa736869d3a374e0ba1 to the current state of master (and rebuilding from CMAKE of course).

How did you manage to solve this build issue ?

I am building with cmake 3.4.1 and gcc 4.8.4, on Ubuntu 14.04 LTS.

Thanks.

**Comment by Sailsman63** [comment]
I'm not sure how this got resolved. I would start by running `make clean` and then `rm CMakeCache.txt` to force a clean build.

Mine cleaned up during a `git bisect`, so perhaps roll back to a commit before 919f2a1, and then build, checkout the next commit up, rebuild? Not sure why this happened in the first place. If you had not posted that you have the same issue, I would have chalked it up to a glitch in the pull process or something....

**Comment by kimkulling** [comment]
The symbol is defined in the generated config.h file. Depending on your
config this will be generated by the cmake run. So when there is something
new in config.h.in just run a new cmake run shall fix the issue.

Kim

Sailsman63 <notifications@github.com> schrieb am Fr., 27. Okt. 2017, 03:45:

**Comment by Sailsman63** [comment]
And that's why this was so baffling to me. I _always_ do a new cmake run when pulling updates. (Including deleting the CMakeCache.txt file)

Regardless, its working for me now, so I'll let it rest.

**Comment by typhomnt** [comment]
Thank you guys, I managed to fix the problem but it was trickier than I thought.

I don't know why I had an old config.h file inside the assimp/include/assimp/ directory (in the sources) (maybe because of an old generating method in the CMakeList ?). Because I forgot to remove this old config.h, whenever the compiler encountered #include<assimp/config.h>, it included this old file instead of the new generated one (inside the build directory).

typhomnt.

**Comment by kimkulling** [comment]
Thanks for the explanation about your issue.

**Comment by kimkulling** [comment]
We moved the place where this file will be generated. Maybe this is a little bit error prone.

**Comment by Sailsman63** [comment]
>I had an old config.h file inside the assimp/include/assimp/ directory

Hmm... Makes a certain amount of sense. When I had this issue, it was directly after trying a standard in-source build, which is not something that I normally do.
