### ISSUE TITLE
How can I export gltf2.0 use pyassimp? 

### ISSUE THREAD

**Issue by spexial** [assimp/assimp#1411]
I use pyassimp export gltf is successful:
pyassimp.export(scene,'444.gltf',"gltf",)
but i want to export gltf2.0, when I input file_type 'gltf2',it's error:
raise AssimpError('Could not export scene!');
thanks :)

**Comment by kimkulling** [comment]
At first we need to release a new version.

**Comment by spexial** [comment]
so can i use c++ to export gltf2.0?

**Comment by kimkulling** [comment]
Yes! When you are using the latest master this is possible.

**Comment by spexial** [comment]
OK,I will try it,Thanks ：）

**Comment by kimkulling** [comment]
You are welcome :-).
