### ISSUE TITLE
after make install assimp: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by godeye** [assimp/assimp#1412]
after i install the assimp,
it shows

> assimp: error while loading shared libraries: libassimp.so.4: cannot open shared object file: No such file or directory

but 
`find / | grep libassimp.so

/root/assimp-4.0.1/lib/libassimp.so
/root/assimp-4.0.1/lib/libassimp.so.4.0.1
/root/assimp-4.0.1/lib/libassimp.so.4
/usr/local/lib/libassimp.so
/usr/local/lib/libassimp.so.4.0.1
/usr/local/lib/libassimp.so.4
`

**Comment by godeye** [comment]
has a solution to it?

**Comment by kimkulling** [comment]
Have you check your LD_LIBRARY_PATH?

**Comment by godeye** [comment]
ok.
use this 
export LD_LIBRARY_PATH=/usr/local/lib 
and it works now.
thanks.

**Comment by kimkulling** [comment]
You are welcome.
