### ISSUE TITLE
doxygen documentation says "v3.1.1 (June 2014)"

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#1413]
building the documentation for assimp-4.0.1, the Doxyfile still says "v3.1.1 (June 2014)", and consequently the API documentation uses this version string as well...

probably the version string should use the CMake variable `PROJECT_VERSION`

**Comment by kimkulling** [comment]
Ups, thanks! Forget to fix that info.

**Comment by kimkulling** [comment]
Shall be fixed now.
