### ISSUE TITLE
cmake error in centos,please help me~

### ISSUE THREAD

**Issue by spexial** [assimp/assimp#1414]
I use 'cmake CMakeLists.txt -G 'Unix Makefiles''.and when I 'make',it's error:c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [code/CMakeFiles/assimp.dir/AssbinLoader.cpp.o] Error 4
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2
I checked the information, it told me that there is not enough memory, but my free memory has 2G。who can tell me  how to do,please help ,thanks

**Comment by spexial** [comment]
@kimkulling

**Comment by spexial** [comment]
@kimkulling,do you konw why,thanks

**Comment by kimkulling** [comment]
You can try to use the ninja build for instance. Should use less memory.
And you can try to use clang.

**Comment by spexial** [comment]
cool ! let me try,thanks again:)
