### ISSUE TITLE
Shipped test file float-color.ply is broken

### ISSUE THREAD

**Issue by turol** [assimp/assimp#1415]
`assimp info` says:

```Failed to load file: Validation failed: aiMesh::mFaces[0]::mIndices[2] is out of range```

`mIndices[2]` is 200. It looks like the second-to-last line is being misparsed as a triangle instead of a vertex.

The cause seems to be a missing newline at end of file. With the newline added it works. This file seems to be part of some unit test. Why does that unit test work if the file is broken?

**Comment by kimkulling** [comment]
Good question. Thanks for the report.
