### ISSUE TITLE
I‘m trying to load a secen called "sponza.obj",finally I got  mess Model or Vertex.

### ISSUE THREAD

**Issue by 404517981** [assimp/assimp#1416]
I just got the index and vertex from assimp when I load "sponza.obj",I ignored normals and others.
but a mess secne was showed. I don't konw the reason. Should I do some transform ? There is a matrix in 
ainode. Mabey I got a mess "sponza.obj",but I got the "sponza.obj" from other pragram that can show a correct secne.

**Comment by 404517981** [comment]
I'm sorry,I made a mistake.There are two "sponza.obj" in other program. but one of sence ... you konw
 It's my false,Not Assimp  |^-^|

**Comment by kimkulling** [comment]
Ok, I will close this issue.
