### ISSUE TITLE
only export necessary symbols (in libraries)

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#1419]
the libassimp library exports a lot of unnecessary symbols (at least on Debian/GNU linux).
esp, a lot of symbols are exported from the library that are not exposed via public headers (e.g. `Assimp::SIBImporter::SIBImporter()`). some of these exported symbols seem to even come from external libraries (like STL).

it would be great if only "public" symbols (as found in the public assimp headers) were exported, so consumers of the library cannot be lured into using them (for non-assimp symbols, consumers might even be tricked into underlinking).

here's a script i'm using to extract the exported symbols from the library file:

~~~sh
nm -D libassimp.so.4 \
| egrep "^[0-9]" \
| awk '{$1=""; $2=""; print $0}' \
| sed -e 's|^ *||' 
| sort -u
~~~

for the Debian packaging, i use a [version script](https://anonscm.debian.org/git/collab-maint/assimp.git/tree/debian/libassimp4.ver) to clamp down the symbols to a bare minimum.
note that the linked version script is actually for *libassimp3*, and has not been updated to *libassimp4* yet. the updating process is the main reason i'm writing here, as it turns out to be time consuming to that manually and after the fact, and it is easy to miss symbols that ought have been exported.

maybe running the tests would be enough to ensure that the entire public API is exported, but test coverage seems to be pretty low (which admittedly doesn't say very much about the coverage for the API).

note: i'm aware that you are already using `visibility("hidden")`, but there are still so many symbols exported (e.g. the Debian *libassimp3* library exports **291** symbols, whereas the upstream *libassimp4* exports **10338**).

maybe there's a way for you to include a version script as well, and keep that uptodate as you add new symbols.

**Comment by kimkulling** [comment]
PR would be great. I don't have enough time. Sorry!

**Comment by umlaeute** [comment]
about the PR: fair enough.
otoh, I would somewhat welcome it if unresolved issues remained open with a `PR welcome` tag.
