### ISSUE TITLE
Prepare UWP-build for assimp

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1428]
See: **I also tried to use Assimp.NET for my UWP C# project, but got the same result as you. From what I understand dynamically loading DLL's is not supported in UWP (see this question for example)

I've successfully been able to compile Assimp (except 2 loads) as a Windows Runtime Component (x86, x64, and ARM), and I've also wrapped a parts of the library in C++/CX ref classes, so they are accessible from C# in UWP as well and use the UWP file API. So I can confirm this is a way to get it working in UWP.

If there is an interest I will probably open source this code sometime in the future.**

Try to build this!

**Comment by hwjwill** [comment]
It would be great if there is UWP support for assimp :)

**Comment by tomwim** [comment]
Is there any news on the assimp + UWP issue?
I am also interested in assimp UWP support

**Comment by elad8a** [comment]
any news?

**Comment by kimkulling** [comment]
This task is already done. I will prekäre the doc.

**Comment by kimkulling** [comment]
See https://stackoverflow.com/questions/40803170/cmake-uwp-using-cmake-to-build-universal-windows-app
