### ISSUE TITLE
[glTF 2] Implement KHR_materials_common extension

### ISSUE THREAD

**Issue by dhritzkiv** [assimp/assimp#1430]
When the extension is completed, it should be added to glTF 2.0 reading and exporting. This should also enable glTF 1.0 -> glTF 2.0 conversion with KHR_materials_common, too.

Follow progress [here.](https://github.com/KhronosGroup/glTF/pull/1075#issuecomment-328408375)

**Comment by kimkulling** [comment]
Good news, the glTF2.0 IMporter already supports the KHR_materials_common
