### ISSUE TITLE
pyassimp.errors.AssimpError: assimp library not found

### ISSUE THREAD

**Issue by 983** [assimp/assimp#1438]
Environment: Windows 8, Python 3.5.2 Anaconda 64 bit

It says [here](https://github.com/assimp/assimp/tree/master/port/PyAssimp) that:

> PyAssimp requires a assimp dynamic library (DLL on windows, .so on linux, .dynlib on macOS) in order to work. The default search directories are:
> - the current directory

However, it does not seem to search the current path for me and prints this instead:

> raise AssimpError("assimp library not found")
> pyassimp.errors.AssimpError: assimp library not found

To fix this, I added the following line [here](https://github.com/assimp/assimp/blob/master/port/PyAssimp/pyassimp/helper.py#L54) but I am not sure if this is the nicest way to do it so no pull request from me

> additional_dirs.append('.')

After that, I checked the error which was thrown (and silenced) [here](https://github.com/assimp/assimp/blob/master/port/PyAssimp/pyassimp/helper.py#L235):
> [WinError 193] %1 is not a valid Win32 application

Apparently this error is thrown when I try to load a 32 bit assimp.dll with 64 bit python and I should have used the 64 bit one instead.

Now all works well.

**Comment by woshisj** [comment]
So  how can I solve it in linux

**Comment by a-mohsen** [comment]
> So how can I solve it in linux

`sudo apt-get install libassimp-dev`

**Comment by snow20230817** [comment]
in search_library
    raise AssimpError("assimp library not found")
assimp.errors.AssimpError: assimp library not found
我按网上的把已经编译好的assimp.dll,以及assimp.lib放到与helper.py同一文件夹，可还是弹出以上的报错，为什么？
