### ISSUE TITLE
when I export model,it Killed

### ISSUE THREAD

**Issue by spexial** [assimp/assimp#1443]
hi,when I use assimp export model,but Killed,I dont know why.my model is 480M fbx.
error:
assimp export: select file format: 'obj' (Wavefront OBJ format)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Killed

**Comment by kimkulling** [comment]
Can you try to run it in a debugger?

**Comment by spexial** [comment]
How to do...

**Comment by spexial** [comment]
I know why, I run it in my mac :480M model use 3.5G Memory，but My server only have 1.5G free memory:(
thanks ,friends:)

**Comment by kimkulling** [comment]
Ok, so I will close the issue.
