### ISSUE TITLE
Assimp requiring debug DLLs

### ISSUE THREAD

**Issue by Moddingear** [assimp/assimp#1448]
Hi, I'm having a problem with Assimp : When I build it from source for Visual Studio 2015, it requires the debugs DLLs that are provided with VS (vcruntimed.dll, ucrtbased.dll and msvcp140d.dll - Note the D at the end), meaning that it won't work on 32-bit, since those dlls are 64-bit, and I can't deploy my game to people that don't have Visual Studio 2015.
I'm building it using CMake from Command Prompt, and there must be something that I'm doing wrong.

Any help is greatly appreciated.

**Comment by kimkulling** [comment]
The default build generated by cmake is 32 bit? The meaning of d stands for debug. So maybe you mixed something up?

**Comment by Moddingear** [comment]
Yes, but CMake is still linking Assimp-vc140-mt.dll to 64-bit debug dlls. I checked that using Dependency Walker.
Same thing when I build using CMake -G "Visual Studio 14 2015 Win64"

**Comment by Moddingear** [comment]
I have stumbled upon the solution by accident, but it works !
When you build the DLL using Visual Studio, you need to change the dropdown box (at the top left-middle) from "Debug" to "Release", this way the good DLLs will be selected.

**Comment by jasjuang** [comment]
There is actually an easier way to use assimp on windows with [vcpkg](https://github.com/Microsoft/vcpkg/)
