### ISSUE TITLE
SMD, No Material Names?

### ISSUE THREAD

**Issue by Spirrwell** [assimp/assimp#1449]
Hello there.

I'm using assimp to import an SMD file. When I iterate over the meshes and get a material, the material name is always Texture_0, Texture_1, etc...

A while ago I pointed out an issue related to line endings regarding SMD files that was fixed when getting textures here https://github.com/assimp/assimp/issues/899 This is unrelated to that, however I now realize that the texture name and the material names are technically swapped.

If I do pAIMaterial->GetTexture( aiTextureType_DIFFUSE, 0, &texName, nullptr, nullptr, nullptr, nullptr, nullptr );

I get what the material name SHOULD be as far as I can tell.

For example, in Blender if I have a material called "BasicMaterial" like so:

https://i.imgur.com/VzgtfBX.png

And if I export it to like say an FBX file, doing pAIMaterial->Get( AI_MATKEY_NAME, matName ); gives me the name "BasicMaterial" however when exporting to SMD assimp considers the material name a texture name instead.

I believe this is incorrect behavior. Is that so?

**Comment by kimkulling** [comment]
Sounds like a bug to me.

**Comment by kimkulling** [comment]
This one was fixed in 5.0.0. The length of the material name wasn't set correcty.
