### ISSUE TITLE
gltf2 can't be exported

### ISSUE THREAD

**Issue by elfc2000** [assimp/assimp#1450]
I use assimp cmd  to export gltf2 format.

assimp export 1.dae 1.gltf2 

but i get a error.

I found in exporter.cpp   line 148
Exporter::ExportFormatEntry( "gltf2", "GL Transmission Format v. 2", "gltf", &ExportSceneGLTF2,
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_SortByPType)

I think the extention must be 'gltf2'   :)

**Comment by spexial** [comment]
try：assimp export 1.dae 1.gltf -fgltf2

**Comment by lslzl3000** [comment]
@spexial -fgltf2 is not working~~~

**Comment by at82** [comment]
Hi, 
I still have the same issue while trying to export using cmd:
 -fgltf2 is not working 
I get the following warning: format id 'glb2' is unknown

Any help is appreciated!
