### ISSUE TITLE
nb_metadata breaks assbin format compatibility

### ISSUE THREAD

**Issue by Ithamar** [assimp/assimp#1451]
Since commit 6c6a8fe671b927bf7ff37157436e803931b8ca68 introduced the metadata at node level, loading older assbin files with the new loader, or loading new ones with an older version loader is broken.

With the format being chunked based I do not really understand why this was done this way, is there anywhere where it warns that assbin would not be a stable format?

That would really suck as it is an ideal "standard" custom format for storing game assets and the like.

**Comment by kimkulling** [comment]
You are right. We need to add some kind of versioning for the bin-data. So that the data will be compatible even if something has changed.

**Comment by Ithamar** [comment]
Okay, I'm willing to look into this, and come up with a Pull Request, I just need some information on how to proceed:

1. If I'm right, this compatibility breakage has been out in the wild for a real release already, so are we "allowed" to break it again? I would like to add the node metadata as separate chunk, but this would mean another breakage I guess.
2. There is also no endianness indication in the format, as it currently reads/writes in the hosts endianness. Should we add that too?
