### ISSUE TITLE
Cannot import an obj file that contains vertices only

### ISSUE THREAD

**Issue by jasjuang** [assimp/assimp#1453]
I am on Ubuntu 16.04, GCC 5.4, latest assimp, and I am having trouble to import an obj mesh that contains vertices only.

Suppose I have an obj file that contains vertices only, and this displays in meshlab without a problem

test.obj

``````
v  0.0  0.0  0.0
v  0.0  0.0  1.0
v  0.0  1.0  0.0
v  0.0  1.0  1.0
v  1.0  0.0  0.0
v  1.0  0.0  1.0
v  1.0  1.0  0.0
v  1.0  1.0  1.0
``````

but when I import it with the following code, I am seeing a segmentation fault

``````
int main(){
  Assimp::Importer myimporter;

  const aiScene* myscene = myimporter.ReadFile("test.obj", 0);

  const aiMesh* mymesh = myscene->mMeshes[0];
  for (size_t t = 0; t < mymesh->mNumVertices; ++t){
    double X = mymesh->mVertices[t].x;
    double Y = mymesh->mVertices[t].y;
    double Z = mymesh->mVertices[t].z;
    std::cout << X << " " << Y << " " << Z << std::endl;
  }
  return 0;
}
``````

I can verify the code is working properly because if I change my obj to

``````
v  0.0  0.0  0.0
v  0.0  0.0  1.0
v  0.0  1.0  0.0
v  0.0  1.0  1.0
v  1.0  0.0  0.0
v  1.0  0.0  1.0
v  1.0  1.0  0.0
v  1.0  1.0  1.0

vn  0.0  0.0  1.0
vn  0.0  0.0 -1.0
vn  0.0  1.0  0.0
vn  0.0 -1.0  0.0
vn  1.0  0.0  0.0
vn -1.0  0.0  0.0
 
f  1//2  7//2  5//2
f  1//2  3//2  7//2 
f  1//6  4//6  3//6 
f  1//6  2//6  4//6 
f  3//3  8//3  7//3 
f  3//3  4//3  8//3 
f  5//5  7//5  8//5 
f  5//5  8//5  6//5 
f  1//4  5//4  6//4 
f  1//4  6//4  2//4 
f  2//1  6//1  8//1 
f  2//1  8//1  4//1 
``````

everything works.

**Comment by kimkulling** [comment]
Right, you need to define the faces at a minimum at the moment. The segfault is ba bug that needs to get fixed.

**Comment by kimkulling** [comment]
I was not able to reproduce the segfault on windows. Will try it using linux next.

**Comment by turol** [comment]
For the first test case:

```
Debug, T0: ValidateDataStructureProcess begin
Error, T0: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there
error: "Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there"
```
@kimkulling try with validation enabled. The importer should fail for this file rather than producing broken output.

@jasjuang You need to check `mNumMeshes` before accessing `mMeshes`.

**Comment by turol** [comment]
[ObjFileImporter.cpp line 228](https://github.com/assimp/assimp/blob/master/code/ObjFileImporter.cpp#L228) is probably the place to change.

**Comment by jasjuang** [comment]
@turol agree checking `mNumMeshes` will allow me to avoid the segfault, but this is still a bug that will be great to be fixed

**Comment by kimkulling** [comment]
OK, I will take care.

@turol : thanks for the hint!

**Comment by kimkulling** [comment]
Ok, I just added a test that in this case nullptr will be returned because the scene is not complete.
