### ISSUE TITLE
SIBImporter ReadString causes vector subscript out-of-bounds

### ISSUE THREAD

**Issue by jaredmulconry** [assimp/assimp#1459]
When running the unit tests in Debug mode on MSVC, I get a vector subscript out-of-bounds error.
This is caused by a very silly line of code inside of the ReadString function inside of SIBImporter.cpp:
str[str.size()] = '\0';
I believe the process of converting this function to using std::vector over manually allocated buffers caused this.
Enough space is reserved in 'str' for this to never surface as a bug in production, but it is very much a bug.

**Comment by kimkulling** [comment]
Thanks for the report, fix is there.
