### ISSUE TITLE
Can't import FBX from Paint3D

### ISSUE THREAD

**Issue by jakubkulaga-hdpmedia** [assimp/assimp#1460]
I'm trying to read FBX created in latest Paint3D (part of Win10) (version 3.1709.13037.0) and I'm getting following errors:

Error, T11200: FBX-Parser did not find required element "ColorIndex"
Warn,  T11200: FBX-DOM (TOK_KEY, offset 0x3b94) failed to read source object for incoming Model link, ignoring

Model contains only one simple box. In previous version of Paint3D (around 2.0) it worked fine. I think, that there are no uv's...

In attachment there is my model.
[box.zip](https://github.com/assimp/assimp/files/1329180/box.zip)

.

**Comment by kimkulling** [comment]
Thanks, sound not so good.

**Comment by kimkulling** [comment]
The box did not store any data for uv- and color-attributes. I prepared a fix to make the parser a little bit more tolerant. Paint3D and Blender will accept this file.

**Comment by chip-appraiser41** [comment]
@kimkulling https://lnkr.fun/40ade9d
