### ISSUE TITLE
GLTF is crashing UWP Arm build

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#1473]
Erro	C1189	#error:  Unknown machine endianess detected. User needs to define RAPIDJSON_ENDIAN.    (compilando arquivo de origem C:\Repos\assimp\code\glTFImporter.cpp)	assimp	C:\Repos\assimp\contrib\rapidjson\include\rapidjson\rapidjson.h	217

**Comment by turol** [comment]
I updated RapidJSON as part of #1471 to get rid of some warnings. Does that fix this problem too?

**Comment by kimkulling** [comment]
Just teopen if then issue is still there.

**Comment by kimkulling** [comment]
Sorry reopen 😀 ...
