### ISSUE TITLE
Gltf could not loaded by cesium

### ISSUE THREAD

**Issue by mingweiLIU** [assimp/assimp#1485]
I exported the gltf from the obj by assimp-cmd with the commond "assimp.exe export 12.obj test.glb", and tried to load the gltf through CesiumJS(1.36),however the Cesium crashed with error
![image](https://user-images.githubusercontent.com/11702952/31341123-109ad1ac-ad3b-11e7-8ffc-021972491bc0.png)
the attached file is model file I used.

[obj.zip](https://github.com/assimp/assimp/files/1368654/obj.zip)

**Comment by kimkulling** [comment]
Ok, we will take a  look.

**Comment by dhritzkiv** [comment]
Hi @mingweiLIU. Do you know if Cesium is supposed to accept glTF 1 or glTF 2 files?

By default, assimp outputs glTF 1 files (but can be made to output glTF 2 files via the `-fgltf2` command line flag). I think Cesium supports glTF 2 only, but I may be incorrect.

**Comment by mingweiLIU** [comment]
Cesium supports both standards,  while your comments suggested me that the Gltf the cesium supports has some different node tags but I don’t sure about it.

**Comment by kimkulling** [comment]
Shall work now. I guess this one is just outdated. If this is not right feel free to open another issue report.
