### ISSUE TITLE
Obj: Import of lines only shall be possible

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1487]
I'm trying use an OBJ file to import a bunch of lines which form a curved grid from Blender. However, I'm getting the error "aiScene::mNumMeshes is 0. At least one mesh must be there". Is there anything I do so that AssImp expects lines instead of triangle meshes?

**Comment by leonzeng** [comment]
I also hope to get lines, how do you do?

**Comment by kimkulling** [comment]
I have just checked the code. This feature is already implemented: https://github.com/assimp/assimp/blob/d34cd103f477fba496f09e3daf49d3ce671eb21a/code/AssetLib/Obj/ObjFileImporter.cpp#L341
