### ISSUE TITLE
AI_MATKEY_TWOSIDED always zero when importing Collada file

### ISSUE THREAD

**Issue by awefers** [assimp/assimp#1492]
When importing Collada files, aiGetMaterialInteger(pMaterial, AI_MATKEY_TWOSIDED, &isTwoSided) always returns zero instead of the actual value as set in the Collada file via the "double_sided" tag.

I have attached a Collada file with a single plane that is set to double sided.

[plane.dae.zip](https://github.com/assimp/assimp/files/1384034/plane.dae.zip)

**Comment by kimkulling** [comment]
Ok, thanks a lot for the report and the example to reproduce the issue.

**Comment by awefers** [comment]
I noticed that you can retrieve the correct value when using the cpp interface: aiMaterial::Get() with a reference to a bool for the value. Unfortunately the C interface is unable to retrieve the correct value.

**Comment by smumryak** [comment]
It is also incorrect for glTF materials. for example this model: https://sketchfab.com/models/38aedc02c0b2412babdc4d0eac7c6803

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2189
