### ISSUE TITLE
Blender: wrong interpretation in mesh loading

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1493]
Look at this pull-request:
https://github.com/assimp/assimp/commit/01510dfe1bff8349d7d0a48b16a356faa4e97bbb

The overlow will be cause by a misinterpreted value. Try to understand what kind of value this is.

**Comment by jaredmulconry** [comment]
This highlights a larger issue with converting data coming out of a blend file. Previous versions of blender stored Smooth Threshold (smoothresh) as a short with whole numbers of degrees. More recent versions store it as a float in terms of radians. These are obviously incompatible.

What's needed is a way of providing a flag, based on the version of the file being imported, that controls the clamping and normalizing behaviour of the base-level data converters (to char, short, int, float, etc.).

**Comment by tellypresence** [comment]
Can this be closed (since support for loading `.blend` files is likely to be frozen in future)?

**Comment by kimkulling** [comment]
Sure
