### ISSUE TITLE
File Error! Who can help me?

### ISSUE THREAD

**Issue by goldscu** [assimp/assimp#1495]
I compiled Assimp In Visusl Studio 2017,when I put "assimp-vc140-mt.lib" and "assimp-vc140-mt.dll" into my solution,it says "File error",and can't load "assimp-vc140-mt.dll" file in line 1.
My system is win7. And I installed "DirextX SDK", there is no problem whem comilng.And i downdloaded orher people compiled file such as "assimp.dll",the same error occurred!
Need helps!
Thanks!

**Comment by kimkulling** [comment]
Can you please show the error?

**Comment by goldscu** [comment]
Thanks!
The problem has been soluted.
I am using vs first,so I don not know how to use dll file
To solute the problem,not imput dll file into solution,and put dll file in same derectory with exe file.

**Comment by kimkulling** [comment]
OK, I will close this issue.
