### ISSUE TITLE
Support for Meshlab project format

### ISSUE THREAD

**Issue by flgw** [assimp/assimp#1505]
Having support for the Meshlab (http://www.meshlab.net/) project formats (*.aln/*.mlp) would be great! And it should be fairly straightforward to do since they are just a list od ply-files with associated transformation matrices.

**Comment by kimkulling** [comment]
Sounds easy to implement. Hopefully ee eill finf time for it.

**Comment by kimkulling** [comment]
PR would be great. I do not have the time right now.
