### ISSUE TITLE
CMake project file on VS2015 uses /MD while lib name is assimp-vc140-mt.lib

### ISSUE THREAD

**Issue by akaltar** [assimp/assimp#1507]
Checking out the latest master and generating files for Visual Studio 2015 [Win64] on Win7x64 with CMake version 3.9.4. results in project files that name the library as assimp-vc140-mt[d].lib, but in Code Generation use /MD and /MDd instead of the assumed /MT and /MTd. 

There should be an option to change between /MT and /MD(Or is there one already?) or at least fix the discrepancy. A simple solution could be changing the default /MD in the configuration of CMake to /MT,

**Comment by kimkulling** [comment]
The naming must be assimp-vc140-mDd.lib

**Comment by kimkulling** [comment]
Just checked, the naming comes from boost, so mt indicates multithreaded and not the VS-compiler flag. Just check https://stackoverflow.com/questions/2715164/how-can-i-decode-the-boost-library-naming
