### ISSUE TITLE
[Collada] export animation

### ISSUE THREAD

**Issue by eevictor** [assimp/assimp#1510]
Enhance ColladaExporter class to save <library_animations/>

**Comment by eevictor** [comment]
Sort of new to GitHub.  Having changed collada exporting animation, prelim tested OK.  So, would like to contribute.

**Comment by kimkulling** [comment]
Just check how to generate a pull request via github per google. You will find a good explanation how to generate a pull request for your changes. Afterwards a couple of automatic tests and builds will be proceeded and we will do a code review. Andxwhen things are looking good we will merge your changes into the master branch.

**Comment by kimkulling** [comment]
Ah, just saw there is already a pull request from your side.

**Comment by eevictor** [comment]
I just updated the int < unsigned int changes.  Sorry about that.
