### ISSUE TITLE
Add scale PostProcess function

### ISSUE THREAD

**Issue by al2950** [assimp/assimp#1514]
Apologies as I know this issue has been raised already in a number of difference forms, but I believe the first step into fixing those other issues is adding a scale post process function.

My issue similar to others is that I am exporting from a 3D package, eg mixamo, where a unit is 1cm into my engine where 1 unit is 1m.

Now simply scaling the root node is not the full answer. As ideally I and others needs to scale scene positions, mesh vertices, skeletons, and animations. It would be SOOOOOOOOO useful if this could all be done with a single function inside Assimp

**Comment by kimkulling** [comment]
Just started to work on that: see https://github.com/assimp/assimp/pull/1520 for the current status.

**Comment by al2950** [comment]
Amazing, thank you.
