### ISSUE TITLE
export .obj without material (.mtl) file

### ISSUE THREAD

**Issue by thomas-lemaire** [assimp/assimp#1515]
Hello the assimp's team,

I would like to manipulate a mesh without any material
- since the data aiMesh structure forces to define a material I define an empty one in the aiScene
- and then when I write this mesh in obj I get a .mtl file

Would it be possible
1. either to be able to define no material for a mesh, and then the exporters which support material would respect this definition (no material defined, no exported material)
2. or to have a new *nomtlobj* exporter to prevent from exporting the .mtl file and associated definition in the .obj file

**Comment by thomas-lemaire** [comment]
similar to #1096 

I am planning to implement proposed solution 2. which is much less invasive and I will do a PR...

**Comment by kimkulling** [comment]
Ok, we need to get the pull request running to get this feature request working.

**Comment by thomas-lemaire** [comment]
This is PR #1518 
Indeed there is still "continuous-integration/travis-ci — Waiting for status to be reported" - Is there something I can do ?

**Comment by thomas-lemaire** [comment]
Thanks for merging @kimkulling !
