### ISSUE TITLE
`includedir` seems not right in 

### ISSUE THREAD

**Issue by skylian** [assimp/assimp#1526]
In [line 4 of assimp.pc](https://github.com/assimp/assimp/blob/62e3ac9b4dc10ce2be0f5d14ee1cea3117c91ba7/assimp.pc.in#L4),shouldnt't it be "includedir=@CMAKE_INSTALL_PREFIX@/@ASSIMP_INCLUDE_INSTALL_DIR@/assimp" as all sample codes does things like "include <assimp/xxxx.h>".

**Comment by kimkulling** [comment]
Thanks for the hint, fix is on its way.
