### ISSUE TITLE
Error importing fbx file with FBX-Tokenize error

### ISSUE THREAD

**Issue by dmsurti** [assimp/assimp#1527]
With the attached sample file, I get the following error:

```
Scene importing failed for filePath /Users/deepaksurti/Downloads/Sapphiart_model.fbx
Scene importing failed with error FBX-Tokenize (offset 0x34) block offset is out of range
```

The model imports fine with FBX review app on a Mac.

<img width="1026" alt="screenshot 2017-11-02 13 28 55" src="https://user-images.githubusercontent.com/4158417/32315357-cbaa7a80-bfd1-11e7-8c44-4e7644aa8c71.png">

[Sapphiart_model.fbx.zip](https://github.com/assimp/assimp/files/1436847/Sapphiart_model.fbx.zip)

**Comment by mesilliac** [comment]
Is this fixed? I had a similar error on assimp 4.0.1, but my file seems to work with master. (i also tried this file linked above and it seems to load without error)

**Comment by MadhuiOS** [comment]
Even i am also getting same issue **FBX-Tokenize (offset 0x34) block offset is out of range**

**Comment by kimkulling** [comment]
So the warning is caused by the parsing of the mapping method for the uv-coordinates. To get the right uv-coordinates uses the 
`MappingInformationType == "ByPolygonVertex"  and isIndexToDirect == true.`
Branch, Unfortunately all indices showing to he related texture coordinates are equal -1 .

I added a check against this, but the vertex data is still broken for the head of the model.

**Comment by kimkulling** [comment]
The rendering problem will be tracked by https://github.com/assimp/assimp/issues/1853 .

**Comment by tellypresence** [comment]
This issue can probably be closed, model loads OK on recent commit

Note that right side of face has messed up normals, but that's consistent with screenshot from FBX review app above
<img src="https://github.com/assimp/assimp/assets/26958898/adf4fdec-07db-4784-b526-b1a07243facf" alt="model_full_left_side" width=180 />
<img src="https://github.com/assimp/assimp/assets/26958898/f9396b19-3840-4b83-ae71-2699b1020839" alt="debug_normals_face_left_side" width=180 />
<img src="https://github.com/assimp/assimp/assets/26958898/f85f333e-815e-4f8e-8afc-5d71cb334fdf" alt="debug_normals_face_right_side" width=180 />
