### ISSUE TITLE
Can't find a way to import lines from .3DS

### ISSUE THREAD

**Issue by SylvainMelin** [assimp/assimp#1532]
Hi.
I have 3DS files containing lines but they seem to be skipped every time when loaded with assimp.
I have disabled any post process when calling aiImportFile and have tried several kind of objects in 3DS Max (editable mesh, editable poly, line) but without success so far.
Is this a known limitation ?
Thanks

**Comment by kimkulling** [comment]
At the moment linew will be skipped. BUt a lot of people are asking for lines and points, so I will support them.

**Comment by SylvainMelin** [comment]
Ok, thank you for this awesome library and support ;)
