### ISSUE TITLE
[Documentation] Missing image files

### ISSUE THREAD

**Issue by stevesamknows** [assimp/assimp#1533]
On this page:
    `    http://assimp.org/lib_html/_animation_overview.html`
this file is missing:
    `    http://assimp.org/lib_html/AnimationOverview.png`

On this page:
`    http://assimp.org/lib_html/index.html#intro`
this file is missing:
`    http://assimp.org/lib_html/logobig.png`

**Comment by kimkulling** [comment]
Thanks, the animation-overview is fixed now. Need to check where I can find the second one.
