### ISSUE TITLE
AssimpView : Compilation error with MinGW 5.3

### ISSUE THREAD

**Issue by JLouis-B** [assimp/assimp#1546]
Hi,
I'm not sure if you're notified when I comment a closed ticket, so I want to report this issue :
https://github.com/assimp/assimp/issues/952

The fix doesn't work and there is still the issue.

**Comment by kimkulling** [comment]
Yes, I am getting a notification, but at the moment I am getting a lot of them. So thanks a lot for the hint. I have reopened the original issue and will try to close it.

As a workaround you can try to work with the qt-based viewer.
