### ISSUE TITLE
Crash when load glTF2.0 on Android

### ISSUE THREAD

**Issue by heejaekim7161** [assimp/assimp#1550]
there is a crash issue when load glTF2.0 on Android.

I found it has been caused by "throw DeadlyImportError" at function "AssetMetadata::Read(Document& doc)" in glTFAsset.inl.
glTFAsset try to read version and throw exception even if it is supported by glTF2.0.

please check this issue.

**Comment by dhritzkiv** [comment]
What commit are you using?

**Comment by heejaekim7161** [comment]
git log --oneline

10a65243 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1545 from assimp/issue_213
a77d9d7b (origin/issue_213) Merge branch 'master' into issue_213
e09349c7 Merge pull request #1544 from assimp/issue_1526
4a4f3fdd closes https://github.com/assimp/assimp/issues/213: log an error instead of letting the fbx-importer crash.
6b04b208 closes https://github.com/assimp/assimp/issues/1526: use correct include folder for assimp.
b0e86d28 Merge pull request #1543 from assimp/issue_1533
5922200e (origin/issue_1533) Merge branch 'master' into issue_1533
9835d28f Merge pull request #1542 from assimp/UnitTest_X3D
f4358630 closes https://github.com/assimp/assimp/issues/1533: put irrXML onto exclucde list for doxygen run.
ab3cf368 Merge branch 'master' into UnitTest_X3D

**Comment by dhritzkiv** [comment]
Thanks. One more thing: could you attach the gltf? It'll help me debug the issue.

**Comment by heejaekim7161** [comment]
I used below link.
https://github.com/KhronosGroup/glTF-Sample-Models

All models that used glTF2.0 had same issue.

**Comment by dhritzkiv** [comment]
Hey, thanks again, @heejaekim7161. I use the KhronosGroup's sample models to test all the time, but can't reproduce this error.

It's odd that the error happens in `glTFAsset.inl` and not `glTF2Asset.inl`.

Are you able to build assimp and run this import outside of your Android project?

**Comment by heejaekim7161** [comment]
Sorry, I can't run on other platform in my environment for some reasons.
Instead, I'll give you more detail.

At "const aiScene* Importer::ReadFile( const char* _pFile, unsigned int pFlags)" in Impoter.cpp,
the Importer check whether or not can read the file as extension in for loop.
In this point, assimp call "inline void AssetMetadata::Read(Document& doc)" in glTFAsset.inl in below sequence.

glTFImporter::CanRead
Asset::Load
AssetMetadata::Read

[Importer.cpp](https://github.com/assimp/assimp/blob/master/code/Importer.cpp)
```
const aiScene* Importer::ReadFile( const char* _pFile, unsigned int pFlags)
{
    ...
            if (!imp)   {
            // not so bad yet ... try format auto detection.
            const std::string::size_type s = pFile.find_last_of('.');
            if (s != std::string::npos) {
                DefaultLogger::get()->info("File extension not known, trying signature-based detection");
                for( unsigned int a = 0; a < pimpl->mImporter.size(); a++)  {

                    if( pimpl->mImporter[a]->CanRead( pFile, pimpl->mIOHandler, true)) {
                        imp = pimpl->mImporter[a];
                        break;
                    }
                }
            }
            // Put a proper error message if no suitable importer was found
            if( !imp)   {
                pimpl->mErrorString = "No suitable reader found for the file format of file \"" + pFile + "\".";
                DefaultLogger::get()->error(pimpl->mErrorString);
                return NULL;
            }
        }
    ...
}
```

[glTFImporter.cpp](https://github.com/assimp/assimp/blob/master/code/glTFImporter.cpp)

```
bool glTFImporter::CanRead(const std::string& pFile, IOSystem* pIOHandler, bool checkSig) const
{
    LOGE("gltf can read");
    const std::string &extension = GetExtension(pFile);

    if (extension != "gltf" && extension != "glb")
        return false;

    if (checkSig && pIOHandler) {
        glTF::Asset asset(pIOHandler);
        try {
            asset.Load(pFile, extension == "glb");
            std::string version = asset.asset.version;
            return !version.empty() && version[0] == '1';
        } catch (...) {
            return false;
        }
    }

    return false;
}
```

[glTFAsset.inl](https://github.com/assimp/assimp/blob/master/code/glTFAsset.inl)

```
inline void Asset::Load(const std::string& pFile, bool isBinary)
{
    ...
    // Load the metadata
    asset.Read(doc);
    ReadExtensionsUsed(doc);
    ...
}

inline void AssetMetadata::Read(Document& doc)
{
    // read the version, etc.
    if (Value* obj = FindObject(doc, "asset")) {
        ReadMember(*obj, "copyright", copyright);
        ReadMember(*obj, "generator", generator);

        premultipliedAlpha = MemberOrDefault(*obj, "premultipliedAlpha", false);

        if (Value* versionString = FindString(*obj, "version")) {
            version = versionString->GetString();
        } else if (Value* versionNumber = FindNumber (*obj, "version")) {
            char buf[4];

            ai_snprintf(buf, 4, "%.1f", versionNumber->GetDouble());

            version = buf;
        }

        if (Value* profile = FindObject(*obj, "profile")) {
            ReadMember(*profile, "api",     this->profile.api);
            ReadMember(*profile, "version", this->profile.version);
        }
    }

    if (version.empty() || version[0] != '1') {
        throw DeadlyImportError("GLTF: Unsupported glTF version: " + version);
    }
}
```

**Comment by dhritzkiv** [comment]
Is the glTF2 file that you're importing a binary glTF (glb) file? If so, assimp doesn't have support for reading or writing them yet.

Otherwise, I can't figure out why the gltf1 importer gets used, and not the gltf2 one.

**Comment by heejaekim7161** [comment]
No, I used .gltf file instead of .glb.
The assimp tried to check glTF1.0 first and then check glTF2.0 if the file isn't supported by glTF1.0.
Because both glTFImporter and glTF2Importer were included in pimpl->mImporter in Importer.cpp.

When I tried to remove "throw DeadlyImportError("GLTF: Unsupported glTF version: " + version);", it worked well.

**Comment by dhritzkiv** [comment]
Hey @heejaekim7161. I'm sorry, but I just don't know why this is happening. I tried several things to reproduce it on my end, but I just can't get it to throw the DeadlyImportError that you described. :(

Maybe someone else will have the answer, or maybe you will figure out the bug. Good luck!

**Comment by kimkulling** [comment]
Could this be a problem with any kind of memory alignment. Most of the issues I have encountered were caused by a broken alignment of the memory ( for instance caused by reinterpret_cast for instance ).

**Comment by heejaekim7161** [comment]
I retried this issue after pull latest commit.
9756b48b Merge pull request #1560 from assimp/source_groups_for_ut
And I confirmed there was no issue.

**Comment by ravip** [comment]
Hi,

I tried compiling assimp for android but could not able to do so. Can anyone help me with compiled version .so file for andorid (ARM architecture) or please let me know detailed steps how to compile the assimp.
