### ISSUE TITLE
Undeclared AI_CONFIG_IMPORT_FBX_SEARCH_EMBEDDED_TEXTURES and AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY

### ISSUE THREAD

**Issue by IntellectualKitty** [assimp/assimp#1553]
Unable to build latest version of Assimp (11-07-2017) because `AI_CONFIG_IMPORT_FBX_SEARCH_EMBEDDED_TEXTURES` is undeclared in [FBXImporter.cpp](https://github.com/assimp/assimp/blob/master/code/FBXImporter.cpp#L138) and `AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY` in [ScaleProcess.cpp](https://github.com/assimp/assimp/blob/master/code/ScaleProcess.cpp#L71).  Both keys are defined in [config.h](https://github.com/assimp/assimp/blob/master/include/assimp/config.h.in) on line [641](https://github.com/assimp/assimp/blob/master/include/assimp/config.h.in#L641) and line [939](https://github.com/assimp/assimp/blob/master/include/assimp/config.h.in#L939) respectively, so this seems to be a file inclusion problem.

**Comment by kimkulling** [comment]
Have you tried to remove the config.h, because this file will be generated during the cmake run?

**Comment by IntellectualKitty** [comment]
I started fresh and removed the build directory and re-ran cmake, but the results were the same.

Also, using the latest version (11-12-2017), the key `AI_CONFIG_PP_FD_CHECKAREA` in [FindDegenerates.cpp](https://github.com/assimp/assimp/blob/master/code/FindDegenerates.cpp#L81) is now undeclared as well.

**Comment by bjornbytes** [comment]
In my case I had an older `config.h` file in the `include/assimp` directory (not in the build folder) that was taking precedence over the newer generated one in the build directory.  Removing the old one fixed things.  It was tricky to track down because `include/assimp/config.h` is gitignored.

Maybe the order of the `INCLUDE_DIRECTORIES` could be changed so that `CMAKE_CURRENT_BINARY_DIR` has higher priority.

**Comment by kimkulling** [comment]
Another interestng fact regarding this issue: when using assimp as a thirdparty-lib the config.h file will not generated.  There is something wrong I guess.

**Comment by IntellectualKitty** [comment]
I started fresh by removing the entire assimp directory and downloading a new copy (instead of just removing the BUILD directory), and now it does build correctly.
