### ISSUE TITLE
OBJ: Too many vertices, would run out of memory

### ISSUE THREAD

**Issue by H-EAL** [assimp/assimp#1554]
Hi,

I am trying to load some biggish OBJ files (around 1GB). That error is generated because of:

```
    else if (pMesh->mNumVertices > AI_MAX_ALLOC(aiVector3D)) {
        throw DeadlyImportError( "OBJ: Too many vertices, would run out of memory" );
    }
```

Right now AI_MAX_ALLOC is defined as:

`#define AI_MAX_ALLOC(type) ((256U * 1024 * 1024) / sizeof(type))
`

I feel that this limitation is really uncalled for, it would be nice to be able to specify that value (256MB) in a config variable or even better, just throw an out of memory exception when the system actually goes out of memory.
Another option would be to ask the system for the actual available memory.

Note that this happens even when aiProcess_SplitLargeMeshes is enabled.

Thanks

**Comment by kimkulling** [comment]
I will try to bring this fix onto the current master.

**Comment by turol** [comment]
This is the way it is for a reason. Valgrind (and maybe ASAN) don't handle too large allocations well and instead of throwing exception return NULL. This makes debugging some things a pain. If the limit is too low, you can increase it. In fact it should probably be a runtime configuration option.

**Comment by kimkulling** [comment]
I tried to optimize this.
