### ISSUE TITLE
collada/anims_with_full_rotations_between_keys.dae gets wrong meshes

### ISSUE THREAD

**Issue by elect86** [assimp/assimp#1561]
While writing test for collada format, the titled file shows corrupted meshes 

![Imgur](https://i.imgur.com/1raq20F.png)

Interesting, this doesnt happen on the jvm port..

**Comment by kimkulling** [comment]
As far as I know this behaviour is related to the debugging facility of VS. The mesh array is  just a pointer without any information provided about its size.  And so the debugger cannot resolve the rest of the meshes. 
I tried to work around this by looping over all meshes, storing the pointer in a local variable and inspect it then.
