### ISSUE TITLE
glTF2 import: Transforms are incorrect (patch attached)

### ISSUE THREAD

**Issue by awefers** [assimp/assimp#1568]
Transforms are incorrect when importing a glTF 2.0 file with a decomposed node transform (translation,  rotation and scale). This is happening because the multiplication order is not to spec, from the glTF 2.0 spec (https://github.com/KhronosGroup/glTF/tree/master/specification/2.0):

"TRS properties are converted to matrices and postmultiplied in the T * R * S order to compose the transformation matrix; first the scale is applied to the vertices, then the rotation, and then the translation."

You can observe the issue when trying to import "Project Polly" from "https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly". The card box, the name plaque and the styrofoam piece will be in the wrong place.

 I have attached  a patch that fixes the transform calculation.

[gltf2_transform_fix.patch.zip](https://github.com/assimp/assimp/files/1472887/gltf2_transform_fix.patch.zip)

**Comment by dhritzkiv** [comment]
Hi @awefers! Great. Thanks for spotting and fixing this (and the other issues: #1562 & #1522). 

Could you create new branches for each of your fixes, apply the patches, and create pull requests? Doing so will help us review and merge the code, and it'll maintain ownership of your work! If you want help with creating pull requests, I'll be happy to guide you.
