### ISSUE TITLE
CMake find_package not working on Ubuntu

### ISSUE THREAD

**Issue by greimela** [assimp/assimp#1571]
Assimp version: 3.2 - 3.3.1
OS: Ubuntu 16.04 - 17.10

I'm trying to use Assimp as a dependency in a CMake project and therefore installed the `libassimp-dev` package on Ubuntu.
However, when I use `find_package(ASSIMP)` in my `CMakeLists.txt`, it sets the environment variable `ASSIMP_INCLUDE_DIRS` to an invalid path, namely `/usr/lib/include`.

The following lines seem to be responsible for this:
https://github.com/assimp/assimp/blob/98da53e66a0f9b6f63a0359031fd329cc1d2b39e/assimp-config.cmake.in#L13-L16
The config assumes that the root folder of assimp can always be found by moving 3 folders upwards starting from the `assimp-config.cmake`.

When I build and install assimp from source everything works fine, since `make install` moves the cmake files to `/usr/local/lib/cmake/assimp-3.3/`. 
`ASSIMP_INCLUDE_DIRS` is therefore set to `/usr/local/include/`.

But the apt package installs the cmake file to `/usr/lib/x86_64-linux-gnu/cmake/assimp-3.3/`, resulting in the invalud `ASSIMP_INCLUDE_DIRS=/usr/lib/include/`. 

Any ideas on how this can be fixed?

**Comment by kimkulling** [comment]
Fixed by https://github.com/assimp/assimp/pull/2161
