### ISSUE TITLE
Would it make sense to have an aiGetBranch for completeness?

### ISSUE THREAD

**Issue by elect86** [assimp/assimp#1574]
https://github.com/assimp/assimp/blob/fb9a5950fd7135bfa9116f6e4716b6f3ada634e5/code/Version.cpp#L110-L112

Since in `revision.h` there is

```
#define GitVersion 0xee56ffa1
#define GitBranch "master"
```

Would it make sense to have also `aiGetBranch`?

**Comment by kimkulling** [comment]
Yes, from my point of view it would make sense!
