### ISSUE TITLE
AI_CONFIG_PP_PTV_NORMALIZE, default value?

### ISSUE THREAD

**Issue by elect86** [assimp/assimp#1581]
Which is the default value of `AI_CONFIG_PP_PTV_NORMALIZE`?

All the others seems to have a default value in the comments

https://github.com/assimp/assimp/blob/e1837b6cc894283afa5652adbe9e6d1dd12704e9/include/assimp/config.h.in#L234

same for `AI_CONFIG_IMPORT_LWO_ONE_LAYER_ONLY`

**Comment by kimkulling** [comment]
The default value is false. You can find this in the code: when the parameter was not specified it will return 0 as an error code. And this is mapped to booleans false.
