### ISSUE TITLE
Visual Studio solution doesn't have -dll configuration

### ISSUE THREAD

**Issue by chakmeshma** [assimp/assimp#1583]
As suggested in this page: http://assimp.sourceforge.net/lib_html/install.html
It's possible to build to dll target. However the solution files generated from CMake for Visual Studio doesn't have any -dll configuation and only available build target extension is .lib .

**Comment by kimkulling** [comment]
Hm, my assimp-buid created via cmake generates dlls as a default.

**Comment by kimkulling** [comment]
The doc is outdated.
