### ISSUE TITLE
models/LWS/move_x.lws fails validation

### ISSUE THREAD

**Issue by turol** [assimp/assimp#1587]
```
assimp info models/LWS/move_x.lws 
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: Validation failed: aiMesh::mFaces[0].mNumIndices is 0
```

This file is used as part of the unit test suite. Adding validation to `test/unit/utLWSImportExport.cpp` triggers test failure. The test probably doesn't test what it should.

**Comment by turol** [comment]
Not actually fixed. It works with GCC <= 5 but fails with GCC >= 6.

**Comment by turol** [comment]
This appears to be caused by strict aliasing violations. Using `-fno-strict-aliasing` works around it.

**Comment by kkulling** [comment]
Thanks a lot for figuring this out!

**Comment by turol** [comment]
Found it. It's the pointer casting fuckery done when calling `LWOImporter::ReadVSizedIntLWO2`. Now the question is how to fix this shit...

Also the code is just full of pointer casting WTFs. They *all* need to be cleaned up or risk blowing up in the future.

**Comment by kimkulling** [comment]
I know, I investigated this thing some months ago. A typical WTF-example.

**Comment by turol** [comment]
Still not fixed. Closing was caused by incorrect commit message.

The real culprit seems to be strict aliasing. We need to
1. Disable -fstrict-aliasing for now to avoid breakage
2. Have someone fix all of the issues exposed by -Wstrict-aliasing=1
