### ISSUE TITLE
Regression on STL binary import

### ISSUE THREAD

**Issue by AlexandreAvenel** [assimp/assimp#1601]
This commit (9a9f18bbed8938323548335d9225e480a0ea8ca6) broke the import of binary STL files.

You can reproduce the bug by using 
`assimp.exe info test\models\STL\Spider_binary.stl`

which fails with this error : 
> ERROR: Failed to load file: OptimizeMeshes: No meshes remaining; there's definitely something wrong
> assimp info: Unable to load input file D:\dev\assimp\test\models\STL\Spider_binary.stl

If you execute the same command with Spider_ascii.stl, it works correctly.

**Comment by kimkulling** [comment]
OK, thanks for the hint. I will fix that!

**Comment by kimkulling** [comment]
Closed by  77b0aa4

**Comment by kimkulling** [comment]
Forgot to close the issue.
