### ISSUE TITLE
[glTF2] some models don't import properly

### ISSUE THREAD

**Issue by dhritzkiv** [assimp/assimp#1605]
See [this comment](https://github.com/assimp/assimp/pull/1603#issuecomment-348142377).

Models that don't import properly (from glTF sample models repo):

- NormalTangentTest
    - GLB variant
        - `ERROR: Failed to load file: OBJ: Invalid face indice`
        - seems to be interpreted as an OBJ?
- MetalRoughSpheres
    - GLB variant
        - `ERROR: Failed to load file: OBJ: Invalid face indice`
        - seems to be interpreted as an OBJ?
    - GLTF and GLTF-embedded variants:
        - `ERROR: Failed to load file: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there`

**Comment by KWEngine** [comment]
I have the exact same issue when importing this model:
https://www.dropbox.com/s/yauejwl9qfutzmb/ghost.glb?dl=0

Is this still an issue?

**Comment by sylvain44730** [comment]
Same here, "Error importing file: OBJ: Invalid face indice" during import from glb generated from blender 2.81. Is there some parameters or addon for blender to correctly export for assimp. Or is there a current developpement in assimp for loading gltf2 kronos format ?
Thanks a lot for responses
