### ISSUE TITLE
Assimp import export format error

### ISSUE THREAD

**Issue by hifeamin** [assimp/assimp#1610]
I have some 3D model in my format and want to change them to standard formats and use them in my project, so I started to use Assimp library. My code for create aiScene is:

```cpp
const aiScene* GenerateScene(int NumberOftexture, float *texture, int NumberOfVertex, double *verftex, int NumberOftri, double *tri) {

MATFile *pmat;
const char **dir;
const char *name;
int   ndir;
int   i;
aiScene* scene=new aiScene();

scene->mRootNode = new aiNode();


scene->mMaterials = new aiMaterial*[1];
scene->mMaterials[0] = nullptr;
scene->mNumMaterials = 1;

scene->mMaterials[0] = new aiMaterial();

scene->mMeshes = new aiMesh*[1];
scene->mMeshes[0] = nullptr;
scene->mNumMeshes = 1;
scene->mMeshes[0] = new aiMesh();
scene->mMeshes[0]->mMaterialIndex = 0;
scene->mRootNode->mMeshes = new unsigned int[1];
scene->mRootNode->mMeshes[0] = 0;
scene->mRootNode->mNumMeshes = 1;

auto pMesh = scene->mMeshes[0];

pMesh->mTextureCoords[0] = new aiVector3D[NumberOftexture];
pMesh->mNumUVComponents[0] = NumberOftexture;
for (int i = 0; i < NumberOftexture; i++)
    pMesh->mTextureCoords[0][i] = aiVector3D(texture[i], (float)texture[i + NumberOftexture], (float)texture[i + 2 * NumberOftexture]);

pMesh->mVertices = new aiVector3D[NumberOfVertex];
pMesh->mNumVertices = NumberOfVertex;
for (int i = 0; i < NumberOfVertex; i++)
    pMesh->mVertices[i] = aiVector3D((float)verftex[i], (float)verftex[i + NumberOfVertex], (float)verftex[i + 2 * NumberOfVertex]);

pMesh->mFaces = new aiFace[NumberOftri];
pMesh->mNumFaces = NumberOftri;

for (int i = 0; i < NumberOftri;i++) {
    aiFace& face = pMesh->mFaces[i];
    face.mIndices = new unsigned int[3];
    face.mNumIndices = 3;
    face.mIndices[0] = (int)tri[i];
    face.mIndices[1] = (int)tri[i + NumberOftri];
    face.mIndices[2] = (int)tri[i + 2* NumberOftri];
}

aiExportScene(scene, "collada", "D:\\myColladaFile.dae", 0);

return scene;}
```

It runs correctly but when I am going to open file with Assimp Library I got error. My import code is

`scene = aiImportFile(path, aiProcessPreset_TargetRealtime_MaxQuality);`

and I got error:

`Info,  T10040: Load D:\myColladaFile.dae
Info,  T10040: Found a matching importer for this file format: Collada Importer.
Info,  T10040: Import root directory is 'D:\'
Error, T10040: Collada: D:\myColladaFile.dae - Invalid data index (32500/32500) in primitive specification
Info,  T10040: Load D:\myColladaFile.dae
Info,  T10040: Found a matching importer for this file format: Collada Importer.
Info,  T10040: Import root directory is 'D:\'
Error, T10040: Collada: D:\myColladaFile.dae - Invalid data index (32500/32500) in primitive specification
Info,  T10040: Load D:\myColladaFile.dae
Info,  T10040: Found a matching importer for this file format: Collada Importer.
Info,  T10040: Import root directory is 'D:\'
Error, T10040: Collada: D:\myColladaFile.dae - Invalid data index (32500/32500) in primitive specification`

But when i export as GLTF format or change `NumberOfVertex` to `NumberOfVertex + 1` it is correct. so How can i export and import with correct format?

**Comment by hifeamin** [comment]
I found that my input data face wasn't correct. It had a number that was more than vertexes count so I got error. I recommend to close this Issue.

**Comment by kimkulling** [comment]
Ok, thanks a lot for the hint. Will be closed after only 1 year :-).
