### ISSUE TITLE
Failed to build for android on windows

### ISSUE THREAD

**Issue by tiantian20007** [assimp/assimp#1613]
I follow every step of the wiki: 
https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-(Quick-overview)
The version is 4.0.1
In the last step which actually does the compiling, I came across these compiler errors:

FIReader.cpp:693:54: error: 'stoi' was not declared in this scope
         return stoi(attributes[idx].value->toString());

FIReader.cpp:705:44: error: 'stof' was not declared in this scope
         return stof(attr->value->toString());

FIReader.cpp:987:79: error: 'to_string' is not a member of 'std'
                 throw DeadlyImportError("Invalid encoding algorithm index " + std::to_string(index));

FIReader.cpp:1011:80: error: 'to_string' is not a member of 'std'
                 throw DeadlyImportError("Invalid restricted alphabet index " + std::to_string(index));

I check the compile command, -std=c++11 is added, however, there is a "-DOPENDDL_NO_USE_CPP11" flag. I've no idea what causes the issue. 

toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-g++.exe   -DANDROID -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_OWN_ZLIB -DASSIMP_BUILD_NO_STL_EXPORTER -DASSIMP_BUILD_NO_STL_IMPORTER -DOPENDDLPARSER_BUILD -DOPENDDL_NO_USE_CPP11 -D_FILE_OFFSET_BITS=64 -Dassimp_EXPORTS -isystem H:/Android/sdk/ndk-bundle/platforms/android-9/arch-arm/usr/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -IF:/OpenGL/assimp-4.0.1/. -I. -Iinclude -IF:/OpenGL/assimp-4.0.1/include -IF:/OpenGL/assimp-4.0.1/code/../contrib/rapidjson/include -IF:/OpenGL/assimp-4.0.1/code/../contrib -IF:/OpenGL/assimp-4.0.1/code/../contrib/unzip -IF:/OpenGL/assimp-4.0.1/contrib/irrXML -IF:/OpenGL/assimp-4.0.1/code/../contrib/openddlparser/include -IF:/OpenGL/assimp-4.0.1/code/.. -fexceptions -frtti -fpic -Wno-psabi --sysroot=H:/Android/sdk/ndk-bundle/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fdata-sections -ffunction-sections -Wa,--noexecstack  -fopenmp -fvisibility=hidden -Wall -Wno-long-long -pedantic **-std=c++11**   -U__STRICT_ANSI__ -MD -MT code/CMakeFiles/assimp.dir/FIReader.cpp.o -MF code\CMakeFiles\assimp.dir\FIReader.cpp.o.d -o code/CMakeFiles/assimp.dir/FIReader.cpp.o -c F:\OpenGL\assimp-4.0.1\code\FIReader.cpp

**Comment by kimkulling** [comment]
These issues are fixed on the current master. I am currently preparing the next release. In 4.1.0 Ou can build it without any errors.

**Comment by tiantian20007** [comment]
I pull master branch, still got this compiler error when compiling IFCReaderGen2.cpp

Error: unrecognized option -mbig-obj

**Comment by kimkulling** [comment]
Ops, could I get the complete log? And did you use the makefile, which can be found at tools/androidmake ?

**Comment by tiantian20007** [comment]
I just follow every step of the wiki:
https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-(Quick-overview)
What do you mean by using the makefile? There is neither such a folder or file named "tools/androidmake" in the source folder or the build folder generated by cmake.

full log:

F:\OpenGL\assimp-build>Ninja
[51/283] Building CXX object code/CMakeFiles/assimp.dir/IFCReaderGen2.cpp.o
FAILED: code/CMakeFiles/assimp.dir/IFCReaderGen2.cpp.o
H:\Android\sdk\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-g++.exe   -DANDROID -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_OWN_ZLIB -DASSIMP_BUILD_NO_STL_EXPORTER -DASSIMP_BUILD_NO_STL_IMPORTER -DOPENDDLPARSER_BUILD -DOPENDDL_NO_USE_CPP11 -Dassimp_EXPORTS -isystem H:/Android/sdk/ndk-bundle/platforms/android-9/arch-arm/usr/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem H:/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -IF:/OpenGL/assimp/. -IF:/OpenGL/assimp/include -I. -Iinclude -IF:/OpenGL/assimp/code/../contrib/rapidjson/include -IF:/OpenGL/assimp/code/../contrib -IF:/OpenGL/assimp/code/../contrib/unzip -IF:/OpenGL/assimp/contrib/irrXML -IF:/OpenGL/assimp/code/../contrib/openddlparser/include -IF:/OpenGL/assimp/code/.. -fexceptions -frtti -fpic -Wno-psabi --sysroot=H:/Android/sdk/ndk-bundle/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fdata-sections -ffunction-sections -Wa,--noexecstack  -fvisibility=hidden -Wall -Wno-long-long -std=c++11   -U__STRICT_ANSI__ -O2 -Wa,-mbig-obj -MD -MT code/CMakeFiles/assimp.dir/IFCReaderGen2.cpp.o -MF code\CMakeFiles\assimp.dir\IFCReaderGen2.cpp.o.d -o code/CMakeFiles/assimp.dir/IFCReaderGen2.cpp.o -c F:\OpenGL\assimp\code\IFCReaderGen2.cpp
Assembler messages:
**Error: unrecognized option -mbig-obj**
[59/283] Building CXX object code/CMakeFiles/assimp.dir/glTFExporter.cpp.o
F:\OpenGL\assimp\code\glTFExporter.cpp: In member function 'void Assimp::glTFExporter::ExportMeshes()':
F:\OpenGL\assimp\code\glTFExporter.cpp:510:12: warning: variable 'idx_srcdata_begin' set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_begin = 0; // Index of buffer before writing mesh data. Also, index of begin of coordinates array in buffer.
            ^
F:\OpenGL\assimp\code\glTFExporter.cpp:511:12: warning: variable 'idx_srcdata_normal' set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_normal = SIZE_MAX;// Index of begin of normals array in buffer. SIZE_MAX - mean that mesh has no normals.
            ^
F:\OpenGL\assimp\code\glTFExporter.cpp:513:12: warning: variable 'idx_srcdata_ind' set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_ind;// Index of begin of coordinates indices array in buffer.
            ^
[60/283] Building CXX object code/CMakeFiles/assimp.dir/glTF2Exporter.cpp.o
ninja: build stopped: subcommand failed.

**Comment by kakugg** [comment]
Hi，Have you buidl successfully?

**Comment by kakugg** [comment]
Hi，Have you build successfully?

**Comment by andr3aLucch3si85** [comment]
Same problem!! CMake 3.13.4 and Ninja 1.9.0.
Help me please!!
