### ISSUE TITLE
Can't compile assimp 4.0.1 on Visual Studio 2017

### ISSUE THREAD

**Issue by Ias0601** [assimp/assimp#1614]
I'm trying to compile assimp 4.0.1 on vs2017. I can't compile 4.0.1 or 4.0.0. both gives an error in X3DImporter about iterator. I didn't try on visual studio 2015.

**Comment by Moumou38** [comment]
I have the same problem: 

Error	C2678	**binary '!=': no operator found which takes a left-hand operand of type 'Assimp::WordIterator' (or there is no acceptable conversion)** (compiling source file C:\Users\Me\Downloads\assimp-4.0.1\assimp-4.0.1\code\X3DImporter.cpp)	assimp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\algorithm	1005	


Error	C2088	**'!=': illegal for struct (compiling source file** C:\Users\Me\Downloads\assimp-4.0.1\assimp-4.0.1\code\X3DImporter.cpp)	assimp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\algorithm	1005	

help

**Comment by kimkulling** [comment]
This issue is fixed on the current master. So please use this one. I will release a new version 4.1.0 in december and the the released source will be fixed again.

**Comment by kimkulling** [comment]
Just reopen, when this issue still occurrs on the current master.
