### ISSUE TITLE
Problem linking assimp from master

### ISSUE THREAD

**Issue by AndreAhmed** [assimp/assimp#1615]
I have got the following two linking errors

/home/richardp/Projects/viewar-converter/src/AssimpLoader.cpp:1066: undefined reference to `aiNode::FindNode(char const*)'
/home/richardp/Projects/viewar-converter/src/AssimpLoader.cpp:1086: undefined reference to `aiNode::FindNode(char const*)'

however I'm linking assimp. I have compiled assimp and made sudo make install and its installed in the system folders.. as usual.. it seems that it uses the system header files, however Im also pointing to the source folders of assimp is that wrong ?

here is how I link it in the cmake

Linking CXX executable OgreAssimpConverter cd /home/richardp/Projects/viewar-converter/linuxBuild/tool && /usr/bin/cmake -E cmake_link_script CMakeFiles/OgreAssimpConverter.dir/link.txt --verbose=1 /usr/bin/c++ -std=c++11 -O2 -g -DNDEBUG -ldl -lX11 -lXt -lXaw -lXft -lassimp -lpthread CMakeFiles/OgreAssimpConverter.dir/__/src/AssimpLoader.cpp.o CMakeFiles/OgreAssimpConverter.dir/main.cpp.o -o OgreAssimpConverter -rdynamic /home/richardp/Projects/Dependencies/ogre/linuxBuild/lib/libOgreMainStatic.a /home/richardp/Projects/Dependencies/ogredeps/linuxBuild/ogredeps/lib/libzziplib.a -lz -lfreeimage /home/richardp/Projects/Dependencies/ogredeps/linuxBuild/ogredeps/lib/libfreetype.a /home/richardp/Projects/Dependencies/boost_1_63_0/dist/lib/libboost_thread.a /home/richardp/Projects/Dependencies/boost_1_63_0/dist/lib/libboost_date_time.a /home/richardp/Projects/Dependencies/boost_1_63_0/dist/lib/libboost_system.a /home/richardp/Projects/Dependencies/boost_1_63_0/dist/lib/libboost_atomic.a /home/richardp/Projects/Dependencies/boost_1_63_0/dist/lib/libboost_chrono.a -lpthread -lassimp /home/richardp/Projects/Dependencies/jsoncpp/libs/libjsonCpp.a

**Comment by kimkulling** [comment]
The signature is wrong, it must be **aiNode::FindNode( const char*)**
