### ISSUE TITLE
Unable load model from bundle

### ISSUE THREAD

**Issue by mreiche** [assimp/assimp#1616]
I'm using the iOS example as template and built up a new project with a single UIViewController with SCNView as view. I'm trying to load the ``skinned_explorer.dae`` model from app bundle, which is the main difference between my app, and the iOS example, which loads the model from user documents directory.

```objc
NSString* modelPath = [[NSBundle mainBundle] pathForResource:@"explorer_skinned" ofType:@"dae"];
NSLog(@"%@ load model: %@",self,modelPath);
NSError *error;
/*SCNAssimpScene* modelScene = [SCNScene assimpSceneNamed:@"art.scnassets/explorer_skinned.dae"  postProcessFlags:AssimpKit_Process_FlipUVs |AssimpKit_Process_Triangulate error:&error];*/
/*SCNAssimpScene* modelScene = [SCNScene assimpSceneWithURL:[NSURL fileURLWithPath:modelPath] postProcessFlags:AssimpKit_Process_FlipUVs |AssimpKit_Process_Triangulate error:&error];*/
SCNAssimpScene* modelScene = [SCNScene assimpSceneNamed:@"explorer_skinned.dae" postProcessFlags:AssimpKit_Process_FlipUVs |AssimpKit_Process_Triangulate error:&error];
```

It doesn't matter which type of import I use. I always get the following error:

``Error Domain=AssimpImporter Code=-1 "Collada: File came out empty. Something is wrong here."``

In reference to: #1278

Facts:
* I've bundle ``explorer_skinned.dae`` and ``explorer.jpg``. XCode is able to display the explorer.
* What works is, to load ``art.scnassets/jeep1.ms3d`` from bundle, but without texture material.
* I'm using AssimpKit (master) from Carthage

**Comment by daxiangpanda** [comment]
can you show me your demo??

**Comment by kimkulling** [comment]
Seems to be fixed or rather just a misunderstanding. I will close the issue.
