### ISSUE TITLE
assimp build failed in Xcode

### ISSUE THREAD

**Issue by ZoeQgOgO** [assimp/assimp#1628]
I set up assimp successfully using Cmake GUI, but when I build it in Xcode, it shows the error:
<img width="750" alt="screen shot 2017-12-10 at 1 59 10 pm" src="https://user-images.githubusercontent.com/34377997/33808319-666f4af2-ddb2-11e7-82b4-9e6c48d45eae.png">

**Comment by kimkulling** [comment]
A simple workaround is not to build the test suite.

**Comment by YiYinYinguu** [comment]
Have you solved this problem? I also had this question.

**Comment by frankyoung0305** [comment]
Have you solved this problem? I have the same problem.

**Comment by kimkulling** [comment]
I guess this one shall be fixed.
