### ISSUE TITLE
crash on fbx importer

### ISSUE THREAD

**Issue by heejaekim7161** [assimp/assimp#1638]
Hi,

The crash occurred when I import a model at https://sketchfab.com/models/6fa1cfb87c6e421d9bda68b277d0121a# on Android.

The callstack is here.
> Assimp::FBX::(anonymous namespace)::ReadDoubleWord(char const*, char const*&, char const*)
> assimp/code/FBXBinaryTokenizer.cpp:170
> 
> Assimp::FBX::(anonymous namespace)::ReadScope(std::vector<Assimp::FBX::Token const*, std::allocator<Assimp::FBX::Token const*> >&, char const*, char const*&, char const*, bool)
> assimp/code/FBXBinaryTokenizer.cpp:347
> 
> Assimp::FBX::TokenizeBinary(std::vector<Assimp::FBX::Token const*, std::allocator<Assimp::FBX::Token const*> >&, char const*, unsigned int)
> assimp/code/FBXBinaryTokenizer.cpp:451
> 
> Assimp::FBXImporter::InternReadFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)
> assimp/code/FBXImporter.cpp:170
> 
> Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*)
> assimp/code/BaseImporter.cpp:97

And I used assimp v4.1.0.

Please check this issue.
Thanks.

**Comment by kimkulling** [comment]
Hi,

just check https://github.com/assimp/assimp/pull/1686 for the fix. There was a dyna,mic_cast instead of a memcpy operation.
