### ISSUE TITLE
FTBFS on the Hurd

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#1642]
In [o3dgcTimer.h#L33](https://github.com/assimp/assimp/blob/b5c7c9c/contrib/Open3DGC/o3dgcTimer.h#L33) there are some includes protected by an `#ifdef __MACH__`:

~~~C
#elif __MACH__
#include <mach/clock.h>
#include <mach/mach.h>
#else
#include <time.h>
#include <sys/time.h>
#endif
~~~

It seems that this is intended for OSX/macOS.
However there are other implementations of the *Mach Microkernel*, notably `GNU Hurd`, which lacks the `mach/clock.h` include.
Therefore this file cannot be built on the Hurd.

If the define was indeed meant for OSX/macOS, I suggest to use `__APPLE__` instead:
~~~C
#elif __APPLE__
#include <mach/clock.h>
#include <mach/mach.h>
#else
#include <time.h>
#include <sys/time.h>
#endif
~~~

**Comment by umlaeute** [comment]
I've also reported this https://github.com/KhronosGroup/COLLADA2GLTF/issues/103 (I guess the code has been taken from there). Nevertheless it would be nice if you could fix that locally as well.

**Comment by kimkulling** [comment]
The code came with the glFT-importer. I will take a look.

**Comment by umlaeute** [comment]
I just discovered that the proposed fix (replacing `__MACH__` with `__APPLE__`) is **not** enough to make assimp build on the Hurd.
I'll try to find a real solution in the next days.

**Comment by kimkulling** [comment]
Great, thanks a lot for your time and work!

**Comment by umlaeute** [comment]
ah, found the problem.

in that file, there seem to be two occurences of `__MACH__`, and both of them have to be replaced with `__APPLE__`.

See the [Debian patch](https://sources.debian.org/src/assimp/4.1.0%7Edfsg-3/debian/patches/fix-hurd-FTBFS.patch/) that allows to successfully build assimp on the Hurd.
