### ISSUE TITLE
Progress Percentage of loading a large obj is very inprecise

### ISSUE THREAD

**Issue by JohnboyJovi** [assimp/assimp#1649]
Hello,

I integrated a ProgressHandler to print a progress bar, when loading a rather large obj (>1M faces). The first progress callbacks I get look good. But then it returns two values above 100%, i.e. 1.1 and 1.4
Before it falls back to 50% and then counts up as expected to 100%.

Anything I can do about that? Or any ideas what the problem can be, or is this expected bahavior? Because showing this progress bar to a user is a bit frustrating ;-)

The values I get are:
```
0.0
0.16
0.23
0.35
0.54
0.79
1.10
1.43
0.5
0.5
0.51
0.54
0.55
0.57
0.59
... 
0.96
0.98
1.0
```
I would be happy to share any more information about the model (or the model itself) with you

Thank you in advance for any help and this awesome library in general,
Jonathan

**Comment by JohnboyJovi** [comment]
This jump back seems to happen when the application consumes more than 1GB and then the memory usage drops. Might that be the problem?

**Comment by kimkulling** [comment]
Maybe. Thanks for the report.

**Comment by kurtzmarc** [comment]
I believe https://github.com/assimp/assimp/pull/2296 will fix this. I was seeing the same results from the ProgressHandler.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2296
