### ISSUE TITLE
Version 4.1.0 installs the static lib lib/libIrrXML.a and no lib/libIrrXML.so

### ISSUE THREAD

**Issue by yurivict** [assimp/assimp#1650]
On FreeBSD, static libs are strongly discouraged.
You need to build shared lib first, and then, optionally, static libs.

**Comment by kimkulling** [comment]
Ok, thanks a lot for the report. We will take care.

**Comment by yurivict** [comment]
FYI: This is a show-stopper for the FreeBSD port update, because they don't accept static libs in ports, as a matter of policy.

**Comment by yurivict** [comment]
This is a third-party lib already linked into libassimp.so.
Would the right fix be to not install it?
I'll just delete it from the installed file set in the FreeBSD port and update the port.

**Comment by kimkulling** [comment]
Sorry for the delay. I can offer you to install it as a shared lib. I will prepare a pull request for it.

**Comment by yurivict** [comment]
Thank you!

**Comment by RichardTea** [comment]
Please don't make changes like this to all platforms.
This change has broken the Windows build (and possibly the Mac one too)

**Comment by kimkulling** [comment]
Why did it not broke the CI build for windows? How does your config look like?

**Comment by RichardTea** [comment]
I presume the CI build doesn't attempt to actually execute the resulting DLL

**Comment by kkulling** [comment]
The executed unittest shall do that. I need to check that and I am really sorry for the inconveniences.
