### ISSUE TITLE
[FBX] Embedded texture - read access violation.

### ISSUE THREAD

**Issue by kosaj** [assimp/assimp#1651]
When I try to iterate over embedded texture that is compressed I'am experiencing "Exception thrown: read access violation." on random index of "pcData" that is a member of aiTexture. Checked with last master (4.1.2018).

Code example with new function scene::GetEmbeddedTexture. The old way with "*number" was also not working for me... [quick code.txt](https://github.com/assimp/assimp/files/1603483/quick.code.txt)

**Comment by kimkulling** [comment]
Ok, thanks for the report.

**Comment by kimkulling** [comment]
Shall work now.
