### ISSUE TITLE
Make the entire importer/exporter API externally available

### ISSUE THREAD

**Issue by NebuHiiEjamu** [assimp/assimp#1658]
Currently as of 4.1, Assimp only makes the bare minimum importer/exporter API available (BaseImporter, ai* types, etc). Many of the convenience APIs (ByteSwapper, StreamReader, IrrXML, CommentRemover, ComputeNormalsWithSmoothingsGroups(), SkeletonMeshBuilder, StandardShapes, fast_atof, StringComparison, ParsingUtils, and perhaps others) don't have their headers installed, nor can they be called from the library by external code, leaving me to have to turn to libraries like GLM and Boost more often, to help extract various format data, when it would be easier to use what Assimp already provides internally.

**Comment by NebuHiiEjamu** [comment]
I'd like to update: BaseImporter is not external whatsoever currently. I cannot build any external plugins.

**Comment by kimkulling** [comment]
Ok, possible to do. This will include moving the includes to the public include folder as well.

**Comment by NebuHiiEjamu** [comment]
Many thanks!

**Comment by geraldineolivier** [comment]
Yes, I would have exactly the same request, so that I can call these mesh manipulation tools from an external code.

**Comment by NebuHiiEjamu** [comment]
Eventually, I'm hoping to take this to modularisation, where the shared lib would hold the core API, and 3D file formats would be their own shared lib in a plugins folder; basically would be what QImageFormats would be to Qt (qmng, qdds, etc), except you'd have assimp.dll and then obj.dll, fbx.dll, 3ds.dll, etc as plugins.

**Comment by kimkulling** [comment]
Done!
