### ISSUE TITLE
[STLLoader] Undefined behavior: reference binding to misaligned address

### ISSUE THREAD

**Issue by dhritzkiv** [assimp/assimp#1660]
Error Output (formatting may be off):

```cppobjdump
runtime error: reference binding to misaligned address 0x00010640d886 for type 'const aiVector3D' (aka 'const aiVector3t<float>'), which requires 4 byte alignment
0x00010640d886: note: pointer points here
b0 3d 00 00 da 27  d9 be 9c e5 47 3f 6a d8  ea be 5f 24 d2 c0 1e a7  41 41 0a 05 ad 3e 5f 24  d2 c0
             ^
UndefinedBehaviorSanitizer: undefined-behavior
```

The error points to this line: https://github.com/assimp/assimp/blob/95661e86625046b70e978be00811b505a0298d44/code/STLLoader.cpp#L455

[Here's a model (riff.stl.zip)](https://github.com/assimp/assimp/files/1589413/riff.stl.zip) that I was able to trigger it with. It was exported from Blender. All other software is able to open it. I also re-exported with Meshlab, but it results in the same behaviour.

**Comment by kimkulling** [comment]
Thanks a lot, we need to copy the data at this place.

**Comment by geraldineolivier** [comment]
I have exactly the same bug...
