### ISSUE TITLE
Image file io from disk not working in gltf2 importer

### ISSUE THREAD

**Issue by gschoeni** [assimp/assimp#1662]
I noticed that gltf2 does not seem to import images properly. I am new to using the repo, so am cautious to submit a pull request, but I found this implementation that seems to expect images to be base64 encoded. 

[https://github.com/assimp/assimp/blob/master/code/glTF2Asset.inl#L670](url)

It would be nice if it worked for regular .png, jpeg, etc on disk.

I was loading this model from disk to test:

[https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox/glTF](url)

**Comment by dhritzkiv** [comment]
Hi @gschoeni. What functionality are you using that needs importing of images?

By default, image files are not imported from disk - only the file path string is stored internally if it's a file path. If the image reference is a base64 encoded datauri, then it is decoded by the importer.

**Comment by gschoeni** [comment]
Hey @dhritzkiv, I was planning on encoding the file as a glb binary blob, sending it over the network, and decoding it on the other side. I was thinking it would be nice if the textures were encoded in the blob as well so that I didn't have to send them in separate blobs or retrieve them from another web server.

Does that make sense? Or is gltf not the best choice for this behavior?

**Comment by gschoeni** [comment]
@dhritzkiv ah I see - the spec states:

> glTF provides two delivery options that can also be used together:
> 
> glTF JSON points to external binary data (geometry, key frames, skins), and images.
> glTF JSON embeds base64-encoded binary data, and images inline using data URIs.
> For these resources, glTF requires either separate requests or extra space due to base64-encoding. Base64-encoding requires extra processing to decode and increases the file size (by ~33% for encoded resources). While gzip mitigates the file size increase, decompression and decoding still add significant loading time.

So it looks like I will have to make separate requests, or base64 encode the image data.

**Comment by dhritzkiv** [comment]
Oh. That makes sense. Currently, assimp –at least for the glTF2 importer/exporter– doesn't support importing scenes with image file paths and outputting an embedded .gltf file, or an embedded .glb file. 

The behaviour to encode all image files within the gltf/glb would need to be added, and would need to be toggled with a flag. I'm not sure what that would look like, however,

**Comment by kimkulling** [comment]
Shall be fixed now as fast as I know. PLease reopen this issue when I was wrong!
