### ISSUE TITLE
[BUG] Compiling static libraries in vs2017 will result in a link error

### ISSUE THREAD

**Issue by panhaowen** [assimp/assimp#1665]
assimp-vc140-mt.lib(IFCUtil.obj) : error LNK2019: An unparsed external symbol ___std_reverse_trivially_swappable_4，The symbol is in the function "void __cdecl std::_Reverse_unchecked1<unsigned int *>(unsigned int * const,unsigned int * const,struct std::integral_constant<unsigned int,4>)" (??$_Reverse_unchecked1@PAI@std@@YAXQAI0U?$integral_constant@I$03@0@@Z) referenced

**Comment by kimkulling** [comment]
Ok, thanks for the report!

**Comment by kimkulling** [comment]
Works for me, just tested it. Could you please try it again and reopen the issue, if its still exists?
