### ISSUE TITLE
Can anyone provide me with an Visual Studio c++ Project that uses assimp to load a texured model into opengl?

### ISSUE THREAD

**Issue by Tim-Electronics** [assimp/assimp#1669]
Hi there,

Can anyone provide me with an Visual Studio c++ Project that uses assimp to load a texured model into opengl?
This because i have spend days to get this to work but i just cant manage it.
I prefer if all the librarys(like assimp and an opengl lib) are included with it so i dont have to sort that all out again.

thanks

**Comment by NebuHiiEjamu** [comment]
This isn't the appropriate place to ask. The issue tracker is for bug reports, feature requests, and the sort. Use Gitter if you need help.

**Comment by kimkulling** [comment]
You can generate the simple-OpenGL-workspace by running cmake.
