### ISSUE TITLE
[gltf2] when I export other model to gltf2,path of .bin file is not right

### ISSUE THREAD

**Issue by spexial** [assimp/assimp#1674]
The .bin file path will bring the local path, resulting in an error.like this:
![image](https://user-images.githubusercontent.com/22853121/34514920-b31c6208-f0aa-11e7-9a9b-509f030827a7.png)
As you can see, the path to the .bin file is different from .gltf
How can I to do,thanks:)

**Comment by Misterblue** [comment]
I've noticed that a command line invocation of assimp does not add the '.gltf2' to the end of the output scene file. Also, the names of the bin files are completely messed up when using the command line invocation. The is a routine GetURI() which is used to generate both the filename to write the file and the URI reference to the bin file in the gltf2 file (one problem with gltf2 is it has image and bin URI references embedded in the file). If the gltf and bin files are not in the local directory, the URI path to the bin file is messed up.

**Comment by spexial** [comment]
@Misterblue yes,so I want to rewrite the code generated gltf2 .bin file

**Comment by Breush** [comment]
@Misterblue @spexial I am currently working on the glTF2 exporter. I want to make an option to embed the bin file and images. I'll see what I can do for your issue first.

**Comment by spexial** [comment]
@Breush I want to do it, but I can't,because I'm a PHPer ,I will not use c++ .so if you can solve it ,thanks very much.  :)
