### ISSUE TITLE
Compilation probleme with Assimp::WordIterator and <algorithm>, VS2017 MSVC 14.12.25827

### ISSUE THREAD

**Issue by geraldineolivier** [assimp/assimp#1675]
Erreur	C2678	'!=' binaire : aucun opérateur trouvé qui accepte un opérande de partie gauche de type 'Assimp::WordIterator' (ou il n'existe pas de conversion acceptable)	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\algorithm	1005	

This line in the algorithm library is problematic with Assimp::WordIterator
for (; _UFirst != _ULast; ++_UFirst, (void)++_UDest)

I  have this error on 4.1.0 and 4.0.1, either SIMPLE OR DOUBLE PRECISION

**Comment by geraldineolivier** [comment]
Note that the nuget nativ and redist version 4.0.1, both Win32 and x64, works perfectly...

**Comment by kimkulling** [comment]
Please try to update your Visual-Studio Installation. Works for me with the latest version of VS2017 ( latest patch applied ). And just reopen the issue if the bug still exists.

And thanks for the report, I wasn't aware that there are issues with VS2017.
