### ISSUE TITLE
Q: Building Assimp as a dylib for iOS

### ISSUE THREAD

**Issue by thomasburbeck** [assimp/assimp#1678]
I'm trying to create a branch of AssimpNet which will work on Xamarin for iOS; and I seem to be extremely close (I've created a .NET Standard 2.0 Library, which is now identifying my dylib - but saying it's not a compatible architecture). 

Unfortunately I don't know a huge deal about CMake. I followed the INSTALL instructions and used:
cmake -G 'Unix Makefiles'
make

This seems to have created me an x86_64 Mac library - not a simulator one? Which commands can I use to generate a .dylib for iOS (not Mac) supporting the most common arch's?

Error: 
"Error loading unmanaged library from path: libassimp64.dylib, error detail:
dlopen(libassimp64.dylib, 2): no suitable image found.  Did find:
	libassimp64.dylib: mach-o, but not built for iOS simulator"

**Comment by kimkulling** [comment]
As far as I know you will need a assembly for Xanmarin. The -so created by the make is just a native shared-object-lib. So when you want to use it for Xanmarin you have to prepare a wrapper lib for Xanmarin. Google should be able to help you.
