### ISSUE TITLE
zconf.h missing

### ISSUE THREAD

**Issue by terziman** [assimp/assimp#168]
Due to the renaming of "zconf.h" into "zconf.h.included" in contrib/zlib/CMakeLists.txt, the reference to "zconf.h" in "contrib/zlib/zlib.h" is broken when building assimp library. To fix this, it might be necessary to add  ${CMAKE_CURRENT_BINARY_DIR} to the list of include directories for assimp in order to find the correctly generated "zconf.h"

A possible fix in the main CmakeLists.txt is as follow:

--- CMakeLists.txt.old  2013-10-10 10:00:14.991820200 +0200
+++ CMakeLists.txt  2013-10-24 09:46:47.635885200 +0200
@@ -111,7 +111,7 @@
   add_subdirectory(contrib/zlib)
   set(ZLIB_FOUND 1)
   set(ZLIB_LIBRARIES zlib)
-  set(ZLIB_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/zlib)
+  set(ZLIB_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/contrib/zlib ${CMAKE_CURRENT_BINARY_DIR}/contrib/zlib)
 else(NOT ZLIB_FOUND)
   ADD_DEFINITIONS(-DASSIMP_BUILD_NO_OWN_ZLIB)
 endif(NOT ZLIB_FOUND)

**Comment by DavidARivkin** [comment]
For some reason this is now broken again, particularly if you use the Microsoft 2015 ARM compiler with ZLib 1.2.8

**Comment by brainmachine** [comment]
I'm having the same issue. -> RC1015 cannot open include file 'zconf.h'.	assimp-master\contrib\zlib\zlib.h	34
