### ISSUE TITLE
[Bug] cmake assimp error

### ISSUE THREAD

**Issue by spexial** [assimp/assimp#1684]
![wx20180106-175631](https://user-images.githubusercontent.com/22853121/34638667-b0b5dd6a-f30b-11e7-9dd9-ef2d187ba4f7.png)
when I cmake the new assimp version which version of @Breush solved gltf2's path of .bin file is not right.

**Comment by kimkulling** [comment]
Thanks for the report. Which platform did you use?

**Comment by spexial** [comment]
@kimkulling I use Mac os
