### ISSUE TITLE
Vertex Colours from gltf not loading

### ISSUE THREAD

**Issue by Devlin1991** [assimp/assimp#1702]
https://github.com/KhronosGroup/glTF-Sample-Models/pull/143/files

I just tested out the new test model from Kronos and I see nothing in the mesh colours when loaded via assimp.

**Comment by kimkulling** [comment]
Ok, thanks for the report.

**Comment by mwitchwilliams** [comment]
May be seeing something similar.
When loading Khronos' Box.gltf in GearVR, I get a correct red Box. But when GearVR runs an X3D file (an XML-based Web 3D file format), that loads the same Box.gltf, the Box appears, but no colors.
So maybe related to this issue, or maybe it's a GearVR issue.

**Comment by makitsune** [comment]
I just found out this is broken and I'm dealing with this issue. Some models in our engine come in as completely black when the vertex colors are wrong.

**Comment by makitsune** [comment]
Some of the models I've tried getting vertex colors from have rgb values of `nan` instead of 0 to 1.

**Comment by makitsune** [comment]
https://github.com/assimp/assimp/pull/3582

**Comment by makitsune** [comment]
https://github.com/assimp/assimp/pull/3582

**Comment by kimkulling** [comment]
OK, thanks for that. I will close the issue.
