### ISSUE TITLE
Assimp_view is crashing 

### ISSUE THREAD

**Issue by razvanab** [assimp/assimp#1703]
Assimp_view is crashing after compilation:
Windows 10
Windows Sdk 10.0.16299.0
Visual Studio 2017

Module information:
version: 23.20.15007.1005
original location: C:\Windows\System32\DriverStore\FileRepository\c0322096.inf_amd64_7ff7d53c3793b9e4\atiumd64.dll

Exception thrown at 0x00007FFFF4C8EE98 (atiumd64.dll) in assimp_viewer.exe: 0xC0000005: Access violation reading location 0x0000000000000B98.
Unhandled exception at 0x00007FFFF4C8EE98 (atiumd64.dll) in assimp_viewer.exe: 0xC0000005: Access violation reading location 0x0000000000000B98.

**Comment by kimkulling** [comment]
Thanks for the report. Just on startup?

**Comment by razvanab** [comment]
Yes

**Comment by kimkulling** [comment]
Shall be fixed.
