### ISSUE TITLE
Need to set /bigobj in MSVC or compile will fail

### ISSUE THREAD

**Issue by griffin2000** [assimp/assimp#1708]
At ToT the compile will fail with this error:

`Error	C1128	number of sections exceeded object file format limit: compile with /bigobj	assimp	E:\Axum\github\assimp\code\Importer\IFC\IFCReaderGen1_2x3.cpp	1	
`

To fix this needs adding to root CMakeLists.txt file on line 216
`  add_compile_options(/bigobj)`

**Comment by kimkulling** [comment]
THanks a lot for the report. Which compiler are you using? Mingw?

**Comment by griffin2000** [comment]
This is VS2015 x64

**Comment by kimkulling** [comment]
OK, fixed by https://github.com/assimp/assimp/commit/5463757688aa6d743ae41d57b32999b231a07a62
