### ISSUE TITLE
Crash on conversion in Converter::ConvertMeshMultiMaterial

### ISSUE THREAD

**Issue by griffin2000** [assimp/assimp#1709]
At ToT I get a crash if I try and convert this FBX file (just running Assimp dump command line will repro it):
https://drive.google.com/open?id=17oyiQuFjHhrTl2k54ZNs8ziOtZQX7EGn

It looks to be a mismatch between the FaceIndices and the MaterialIndices in Converter::ConvertMeshMultiMaterial, the crash is an array overun in the faces array

**Comment by griffin2000** [comment]
Any thoughts on what this fix might be for this? It is a valid FBX (can view in FBXViewer)

To me it looks like a logic error in the Converter::ConvertMeshMultiMaterial (it is assuming the two arrays FaceIndices and the MaterialIndices are identical lengths but this is not a good assumption), but not familar enough with the code to fix it.

**Comment by kimkulling** [comment]
Shall work now.
