### ISSUE TITLE
Do assimp support binary fbx format

### ISSUE THREAD

**Issue by KiranSNagarajaiah** [assimp/assimp#1711]
Hello 

I want to know assimp support binary FBX format or not.
And also want to fuse multiple FBX file into one single FBX.

Please reply Thank you in advance

**Comment by mesilliac** [comment]
Assimp supports loading binary FBX files, but not saving them, yet.

I'm currently working on the binary FBX export. Basic support (no animations) should be ready for testing within the next week or two.
