### ISSUE TITLE
Allow export to Collada version 1.5

### ISSUE THREAD

**Issue by felixvd** [assimp/assimp#1714]
We have to convert some robot files from Collada 1.4.1 to Collada 1.5. We have found other software that can export to Collada 1.5, but cannot read 1.4.1 files. It would be good if this library supported the latest version, but I suppose 1.4.1. is not fully done (#606), so this is a lofty feature request.

We are trying our luck with this next: https://github.com/gregeryb/DAEBlend

**Comment by kimkulling** [comment]
Shall work, please reopen, if this is still an issue.
