### ISSUE TITLE
No detailed steps for compiling assipm for andorid (ARM architecture) and no android sample available

### ISSUE THREAD

**Issue by ravip** [assimp/assimp#1718]
Please provide the detailed steps to compile the assimp 4.1.0 for android (ARM architecture). Also consider providing some android example in the release, that will help us getting the gist of framework and became usable for many android developers.

**Comment by kimkulling** [comment]
Please check: https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-%28Quick-overview%29

Feel free to optimize the entry :-).
