### ISSUE TITLE
Reopen #1169

### ISSUE THREAD

**Issue by mvidiassov** [assimp/assimp#1719]
Please, reopen #1169 "Xcode 8.3 beta 2 won't compile assimp" 
I am getting the same warning as triggered that issue:
Taking address of packed member 'x' of class or structure 'aiVector2t' may result in an unaligned pointer value.
The cause seems to be that [c3bb2b6](https://github.com/assimp/assimp/commit/c3bb2b66ac94d8e75396210268d7f6e82286eaa6) only fixed 3d vectors.
Why not to apply the same approach to 2d?
Version info: Assimp 4.1.0, Xcode 9.1, MacOS 10.12.6

**Comment by kimkulling** [comment]
Thanks for the report, I have reopened the issue. Let's see if we can fix it now.

**Comment by kimkulling** [comment]
Shall be fixed now.
