### ISSUE TITLE
Animation duration bug?

### ISSUE THREAD

**Issue by tomspilman** [assimp/assimp#1720]
I noticed that in the latest development release if you import the `dude_2011.fbx` from here:

https://github.com/SickheadGames/MonoGame/tree/fbx_fixes/Test/Assets/Models/Dude

The animation duration (as computed via `Animation.DurationInTicks / Animation.TicksPerSecond`) is incorrect and slightly different that with an older release (actually much older from 2014).

The reason i think this is a bug is because the value is incorrect to another FBX importer which calculates the correct duration of `12670000` ticks vs `12080000` ticks with the latest development AssImp.

**Comment by kimkulling** [comment]
Thanks for the report. Do you have some kind of fix? Would be great to get some help here. We have a lot open issue reports regarding FBX and I am really spare on time.

Thanks in advance!

**Comment by tomspilman** [comment]
> Do you have some kind of fix?

I don't but will investigate when i can.

**Comment by tomspilman** [comment]
So i am not totally sure...  but i suspect the old versions of Assimp was wrong and there isn't a bug here.

First i will say i'm trying to replicate the behavior of the FBX importer from Microsoft's XNA.  It used FBX 6.1.0 which Assimp doesn't support but i can see the ascii says:
```
Takes:  {
    Current: "Take 001"
    Take: "Take 001" {
        FileName: "Take_001.tak"
        LocalTime: 1924423250,57732697500
        ReferenceTime: 1924423250,57732697500
```
After converting that to FBX 7.1.0 using Autodesk's converter it looks like this:
```
Takes:  {
	Current: "Take 001"
	Take: "Take 001" {
		FileName: "Take_001.tak"
		LocalTime: 1924423250,57732697500
		ReferenceTime: 1924423250,57732697500
```
Since the local and reference times are the same i don't suspect any issue in the FBX conversion here.

So doing the math myself using the local time of the animation take:
```
int64_t start_ticks = 1924423250;
int64_t end_ticks = 57732697500;
int64_t ticks_per_second = 46186158000;
double duration = double(end_ticks - start_ticks) / ticks_per_second;
```
That correctly results in `1.208333333333333` which matches the results of the current release of Assimp.

Unless i'm doing the math wrong here to calculate the duration of an animation from the local start/end times...  i think there is no bug and this can be closed.
