### ISSUE TITLE
RT-extension not found under Mac OS

### ISSUE THREAD

**Issue by mvidiassov** [assimp/assimp#1723]
code/CMakelist.txt looks for RT functions like clock_gettime in librt, unless the compiler is MSVC.
Since RT-extension in Mac OS is in the system library (libc), it is not found.
The extension was introduced in Mac OS 10.12, headers for it come with Xcode 8.

I have no suggestion on how to fix the problem properly since I do not know what is proper Assimp approach, for example is cross-compiling Assimp in current environment, but targeting older version of Mac OS a supported scenario?
May be as a workaround some cmake option can be introduced so that the user  will be able to make the choice himself without editing code/CMakelist.txt?

**Comment by kimkulling** [comment]
Is this issue still relevant?

**Comment by kimkulling** [comment]
I guess not.
