### ISSUE TITLE
How  to load binary FBX in Android using Assimp

### ISSUE THREAD

**Issue by KiranSNagarajaiah** [assimp/assimp#1725]
Hi 

How to load binary fbx file in android?? I want to load FBX file and display in UI. Please let me know is there any sample already available for android with FBX loading and displaying.

Thanks in advance

**Comment by nishantdande** [comment]
Hi,
Please follow below link -
http://www.anandmuralidhar.com/blog/android/assimp/

Give FBX file Path  in ModelAssimp.cpp file.

**Comment by KiranSNagarajaiah** [comment]
Thanks @nishantdande i tried that example and able  to display fbx model but i am not able to apply texture. Please help

**Comment by kimkulling** [comment]
PLease show some code and reopen the issue then.

**Comment by elect86** [comment]
If interested, binary fbx import has been just finished on the [jvm assimp port](https://github.com/kotlin-graphics/assimp)

**Comment by dw881220** [comment]
Have you solved this issue? I meet the same issue as well. I can load fbx file but can not apply the texture.

**Comment by nishantdande** [comment]
Hi,

I have tried to render GLTF, DAE file on Android Platform but not sure about binary FBX. 

Please find sample rendering code.
https://github.com/nishantdande/assimp_android <https://github.com/nishantdande/assimp_android>


Thanks,
Nishant.
M:+919511744622
Skype - nishant.dande
LinedIn - https://www.linkedin.com/in/nishant-dande-37948b42/
Github - https://github.com/nishantdande

**Comment by reachwasim** [comment]
I also have exactly the same problem. Was applying texture really solved as part of this issue? Any response is truly appreciated thank you

**Comment by Shahbazsultan** [comment]
Tool chain 'ndk-gcc' (GNU GCC): XCode arm-linux-androideabi-gcc is a wrapper around Clang. Treating it as Clang and not GCC.

**Comment by kimkulling** [comment]
This shall work. Embedded textures will work as well.
