### ISSUE TITLE
Is it possible to fuse multiple FBX file into one single FBX using Assimp??

### ISSUE THREAD

**Issue by KiranSNagarajaiah** [assimp/assimp#1727]
Hello 

I am new to assimp. i want to fuse / merge multiple FBX files into single fbx file while displaying.
Please let know to fuse/merge if possible. Thank you

**Comment by kimkulling** [comment]
Never tried that out.

**Comment by kimkulling** [comment]
Just did some investigations:
You can use the class SceneCombiner: Import the two scenes and merge them together via SceneCombiner::MergeScenes.

So you should be able to fuse several scenes together into one scene. But there is no tool support provided at the moment to do so. If you need some more tooling you need to open a feature-request.
