### ISSUE TITLE
Expected end of <source> element

### ISSUE THREAD

**Issue by wh1sp3r** [assimp/assimp#174]
I made simple box in 3ds max 2014 exported to collada file. ( FBX collada exporter )
Latest version shows the error in the title.

Version downloaded from assimp website is working fine.

EDIT:

Ok, i found the way, how to show this ERROR.
Export something from 3ds max into COLLADA *.dae format, then import it back to 3ds max and export back.
This file cannot be loaded by Assimp.

**Comment by kimkulling** [comment]
I cannot reproduce this issue and it wasn't reported again. So from my point of view this issue was already solved. 
Please reopen if this is still there!

Thanks!
