### ISSUE TITLE
Can't remove formats from build

### ISSUE THREAD

**Issue by IgrauBezRuk** [assimp/assimp#1740]
When Im writing` set(ASSIMP_BUILD_FBX_IMPORTER OFF)` before including assimp as subdirectory, it works only with second cmake config time
what I mean is when Im launching cmake first time I have this
```
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled formats:
```
When Im configuring again with same comand second time, I have this

```
Enabled formats: OBJ GLTF
-- Disabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D 3MF MMD
```
Also this is not works` set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF)`

**Comment by kimkulling** [comment]
Thanks for the report. I guess some bug in the cmake-macro.

**Comment by Z-EMB** [comment]
#1943 shall fix enabling/disabling importers

**Comment by kimkulling** [comment]
SHall be fixed now
