### ISSUE TITLE
Build currently fails on Win64

### ISSUE THREAD

**Issue by thekitchensink** [assimp/assimp#1743]
Generated using this command in some random build directory:

`cmake ../assimp -G "Visual Studio 15 2017 Win64`

It generates the solution fine, then fails to build - adding the "/bigobj" flag to the windows compiler flags seems to fix the problem, but then there are a bunch of warnings (1400 ish) from gtest due to "std::tr1" being deprecated soon.

 I can push up a quick PR to add "/bigobj" for the moment, but I think the gtest upgrade is going to be a bit more work.

**Comment by kimkulling** [comment]
OK, working on uit. Thanks for the report.
