### ISSUE TITLE
404 error for docs page on main website

### ISSUE THREAD

**Issue by stevesamknows** [assimp/assimp#1747]
Following links were broken when this was posted:
http://assimp.org/lib_html/index.html
http://assimp.org/howtoBasicShapes.html

"Die angeforderte Seite konnte nicht gefunden werden!" etc.

**Comment by kimkulling** [comment]
OK, I need to fix the link.

**Comment by stevesamknows** [comment]
Thank you -- have always found the web docs very useful and easy to navigate

**Comment by kimkulling** [comment]
Fixed!
