### ISSUE TITLE
assimp-4.1.0 make error on win64

### ISSUE THREAD

**Issue by gqy2468** [assimp/assimp#1750]
**assimp-4.1.0 make error on win64 (cmake -G "MSYS Makefiles") :**

[ 75%] Building CXX object test/CMakeFiles/unit.dir/__/contrib/gtest/src/gtest-all.cc.obj
In file included from d:/Documents/Downloads/assimp-4.1.0/contrib/gtest/src/gtest-all.cc:45:0:
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc: In constructor 'testing::internal::Mutex::Mutex()':
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:242:45: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_SECTION*' in initialization
       critical_section_(new CRITICAL_SECTION) {
                                             ^
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:243:48: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
   ::InitializeCriticalSection(critical_section_);
                                                ^
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc: In destructor 'testing::internal::Mutex::~Mutex()':
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:253:46: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'PCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void DeleteCriticalSection(PCRITICAL_SECTION)'
     ::DeleteCriticalSection(critical_section_);
                                              ^
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc: In member function 'void testing::internal::Mutex::Lock()':
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:261:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void EnterCriticalSection(LPCRITICAL_SECTION)'
   ::EnterCriticalSection(critical_section_);
                                           ^
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc: In member function 'void testing::internal::Mutex::Unlock()':
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:271:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void LeaveCriticalSection(LPCRITICAL_SECTION)'
   ::LeaveCriticalSection(critical_section_);
                                           ^
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc: In member function 'void testing::internal::Mutex::ThreadSafeLazyInit()':
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:292:33: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL
_SECTION*' in assignment
         critical_section_ = new CRITICAL_SECTION;
                                 ^~~~~~~~~~~~~~~~
d:\documents\downloads\assimp-4.1.0\contrib\gtest\src\gtest-port.cc:293:54: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
         ::InitializeCriticalSection(critical_section_);
                                                      ^
make[4]: *** [test/CMakeFiles/unit.dir/__/contrib/gtest/src/gtest-all.cc.obj] Er
ror 1
make[3]: *** [test/CMakeFiles/unit.dir/all] Error 2
make[2]: *** [all] Error 2

**Comment by kimkulling** [comment]
Thanks for the report.

**Comment by kimkulling** [comment]
Shall be fixed now.

**Comment by hongzheng2018** [comment]
@kimkulling 
how to fix this error ?

I use this way to fix this error ,you can see as below:
 Replace this line in gtest-port.h(line 402)
 `struct _RTL_CRITICAL_SECTION`
with this 
```
#if GTEST_OS_WINDOWS_MINGW
      // MinGW defined _CRITICAL_SECTION and _RTL_CRITICAL_SECTION as two
      // separate (equivalent) structs, instead of using typedef
     typedef struct _CRITICAL_SECTION GTEST_CRITICAL_SECTION;
#else
       // Assume CRITICAL_SECTION is a typedef of _RTL_CRITICAL_SECTION.
      // This assumption is verified by
      // WindowsTypesTest.CRITICAL_SECTIONIs_RTL_CRITICAL_SECTION
      typedef struct _RTL_CRITICAL_SECTION GTEST_CRITICAL_SECTION;
#endif
```

Replace this line in gtest-port.h(line 1696)
`_RTL_CRITICAL_SECTION* critical_section_;`
with this 
`GTEST_CRITICAL_SECTION* critical_section_;`

I use MinGW on WIN32 to compile
