### ISSUE TITLE
Android : Step to generate libassimp.so file for arm architecture 

### ISSUE THREAD

**Issue by nishantdande** [assimp/assimp#1754]
Hi,
I am trying to generate libassimp.so for android arm architecture but every time I am getting .so for x86-64 architecture.

I am running below command to generate .so for arm -
cmake -DANDROID_FORCE_ARM_BUILD=ON -DANDROID_ABI="armeabi-v7a" -DANDROID_NATIVE_API_LEVEL="android-8" -DANDROID_TOOLCHAIN_NAME="/home/nishant/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9" CMakeLists.txt

make

Please provide steps to generate libassimp.so file for arm architecture which will run on Android platform.

**Comment by kimkulling** [comment]
You can find a detailed documentation in our wiki: https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-%28Quick-overview%29

**Comment by sinigr54** [comment]
Hello, can you get detailed steps to build assimp with jni port for android?
My OS is Linux

**Comment by monxarat** [comment]
Hi @nishantdande 

I have built with your command line.

```
CMake Warning:
  Manually-specified variables were not used by the project:

    ANDROID_ABI
    ANDROID_FORCE_ARM_BUILD
    ANDROID_NATIVE_API_LEVEL
    ANDROID_TOOLCHAIN_NAME

```
How to fix it.

**Comment by wssbygone** [comment]
> Hi @nishantdande
> 
> I have built with your command line.
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     ANDROID_ABI
>     ANDROID_FORCE_ARM_BUILD
>     ANDROID_NATIVE_API_LEVEL
>     ANDROID_TOOLCHAIN_NAME
> ```
> 
> How to fix it.

I've the same issue, who can help?
