### ISSUE TITLE
AMD64 switch breaks builds

### ISSUE THREAD

**Issue by MauriceH1** [assimp/assimp#1760]
If you use the "Visual Studio 15 2017 Win64" generator in CMake together with the AMD64 switch you get the following error in when trying to build in Visual Studio:
`4>   Creating library C:/Users/Youkai/Development/Tools/Assimp/build/contrib/zlib/Debug/zlibd.lib and object C:/Users/Youkai/Development/Tools/Assimp/build/contrib/zlib/Debug/zlibd.exp
4>inflate.obj : error LNK2019: unresolved external symbol inflate_fast referenced in function inflate
4>infback.obj : error LNK2001: unresolved external symbol inflate_fast
4>C:\Users\Youkai\Development\Tools\Assimp\build\contrib\zlib\Debug\zlibd.dll : fatal error LNK1120: 1 unresolved externals
4>Done building project "zlib.vcxproj" -- FAILED.`

I've also noticed that AMD64 switch breaks the build when using the "Visual Studio 15 2017" generator, although this shouldn't be too much of an issue as I imagine people won't use the x64 implementation in a 32bit project.

Using the 32bit assembly with a 64bit project works as expected though.

**Comment by kimkulling** [comment]
OK, thanks a lot for the report.

**Comment by kimkulling** [comment]
Shall be fixed now.

**Comment by asmaloney** [comment]
@kimkulling Is it possible this problem has reappeared? You didn't reference your fix, so I can't see what you did.

Someone trying to build one of my plugins using assimp has [run into this](https://github.com/asmaloney/MeshIO/issues/1). (I am not set up on Windows to build any of this, so I can't attack it myself.)

As I mention there, there's an extensive analysis of the issue on [StackOverflow](https://stackoverflow.com/questions/29505121/cmake-zlib-build-on-windows).
