### ISSUE TITLE
Opened IOStreams should always be closed with IOSystem::Close

### ISSUE THREAD

**Issue by mabuchner** [assimp/assimp#1761]
Currently most importers use `unique_ptr<IOStream>` or directly `delete` the opened `IOStream`. The `IOSystem::Close` function is not called.

This is bad, because it only works, if the `IOStream` returned by `IOSystem::Open` actually was allocated using `new`. If my custom `IOSystem` implementation would use a different allocator, then this would fail catastrophically.

By always calling `IOSystem::Close` this could be avoided. The `IOSystem` knows how to allocate the `IOStream`, therefore it should also know how to deallocate this resource.

**Comment by kimkulling** [comment]
Thanks for the report. Just started my investigations to find a fix.

**Comment by kimkulling** [comment]
Shall be already fixed.

**Comment by mabuchner** [comment]
A [search for `std::unique_ptr<IOStream>`](https://github.com/search?q=repo%3Aassimp%2Fassimp%20unique_ptr%3CIOStream%3E&type=code) shows, that this is still a problem.

The pointer returned by `IOSystem::Open` frequently gets wrapped in a `std::unique_ptr<IOStream>`. On destruction `std::unique_ptr<IOStream>` will use `delete` to deallocate the `IOStream`. This only works correctly, if  `IOSystem::Open` used `new` to allocate the `IOStream`. In this situation the `IOSystem::Close` method isn't called at all.

Additionally, derived `IOSystem` classes might want to do some bookkeeping in `IOSystem::Open` and `IOSystem::Close`, which gets troublesome, if `IOSystem::Close` is only called sometimes.

Not sure how big of a problem this is in practice. When I needed this functionality 5 years ago (👴) I found a workaround.

**Comment by kimkulling** [comment]
Already fixed. I will close the issue.
