### ISSUE TITLE
The skin animation is not correct

### ISSUE THREAD

**Issue by jellychen** [assimp/assimp#1768]
I download a fbx model form blow url
[https://www.3dpunk.com/work/details-w4616.html](url)

It is a bat skin animaiton, but I use assimp donot get a corrent one.

**Comment by mesilliac** [comment]
I'm not sure how to download this file, it seems to need some sort of login?

**Comment by kimkulling** [comment]
Try it again, we updated the FBX-animation support. If the issue is still there just reopen the issue.
