### ISSUE TITLE
Compilation fails with MinGW-64 (gcc 4.8.1)

### ISSUE THREAD

**Issue by slimsag** [assimp/assimp#177]
Firstly,

If you use mingw-64 (gcc 4.8.1) from here:
```
http://sourceforge.net/projects/mingwbuilds/
```

assimp will not compile; it complains of missing ::strlen in include/assimp/types.h

```
[  7%] Built target zlibstatic
Scanning dependencies of target assimp
[  7%] Building CXX object code/CMakeFiles/assimp.dir/Assimp.cpp.obj
C:\Users\stephen\Desktop\assimp\code\Assimp.cpp:1:0: warning: -fPIC ignored for target (all code is position indepe
ndent) [enabled by default]
 /*
 ^
In file included from C:\Users\stephen\Desktop\assimp\code\../include/assimp/Logger.hpp:47:0,
                 from C:\Users\stephen\Desktop\assimp\code\../include/assimp/DefaultLogger.hpp:46,
                 from C:\Users\stephen\Desktop\assimp\code\AssimpPCH.h:135,
                 from C:\Users\stephen\Desktop\assimp\code\Assimp.cpp:45:
C:\Users\stephen\Desktop\assimp\code\../include/assimp/types.h: In member function 'void aiString::Set(const char*)
':
C:\Users\stephen\Desktop\assimp\code\../include/assimp/types.h:285:22: error: '::strlen' has not been declared
   const size_t len = ::strlen(sz);
                      ^
C:\Users\stephen\Desktop\assimp\code\../include/assimp/types.h: In member function 'void aiString::Append(const cha
r*)':
C:\Users\stephen\Desktop\assimp\code\../include/assimp/types.h:318:22: error: '::strlen' has not been declared
   const size_t len = ::strlen(app);
```

more errors follow. This can be fixed by adding an include statement for cstring around line 48 of types.h:
```
// Some runtime headers
#include <cstring>
```

Then compilation is all good and dandy, until it tries to assemble IFCReaderGen.cpp

```
[ 53%] Building CXX object code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.obj
C:\Users\stephen\Desktop\assimp\code\IFCReaderGen.cpp:1:0: warning: -fPIC ignored for target (all code is position
independent) [enabled by default]
 /*
 ^
c:/progra~1/mingw-~1/x64-48~1.1-p/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_64-w64-mingw32/bi
n/as.exe: CMakeFiles\assimp.dir\IFCReaderGen.cpp.obj: too many sections (34698)
C:\Users\stephen\AppData\Local\Temp\ccvLJeF3.s: Assembler messages:
C:\Users\stephen\AppData\Local\Temp\ccvLJeF3.s: Fatal error: can't write CMakeFiles\assimp.dir\IFCReaderGen.cpp.obj
: File too big
c:/progra~1/mingw-~1/x64-48~1.1-p/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_64-w64-mingw32/bi
n/as.exe: CMakeFiles\assimp.dir\IFCReaderGen.cpp.obj: too many sections (34698)
C:\Users\stephen\AppData\Local\Temp\ccvLJeF3.s: Fatal error: can't close CMakeFiles\assimp.dir\IFCReaderGen.cpp.obj
: File too big
code\CMakeFiles\assimp.dir\build.make:2673: recipe for target 'code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.obj' fai
led
mingw32-make[2]: *** [code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.obj] Error 1
CMakeFiles\Makefile2:158: recipe for target 'code/CMakeFiles/assimp.dir/all' failed
mingw32-make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
Makefile:115: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

which (I think) is because of the file being quite large (admittedly I don't know what the file is for, I'm no C++ expert. Looks auto-generated to me). I googled and came across this:
```
http://mingw-users.1079350.n2.nabble.com/File-too-big-too-many-sections-td7579168.html
```

I'd like to write Go bindings for assimp, which is why I am trying to build with mingw-64 (as it is not possible to use VS libraries with Go).

I would appreciate your time on this issue.
Stephen

**Comment by elect86** [comment]
Hi, I have the same problem

Win7 x64, cygwin x64 and Netbeans

 ```
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/as: CMakeFiles/assimp.dir/IFCReaderGen.cpp.o: too many sections (41590)
/cygdrive/c/Users/GBARBI~1/AppData/Local/Temp/ccmrliZV.s: Assembler messages:
/cygdrive/c/Users/GBARBI~1/AppData/Local/Temp/ccmrliZV.s: Fatal error: can't write CMakeFiles/assimp.dir/IFCReaderGen.cpp.o: File too big
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/as: CMakeFiles/assimp.dir/IFCReaderGen.cpp.o: too many sections (41590)
/cygdrive/c/Users/GBARBI~1/AppData/Local/Temp/ccmrliZV.s: Fatal error: can't close CMakeFiles/assimp.dir/IFCReaderGen.cpp.o: File too big
code/CMakeFiles/assimp.dir/build.make:2678: recipe for target 'code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.o' failed
make[2]: *** [code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'code/CMakeFiles/assimp.dir/all' failed
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kimkulling** [comment]
But this is only a bad workaround.

**Comment by elect86** [comment]
I imagined, but it is the only one I am able to implement to make it compile..

**Comment by asmaloney** [comment]
With the patched assimp included in Qt, *IFCReaderGen.cpp* was split into two by Andy Nichols:

https://github.com/qtproject/qt3d/blob/dev/src/3rdparty/patches/0002-assimp-Fix-building-with-mingw-older-than-4.9.patch

This seems like a reasonable solution.

(Aside: I think the other patches for Qt are already applied in the more recent version of assimp - they include 3.1.1.  With this fix they might not to have to patch assimp for use in Qt which would be nice.)

**Comment by kimkulling** [comment]
Thanks for the tip

Andy Maloney <notifications@github.com> schrieb am Sa., 6. Feb. 2016 12:22:

**Comment by aru** [comment]
I encountered the same issue trying to build on Cygwin with GCC, I got around this (and other cygwin specific issues) adding the following to the top-level CMakeLists.txt:

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -Wall **-Wa,-mbig**-obj -**std=gnu++11**" )

-Wa,-mbig-obj tells the assembler it's gonna be a big file, I suspect Mingw requires the same flag but I haven't tested that yet, if I get around doing that (probably in a month) and to the bottom of this issue I can offer these changes as a pull request.

std=gnu++11 helps cygwin find POSIX functions like strncasecmp and realpath under Windows.

**Comment by Kvrepo** [comment]
I also have issues with compiling with MinGW but in Code::Blocks.

I've included the <cstring> slimsag suggested and played around with aru's line, even thou that's for Cygwin, but with no luck.

At one point it stops every time at StringComparsion.h. The errors are the following:
```
\assimp-3.3.1\assimp-3.3.1\code\StringComparison.h||In function 'int Assimp::ASSIMP_stricmp(const char*, const char*)':|
\assimp-3.3.1\assimp-3.3.1\code\StringComparison.h|144|error: '::strcasecmp' has not been declared|
\assimp-3.3.1\assimp-3.3.1\code\StringComparison.h||In function 'int Assimp::ASSIMP_strincmp(const char*, const char*, unsigned int)':|
\assimp-3.3.1\assimp-3.3.1\code\StringComparison.h|193|error: '::strncasecmp' has not been declared|
```

As I've found out strcasecmp and strncasecmp are actually declared in <string.h>, so I really don't know what the problem could be.

**Comment by xantares** [comment]
I succeeded in building latest version with gcc 6, maybe try a more recent gcc that defaults to a higher c++ standard (c++11 or c++14 for gcc6).

**Comment by kimkulling** [comment]
Closed by  304556a

**Comment by iKlsR** [comment]
This is happening on gcc 5.3 now.

**Comment by nikolaynnov** [comment]
The similar issue with MSVS2015 x64:
qt\5.9.1_x64\qt3d\src\3rdparty\assimp\code\IFCReaderGen1.cpp : fatal error C1128: number of
sections exceeded object file format limit: compile with /bigobj
cl : Command line error D8040 : error creating or communicating with child process
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"' : return code '0x
2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code
'0x2'

It blocks QT 5.9.1 compilation.

**Comment by iKlsR** [comment]
@nikolaynnov Hardly related, read the error again and see https://msdn.microsoft.com/en-us/library/ms173499.aspx
