### ISSUE TITLE
X3D File format doesn't work with meshlab

### ISSUE THREAD

**Issue by AndreAhmed** [assimp/assimp#1770]
Hi,
X3D file format exported from mesh lab has the ImageTexture  url = "image.pnp", it doesn't have a tag like url = '"image.png"' and the importer doesn't work in that case.

**Comment by mabuchner** [comment]
[`url` is a MFString](http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/texturing.html#ImageTexture). Therefore `'"image.png"'` is the correct spelling.

You should probably report this issue to [MeshLab](https://github.com/cnr-isti-vclab/meshlab).
