### ISSUE TITLE
ObjectCompare in BlenderImmediate.h doesn't follow strict weak ordering

### ISSUE THREAD

**Issue by maxvollmer** [assimp/assimp#1776]
```
    struct ObjectCompare {
        bool operator() (const Object* left, const Object* right) const {
            return ::strncmp(left->id.name, right->id.name, strlen( left->id.name ) ) == 0;
        }
    };
```
This comparator will cause an exception being thrown and possibly crash Assimp, since its implementation violates strict weak ordering. As counter-intuitive as it seems, a comparator must return false for equal values. The C++ standard defines and expects this behavior: `true if lhs < rhs, false otherwise.`
This would be a correct implementation:
```
    struct ObjectCompare {
        bool operator() (const Object* left, const Object* right) const {
            return ::strncmp(left->id.name, right->id.name, strlen( left->id.name ) ) < 0;
        }
    };
```

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/1777
