### ISSUE TITLE
glTF2 Round-Trip Failure

### ISSUE THREAD

**Issue by Starnick** [assimp/assimp#1783]
Hey,

Using a build targeting the 4.1.0 release, I encountered an error when testing a workflow where I am importing from an OBJ file, exporting to glTF2, then importing the generated glTF2 file. Assimp complains that there is no importer that is able to read the glTF2 file (but it opens fine in other applications), and the import fails.

I noticed that the URI in the json file that points to the bin file is an absolute file path, which seems a little odd. If I edit this line, and make it relative...e.g. set it to "Lighthouse-exported.bin", then assimp imports the model as expected.

I attached a zip of the generated glTF2 files.

[Lighthouse-exported.zip](https://github.com/assimp/assimp/files/1708761/Lighthouse-exported.zip)

**Comment by kimkulling** [comment]
That is bad, thanks for the report.

**Comment by Starnick** [comment]
Looks like this was fixed on the master branch, I was using the 4.1.0 release when I ran into it.
