### ISSUE TITLE
FBX file has extra mesh

### ISSUE THREAD

**Issue by seeme00** [assimp/assimp#1786]
Hi,
I'm loading a fbx mesh from this website:
https://www.mixamo.com
[survivor_a_lusth.zip](https://github.com/assimp/assimp/files/1714300/survivor_a_lusth.zip)
![model](https://user-images.githubusercontent.com/11278696/36072979-60c94b68-0f29-11e8-8d61-6cae14b95c53.png)

When looking at it in 3ds max, I see the following structure.
![max](https://user-images.githubusercontent.com/11278696/36072977-57690a04-0f29-11e8-924c-2c48c00179d9.png)

When looking at it in assimp viewer, I have the following structure with some extra nodes.
What are those nodes? They appear as lines when parsing the file with assimp.
I also dont see those with FbxExporter's viewer.
![viewer](https://user-images.githubusercontent.com/11278696/36072981-65604618-0f29-11e8-8725-8c44123a55c5.png)

Thanks
JNQ

**Comment by mesilliac** [comment]
could be the mesh has more than one type of face (some points or lines or quads, for example) and the sort-by-ptype option is being used so it splits the mesh so each has faces of a consistent type?

**Comment by mesilliac** [comment]
Indeed the top mesh is made of lines an the bottom one triangles. If you turn off the optimizations you get a single triangle mesh. Probably there are some degenerate triangles which get converted to lines, then the mesh is split by primitive type and you end up with two meshes.
