### ISSUE TITLE
Relation between aiNode and Bone

### ISSUE THREAD

**Issue by seeme00** [assimp/assimp#1787]
Hi,
I'm trying to perform hardware skinning using assimp and ozz animation.
I can get the bone position from ozz, but I need the inverse bind pose matrix from assimp to feed the shader.
The problem is that some bones listed by ozz are not listed as bones by assimp.

From what I can see, ozz skeleton is almost a 1:1 copy of the assimp scene graph.
There is a discrepancy between the two lists of matrices, so I can't just multiply them.

What's the relation between an aiNode transform and a bone offset matrice?
How do I get a coherent list of matrices ?

Thanks,
JNQ

**Comment by mesilliac** [comment]
the bone offset matrix should relate the mesh to the ainode transform for the bone, in the bind pose.

i think assimp discards any bone nodes that are not being used by the mesh in question (i.e. have zero weight). Hence the discrepancy between the full skeleton, and the aiBone list for the mesh.

for animation, it should work to only use the bones assimp has. Take the world-space position of the node corresponding to that bone (which depends on the full skeleton position, as the transforms are inherited). Then the inverse bind pose matrix can be used directly to get the mesh position relative to the current position of that bone node. That gives the desired vertex position according to this bone.

That gives the influence from one bone. Combining for many bones is just a weighted sum of this formula:
```sum(animated bone node position * inverse bind pose matrix * vertex position * bone-vertex weight)```

i think you can assume that any bone not listed by assimp has weight 0, and thus won't influence animation directly.

**Comment by kimkulling** [comment]
I will close this issue, just reopen if there are still any open questions.
