### ISSUE TITLE
AC3D importer and shading

### ISSUE THREAD

**Issue by agerrius** [assimp/assimp#1788]
It seems the AC3D importer always applies smooth shading to the objects and does not use the attributes of the SURF command that specify if smooth shading should be used. I have attached a sample object with two cylinders, one has smooth shading applied the other not.

I'll try if I can find a fix for this, but not familiar enough with the assimp code to know where the shading is applied.

[cylinder2.zip](https://github.com/assimp/assimp/files/1714719/cylinder2.zip)

**Comment by agerrius** [comment]
I did some more searching in the code and it seems the AC3D loader doesn't define any normals. So it is the post-processing that adds them. I'll investigate if it would work to set the normals for the flat shaded polygons in the AC3D loader and for the smooth shaded ones let the post-processing calculate them. I guess that would require to have a mesh with either flat or smooth shaded faces.

**Comment by kimkulling** [comment]
Hi, any updates?

**Comment by agerrius** [comment]
Hi, sorry, I didn't investigate this further. The AC3D format is not extremely important for my tool, so I got distracted by other things.

**Comment by tellypresence** [comment]
Can this be closed?

**Comment by kimkulling** [comment]
I think, yes. It seems to be outdated.
