### ISSUE TITLE
DefaultLogger::detatchStream return value seems not to match documentation

### ISSUE THREAD

**Issue by BluebirdGreycoat** [assimp/assimp#1796]
The docs for `DefaultLogger::detatchStream` say that it returns true if the user stream is detached and we gain ownership, but that seems not to be the case in my project.

This is how I attach the stream (g_logger is a `std::unique_ptr`):
```
auto severity = Logger::Err | Logger::Warn;
DefaultLogger::get()->attachStream(g_logger.get(), severity);
```

This is how I try to detach it:
```
bool result = DefaultLogger::get()->detatchStream(g_logger.get(), 0);
```
Passing 0 as severity level is correct, is it not?

Glancing through the implementation of `DefaultLogger::detatchStream`, it seems that the function does not return `true` because of the `break` statement before it.

The strangest thing is that my usage was working fine when I first wrote it, but it broke after I fixed a bug elsewhere in the project ...

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/1843
