### ISSUE TITLE
FBX import missing meshes name

### ISSUE THREAD

**Issue by Trylz** [assimp/assimp#1807]
When importing FBX files meshes have empty names(aiMesh::mName).
I attached the test scene and my code snippet. The loading is done in BaseModel::loadFromAiModel(const std::string& path, bool importMaterials)

[Files.zip](https://github.com/assimp/assimp/files/1746010/Files.zip)

**Comment by mesilliac** [comment]
FBX files don't usually name the meshes themselves - rather the node that contains the mesh is what is named with the expected name.

In this fbx file also, the mesh geometry entries are actually unamed.

We could name the mesh the same as the node in this case, that might make things clearer.

**Comment by Trylz** [comment]
I see. That probably what other importer does(I tried in Blender). 
The weird thing is i tried myself to assign random name to the MeshGeometry but they are ignored. I am probably doing it wrong. Do you have an idea of where it should be done ?

**Comment by mesilliac** [comment]
Do you mean in the assimp code? The name (if it exists) is assigned in `Converter::SetupEmptyMesh`, in FBXConverter.cpp around line 909.

**Comment by Trylz** [comment]
Yes i tried the following. During import meshes name are still empty.

``    aiMesh* const out_mesh = new aiMesh();

    out_mesh->mName.Set("TestName");

    meshes.push_back( out_mesh );
    meshes_converted[ &mesh ].push_back( static_cast<unsigned int>( meshes.size() - 1 ) );

    return out_mesh;``

**Comment by mesilliac** [comment]
that's weird - i just tried this exact code and the mesh in the imported scene was definitely named "TestName". How are you checking the name?

using test/models/FBX/phong_cube.fbx, i get on assimp master:
```
Meshes:  (name) [vertices / bones / faces | primitive_types]
    0 (): [24 / 0 / 12 | triangle]
```

and using this code above:
```
Meshes:  (name) [vertices / bones / faces | primitive_types]
    0 (TestName): [24 / 0 / 12 | triangle]
```

**Comment by mesilliac** [comment]
(this was using the `assimp info` command but from this PR which isn't merged yet: https://github.com/assimp/assimp/pull/1810 )

**Comment by Trylz** [comment]
Yes thanks, the test name is properly set. The problem was on my side.

**Comment by kimkulling** [comment]
Ok, so I will close the issue.

**Comment by Trylz** [comment]
Well in facts the issue is not fixed.  Meshes name are still missing but my little test pass :)

**Comment by darksylinc** [comment]
We were hit by this issue which is NOT fixed.

We fixed it by patching Assimp with the following:

```
diff --git a/code/FBXConverter.cpp b/code/FBXConverter.cpp
index d0f1c0de..fed24e90 100644
--- a/code/FBXConverter.cpp
+++ b/code/FBXConverter.cpp
@@ -167,23 +167,24 @@ private:
     // ------------------------------------------------------------------------------------------------
     // MeshGeometry -> aiMesh, return mesh index + 1 or 0 if the conversion failed
     std::vector<unsigned int> ConvertMesh( const MeshGeometry& mesh, const Model& model,
-        const aiMatrix4x4& node_global_transform );
+        const aiMatrix4x4& node_global_transform, aiNode &nd );
 
     // ------------------------------------------------------------------------------------------------
-    aiMesh* SetupEmptyMesh( const MeshGeometry& mesh );
+    aiMesh* SetupEmptyMesh( const MeshGeometry& mesh, aiNode& nd );
 
     // ------------------------------------------------------------------------------------------------
     unsigned int ConvertMeshSingleMaterial( const MeshGeometry& mesh, const Model& model,
-        const aiMatrix4x4& node_global_transform );
+        const aiMatrix4x4& node_global_transform, aiNode& nd );
 
     // ------------------------------------------------------------------------------------------------
     std::vector<unsigned int> ConvertMeshMultiMaterial( const MeshGeometry& mesh, const Model& model,
-        const aiMatrix4x4& node_global_transform );
+        const aiMatrix4x4& node_global_transform, aiNode& nd );
 
     // ------------------------------------------------------------------------------------------------
     unsigned int ConvertMeshMultiMaterial( const MeshGeometry& mesh, const Model& model,
         MatIndexArray::value_type index,
-        const aiMatrix4x4& node_global_transform );
+        const aiMatrix4x4& node_global_transform,
+        aiNode &nd );
 
     // ------------------------------------------------------------------------------------------------
     static const unsigned int NO_MATERIAL_SEPARATION = /* std::numeric_limits<unsigned int>::max() */
@@ -1119,7 +1120,7 @@ void Converter::ConvertModel( const Model& model, aiNode& nd, const aiMatrix4x4&
 
         const MeshGeometry* const mesh = dynamic_cast< const MeshGeometry* >( geo );
         if ( mesh ) {
-            const std::vector<unsigned int>& indices = ConvertMesh( *mesh, model, node_global_transform );
+            const std::vector<unsigned int>& indices = ConvertMesh( *mesh, model, node_global_transform, nd );
             std::copy( indices.begin(), indices.end(), std::back_inserter( meshes ) );
         }
         else {
@@ -1137,7 +1138,7 @@ void Converter::ConvertModel( const Model& model, aiNode& nd, const aiMatrix4x4&
 
 
 std::vector<unsigned int> Converter::ConvertMesh( const MeshGeometry& mesh, const Model& model,
-    const aiMatrix4x4& node_global_transform )
+    const aiMatrix4x4& node_global_transform, aiNode& nd )
 {
     std::vector<unsigned int> temp;
 
@@ -1161,18 +1162,18 @@ std::vector<unsigned int> Converter::ConvertMesh( const MeshGeometry& mesh, cons
         const MatIndexArray::value_type base = mindices[ 0 ];
         for( MatIndexArray::value_type index : mindices ) {
             if ( index != base ) {
-                return ConvertMeshMultiMaterial( mesh, model, node_global_transform );
+                return ConvertMeshMultiMaterial( mesh, model, node_global_transform, nd );
             }
         }
     }
 
     // faster code-path, just copy the data
-    temp.push_back( ConvertMeshSingleMaterial( mesh, model, node_global_transform ) );
+    temp.push_back( ConvertMeshSingleMaterial( mesh, model, node_global_transform, nd ) );
     return temp;
 }
 
 
-aiMesh* Converter::SetupEmptyMesh( const MeshGeometry& mesh )
+aiMesh* Converter::SetupEmptyMesh( const MeshGeometry& mesh, aiNode& nd )
 {
     aiMesh* const out_mesh = new aiMesh();
     meshes.push_back( out_mesh );
@@ -1187,16 +1188,20 @@ aiMesh* Converter::SetupEmptyMesh( const MeshGeometry& mesh )
     if ( name.length() ) {
         out_mesh->mName.Set( name );
     }
+    else
+    {
+        out_mesh->mName = nd.mName;
+    }
 
     return out_mesh;
 }
 
 
 unsigned int Converter::ConvertMeshSingleMaterial( const MeshGeometry& mesh, const Model& model,
-    const aiMatrix4x4& node_global_transform )
+    const aiMatrix4x4& node_global_transform, aiNode& nd )
 {
     const MatIndexArray& mindices = mesh.GetMaterialIndices();
-    aiMesh* const out_mesh = SetupEmptyMesh( mesh );
+    aiMesh* const out_mesh = SetupEmptyMesh( mesh, nd );
 
     const std::vector<aiVector3D>& vertices = mesh.GetVertices();
     const std::vector<unsigned int>& faces = mesh.GetFaceIndexCounts();
@@ -1320,7 +1325,8 @@ unsigned int Converter::ConvertMeshSingleMaterial( const MeshGeometry& mesh, con
 }
 
 std::vector<unsigned int> Converter::ConvertMeshMultiMaterial( const MeshGeometry& mesh, const Model& model,
-    const aiMatrix4x4& node_global_transform )
+    const aiMatrix4x4& node_global_transform,
+    aiNode& nd )
 {
     const MatIndexArray& mindices = mesh.GetMaterialIndices();
     ai_assert( mindices.size() );
@@ -1331,7 +1337,7 @@ std::vector<unsigned int> Converter::ConvertMeshMultiMaterial( const MeshGeometr
     for( MatIndexArray::value_type index : mindices ) {
         if ( had.find( index ) == had.end() ) {
 
-            indices.push_back( ConvertMeshMultiMaterial( mesh, model, index, node_global_transform ) );
+            indices.push_back( ConvertMeshMultiMaterial( mesh, model, index, node_global_transform, nd ) );
             had.insert( index );
         }
     }
@@ -1341,9 +1347,10 @@ std::vector<unsigned int> Converter::ConvertMeshMultiMaterial( const MeshGeometr
 
 unsigned int Converter::ConvertMeshMultiMaterial( const MeshGeometry& mesh, const Model& model,
     MatIndexArray::value_type index,
-    const aiMatrix4x4& node_global_transform )
+    const aiMatrix4x4& node_global_transform,
+    aiNode& nd )
 {
-    aiMesh* const out_mesh = SetupEmptyMesh( mesh );
+    aiMesh* const out_mesh = SetupEmptyMesh( mesh, nd );
 
     const MatIndexArray& mindices = mesh.GetMaterialIndices();
     const std::vector<aiVector3D>& vertices = mesh.GetVertices();
```

Apparently meshes can have names, but if they're empty we just apply the parent node's name instead. This means there may be more than one mesh with the same node (depending on how the hierarchy was setup in Maya) but that's a limitation of the format and is far more useful like this than just having all meshes having blank names.

**Comment by Trylz** [comment]
Thanks alot, i will try it. What is the meaning of nd in aiNode& nd ?

**Comment by Trylz** [comment]
Works well. PR is there #1929

**Comment by darksylinc** [comment]
Hi! Thanks for turning it into a PR!

I just saw this commit message, the email notification sneaked into the spam box and I didn't notice until now.

As for "aiNode &nd", I'm just passing the parent node further down the several calls that ultimately create the mesh so that SetupEmptyMesh can access it and use its name.

That node came from Converter::ConvertModel and is passed to ConvertMeshMultiMaterial/ConvertMeshMultiMaterial (2nd overload)/ConvertMeshSingleMaterial and ultimately reaches SetupEmptyMesh where it's actually used.

**Comment by Trylz** [comment]
You welcome :) I see, i submitted as you implemented it .

**Comment by ivan-kadyko** [comment]
Hello.  I have problem with empty names in meshes in fbx 7.5. I use assimp.net 4.1 and load 3d-model fbx version 7.5 with flag PostProcessPreset.TargetRealTimeMaximumQuality.  If convert this fbx-model in version 7.4 I haven't issue.  I have attached zip-file for example. 
[empty_mesh_names_in_fbx_7.5.zip](https://github.com/assimp/assimp/files/3106524/empty_mesh_names_in_fbx_7.5.zip)

**Comment by mesilliac** [comment]
@ivan-kadyko that's strange, i just had a look and `buildings_7.5.fbx` seems to have mesh names, while actually `buildings_7.4.fbx` doesn't (using`assimp info` to check - in the 7.4 file they're named `Untitled.004` etc). Both of them do seem to have the correct _node_ names, however. Postprocessing splits the meshes into both into line and triangle meshes, but it does this for both 7.4 and 7.5. The node and mesh order has changed in the 7.5 file, but behaviour should be the same anyway.

In any case it sounds like a new issue. Can you open a new issue for it with some more detail on how you are testing the mesh name and what result you get when it's working correctly?

**Comment by ivan-kadyko** [comment]
I am sorry for delay. I also tested without postprocessing steps, only ordinary loading via "AssimpContext.ImportFile(string file)"

https://github.com/assimp/assimp/issues/2476
