### ISSUE TITLE
FBX Connections

### ISSUE THREAD

**Issue by AndreAhmed** [assimp/assimp#1809]
I use assimp fbx importer and I get a list of meshes. but There are materials that are not assigned to some meshes.  I opened the FBX ASCII file and I looked for the material name, I found it is in FBX Connections.  I looked for the documentation, but I don't understand how the FBX connections works, and how would I read it, so that I relate a material to a mesh.  Here is a screenshot of the my FBX file connections

[https://i.stack.imgur.com/iLzc2.png](url)

**Comment by mesilliac** [comment]
The material is connected to the model node in connections, and then if you have textures they are connected to attributes of the matrial. The geometry (mesh) is also connected to the model node alongside the material.

For example, something like:
```"OO", <model_node>, <root_node>
"OO", <geometry>, <model_node>
"OO", <material>, <model_node>
"OP", <diffuse_texture>, <material>, "DiffuseColor"```

**Comment by AndreAhmed** [comment]
Thanks. Why assimp doesn't assign the materials according to that structure ?

**Comment by mesilliac** [comment]
It does - if the materials are linked to the meshes they should be assigned. Sounds like a bug if they are not. Are you able to provide the fbx file that won't load correctly?

One possible cause would be if a program wrote a material definition that wasn't "lambert" or "phong". These are the only types properly supported by FBX, but programs can write pretty much anything, and sometimes do.

**Comment by AndreAhmed** [comment]
here is a sample file
[Fenster_Wand_180221_Revit.zip](https://github.com/assimp/assimp/files/1751407/Fenster_Wand_180221_Revit.zip)

**Comment by mesilliac** [comment]
Hmm, looks like most of the items in this fbx file are stored in "references" to some external resource. The fbx file itself doesn't actually have any materials in it, which is why assimp can't load them.

There should be an option in the FBX export dialog for the exporting program to export the references, after which assimp should be able to load them. Something like "referenced assets content"? (this is what it is in Maya)

**Comment by AndreAhmed** [comment]
Thanks for fast reply. but What should  I modify in Assimp to just get the names of the references.

**Comment by mesilliac** [comment]
In assimp it's not possible, because the fbx itself doesn't have a material definition. In stead the references are in some complex format, mostly specific to the application being used, and involving custom metadata sections added into the fbx.

**Comment by mesilliac** [comment]
if you want to take a look i recommend the fbx2json.py script Blender uses: https://github.com/scorpion81/blender-addons/tree/master/io_scene_fbx - the fbx data is pretty crazy :)

Like this is the only thing actually connected to the model:
```
        ["Object", [4514529216, "ProxyObject_Mauerwerk - Ziegel", ""], "LSS", [
            ["Properties70", [], "", [
                ["P", ["ADSKAssetReferenceID", "KString", "", "", "A3A549DA-616A-4977-B74F-AFED98A871FA"], "SSSSS", []]]]]],
```
but it just has this hashed reference id, nothing actually saying anything about what is referenced.

**Comment by AndreAhmed** [comment]
I just need the name  Mauerwerk-Ziegel.. not what connected it.. how would I retrieve that in assimp ?

**Comment by mesilliac** [comment]
It's not possible, because it's not ever defined as part of anything assimp can recognize. The only place the name is kept in the file is part of a program-specific metadata section. The only thing that can understand this section is the original program that wrote the fbx file (in this case "Autodesk Revit 2016")

**Comment by mesilliac** [comment]
there is literally no material definition in the fbx file

**Comment by AndreAhmed** [comment]
but at this line what does it mean

	;ProxyObject_Mauerwerk - Ziegel, Model::Basiswand WA-MW-24 [1074003]
	C: "OO",54976096,55035920

**Comment by mesilliac** [comment]
That's the object i printed above - it's not any kind of object understood by FBX, just something with the name "ProxyObject_Mauerwerk - Ziegel" and a hashed reference ID "A3A549DA-616A-4977-B74F-AFED98A871FA".

Presumably the reference will be understood by Revit, using its own internal data handling system. But sadly there's no way for another program to understand what it means, or use it in any meaningful way.

If it were an FBX material, it would be defined as a "Material", not an "Object", and assimp would indeed add it to the list of materials.

The best option if you want to analyze the FBX and extract data like this would probably be to convert it to JSON and use a JSON parsing tool, or else to use the FBX SDK which should have some way of iterating over all the available objects.
