### ISSUE TITLE
Need command line 'export' details

### ISSUE THREAD

**Issue by lslzl3000** [assimp/assimp#1813]
Cannot find doc details for command line 'export'~ 
We only know 'assimp export <model> [<out>] [-f<h>] [common parameters]'
Anyone give me more info for [-f<h>] and [common parameters]?

**Comment by mesilliac** [comment]
common parameters: http://sir-kimmi.de/assimp/lib_html/common.html

-f specifies the file format, in case it's not obvious from the file extension

**Comment by kimkulling** [comment]
And I need to update the doc. The current referenced version is 4.0.0.
