### ISSUE TITLE
DWG Fails 

### ISSUE THREAD

**Issue by AndreAhmed** [assimp/assimp#1816]
Hi I have this file that doesn't file an importer for it. Assimp fails on it.

[Wohnungstyp 14.dwg.zip](https://github.com/assimp/assimp/files/1759379/Wohnungstyp.14.dwg.zip)

**Comment by loebl** [comment]
DWG files are currently not supported. Due to the complexity of the format I doubt that any support is coming soon.

**Comment by LegalizeAdulthood** [comment]
@AndreAhmed You might want to look at this

https://github.com/codelibs/libdxfrw

Maybe that can work for you instead of assimp.

**Comment by tellypresence** [comment]
<a href="https://www.okino.com/convert/_single/dwg.htm">Okino</a> advises against using <tt>.dwg</tt> format:<br><tt>At Okino we consider DXF/DWG to be one of the worst 3D file formats when translating 3D model data between applications (depending on its contents). There is very little understanding about this in the 3D graphics world. As outlined in our <a href="https://www.okino.com/conv/demos.htm#bestpractices">"CAD Data Sourcing Suggestons and Rules"</a> page you should ideally use the <a href="https://www.okino.com/conv/imp_dwf.htm">DWF-3D</a> file format when sourcing from either AutoCAD, Navisworks, Revit and optionally Autodesk Inventor.</tt>
