### ISSUE TITLE
Cmake config not setting correct lib suffix

### ISSUE THREAD

**Issue by forry** [assimp/assimp#1831]
Under MSVC the cmake tries to generate library suffix. It makes it a cache variable so that user can change it but then it doesn't propagate it to the config file. The part of the suffix is hardcoded (the MSVC ver).

**Comment by kimkulling** [comment]
Thanks for the report!

**Comment by kimkulling** [comment]
Yes, the library suffic configured in the config in was set to FORCE. So a overwritten config for this variable will not be applied. I will fix that issue.

**Comment by forry** [comment]
Many thanks
