### ISSUE TITLE
CMake Error at CMakeLists.txt:965 (INSTALL):

### ISSUE THREAD

**Issue by dpMerchant** [assimp/assimp#1833]
I'm trying to compile source code 4.1.0 using CMake on Windows 10 with Visual Studio 2017. I am getting this error from CMake that stops the process.

CMake Error at CMakeLists.txt:965 (INSTALL):
  INSTALL TARGETS given no ARCHIVE DESTINATION for static library target
  "assimp".

I looked up this area in the CMakeLists.txt and I see this.

INSTALL( TARGETS assimp
  LIBRARY DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  ARCHIVE DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  RUNTIME DESTINATION ${ASSIMP_BIN_INSTALL_DIR}
  FRAMEWORK DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  COMPONENT ${LIBASSIMP_COMPONENT})

Can you give me an idea what is wrong. It seems that ASSIMP_LIB_INSTALL_DIR has no value and this is causing the error.

**Comment by kimkulling** [comment]
Normally this var is set to lib. You can set it manually when something went wrong. Just define it via:

`cmake -DASSIMP_LIB_INSTALL_DIR=lib 
`
to check if this fixes the issue. But remove the CMakeCache.txt before restarting it. If the issue is still there just reopen this issue.

**Comment by sagaceilo** [comment]
I had the same issue. Doing _cmake -DASSIMP_LIB_INSTALL_DIR=lib_ on clean state fixed it. I didnt cheked whats changed from last time I recompiled Assimp, but its either project configuration that changed or CMake version (checked on 3.13.3, last time I've used 3.11.x).
