### ISSUE TITLE
Issue during loading of model from issue 1527

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1853]
See https://github.com/assimp/assimp/issues/1527: try to import model: The head of the model is broken

**Comment by tellypresence** [comment]
This can probably be closed, the fault is likely with the model, not with assimp importer.

Note the problem with incorrect normals on right side of model face is also visible in Mac FBX review app [screenshot](https://user-images.githubusercontent.com/4158417/32315357-cbaa7a80-bfd1-11e7-8c44-4e7644aa8c71.png)
