### ISSUE TITLE
field of view computation for blender files is off by a factor of 2

### ISSUE THREAD

**Issue by jkrueger** [assimp/assimp#1854]
https://github.com/assimp/assimp/blob/d81078edddb815031cf6072dc11d98a4db18392f/code/BlenderLoader.cpp#L1150

I think the calculation for the field of view form focal length and sensor width isn't correct. The relationship between the two is d/2f = tan fov/2, so the computation is off by a factor of two.

**Comment by Gargaj** [comment]
> 
> 
> [assimp/code/BlenderLoader.cpp](https://github.com/assimp/assimp/blob/d81078edddb815031cf6072dc11d98a4db18392f/code/BlenderLoader.cpp#L1150)
> 
> Line 1150 in [d81078e](/assimp/assimp/commit/d81078edddb815031cf6072dc11d98a4db18392f)
>  out->mHorizontalFOV = std::atan2(cam->sensor_x,  2.f * cam->lens); 
> 
> I think the calculation for the field of view form focal length and sensor width isn't correct. The relationship between the two is d/2f = tan fov/2, so the computation is off by a factor of two.

Where "d" is the focal length?
