### ISSUE TITLE
FBX import error during validation for light nodes

### ISSUE THREAD

**Issue by loebl** [assimp/assimp#1855]
Our program writes FBX ver 7 Light nodes with duplicate names (it's always "Light"). Starting with FBX 7 this is valid.
Assimp throws an error during validation for those duplicate node names, preventing import (unless validation is disabled in post-processing).

Primitive example attached.
[light_box.zip](https://github.com/assimp/assimp/files/1841932/light_box.zip)

**Comment by kimkulling** [comment]
Interesting, not unique names are aallowed now? So we have to diduingish between them by an id?

**Comment by kimkulling** [comment]
I canot see any light definitions ( in Blender ). Is this the right model?

**Comment by loebl** [comment]
Just tested it here with Blender 2.79 (2017-09-11) and the light nodes are there (although possibly not with parameters that make sense; I only threw them in the scene). There are inserted under FbxWorldNode -> LightsNode.

I converted the model to ASCII FBX if you want to take a look at the file structure itself. (But Blender won't load this).
[light_box_ascii.zip](https://github.com/assimp/assimp/files/1851688/light_box_ascii.zip)

And the duplicate naming issue is mentioned in the docs for the SDK [in the first note here](http://help.autodesk.com/view/FBX/2018/ENU/?guid=FBX_Developer_Help_nodes_and_scene_graph_fbx_nodes_html). The SDK itself will make names unique if the target file format do not support them. My example file (Version 7.4 generated with SDK 2018.1) does contain duplicate names, so they are supported by the file format.

**Comment by kimkulling** [comment]
OK, thanks for the hint. I just found the definitions. I guss we cantry to deal with this by generating unique names for the light nodes ( something like <orig_name>.001, <orig_name_.002 etc.

**Comment by kimkulling** [comment]
So I guess I found the reason. The FBX importer is checking if any nodes are already defined. UNfortunately the implemented mechanism for renaming these nodes is currently broken. I will figure out how to deal with this.

**Comment by kimkulling** [comment]
PLease check https://github.com/assimp/assimp/pull/1864
