### ISSUE TITLE
{COLLADA} Dropped transform on child node

### ISSUE THREAD

**Issue by asmaloney** [assimp/assimp#1869]
I am loading an old test model (I got it from Khronos at some point as a reference model). It is animated, but I'm not doing anything with that. (I'm also not using textures yet.)

Here is what I'm using to load:
```
Assimp::Importer importer;
	
importer.SetPropertyInteger( AI_CONFIG_PP_RVC_FLAGS,
					aiComponent_ANIMATIONS |
					aiComponent_BONEWEIGHTS |
				 	aiComponent_CAMERAS |
					aiComponent_LIGHTS );
	
const aiScene	*scene = importer.ReadFile( fileName,
					aiProcess_CalcTangentSpace | 
					aiProcess_Triangulate |
					aiProcess_JoinIdenticalVertices );
```

(Even if I don't remove anything with SetPropertyInteger() I get the same results.)

It's supposed to look like this:
![plane](https://user-images.githubusercontent.com/391371/38179331-016b07cc-35f0-11e8-86ce-a75bcbd4f54d.jpg)

Instead when I load it, I get this (the yellow is just my selection box around the propeller):
![my plane](https://user-images.githubusercontent.com/391371/38179354-53373c56-35f0-11e8-90ad-689bcbc86724.jpeg)

The propeller is the mesh that is animated in this model.

Am I correct in assuming that the model should look proper without having to do anything with the animations?

Here's the model:

[Seymour_Plane.zip](https://github.com/assimp/assimp/files/1866844/Seymour_Plane.zip)

Thank you!

**Comment by asmaloney** [comment]
I copied the example and removed the animation to simplify and still have the same result. Looking at the file I noticed that there is a `<translate>` on the "prop" that is precisely what's missing - translation in the z:

```xml
<node id="plane" name="plane">
    <rotate sid="rotateZ">0 0 1 0</rotate>
    <rotate sid="rotateY">0 1 0 0</rotate>
    <rotate sid="rotateX">1 0 0 0</rotate>
    <instance_geometry url="#planeShape-lib">
        <bind_material>
            <technique_common>
                <instance_material symbol="matteSG" target="#matte">
                    <bind_vertex_input semantic="TEX0" input_semantic="TEXCOORD" input_set="0"/>
                </instance_material>
                <instance_material symbol="shineSG" target="#shine">
                    <bind_vertex_input semantic="TEX0" input_semantic="TEXCOORD" input_set="0"/>
                </instance_material>
            </technique_common>
        </bind_material>
    </instance_geometry>
    <node id="prop" name="prop">
        <translate sid="translate">0 0 5.40413</translate>
        <rotate sid="rotateZ">0 0 1 15</rotate>
        <rotate sid="rotateY">0 1 0 0</rotate>
        <rotate sid="rotateX">1 0 0 0</rotate>
        <instance_geometry url="#propShape-lib">
            <bind_material>
                <technique_common>
                    <instance_material symbol="shineSG" target="#shine">
                        <bind_vertex_input semantic="TEX0" input_semantic="TEXCOORD" input_set="0"/>
                    </instance_material>
                </technique_common>
            </bind_material>
        </instance_geometry>
    </node>
</node>
```

I spent some time looking at the code and don't see anything obviously incorrect.

**Comment by asmaloney** [comment]
I've removed everything I could (materials, etc.) and just left the geometry to try to make a smaller example:

[seymourplane_stripped.zip](https://github.com/assimp/assimp/files/1882002/seymourplane_stripped.zip)

**Comment by kimkulling** [comment]
Great, thanks a lot for the bug report!

**Comment by asmaloney** [comment]
This is my bug. As far as I can tell assimp's doing the right thing.
