### ISSUE TITLE
Objects rendering as yellow in assimp_qt_viewer on Linux

### ISSUE THREAD

**Issue by DMJC** [assimp/assimp#1877]
Textured 3D Objects are rendering as bright yellow in assimp_qt_viewer on Linux. 
What it should look like:
![image](https://user-images.githubusercontent.com/732515/38281696-42753d04-37ef-11e8-836a-819d88af4f37.png)

Screenshot of assimp_qt_viewer:
![image](https://user-images.githubusercontent.com/732515/38281712-59d8f49a-37ef-11e8-89a4-ff8ea0fb141c.png)

**Comment by DMJC** [comment]
Only occurs when lighting is disabled.

**Comment by DMJC** [comment]
Submitted patch for review. Fix was to add a call to qglcolor(QColor::white) after the yellow axis draw.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/1879
