### ISSUE TITLE
Compilation for an Android ndk project (c++ opengles animation, JAVA activity)

### ISSUE THREAD

**Issue by Nicolas-Loew** [assimp/assimp#1880]
I have a problem with the compilation of ASSIMP for Android.

I use the Android NDK (and JNI) to call my C++ code in a JAVA activity.

Gradle calls my CMakelist to compile my shared library. In this CMakelist I target my .cpp files and my library subdirectory (assimp and glm). The assimp build throws an error: 'error: cannot find -lpthread'

My problem is: how can I compile ASSIMP and how can I include assimp in my Android NDK project?

**Comment by kimkulling** [comment]
This dependency was required for compiling gtest with the unittests. You can just switch them off by using the following option:

 ```
externalNativeBuild {
        cmake {
            arguments '-DASSIMP_BUILD_ZLIB=ON -DASSIMP_BUILD_TESTS=OFF'
            cppFlags '-fexceptions -frtti -std=c++11'
        }
    }
```
