### ISSUE TITLE
Make StreamReader::Get<T> and StreamWriter::Put<T> public

### ISSUE THREAD

**Issue by NebuHiiEjamu** [assimp/assimp#1881]
When dealing with formats, a lot of data blocks (file headers, for example) are read into defined structs, often byte-packed. IOStream::Read() does as it should, but if the endian is reversed, each field of the struct must be byte swapped. The alternative to this is to make several calls to StreamReader::GetX#() which seems ugly for packed structs. Get<T>() and Put<T>() seem to aleviate that problem, but they are currently private to their respective Stream classes.

**Comment by kimkulling** [comment]
Good idea. Pull request is on its way.
