### ISSUE TITLE
mirror modifier in blender importer makes duplicates

### ISSUE THREAD

**Issue by malytomas** [assimp/assimp#1885]
I would expect that output of the mirror modifier would be single mesh with all the "reflections" merged together. Or is the current behavior preferred?

**Comment by kimkulling** [comment]
Sorry, I am confused. Which mirror modifier do you mean?

**Comment by malytomas** [comment]
Imagine a single mesh in blender. If I apply a mirror modifier in blender on it, it is still treated as a single object. However, if I import the blend file directly with assimp, the assimp will apply the mirror modifier (which is amazing improvement btw :D ), however, it will produce multiple objects, all with the same name.

This behavior could be intentional, if the mesh itself was not modified, and only new node was added to scene graph with "mirroring" matrix, to save some memory.
However, this is not what a blender user would expect. More so, that the modifier in blender is able to merge (crop) "overlapping" parts of the mesh.

I am not familiar with assimp internals, but from a quick look, I have found a function that merges multiple meshes. I may try to add it to the modifier. My question is, which behavior do you actually prefer?

This is the modifier in assimp: https://github.com/assimp/assimp/blob/9fd6744f9313ca890f9a48788151ad1385922cdb/code/BlenderModifier.cpp#L186

**Comment by kimkulling** [comment]
OK, didn' know this. First thing would be to give the mirrored objects a new name I guess.
