### ISSUE TITLE
GCC DLL linker error: export ordinal too large

### ISSUE THREAD

**Issue by NebuHiiEjamu** [assimp/assimp#1886]
Trying to build a debug DLL of Assimp's latest git revision on MinGW-w64 with MSYS2 and it errors on the linking phase with this:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Error: export ordinal too large: 66050
```

I'm not sure what to do. Perhaps there's a function with an unusually high index? Static library still compiles just fine. 4.1.0 DLL, in contrast, builds with only 781 exported symbols. MSVC builds the latest revision as a DLL just fine also, with only around 900 symbols. There is no reason why the GCC DLL should have an index of 66050.

**Comment by kimkulling** [comment]
OK, thanks for the report. We need to check. Anyone an idea?

**Comment by NebuHiiEjamu** [comment]
Well to reproduce it, I use MSYS2, which can be found at msys2.org I used the mingw-w64-x86_64 build chain (cmake, mingw-w64-x86_64-{gcc,zlib}) with debug and "MSYS Makefiles" generator.

**Comment by JekaS178RUS** [comment]
Have same problem, but value of esport symbol is different: 81740

**Comment by JekaS178RUS** [comment]
There is what I have found about this issue on stackoverflow:

It considers the ordinal to be an unsigned 16-bit integer (range 0-65535) and therefore the ordinal number supplied it out of range. I couldn't find anything in the documentation for [EXPORTS ](https://docs.microsoft.com/en-us/cpp/build/reference/exports)that specified the valid range of ordinals, but the Export Ordinal Table [documentation ](https://docs.microsoft.com/ru-ru/windows/desktop/Debug/pe-format#export-ordinal-table)confirms that the indices are 16-bit integers

**Comment by JekaS178RUS** [comment]
Made some tests again on this issue. this time I used Qt creator with different build system MSYS Makefiles,  MinGW Magefiles, NINJA everywere same problem, which is reasonable because compiller and linker is same.

But problem present only in Debug mode, Release and Release with debug info works fine

**Comment by gallickgunner** [comment]
Any update on this issue? I'm trying to compile the latest repo through Cmake using `Mingw-w64 8.1.0`. And it throws the same error. The value of the symbol is different tho, it's 81581.

**Comment by kimkulling** [comment]
Yeah! Just check it again. The step data structures are currently not part of the lib any more.
