### ISSUE TITLE
Ifc4 models

### ISSUE THREAD

**Issue by Vizzr** [assimp/assimp#1889]
I need to import Ifc models for a project of mine, but I cannot load Ifc 4 models.

I've read other issues where you said you are working on complete ifc 4 support.

A comment from January 15th says that you are working on supporting it completely.
Is there any estimation of when it will be completely supported?

And is there a way to bypass loading Ifc 4 models?

**Comment by kimkulling** [comment]
Will close this one to track all feature-requests in one issue report.
