### ISSUE TITLE
glTF 2.0 tangents should be read as vec4

### ISSUE THREAD

**Issue by revolucas** [assimp/assimp#1892]
According to glTF specs, https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes

Tangents are a vec4 with 'w' specifying handedness. I'm unable to get proper looking normals with just the x,y,z.

**Comment by kimkulling** [comment]
So you need vec4 from the aiMesh?

**Comment by revolucas** [comment]
Yes, mTangents returns aiVector3D. Unless there is some other way to get handedness of the tangent basis?

**Comment by Sailsman63** [comment]
This sounds like more of an importer issue: assimp's API is that all tangents are `aiVector3D`, and it is assumed that they are all of the same handedness. (RH by default)

`glTF` allows you to use the `w` component to specify whether that particular tangent is LH or RH. I'd think that the importer should read that component, and based on its value, convert the tangent to whichever handedness is being used across this particular `aiMesh`.

**Comment by kimkulling** [comment]
And in the importer the type for a tangent type looks like:

```
struct Tangent {
    aiVector3D xyz;
    ai_real w;
} *tangents = nullptr;

```
So the requirement is fullfilled.
