### ISSUE TITLE
OBJ export + OptimizeGraph: All groups get name "$MergedNode_0"

### ISSUE THREAD

**Issue by TripleSnail** [assimp/assimp#1894]
When importing an OBJ file and using OptimizeGraph (-og) flag, all groups (g) in the exported file are named  "$MergedNode_0".

This happens, because OptimizeGraph combines all nodes into one node called $MergedNode_0. This name is then used for all groups (g).

```
// In  ObjExporter::AddNode
for(unsigned int i = 0; i < nd->mNumMeshes; ++i) {
        // For all nodes after OptimizeGraph
        // nd->mName == "$MergedNode_0"
        AddMesh(nd->mName, pScene->mMeshes[nd->mMeshes[i]], mAbs);
}
```

Using the name of a mesh seems to produce more desirable results.

Tested on the latest commit 6a0dc071a967be9d69ed86228f21be04dfec23d6, but I think this happened on 4.1 too.

**Comment by kimkulling** [comment]
Ok, thanks for the hint. I opened a pull-request to test your new naming strategy.
