### ISSUE TITLE
FBXExporter doesn't write the root node

### ISSUE THREAD

**Issue by PLeoncini** [assimp/assimp#1897]
Hi, many thanks for this valuable new feature of the library.
Yet, it seems to me like the subject exporter doesn't actually write just the root node. In the current code, in:

`void FBXExporter::WriteModelNodes(
    StreamWriterLE& outstream,
    const aiNode* node,
    int64_t parent_uid,
    const std::unordered_set<const aiNode*>& limbnodes,
    std::vector<std::pair<std::string,aiVector3D>>& transform_chain
)
`

it seems to miss all chanches to write the root node, i.e.:

```
	if (node_name.find(MAGIC_NODE_TAG) != std::string::npos) {
```
yet, unfortunately, I don't come from a previous FBX import (I generate the Assimp scene by conversion)

```
	// generate uid and connect to parent, if not the root node,
	if (node != mScene->mRootNode)
```
no comment

```
	if (node == mScene->mRootNode) {
		// handled later
```
no comment

```
 	// if more than one child mesh, make nodes for each mesh
	if (node->mNumMeshes > 1 || node == mScene->mRootNode) {
		for (size_t i = 0; i < node->mNumMeshes; ++i) {
			...
		}
	}
```
the case node == mScene->mRootNode is considered, yet if node->mNumMeshes is 0 the for doesn't actually execute.

I suggest the two following modifications, which worked in my case:

```
	// generate uid and connect to parent, if not the root node,
#if 0 // original code
	if (node != mScene->mRootNode)
#else
	// do it even for the root node, since soon it'll be written down too
#endif
	{
		...
	}

	// what type of node is this?
	if (node == mScene->mRootNode) {
#if 0 // original code
		// handled later
#else
		// write down the root node - I choosed the "Model" type string, maybe there could be a better type...
		WriteModelNode(outstream, binary, node, node_uid, "Model", transform_chain);
#endif
````
Once again, thanks to the contributors for the committment,
Paolo

**Comment by mesilliac** [comment]
Hi Paolo, indeed the root node in FBX files is never explicitly written. If there is important information there, probably the best thing to do would be to add another node below the root node, and parent everything to it. It's a "feature" of FBX files that the root node is not there, so possibly writing it would not be handled correctly by other programs.
