### ISSUE TITLE
Helper bones are disregarded

### ISSUE THREAD

**Issue by GovanifY** [assimp/assimp#1901]
Hi,
I am currently making a model importer based on assimp which disregards any bone that doesn't affect vertices directly, "helper" bones.
While this might be a wanted behaviour in most cases(gamedev, export optimization, etc) it prevents me from reusing animations made for the said model, as the bone counts doesn't match anymore.

I would so believe that adding a post-processing flag to disable this feature might be helpful, as the contrary would break assimp behaviour on older softwares.
Does this sound fair or is there anything I'm missing with the current state of Assimp? Because as far as I can tell this omission is hardcoded directly in the importers (here is for example the collada importer doing that https://github.com/assimp/assimp/blob/master/code/ColladaLoader.cpp#L823 )

**Comment by mesilliac** [comment]
I agree this would be nice, it has been a problem for me as well.

An importer parameter might be better than a post-processing flag, as it could be implemented for one importer at a time with little effort.

I'm not sure what the general assimp policy is on this sort of thing (?).

**Comment by Topaz-Reality** [comment]
I agree that this is an issue. One of my friends whom tried to work on ann imported faced this exact issue, he gave up making it completely afterwards.

Maybe if this is fixed, I can get him back to do it. I really want custom models in God of War 1.

**Comment by kimkulling** [comment]
This issue shall be fixed now.
