### ISSUE TITLE
assimp-config.cmake sets incomplete ASSIMP_LIBRARIES

### ISSUE THREAD

**Issue by daef** [assimp/assimp#1912]
I had troubles running debug builds using assimp (compiled & installed via vcpkg)
After some investigation it seems that the library-path in assimp-config.cmake is not complete.

Find attached a [test project](https://github.com/assimp/assimp/files/1942032/asstst.zip) that fails to copy assimp-vc140-mtd.dll on build unless ASSIMP_LIBRARIES is adapted (see https://github.com/Microsoft/vcpkg/issues/3193 )

**Comment by daef** [comment]
All my problems went away when I stared using the current version and importing assimp::assimp instead of ${ASSIMP_LIBRARIES} in my cmake

**Comment by kimkulling** [comment]
Fixed?
