### ISSUE TITLE
Compiler warning: warning C4800: 'void *': forcing value to bool 'true' or 'false' (performance warning)

### ISSUE THREAD

**Issue by Kessica** [assimp/assimp#1930]
Although not serious, there is a performance impact with this: This using the current build using Visual Studio 2015.

assimp\include\assimp\metadata.h(152): warning C4800: 'void *': forcing value to bool 'true' or 'false' (performance warning)

The lines around this error are:
    case AI_BOOL:
       mValues[ i ].mData = new bool( rhs.mValues[i].mData );
       break;

It probably requires a cast if this is the intended operation.

Cheers

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/commit/8d42b31e20136cb8779f1bffef5ce7744f36b084
