### ISSUE TITLE
Memory leak in SortByPTypeProcess

### ISSUE THREAD

**Issue by Aneoshun** [assimp/assimp#1934]
Hi all, 

It looks like there is a memory leak in the SortByPTypeProcess (postprocessing).

If you reach this line:
https://github.com/assimp/assimp/blob/410e9d4b3f7b3cd921310aea5c24d04cfd57a8ff/code/SortByPTypeProcess.cpp#L190
the mesh currently processed is just lost (not added to outMeshes and not freed).
I tried to free the mesh like this:
``` 
else {
   // delete the input mesh                                                                                                                                                                      
   delete mesh;
   // avoid invalid pointer                                                                                                                                                                      
   pScene->mMeshes[i] = NULL;
   bAnyChanges = true;
}
```
and it solves the memory leak that I had in my code.

EDIT: Apparently this has already been reported in #962, but it looks like it has not been fixed.

I am using ubuntu 16.04, and Assimp from Master.
Let me know if you need more details.
If needed, here is the corresponding valgrind report:

> 6,368 (5,184 direct, 1,184 indirect) bytes in 4 blocks are definitely lost in loss record 5 of 6
==27710==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27710==    by 0x6358CB8: Assimp::ColladaLoader::CreateMesh(Assimp::ColladaParser const&, Assimp::Collada::Mesh const*, Assimp::Collada::SubMesh const&, Assimp::Collada::Controller const*, unsigned long, unsigned long) (ColladaLoader.cpp:598)
==27710==    by 0x6358781: Assimp::ColladaLoader::BuildMeshesForNode(Assimp::ColladaParser const&, Assimp::Collada::Node const*, aiNode*) (ColladaLoader.cpp:543)
==27710==    by 0x6356F10: Assimp::ColladaLoader::BuildHierarchy(Assimp::ColladaParser const&, Assimp::Collada::Node const*) (ColladaLoader.cpp:265)
==27710==    by 0x6356DF3: Assimp::ColladaLoader::BuildHierarchy(Assimp::ColladaParser const&, Assimp::Collada::Node const*) (ColladaLoader.cpp:253)
==27710==    by 0x635676D: Assimp::ColladaLoader::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) (ColladaLoader.cpp:179)
==27710==    by 0x6233B0D: Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) (BaseImporter.cpp:99)
==27710==    by 0x6247271: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:649)
==27710==    by 0x62255C6: aiImportFileExWithProperties (Assimp.cpp:192)
==27710==    by 0x5539059: dart::dynamics::MeshShape::loadMesh(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<dart::common::ResourceRetriever> const&) (in /home_nfs/antoine/workspace/lib/libdart.so.7.0.0)
==27710==    by 0x5D2CDF5: std::shared_ptr<dart::dynamics::Shape> dart::io::DartLoader::createShape<urdf::Visual>(urdf::Visual const*, dart::common::Uri const&, std::shared_ptr<dart::common::ResourceRetriever> const&) (in /home_nfs/antoine/workspace/lib/libdart-io-urdf.so.7.0.0)
==27710==    by 0x5D22CC6: dart::io::DartLoader::createShapeNodes(urdf::ModelInterface const*, urdf::Link const*, dart::dynamics::BodyNode*, dart::common::Uri const&, std::shared_ptr<dart::common::ResourceRetriever> const&) (in /home_nfs/antoine/workspace/lib/libdart-io-urdf.so.7.0.0)
==27710== 
==27710== LEAK SUMMARY:
==27710==    definitely lost: 5,184 bytes in 4 blocks
==27710==    indirectly lost: 1,184 bytes in 28 blocks
==27710==      possibly lost: 0 bytes in 0 blocks
==27710==    still reachable: 72,704 bytes in 1 blocks

**Comment by kimkulling** [comment]
Thanks a lot for the report. I will fix that.

**Comment by kimkulling** [comment]
Fixed.
