### ISSUE TITLE
can not read fbx file

### ISSUE THREAD

**Issue by miniminiming** [assimp/assimp#1936]
Scene import failed: No suitable reader found for the file format of file "/data/user/0/ming.com.assimptest/files/shadow_fiend_econ.fbx".

**Comment by kimkulling** [comment]
Could you please provide the test-file?

And thanks for the report.

**Comment by aavenel** [comment]
Based on the filename, I think you can download the test file here : http://www.dota2.com/workshop/requirements/nevermore

I have a different error message : 
```
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: FBX-Parser (TOK_DATA, offset 0x9cdc6) failed to parse ID, unexpected data type, expected L(ong) (binary)
assimp info: Unable to load input file Downloads\nevermore\shadow_fiend_econ.fbx
```

**Comment by rebirth123** [comment]
Do you know what fbx version you're using or what app made it?  It seems fbx works well at my end (some as old as 2013 exported from Maya).  I have had problems with some animated files, but I usually fixed it by playing with the export settings (can't recall exactly what I did).

**Comment by kimkulling** [comment]
Shall work now.
