### ISSUE TITLE
Integrate with Hunter

### ISSUE THREAD

**Issue by Binero** [assimp/assimp#1946]
[Hunter](https://github.com/ruslo/hunter) is a package manager for cmake. It automatically downloads dependencies and builds them, while the interface to packages is the same as find_package. 

At the moment there is a [fork](https://github.com/hunter-packages/assimp) of assimp that integrates with hunter, but it is quite dated.

I propose to support hunter in-tree, to prevent it from falling behind in the future. Package managing in C++ sucks (just look at this very project's CMakeLists.txt file), and hunter takes a bit of that pain away.

**Comment by NukeBird** [comment]
+1!

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2488
