### ISSUE TITLE
[FBX] Embedded Texture in ASCII FBX doesn't seems to be read

### ISSUE THREAD

**Issue by Natches** [assimp/assimp#1957]
I found that there isn't any texture found from this FBX file, but one is embedded in ( line : 432 ).
I think this is because this FBX is saved in ASCII and when ASSIMP try to load the content, it seems to fail here  ( line : 310 of  FBXMaterial.cpp ) :
`if (!token.IsBinary()) {
                DOMWarning("video content is not binary data, ignoring", &element);
            }`.
At the end there is no Texture in the aiScene.
Here is the FBX : [TexturedCube.zip](https://github.com/assimp/assimp/files/1997215/TexturedCube.zip) .

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2407
