### ISSUE TITLE
UTF8-encoded Paths, MAX_PATH-reliancy

### ISSUE THREAD

**Issue by acgessler** [assimp/assimp#197]
Related to the now closed #194:
- Handle UTF8-encoded paths
- Do not rely on MAX_PATH and MAX_PATH reliant APIs as it is not actually a requirement on most filesystems.

While the original PR has been closed for now due to the UTF8 conversion code there being partly from DWG/DWF, it should be migrated to use our own Unicode conversion code and then applied.

**Comment by abma** [comment]
thats a very simple snipped to convert utf8 to wchar:

https://github.com/spring/pr-downloader/blob/dfb39dbce607a7de724cb579f486784862c9434e/src/Util.cpp#L117

maybe not cleanest / fastest code, but worked for me pretty well

**Comment by kveretennicov** [comment]
FWIW, we have been bitten by this (targeting Win32) and will probably implement IOStream as an emergency workaround.

**Comment by kimkulling** [comment]
Any updates?
