### ISSUE TITLE
BLEND importer dont support multiple UV sets on mesh object

### ISSUE THREAD

**Issue by CwTCwT** [assimp/assimp#1973]
i tried to import blender project using 2 textures each using own set of UV coords (see attached zip, used blender version: 2.79b).
but from debug i saw only one set of uv maps is imported/converted.

[plane_2_textures_2_texcoords.zip](https://github.com/assimp/assimp/files/2020293/plane_2_textures_2_texcoords.zip)

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2005
