### ISSUE TITLE
CmakeList.txt - How to add only the .FBX importer?

### ISSUE THREAD

**Issue by VelvetPigeon** [assimp/assimp#1976]
Hey, I've downloaded current state of repository and I want to include only the .fbx importer to the build.
Can some one show me how CMakeList should be set up to do so? There were some changes in CMakeList that removed all importers from configuration process in CMake.
[I don't understand this at all...](https://github.com/assimp/assimp/commit/908ef3e44ad37c087724553943aacb86f5f3804c#diff-663e9ee46a1a0eda8178422a576884b3)
![image](https://user-images.githubusercontent.com/39524869/40366334-23ea215c-5dd7-11e8-8719-6784a4f9f2d2.png)

**Comment by mesilliac** [comment]
You shouldn't need to edit the CMakeLists.txt at all - rather you should add configuration options to your build. It seems you already have a GUI to do this? In this GUI you're using you can check options like `ASSIMP_NO_EXPORT` which will disable the exporters, and you can select only `ASSIMP_BUILD_FBX-IMPORTER`, making sure all the other `ASSIMP_BUILD_XXX_IMPORTER` are unchecked. Then it will only include FBX import and nothing else.

**Comment by VelvetPigeon** [comment]
There is no "ASSIMP_BUILD_FBX_IMPORTER" option to check in CMake after "Configuration" being hit.
I've added this "OPTION(ASSIMP_BUILD_FBX_IMPORTER "test" YES)" to "CMakeLists.txt" but it did not help, its showing me 0 importers selected after "Configuration" being press.

**Comment by kimkulling** [comment]
Thanks a lot for the feedback, I guess we need to add this to our FAQ.
