### ISSUE TITLE
glTF2 Importer: animations

### ISSUE THREAD

**Issue by corporateshark** [assimp/assimp#1983]
There is a `LazyDict<Animation> animations` member field in `glTF2Asset.h`. However, it is never used in `glTF2Importer`.

**Comment by PixelClear** [comment]
Any one working one this issue?
I am also looking for same fix?

**Comment by ne0ndrag0n** [comment]
Does assimp 4.1.0 support importing glTF2 animations yet? gltf 2.0 export has both channels and samplers fields but no animations are found.

**Comment by corporateshark** [comment]
@ne0ndrag0n Nope, it does not support importing of animations. It does not even read glTF2 animation data into the internal data structs.

**Comment by kimkulling** [comment]
That is bad. So I will mark this as a bug.

**Comment by corporateshark** [comment]
Both skeletal and node animations are necessary.

**Comment by PixelClear** [comment]
@kimkulling Any clues when 5.0 will be out?

**Comment by EvilPudding** [comment]
This seems really easy to implement, is anyone on it or could I look into it?

**Comment by corporateshark** [comment]
@EvilPudding It seems no one is working on it right now. But having it fixed would be just awesome!
