### ISSUE TITLE
PyPI version mismatch

### ISSUE THREAD

**Issue by rspencer01** [assimp/assimp#1986]
This is an issue to track the fact that PyPI has a different version to specified in the `setup.py`.  The current version of `pyassimp` tracks that of `assimp` and (as of writing) is `4.1.0`.  However, the version uploaded to PyPI is `4.1.3` due to issues the maintainer had while trying to set the authors attribute after #1969.

This issue will be resolved when `assimp` catches up to `4.1.3` or surpasses it.  In future we should probably use sub-micro version numbers (eg `4.1.0.2`, `4.1.0.3` etc.) to version the python specific code.

**Comment by kimkulling** [comment]
Shall be fixed, just merged the pull-request.
