### ISSUE TITLE
Change aiString::length to uint32_t

### ISSUE THREAD

**Issue by turol** [assimp/assimp#1993]
There's big hack in 
https://github.com/assimp/assimp/blob/fd2a71b3fd6c8a6b06c98b56dcab7695a389f528/code/MaterialSystem.cpp#L529
which says that aiString length really should be `uint32_t` but this breaks the ABI.

We should do this before the next release. Since the ABI changes we need to bump the major version to 5. Should I go ahead and do this?

**Comment by kimkulling** [comment]
Yes, please! No more hacks. I am fighting with a lot of hacks when portng to unicode on windows.

**Comment by turol** [comment]
On further consideration we should do a stable 4.x release first and then do this and any other ABI-related changes. This might cause subtle bugs and we should test the git version for a while to make sure we got them all.

**Comment by kimkulling** [comment]
At the moment we havae already ABI-breaking changes in the main branch. SO we need to branch from 4.1.0 and cherrypick.

**Comment by turol** [comment]
Should I send a PR which increases major version to 5?

**Comment by smalcom** [comment]
Hm, but size_t is better, isn't it?
Just change "unsigned int mDataLength;" to "size_t mDataLength;" in "struct aiMaterialProperty" and
"HACK" can be removed.

**Comment by kimkulling** [comment]
This issue is already fixed. ai_uint32_t is already in use.
