### ISSUE TITLE
Normals generated by assimp

### ISSUE THREAD

**Issue by dasmysh** [assimp/assimp#1995]
This is less an issue and more a question/discussion but I did not find a better place to put it :).

I am in the unfortunate position needing to load meshes with normals already present but they are incorrect. Assimp currently has the option to generate normals, but only if they are not already present.

Is there a reason why not to have an option to force assimp to regenerate the normals?

If there is no reason, I am willing to make a pull request for that feature but I am also in doubt how implement that the best way. Would you create an additional post process or enhance the two existing ones?

**Comment by kimkulling** [comment]
There is a simple reason for that: I guess you are the first person who requests this :-). Feel free to provide a pull request for  that feature-request. From my point of view this makes completly sense.
