### ISSUE TITLE
FBX ReadFile DeadlyImportError 

### ISSUE THREAD

**Issue by JrIndie** [assimp/assimp#1997]
I am using 4.1.1 from: https://github.com/assimp/assimp/releases/tag/v4.1.0

Whenever I call importer.ReadFile, I get this error in output:
```
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
Exception thrown at 0x00007FFC94E9F218 in AssimpConverter.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x00000070DCF8DDD8.
```

```
const aiScene* scene = importer.ReadFile(
            fileName.c_str(),
            aiProcess_CalcTangentSpace |
            aiProcess_JoinIdenticalVertices |
            aiProcess_Triangulate | aiProcess_SortByPType
        );
```

My blender is 2.79, any reason why?

**Comment by kimkulling** [comment]
Which file do you try to import?

**Comment by JrIndie** [comment]
It is a file our artist made.  Do you need the file?  I can send you a portion of the file via email.  Collada export and loading via Assimp works however.

**Comment by kimkulling** [comment]
Would be great to get a small file which reproduce the issue.

**Comment by JrIndie** [comment]
I downloaded blender 2.72 from the year 2014. .... FBX still does not work. I guess its been broken for a while??? Should be noted I guess. Or maybe my blender file is unique, but Im not sure how unique it could be, its just an animation.

To anyone who comes here looking for answers...  Either pray and hope this gets fixed, or move on and build your own parser.

**Comment by clcaalu** [comment]
I had the same problem. Thanks to the FBX converter I had it working!! It works only for me using [FBX Converter](https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives) with versions 2013, 2012 and 2011
Files exported using Blender failed.

**Comment by JrIndie** [comment]
Attached is an example

[Example.zip](https://github.com/assimp/assimp/files/2338196/Example.zip)

**Comment by JrIndie** [comment]
Attached is an example.

[Example.zip](https://github.com/assimp/assimp/files/2338206/Example.zip)

**Comment by griffin2000** [comment]
Works fine for me in Blender 2.77. Can export to FBX and import to Assimp fine (version 88c1ec827). 

[Example.zip](https://github.com/assimp/assimp/files/2338298/Example.zip)

**Comment by JrIndie** [comment]
Attached is 1 mesh + animations + 1 material to reproduce the issue.

[Example.zip](https://github.com/assimp/assimp/files/2338359/Example.zip)

**Comment by griffin2000** [comment]
Hmmm also works fine for me at b4860aef20cc18f22897d2b0810bb5e88c1ec827

`param = -lh
param = -fuv
param = -sbpt
param = -cts
param = -jiv
param = -tri
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Importing file ...                   OK
   import took approx. 1.57700 seconds

assimp dump: Wrote output dump E:\Downloads\Example (4)\Example.assxml
Press any key to continue . . .

**Comment by JrIndie** [comment]
Thanks with the help of griffin2000, this issue was actually due to using the precompiled libraries.  Using master, and building it yourself produces no issues!
