### ISSUE TITLE
[FBX] Can't get ScaleUnitFactor from mMetaData.

### ISSUE THREAD

**Issue by VelvetPigeon** [assimp/assimp#1998]
Hey,
I'm trying to extract UnitScaleFactor from "mMetaData" so when I check "mNumProperties" is returning 1. Going further when I print the "mKeys" index 0 it shows "UnitScaleFactor" but when I try to get the value of "UnitScaleFactor" using "Get" on "mMetaData" its always returning false and the value is 0.

https://github.com/assimp/assimp/issues/775
![image](https://user-images.githubusercontent.com/39524869/40967462-52eab98a-68b3-11e8-863b-9334e016d08f.png)

**Comment by kimkulling** [comment]
Which kind of file do you use?

**Comment by LeithKetchell** [comment]
I have a similar issue: my fbx file was obtained from mixamo.com - it reports 0 properties in the metadata, so I'm completely out of luck (unless Blender is able to write that information for me - and if I have to re-export my models from blender, I might as well be dealing with bad unit scaling at the same time, which kind of defeats the purpose of dealing with the issue in assimp)
