### ISSUE TITLE
assimp_cmd defaults to glTF 1

### ISSUE THREAD

**Issue by wlinna** [assimp/assimp#2001]
```
.\assimp.exe export .\aso.obj aso.glb
param = aso.glb
assimp export: select file format: 'glb' (GL Transmission Format (binary))
```
I can use -fglb2 to use select glb2-format, but wouldn't it be better to default to v2?

I found that the default can be changed by changing  [this](https://github.com/assimp/assimp/blob/cce5647338a403be6e10b65f2150ee73cb97347f/code/Exporter.cpp#L153) to this:

```
    Exporter::ExportFormatEntry("gltf2", "GL Transmission Format v. 2", "gltf", &ExportSceneGLTF2,
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_SortByPType),
    Exporter::ExportFormatEntry("glb2", "GL Transmission Format v. 2 (binary)", "glb", &ExportSceneGLB2,
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_SortByPType),
    Exporter::ExportFormatEntry( "gltf", "GL Transmission Format", "gltf", &ExportSceneGLTF,
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_SortByPType ),
    Exporter::ExportFormatEntry( "glb", "GL Transmission Format (binary)", "glb", &ExportSceneGLB,
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_SortByPType ),
```

Notice the changed order

**Comment by samyuchao** [comment]
hi wlinna,

Could it works with assimp_cmd?  I'm failed to export gltf as glb using assimp_cmd. [https://github.com/assimp/assimp/issues/2004](https://github.com/assimp/assimp/issues/2004)

**Comment by wlinna** [comment]
Hi,
I haven't tried to open generated glb files yet. I can try on next Monday.

How do you try to view them?

**Comment by wlinna** [comment]
At least on the model I use, the binary gltf 2 -file looks okay to me.

I used this:
https://gltf-viewer.donmccurdy.com/

**Comment by kimkulling** [comment]
Good idea, a pull request is on its way.
