### ISSUE TITLE
JoinIdenticalVertices flag not working in the 4.1.0

### ISSUE THREAD

**Issue by ihmc3jn09hk** [assimp/assimp#2006]
Previous version works while this version just not working correctly. Using the same obj file, the vertices are not joining in the 4.1.0 version while they joint perfectly in the previous one. 
The issue of the previous version is that the vertices id/order is changed even in case of directly export after import without any flag specified. 
However, the issue is not fixed in 4.1.0 but even worse is the malfunction of JoinIdenticalVertices flag.
So sad...

**Comment by kimkulling** [comment]
I guess this change caused the broken behaviour: https://github.com/assimp/assimp/commit/1f9d6f1ec4b60ce94699ac4f644d472d45e8e71e#diff-5845c50678a1c076669de5109f757194

**Comment by Nimer-88** [comment]
@kimkulling could you please hare with me on how did that diff break the `JoinIdenticalVertices` behavior? The mentioned diff added only handling for `mAnimMesh` when joining vertices. In case of no `mAnimMesh` being present, nothing changed.

**Comment by kimkulling** [comment]
Um, so maybe the first guess was wrong. I need to investigate this.

**Comment by DimaS86** [comment]
Hello! Thank you for this project!
I know it is kind of weird that I comment now, but I found out a strange thing. 
I have a simple cube, which has 36 vertices and 8 unique vertices.
I am expecting to receive 8 vertices after applying JoinIdenticalVertices flag, but I receive 24 instead.
However, if I apply DropNormals flag, which is not available in the latest version, (why have you removed it?), 
I somehow get the expected 8 vertices.
Hope it helps to resolve this unpleasant issue.

**Comment by DimaS86** [comment]
And one more thing. It only works for the version built on my PC locally (I downloaded it a while ago). If I install the nuget package, it doesn't work. I could share the source code that I have locally if you wish.

**Comment by LordEymerich** [comment]
@DimaS86 Thanks a lot!!! Using the aiProcess_DropNormals flag solved the issue for me! Using only the aiProcess_JoinIdenticalVertices flag removed some identical vertices (same position in 3D space) but not all of them even if my STL has no other attributes.
