### ISSUE TITLE
AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR stack corrupted

### ISSUE THREAD

**Issue by infobeisel** [assimp/assimp#2021]
calling the method aiMaterial.Get(AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR, pOut); leads to "runtime check failure: Stack around the variable 'pOut' was corrupted."

Calling the method with parameters
AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLIC_FACTOR or AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_ROUGHNESS_FACTOR works fine and returns correct results.

**Comment by corporateshark** [comment]
`baseColorFactor` is `vec4` while other 2 factors are just floats. Are you sure the size of your `pOut` is enough to store the data?

**Comment by infobeisel** [comment]
my bad, you are right. thank you!
