### ISSUE TITLE
[FBX] Embedded Textures ASCII/BINARY

### ISSUE THREAD

**Issue by VelvetPigeon** [assimp/assimp#2033]
Could some one tell me how can I load Embedded Textures from .fbx ascii format?
I'm using this method to get the textures on .fbx binary format "sceneHandle->GetEmbeddedTexture(filename)" and it is working flawlessly but when I do it on .fbx ascii format this method will return nullptr. 

#1957

**Comment by Aidmx** [comment]
Is fbx ASCII can save embedded textures?

**Comment by mlavik1** [comment]
@Aidmx Yes. ASCII FBX has support for embedded textures, but Assimp doesn't read the content yet. I'm working on it now.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2407
