### ISSUE TITLE
FBX import: unexpected type code: c

### ISSUE THREAD

**Issue by ZimmerA** [assimp/assimp#2034]
I tried to load a fbx file and got the following error:

> ERROR::ASSIMP::FBX-Tokenize (offset 0x3e3) cannot ReadData, unexpected type code: c

From what i understood by looking at the binary tokenizer (https://github.com/assimp/assimp/blob/master/code/FBXBinaryTokenizer.cpp) it checks for uppercase 'C' on line 236. I dont know why this file seems to contain a lowercase 'c'.

**Comment by aavenel** [comment]
Hi ZimmerA,

This seems strange, could you provide the FBX file ?
Thanks!
