### ISSUE TITLE
Material is not being loaded when using ReadFileFromMemory

### ISSUE THREAD

**Issue by diegoalejandrogomez** [assimp/assimp#2038]
If you use ReadFileFromMemory with an obj file, it is loading just the default material

Example:
//rawBuffer contains all the information in a obj file
aiScene* scene = importer.ReadFileFromMemory(rawBuffer, rawSize, aiProcess_CalcTangentSpace |
                                                                           aiProcess_Triangulate |
                                                                           aiProcess_JoinIdenticalVertices |
                                                                           aiProcess_SortByPType, NULL);

then my scene->mNumMaterials is 1, and it is just the default material created in the obj parser

The problem seems to be related with how ReadFileFromMemory works. As far as I know, that method is using a temporary file, but is not considering mtl file at all
Am I missing something?

**Comment by redmarmaduke** [comment]
Please refer to the documentation for ReadFileFromMemory @ http://assimp.sourceforge.net/lib_html/class_assimp_1_1_importer.html#a9b3c5e8b1042702f449e84a95b3324f6.

It states interface does not completely support certain formats (including obj), that put data in other files.  The documentation suggests something that may resolve your issue.

**Comment by kimkulling** [comment]
This behaviour is correct. Material files in obj are stored in different files and readFromMemory cannot handle this. Maybe we need to think about a different way.
