### ISSUE TITLE
FBX import - texture UV transform

### ISSUE THREAD

**Issue by warkid** [assimp/assimp#2043]
Importing code for FBX file format assumes that UV transform is stored within texture's ModelUVTranslation/ModelUVScaling. 

But FBX exported 3DS MAX 2017, for example, has texmap Offset/Tiling stored in Properties70's Scaling and Translation. See [texmapuvtiling_ascii.FBX.zip](https://github.com/assimp/assimp/files/2148947/texmapuvtiling_ascii.FBX.zip)

Is there a reason why FBX converter chooses to use those parameters instead of Props'?

**Comment by kimkulling** [comment]
I guess the main reason was that the author didn't had any files exported from Maya.

**Comment by mlavik1** [comment]
What is the difference between "ModelUVScaling" and "Scaling"? (and "ModelUVTranslation" vs "Translation")?

**Comment by mlavik1** [comment]
I have done some testing, and as far as I can see "ModelUVScaling" and "ModelUVTranslation" have no effect on 3DS Max. When exporting from 3DS Max these are always set to the default values (scale: 1,1; offset: 0,0). 
So all models I export from 3DS Max get the wrong UV scale when using Assimp. However, when using FBX SDK I can fetch the correct UV scale using FbxTexture::GetUVScaling(). The value returned is the one stored in "ModelUVScaling".

**My guess**: 3DS Max uses "ModelUVScaling" and "ModelUVTranslation", while some other software use "Scaling" and "Translation".

**Suggested solution**: Use "ModelUVScaling" and "ModelUVTranslation" if available - if not, use "Scaling" and "Translation".
Alternatively we can leave it as it is and expose all 4 properties (as _AI_MATKEY_...) and let the user decide what do do in these cases.

**Comment by kimkulling** [comment]
Good point, I merged the pull request. Thanks a lot for figuring this out.
