### ISSUE TITLE
Null/locator bones are not loaded

### ISSUE THREAD

**Issue by Warlander** [assimp/assimp#2054]
Like in topic. It seems that bones not influencing any vertices are ignored by Assimp and not imported.
Such bones are often used as positioning hints (for example, where human should be placed on a horse after mounting it), but there is no way to read info about them in Assimp.

My suggestion is to add pointer to bones array to scene directly, from where you can read all bones including the ones not influencing any mesh.

**Comment by haikarainen** [comment]
I think maybe this issue is relevant for me as well.

Iterating a meshes' `mBones` array will not find all the bones for a certain model I have. These bones do not influence vertices directly although they do influence their child-bones, which in turn influence vertices. And as @Warlander says, it would be _very_ useful to be able to use locator bones as well. 

I opened the same model in open3mod, which uses a 4 year old release of assimp.net, and that program seem to find them just fine. Not sure how that program goes about iterating the bones (I would guess that it iterates all the nodes and somehow finds out that a node is part of a skeleton or something)

Other models work just fine in my application.

**Comment by JrIndie** [comment]
This is very important.  We were going to use bone's for special effects and other hit detection methods in our game.

**Comment by haikarainen** [comment]
@JrIndie @Warlander what formats do you get this issue with? Ive personally only tried FBX. 

Also, I dont know how actively assimp ia being developed, given the sheer amount of open issues. I think we should consider looking into and fixing this ourselves!

**Comment by haikarainen** [comment]
So I've done some additional testing, it seems like Assimp successfully identifies the scene nodes for the bones, but probably just skips the bone data for them internally for some reason.

Will take a dive in the code and see if it maybe is an easy fix

**Comment by haikarainen** [comment]
Found the culprit in my case at least: 

https://github.com/assimp/assimp/blob/master/code/JoinVerticesProcess.cpp#L418

Current workaround for me is to simply disable `aiProcess_JoinIdenticalVertices` when importing, will check how well it imports without it (and if animations in this specific FBX remains healthy). Will report back.

**Comment by haikarainen** [comment]
Leaving this issue for the day, someone else feel free to dig in, and report if this resolves any issues for you! The bones are imported now, however there are issues for me with animations and whatnot.

**Comment by Warlander** [comment]
Personally I'm importing Collada models, but I think this fix should work for all cases. Thank you for the solution, I'm hoping it will be available in the next release. :)

**Comment by haikarainen** [comment]
@Warlander Just feel a need to mention; This isn't really a solution. This simply lets the bones be imported, although since the animations are messed up, and I haven't tested it further, I cant guarantee it really works. 

Personally I'm looking on OpenFBX but it would suck to rewrite everything to fit another library.. How is Collada working with skeletal animations and the likes? Do you have any experience exporting from blender and then importing into assimp?

Cheers

**Comment by Warlander** [comment]
Unfortunately no experience with exporting from Blender, we are using the Maya for modeling. Assimp seem to open Collada files created by it mostly fine, just cannot import nulls (which is why I created this issue).

**Comment by haikarainen** [comment]
@Warlander Just wanted to say that I personally went ahead and wrote my own FBX-importer from scratch instead.  It's a pretty simple format (even if information is scarce), and you get all the data you need very easily, even if you have to write your own stuff to make sense of the imported data. Just a tip!

**Comment by kimkulling** [comment]
Seems to be a general issue in assimp. Thanks a lot for figuring these codes out.

**Comment by reduz** [comment]
Trying to import Skeletons where this happens in Godot, they look pretty bad. I can kind of guesswork something, but still looks bad. Can't use these bones to attach things from code either.

I also see no workaround for this, as this seems like a design flaw in the library. Hope it can be fixed eventually, but seeing almost a year passed I don't hold my hopes up.

**Comment by kimkulling** [comment]
Sorry for all the delays, could you provide an example file from Godot? Thanks!

**Comment by reduz** [comment]
@kimkulling don't worry. Actually I'm wrong, I suppose nothing avoids from adding a bone with no weights to the mesh, maybe this could be a flag when setting up Assimp? ("keep empty bones").

The file on this issue exhibits the problem: #2424 
Bone number 5 is missing, so the skeleton can't be displayed properly (it's also wrongly rotated).
![image](https://user-images.githubusercontent.com/6265307/56078404-0c1e6a00-5dbe-11e9-9403-d8dd3bf4cfb3.png)

**Comment by kimkulling** [comment]
Hm, have you checked the latest master? I just imported the FBX with the latest master. I saw all bones including bone 5. And I have compared the anmimation in the assimp-viewer with the blender animation and both seems to be the same.

**Comment by kimkulling** [comment]
Which version is currently in use when I run the latest master from godot?

**Comment by jamesBrosnahan** [comment]
@kimkulling Where do I find documentation on writing unit tests for the importer/exporter?

**Comment by kkulling** [comment]
There is no documentation at the moment. Fo write a unittest you hae to follow these steps:

- Add a class to the folder https://github.com/assimp/assimp/tree/master/test/unit/ImportExport
- Derive the testclass from AbstractImportExportBase 
- You need to override the importerTest-method. When the import is fine just return true like:

```
class utCOBImportExport : public AbstractImportExportBase {
public:
    virtual bool importerTest() {
        Assimp::Importer importer;
        const aiScene *scene = importer.ReadFile(ASSIMP_TEST_MODELS_DIR "/COB/molecule.cob", aiProcess_ValidateDataStructure);
        return nullptr != scene;
    }
};

TEST_F(utCOBImportExport, importAMFFromFileTest) {
    EXPECT_TRUE(importerTest());
}
```

**Comment by JulianKnodt** [comment]
@kimkulling sorry to revive an old dead thread, but it appears this issue is still present in the current version. There also doesn't seem to be a linked PR that would resolve this, is it still open to being worked on/do you know if the current state has changed since this thread?

**Comment by fire** [comment]
As I was subscribed to this thread, https://github.com/godotengine/FBX2glTF and https://github.com/ufbx/ufbx are the current recommendations from me.

**Comment by Yuuon** [comment]
I might have the same issue here, the example FBX is from a free asset in Unity asset store called "Free voxel girl", in Unity it says it has 15 bones, and the assimp importer can only pick 11 bones when import, while the missing 4 is left/right hand and foot -- which I guess they are actually not in use becuase the simple lowpoly voxel model. Import flag is "PostProcessPreset.TargetRealTimeMaximumQuality | PostProcessSteps.Triangulate".

**Comment by perkele1989** [comment]
Doing this same thing many years later, and this basic feature is STILL broken in assimp. I'm going to rewrite my importer with ufbx instead, maybe I'll ahve more luck there

**Comment by deggua** [comment]
Having this issue currently as well. I can upload the mesh file if the devs want to look at it. It's a .DAE, not a .FBX
