### ISSUE TITLE
Windows build does not support C4D files by default?

### ISSUE THREAD

**Issue by chanibal** [assimp/assimp#2055]
Hi, I downloaded the 4.1.0 windows build of assimp from github's releases to use it on a Cinema4D.
Unfortunately, when trying to use it, I get:
```
$ ./assimp.exe info file.c4d
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: No suitable reader found for the file format of file "file.c4d".
assimp info: Unable to load input file file.c4d
```

When trying to check what formats are supported, C4D isn't there:
```
$ ./assimp listext
*.3DS;*.3d;*.3ds;*.3mf;*.PRJ;*.ac;*.ac3d;*.acc;*.amf;*.ase;*.ask;*.assbin;
*.b3d;*.blend;*.bvh;*.cob;*.csm;*.dae;*.dxf;*.enff;*.fbx;*.glb;*.gltf;*.hmp;
*.ifc;*.ifczip;*.irr;*.irrmesh;*.lwo;*.lws;*.lxo;*.md2;*.md3;*.md5anim;
*.md5camera;*.md5mesh;*.mdc;*.mdl;*.mesh;*.mesh.xml;*.mot;
*.ms3d;*.ndo;*.nff;*.obj;*.off;*.ogex;*.pk3;*.ply;*.pmx;*.prj;*.q3o;
*.q3s;*.raw;*.scn;*.sib;*.smd;*.stl;*.stp;*.ter;*.uc;*.vta;*.x;*.x3d;
*.x3db;*.xgl;*.xml;*.zgl
```

Is the windows build somehow lacking C4D support?

**Comment by kimkulling** [comment]
You need to enable the support explicitly by your own. Background is that the SDK for C4D-files is not free as far as I know. 

How to enable this feature check our wiki at: https://github.com/assimp/assimp/wiki/Cinema4D-&-Melange
