### ISSUE TITLE
BVH to Collada conversion improvements

### ISSUE THREAD

**Issue by ppiecuch** [assimp/assimp#2065]
Hello All :)
I am working on some cleanup on BVH to Collada conversion and one of feature I would like to have and prepare is the skeleton preview, like on the picture below. I know that I can do this by adding last node like this:

      <node id="defaultobject"  name="defaultobject" type="NODE">
        <matrix sid="matrix">1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1</matrix>
        <instance_geometry url="#meshId0">
          <bind_material>
            <technique_common>
              <instance_material symbol="defaultMaterial" target="#SkeletonMaterial">
              </instance_material>
            </technique_common>
          </bind_material>
        </instance_geometry>
      </node>
 
But I am not sure how to properly implement this in the exporter - maybe by adding some aiNode in the hierarchy? Anyone could help me with this and maybe share some code :)

Regards and Thanks in advance
Pawel

![screen shot 2018-07-22 at 13 13 06](https://user-images.githubusercontent.com/1011685/43045025-05a926f2-8db1-11e8-8f7f-4a64bf91265d.jpg)

**Comment by kimkulling** [comment]
I would recommend to implement this as a new node.
