### ISSUE TITLE
Building with MinGW w64: too many sections

### ISSUE THREAD

**Issue by JekaS178RUS** [assimp/assimp#2067]
When building with MinGW when compilling Importer/IFC/IFCReaderGen1_2x3.cpp I get error:

> too many sections (61358)
> D:\Programming\tools\msys2\tmp\cccuSdER.s: Assembler messages:
> D:\Programming\tools\msys2\tmp\cccuSdER.s: Fatal error: can't write 171 bytes to section .text of CMakeFiles/assimp.dir/Importer/   IFC/IFCReaderGen1_2x3.cpp.obj because: 'File too big'

To fix this I add -DCMAKE_CXX_FLAGS=-Wa,-mbig-obj to cmake call.

Maybe it's a good idea to add this to CMakeLists.txt as a conditional option for MinGW compiler, or reduce size of IFCReaderGen* files if posible.

**Comment by kimkulling** [comment]
Do you build this with QtCreator?

**Comment by JekaS178RUS** [comment]
I will try, but in Qt there is only 32 bit version of MinGW.

ср, 25 июл. 2018 г., 21:39 Kim Kulling <notifications@github.com>:

**Comment by kimkulling** [comment]
QtCreator tries to build it by using ninja. And building with ninja will cause that the flag -bigobj is not set. I will prepare a patch for that.

**Comment by JekaS178RUS** [comment]
Good to hear it. When I found this problem I used MSYS2 with MinGW w64 (please note this is not same as in Qt).

**Comment by JekaS178RUS** [comment]
Hello! 
I tried again with Qt Creator and w64 version of MinGW with different generators: "CodeBlocks - Ninja" (QtCreator prefered) "CodeBlocks - MinGW Makefiles" and classic "MinGW Makefiles" and situation is the same for all generators, so Ninja is not the origin of the problem. In all cases I have to edit CMAKE configuration adding bigobj flag.

**Comment by haolly** [comment]
same here with MingW

**Comment by UltimatePajerix** [comment]
You can by adding the compilation flags "-flto -Wl,-allow-multiple-definition" and you can add "-fuse-linker-plugin". "-Wa,-mbig-obj" do not work on x86/32bits architecture (only x64)

**Comment by leimiles** [comment]
Hi, got this error with mingw32, any advice plz?
`
[ 43%] Building CXX object code/CMakeFiles/assimp.dir/Importer/IFC/IFCLoader.cpp.obj
[ 44%] Building CXX object code/CMakeFiles/assimp.dir/Importer/IFC/IFCReaderGen1_2x3.cpp.obj
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: too many sections (82618)
C:\Users\LEIMIL~1\AppData\Local\Temp\cccVb0Wu.s: Assembler messages:
C:\Users\LEIMIL~1\AppData\Local\Temp\cccVb0Wu.s: Fatal error: can't write 170 bytes to section .text of CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: 'File too big'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: too many sections (82618)
C:\Users\LEIMIL~1\AppData\Local\Temp\cccVb0Wu.s: Fatal error: can't close CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: File too big
make[2]: *** [code\CMakeFiles\assimp.dir\build.make:1831: code/CMakeFiles/assimp.dir/Importer/IFC/IFCReaderGen1_2x3.cpp.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:309: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:135: all] Error 2

`
