### ISSUE TITLE
ColladaLoader: Material props that have textures return random color

### ISSUE THREAD

**Issue by septag** [assimp/assimp#207]
Using the latest assimp build, with collada files exported from 3dsmax 2012 with the latest OpenCollada build.
when I set a texture to a specific channel (for example specular), the "specular" tag replaces "color" with "texture" (which I think it sucks, should include both texture and color, but anyway it's in collada spec).
But when only texture is available under material property, collada returns valid Color for that prop, and the color is some random thing, which I can't figure out where it reads it from.

for example If I set diffuse texture, _AI_MATKEY_COLOR_DIFFUSE_ returns color (0.6, 0.6, 0.6). The value doesn't exist in collada file and the diffuse color inside 3dsmax is not that either.

**Comment by gwasterisk** [comment]
@septag I'm having the same problem with assimp 3.1.1. Please update us about your findings.

**Comment by kimkulling** [comment]
I guess this one was already fixed.
