### ISSUE TITLE
Disable debug postfix on non-windows platforms

### ISSUE THREAD

**Issue by stevesamknows** [assimp/assimp#2075]
CMAKE_DEBUG_POSTFIX is problematic on some non-windows platforms; android
in particular much prefers that debug and release libs have the exact same filename
to avoid major boilerplate around lib loading (in java/kotlin) and using prebuilts etc. (in
cmake scripts).

IIUC the debug postfix is mostly applicable on windows platforms, so
would be preferable to add MSVC in IF block in top CMakeLists.txt e.g.
```
IF (MSVC AND (CMAKE_BUILD_TYPE STREQUAL "Debug"))
   SET(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Debug Postfix for lib, samples and tools")
...
```
Or, if it is strongly preferred to avoid changing existing behavior, instead something like
```
OPTION( INJECT_DEBUG_POSTFIX
  "Inject debug postfix in .a/.so lib names"
  ON
)
IF (INJECT_DEBUG_POSTFIX AND (CMAKE_BUILD_TYPE STREQUAL "Debug"))
   SET(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Debug Postfix for lib, samples and tools")
```
which user could then override idiomatically in their top level cmake script

**Comment by kimkulling** [comment]
Good idea, I will try to prepare a pull request.

**Comment by RichardTea** [comment]
When a specific platform requires particular settings by convention or technical requirement, please change those settings for that particular platform and not for all platforms.

This broke the debug prefix completely, and then the first attempted fix for it broke it further.
