### ISSUE TITLE
how i build so for android in mac os?

### ISSUE THREAD

**Issue by Nullifier1571** [assimp/assimp#2084]
i clone project from git ,then use this commend
$ mkdir build && cd build
$ cmake  ..
$ make -j8
then i got libassimp.dylib this file,but i want use .so for android
i had set cmake classPath in bashfile
i see https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-%28Quick-overview%29 this link & https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake this link

**Comment by kimkulling** [comment]
I have not try to compile assimp for moc os because I do not have any mac around. But I guess you just need to use the android toolchain. when running the cmake gui as described in the wiki entry.

**Comment by lb377463323** [comment]
I have the same issue, have you solved it?
