### ISSUE TITLE
PLY mesh import

### ISSUE THREAD

**Issue by JekaS178RUS** [assimp/assimp#2087]
I have simple model with only one mesh, then I save it as ply and obj with Blender.
When I import it from ply file I have mRootNode with 1 mesh and no childrens
When I import it from obj file I have mRootNode with no meshes and 1 children with 1 mesh.

I rember same issue with STL importer. Can you clearify if both cases valid or mRootNode **must** have childrens and no meshes?

**Comment by kimkulling** [comment]
I guess this is caused by different implementation how to generate the underlying node hierarchy. Could you please provide a small reproducable model? Thanks in advance.

**Comment by JekaS178RUS** [comment]
Here you are
[cube.zip](https://github.com/assimp/assimp/files/2273577/cube.zip)

**Comment by kimkulling** [comment]
Thanks a lot!

**Comment by kimkulling** [comment]
As I said before this is caused by the different implementations of the loaders. I guess we need a global policy for that. 
It is ok to have meshes in your root node.
