### ISSUE TITLE
.Obj File issues - Triangulate and other flags.

### ISSUE THREAD

**Issue by gallickgunner** [assimp/assimp#2093]
So I'm loading a cube from `.obj` File. And I have mentioned these flags.

 ```
 aiProcess_Triangulate |
  aiProcess_SortByPType |      // to remove lines and points
  //aiProcess_PreTransformVertices |
  aiProcess_OptimizeGraph;
```

I will explain the commented flag later. I'm expecting Assimp to give me `36` vertices. However it gives me `24`. If i specify the "Join Identical Vertices" flag, the number doesn't change. I tried printing the number of faces and surprisingly it says the total number of Faces are `12`. Without the triangulate flag, the number of faces are 6.

So this means, that Triangulate is working somewhat, and it has increased the number of faces, but the number of vertices remain unchanged. It's almost as if `aiProcess_JoinIdenticalVertices` is being set by default. I am checking the number of vertices from the `aiScene`'s mesh array and the `mRootNode`'s mesh array. Result is same.

Secondly, about the commented flag, It seems that `aiProcess_PreTransformVertices` is incompatible with `aiProcess_OptimizeGraph`. Defining both returns false from `ValidateFlags`. Is this the expected behaviour? 

Thirdly, If neither of those above flags are present, the RootNode is empty and I can only access data through `aiScene`'s mesh array. Again is this the expected behaviour?

Any help would be appreciated.
-Thanks.

**Comment by JekaS178RUS** [comment]
Please provide your obj file.
12 faces for triangulated cude is absolutely fine: 2 triangles * 6 faces. 12 faces * 3 vertex is 36 as you expect. But if your cude has no normals it could be 8. With colors ot texcoords it could be any other, so without obj file it is imposible to say how many verticies should have your model.

**Comment by gallickgunner** [comment]
I have tried both with and without UVs. The files are attached below. A preview of one is given

```
# Blender v2.74 (sub 0) OBJ File: ''
# www.blender.org
mtllib untitled-scene.mtl
o Box
v 0.500000 0.500000 0.500000
v 0.500000 0.500000 -0.500000
v 0.500000 -0.500000 0.500000
v 0.500000 -0.500000 -0.500000
v -0.500000 0.500000 -0.500000
v -0.500000 0.500000 0.500000
v -0.500000 -0.500000 -0.500000
v -0.500000 -0.500000 0.500000
vn 1.000000 0.000000 0.000000
vn -1.000000 0.000000 0.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 -1.000000 0.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 -1.000000
usemtl b0b0b0
s 1
f 1//1 3//1 4//1 2//1
f 5//2 7//2 8//2 6//2
f 5//3 6//3 1//3 2//3
f 8//4 7//4 4//4 3//4
f 6//5 8//5 3//5 1//5
f 2//6 4//6 7//6 5//6
```
[objfiles.zip](https://github.com/assimp/assimp/files/2281330/objfiles.zip)

**Comment by gallickgunner** [comment]
Ok so I just checked, and `aiProcess_PreTransformVertices` is incompatible with `aiProcess_OptimizeGraph`. It's coded in `importer.hpp`.  This clears out the 2nd problem.

Problem 1 and 3 still remaining.

**Comment by gallickgunner** [comment]
Any updates on the triangulate flag bug?

**Comment by gallickgunner** [comment]
@twhittock - True but this functionality is provided by #aiProcess_JoinIdenticalVertices flag. This should not be there by default or there is no meaning for the flag to exist. Normally Assimp should load 36 vertices but for people who are working with indexed geometry they can use the flag to get unique vertices only.

**Comment by twhittock** [comment]
By my understanding, by asking for triangulation, you're asking the library to change the mesh faces, not to change the vertices. Expanding the vertices so they were unique per face would be some sort of explode, detach or unshare operation on the vertices, normally.

join identical would compare vertices in the existing vertex list and merge items into the same index if they were previously detached in the modelling tool, but not actually moved away from each other. It would be an optimisation in the case of a messy input.

**Comment by gallickgunner** [comment]
From what i gathered over the net, Assimp used to load unique vertices. Check this as an example. The OP states that assimp loadead 36 vertices when provided 8. So there is a bug probably in the current build.

https://sourceforge.net/p/assimp/discussion/817654/thread/1fa44ba8/
