### ISSUE TITLE
std::to_string do not exist on android NDK with Clang 5.0 (ASSIMP 3.3.1) (NDK15)

### ISSUE THREAD

**Issue by simonprovost** [assimp/assimp#2097]
Hello,

### **Informations Part**

Parameters cross compilation with toolchain android:

- CLANG: 5.0
- NDK: 15c
- STL: C++_static
- ABI: armeabi-v7a with NEON

ASSIMP : 

- Version 3.3.1

I can say that i have (c++11 on std) (line came from CMakeLists.txt ASSIMP : 
`  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -Wall -Wno-long-long -pedantic -std=c++11" )
`
__________________________________________________________________________

### **Error Part:**
Output Clang compilation:

_File ColladaParser.cpp:302:45:_
` error: no member named 'to_string' in namespace 'std'; did you mean simply ' animName = std::string("animation_") + std::to_string(mAnimationClipLibrary.size());`

I do not understand why ? i tested with many things like  (1 exemples):

- Add namespace _std_ to "to_string" function was re create by Assimp on StringUtils.

Warning i added "cstdlib" header to StringUtils.h to handle the problem with "::atof" was "no member named 'atof' in the global namespace".

### **EDIT 17 AUGUST 3PM:**

I was curious to know if Assimp 3.3.1 with ndk 17 compiled or not ? Because we can see in [Android support library c++](https://developer.android.com/ndk/guides/cpp-support#cs) that before ndk 16 libc++ was only in Beta quality. 

So the conclusion for this test was perfect:

The percent when crashed with ndk15 was passed, so, the problem with to_string outed. (ndk 17).

**TEST PASSED - 17 AUGUST**
NDK 17 + CLANG 5 + C++_static + Assimp 3.3.1 works without problem like libc++ or anything.

______________________________________________________________________________

Someone help ? idea's ? Thank you. 

Thank you advance for help and Best regards.

**Comment by simonprovost** [comment]
### SOLVED : 

When i saw that in NDK 17 it works, i made a diff between both ndk toolchain:

- I saw weird thing in this condition that we can say is different between both ndk.

`if(NOT ANDROID_STL)
	set(ANDROID_STL gnustl_static) // ndk15
	#set(ANDROID_STL c++_static) // ndk17
endif()`

So, in first i try if i comment the first line and un-comment the second if it works, and it is. So, i was write (set ANDROID_STL c++_static) in my main CMakeLists.txt and it works right now.

Thank you.

**Comment by kimkulling** [comment]
Ok, thanks for the update.
