### ISSUE TITLE
Invalid default material

### ISSUE THREAD

**Issue by JekaS178RUS** [assimp/assimp#2101]
Hello!

I have PLY file with no vertex colors or any materials. But when imported it have material with empty name, and aiCreateAndRegisterDefaultMaterial() return pointer to a different material. Is it a bug or I did smth wrong?

Here is a code to reproduce problem with latest master:

```
#include <assimp/Importer.hpp>
#include <assimp/scene.h>

#include <iostream>

int main ()
{
	Assimp::Importer importer;
	aiMaterial* default_material = aiCreateAndRegisterDefaultMaterial();
	const aiScene* scene = importer.ReadFile("D:\\cude_triangles.ply", 0 );

	aiMaterial* material = scene->mMaterials[0];

	std::cout << (material == default_material) << std::endl;
	aiString name;

	material->Get(AI_MATKEY_NAME, name);
	std::cout << name.C_Str() << std::endl;
}
```
When importing OBJ file with no materials material have name "DefaultMaterial" but aiCreateAndRegisterDefaultMaterial() return different pointer;

**Comment by JekaS178RUS** [comment]
In source code I can see that method aiCreateAndRegisterDefaultMaterial used only in STL importer, damn, I thought it used any case when scene have no material specified.

**Comment by kimkulling** [comment]
I forgot to adapt the rest, sorry for that. I can prepare this for obj next.

**Comment by JekaS178RUS** [comment]
@kimkulling I will be grateful, obj, ply and stl is everything what I need for today, thanks.

**Comment by JekaS178RUS** [comment]
Also I found that STLImporter overwrite any parameters setted for default material. I think importers should not overwrite default material parameters. I mean if model has no material at all it should use default material as is. If model has any material than importer should not use default material.
