### ISSUE TITLE
bad texture coordinates from gltf 2.0

### ISSUE THREAD

**Issue by siddharthcmdz** [assimp/assimp#2102]
hi,
I'm a first time user of asset import. Thank you for such a great library. 
I'm trying to import gltf models into my viewer. The positions are fine, but when i use the texture coordinates given by the importer, the textures are not correctly mapped.

Here's how i retrieved texture coordinates:
```
    //store texture coordinates if available.
    if (meshData->HasTextureCoords(0))
    {
      std::vector<glm::vec2> texcoordlist;
      texcoordlist.reserve(meshData->mNumVertices);
      int t = 0;
      for (t = 0; t < meshData->mNumVertices; ++t) //meshData is aiMesh*
      {
        float u = meshData->mTextureCoords[0][t].x;
        float v = meshData->mTextureCoords[0][t].y;
        texcoordlist.push_back(glm::vec2(u, v));
      }
      //pass texcoordlist to the renderer.
    }

```
Here is the dataset i'm using:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet/glTF
filename: DamagedHelmet.gltf

This is the image of the model when i open it in windows 10 3D builder:
![image](https://user-images.githubusercontent.com/14873104/44440353-b75f8200-a595-11e8-9cb2-2620964980b9.png)

And here is the image i get in my viewer:
![image](https://user-images.githubusercontent.com/14873104/44440411-f2fa4c00-a595-11e8-950d-3ac6395ad4ba.png)

Any advise?

thank you

**Comment by kimkulling** [comment]
So all the y-axis have to be inverted?

.
>

**Comment by siddharthcmdz** [comment]
Sorry i forgot to mention about the y-axis texture coordinate: i did try doing that, but it did not fix the issue.
what i did:
```
      std::vector<glm::vec2> texcoordlist;
      texcoordlist.reserve(meshData->mNumVertices);
      int t = 0;
      for (t = 0; t < meshData->mNumVertices; ++t)
      {
        float u = meshData->mTextureCoords[0][t].x;
        float v = meshData->mTextureCoords[0][t].y;
        texcoordlist.push_back(glm::vec2(u, 1-v));
      }

```
result:
![image](https://user-images.githubusercontent.com/14873104/44483186-6e044680-a618-11e8-86d8-d9be3c34491c.png)

**Comment by schubboy** [comment]
Just kind of guessing from the looks of the screenshot, but it almost seems to be missing the UV mapping channel from the import.  I'm not an expert in this library so I can't say why, but just visually taking a guess...

**Comment by schubboy** [comment]
@kimkulling i've had issues where opengl/glsl vs directx had differences in how they expected to reference the y channel lookup on the texture, EG: 1 was the "top" of the texture vs 0 being the "top".  Inverting the UV.y lookup is one way to deal with that.  That was just a guess / suggestion to check on.

**Comment by siddharthcmdz** [comment]
is there a way for me to confirm the actual UVs coming from gltf file and comparing it with what asset import's provided UVs?

**Comment by corporateshark** [comment]
Try `texcoordlist.push_back(glm::vec2(u, 1.0f-v));`

**Comment by siddharthcmdz** [comment]
trying out 1-v results in the last image posted.

**Comment by siddharthcmdz** [comment]
Well looking closely at the invalid image and the valid image, i did a -u instead of u and it works on gltf! but ofcourse this breaks other file formats. 
Could someone confirm that this is a bug in assetimport. I shouldnt need to do a -u, v for my texcoords.

**Comment by spn5** [comment]
Anyone? moderators?

**Comment by siddharthcmdz** [comment]
@corporateshark thanks for the reply. I'll check if im doing something with texcoords in my renderer. Will get back to you.

**Comment by ofTheo** [comment]
Hmm - I am running into a similar issue with the current 5.2.5 release and this same model. 

If I print out the texture coordinates directly from assimp with:

```
	if(aim->GetNumUVChannels()>0){
		for (int i=0; i < (int)aim->mNumVertices;i++){
			std::cout << " OG coord is "  << aim->mTextureCoords[0][i].x <<", " << aim->mTextureCoords[0][i].y << std::endl;

```

I get only negative numbers for y:

```
 OG coord is 0.482977, -0.667462
 OG coord is 0.481101, -0.665067
 OG coord is 0.480537, -0.666455
 OG coord is 0.477414, -0.664078
 OG coord is 0.477494, -0.66583
```

To make them usable I have to *= -1.0 

```
-1.0*aim->mTextureCoords[0][i].y
```

But this is just for this model and doing this breaks all the other models which work fine ( other gltf, fbx, and dae models ). 

My suspicion is that it is some how related to the weird texture offset that this model uses:

see the min and max on these lines:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf#L48-L60 

            "max" : [
                0.9999759793281555,
                1.998665988445282
            ],
            "min" : [
                0.002448640065267682,
                1.0005531199858524
            ],

using the old assimp C api loader ( which I assume isn't as up to date ) you can see the offsets in the texcoords which show y starting at 1.0 and going to 1.999 :

```
 OG coord is 0.482977, 1.66746
 OG coord is 0.481101, 1.66507
 OG coord is 0.480537, 1.66646
 OG coord is 0.477414, 1.66408
 OG coord is 0.477494, 1.66583
``` 

with the older C loader you can just subtract the min y coordinate value from the model file ( in this case 1.00005 ) 

```
            "min" : [
                0.002448640065267682,
                1.0005531199858524
            ],
```

from each tex coord and get the correct tex coord value

```
New OF coord is 0.477494, 0.66583
```

But the current assimp C++ api gives:

```
 OG coord is 0.477494, -0.66583
```

This looks like assimp is currently doing `1.0005531199858524 - mTextureCoords[0][i].y` on import when it should be doing `mTextureCoords[0][i].y - 1.0005531199858524`  <-- subtract the min y coordinate value from the gltf file. 

I hope this makes sense. 
We've been using assimp for over 10 years in [openFrameworks](https://github.com/openframeworks/openFrameworks) and have only seen this issue with this model.

**Comment by ofTheo** [comment]
Looking into the code it might actually be that [glTF2Asset.inl](https://github.com/assimp/assimp/blob/de83245f4211c09e52e0298a28a8e61ccd55b0fd/code/AssetLib/glTF2/glTF2Asset.inl#L841-L858) is not accounting for the min/max tex coordinate range at all. 
It might just be that the flipping which assimp does is producing the negative values. 

https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp#L562-L564

```
              for (unsigned int i = 0; i < aim->mNumVertices; ++i) {
                    values[i].y = 1 - values[i].y; // Flip Y coords
                }
```

Looking through this section here I see the "componentType", "type" and "count" getting read from the data structure, but not the min and max values ( which I imagine for many models can be ignored ). 

https://github.com/assimp/assimp/blob/de83245f4211c09e52e0298a28a8e61ccd55b0fd/code/AssetLib/glTF2/glTF2Asset.inl#L841-L858 

`glTF2Asset.inl` appears to be reading most of the tags but not the "max" and "min" ones which in this case use a `1.0005531199858524` to `1.998665988445282` range for y tex coords 

Section for TEXCOORD_0 
```
        {
            "bufferView" : 3,
            "componentType" : 5126,
            "count" : 14556,
            "max" : [
                0.9999759793281555,
                1.998665988445282
            ],
            "min" : [
                0.002448640065267682,
                1.0005531199858524
            ],
            "type" : "VEC2"
        }
```
 
cc @xiaohunqupo @Promit @RichardTea

**Comment by ofTheo** [comment]
Can we reopen this issue @corporateshark ?

**Comment by ofTheo** [comment]
Apologies for all the noise. 
Definitely not an assimp issue 🤦‍♂️

Incase someone else runs into this. 
The fix for me was to add `aiProcess_ConvertToLeftHanded` to the flags passed to: `importer.ReadFile`. 

For some reason most models were loading fine without it, but this one in particular was really weird without the flag. 

Thank you all for your work on this project!

**Comment by ashpil** [comment]
For others running into the same issue with this same model: this model requires a `repeat` sampler wrapping mode. `mirrored repeat` will cause it to look as above.
