### ISSUE TITLE
Need assistance | MD5 Models

### ISSUE THREAD

**Issue by Codeblockz** [assimp/assimp#2111]
I'm converting from assimp's verbose internal format to a model format similar to MD5... I can't seem to figure out how to retrieve the Weight::m_JointID parameter when rebuilding weights from assimps vertex weight data. Any tips/suggestions would be appreciated. 

https://stackoverflow.com/questions/52085307/retrieve-md5-weight-joint-ids-from-assimp-data-after-import

**Comment by kimkulling** [comment]
I Started to discuss.
