### ISSUE TITLE
Suggested rollback to FBXConverter camera changes

### ISSUE THREAD

**Issue by schuttejoe** [assimp/assimp#2115]
I just recently updated from 4.1.0 to latest and found that my cameras were being incorrectly exported from FBX files. I tracked the problem down to this commit: https://github.com/assimp/assimp/commit/0b15d5cd46caaa7fcb2d82e025a914f9e21cbeef

which is undoing the changes from a prior commit with a thorough comment explaining why it had done things this way: https://github.com/assimp/assimp/commit/5be2351dc6aa06502a561a5e2e8905d6c60e39ca

**Comment by inhosens** [comment]
Sigh, I found it was reverted today. But I think @schuttejoe used some tools like blender for exporting his FBX files and those tools are not correctly exporting the camera's properties. I already tested it with FBX sdk.
