### ISSUE TITLE
i think StreamWriter.h has bug.

### ISSUE THREAD

**Issue by copycd** [assimp/assimp#2118]
void PutString(const std::string& s)
    {
        // i added
        if(s.empty())
            return;

        // as Put(T f) below
        if (cursor + s.size() >= buffer.size()) {
            buffer.resize(cursor + s.size());
        }
        void* dest = &buffer[cursor];
        ::memcpy(dest, s.c_str(), s.size());
        cursor += s.size();
    }

**Comment by kimkulling** [comment]
Looks fine fo me, no override.

**Comment by copycd** [comment]
i had encountered error below code.
// original source code
void PutString(const std::string& s)
{
    // as Put(T f) below
    if (cursor + s.size() >= buffer.size()) {
        buffer.resize(cursor + s.size());
    }
    void* dest = &buffer[cursor];
    ::memcpy(dest, s.c_str(), s.size());
    cursor += s.size();
}

example.
if input string = ""
current buffer.size() is 124
current cursor value is 124

error is occurred .

void* dest = &buffer[cursor];
invalid point.




void* dest = &buffer[cursor];
