### ISSUE TITLE
assimp load more points for obj file

### ISSUE THREAD

**Issue by mttbx** [assimp/assimp#2120]
Hi,
    I loaded obj file with flag aiProcess_JoinIdenticalVertices, and it still add more points for my mesh.
    I checked the number of v points in my obj file, it has about less 200 points than what I loaded.
    Am I doing wrong? It's driving me crazy......

**Comment by mttbx** [comment]
I further noticed that there's more texture coordinates than vertex coordinates in my obj files. Is this cause the problem? I load the obj file into 3dmax, they know that the vertex is the same points, so I assume the obj file is correct. Then the issue is that how to load the obj files into assimp correctly. Can you help me?

**Comment by kimkulling** [comment]
Hi,
this is common behaviour of the obj-import, please check: https://sourceforge.net/p/assimp/discussion/817654/thread/026e9640/

Kim
