### ISSUE TITLE
vs2017  complie error: undefined preprocessing  command “cmakedefine”

### ISSUE THREAD

**Issue by w33haa** [assimp/assimp#2123]
I used Cmake-gui.exe to generate vs solution,and then complied it, it told the **cmakedefine** is undefined

**Comment by kimkulling** [comment]
Could you please specify which error was shown. For me the described way works. Thanks!

**Comment by JekaS178RUS** [comment]
I don't know what is cmakedefine but I used vs2017 to compile assimp several times and everything was ok. Which version of cmake you are using?

**Comment by kimkulling** [comment]
Just reopen if this issue still exists.
