### ISSUE TITLE
how to fix this issue while compiling for android

### ISSUE THREAD

**Issue by vicky707** [assimp/assimp#2125]
Error:
PS E:\assimp-master> cd buildandroid
PS E:\assimp-master\buildandroid> cmake -DCMAKE_TOOLCHAIN_FILE=$ANDTOOLCHAIN -DENABLE_BOOST_WORKAROUND=ON -DCMAKE_INSTAL
L_PREFIX=/assimp-2.0 -DANDROID_ABI=armeabi-v7a _DANDROID_NATIVE_API_LEVEL=android-8 -DANDROID_FORCE_ARM_BUILD=TRUE ..
-- Building for: Visual Studio 15 2017
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file: $ANDTOOLCHAIN
Call Stack (most recent call first):
  CMakeLists.txt:39 (PROJECT)

CMake Error at CMakeLists.txt:39 (PROJECT):
  Failed to run MSBuild command:

**Comment by monxarat** [comment]
@vicky707 
you must set $ANDTOOLCHAIN in your environment

$ANDTOOLCHAIN is the path to your toolchain.

You cant general toolchain by way run below command line
`sh make-standalone-toolchain.sh –platform=android-18 –ndk-dir=$NDK_PATH –install-dir=<The path you want to save toolchain> –toolchain=arm-linux-androideabi-4.4.3`

make-standalone-toolchain.sh have in NDK build folder.

**Comment by kimkulling** [comment]
You can try this tutorial as well: https://github.com/assimp/assimp/wiki/Android-compilation-on-Windows-(Quick-overview)
