### ISSUE TITLE
aiCreateAndRegisterDefaultMaterial is broken

### ISSUE THREAD

**Issue by turol** [assimp/assimp#2126]
It will lead to double-free when using multiple importers.

This addition to unit tests:
```
TEST_F(utSTLImporterExporter, test_multiple) {
    // import same file twice, each with its own importer
    // must work both times and not crash
    Assimp::Importer importer1;
    const aiScene *scene1 = importer1.ReadFile( ASSIMP_TEST_MODELS_DIR "/STL/Spider_ascii.stl", aiProcess_ValidateDataStructure );
    EXPECT_NE(nullptr, scene1);

    Assimp::Importer importer2;
    const aiScene *scene2 = importer2.ReadFile( ASSIMP_TEST_MODELS_DIR "/STL/Spider_ascii.stl", aiProcess_ValidateDataStructure );
    EXPECT_NE(nullptr, scene2);
}

```

Will result in this when run:
```
[ RUN      ] utSTLImporterExporter.test_multiple
double free or corruption (out)
Aborted
```
Reverting part of #2069 will fix it. The old code is still there in comments in `STLLoader.cpp`. Just put the old code back and add that unit test to make sure that the real fix for #1724 won't break. This bug is very critical since it breaks existing applications.

**Comment by JekaS178RUS** [comment]
Let's discuss here how to handle default material or any default properties which set in importers. For example STL importer creates default material with full white specular diffuse and ambient components, OBJ instead set diffuse to 0.6 and non full white specular and ambient. All three components setted to full white is not a good idea, model will be over saturated. I have my own values which I would like to be default (I belive I am not alone), and I don't have API to know if any material property is really set in material or it's a defaulted by importer. Another example: I have PLY model with texture but without any light specified. Should created material to be "Default" or not? I belive it's not. 

While parsing material method Get will not change variable if property doesn't exist in material, it gieves simple way for developers to set their own default properties:

```
aiColor3D dif(0.6f,0.6f,0.6f);
aiColor3D amb(0.2f,0.2f,0.2f);
aiColor3D spec(0.2f,0.2f,0.2f);
float shine = 32.0;
ai_material->Get(AI_MATKEY_COLOR_AMBIENT, amb);
ai_material->Get(AI_MATKEY_COLOR_DIFFUSE, dif);
ai_material->Get(AI_MATKEY_COLOR_SPECULAR, spec);
ai_material->Get(AI_MATKEY_SHININESS, shine);
```
In this way I think good solution is to create material but not set any properties which is not declared in importing file, in this case aiCreateAndRegisterDefaultMaterial will not be needed. And problem with detecting defaulted values will be solved.
