### ISSUE TITLE
Compilation fail with MinGW in debug mode

### ISSUE THREAD

**Issue by JLouis-B** [assimp/assimp#2131]
Hi,
I have an issue to build Assimp in debug mode.

Sound similar to some previous issues like #177 
No problem in release, just with the debug config.

There is the error :

`[  8%] Building CXX object code/CMakeFiles/assimp.dir/Importer/IFC/IFCReaderGen1_2x3.cpp.obj
cd /d C:\Users\Jean-Louis\Desktop\Libs\assimp-master\Builds\CB_Build\debug\code && C:\Qt\Tools\mingw530_32\bin\g++.exe  -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DOPENDDLPARSER_BUILD -DWIN32_LEAN_AND_MEAN -Dassimp_EXPORTS @CMakeFiles/assimp.dir/includes_CXX.rsp -fvisibility=hidden -Wall -Wno-long-long -std=c++11 -Wa,-mbig-obj -g   -U__STRICT_ANSI__ -o CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj -c C:\Users\Jean-Louis\Desktop\Libs\assimp-master\code\Importer\IFC\IFCReaderGen1_2x3.cpp
C:/Qt/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: too many sections (47684)
C:\Users\JEAN-L~1\AppData\Local\Temp\ccI6sJPu.s: Assembler messages:
C:\Users\JEAN-L~1\AppData\Local\Temp\ccI6sJPu.s: Fatal error: can't write CMakeFiles\assimp.dir\Importer\IFC\IFCReaderGen1_2x3.cpp.obj: File too big
`

**Comment by JekaS178RUS** [comment]
Duplicated, have a look here https://github.com/assimp/assimp/issues/2067

**Comment by JLouis-B** [comment]
Ok, I hadn't see that
