### ISSUE TITLE
Assimp.Scene for Collada does not give access to the ID-attributes of its elements

### ISSUE THREAD

**Issue by aleksandaratanasov** [assimp/assimp#214]
Hi!

  Is it possible for the developers of Assimp to make the ID-attribute of the various Collada-elements visible for read-only access? Assimp's Collada import feature is actually missing a lot of things from 1.4 (1.5 is not supported at all if you include 1.5 elements (that is - elements that are not part of the 1.4 specification) in your document, which throws exceptions about missing elements, breaks the parsing process and thus makes it impossible to use with the latest Collada standard) such as the physics-models and the included shape-element, which is really useful for putting objects in space without the need to alter their geometric data by using the rotation- and translation-nodes (example: assembling multiple links of a robot together; in 1.5 you can extract this information from the kinematics-model-element where each link is attached and additional parameters such as position and orientation in space can be given). If I want to add support for those elements in my application, I also have to parse the geometric data to get my hands on the id of each and every geometry stored there and thus be able to reference it in the instance_geometry-element's child - the shape-element (attribute URL stores the reference to the respective geometry). This is quite unhandy especially since the LoadCollada-object obviously works with those IDs internally (otherwise referencing the various arrays, materials etc. would be impossible!) and the user is forced to do additional parsing of data (especially if more attribute-info is needed things can get pretty ugly) that is already been used and could have been stored. Even if only the geometry-element's ID-attribute is visible this can be a huge relief.

Best regards,
Aleksandar

**Comment by kimkulling** [comment]
As far as I know this is already the case. I just checked the code and the ids from all nodes are stored as the aiNode names.
