### ISSUE TITLE
Assimp export from FBX to gltf2

### ISSUE THREAD

**Issue by modestotech** [assimp/assimp#2144]
I've managed to export FBX to gltf2 with the syntax. 
assimp export fileIn.fbx fileOut.gltf -fgltf2

When validating over at [Khronos](https://github.khronos.org/glTF-Validator/) the asset is valid. However, I get a message:
`                "code": "NON_RELATIVE_URI",
                "message": "Non-relative URI found: /mnt/c/Users/Max/Documents/models_out_web/model02.bin.",
                "severity": 1,
                "pointer": "/buffers/0/uri"`

Will this be a problem when I start to distribute the gltf2 models? They will be stored in a library and used by an organisation. If yes, how do I solve it?

**Comment by kimkulling** [comment]
You need to define a relative URI like `../mydata/model2.bin`
