### ISSUE TITLE
feature request [view xyz axis "gizmo"] and [save flip normals]

### ISSUE THREAD

**Issue by MeinerI** [assimp/assimp#2146]
Я не говорю по-английски. 
Хочется видеть расположение осей 
и сохранять модель с флипнутыми нормалями.

**Comment by tellypresence** [comment]
> Я не говорю по-английски. Хочется видеть расположение осей и сохранять модель с флипнутыми нормалями.

"I don't speak English.
I would like to see the axis orientation
and save the model with flipped normals."
