### ISSUE TITLE
Using assimp to convert model with separate texture file to a single GLB

### ISSUE THREAD

**Issue by shueseman-skyline** [assimp/assimp#2149]
I want to use assimp to convert files from a variety of formats to the GLB2 format (for use with Cesium).  However, the resulting GLB files still have references to an external texture files.  Is there a flag I can set when doing the export that will "bundle up" the textures into the GLB?  

For instance, when I convert the Collada duck model in the assimp models folder to a GLB2, the resulting GLB2 still references duckCM.tga.   I have reviewed the various post processing flags that are available, but there doesn't seem to be one that achieves this.

The command I am running:

assimp export C:\Users\Scott\Downloads\assimp-4.1.0\test\models\Collada\duck.dae C:\Users\Scott\Pictures\duck.glb -fglb2

Is this not a supported scenario with assimp?  I am trying this with the release version 4.1.0 of assimp.

**Comment by shueseman-skyline** [comment]
Hi, just wanted to follow up.  This is working pretty well for me.  I downloaded the latest source, built and tested via the command line tool.  It does create the single GLB files with the embedded textures.   Thanks for the quick turnaround.

**Comment by shtams** [comment]
I ran into the same problem, but so far assimp v.5.0 still has an external link for the texture (((

**Comment by ponahoum** [comment]
@shtams i works for me with 5.0.1. You should try the following command
`.\assimp.exe export "input.fbx" "output.glb" -embtex`

**Comment by JSWorkspace1** [comment]
I was also testing converting to glb with embedded textures with the "/test/models/Collada/duck.dae" 
While most glb Viewers will show the textures correctly but not all will.
The Original texture is a .bmp file wich gets embedded in the glb but the GLTF spec appears to only support png and jpg formats for textures.
In the official [Validator ](https://github.khronos.org/glTF-Validator/) can see the following error message  "Invalid MIME type 'image/bmp' for the texture source. Valid MIME types are ('image/jpeg', 'image/png').",   

Would it be possible to automatically convert textures when exporting to GLB to stay in Specification?

**Comment by Abde5** [comment]
+1 @JSWorkspace1.

Exporting to glTF from many file formats i.e. the test models with tga/bmp textures do not work well in some viewers.

With imagemagick we could easily achieve this. What do you think @kimkulling ?
