### ISSUE TITLE
aiImportFile: produces scene 0x0

### ISSUE THREAD

**Issue by elenaVal** [assimp/assimp#2163]
Hello, 
i am quite new of how to use assimp library, so i have an issue that i do not really know how to solve it.
In particular, i am trying to call the aiImportFile in order to create the scene and after that to display a 3D object (.ply). However, in some cases i got back that the scene is 0x0 size.

Do you know, how to solve this issue or to find what causes this problem?
I would like to point out that the same 3D object could be opened by using an external software, so i guess that there is no problem with the object itself. 

Thanks a lot

**Comment by kimkulling** [comment]
Just check the log or test to import your model via the Assimp-viewer. Normally a 0x0-scene is a signe for an incorret imported models because of model errors like no triangles inside the model.
