### ISSUE TITLE
FBX unit scale issue

### ISSUE THREAD

**Issue by Nimer-88** [assimp/assimp#2166]
FBX files exported (at least from Maya) use centimeters as base unit (no matter which unit is setup in the Maya preferences as current unit), but FBX when importing threats these values as meters.

As result the same 3d object exported from Maya as FBX and DAE gets imported with different scales.

I believe the assimp unit scale (by default) is meter (same as in case of collada files).

**Comment by kimkulling** [comment]
You can get the current unit scale used from the FBX file via: 

`    scene->mMetaData->Get("UnitScaleFactor", factor);
`

**Comment by LeithKetchell** [comment]
The following code fails to retrieve the unit scale factor from a binary fbx file.
[code]
        Assimp::Importer importer;
        const aiScene *scene = importer.ReadFile(GetNativePath(inFile).CString(), aiProcess_ValidateDataStructure);
        double factor(0.0);
        bool result = scene->mMetaData->Get("UnitScaleFactor", factor);
        if(result==false)
            PrintLine("Failed to retrieve  unit scale factor!");
        else
            PrintLine("Scale is " + String(factor));
[/code]
Assuming that query had worked, do I set my scale factor as follows? I note that unit scale is a double, but there's apparently no method to set a double on an import property.
[code]
            aiSetImportPropertyFloat(aiprops, AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY, factor);
            flags |= aiProcess_GlobalScale;
            scene_ = aiImportFileExWithProperties(GetNativePath(inFile).CString(), flags, nullptr, aiprops);
[/code]

**Comment by sanonz** [comment]
I have the same problem.

**Comment by garraGH** [comment]
I can retrieve the factor. But it corruptted when the function is over.

**Comment by kimkulling** [comment]
Ok, thanks for the info. I have reopened the issue.

**Comment by kimkulling** [comment]
You can get a copy of the unitscale as a double. The metadata-api can be use t access and set the unitscale in c++:

```
TEST_F(utFBXImporterExporter, importUnitScaleFactor) {
    Assimp::Importer importer;
    const aiScene *scene = importer.ReadFile(ASSIMP_TEST_MODELS_DIR "/FBX/global_settings.fbx", aiProcess_ValidateDataStructure);

    EXPECT_NE(nullptr, scene);
    EXPECT_NE(nullptr, scene->mMetaData);

    double factor(0.0);
    scene->mMetaData->Get("UnitScaleFactor", factor);
    EXPECT_DOUBLE_EQ(500.0, factor);

    scene->mMetaData->Set("UnitScaleFactor", factor * 2);
    scene->mMetaData->Get("UnitScaleFactor", factor);
    EXPECT_DOUBLE_EQ(1000.0, factor);
}

```
This value will not get corrupted when the importeer gets destroyed. But the metadata will be released. So you have to cache the unitscale.

The import-property will be set as float/double depending on the requested precision of the assimp. Normally the unit-scale-factor is always double. This is a bug from my point fo view. We need to have a double property setter as well to be consistent in our API.

**Comment by kimkulling** [comment]
Please check https://github.com/assimp/assimp/pull/3137

**Comment by jinfagang** [comment]
Hi, if I want get the max extent from obj model, how to get it? the scale factor here always returns me 1. Clearly my model is not 1

**Comment by mickeyordog** [comment]
I'm still experiencing this issue. The following code after import:
`    double factor(0.0);
    if (assimpScene->mMetaData->Get("UnitScaleFactor", factor)) {
        std::cout << "Unit scale factor is " << factor << std::endl;
    }
    else {
        std::cout << "Failed to get unit scale factor!" << std::endl;
    }`
Always results in failing to get the unit scale factor. Changing it to a float will successfully get the value 1, though my fbx files are importing 100x too big
