### ISSUE TITLE
OBJ file parsing error

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#2177]
Hi. OBJ file parsing is ignoring the last line when there is no CRLF (or just CR) at the ending of the line.

Test obj code:
`mtllib cube.mtl

v -1.000000 -1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 1.000000
v 1.000000 1.000000 1.000000
v -1.000000 1.000000 -1.000000
v 1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v 1.000000 -1.000000 -1.000000

vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000

vn 0.000000 0.000000 1.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 -1.000000 0.000000
vn 1.000000 0.000000 0.000000
vn -1.000000 0.000000 0.000000

g cube
usemtl cube
s 1
f 1/1/1 2/2/1 3/3/1
f 3/3/1 2/2/1 4/4/1
s 2
f 3/1/2 4/2/2 5/3/2
f 5/3/2 4/2/2 6/4/2
s 3
f 5/4/3 6/3/3 7/2/3
f 7/2/3 6/3/3 8/1/3
s 4
f 7/1/4 8/2/4 1/3/4
f 1/3/4 8/2/4 2/4/4
s 5
f 2/1/5 8/2/5 4/3/5
f 4/3/5 8/2/5 6/4/5
s 6
f 7/1/6 1/2/6 5/3/6
f 5/3/6 1/2/6 3/4/6`

**Comment by kimkulling** [comment]
Damned, this one was already fixed before. I need to fix xthe unittest as well.

Thanks a lot for the report.

**Comment by rickomax** [comment]
@kimkulling I've fixed that on TriLib repo. I'll make a pull-request as soon as I have sorted out some stuff.

**Comment by kimkulling** [comment]
Shall work now.
