### ISSUE TITLE
Cannot import files from Maya

### ISSUE THREAD

**Issue by PeymanT** [assimp/assimp#2178]
We have been using assimp and maya successfully for several weeks but now all of a sudden no files from Maya work. I've tried both FBX and Collada and both are empty when you look at the imported assimp scene. I have tried both Maya student 2018 and Maya LT. One of my colleges managed to get one of the files to load by running it through blender first but even this has proven to be unreliable on my end. A simple test cylinder exported from maya crashes the importer because the scene is empty. I'm using default settings and exporting with FBX 2018, however I have tried older versions down to FBX 2013 as well without success. It would be helpful if someone could download the simple cylinder provided and see if they can import it since we are unsure as to what is causing this since we have not touched the importer for a long time and as I said before FBX files from Blender appear to be working. So I'm not sure if this is a bug with assimp or not.

[testcylinder.zip](https://github.com/assimp/assimp/files/2468279/testcylinder.zip)

Update:
The issue may lie in a conflict between Maya Student 2018 and Maya LT since the issues only appeared after I installed the former alongside the latter. I'll update here again if that is the case but for now it is still assimp that fails and not our own code, for whatever reason.

**Comment by kimkulling** [comment]
Try it again, works now.
