### ISSUE TITLE
MinGW build problem: "string table overflow at offset"

### ISSUE THREAD

**Issue by JekaS178RUS** [assimp/assimp#2179]
Hello! Recently I tried to build assimp with mingw, again...
And found another issue:

$ cmake .. -G "Ninja" # or "MSYS Makefiles" 
$ ninja

> [ 19%] Building CXX object code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj
> D:/Programming/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: section .xdata$_ZNSt10_Head_baseILy0EPN6Assimp8StepFile29directed_dimensional_locationELb0EE7_M_headERKS4_: string table overflow at offset 10000029
> D:\Programming\tools\msys2\tmp\ccJ7OgCw.s: Assembler messages:
> D:\Programming\tools\msys2\tmp\ccJ7OgCw.s: Fatal error: can't close CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: File too big
> mingw32-make[2]: *** [code/CMakeFiles/assimp.dir/build.make:1431: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj] Error 1
> mingw32-make[1]: *** [CMakeFiles/Makefile2:191: code/CMakeFiles/assimp.dir/all] Error 2
> mingw32-make: *** [Makefile:130: all] Error 2
> 
> 
> FAILED: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj
> D:\Programming\tools\msys2\mingw64\bin\c++.exe  -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_OWN_ZLIB -DOPENDDLPARSER_BUILD -DWIN32_LEAN_AND_MEAN -Dassimp_EXPORTS -I../. -I../include -I. -Iinclude -ID:/Programming/tools/msys2/mingw64/include -I../code/../contrib/rapidjson/include -I../code/../contrib -I../contrib/irrXML -I../code/../contrib/openddlparser/include -I../code/../include -Icode/../include -ID:/Programming/tools/msys2/mingw64/include/minizip -fvisibility=hidden -fno-strict-aliasing -Wall -Wno-long-long -std=c++11 -Wa,-mbig-obj    -U__STRICT_ANSI__ -MD -MT code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj -MF code\CMakeFiles\assimp.dir\Importer\StepFile\StepFileGen1.cpp.obj.d -o code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj -c ../code/Importer/StepFile/StepFileGen1.cpp
> D:/Programming/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: section .xdata$_ZNSt10_Head_baseILy0EPN6Assimp8StepFile29directed_dimensional_locationELb0EE7_M_headERKS4_: string table overflow at offset 10000029
> D:\Programming\tools\msys2\tmp\ccYniIgq.s: Assembler messages:
> D:\Programming\tools\msys2\tmp\ccYniIgq.s: Fatal error: can't close code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: File too big

[Here ](https://stackoverflow.com/questions/14125007/gcc-string-table-overflow-error-during-compilation/14601779)I found a workaround for this:

cmake .. -G "Ninja or what ever you are using"  -DCMAKE_CXX_FLAGS=-O2

**Comment by kimkulling** [comment]
Fixed.
