### ISSUE TITLE
OBJ file parsing error (2)

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#2186]
Hi.

There is a strange parameter in a method call in 'ObjFileParser' which isn't allowing Assimp to load certain OBJ files.

This is the line:
[https://github.com/assimp/assimp/blob/4d3ce0fed2859576e63c2eb5b67f1e5f2913be89/code/ObjFileParser.cpp#L122](https://github.com/assimp/assimp/blob/4d3ce0fed2859576e63c2eb5b67f1e5f2913be89/code/ObjFileParser.cpp#L122)

When loading OBJ files that have relative paths in 'usemtl' lines, the above code will cause the model to stop loading prematurly, as the relative path may contain the backslash character, like this one:
`usemtl BMCD2AR3\Solid_Materials_\Matte\Normal\Brown_medium`

Can anyone explain why we have that backslash there? Since there isn't such thing defined as token or anything else in any OBJ File Format specification.

**Comment by rickomax** [comment]
@kimkulling I've fixed that on TriLib repo. I'll make a pull-request as soon as I have sorted out some stuff.

**Comment by jfaust** [comment]
This appears to have gotten changed via https://github.com/assimp/assimp/commit/35a044bda37b2bad50a41746622c746acd139631

But it has broken parsing of a large number of OBJ files. The most complete specification I know of (http://paulbourke.net/dataformats/obj/) has many uses of "\" as a line-continuation character.

A model I just ran into has a bunch of lines like this, amongst other uses of "\" as a continuation:
```
vn 0.9999989867210388 -3.294318593957679e-12 \
 0.001427346956916153
vn 0.9999989867210388 -3.294318593957679e-12 \
 0.001427346956916153
vn 0.9999989867210388 -5.843482707261483e-13 \
 0.001427346956916153
vn 0.9999989867210388 -5.843482707261483e-13 \
 0.001427346956916153
vn 0.9999989867210388 -1.939333459446968e-12 \
 0.001427346956916153
vn 0.9999989867210388 -1.939333459446968e-12 \
 0.001427346956916153
```

@rickomax @kimkulling

**Comment by rickomax** [comment]
@jfaust Never seen such thing on OBJ files!
And I work with a lot of these...
We should parse it differently then, as if this character be found on a group name, it will break the parser as it was doing before.

**Comment by jfaust** [comment]
It does seem like a silly thing to have as part of the format. Seems to be mostly designed for matrix data, but at least one exporter appears to use it to limit line lengths.

**Comment by kimkulling** [comment]
Fix is merged, so I will close this issue.
