### ISSUE TITLE
FBX instances with different materials have a single material after import

### ISSUE THREAD

**Issue by wrr** [assimp/assimp#2188]
Similarly to this issue: https://answers.unity.com/questions/1206370/fbx-instance-problem.html

If the FBX with red and blue cubes is imported via Assimp, both cubes have blue material after the import (link to FBX https://answers.unity.com/storage/temp/72655-2cubes-2color-ascii-2name.zip)

This can be reproduced with the Assimp viewer.

**Comment by kimkulling** [comment]
Ok, thanks for the report. Seems to be related to the fact that each mesh can only be assigne to one material. 
We need to special material indicator for instance-mesh-data for multible materials.

**Comment by kimkulling** [comment]
This one shall be closed now.
