### ISSUE TITLE
Textures from fbx file not being recognized.

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#219]
Hi,

I'm working with assimp trunk (3cc4ece11e), and just trying to import
some fbx models.  These models are exported from cinema 4D R14.042,
using FBX version 7.3 (2013), as text or binary. Also tried with v7.2.

Nodes, meshes and materials seems to be loaded fine, but nothing happens
with textures, no matter if I embed them or not.

On the other hand, exporting this 3d model to 3ds or dae is working, and
textures are loaded internally in assimp structure.

About flags, I usually work with ImproveCacheLocality,
joinIdenticalVertices, removeRedundantMaterials, sortByPType,
genUVs,transformUVs, optimizeMeshes and triangulate. I've also tried
removing all of them but triangulate.

Also tried to load this exported file in cinema4d, just in case exporter
is broken, but everything loaded correctly.

I've attached a logstream, to see what is going on, and found tons of
lines like this:

Warn,  T4064: FBX: ignoring dummy material layer (all entries -1)
Error, T4064: FBX: material index out of bounds, setting default material
...

Other error/warning lines found:
Error, T4064: FBX: no material assigned to mesh, setting default material
Skipping one or more lines with the same contents
Warn,  T4064: FBX-DOM (TOK_KEY, offset 0x40ef68) failed to read source
object for texture link, ignoring

I'm compiling amd64 static lib, with noboost and singlethreaded option.

**Comment by kimkulling** [comment]
Is this related to embedded textures? Because embedded textures for FBX are supported now.

**Comment by kimkulling** [comment]
Fixed by embedded texture support.

**Comment by Leo-Saramago** [comment]
Hello, there! In my .FBX text(from C4Dr18), I see my Material diffuse channel texture path, but there's no sign of the texture assigned to the alpha channel. Did this happen to anyone else?
