### ISSUE TITLE
Feature request: DropXXXProcess to control JoinVerticesProcess behaviour.

### ISSUE THREAD

**Issue by daef** [assimp/assimp#2190]
Assimp removes duplicate vertices only after comparing not only position but also comparing normals, uvs, tangents and bitangents.
This is [intended behaviour](https://github.com/assimp/assimp/blob/master/code/JoinVerticesProcess.h#L59).

I would like to import a File without it's normals(etc..) so the merging process removes as many vertices as possible.

**Comment by daef** [comment]
I guess I could archieve what I want with by removing parts of the imported data from the scene before the JoinVertices process kicks in.

I propose pendants to GenFaceNormalsProcess, ComputeUVMappingProcess and CalcTangentsProcess:
DropNormalsProcess, DropUVsProcess and DropTangentsProcess

Those Processes would run first, invalidating/dropping the data read.

That addition would probably obsolet aiProcess_ForceGenNormals - since it archieves the same.

Importers could also optimize on this (e.g. if dropNormalsProcess is set there is no need to interpret those bytes -> skip)

**Comment by daef** [comment]
Added PR with example "DropNormalsProcess" (untested code!)

**Comment by kimkulling** [comment]
Implemented, I will close this one.

**Comment by daef** [comment]
Were DropUVs and DropTangents implemented too? I cannot find the commit.
