### ISSUE TITLE
assimp-net github repo

### ISSUE THREAD

**Issue by Starnick** [assimp/assimp#2193]
I'd like to discuss the future of **assimp/assimp-net** repository. 

I do all my active development on my bitbucket repository (https://bitbucket.org/Starnick/assimpnet), which has all my other projects. Before anyone says to switch entirely to github, I originally was on googlecode but switched to bitbucket because I preferred their services over github.

However, this does cause issues. People mistake the github repo that you guys imported from googlecode as mine and I don't actually administer it. So a few ideas:

1. Delete it outright, the main assimp repository already points to my bitbucket repository.

2. Maintain a git mirror of my bitbucket repo. Although this may mean it'll get out of date.

3. Keep as is, but modify the readme/project description to point to the bitbucket repo.

Thoughts? @kimkulling?

**Comment by kimkulling** [comment]
From my point of view the right way would be to use the github-repo. So everything is in place. If you still want to work on bitbucked keep it in sync would be a proper way as well.

Any other thoughts?

**Comment by kimkulling** [comment]
@Starnick Sorry, I forget this ticket. From my point of view we are pointing now directly to the bitbucket repo. Maintaining a github-repo haven't worked for me. I don't have enough time for that.
If you are still insterested to migrate to Github we could add you to our CI. Or we need to find a way to add your DevOps-CI somehow to the assimp-stuff.

At this point just havinf the link to your repo works fine for me.
