### ISSUE TITLE
GLTF KHR_draco_mesh_compression

### ISSUE THREAD

**Issue by Starnick** [assimp/assimp#2195]
Adding support for the GLTF Extension, [KHR_draco_mesh_compression](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_draco_mesh_compression), I think will be a great addition to the GLTF exporter/importer. I mentioned this on twitter to @kimkulling, but I'm unaware of any current or pending work done by other contributors. I did see this extension mentioned in passing on some older threads that first added GLTF support to Assimp.

My company in particular would have interest in this, because our current workflow with GLTF is using it as a format that we push to a web server to store content, that can be fetched by clients to add to their project on-demand.

I might try and contribute this myself, since AssimpNet 4.1.0 has been released and I need something else to do :), but coming from .NET, working with cmake projects (other than building them) is a little intimidating. If not, at least we should have it on the radar as I'm sure other people would want this extension to be supported?

**Comment by kimkulling** [comment]
To build the c++-stuff try to follow the following tutorial: https://github.com/assimp/assimp/blob/master/Build.md 

And feel free to ask me on gitter if you need help. It would be great if you could work on that feature.

**Comment by makc** [comment]
@Starnick looking at https://github.com/Starnick/assimp it does not seem you have made any progress?

@kimkulling do you know if anybody else was working on this?

**Comment by ardenpm** [comment]
I've recently been asked about support for this. It seems to have gained popularity recently and would be useful to support.

**Comment by RichardTea** [comment]
@kimkulling What's the recommended way to bring in upstream libraries?
The 'reference implementation' of Draco compression is this Google implementation on github:
https://github.com/google/draco

Do you prefer to copy-paste or use gitmodules?

**Comment by kimkulling** [comment]
At the moment we are adding them directly to the repo, submodules are not the recommended way.

**Comment by PlasmaMichael** [comment]
@kimkulling Hi! Is there any news about Draco compression support? It is an essential feature when model and transferred over network. The good point is it looks like there is only needed to use the Google Draco lib on the vertices buffer, textures looks to not be compressed using Draco so it's only about mesh data if I'm correct. So that looks to be a good point, no need to spend time on implementing encoder/decoder, just needed to use the lib to decode the buffer data if the Draco compression is used. Thanks for the answer!

**Comment by makitsune** [comment]
This would be very useful for us as well. We're using http for all of our models and textures and draco makes a big difference.

**Comment by paynebc** [comment]
Another vote for this feature, our models are pretty huge and are transmitted over network a lot, so this is a must have for us

**Comment by RichardTea** [comment]
I should have time to look into this next week.

I'll also try to arrange it so that the draco functions can be exported from the DLL/dylib for direct use by client applications.

**Comment by Honya2000** [comment]
Any plans to support draco encoder for glb's exporting?

**Comment by Jeggery** [comment]
hello， Is this feature supported now? I'm looking forward to it. How is the progress
