### ISSUE TITLE
Export Assembly struture for STEP

### ISSUE THREAD

**Issue by eryar** [assimp/assimp#2198]
Hello,

I have looked the StepExporter and find that it can export the mesh and color in the scene, it is possible to support export the scene structure to the STEP assembly structure?

Best Regards,
Shing Liu

**Comment by kimkulling** [comment]
A lot of work. But of course is it doable :-).

**Comment by kimkulling** [comment]
Duplicate to https://github.com/assimp/assimp/issues/2734
