### ISSUE TITLE
Undefined reference Assimp::STEP

### ISSUE THREAD

**Issue by AlexAUT** [assimp/assimp#2202]
With the current master if you only build a subset of importers there are missing symbols in the shared library. When switching to `BUILD_ALL_IMPORTER_BY_DEFAULT=True` everthing works perfectly fine.

cmake command:
```
cmake .. -DCMAKE_BUILD_TYPE=$buildType
               -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=False
               -DASSIMP_BUILD_TESTS=False
               -DASSIMP_BUILD_SAMPLES=False
               -DASSIMP_BUILD_OBJ_IMPORTER=True
               -DASSIMP_BUILD_FBX_IMPORTER=True
               -DASSIMP_BUILD_COLLADA_IMPORTER=True
               -DASSIMP_BUILD_ASSIMP_TOOLS=False
```

After linking the produces shared library (find_package) I got the following missing symbols:
```
undefined reference to `Assimp::STEP::ReadFileHeader(std::shared_ptr<Assimp::IOStream>)'
undefined reference to `Assimp::STEP::TypeError::TypeError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)'
undefined reference to `Assimp::STEP::LazyObject::~LazyObject()'
```

Operating system: `Linux`
Compiler: `g++ (GCC) 8.2.1`

**Comment by kimkulling** [comment]
Ok, thanks for the bug-report. I guess this issue was introduced by the step-file-format.

**Comment by boonto** [comment]
Adding `-DASSIMP_BUILD_IFC_IMPORTER=ON` seems to be a workaround for now.
