### ISSUE TITLE
Unable to build with macOS framework

### ISSUE THREAD

**Issue by utahwithak** [assimp/assimp#2212]
This might be my fault, I'm not sure. I'm trying to compile this into a macOS framework. 
After cloning I'm running this script:
```
#!/bin/sh
rm -rf ./assimp/build
mkdir ./assimp/build
cd ./assimp/build
cmake -G Xcode -DCMAKE_MACOSX_RPATH=1 -DBUILD_FRAMEWORK=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ZLIB=ON ..
```
This outputs a Xcode project and that outputs the framework `assimp.framework` 🎉 

So I then take that output and put it into a different Xcode project to start actually using it and it fails on the import. 
```
Lexical or Preprocessor Issue Group
.../assimp.framework/Headers/vector2.h:56:10: './Compiler/pushpack1.h' file not found
```
Looking into the framework headers folder it looks like vector2.h is doing some positional imports to headers that don't get included in the framework.

**Comment by kimkulling** [comment]
Could you please post the compile errors as well. Thanks a lot!
