### ISSUE TITLE
Using framework version C breaks macOS code signing

### ISSUE THREAD

**Issue by utahwithak** [assimp/assimp#2213]
If you work around #2212 when you attempt to embed the framework into a macOS project code-signing will fail. It appears to me that this is because the build settings are setting the framework version to `C`. Xcode/CodeSign appears be always looking for a version `A` (which I think is standard). 

Changing the build settings to output the framework as version `A` resolves the issue and it can be signed. 

Doing so, though, I'm not sure if the `C` was intentional to restrict this use or if there was an issue. 

I'm not sure if this is a bug or desired behavior.

**Comment by kimkulling** [comment]
I guess this was made to have this as a desired behaviour.
