### ISSUE TITLE
.sln files can't build samples with VS2017 Community Edition

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2220]
Except the minor issue reported in #2210 I was able to build assimp library with VS2017 Community Edition.
Before the building, cmake generates the proper `.sln` files for VS2017.

I see that the samples use a different approach and `.sln` files are already provided in the repository.
The readme provides info on how to handle samples
https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/samples/README#L20-L24
but I think it's not complete.

First of all, VS2017 upgrades `.sln` files to a new format (and this is not a problem by itself), but they can't be built for a couple of reasons (at least):

- As described [here](https://stackoverflow.com/questions/44219901/cannot-open-include-file-stdio-h-visual-studio-community-2017-c-error) it's necessary change to change `Properties->General->Windows SDK Version` to `10`
- Building the samples requires `assimp.lib` and `assimp/config.h` which are generated by the library build, and (I think) they must be copied inside the proper directories

After tese two changes I was able to compile the samples (with some warnings from VS2017, which don't break the compilation).

Is this the expected way to build samples?
If this is the case, I can propose a PR with more info in `README`.
If it's not, how should I build the samples?

**Comment by kimkulling** [comment]
Please use the cmake-build-environment to generate a proper sln-file. The issue with the STEP-file -Parser should be fixed already. 
Please reopen the issue if its still not work for you.
