### ISSUE TITLE
How to import textures in plain C

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2221]
I see that there is the example SimpleTexturedOpenGL but it's in C++.
I can't find documentation and/or examples showing how to import and handle textures in plain C (not C++).
Is this possible with assimp?

**Comment by JekaS178RUS** [comment]
assimp is not about loading textures. Have a look at stb_image

**Comment by escherstair** [comment]
Based on your answer I don't understand what the following function contained in sample SimpleTexturedOpenGL are supposed to do
https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp#L174

Can you clarify, please?

**Comment by JekaS178RUS** [comment]
assimp read models. Models can have textures. Using assimp you can get texture description from model materials: path, type etc. Then using any library you want you can load file and create texture. In this example, DevIL library is used.

**Comment by escherstair** [comment]
Thank you very much.
I try to summarize what I understood form your messages and the example; feel free to correct meif I'm wrong.

- https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp#L190
The message is quite clear "Support for meshes with embedded textures is not implemented"
One doubt from my side: [this page](https://github.com/assimp/assimp/wiki/Embedded-Textures-References) refers to Embedded Textures.
Are they supported or not?

- the model can contain materials

- from materials I can get the path of the texture file
https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp#L202

- DevIL library is used to load textures from external files (*.mtl files?)

- some `glXXXXXX()` functions are used to apply textures

**Comment by escherstair** [comment]
Is https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/include/assimp/material.h#L1556 the function correspondign to the getter https://github.com/assimp/assimp/blob/e6905b6a5b57b4045f522edea7c4b5fa31c2f6c3/include/assimp/material.h#L756 for a plain C program?

**Comment by kimkulling** [comment]
Yes, it is. 

About texture-loading: Assimp just says which texture are in used and which textures are stored in raw data in the model. We do not offering any image libs to encore texture data.
