### ISSUE TITLE
OFF / Object File Format import issues

### ISSUE THREAD

**Issue by jsfrancal** [assimp/assimp#2228]
Dear all,

Thanks for this great and useful project.
I just wanted to point out some apparent deficiencies with the OFF loader.
I am using assimp 4.1 as pre-packaged under Macports in OSX, through two Python wrappers, pyassimp and assimpcy, and the issues appear with both wrappers so I am assuming the underlying implementation assimp is where the issues find their root.

While plain OFF files do load when there are no vertex attributes ('OFF' header), and the loading is also successful when there are face attributes (RGBA color in float or int format seem to load) in the file, the loading seems to fail with all variants of the OFF format containing any form of vertex attributes - colors ('COFF' header), texture coordinates ('STOFF' header), etc. Also the presence of comments in the file is not supported. In all these cases assimp reports an error 'OFF: There are no valid vertices'.
These variants are officially part of the OFF specification found e.g. on the geomview page:
http://www.geomview.org/docs/html/OFF.html
I have attached a zip file containing basic positive examples of all these variants that can help reproducing the issues. [off.zip](https://github.com/assimp/assimp/files/2594819/off.zip)

Thanks for any help with these issues,
Best regards.

**Comment by jsfrancal** [comment]
Hi all,

I've had a very quick look at the code and I confirm lack of support for any form of attributes in the current loader. If you check the following excerpt of OFFLoader.cpp, l.127 and on:

`
GetNextLine(buffer,line);
    if ('O' == line[0]) {
        GetNextLine(buffer,line); // skip the 'OFF' line
    }

    const char* sz = line; SkipSpaces(&sz);
    const unsigned int numVertices = strtoul10(sz,&sz);SkipSpaces(&sz);
    const unsigned int numFaces = strtoul10(sz,&sz);

    if (!numVertices) {
        throw DeadlyImportError("OFF: There are no valid vertices");
    }
`

You can see that the code assumes the first line starts with 'O' then skips it before loading primitive counts. With all vertex attribute versions of OFF ('[ST][C][N][4][n]OFF' in the specification), the first line isn't skipped which screws up reading the vertex count.

Actually there would be a very easy quick fix as step one toward full support, if the parser correctly parsed the first line including all other variants, the rest of the loader would go on smoothly. No attributes would be loaded aside from vertex positions as the parser would skip to the next line after reading them (which is currently what goes on with face attributes), but that's fine as it would at least minimally parse vertices and faces of the file without failing.

**Comment by jsfrancal** [comment]
Confirmation: after cloning the source, replacing line 128 with the following allows the program to load vertices and faces even with vertex attribute headers:

`
    if (strstr(line, "OFF")) {
`

I will try making a pull request. If I find the time I might be able to work a correct importer of attributes (at least vertex colors and normals).

**Comment by kimkulling** [comment]
Hi, 
thanks a lot for figuring this out! If you are spare on time I can prepare the pull request for you.

Kim

**Comment by jsfrancal** [comment]
I'm looking at the OFF loader implementation to perhaps implement normal loading; but I have a question.
The current OFF implementation reads all vertices and their coordinates, then reads faces (in the order of the OFF specification), but creates a new vertex duplicate for each vertex index in a face, such that no final vertex in the assimp mesh is shared among faces.

This kind of duplication makes sense in file formats where each vertex might have different attributes according to the face they are addressed in, such as the OBJ format where a vertex index in a face tag actually has one index per attribute, each referencing a different entry in a dedicated attribute table (among coordinates, normal, and texture coordinate tables of the file). That representation does need the conversion with vertex duplication for attribute unicity, as required by rendering APIs.

But in the OFF format there is nothing in the syntax allowing per-face per-attribute indexing that would justify such duplication.
So it would be presumably doable (and simpler and faster) to allow faces to share vertices in the final vertex buffer and avoid vertex duplication.

So my question is : is there any constraint or specification in assimp internals that forbids vertex sharing among faces?
If not, I would just simplify the current vertex loading and remove the vertex duplication.

Best,
JS

**Comment by jsfrancal** [comment]
OK I rewrote much of the OFF loader under the assumption that vertex sharing among faces is fine.
The assumption is viable as long as face color loading isn't supported. Are any kinds of face coloring data scheme supported in assimp? I don't think I've seen it anywhere. In case of flat face colors, indeed face vertices might have to be duplicated to be provided with a face specific color each time. Future work.

The implementation I provide loads all possible vertex attributes (normals, vertex colors, and texture coordinates). It parses the header as per the specification (including tolerance for the case where no OFF header is present). It also deals with comments in the header sections and manages varying dimensions and the presence of a homogenous coordinate (OFF vertices can be provided with arbitrary dimensions, my current implementation rejects any dimension value over 3).  I use the homogenous coordinate simply to divide all other coordinates by it. My current implementation assumes vertex colors are given as floats between 0.0 and 1.0 (doesn't check this bound, can add in the future). The only limitation to that is that the specification allows color channel values to be also specified as integers in range 0..255. I would assume that if detected as integers these values would need to renormalized to colors 0.0..1.0 to be generally assimp and graphics pipeline compliant and regular, but I would need confirmation as to whether this corresponds to assimp practice before putting that into the implementation.

I have attached the new code for your review and will be glad to push it to the repository with the next pull request.
[OFFLoader.cpp.zip](https://github.com/assimp/assimp/files/2615396/OFFLoader.cpp.zip)

**Comment by jsfrancal** [comment]
Didn't get an answer to my proposed contribution. Wasn't able to create a pull request when I went in that portion of the assimp github page. I'm only learning to use github but willing to learn. Just trying to offer a hand on this OFF stuff, a format we historically used a lot in our research projects at Inria and which would help my research team to adopt assimp as base loader in projects in the next months. Let me know if there's anything I can do to improve my contribution or make it more suitable to the project. Here's some stuff I may be able to help with: 

- hardening the existing OFF code to avoid leaks (currently there are probably leaked buffers when the code throws fatal exceptions - which was already the case in the existing base code)
- writing in support for loading OFF files with flat face colors, which is basically the only thing missing from the implementation supplied in my previous post
- creating support for OFF exports in assimp

Best regards,
JS

**Comment by kimkulling** [comment]
Hi,
thanks a lot for the code-review. I did not saw your update, sorry. I will prepare a pull-request for it if this is ok for you. Them we will have the complete CI-workflow with all the nessesary checks.

Kim

**Comment by jsfrancal** [comment]
Great ! Thanks ! I will try my best to provide a valuable contrib.

**Comment by kimkulling** [comment]
See https://github.com/assimp/assimp/pull/2250 for a more detailed discssion.
