### ISSUE TITLE
crash in SortByPTypeProcess when importing

### ISSUE THREAD

**Issue by stefankueng** [assimp/assimp#2229]
Crash happens here (code/SortByPTypeProcess, function Execute):

```
        unsigned int numPolyVerts = 0;
        for (;pFirstFace != pLastFace; ++pFirstFace) {
            if (pFirstFace->mNumIndices <= 3)
                ++aiNumPerPType[pFirstFace->mNumIndices-1];
            else
            {
                ++aiNumPerPType[3];
                numPolyVerts += pFirstFace-> mNumIndices;
            }
        }

```
when the model has zero indizes (i.e. pFirstFace->mNumIndices == 0).

I fixed it like this:

```
        unsigned int numPolyVerts = 0;
        for (;pFirstFace != pLastFace; ++pFirstFace) {
            if (pFirstFace->mNumIndices == 0)
                continue;
            if (pFirstFace->mNumIndices <= 3)
                ++aiNumPerPType[pFirstFace->mNumIndices-1];
            else
            {
                ++aiNumPerPType[3];
                numPolyVerts += pFirstFace-> mNumIndices;
            }
        }

```

**Comment by turol** [comment]
I don't think this is right. If a face has zero indices it should fail validation. The correct thing to do is to figure out why the importer created an invalid face and fix that.

**Comment by stefankueng** [comment]
Here's the file that crashed my app.
[Laufen-Pro-1200.zip](https://github.com/assimp/assimp/files/2595398/Laufen-Pro-1200.zip)

**Comment by turol** [comment]
Tracked this down to [DXFLoader.cpp:772](https://github.com/assimp/assimp/blob/master/code/DXFLoader.cpp#L772). Adding this after that makes it not crash, no idea if it loads correctly:

```
if (line.counts.back() == 0) {
    line.counts.pop_back();
}
```

Someone else can do the testing and PR, I don't currently have the time.

**Comment by kimkulling** [comment]
I have prepared a pull request. Feel free to review it. Thanks a lot for the report and the proposed fix. If I get it right polylines with only one vertex will be handled wrong. So this fix helps.
