### ISSUE TITLE
X File Mesh with no declared faces fails to read

### ISSUE THREAD

**Issue by leezer3** [assimp/assimp#2238]
Take this rather simplified example:
```
xof 0303txt 0032

Header {
 1;
 0;
 1;
}

Mesh {
 4;
 -0.950000;-0.144000;0.000000;,
 0.950000;-0.144000;0.000000;,
 -0.950000;-0.144000;25.200001;,
 0.950000;-0.144000;25.200001;;
 0;
 ;

 MeshMaterialList {
  0;
  0;
  ;
 }

 MeshNormals {
  4;
  0.000000;0.000000;0.000000;,
  0.000000;0.000000;0.000000;,
  0.000000;0.000000;0.000000;,
  0.000000;0.000000;0.000000;;
  0;
  ;
 }

 MeshTextureCoords {
  4;
  1.000000;9.000000;,
  0.000000;9.000000;,
  1.000000;0.000000;,
  0.000000;0.000000;;
 }
}
```
We have declared a mesh with four verticies, but no faces- Note that the number of faces is **0** , and the actual face statement is blank.

This appears to be an actually valid X file (although useless in this stripped down state), but assimp fails to load it.
It would appear to be getting confused at this point:
https://github.com/assimp/assimp/blob/master/code/XFileParser.cpp#L594
Adding the following after the loop would probably fix it (untested):
```C++
if(numFaces == 0)
{
TestForSeparator();
}
```

**Comment by leezer3** [comment]
Have another example:
```
xof 0303txt 0032

Header {
 1;
 0;
 1;
}

Mesh {
 0;
 ;
 0;
 ;

 MeshMaterialList {
  0;
  0;
  ;
 }

 MeshNormals {
  0;
  ;
  0;
  ;
 }

 MeshTextureCoords {
  0;
  ;
 }
}
```
This one doesn't like the fact that we have everything declared with a count of zero. Would probably require a little more hacking than the one above to fix, as you're specifically checking for expected numbers.

**Comment by leezer3** [comment]
Third example:
```
xof 0303txt 0032

Mesh {
 2;
 0.000000;0.000000;0.000000;,
 0.000000;0.000000;0.000000;;
 0;
}
```

This one doesn't like the fact that we've declared a mesh with verticies and nothing else.

All of these examples are somewhat pointless on their own, sorry :(

**Comment by kimkulling** [comment]
I will try to test this one:

```
if(numFaces == 0)
{
TestForSeparator();
}
```
At the moment not having any faces in the model makes the data invalid if you are testing it. So it would be nice to fix the first behaviour, but I am not quit sure if its makes sense to fix the rest ( with looking to my time ... ).
