### ISSUE TITLE
assimp_cmd fails to load Opengex file

### ISSUE THREAD

**Issue by Adriankhl** [assimp/assimp#2245]
I was trying to use `assimp info`  to load ogex file in assimp/test/models/OpenGEX.

To test that, I build 4 different version of assimp: v3.3.1, v4.0.1, v4.1.0, master.

They all can load Example.ogex, but only v3.3.1 can load collada.ogex properly.

v4.0.1 gives:
`git/assimp/code/ValidateDataStructure.cpp:93: void Assimp::ValidateDSProcess::ReportError(const char*, ...): Assertion `false' failed.
Aborted (core dumped)`

v4.1.0 gives:
`ERROR: Failed to load file: Validation failed: aiScene::mLights[3] has no corresponding node in the scene graph (light3)
assimp info: Unable to load input file collada.ogex`

master gives:
`ERROR: Failed to load file: Validation failed: aiScene::mLights[3] has no corresponding node in the scene graph (light3)
assimp info: Unable to load input file collada.ogex`

**Comment by kimkulling** [comment]
Thanks for the report, I will check that!

**Comment by kimkulling** [comment]
This one is fixed already. I will close the issue.
