### ISSUE TITLE
CMake config on Ubuntu 18.04 points to wrong include folder

### ISSUE THREAD

**Issue by manhnt9** [assimp/assimp#2247]
I install using apt: libassimp-dev
```
find_package(Assimp REQUIRED)
message(STATUS ${ASSIMP_INCLUDE_DIRS})
```
Output: /usr/lib/include
Meanwhile the true include folder is: /usr/include/assimp

The file `/usr/lib/x86_64-linux-gnu/cmake/assimp-4.1/assimp-confing.cmake` is in `/usr/lib` so the path it found out is `/usr/lib`. So I think the installation folder of the package doesn't match the cmake config.

I'm trying to make a library target out of library variable (new CMake syntax) as below:
```
find_package(Assimp REQUIRED)

add_library(Dependencies::Assimp SHARED IMPORTED GLOBAL)
target_include_directories(Dependencies::Assimp
  INTERFACE ${ASSIMP_INCLUDE_DIRS}
)
set_property(TARGET Dependencies::Assimp PROPERTY IMPORTED_LOCATION ${ASSIMP_LIBRARIES})
```
CMake output: 
```
CMake Error in library/CMakeLists.txt:
  Imported target "Dependencies::Assimp" includes non-existent path

    "/usr/lib/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Please consider updating the Assimp Ubuntu package. Thanks.

**Comment by kimkulling** [comment]
I will. Thanks a lot for figuring this out.

**Comment by manhnt9** [comment]
Thanks!

**Comment by kimkulling** [comment]
Pull-request is on its way. It would be great if you are able to test it, feedback is welcome!

**Comment by fxcoudert** [comment]
This change yields a wrong include dir on macOS (and possibly any target that sets CMAKE_INSTALL_PREFIX: https://github.com/Homebrew/homebrew-core/issues/47405

**Comment by Norb48** [comment]
Hi, can someone tell what this has to do with ubuntu or Linux when I use macos I'm trying to install mysql and I have all the dependencies needed(the latest) for mysql installed. 
```Last 15 lines from /Users/lucilalico/Library/Logs/Homebrew/mysql/01.cmake:
    Debian/Ubuntu:              apt install libedit-dev
    RedHat/Fedora/Oracle Linux: yum install libedit-devel
    SuSE:                       zypper install libedit-devel

Call Stack (most recent call first):
  CMakeLists.txt:1891 (WARN_MISSING_SYSTEM_EDITLINE)


CMake Error at CMakeLists.txt:1893 (MESSAGE):
  -DWITH_EDITLINE=system, but missing system libraries.

  You can use -DWITH_EDITLINE=bundled instead.


-- Configuring incomplete, errors occurred!

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!```
