### ISSUE TITLE
Suggestion: add LGTM analysis

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2248]
Do you think it would be a good idea adding [LGTM](https://github.com/marketplace/lgtm) analysis to this repository?
It's free of charge for open source projects and public repositories.

**Comment by kimkulling** [comment]
It will offer some security analysis feature, if I get it right. Do you know if an automatic static code analysis is part of the tool as well?

**Comment by escherstair** [comment]
As far as I understand and based on what I see on other github repositories that use LGTM, it offers a sort of code analysis.
Some of the reported issues refer to variable multiple defined, large data passed by value, sections to be refactored, ...

**Comment by kimkulling** [comment]
Done, see https://github.com/assimp/assimp/pull/2324
