### ISSUE TITLE
Mesh created for a light only file (collada)

### ISSUE THREAD

**Issue by dlyr** [assimp/assimp#2260]
Hi, I use a collada with light only (to populate a scene from other file).
When I open such a file (with my own program, or even with the SimpleOpenGL sample) I get some unwanted meshes (a cube and a pyramid).

It seems that when loading a file without mesh, some skeleton and mesh are created 
https://github.com/assimp/assimp/blob/d7eae5bb1384025b3e7e7812fd45195970d79917/code/ColladaLoader.cpp#L221

Commenting out these lines do not solve the problem, because I get no light at all.

Do you have any suggestion to load a file with only lights, and give an acces to the light data loaded ?

Thanks in advance.

**Comment by kimkulling** [comment]
You can load the model with the skeleton-mesh enabled and throgh it away at the end. So just ignore the skeleton-mesh.

**Comment by dlyr** [comment]
Well, but what if I open a set of files, without knowing in advance there will be a file with lights only ?
