### ISSUE TITLE
Using an asynchronous IOHandler

### ISSUE THREAD

**Issue by SBRK** [assimp/assimp#227]
Is there a way to handle an asynchronous IOHandler to pass to Assimp::Importer::SetIOHandler ? From what I see, the Open method must return the data right away, but I have to handle loading files asynchronously.

**Comment by kimkulling** [comment]
I guess default way at the time is to run assimp in a separate thread.

**Comment by SBRK** [comment]
> I guess default way at the time is to run assimp in a separate thread.

Old Request, I know (I'm not even working on this subject anymore) but this was not an option at the time because we were running this in a browser, complied with emscripten, and there was (at the time, at least) no support for threads
