### ISSUE TITLE
Material.inl illegal token on right side of '::

### ISSUE THREAD

**Issue by nsporillo** [assimp/assimp#2271]
I just got a test project setup and hoped I had Assimp setup and working, but I ran into this error in the Material.inl file in the include dir.

![image](https://user-images.githubusercontent.com/1480197/50050080-e313f400-00bf-11e9-9c0b-eb64ef0180d0.png)
![image](https://user-images.githubusercontent.com/1480197/50050085-ec04c580-00bf-11e9-851d-262554a92e56.png)

Line 106.

**Comment by TriJacob** [comment]
Hey dude, I'm in the exact same position as you currently. Did you manage to find a solution?

**Comment by nsporillo** [comment]
@TriJacob it was a long process but it seemed I just followed the wrong tutorial for setting everything up. I had to spend many hours trying different tutorials and eventually found a setup that worked for my setup. (Windows 10 64-Bit)

I wish I had better help, it was a very painful process.

**Comment by turol** [comment]
`windows.h` defines `min` unless you define `NOMINMAX` before including it. This breaks all kinds of things in the C++ headers.

**Comment by TriJacob** [comment]
@turol Yo, thanks for the response but I fixed this days ago haha! There was a few solutions but that wasn't one that worked for me. I ended up for a while just encasing the problem in brackets example: (std::min) which worked until I found that I had a dependancy issue that was causing it so it's all sorted now.

**Comment by Karutoh** [comment]
Encapsulating `std::min` in parentheses seemed to do the trick for me.

Windows 10 Pro x64
Visual Studio 2019 Community
Cmake

**Comment by kimkulling** [comment]
Thanks a lot for the update. 

Which tutorial have you follow? 

Kim

**Comment by psilogroup** [comment]
> 
> 
> `windows.h` defines `min` unless you define `NOMINMAX` before including it. This breaks all kinds of things in the C++ headers.

thanks this worked for me, I had included the constant NOMINMAX in preprocessor definitions: WIN32;_DEBUG;_CONSOLE;dSINGLE;NOMINMAX;%(PreprocessorDefinitions)

**Comment by vofks** [comment]
> `windows.h` defines `min` unless you define `NOMINMAX` before including it. This breaks all kinds of things in the C++ headers.

Saved my life
