### ISSUE TITLE
coverity scan not triggered anymore

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2275]
Clicking on coverity button on the home page opens the [coverity console for assimp project](https://scan.coverity.com/projects/5607).
I see that last analyzed is onJul 01, 2017.
An old issue (#609) which is marked as done should trigger a coverity report for every Travis build.
It seems that this doesn't work anymore.

Could you verify, please?

**Comment by kimkulling** [comment]
I am n track, seems to be an issue with the coverity-scan-branch. We do not react on each pull-request on master, we are using a special branch for it.

I just updated a new version for it. Let's see if it will get a trigger.

**Comment by kimkulling** [comment]
Still works.
