### ISSUE TITLE
Very big size of Assimp library (ios/android)

### ISSUE THREAD

**Issue by badaninm** [assimp/assimp#2276]
I'm trying to include glTF in my assimp version, so I have to rebuild it.
I'm building iOS/Android versions of assimp and the result size is too big. I've read wiki page and other *size* issues and tried to exclude from build unused formats (I need COLLADA, OBJ, FBX and GLTF only) and switched on ASSIMP_NO_EXPORT key. The result for iOS is about 114Mb which is not acceptable.
Since I've already used Assimp before, it's size built with the same script was multiple times tinier (for example commit c666a05e in master branch from 2/nov/2017 is about 6Mb)
I guess that using the old versions could be unacceptable some day because of updates at formats or something else so I want to keep the lib up-to-date.
Also have the size problem with android version, but it's bigger than iOS version and is too big to comfortable use. 
Unfortunately I have no old scripts which gave good results for android. But as I see it on iOS, the size became bigger.
So the question is - is it possible to reduce the assimp size on iOS/Android and how?

**Comment by aavenel** [comment]
Just a wild guess since I don't really know build pipeline for iOS and Android : 
Build script `port/iOS/build.sh` has a flag called `--no-fat`
Did you try to use this and compare build size ?

**Comment by badaninm** [comment]
Forgot to tell that 6Mb is the size of fat lib (arm64 + armv7) and 114Mb is the arm64 size only - the difference is very painful

**Comment by CapsAdmin** [comment]
This is also an issue for me on desktop. It becomes difficult to distribute a precompiled version of assimp now that it's become this big.

**Comment by pumexx** [comment]
I can confirm the huge size of libassimp.so crosscompiled for Android (armv7-a) : 114 MB.

**Comment by kimkulling** [comment]
Have you tried to compile it without the step-stuff?

**Comment by CapsAdmin** [comment]
What's "step-stuff" ?

**Comment by danielmaciel** [comment]
Is the library stripped?

**Comment by kimkulling** [comment]
Stripped? Which compiler / linker option do you mean? Thanks in advance!

**Comment by vloppin** [comment]
On Android it's seems to be "normal", as regular build adds `-g` options.
According to this android-ndk/ndk#243 issue, when using graddle to build an APK, the library are automatically stripped.
To switch to "classic" behavior it's possible to add `-g0` options on CXX_FLAGS.
I test it and move from 122 Mb to 16 Mb.

**Comment by badaninm** [comment]
Looks like vloppin is right. I tried to build assimp this way and size decreased significantly. Still need to test it, but I think it should help. Thanks!

**Comment by agGitHub** [comment]
Hi. What do you mean by "add -g0 options on CXX_FLAGS"? Does it mean that I should compile with "make 'CXXFLAGS=-g0'"? If yes, should I get directly a small .so file? Or do the size of the .so files reduced when I compile my Android project? Thanks.
