### ISSUE TITLE
GLTF: Unsupported binary glTF version

### ISSUE THREAD

**Issue by DiegoAce** [assimp/assimp#2282]
I downloaded the newest version of Blender 2.8 Beta. Exported the default cube as gltf2, and I get "GLTF: Unsupported binary glTF version" when I try to load it with Assimp 4.1.0. I attached the file exported from blender. 

[untitled.glb.zip](https://github.com/assimp/assimp/files/2707586/untitled.glb.zip)

**Comment by kimkulling** [comment]
Ok, I will check that. Thanks a lot for the hint.

**Comment by DiegoAce** [comment]
I'm using the release from Dec. 11. 
I do get the same results as you when I check the file with the provided bin/assimp executable, although when I build a static lib and use it in my program I get the error I provided when I run ReadFile. I don't have this problem with other formats like .obj, .fbx, or .dae.

I downloaded assimp and ran:
cmake CMakeLists.txt
cmake CMakeLists.txt -DBUILD_SHARED_LIBS=OFF
make -j4

Then used the resulting static libs.

**Comment by pierremoreau** [comment]
I switched to building a static library and using it in a custom application, but the model still loads fine (I am on commit 9c78a43fbe49d121289e604c641a9ed13664ac9c).

**Comment by DiegoAce** [comment]
Maybe because I'm on a Mac? 
GNU Make 3.81 built for i386-apple-darwin11.3.0
cmake version 3.11.4

The code is simple:
```
            Assimp::Importer importer;
            const aiScene* scene = importer.ReadFile(file.c_str(), 0);
```

**Comment by kimkulling** [comment]
The latest master will work. Hold on, we will release a new version this month ( hopefully ) : 5.0.

**Comment by tellypresence** [comment]
I get the same error when attempting to load bundled test model
`test/models/glTF/BoxTextured-glTF-Binary/BoxTextured.glb`
Error:
`Unsupported binary glTF version`
