### ISSUE TITLE
How to use assimp

### ISSUE THREAD

**Issue by 1097170892** [assimp/assimp#2298]
Hello, I am a beginner, I hope to use assimp to make a format converter, may I ask if there are any examples for reference, how to use assimp, thank you for your answer

**Comment by kimkulling** [comment]
Hi,

you can check this link if you want to use assimp for converting things:

https://stackoverflow.com/questions/33091864/assimp-command-line-to-convert-obj-file-to-slt

And this tutorial helps how to load stuff with it:

http://ogldev.atspace.co.uk/www/tutorial22/tutorial22.html
