### ISSUE TITLE
Possible to enable and disable meshes?

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2305]
Is it possible to enable and disable meshes both outside and inside of an animation?

1. format specifies disabled meshes
2. animation disables and enables meshes or alternatively a mesh vertex animation data type. This is different from a blend shape because the number vertexes can be different.

**Comment by kimkulling** [comment]
If I get you right you want be able to disable a mesh in the animation controller, right?

**Comment by fire** [comment]
The goal is to handle mesh animations that are different per frame.

I can use the blend shapes to handle vertexes that are not added / deleted.

Any idea how to design this?

**Comment by fire** [comment]
I have a prototype for blend shaped based constant topography (no vertex adds / deletes).

**Comment by fire** [comment]
https://github.com/fire/godot/blob/asset_import/thirdparty/assimp/code/ABCImporter.cpp

**Comment by kimkulling** [comment]
AS far as I know animation and blend-shapes will reference the meshes via their names. So only if the name of the mesh is referenced once it will be part of the animation. To enable / disable a set of meshes you need to change their name reference in the blend shape / animation. 

Does this makes sense to you?

Kim
