### ISSUE TITLE
Premake?

### ISSUE THREAD

**Issue by TheRealSmolt** [assimp/assimp#2308]
I know this really isn't an issue, but I don't have anywhere else to put this. Is there any way I can get assimp to work with premake? It's my current build system and I'd really like to use assimp. I know I can build it and link it separately but I'd try to link the project. Is there any way (besides rewriting it in premake (I don't know CMake too well)). Thanks.

**Comment by kimkulling** [comment]
Maybe you can give this project a try: https://github.com/TurkeyMan/premake-cmake

**Comment by TheRealSmolt** [comment]
I think this creates cmake from premake

**Comment by TheRealSmolt** [comment]
If possible I'd like to keep premake as my build system. I guess if it's not I'll need to find something else... Thanks.

**Comment by kimkulling** [comment]
Then you have to write your own premake build-script I guess. We do not support premake at the moment.

**Comment by L4ZZA** [comment]
> Maybe you can give this project a try: https://github.com/TurkeyMan/premake-cmake

What is this project supposed to do? (not clearly stated in its description)

**Comment by L4ZZA** [comment]
> If possible I'd like to keep premake as my build system. I guess if it's not possible I'll need to find something else... Thanks.

@TheRealSmolt Did you manage to build it? If so, did you build it as static library or as dynamic (aka dll)

**Comment by FelipeCarlin** [comment]
Did anyone achieve this?
I’m in the same situation, my project uses **premake**, but i can’t seem to be able to do it.

I’m currently getting linking errors when trying to link the library statically and dynamically

**Comment by Tetrago** [comment]
Yeah I ended up using Conan and premame...

**Comment by FelipeCarlin** [comment]
Thanks for the fast reply!

Could you share your premake file for assimp?

**Comment by Tetrago** [comment]
Sorry, I can't find that project, I haven't worked on it for a while. I'd recommend you look here: https://docs.conan.io/en/latest/integrations/build_system/premake.html
