### ISSUE TITLE
Windows installer does not work silently

### ISSUE THREAD

**Issue by seanmiddleditch** [assimp/assimp#2334]
The windows installer, even with the /verysilent option, still pops up a non-silent dialog for the MSVC140 redistributable package. The Assimp installer should install its dependencies silently when the installer is installed silently.

This is a problem for users of CI systems (where there is no human to click dialogs on every build) or for automated deployment systems. It effectively means that the official Assimp installer cannot be used as a reliable SDK installer.

**Comment by kimkulling** [comment]
Ok, thanks for the hint.
