### ISSUE TITLE
PyAssimp can't load simple OBJ

### ISSUE THREAD

**Issue by treyenelson** [assimp/assimp#2339]
Here's the error trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyassimp/core.py", line 321, in load
    scene = _init(model.contents)
  File "/usr/local/lib/python3.7/site-packages/pyassimp/core.py", line 216, in _init
    call_init(obj, target)
  File "/usr/local/lib/python3.7/site-packages/pyassimp/core.py", line 84, in call_init
    _init(obj,parent=caller)
  File "/usr/local/lib/python3.7/site-packages/pyassimp/core.py", line 212, in _init
    setattr(target, name, obj)
AttributeError: 'bytes' object has no attribute 'aketrans'
```

This happens even on a simple cube:
```
# Blender v2.80 (sub 44) OBJ File: ''
# www.blender.org
mtllib cube.mtl
o Cube
v -1.000000 -1.000000 1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 -1.000000
v 1.000000 -1.000000 1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 -1.000000
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.250000
vt 0.625000 0.500000
vt 0.375000 0.500000
vt 0.625000 0.750000
vt 0.375000 0.750000
vt 0.625000 1.000000
vt 0.375000 1.000000
vt 0.125000 0.500000
vt 0.125000 0.750000
vt 0.875000 0.500000
vt 0.875000 0.750000
vn -1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 1.0000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
usemtl None
s off
f 1/1/1 2/2/1 4/3/1 3/4/1
f 3/4/2 4/3/2 8/5/2 7/6/2
f 7/6/3 8/5/3 6/7/3 5/8/3
f 5/8/4 6/7/4 2/9/4 1/10/4
f 3/11/5 7/6/5 5/8/5 1/12/5
f 8/5/6 4/13/6 2/14/6 6/7/6
```

The error can be reproduced by saving that OBJ as "cube.obj" and running a docker image:
```
docker run -it --mount type=bind,source="$(pwd)",target=/models seekadventure/assimp bash

cd /models
python -c "import pyassimp; pyassimp.load('cube.obj')"
```
The docker repo description shows the Dockerfile: 
https://hub.docker.com/r/seekadventure/assimp

I tracked down the exact commit and line of code that introduce the error:
https://github.com/assimp/assimp/blob/0adc032f6983bc74f3556081c0b66f8fe874369d/port/PyAssimp/pyassimp/structs.py#L1088

Deleting that line resolves the error.
Unfortunately, I lack the understanding of assimp and python c types to find the correct solution.

**Comment by treyenelson** [comment]
@vjf You added the `mPrivate` field, so you probably have a good idea of what's going on and might be able to fix this.

**Comment by kimkulling** [comment]
There is an issue with tha latest version of pyassimp. I can reproduce it on Ubuntu. Thanks for the report.

**Comment by okuma10** [comment]
any news on this?

**Comment by SimonMaracine** [comment]
I'm still getting this error in pyassimp 4.1.4 on Ubuntu and Python 3.7. It seems that the issue still exists. Or am I doing something wrong?

**Comment by okuma10** [comment]
SimonMaracine
try an older version. If it works maybe you need to look at the difference between it and the new version. I think I ended up changing one line to get it to work

**Comment by SimonMaracine** [comment]
You're right. Version 4.1.3 of pyassimp works. But I don't know how to look at the changes between the versions.

**Comment by okuma10** [comment]
SimonMaracine
look at treyenelson's commented on Feb 15, 2019
That's how I managed to get it working.

**Comment by E1k3** [comment]
@kimkulling Please reopen this issue until this regression is fixed

**Comment by kimkulling** [comment]
OK, done!

**Comment by E1k3** [comment]
The workaround by @treyenelson still works:
> I tracked down the exact commit and line of code that introduce the error:
> 
> https://github.com/assimp/assimp/blob/0adc032f6983bc74f3556081c0b66f8fe874369d/port/PyAssimp/pyassimp/structs.py#L1088
> 
> Deleting that line resolves the error.
> Unfortunately, I lack the understanding of assimp and python c types to find the correct solution.

@vjf Any suggestions on how to solve this?
