### ISSUE TITLE
Linux/JNI: Installation fails, if ASSIMP_ANDROID_JNIIOSYSTEM=ON, but ANDROID=OFF

### ISSUE THREAD

**Issue by BoneCrasher** [assimp/assimp#2340]
If I compile assimp as follows:
1. without an android toolchain file
2. OR properly set android compilation enviornment and ANDROID set to ON
3. This script:

`#!/bin/bash

THIS=`pwd -P`

buildOne ()
{
    export CFLAGS="-m${addressmode}"
    export CXXFLAGS="-m${addressmode}"

    cd ${build_directory}

    cmake                                            \
        -DCMAKE_INSTALL_PREFIX="${deploy_directory}" \
        -DCMAKE_BUILD_TYPE=${configuration}          \
        -DASSIMP_ANDROID_JNIIOSYSTEM=ON              \
        ${source_directory}

    cmake --build . -- -j12
    cmake --build . --target install

    cd ${THIS}
}

buildOne linux ${addressmode} ${configuration}`

Assimp fails to INSTALL the compiled components, since ASSIMP_ANDROID_JNIIOSYSTEM_PATH remains undefined, leaving the ~/include/assimp/port/AndroidJNI/AndroidJNIIOSystem.hpp undetected.

**Comment by BoneCrasher** [comment]
Added PR https://github.com/assimp/assimp/pull/2341

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2341
