### ISSUE TITLE
Query to see if an mesh is hidden in FBX?

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2347]
Is there a flag I can check per mesh to see if it is disabled in FBX?

**Comment by kimkulling** [comment]
There are the properties SHow and Culling provided by the object model, maybe this could help you a little bit.

**Comment by fire** [comment]
https://github.com/assimp/assimp/blob/475e51d157e7826bdcbc0d88e6a73b1764960e0a/code/FBXDocument.h#L444 How do I access this from the p_node interface? My best guess is metadata, but any ideas?

**Comment by fire** [comment]
Show is the improper attribute. 

The proper attribute is:

P: "Visibility", "Visibility", "", "A",0

**Comment by fire** [comment]
@kimkulling Any comments on how to read this attribute from fbx?

diff --git a/thirdparty/assimp/code/FBXProperties.cpp b/thirdparty/assimp/code/FBXProperties.cpp
index 8d7036b6a9..66a47d881b 100644
--- a/thirdparty/assimp/code/FBXProperties.cpp
+++ b/thirdparty/assimp/code/FBXProperties.cpp
@@ -83,6 +83,9 @@ Property* ReadTypedProperty(const Element& element)
     if (!strcmp(cs,"KString")) {
         return new TypedProperty<std::string>(ParseTokenAsString(*tok[4]));
 	}
+    else if (!strcmp(cs, "Visibility")) {
+		return new TypedProperty<bool>(ParseTokenAsInt(*tok[4]) != 0);
+	}
     else if (!strcmp(cs,"bool") || !strcmp(cs,"Bool")) {
         return new TypedProperty<bool>(ParseTokenAsInt(*tok[4]) != 0);
     }

Isn't enough.

**Comment by kimkulling** [comment]
For me this code looks correct. But the assimp-design will cause some trouble because a visibility flag seems to be missing.

**Comment by fire** [comment]
Any suggestions on how to change the design?

**Comment by kkulling** [comment]
Sure, I would just add a visibility information to each aiNode,

**Comment by tellypresence** [comment]
> ```
> diff --git a/thirdparty/assimp/code/FBXProperties.cpp b/thirdparty/assimp/code/FBXProperties.cpp
> index 8d7036b6a9..66a47d881b 100644
> --- a/thirdparty/assimp/code/FBXProperties.cpp
> +++ b/thirdparty/assimp/code/FBXProperties.cpp
> @@ -83,6 +83,9 @@ Property* ReadTypedProperty(const Element& element)
>      if (!strcmp(cs,"KString")) {
>          return new TypedProperty<std::string>(ParseTokenAsString(*tok[4]));
>  	}
> +    else if (!strcmp(cs, "Visibility")) {
> +		return new TypedProperty<bool>(ParseTokenAsInt(*tok[4]) != 0);
> +	}
>      else if (!strcmp(cs,"bool") || !strcmp(cs,"Bool")) {
>          return new TypedProperty<bool>(ParseTokenAsInt(*tok[4]) != 0);
>      }
> ```
> 
> Isn't enough.

@fire Looks like the problem is that you're checking against the attribute name ("`Visibility`"), but at this point the `if/else` cascade is concerned with types (`string`, `bool`, `int` etc).  So if `Visibility` is in fact a boolean value, the check is already in place and no modification is necessary in that section of the code.  The question is probably, does the passed in `Element` parameter's token list actually contain "Visibility"?

**Comment by fire** [comment]
Ah, sorry this fbx issue was in 2019, I've already rewritten a fbx importer like 3-4 times by now. See https://godotengine.org/article/introducing-the-improved-ufbx-importer-in-godot-4-3/
