### ISSUE TITLE
Obj: can we still load broken files?

### ISSUE THREAD

**Issue by ov** [assimp/assimp#2349]
I got an OBJ file that has out-of-range normals indices in faces. However, both vertex and texture indices are fine, so the shape technically can be loaded without normals. However, Assimp decides to throw an exception and terminates the loading completely.

The question is: maybe we can try loading as much as we can instead?

The fix is quite simple. We need to declare two variables to `ObjFileImporter::createVertexArray()` method: `normalsok` and `texturesok`. Both `bool` and both `true`. Then inside the big loop where we check that normals and uvs are in range we should set them to `false` instead of throwing exceptions. We also need to check these vars before even trying to process another normal or texture index.

Finally, at the very end of the method we need to check if any of these variables are `false` and delete the corresponding array as it never been there. This way we miss some data, but can still load the mesh.

Unfortunately, we can't do this for positions as they are essential for the shape.

I am ready to provide a pull request, just not sure if it will be accepted, because it changes the behavior of the library for corrupted files.

**Comment by JekaS178RUS** [comment]
I like it

**Comment by kimkulling** [comment]
Me too, I will merge it!
