### ISSUE TITLE
Alembic and dependent libraries inclusion?

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2352]
I have a fork of assimp that uses the alembic libraries.

https://github.com/fire/godot/blob/c498f6ee9c50b993a911e2ee5caef830d290e950/thirdparty/assimp/code/ABCImporter.h

https://github.com/fire/godot/blob/c498f6ee9c50b993a911e2ee5caef830d290e950/thirdparty/assimp/code/ABCImporter.cpp

It depends on at least Alembic and Openexr's ILMBase. Do you want to merge the two libraries? Do you want it as an external include?

Only basic meshes and animations with same vertex count / index are imported. No uv mapping yet. Currently it is one mesh with stored frames as blend shapes.

In theory alembic animation can also be an animation where each frame is a separate mesh and enabled in the animation on demand.

Future work would be an optimizer that uses matrix / tensor math to simplify the animation into base poses using pca.

**Comment by kimkulling** [comment]
Great, I will try to integrate if after 5.0.

**Comment by fire** [comment]
https://github.com/fire/godot/blob/4a63d566ede5782ffb7c78d368258b2606929563/thirdparty/assimp/code/ABCImporter.cpp Updated repository.

**Comment by fire** [comment]
I don't know where the files went.

**Comment by fire** [comment]
They're here for future reference https://github.com/fire/godot/blob/4a63d566ede5782ffb7c78d368258b2606929563/thirdparty/assimp/code/ABCImporter.cpp.
