### ISSUE TITLE
how to calculate the matrix of a mesh

### ISSUE THREAD

**Issue by wssbygone** [assimp/assimp#2357]
hello, I'm confused about the matrix of a mesh, 

![1](https://user-images.githubusercontent.com/38974768/53722275-23556800-3ea0-11e9-9571-7b508f2069ef.png)

look at the picutre above, it's a assxml file from assimp_cmd dumping the fbx model file, and the second matrix must is not the final transformation matrix of mesh 0,  it seems the result of  some matrixs multiply by  each other, how can I calculate the true transformation matrix for mesh 0?

Thanks
Daniel

**Comment by kimkulling** [comment]
What you see is the local transformation matrix depending on its parent transformation. You can compute the global matrix by multiplying them. In the following example you want to get the global matrix for a node with one parent transformation:

`Assimp.Matrix4x4 glbalMatrix = node.Transform * parentTransform;`

Hope that helps. You will find a llof of discussions about this topic as well!

Kim

**Comment by wssbygone** [comment]
thanks for your reply, I seems that all transform matrices of nodes need to transpose  firstly, and makes the right result.

daniel
