### ISSUE TITLE
Final line of .obj without newline at the end is not loaded

### ISSUE THREAD

**Issue by rproepp** [assimp/assimp#2358]
I ran into the same problem described in #770 in the most recent Assimp version. Even when I load the test/models/OBJ/box_without_lineending.obj file added in 1550191, I don't get triangles for the face defined by the last line in the file.

Looking at the code, ObjFileParser::parseFile uses IOStreamBuffer<T>::getNextDataLine to parse the file line by line in a while loop. But getNextDataLine always returns false for the final line of the file.

**Comment by kimkulling** [comment]
Ok, thanks for the report, I will take care!

**Comment by jammm** [comment]
Same issue faced here. Using `CornellBox/CornellBox-Original.obj` from https://casual-effects.com/data/, the final object `light` doesn't load.

The above issue only happens to me on OSX, not Windows, where it loads correctly. Using Assimp 4.1.0 in both. Haven't tested in linux.

**Comment by tellypresence** [comment]
[`test/models/OBJ/box_without_lineending.obj`](https://github.com/assimp/assimp/blob/master/test/models/OBJ/box_without_lineending.obj) seems to render fine, all faces complete:
<img al="box_without_lineending_obj" src="https://github.com/user-attachments/assets/50206e6a-3aad-4a06-b308-9c46f5584adf" width=120 >

Can this be closed?

**Comment by kimkulling** [comment]
Sure!
