### ISSUE TITLE
Unable to include assimp into project: Error C2757: 'Assimp': 

### ISSUE THREAD

**Issue by Impulse21** [assimp/assimp#2364]
When adding the include files to my own project, I keep getting the following error with the ASSIMP namespace:

"error C2757: 'Assimp': a symbol with this name already exists and therefore this name cannot be used as a namespace name"

This occurs in types.h(72), and anim.h(407). Is there an issue with the namespace name?

**Comment by kimkulling** [comment]
Could you please post some code for me? Thanks!

Kim

**Comment by Impulse21** [comment]
Hey Kim,

I guess to start - this is occurring with Visual studio 2017. This error occurs once I add the following include statements to my CPP file:

#include <assimp/cimport.h>
#include <assimp/scene.h>
#include <assimp/postprocess.h>

If I attempt to compile after adding these headers, I get the namespace errors with assimp/types.h and assimp/anim.h.

Cheers,

**Comment by kimkulling** [comment]
Any namespaces before from your side or a class named assimp? The include works for me.

**Comment by Impulse21** [comment]
Nothing by that name. I can add you to my repo to see what I am doing if that helps. I removed the assimp references, but you can see where I have the includes defined in "Common\ModelLoader.h",  "Common\ModelLoader.cpp", under "3d-model-rendering" branch.

**Comment by kimkulling** [comment]
Could you please post a small reproducable example? Thanks!

**Comment by Impulse21** [comment]
Yeah for sure. I will try to get a small sample today.
Cheers!

**Comment by Impulse21** [comment]
Looks like when I try to create a small exe to reproduce this issue, it goes away. I guess I gotta figure out what is wrong with my own solution. My apologies, and thank you for the help :)

**Comment by kimkulling** [comment]
You are welcome. I know these kind of issues as well. Hard to debug!
