### ISSUE TITLE
buiding issue C2678 and C2088 with Visual Studio 15 2017 and Assimp 4.0.1

### ISSUE THREAD

**Issue by jpcordovae** [assimp/assimp#2367]
I did the command:
cmake . -G "Visual Studio 15 2017 Win64" 

and then I tried to compile the library, however I got this error:

![image](https://user-images.githubusercontent.com/573633/54090617-1a531380-4344-11e9-9fb0-65d1ca401815.png)

I tried to change the  C++ standard lenguaje and same error, seems a compiler bug or "VS standard bug" 📦 
![image](https://user-images.githubusercontent.com/573633/54090648-4ec6cf80-4344-11e9-860b-2ec32a5b465f.png)

**Comment by kimkulling** [comment]
Is it possible for you to use the latest version?

**Comment by jpcordovae** [comment]
Yes, it works with the last version.


Juan Pablo Cordova E.
