### ISSUE TITLE
contrib/zlib_note.txt still accurate?

### ISSUE THREAD

**Issue by asmaloney** [assimp/assimp#2373]
This note refers to a "heavily modified" zlib 1.2.3.

According to the sources included, zlib is at 1.2.11.1. Is it still "heavily modified"? Is the rest of this note still accurate? (Maybe add a "last modified" date in the note?)

Any reason zlib isn't included as a submodule?

**Comment by Cgettys** [comment]
In a similar vein, would we prefer to to swap over all usages of zlib to zip? Right now we have contrib/zip which is supposed to provide a nice interface for compressing (& I'm pretty sure decompressing as well) and solve these kinds of woes (and the upstream maintainer is friendly & responsive & was happy to learn that assimp uses it :) ). In addition, we have the pair of contrib/unzip and contrib/zlib doing the same operations, I believe. To me, having three dependencies, once of which is designed to replace the other two, doesn't make too much sense long-term (though obviously I understand the reasons that it may not have been done/be feasible, e.g. difficulty in refactoring.

**Comment by kimkulling** [comment]
Good point, there is no real reason to use both.

**Comment by Cgettys** [comment]
Agreed. 

I'm not taking a side on which option is better (ease of use + ease of upstreaming fixes/improvements vs incredibly common and well tested but also more set in stone), but it's probably better to pick 1 of those two options (reduced codebase size, faster tests, less chance of bugs, less warnings...) 
 

Is there a preferred way assimp does migrations? E.g. if you modify a file you update that outdated dependency to slowly migrate, or if you create a new file you must use the new one or all at once on a feature branch? 

And what's maintainers'preference between the two technology options?

**Comment by Cgettys** [comment]
Also to go back to @asmaloney's question, is there a reason that the contrib modules aren't CMake external projects? Even if they were frozen/pointing to local folders, it might clean things up a bit (but maybe not, external projects can be a pain in CMake in my experience).

**Comment by asmaloney** [comment]
I would prefer **zlib** because it ships with macOS and Linux and is pretty much the de-facto standard.

I agree - external projects can be a pain if they aren't careful with their cmake usage (see #2382) :-) But at the end of the day it makes it easier for others to build your project (assimp or whatever assimp is being included in). Another big win is that you can associate an external dependency to a specific release which is better for testing/bug handling.

**Comment by Cgettys** [comment]
Related to this whole discussion: #2396
And that's a fair argument. zip does use the same algorithms though, and since zip is so small, it has the advantage of us just being able to build it from source and avoid the whole "should we use system version" thing. 

 Another somewhat weird thing is that it looks like we're using a contrib project minizip inside of zlib at the moment (e.g. contrib/zlib/contrib/minizip), and I'm not sure I really like that nesting personally. But I don't have a huge stake either way (though I'll feel slightly bad if we switch away from zip - we just pull requested some fixes to the maintainer and he was happy to hear it was being used in Assimp). 

I don't know if anyone's run a performance comparison between zip and minizip/unzip; I think that's another important question.

**Comment by Cgettys** [comment]
Some more notes:
I think code/D3MFExporter.cpp is the only place we use zip.
Also worth noting - contrib/unzip appears to have very similar (looks like someone tweaked function parameters so they didn't have to cast??) versions of files found under contrib/zlib/contrib/minizip. I think it probably would be better to kill off the unzip folder in favor of using the minizip version. I also suspect this is where the "heavily modified" comments came from, though I'm not really sure.

**Comment by kimkulling** [comment]
Deprecated.
