### ISSUE TITLE
`Visibility` metadata is missing in FBX

### ISSUE THREAD

**Issue by xylosper** [assimp/assimp#2375]
Here's an example: https://www.turbosquid.com/FullPreview/Index.cfm/ID/1117798

This FBX contains a mesh named 'Collider' whose `Visibility` property is 0.
3D painter from Microsoft and FBX Review do not show this mesh as in the screenshots from the website.
However, when importing the file with Assimp, Assimp node for 'Collider' does not have `Visibility` in metadata, and I cannot figure out that this node should be hidden.

**Comment by fire** [comment]
Tried looking for the property "Visibility" but I couldn't get it added to assimp.

**Comment by fire** [comment]
Tried this way, but it broke the entire assimp library. https://github.com/assimp/assimp/issues/2347#issuecomment-471133081

**Comment by fire** [comment]
@kimkulling Can you comment? This is causing hassle because the meshes need to be deleted in the source or in the internal format.

**Comment by kimkulling** [comment]
Hm, at the moment there is no way to set a visibility flag for meshes, right? So when saying this mesh is not visible we are not able to store it in our node-hierarchy. 

I guess this is a design issue in Assimp we need to solve.

**Comment by xylosper** [comment]
@kimkulling Well, I'm just mentioning that metadata is missing. Once assimp imports Visiblity by converting to boolean into metadata, user can decide to display the mesh or not.

**Comment by kimkulling** [comment]
Ah, sorry, I misunderstood your issue. I need to check.

**Comment by tellypresence** [comment]
Re-opening as new issue #6263 was raised about this

**Comment by tellypresence** [comment]
Feature request issues tracked via epic #6183
