### ISSUE TITLE
FBX Loader doesn't include light data

### ISSUE THREAD

**Issue by Pitj3** [assimp/assimp#2381]
When loading FBX model exported from 3DSMax, assimp does not load light data properly.
https://i.imgur.com/02NDtB6.png

The FBX file does contain all the right data such as the position.

Seems to me this is a assimp bug.

**Comment by kimkulling** [comment]
Hi,

you can get the trnsformation data for the light in the corresponding node in the scenegraph. Just take a look into the model 

test/models-nonbsd/FBX/2013_ASCII/pyramob.fbx

There is a light with the name: Omni01 . You can find a node with the same name. Just take these transformation data. The reason for this kind of design is that in this way you can model the light transformation depending on a node ( for instance a car with lights on, when it drves the lights shall get moved as well ).
