### ISSUE TITLE
Build Fails with LNK1000 when "BUILD_SHARED_LIBS" is deactivated

### ISSUE THREAD

**Issue by lobneroO** [assimp/assimp#2384]
Using VS2017 professional.

I have loaded 5.0.0 rc1 and tried to build it with BUILD_SHARED_LIBS deactivated (ASSIMP_BUILD_ZLIB activated, everything else was default iirc), afterwards the Build of assimp would fail with "LNK1000 : Internal error during IMAGE::BuildImage"

When I reactivated the BUILD_SHARED_LIBS flag it worked again.

**Comment by kimkulling** [comment]
I was able to reproduce the issue.

**Comment by kimkulling** [comment]
Shall work now. Thanks a lot for the report!
