### ISSUE TITLE
CLI exporter options

### ISSUE THREAD

**Issue by kuzkokov** [assimp/assimp#2394]
Hi, guys! I'm trying to use assimp cli to export from `.glb` to `.obj`. And it works quite all right, but I get `.obj` files of the bigger size than was `.glb`, though using, for example, blender I am able to reduce the size.  
So my questions is, is there some options for `assimp export`, so that I could somehow set it up?
(And yeah, the size of models is mattered for me.)

**Comment by Cgettys** [comment]
It's a bit buried, and I'm not sure how much they'd help, but here you go:
```
	// -ptv    --pretransform-vertices
	// -gsn    --gen-smooth-normals
	// -gn     --gen-normals
	// -cts    --calc-tangent-space
	// -jiv    --join-identical-vertices
	// -rrm    --remove-redundant-materials
	// -fd     --find-degenerates
	// -slm    --split-large-meshes
	// -lbw    --limit-bone-weights
	// -vds    --validate-data-structure
	// -icl    --improve-cache-locality
	// -sbpt   --sort-by-ptype
	// -lh     --convert-to-lh
	// -fuv    --flip-uv
	// -fwo    --flip-winding-order
	// -tuv    --transform-uv-coords
	// -guv    --gen-uvcoords
	// -fid    --find-invalid-data
	// -fixn   --fix normals
	// -tri    --triangulate
	// -fi     --find-instances
	// -og     --optimize-graph
	// -om     --optimize-meshes
	// -db     --debone
	// -sbc    --split-by-bone-count
	//
	// -c<file> --config-file=<file>
```
[Source file](https://github.com/assimp/assimp/blob/master/tools/assimp_cmd/Main.cpp)

I think what you want is probably -og and/or -om, perhaps in conjunction with -rrm. -fi would also probably help, and potentially -jiv & -fd. Then again, I haven't played around too too much with the flags, so your mileage may vary.
See also [this documentation](http://sir-kimmi.de/assimp/lib_html/postprocess_8h.html#a64795260b95f5a4b3f3dc1be4f52e410) about what the options actually do  (slightly outdated, but useful)

**Comment by kuzkokov** [comment]
Great, many thanks!
