### ISSUE TITLE
Trying to use contrib/zip library in project gives duplicate symbol error

### ISSUE THREAD

**Issue by gitbetter** [assimp/assimp#2396]
I'm wondering how we can properly include the contrib/zip library separately in our project while also using Assimp. If I attempt to link the two libraries statically within my project I get a duplicate symbol error, because contrib/zip is built and linked as part of the Assimp library generation process. Is there a way to include contrib/zip within a project file without having to build it separately from Assimp?

**Comment by Cgettys** [comment]
I'm not sure this is actually a bug as much as it is C/C++ being C/C++. But, at any rate, one answer is to simply add #define ASSIMP_BUILD_NO_3MF_EXPORTER unless you happen to be using that exporter, since that's the one place assimp appears to be using zip.

**Comment by gitbetter** [comment]
Should have tried that. The other solution I went with was to build assimp as a shared library, but I'll keep that in mind if I need to rebuild. Thank you!
