### ISSUE TITLE
C4DImporter does not compile anymore

### ISSUE THREAD

**Issue by DerJJ** [assimp/assimp#2398]
When ASSIMP_BUILD_NONFREE_C4D_IMPORTER is ON and the Melange SDK is put in the right place, the C4DImporter.cpp does not compile anymore due to loging chances on assimp side.

Old-Code:
`template<> const std::string LogFunctions<C4DImporter>::log_prefix = "C4D: ";`
Fixable e.g. by replacing the above line with:
`template<> const char* LogFunctions<C4DImporter>::Prefix() {
        static auto prefix = "C4D: ";
        return prefix;
    }`

Assimp master, 2nd of April @ 933fe5e
Melange 20.004_RBMelange20.0_259890
Tested on win64 MSVC15.

**Comment by kimkulling** [comment]
Thanks for the report, fix is on its way.
