### ISSUE TITLE
3dtiles

### ISSUE THREAD

**Issue by simonasdmd** [assimp/assimp#2403]
Can this be done with obj split? It is to split the obj file containing multiple objects (o) into multiple separate obj files.

**Comment by kimkulling** [comment]
Good question. If I get it right: you want to split a obj-file into separate obj-files to generate a set of tiles, Correct. For instance split each group in one obj file into the tiles.

**Comment by simonasdmd** [comment]
Yes, I want to get each small obj file after splitting obj. Convert to 3dtiles

**Comment by simonasdmd** [comment]
@kimkulling Yes, I want to get each small obj file after splitting obj. Convert to 3dtiles

**Comment by kimkulling** [comment]
No one else was asking for that. So I would suggest if you are still interested in this topic just prepare a PR.

We will not be able to provide this feature.
