### ISSUE TITLE
Host doxygen documentation on GitHub

### ISSUE THREAD

**Issue by Cgettys** [assimp/assimp#2405]
The newest published version of the doxygen I can find seems to be for 4.0.0: [Documentation](http://sir-kimmi.de/assimp/lib_html/index.html). There may be newer available (and is certainly newer files on master), but it could be more easily accessible, and this might cut down on the number of issues received that take the form of "How do I do xyz?" Not that there's anything wrong with asking those questions - I think that's valid - but I think most people prefer to be able to find the answer in the documentation and not have to wait for a response.

One way to improve the availability documentation for this project would be to use something like [this gist](
https://gist.github.com/vidavidorra/548ffbcdae99d752da02) to automatically keep master's documentation up to date by extending the CI pipeline that's already in place.
Thoughts?

**Comment by kimkulling** [comment]
Right, makes completly sense!

**Comment by kimkulling** [comment]
Just moved the documentation to https://assimp-docs.readthedocs.io/en/latest/ .

**Comment by Cgettys** [comment]
Awesome!
