### ISSUE TITLE
StepFileGen1.cpp compilation error on MinGW-64

### ISSUE THREAD

**Issue by pianoman373** [assimp/assimp#2406]
When trying to compile on Windows with MinGW-64 I get the following error:

```
[ 70%] Building C object code/CMakeFiles/assimp.dir/__/contrib/zip/src/zip.c.obj
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\assimp.dir\Importer\StepFile\StepFileGen1.cpp.obj: section .xdata$_ZNSt10_Head_baseILy0EPN6Assimp8StepFile29directed_dimensional_locationELb0EE7_M_headERKS4_: string table overflow at offset 10000029
C:\Users\username\AppData\Local\Temp\ccIXyKsu.s: Assembler messages:
C:\Users\username\AppData\Local\Temp\ccIXyKsu.s: Fatal error: can't close CMakeFiles\assimp.dir\Importer\StepFile\StepFileGen1.cpp.obj: File too big
mingw32-make.exe[3]: *** [code\CMakeFiles\assimp.dir\build.make:2485: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:290: code/CMakeFiles/assimp.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:436: test/CMakeFiles/unit.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:241: unit] Error 2
```

This only happens when compiling in debug mode. Release mode works fine.

**Comment by kkulling** [comment]
Could you try to add the compiler flag /bigobj for the debug mode. Seems to be a configuration issue. 

And thanks a lot for the hint!

Kim

**Comment by pianoman373** [comment]
I tried setting both CMAKE_CXX_FLAGS_DEBUG and CMAKE_C_FLAGS_DEBUG to /bigobj but got an error that it wasn't a valid option. After some googling I found -Wa,-mbig-obj which did work as a valid option, but unfortunately didn't fix the file too big error.

**Comment by kimkulling** [comment]
I tried all these options as well and I wasn't able to find a fix for that. Argh!

**Comment by kkulling** [comment]
Honestly speaking: I do not know. This issue is currently under investigantion by me.

**Comment by Cgettys** [comment]
I was able to fix ``` string table overflow at offset ...``` by using -O2 just on that file. However, it appears that when using mingw, those symbols are still exported even though I don't understand why they are. So instead I get an error because there are too many symbols, as mentioned in the pull request. Not sure where to go from here besides trying to not export those symbols (which I'm having little luck with so far)
