### ISSUE TITLE
IRRXML is now always built as a dynamic lib on all platforms, and not deployed on Windows

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#2411]
Commit ba6a738 to fix #1650 has changed _all_ platforms, not just BSD.

This has now broken the Windows build, and possibly others, as the knock-on changes were not applied.

Please revert these commits to IRRXML, or alternatively make building IRRXML as a dynamic library optional.
Adding additional DLLs without _explictly_ calling them out as new dependencies is extremely bad form.

**Comment by kimkulling** [comment]
Good point, please check https://github.com/assimp/assimp/pull/2414
