### ISSUE TITLE
aiNodeAnim question

### ISSUE THREAD

**Issue by congard** [assimp/assimp#2415]
Hello﻿! I'm converting the data that I loaded using Assimp into my own, and the question arose.
I have code﻿ like this:

```
const aiAnimation﻿* ﻿pAnimation﻿ = ai_scene->mAnimations[0];
const aiNodeAnim* pNodeAnim = findNodeAnim(pAnimation, nodeN﻿ame);
```

`pNodeAnim` - pointer. Can the same pointer be﻿ contained in `ai_scene->mAnimations[1]`? And in general, in Assimp it happens (with any other assimp types/classes/structures)? Thanks in advance﻿﻿ ﻿for your reply﻿﻿﻿

**Comment by congard** [comment]
As far as I understand, this is impossible. Am I right?
For example, [ColladaLoader source](https://github.com/assimp/assimp/blob/master/code/ColladaLoader.cpp#L1389) or [MD5Loader source](https://github.com/assimp/assimp/blob/master/code/MD5Loader.cpp#L605)

**Comment by kimkulling** [comment]
Hi, yes you are right. Animations shall be unique. So when you are  getting an animation we must guarantee that this one is unique.
