### ISSUE TITLE
Failed to initialize Direct3D 9 (2)

### ISSUE THREAD

**Issue by X3msnake** [assimp/assimp#2422]
![image](https://user-images.githubusercontent.com/11083514/55980933-7d123480-5c8d-11e9-970e-3e08ca5dbdd2.png)

Installed release 4.0.1 from the releases

![image](https://user-images.githubusercontent.com/11083514/55981014-b77bd180-5c8d-11e9-98a5-21beea82c758.png)

Windows7 64bit

I want to use the tool to be able to read and export C4D models, besides not working at the moment does this version has this feature or must i learn how to compile a version with Maxons library? and if so why isn't there a precompiled version for those less knowlageble like me to use

**Comment by kimkulling** [comment]
You need to install the C4-libraries and build a new versio of assimp from master with the C4-support enabled.

See https://github.com/assimp/assimp/wiki/Cinema4D-&-Melange to learn more. I guess yes: you need to learn how to do this on your own at the moment, sorry.
