### ISSUE TITLE
VS2013 failed to build v4.1.0

### ISSUE THREAD

**Issue by IntPtrZero** [assimp/assimp#2423]
When i use VS2013 building the project produced by cmake, i get lots of(248) error messages. It looks like you have used some new C++ features in this version. I wonder if vs2013 is no longer surported. If so, please add some info in the realease note.
error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int 
error C2923: “std::vector”: 对于参数“_Ty”，“VmdIkEnable”不是有效的 模板 类型变量 
error C2780: “_OutTy *std::move(_InIt,_InIt,_OutTy (&)[_OutSize])”: 应输入 3 个参数，却提供了 error C2678: 二进制“[”: 没有找到接受“std::vector”类型的左操作数的运算符(或没有可接受的转换) 
error C2663: “std::vector<_Ty,_Alloc>::resize”: 2 个重载没有“this”指针的合法转换	
error C2662: “_Vector_alloc<!std::is_empty<_Alloc_types::_Alloc>::value,std::_Vec_base_types<_Ty,_Alloc_types::_Alloc>>::size_type std::vector<_Ty,_Alloc>::size(void) throw() const”: 不能将“this”指针从“std::vector”转换为“const std::vector<_Ty,_Alloc> &” 
error C2660: “pmx::ReadString”: 函数不接受 1 个参数
.........................more errors................................................

**Comment by kimkulling** [comment]
Right, I needto check that. Thanks a lot for the hint.

**Comment by kimkulling** [comment]
Compiler not supported any more.
