### ISSUE TITLE
Broken skeleton in Blender FBX exported

### ISSUE THREAD

**Issue by reduz** [assimp/assimp#2424]
Here is the .blend file and corresponding exported FBX.
Skeleton is broken in assimp.
It's a very simple file, I find it surprising that it's broken while other more complex files I tried seem to work great.

[huesitos.zip](https://github.com/assimp/assimp/files/3075645/huesitos.zip)

**Comment by kimkulling** [comment]
Hi,

jst checked the model ith the latest master. The animation as ok, the node hierarchy looked fine as well. Which version have you checked ( 4.1 or latest master )?

Kim

**Comment by kimkulling** [comment]
Just imported the model with godot using the latest assimp-master. Animation looks broken in Godot, I can confirm that.

**Comment by kimkulling** [comment]
![image](https://user-images.githubusercontent.com/2323156/56205666-b6aabd00-604a-11e9-9870-0190d2131a78.png)

This is how it looks in Assimp-Viewer.

**Comment by reduz** [comment]
What viewer is that? I am trying assimp_qt_viewer and it does not support animation.

**Comment by reduz** [comment]
Also, my feeling is this viewer just applies bone transforms directly to the mesh. In Godot we have the concept of hierarchy and actual skeletons, so we need to reconstruct the scene as it came from a DCC and there is missing information.

**Comment by kimkulling** [comment]
There is a viewer for windows using DirectX9. There you can check the skeleton-animation.

**Comment by reduz** [comment]
Ah, I'm using Ubuntu to develop, where can this viewer be downloaded? Maybe I can use wine to execute it.

**Comment by reduz** [comment]
The website has a link to this, which is obviously not the same program (and the skeleton loaded is also broken on that one):
http://www.assimp.org/index.php/viewer

**Comment by reduz** [comment]
Still broken here:
![image](https://user-images.githubusercontent.com/6265307/56217047-ee106e00-6038-11e9-9d9d-fdb623c798bb.png)

**Comment by kimkulling** [comment]
The viewer you are using there is outdated because the version of assimp is oooold. I am currently trying to debug the issue in Godot.

**Comment by congard** [comment]
I often have problems with importing a skeleton in a blender. First, make sure the blender does not “break” the model. I had the following problem: when loading a dae model and carrying out some manipulations over it (resizing) and exporting back to dae, the skeleton became damaged. When re-exporting the model is incorrectly displayed in the blender itself. I could only get around this by converting from dae to fbx and then back to dae.
So make sure this is not a blender bug.
