### ISSUE TITLE
OBJ files containing "nan" or "infinity" values for vertex texture coords cannot be opened

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#2428]
Some exporters have been found to do this, notably Vectorworks 2016, 2017, 2018 and 2019.

Attempting to import a file like this results in the fatal error `OBJ: Invalid number of components`

This is caused by `ObjFileParser::getNumComponentsInDataDefinition()`, which doesn't accept NaN or Infinity as being a component value, only using assimp::IsNumeric()

**Comment by JekaS178RUS** [comment]
Yes, I also hit this problem. But what we should do if value is nan?

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2429
