### ISSUE TITLE
PyAssimp: NULL pointer access

### ISSUE THREAD

**Issue by yohel99** [assimp/assimp#2439]
I downloaded latest source and built it.
However, I got 3 errors in Python 3.5 when pyassimp loaded a FBX file.
I temporally fixed them in my local machine.
In my guess, one of errors may not have mentioned is this topic.

**Environment**
* PyAssimp: 0x55cdf1d3
* Python: 3.5.2 in pyenv
* OS: OSX Mojave 10.14.4

**Logging**
```
DEBUG:pyassimp:Added animmesh as self.animmesh (type: <class 'pyassimp.structs.LP_LP_AnimMesh'>)
ERROR:pyassimp:In <pyassimp.structs.Scene object at 0x121f96f28>->meshes: NULL pointer access. Quitting now.
```

**Source Code**
https://github.com/assimp/assimp/blob/55cdf1d37c4ecd973c2a2e134e213cf32a772635/port/PyAssimp/pyassimp/helper.py#L277

I added a check for NULL before this line in my machine.
```
if not object:
  raise AttributeError
```
But It wouldn’t be better solution.

Thanks

**Comment by kimkulling** [comment]
Ok, thanks for the report.
