### ISSUE TITLE
library exports functions in executable

### ISSUE THREAD

**Issue by ghost** [assimp/assimp#2440]
Assimp makes my application executable to spit out .exp and .lib files on build, meaning that an unwanted __declspec(dllexport) is hiding somewhere, but where it is, exactly? I've tried to remove ASSIMP_BUILD_DLL_EXPORT from preprocessor definitions of assimp project to no avail.

**Comment by RichardTea** [comment]
Which platform/compiler?

Are you building Assimp as a DLL (default) or static library for your application?

**Comment by AnonTen** [comment]
VS2019, static library

**Comment by kimkulling** [comment]
I guess this issue is caused by the generated project space from cmake. Per default the export libs are set to enabled there. I guess I need to check how to disable this in cmake.

Thanks a lot for the bug report!

**Comment by kimkulling** [comment]
This issue does not uccur any more when creating the project files with the command:

`cmake .\CMakeLists.txt -DBUILD_SHARED_LIBS=OFF`

I tried this out for VS2019 with static linkage enables. The output in the lib folder looks like:

```
-a----        15.03.2024     15:27      336245896 assimp-vc142-mtd.lib
-a----        15.03.2024     15:27       28200960 assimp-vc142-mtd.pdb
```
I guess this shall be the expected behavior.
