### ISSUE TITLE
Builds irrXML but doesn't seem to be used

### ISSUE THREAD

**Issue by russkel** [assimp/assimp#2453]
From the process of adding assimp to alpine linux (https://github.com/alpinelinux/aports/pull/7762#issuecomment-491359839) it was determined that the static lib is built even if it is not used (which seems to be the case in our building of assimp). Perhaps the cmake build should be modified to build it if it will only actually be required?

**Comment by kimkulling** [comment]
Good point. Thanks for the hint!

**Comment by UMDire** [comment]
Hey need some help on similar issue the build is generating the irrxml but there are path issues if we need package the assimp in an app on mac. any idea how to set the path issues.

**Comment by russkel** [comment]
What are the path issues, @UMDire?

**Comment by kimkulling** [comment]
irrXML is deprecated.
