### ISSUE TITLE
Understanding the relation between mesh transforms to bones.

### ISSUE THREAD

**Issue by willmotil** [assimp/assimp#2454]
Hi im using assimp.net under MonoGame at the moment i have it basically working and i think you guys have done a wonderful job.

The problem im having fundamentally atm is in understanding the rules or intent of the mesh transform in relation to bone transforms using assimp.  Im missing something and i can't seem to figure out how to multiply them together properly.
.
Directly here is my problem.
.
When i use bones it seems that i must ignore the mesh transforms and just leave them as identity. 
And for a rigged model with no mesh transforms this seems to work just fine.
If i do try to multiply them in with the world or bones it will blow up the mesh or twist it into the wrong orientation.
.
Conversely i must use the mesh node transforms for a model with animated meshes with no bones.
All is fine then as well provided i replace when animating the original mesh transform.
.
I also have a old model that appears to use both bone and mesh animations, 
Which i can't get to work properly and is the problem im having.
.
In my mind i imagine there is a way to multiply the matrices all together without screwing up either situation and allow one formula to work for either.
But .... 
No matter how i try to multiply the mesh transforms in with the matrix multiplication chain i can't see the proper way to do it without messing up one or the other ?

A little more info...

Basically i apply the mesh transform against the world as i draw the meshes 
`effect.Parameters["World"].SetValue(world * m.MeshCombinedFinalTransformMg);`
the above which is really the mesh * the root placed in the mesh after updating the nodes.
```
        /// <summary>
        /// Updates the node transforms
        /// </summary>
        private void IterateUpdate(RiggedModelNode node)
        {
            if (node.parent != null)
                node.CombinedTransformMg = node.LocalTransformMg * node.parent.CombinedTransformMg;
            else
                node.CombinedTransformMg = node.LocalTransformMg;
            // set to the final shader matrix.
            if (node.isThisARealBone)
                globalShaderMatrixs[node.boneShaderFinalTransformIndex] = node.OffsetMatrixMg * node.CombinedTransformMg;
            // call children
            foreach (RiggedModelNode n in node.children)
                IterateUpdate(n);
        }
```
the bones are passed into my shader separately which looks like this.

```
VsOutputSkinnedQuad VertexShaderRiggedModelDraw(VsInputSkinnedQuad input)
{
    VsOutputSkinnedQuad output;

    float4 pos = input.Position;
    float3 norm = input.Normal;

    float sum = input.BlendWeights.x + input.BlendWeights.y + input.BlendWeights.z + input.BlendWeights.w;
    pos =
    mul(pos, Bones[input.BlendIndices.x]) * (float) input.BlendWeights.x / sum +
    mul(pos, Bones[input.BlendIndices.y]) * (float) input.BlendWeights.y / sum +
    mul(pos, Bones[input.BlendIndices.z]) * (float) input.BlendWeights.z / sum +
    mul(pos, Bones[input.BlendIndices.w]) * (float) input.BlendWeights.w / sum;
    
    pos = mul(pos, World);

    output.Color = float4(1.0f, 1.0f, 1.0f, 1.0f); // place holder dunno if added color.
    output.TexureCoordinateA = input.TexureCoordinateA;
    output.Position3D = pos.xyz;
    output.Normal3D = normalize(mul(norm, World));
    float4x4 vp = mul(View, Projection);
    output.Position = mul(pos, vp);
    return output;
}
```
mesh animation ok
![RMLmeshAnimations](https://user-images.githubusercontent.com/7495196/57564189-d5fce780-7375-11e9-819d-0844b3dc26d7.gif)
bone animation ok  
But i have to set the mesh transform to identity or not use it when animating.
Because the scaling for some models bone animations will multiply with the mesh transform and just explode it in size and mess up the orientation.
![RMLmeshAnimations](http://community.monogame.net/uploads/default/original/2X/9/95023776e01cdf086dfce6fe9ddeda9a08d30d93.gif)
both arrggg
![victoria](https://user-images.githubusercontent.com/7495196/57564212-499ef480-7376-11e9-99b8-e468c9ef9b4d.png)

**Comment by kimkulling** [comment]
The offset matrices will store the animation with respect to the root transform of the mesh. So I can imagine that using the local transformations with the global offset matrix will screw up your matrix and the rendering looks broken. 

Currently, we do not have the local bone transformation to the relative parent. A PR that is in a review shall fix this fundamental problem with our animation chain. But it will take a while until we will be able to provide this in the assimp.net port.

Unfortunately, we do not have any maintainer for the .NET port.
