### ISSUE TITLE
FBX Property duplicate

### ISSUE THREAD

**Issue by JekaS178RUS** [assimp/assimp#2459]
Hello!

In mingw debug build I got this error:

[ 69%] Linking CXX shared library libassimpd.dll
CMakeFiles/assimp.dir/objects.a(FBXExporter.cpp.obj): In function `Assimp::FBX::Property::~Property()':
D:/Programming/libs/assimp-src/code/FBXExportProperty.h:82: multiple definition of `Assimp::FBX::Property::~Property()'
CMakeFiles/assimp.dir/objects.a(FBXProperties.cpp.obj):D:/Programming/libs/assimp-src/code/FBXProperties.cpp:66: first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:3178: code/libassimpd.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

And there is actually 2 Assimp::FBX::Property classes one in 
https://github.com/assimp/assimp/blob/master/code/FBXProperties.h
and second in
https://github.com/assimp/assimp/blob/master/code/FBXExportProperty.h

**Comment by kimkulling** [comment]
Fix is on its way, thanks for the report.
