### ISSUE TITLE
ASSIMP::string too long error?

### ISSUE THREAD

**Issue by Megas97** [assimp/assimp#2471]
Hello everyone,

I have a code which should work with any .obj model out there but it only works with the nanosuit example model from the tutorials. Most of the time I get the error ASSIMP::string too long in the console and no model shows up. I tried so many models but like 90% give that error. I just want to load/display some car model (preferably from the ones below, but if none work any car would be fine as long as it loads and displays correctly). I really have no idea how OpenGL works, but my lecturer said if I change the model it should all be fine. If someone can shed some light on a fix for this error or some 100% working code for loading .obj models I'd greatly appreciate it as my deadline is on the 29th this month and I have nothing right now. Can't imagine what the exam will be if this is so hard, please help :(

PS: Here are the models that give "string too long" error:
Dodge Challenger: https://free3d.com/3d-model/dodge-challenger-1971-72998.html
Dodge Charger: http://animium.com/2008/08/dodge-charger-r-t
Ford Mustang: https://free3d.com/3d-model/ford-mustang_gt-500-193364.html

Also I'm using Visual Studio 2017 Community on Windows 10 and OpenGL 3.3+ with C++ (or C).

**Comment by Megas97** [comment]
Fixed! Had to remove all empty tags in the .mtl files of objects. :)

**Comment by kkulling** [comment]
Nice to hear that.
