### ISSUE TITLE
AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES removes all bones

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2474]
importer.SetPropertyBool(AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES, false); removes all bones.

**Comment by kimkulling** [comment]
Ops, thanks a lot for the hint!

**Comment by fire** [comment]
Attaching a sample model.

https://github.com/assimp/assimp-mdb/blob/master/model-db/fbx/huesitos.fbx

**Comment by RevoluPowered** [comment]
Resolved! Please close me.

**Comment by kimkulling** [comment]
Ok, I will do so!
