### ISSUE TITLE
Incorrect Shininess value in material for FBX-model

### ISSUE THREAD

**Issue by ivan-kadyko** [assimp/assimp#2477]
Hello. I use assimp.net 4.1. As I understand property  "Hardness" is equals in property in "Assimp.Material.Shininess". When I load blender-project, I have the same value(Shininess = Hardness ). Also I haven't problem when export collada 3d-model from Blender editor and loaded in assimp, But when I load export fbx 3d-model from Blender editor and loaded via current library values are different (Shininess != Hardness)

I have attached a simple example.
[simple_project.zip](https://github.com/assimp/assimp/files/3202894/simple_project.zip)

**Comment by kimkulling** [comment]
I guess this issue is already fixed.
