### ISSUE TITLE
Ports - Which are actually maintained

### ISSUE THREAD

**Issue by Cgettys** [assimp/assimp#2486]
I've been trying to track down a couple of bugs & have looked at the issue board and source tree a lot lately, and I noticed the following about the ports at https://github.com/assimp/assimp/tree/master/port:
PyAssimp - seems to have drifted from the API since it was once autogenerated but is no longer & gotten lots of bugs as a result
AssimpDelphi - 8 years old
The below appear to be incomplete, untested, and have not seen code changes in 9 years as far as I can tell:
dAssimp
swig

My question is which of these actually work & are maintained, and which are not actually used by anyone? While it doesn't cause issues for me personally, it seems like it might be worth thinking about as part of the v5.0 reorganization and cleanup you seem to be working on @kimkulling.

**Comment by kimkulling** [comment]
Here the list with the current maintain-status for the ports. Just pink me if something needs to get fixed!

* PyAssimp - Maintained by the community most of the time
* NetAssimp - Maintained by this repo https://github.com/kebby/assimp-net, fixes for the links are on their way
* AssimpDelphy - Not maintained at the moment
* dAssimp - I do not have a clue
* jAssimp - Maintained
* Pascal - I don't know
* Javascript (Alpha) - Same here
* Unity 3d Plugin - Maintained
* HAXE-Port - Maintained.
