### ISSUE TITLE
Release build

### ISSUE THREAD

**Issue by antoninklopp** [assimp/assimp#2512]
Hi, 

Thank you for the awesome work. I am using the trilib package for unity which is using assimp, but it seems that there is a build problem in the assimp version for android it is using. 

Since it seems very painful to build assimp for android, could you had the binaries for some platforms in the next release? It would be very helpful. 

Thank you very much !

**Comment by kimkulling** [comment]
We will try to optimize the build chain. But I will not be able to fulfill the requirement to offer build artifacts for all supported platforms.
