### ISSUE TITLE
Importer unicode support broken

### ISSUE THREAD

**Issue by rmccampbell** [assimp/assimp#2513]
This issue https://github.com/assimp/assimp/issues/1612 addressed unicode support on windows. However although it was closed, the solution is broken as mentioned in the follow up responses. The IsTextUnicode check should be removed and the proper unicode functions always used on windows. (This check is not useful for efficiency anyway, since windows will translate legacy ANSI function calls to unicode behind the scenes regardless).

**Comment by rmccampbell** [comment]
Also it seems that MB_PRECOMPOSED is deprecated. And the fixed sized buffers should ideally be replaced with dynamically sized.

**Comment by kimkulling** [comment]
You are right, this issue is still there. The issue #1612 was duplicated. That was the reason that I haven't reopen it again.

**Comment by rmccampbell** [comment]
Where's the duplicate?

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2633
