### ISSUE TITLE
assimp can't open the maya custom dae model

### ISSUE THREAD

**Issue by acfhs** [assimp/assimp#2514]
Dear all,
Thanks for this great and useful project.
I recently made a human body model using Maya and exported as dae (version1.6) format (using the plug-in opencollada - Maya - PC - 2018, https://github.com/KhronosGroup/OpenCOLLADA/releases);
As a result, assimp cannot open this file, but the dae (version1.4) file made by makehuman can be worked, I don't know why.
Thanks for any help with these issues,
Best regards.

**Comment by RichardTea** [comment]
Can you link to a DAE model that fails?

**Comment by acfhs** [comment]
thanks for your help, all the resources are here; https://github.com/acfhs/model.git

**Comment by RichardTea** [comment]
The Maya one does open, and has all the geometry, however it is completely transparent.

I suspect this is a bug in the Maya export as it doesn't reference any texture files, while the makehuman one does.

**Comment by acfhs** [comment]
In face, the dae export dae doesn't hava textures,even if you ticked the copy texture tab.here is dae file link https://github.com/acfhs/model.git

**Comment by kimkulling** [comment]
I can confirm that the maja model is broken. Even in blender there is no model rendered. 

So I will close the issue.
