### ISSUE TITLE
Cannot download automatically assimp from an external camke project

### ISSUE THREAD

**Issue by Cherubin62** [assimp/assimp#2524]
Using the cmake command below, we get only an empty file !

	file(DOWNLOAD
		https://github.com/assimp/assimp/archive/v4.1.0.tar.gz
		${DEPENDENCIES_DIR}/assimp-4.1.0.tar.gz)

Do you if the path is correct or a mistype in the command ?

**Comment by kimkulling** [comment]
For me it looks ok. And the file is ok as well. Maybe full hd?
