### ISSUE TITLE
Link Error with Minimal Importers/Exporters Options

### ISSUE THREAD

**Issue by amreus** [assimp/assimp#2527]
Hi. Not sure if bug or me.  I am trying to build a minimal assimp shared library to link my code to. I disabled all exporters and importers, then add the STL importer back in. I change only the following options using `cmake-gui` with the VS 2017 x64 generator:

```
ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT:False
ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT:False
ASSIMP_BUILD_ASSIMP_TOOLS:False
ASSIMP_BUILD_STL_IMPORTER:True
ASSIMP_BUILD_TESTS:False
```
Using the command `cmake --build . --config Release` I get the following error:

```
Exporter.obj : error LNK2001: unresolved external symbol "void __cdecl Assimp::ExportSceneAssxml(char const *,class Assimp::IOSystem *,stru
ct aiScene const *,class Assimp::ExportProperties const *)" (?ExportSceneAssxml@Assimp@@YAXPEBDPEAVIOSystem@1@PEBUaiScene@@PEBVExportProper
ties@1@@Z) [C:\Users\Jim\Code\repos\assimp\build\code\assimp.vcxproj]
C:\Users\Jim\Code\repos\assimp\build\code\MinSizeRel\assimp-vc141-mt.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\Jim\Code\r
epos\assimp\build\code\assimp.vcxproj]
```

These 2 files are created but shouldn't there also be a shared library .dll created for my code to link to?
``
assimp-vc141-mt.exp
assimp-vc141-mt.lib
``
Thanks.

**Comment by kimkulling** [comment]
Fix is on its way. Thanks for the report!

**Comment by amreus** [comment]
Works, thank you!
