### ISSUE TITLE
Add support for Collada ZAE packaging

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#2539]
Collada 1.5.0 mandates support of a new packaging format "ZAE".

This is simply a ZIP containing the Collada DAE file, texture resources and a single "manifest.xml" file.

The manifest file contains an element `<dae_root>%colladafilepath.dae%</dae_root>`, eg:
```
<?xml version="1.0" encoding="utf-8"?>
<dae_root>./some_file.dae</dae_root>
```

Texture paths inside the Collada DAE are relative to the top of the ZIP, not the location of the DAE.

**Comment by kimkulling** [comment]
OK, thanks a lot for the information. Do you have an example file next to you :-) ?

**Comment by RichardTea** [comment]
I've started work on this, hopefully will have a pull request 'soon'.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2545
