### ISSUE TITLE
FBX should scale the root node automatically

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2542]
The cm to m option doesn't work and FBX rotation needs to done manually.

Here are some of the transforms, the rotation list isn't complete.

I may make a pull request for this.

[EDITED] This code should be in Matrix format.
[EDITED] Removed code

**Comment by Aidmx** [comment]
its better enum than int

**Comment by fire** [comment]
I have different results when I tested, the animation is rotated compared to the initial pose. Since this isn't the original bug I'll recreate.
