### ISSUE TITLE
Assimp will discard bone information of FBX if no mesh bind for it

### ISSUE THREAD

**Issue by roggiezhang** [assimp/assimp#2544]
Hi, 

I am trying to read all bone information (like offset matrix) of FBX from Assimp. However, I found it will only read those bones that has mesh binding. For those bone (subdeformer) that has not mesh binding, the offset matrix will not be kept. 

I want to understand if this is a bug or I can calculate offset matrix through existing information.

Thanks,
Lin

**Comment by kimkulling** [comment]
Hi,

just set AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES to FALSE and empty bone information will not be removed any more.

Kim

**Comment by roggiezhang** [comment]
From i got from the source code, set AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES to false will not generate any bone information. There is a code snippet like this:
if (ok && mRemoveEmptyBones) {
                        ConvertCluster(bones, model, *cluster, out_indices, index_out_indices,
                            count_out_indices, node_global_transform);
                    }

So if AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES  is set to false, no bones will be generated.

**Comment by roggiezhang** [comment]
@kimkulling Can you answer on this?

**Comment by hubbas** [comment]
I have the same issue. I have been fighting this for couple a days now. If I just call:
`ConvertCluster(bones, model, *cluster, out_indices, index_out_indices,
count_out_indices, node_global_transform);` it will keep the empty nodes so that they can be queried from the root node, but will still not be stored in `mBones`. AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES is broken :(

**Comment by roggiezhang** [comment]
@hubbas You need to remove all optimization flags also to keep the empty bones. I have tested it already.

**Comment by hubbas** [comment]
Thanks for you answer @roggiezhang!

I have tried that, and a variety of flag combinations but on certain fbx files it will still remove bones. I see that the FBXConverter code stores all the bones (if I run it with the above code to force it to keep empty bones), but after loading the scene it will only give the bones that have weights. Can I ask what format you're loading? If fbx what version in that case?

Maybe I can work around it someone. The thing is I'm using assimp to convert to my own file format and  if I somehow can get the information about the bones from the nodes instead that should be fine. Basically I need to know the skelton hierarchy, whether a bone is influencing vertices or not. Is there a way to get the type from the nodes? I see that the nodes store meta data but how do I know if a node is a bone for instance?

**Comment by roggiezhang** [comment]
@hubbas Assimp will ignore those bones that has no skinning. If you want to get those bones, I don't think you can get it as I had some time debugging on this. The way to judge if a node is a bone is that you have bone array in the scene, and you have node name. Then the node name will have one-one mapping to the bone name.

**Comment by roggiezhang** [comment]
@hubbas you'd better remove all flags. Here is an example of flags I set that works for me:
unsigned int ppsteps = aiProcess_LimitBoneWeights | // limit bone weights to 4 per vertex
        aiProcess_Triangulate |
        aiProcess_GenSmoothNormals;

    aiPropertyStore* props = aiCreatePropertyStore();
    aiSetImportPropertyInteger(props, AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_LINE | aiPrimitiveType_POINT);
    //aiSetImportPropertyInteger(props, AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, 0);
    aiSetImportPropertyInteger(props, AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES, 0);
    auto scene = (aiScene*)aiImportFileExWithProperties(assetPath, ppsteps, NULL,props);
    aiReleasePropertyStore(props);

**Comment by hubbas** [comment]
I already tried this but it will still not give me all the bones. Anyways I think I have a work around for now that might work. I might have a closer look into assimps code base when I have time and see if I can fix the issue with AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES removing all bones and the issue animation nodes not matching bone name (related to AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS I think).

**Comment by roggiezhang** [comment]
@hubbas Yes. Assimp will insert some nodes as a workaround for pivots which cannot be represented. You'd have to handle that by yourself.

**Comment by onurtore** [comment]
It looks like setting AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES to false does not solve the issue.

**Comment by kimkulling** [comment]
Not completly implemented for all importers, so I will reopen this issue.

**Comment by sascharo** [comment]
> It looks like setting AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES to false does not solve the issue.

Yeah, it doesn't solve it for me with the v6.0.2.
