### ISSUE TITLE
debone is removing valid bones

### ISSUE THREAD

**Issue by malytomas** [assimp/assimp#2547]
Hi,
I have an FBX file exported from blender with a simple mesh with 3 bones. Multiple vertices are affected by each bone, but each vertex is affected by one bone only. All bones have (at least) two keyframes.
When I add debone postprocessing flag, the bones are removed.
I think that if the bones have associated animation with more than one unique keyframes, they should be kept.
Can you please confirm if this is bug or intended behavior?
Thanks.
[spawner.zip](https://github.com/assimp/assimp/files/3390081/spawner.zip)

**Comment by fire** [comment]
In my experience assimp's blend shapes doesn't work with the deboner, but let me check.

**Comment by kimkulling** [comment]
I guess this shall fix this https://github.com/assimp/assimp/pull/2585

Please reopen if still there!

**Comment by malytomas** [comment]
I have just tried this and the issue remains.
The debone process seems to convert the SKELETAL animation into SHAPES animation? It splits the mesh into 3 separate objects.
Also I do not see a button to reopen the issue.

**Comment by mick-p1982** [comment]
I wrote "deboner". Its purpose is for lazy exporters that don't understand parenting meshes to nodes just export the meshes as a, very complicated by comparison, skeletal animation. I can't remember how it works but the idea is to undo this representation for meshes/animations that only use 1 as a vertex weight.

There are some options. I can't remember the specifics, like if it simply ignores animations that have non-1 weights anywhere. But this is the idea behind it: If not really a weighted skin animation then output a node animation.

**Comment by mick-p1982** [comment]
> 
> 
> In my experience assimp's blend shapes doesn't work with the deboner, but let me check.

I think to fix this MakeSubmesh just needs to be updated to cover aiAnimMesh/aiMesh::mAnimMeshes.

**Comment by mick-p1982** [comment]
> Can you please confirm if this is bug or intended behavior?

To be more clear, I think this is the intended behavior. The idea is the meshes should be animated without involving bones. That's why they are "deboned".

**Comment by malytomas** [comment]
> I wrote "deboner". Its purpose is for lazy exporters that don't understand parenting meshes to nodes just export the meshes as a, very complicated by comparison, skeletal animation. I can't remember how it works but the idea is to undo this representation for meshes/animations that only use 1 as a vertex weight.

Debone is an import option - it cannot be enabled for individual meshes only.
Instead, would it be possible to add additional option for the Deboner itself that would control the preference of skeletal vs shapes animations? In case of the preference for skeletal animations, the Debone postprocess would still apply to meshes with bones but without animations.

(My point is to reduce number of draw calls, even at the cost of skeletal animation.)

**Comment by mick-p1982** [comment]
> Debone is an import option

Yes? By "exporters" I mean the typically crummy export/import plugins people use to get their work out of modeling software's proprietary formats. Assimp didn't historically have any "exporters" but some were added later, maybe there are more now, but it's called Asset-Import-Library for a reason :)

> Debone postprocess would still apply to meshes with bones but without animations.

Bones are for animation, therefore meshes with bones are almost always animated. Debone removes weights from geometry that doesn't require them so they can be rendered without a matrix-palette style shader's overhead.
