### ISSUE TITLE
EXEC_BAD_ACCESS after attempt to import some COLLADA models

### ISSUE THREAD

**Issue by vfiloretov** [assimp/assimp#2548]
When I try to import [attack.dae](https://drive.google.com/file/d/1zUM2pYANWpnuiR_nqhbB0V1GD1V0UZ5S/view?usp=sharing) model I get EXEC_BAD_ACCESS.

![](https://i.imgur.com/obI0EmO.png)

It happens at some moment when pData.mValues.size() == 0 and we dereference pData.mValues[pos] in return statement. 

```
<source id="SID_64">
     <float_array id="SID_64-array" count="0"/>
     <technique_common>
      <accessor source="#SID_64-array" count="0" stride="1">
       <param name="WEIGHT" type="float"/>
      </accessor>
     </technique_common>
    </source>
```
I tried to investigate and found it. What you think about adding zero size check?

**Comment by kimkulling** [comment]
I found a solution for that bug. Pull request is under preparation.
