### ISSUE TITLE
Blender 2.8 files cannot be read

### ISSUE THREAD

**Issue by jankrassnigg** [assimp/assimp#2559]
.blend files written with Blender 2.8 (RC) fail to be read with latest assimp (5.0 RC1).

It outputs the error "expected at least one object without a parent".

Attached a simple file for reference, though I guess it won't work even with the most basic example.

[Drive.zip](https://github.com/assimp/assimp/files/3423189/Drive.zip)

**Comment by kimkulling** [comment]
Haven't start to investigate this issue, sorry. We need to update the database of blender for the job in assimp... Hard job :-)

**Comment by kimkulling** [comment]
As a workaround you can expport the model to Collada, or FBX, this shall work.

**Comment by kingdevnl** [comment]
@kimkulling Any updates to this?. Would love to use the .blend file as more advanced Material options etc.

**Comment by jankrassnigg** [comment]
I'm sure that if there where any update on this, they would post it here. The latest Blender version is in many ways a complete overhaul, I would expect it to take several weeks to months to figure out all the details and implement support for it, especially considering that most work is done in spare-time.

**Comment by C0re-Cheats** [comment]
any updates?

**Comment by kimkulling** [comment]
Start working on that. I have several issues describing this undefined behavior. I will use this one to track the issue: https://github.com/assimp/assimp/issues/3407
