### ISSUE TITLE
CM to M doesn't handle Animations, Lights, Cameras, etc.

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2561]
CM to M doesn't handle anything other than meshes.

There's no code for:

* Blendshapes
* Animations
* Lights
* Cameras

**Comment by fire** [comment]
https://github.com/assimp/assimp/blob/master/code/FBX/FBXConverter.cpp#L3561

This shows only the mesh's positions being transformed.

**Comment by RevoluPowered** [comment]
Resolved please close me.

**Comment by kimkulling** [comment]
Ok, I will do so!
