### ISSUE TITLE
INJECT_DEBUG_POSTFIX option is not working

### ISSUE THREAD

**Issue by panquez** [assimp/assimp#2567]
Hi, 

this issue is related to issues #2075 #620 .

I try to link with assimp on windows (VS19) in Debug. It seems there is a problem.

`CMake Error at build/third_party/assimp/install/lib/cmake/assimp-5.0/assimpTargets.cmake:85 (message):
    The imported target "assimp::assimp" references the file
       "D:/a/1/s/build/third_party/assimp/install/lib/assimp-vc141-mt.lib"
    but this file does not exist.  Possible reasons include:
    * The file was deleted, renamed, or moved to another location.
    * An install or uninstall procedure did not complete successfully.
    * The installation package was faulty and contained
       "D:/a/1/s/build/third_party/assimp/install/lib/cmake/assimp-5.0/assimpTargets.cmake"
    but not all the files it references.`

There is indeed no assimp-vc141-mt.lib, but assimp-vc141-mt**d** .

After having read the above issues and repo activities, I have found that the option INJECT_DEBUG_POSTFIX has had been added but it is unused.

In the assimp root CMakeLists.txt (l.344), one can see :

`IF (is_multi_config INJECT_DEBUG_POSTFIX OR (CMAKE_BUILD_TYPE STREQUAL "Debug"))
  SET(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Debug Postfix for lib, samples and tools")
ELSE()
  SET(CMAKE_DEBUG_POSTFIX "" CACHE STRING "Debug Postfix for lib, samples and tools")
ENDIF()`

In my case, is_multi_config is false but CMAKE_BUILD_TYPE STREQUAL "Debug" is true. That is why CMAKE_DEBUG_POSTFIX is set to "d". Even if INJECT_DEBUG_POSTFIX is set to false.

Instead, I propose you:

`IF (INJECT_DEBUG_POSTFIX AND (CMAKE_BUILD_TYPE STREQUAL "Debug"))
  SET(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Debug Postfix for lib, samples and tools")
ELSE()
  SET(CMAKE_DEBUG_POSTFIX "" CACHE STRING "Debug Postfix for lib, samples and tools")
ENDIF()`

I will propose a PR on that point.

What do you think of this? Have you any other idea?

Thanks again for your help and your work

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2568/
