### ISSUE TITLE
Can't locate index 61 on dynamic link library

### ISSUE THREAD

**Issue by FlashPanda** [assimp/assimp#2573]
![image](https://user-images.githubusercontent.com/29620260/62102631-398b1700-b2cc-11e9-8906-1dc56b342230.png)
I ran unit.exe on my computer which is win10. And I came to the problem above. The picture says Can't locate index 61 on dynamic link library "assimp-vc141-mtd.dll". I'm pretty sure that the dll is exist.
When I dump the dll, I got the result below.
![image](https://user-images.githubusercontent.com/29620260/62102800-e1084980-b2cc-11e9-81eb-966388cfc6f2.png)
It's really hard for me to solve the problem. Can anyone help? Thanks.

**Comment by FlashPanda** [comment]
One more thing, I compiled the project with vs2017.

**Comment by kimkulling** [comment]
Seems to be an issue with the openddl parser. Which unittest failes ( the console log would be useful. )

**Comment by kimkulling** [comment]
Shall be fixed now.
