### ISSUE TITLE
cmake failed for Visual Studio 2019 Win64

### ISSUE THREAD

**Issue by wd357dui** [assimp/assimp#2582]
Win32 is fine

Here's the prompt:

D:\Github\assimp-master_2019-8-7>cmake CMakeLists.txt -G "Visual Studio 16 2019" -A "Win64"
CMake Error at CMakeLists.txt:54 (PROJECT):
  Failed to run MSBuild command:

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

  用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.2.32702+c4012a063
  版权所有(C) Microsoft Corporation。保留所有权利。

  生成启动时间为 2019/8/7 13:22:45。
  节点 1 上的项目“D:\Github\assimp-master_2019-8-7\CMakeFiles\3.14.19060802-MSVC_2\VCTargetsPath.vcxproj”(默认目标)。
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\Github\assimp-master_2019-8-7\CMakeFiles\3.14.19060802-MSVC_2\VCTargetsPath.vcxproj]
  已完成生成项目“D:\Github\assimp-master_2019-8-7\CMakeFiles\3.14.19060802-MSVC_2\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

  生成失败。

  “D:\Github\assimp-master_2019-8-7\CMakeFiles\3.14.19060802-MSVC_2\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\Github\assimp-master_2019-8-7\CMakeFiles\3.14.19060802-MSVC_2\VCTargetsPath.vcxproj]

  0 个警告
  1 个错误

  已用时间 00:00:00.52

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "D:/Github/assimp-master_2019-8-7/CMakeFiles/CMakeOutput.log".

**Comment by kimkulling** [comment]
This seems to be an issue of cmake, just use it without the -A option will generate you the correct x64-project files.
