### ISSUE TITLE
LINK : fatal error LNK1189: library limit of 65535 objects exceeded

### ISSUE THREAD

**Issue by anandvsingh** [assimp/assimp#2586]
I am getting this error when I am building this in Debug Mode.

Environment: Windows 10 64 Bit.
Compiler : Microsoft (R) Build Engine version 14.0.27530.0 (Visual Studio 2015 update 3)

**Comment by malytomas** [comment]
```
/bigobj
```
Adding this flag will fix it.
But I do not know if it has any negative side effects.

**Comment by anandvsingh** [comment]
That worked on my machine thanks.

**Comment by malytomas** [comment]
Perhaps you could make a pull request with this flag?

**Comment by anandvsingh** [comment]
> Perhaps you could make a pull request with this flag?

Done.
