### ISSUE TITLE
PLY export has no color

### ISSUE THREAD

**Issue by nuernber** [assimp/assimp#2591]
Steps to Reproduce:
1. Download `https://github.com/assimp/assimp/blob/master/test/models/FBX/cubes_nonames.fbx`
2. Run `assimp.exe export cubes_nonames.fbx cubes_noname.ply`
3. Notice that the exported ply file has no colors.

Notes:
- `assimp.exe version` outputs `Version 4.1 -shared -st (GIT commit 0)`
- Exporting as an obj does export colors though.

**Comment by kimkulling** [comment]
This one shall be fixed in the latest release.
