### ISSUE TITLE
...mt.dll though /md compiled

### ISSUE THREAD

**Issue by RumbleballTheReal** [assimp/assimp#2594]
The resulting filename is always ...mt.dll ...mtd.dll, even if the Solution is set to build /md (which is also the default).

**Comment by RichardTea** [comment]
The generated solution and project files are throwaway temporary files, don't make changes there. They will not stick and won't necessarily have the desired effect.
(Aside from that, manually setting "/MD" in a solution wouldn't change the filename in a 'natively' MSVC project either.)

The filename suffixes and runtimes are specified by your cmake configuration.
The default for MSVC is "mt" for "Multi-Threaded" and "mtd" for "Multi-Threaded Debug" and to link to the multi-threaded DLL runtime.
"md" would be confusing, as the "d" suffix normally denotes a Debug version. DLLs can't be compiled "/MT"

To change suffixes and runtime you will need to change your cmake configuration _before_ generating the solution.

The "real" project files are CMakeLists, *.cmake and the settings you apply when running cmake.
I use a cmake cache file to set assimp the way my project needs.

**Comment by RumbleballTheReal** [comment]
@RichardTea Thank you. Thats some confusing stuff...
