### ISSUE TITLE
Proposal for scaling - also requesting feedback from assimp users

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2609]
We're working to improve the application pipeline in assimp for Godot.

**Basically we want to add the following option to the importer:**
- importer->set_application_scale( Units::M ) (pseudo code):

This means that if you have a "file scale" and a "unit scale" difference in your engine it will calculate the multiple of the scales required modelScale = applicationScale * fileScale before passing the scale to 'ScaleProcess'.

Other examples include (pseudo code):
- importer->set_application_scale( Units::CM )
- importer->set_application_scale( Units::FT )

if your file scale is CM and the application is in CM then no conversion should be done, but if a conversion is required, the importer would automatically compute this.

**My own concerns are as follows:**
- What should we do if ScaleProcess is disabled in assimp?
- Would this be useful for existing importers?

**Comment by RichardTea** [comment]
I don't think it should make any difference whether or not ScaleProcess is enabled.
Each assimp importer should still set the final scale factor that would be passed to ScaleProcess.

Some applications prefer to apply post-processing as a separate step to import, because they might undertake different post-processing depending on the content of the model, eg "magic node names" to indicate specific internal usage (map, pickup, actor etc)

This would certainly be useful for importing Collada, FBX and Blender.

Unfortunately many other formats don't have defined units at all, and it's probably optional for others.
It's important not to affect these - if the format or file does not specify an internal 'real world' size then the scale factor must not be changed.

**Comment by kimkulling** [comment]
At the moment all distances in Assimp are unitless. So we could introduce a default unit like Units::MM or Units::M. When the user wants to change that this proposal could be the way to go. 

Special for some CAD-formats like IFC or STEP ( where we get a lot of requests for ) this would be a nice option.

**Comment by RevoluPowered** [comment]
Personally I would prefer meters because that is what science uses across the board, but I'm not entirely sure what would be best to use long term.

Do we need to support imperial units or should we stick to metric?

**Comment by RevoluPowered** [comment]
> Unfortunately many other formats don't have defined units at all, and it's probably optional for others.
> It's important not to affect these - if the format or file does not specify an internal 'real world' size then the scale factor must not be changed.

To handle this I believe your solution is good. I think we should also add a warning if this is the case too. 

We can implement get_format_scale() which returns the file scale relative to meters, functions in the importer interface so that if a format implements it then it supports scaling to another size.

Anything which has **get_format_scale** implemented will handle the unit scale and not warn the user that their format has not defined units. Any scale process attempts will be allowed but it will have by default the 'file scale' set to 1.0 so it has no effect on the scaling process.

Prototype  example here - not finished still need to add scale process to handle this. also this really does no conversion this is just a example of the interface we could potentially use, feedback?
https://github.com/RevoluPowered/assimp/commit/6489488a428fb5e38194175f72f5f51fccbde005


Ideally we tell the users, where possible that we try to keep everything in the specified units where possible.

**Comment by RevoluPowered** [comment]
Might have found a cleaner way to do that just realized I can just move 99 percent all to base importer.

**Comment by RevoluPowered** [comment]
Prototype created: https://github.com/assimp/assimp/pull/2611

I still have to test it but you get the idea. Tried to also keep backward compatibility by adding new configuration option.

**Comment by kimkulling** [comment]
Merged, let's see how the users will work with it.
