### ISSUE TITLE
ScaleProcess test coverage

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2612]
I will look into implementing test coverage for the new scale process method as it was removed because you can't detect the scaling since the positions are scaled rather than the matrix scale values.

Probably just need to check node by node and ensure the transform position is x scale from the original within a tolerance.

**Comment by kimkulling** [comment]
Currently, the test coverage measurement is broken. And this topic will be tracked by a different issue report. 

So I will close this one.
