### ISSUE TITLE
Unable to build Assimp 

### ISSUE THREAD

**Issue by bubble8773** [assimp/assimp#262]
Hello,

Good Day! I have been trying to use assimp with opengl. I tried building the samples provided in the package on Visual studio 2012,  but it gives errors after setting the paths for include and lib files. 

>>Error	3	error MSB3073: The command "copy "C:\Assimp\samples\SimpleTexturedOpenGL\SimpleTexturedOpenGL\Debug\\SimpleTexturedOpenGL.exe" ..\..\bin
copy ..\..\..\bin\assimp_debug-dll_Win32\Assimp32d.dll ..\..\bin

>>:VCEnd" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets	134	5	SimpleTexturedOpenGL

>>Warning	2	warning MSB8012: TargetName(SimpleTexturedOpenGL) does not match the Linker's OutputFile property value (SimpleTexturedOpenGL_Debug). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets	1139	5	SimpleTexturedOpenGL

>>Warning	1	warning MSB8012: TargetPath(C:\Assimp\samples\SimpleTexturedOpenGL\SimpleTexturedOpenGL\Debug\SimpleTexturedOpenGL.exe) does not match the Linker's OutputFile property value (C:\Assimp\samples\SimpleTexturedOpenGL\SimpleTexturedOpenGL\Debug\SimpleTexturedOpenGL_Debug.exe). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets	1137	5	SimpleTexturedOpenGL

With lighthouse3d code for using Assimp and devil

>>'AssimpModelImport Demo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Assimp32d.dll'. Cannot find or open the PDB file.
The program '[10228] AssimpModelImport Demo.exe' has exited with code -1072365566 (0xc0150002).

>>Using Cmake with Nmake generator says: Project files are invalid.

Please help me regarding this.

Thank you, 
Nandita

**Comment by bubble8773** [comment]
Hello Kimmi, 

Good Day! Hope you are doing well.

I have tried to build and run SimpleTexturedOpenGL for assimp 3.11. on Visual studio 2013 and it happens to cause Unhandled exception at 0x77198F05 (ntdll.dll). Please advise in this regard.

Thank you, 
Nandita

**Comment by kimkulling** [comment]
Hm, sounds like a mismatch of used runtimes. Did you used the VS2013-prebuild binaries?

Kimmi

**Comment by bubble8773** [comment]
No I had used the ones from the sdk (bin32 , bin64).

Thank you, 
Nandita

**Comment by kimkulling** [comment]
Normally these SDK is compiles with a special runtime + compiler. You must use the same one to get it running. Normally this is visible via the name of the SDK or via its containing folder. Can you please check if you are using the same compiler as the SDK?
