### ISSUE TITLE
Badly written config files

### ISSUE THREAD

**Issue by forry** [assimp/assimp#2625]
Hi,
I've tried master branch and also v5 rc2 tag with both cmake 3.14.6 and 3.15.2 trying to make build for MSVC 2019 x64. I'm trying to use assimp via the config in other application using standard cmake aproach with find_package and then link with target assimp::assimp. There is few problems I've encountered:
1. You generate *targets-debug.cmake even if no one wants to build debug version of assimp, thus making the application cmake failing on not finding the debug lib file. Preffered approach would be to generate the targets-* config only when building the targets (the default cmake behaviour for best practise).
2. In assimpTargets.cmake line 54 under # Create imported target assimp::assimp; you use ON/OFF value but the policies for this behaviour are not set correctly (policies are for version 2.6) so even ON resolves in false thus the application tries to link with the .dll instead of implib because of how targets in cmake works.
3. Even after handily hacking through that there is targets-* line 86 which do get_filename_component(ASSIMP_ROOT_DIR <INSTALL_PREFIX> REALPATH). If the <INSTALL_PREFIX> is the usual win path with backwards slashes the cmake fails here. Also note that with the config files generated by cmake (not from your templates) there is no problem with using system native path strings.

There is where I've stop investigating. I would suggest, that you use standard cmake approach for generating config files (best practices, without templates) or somehow adjust your templates and test them on windows. 

Cheers, forry

**Comment by kimkulling** [comment]
This sounds really bad, thanks for the detailed report. The cmake-system has grown over the last couple fo years and so we have some technical dept here. 

I will mark this issue as a techdept-story.
