### ISSUE TITLE
Gltf Crash Material Property

### ISSUE THREAD

**Issue by RumbleballTheReal** [assimp/assimp#2627]
WHY?

gltfexporter.cpp    

void GetMatScalar(const aiMaterial* mat, float& val, const char* propName, int type, int idx) {
        **ai_assert**(mat->Get(propName, type, idx, val) == AI_SUCCESS);
    }

**Comment by kimkulling** [comment]
This looks like a typo, I doesn't make any sense to have this in the assertion test.

**Comment by kimkulling** [comment]
See: https://github.com/assimp/assimp/pull/2654
