### ISSUE TITLE
Enable 'Rolling builds' to speed up AppVeyor tasks

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2629]
I don't know if 'Rolling builds' have been enabled for assimp project.
Based on AppVeyor documentation [here](https://www.appveyor.com/docs/build-configuration/):

> Whenever you do a new commit to the same branch OR pull request all current queued/running builds for that branch or PR are cancelled and the new one is queued. Other words, rolling builds make sure that only the most recent commit is built.
...
Note that “Rolling builds” can only be enabled in the settings UI of a project and not via appveyor.yml and that the presence of appveyor.yml does not disable this UI setting.

I think that they are useful but I can't verify if they are enbaled or not.

**Comment by kimkulling** [comment]
Thanks for the hint, this feature is enabled now!
