### ISSUE TITLE
Starcraft 2 M3 model support

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#263]
I just looked at the Assimp page after years of not touching it, and it seems like the M3 support is still considered beta, and yet I don't see it at all in the github repo.

Just in case it interests anyone, I wrote specs largely based on other people's work but cleaner and with explanations on how things work.
You can find them here: http://www.hiveworkshop.com/forums/programming-714/m3-specifications-243127/
In addition, you can check an actual implementation of all my notes in my WebGL viewer, though it might be a little messy: https://github.com/flowtsohg/mdx-m3-viewer/tree/master/src/viewer/m3

Cheers.

**Comment by tellypresence** [comment]
M3 support removal explains load failure for
`test/models-nonbsd/M3/Bunker.m3`

**Comment by tellypresence** [comment]
Commit [`88da17a`](https://github.com/assimp/assimp/commit/88da17a24624c6014b2a72f27710650c6c997640) removed StarCraft `.m3` support
