### ISSUE TITLE
Assimp v5.0.0 rc2 undefined reference to when linking with project using MinGW

### ISSUE THREAD

**Issue by congard** [assimp/assimp#2632]
OS: Windows 10
MinGW: x86_64-8.1.0-posix-seh-rt_v6-rev0
Message: Just "undefined reference to WhatIUse"
```
undefined reference to `Assimp::Importer::Importer()'
undefined reference to `Assimp::Importer::~Importer()'
undefined reference to `Assimp::Importer::ReadFile(char const*, unsigned int)'
```
And so on. With Assimp v5.0.0 rc1 everything links fine

**Comment by kimkulling** [comment]
Ok, thanks a lot for the bug-report!

**Comment by JekaS178RUS** [comment]
Same as here https://github.com/assimp/assimp/issues/2431?

**Comment by kimkulling** [comment]
So the issue has occurred on RC2, is that correct?

**Comment by congard** [comment]
Yes, on RC2

**Comment by congard** [comment]
With 5.0.0 release the same situation

**Comment by kimkulling** [comment]
Still open?

**Comment by congard** [comment]
@kimkulling will check tomorrow

**Comment by congard** [comment]
It seems that now everything ok on Windows, but new issue with bones appears on both Windows and Linux
