### ISSUE TITLE
Problem with assimp skeletal animation in opengl

### ISSUE THREAD

**Issue by WildFire212** [assimp/assimp#2635]
I am facing problems with setting up skeletal animation in opengl using assimp.
The transformations are going wrong somehow. 
Pls help..

[AnimatedModel.h.txt](https://github.com/assimp/assimp/files/3574407/AnimatedModel.h.txt)
[Bone.h.txt](https://github.com/assimp/assimp/files/3574409/Bone.h.txt)
[GBufferAnimationShader.txt](https://github.com/assimp/assimp/files/3574410/GBufferAnimationShader.txt)
[mat4.cpp.txt](https://github.com/assimp/assimp/files/3574411/mat4.cpp.txt)
[mat4.h.txt](https://github.com/assimp/assimp/files/3574412/mat4.h.txt)
[AnimatedComponent.cpp.txt](https://github.com/assimp/assimp/files/3574413/AnimatedComponent.cpp.txt)
[AnimatedComponent.h.txt](https://github.com/assimp/assimp/files/3574414/AnimatedComponent.h.txt)
[AnimatedModel.cpp.txt](https://github.com/assimp/assimp/files/3574415/AnimatedModel.cpp.txt)

**Comment by congard** [comment]
Just in case: before including `glm` try to add `#define GLM_FORCE_CTOR_INIT`

**Comment by WildFire212** [comment]
thank you for the quick reply!
But it wont work even after adding #define GLM_FORCE_CTOR_INIT 
![animationbug](https://user-images.githubusercontent.com/33984831/64349590-ddc35480-d014-11e9-9883-c198d1546ce7.PNG)

**Comment by WildFire212** [comment]
the final bone transforms matrix array that i am passing to the shader is not correct.
However i am not able to find a flaw..

**Comment by RevoluPowered** [comment]
@WildFire212 
This may help you out it's good reference material
http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html

**Comment by kimkulling** [comment]
The calculation of the bone transforms looks right. But I havn't tested if the translations, rotations and scalings are right. And I saw that you have used an animation duration of 25.0f. Get this scaled correctly when the duration of animation stored in the animation is taken into account as well?

Just an idea!

**Comment by kimkulling** [comment]
Closed, please reopen the issue if your topic is still open.
