### ISSUE TITLE
STL File Size

### ISSUE THREAD

**Issue by JuandreG** [assimp/assimp#2651]
Hello!

I'm having issues exporting STL files. This is my test scenario.

I have a STL file with a file size of byte[6228484]. I use the Assimp ImportFileFromStream method to create a scene from the byte array. This all works perfectly fine.

I then want to, without making any changes to the scene, export it again using the Assimp ExportToBlob method. This also works fine but when the export is complete the byte array size is byte[32527525]. This is a whole lot bigger than the initial byte array.

Am I missing something, why is the file so big?

**Comment by JuandreG** [comment]
I had a look through the supported formats and found stlb, when I passed this as the formatId in the Assimp ExportToBlob method it worked perfectly.

Thanks for this great library!

**Comment by kimkulling** [comment]
Thanks a lot for the nice works!
