### ISSUE TITLE
Clang formatting

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2652]
Any chance we can start using clang-format?

I don't need it for every file, but it would be nice if new contributions could optionally include files formatted using clang-format.

It really cleans up files, we use it in godot and it's quite simple.

**Comment by kimkulling** [comment]
Do you measn include it into the CI?

**Comment by RevoluPowered** [comment]
I was considering that we could add it to the CI for only changed files, so that anything edited must be updated but anything which is not touched can remain the same, so we don't get huge commits with thousands of files changed.

It would be up to you but I would really like to enforce it because we can get much cleaner code in the long run.

**Comment by RevoluPowered** [comment]
the only hard part to this is picking a style guide

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

The LLVM standard is probably what I would use, this is what godot uses and it's pretty simple. Most tools support clang-format.

**Comment by RevoluPowered** [comment]
I would also recommend we update the C++03 to C++11.

**Comment by kimkulling** [comment]
This should be the case already!

**Comment by RevoluPowered** [comment]
do you mind if I add it an PR it after I do the update?

**Comment by kimkulling** [comment]
For the clang-formatter? Sure

**Comment by kimkulling** [comment]
Closed and fixed.
