### ISSUE TITLE
FBX-Tokenize

### ISSUE THREAD

**Issue by Destranix** [assimp/assimp#2653]
I'm getting

> FBX-Tokenize (offset 0x23) block offset is out of range

when loading a FBX-File.

Newest tested commit: 69265273

I attached a .zip with one file working and one not.

transparentTest.fbx: not working
transparentTest2.fbx: working
Difference: Removed two objects and three materials. One material using emissive Colors, one using a normal map, another one smimiliar to materials contained in the working file.

Tested with following code:

```
#include <stdio.h>
#include <assimp/cimport.h>
#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <assimp/version.h>

int main(){
	unsigned int flags = 0;

const struct aiScene* scene = aiImportFile("transparentTest.fbx", flags);

	fprintf(stderr, "%s\n", aiGetErrorString());

printf("%p %u %u %#x\n", (void*) scene, aiGetVersionMajor(), aiGetVersionMinor(), aiGetVersionRevision());
fflush(stdout);

aiReleaseImport(scene);
return 0;
}
```

Tested on Linux, but does also not work in LWJGL on Windows at commit c1d95aaa

[Files.zip](https://github.com/assimp/assimp/files/3609410/Files.zip)

**Comment by kimkulling** [comment]
Samke behaviour on windows. The first file is broken. But I get the same behaviour when I try to import it via blender.

**Comment by kimkulling** [comment]
For me it looks like a broken file. The tokenizer checks the size for the token and this value looks like not setup correctly.

**Comment by Destranix** [comment]
That might be possible. I used Maya 2014 when creating and exporting the File. I'll do some more tests.

**Comment by Destranix** [comment]
Reexporting fixed the problem, sorry for stealing your time, I've simply overlooked possible Maya exporting errors.

**Comment by kimkulling** [comment]
Not to worry, thanks for the test!

Destranix <notifications@github.com> schrieb am So., 15. Sep. 2019, 12:12:

**Comment by tellypresence** [comment]
Just to clarify, I believe the problematic .fbx file is the bundled one:
`test/models/FBX/transparentTest.fbx`

Can verify I get the same error when attempting to load this bundled file:
    `FBX-Tokenize (offset 0x23) block offset is out of range`
