### ISSUE TITLE
segfault with blend-file

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#2657]
During some routine-tests, I found that assimp-4.1.0 (as packaged in Debian), segfaults with some blend-files (see attachment):

[model.zip](https://github.com/assimp/assimp/files/3621835/model.zip)

The code to trigger the problem is trivial:

~~~C
#include <assimp/cimport.h>
#include <stdio.h>

int main(int argc, char**argv) {
  int i;
  for(i=1; i<argc; i++) {
     const struct aiScene*s = aiImportFile(argv[i], 0);
     if(s)aiReleaseImport(s);
  }
  return 0;
}
~~~

I haven't tried whether the current HEAD fixes the problem.

**Comment by umlaeute** [comment]
sidenote: the model comes from [morse-simulator](http://morse-simulator.github.io/), which packaged in Debian and comes under a BSD-3 clause license.

It can be obtained from [github](https://github.com/morse-simulator/morse/blob/2239cbaed7a2d506c4de5b2d3b719667b98e5a5b/data/environments/human_tut/tutorial_scene.blend).

Blender crashes on the file as well.
However, this is probably no excuse for crashing assimp...

**Comment by umlaeute** [comment]
ah, it seems that with assimp5 (current git HEAD) the problem has been fixed.

sorry for the noise.

**Comment by kimkulling** [comment]
No problem, thanks to you for helping us with the information!
