### ISSUE TITLE
zlib build issues - mostly on Mac

### ISSUE THREAD

**Issue by MarkCallow** [assimp/assimp#2673]
2 issues with the zlib build:

1.  The library's install name on macOS is not being set to an @rpath based name leading to the warning `MACOSX_RPATH is not specified for the following targets` from the CMake generator.
2. Even if `BUILD_SHARED_LIBS` is unchecked the warning in no. 1 appears, suggesting CMake is still trying to build zlib as a shared library.

With Xcode 11 urging use of hardened runtime, which requires signed libraries, fixing no. 1 is important. Until such time as all libraries built by Brew or MacPorts are signed the only recourse is to copy the libraries into one's app bundle and sign them. For `dyld` to load them after copying, their install names must be `@rpath/<libname>.dylib`.

Does libminizip get built as well as libz when ASSIMP_BUILD_ZLIB is checked?

To work around the issues for now I am building a static libassimp and linking my app with that and static libminizip and libz from my MacPorts installation.

**Comment by RichardTea** [comment]
What reasons are there not to use the system zlib on Mac?

I've always used the system zlib on Mac (and Linux) as I can be sure it's up-to-date and signed (where necessary)

**Comment by kimkulling** [comment]
I guess the most annoying issue regarding the MAC is the fact that I do not have this platform available for testing.

**Comment by MarkCallow** [comment]
> What reasons are there not to use the system zlib on Mac?

- libassimp has a dependency on libminizip and well as libz. As far as I can tell the former is not included in the macOS system libs.
- When installing libassimp via MacPorts it pulls in its dependencies - mentioned above - meaning those libraries appear in /opt/local/lib. I expect Brew does similar.
- -L/opt/local/lib on the compile command, to find libassimp, means that directory is searched before the system directories.

So unless you take special steps, e.g. explicitly refer to /usr/lib/libz.dylib early in the link command you're going to get the MacPorts built version.

**Comment by kimkulling** [comment]
Shall work right now.
