### ISSUE TITLE
Building assimp 4.0.1 with Visual studio 2017 and Cmake

### ISSUE THREAD

**Issue by PuscasuRobert** [assimp/assimp#2682]
After running the following 2 commands in cmd (the words inside quotes are placeholders):

cd "new build directory"
cmake.exe "assimp directory"

I got a VC project, opened it with Visual studio 2017, pressed right click on ALL_BUILD and then pressed Build, these are the following errors i got:

https://drive.google.com/file/d/1mvxh5zQGZUP8CiZDYV4kf6masRE8mA1J/view?usp=sharing

Whats going on here? Im on Windows 8 64 bit.

**Comment by brownvikki16** [comment]
I'm having the same issue with the most recent master version of assimp. I keep getting the "cannot open file 'assimp-vc140-mt.lib' " message even though I'm using assimp-vc142-mt.lib. All my includes and directories are correct. I'm not sure what's going on.

**Comment by PuscasuRobert** [comment]
brownvikki16 

I found a work around. I wanted to use assimp 4 for the GLTF loader. So i just used assimp 3.3 and the .fbx loader. .fbx has all the features GLTF has, except that i doesnt remember the texture paths. So i just wrote them in code.

**Comment by kimkulling** [comment]
Have you tried tha latest master?

**Comment by PuscasuRobert** [comment]
> Have you tried tha latest master?

No, i just used assimp 3.3 and coded a workaround.

**Comment by kimkulling** [comment]
Please try the latest master and reopen the issue when the issue still exists. Unfortunately I do not have the resources to help you with this old version.

Sorry for beeing such a troublemaker!

Kim
