### ISSUE TITLE
FBX Load Access Violation 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by Mikez2015** [assimp/assimp#2686]
OS - Windows 7x64, VS 2019 x64
After I installed VS 2019 and recompiled lastest assimp libraries, I got this error:

https://drive.google.com/file/d/1QFnf4sUOpIJmJHmgRZ9lwmBRta3erHaA/view?usp=sharing

With VS 2017 everything worked without errors.

**Comment by Mikez2015** [comment]
I am sorry, my mistake!!! I forgot update includes.

**Comment by Mekriy** [comment]
Молодець
