### ISSUE TITLE
v5.0.0, aiGetVersionMajor() returns 4

### ISSUE THREAD

**Issue by Opioid** [assimp/assimp#2693]
According to git I am building v5.0.0-15-g09d80ff4, but aiGetVersionMajor() still returns 4. Am I not actually building the newest version or is this number just out of sync?

**Comment by mosra** [comment]
@kimkulling I just ran into this as well -- in [magnum](https://magnum.graphics) I have to do various workarounds / data patching based on Assimp version used and this omission effectively makes version 5 indistinguishable from 4.1.
