### ISSUE TITLE
Proposal - Allow building without exporters.

### ISSUE THREAD

**Issue by lukediamond** [assimp/assimp#2707]
While using the library solely for importing mesh files, I tried to disable all exporters to save compile time and lower binary size. Without adding exporters, however, the array
```cpp
Exporter::ExportFormatEntry gExporters[] = { ... };
```
will be empty, which raises an error of the form 'cannot allocate an array of constant size 0'.

To produce this error exactly as I have:
```bash
# in the root project directory
mkdir build
cd build
cmake -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF ..
cmake --build .
```
By adding an empty exporter definition, such as 

```cpp
void ExportEmpty(const char*, IOSystem*, const aiScene*, const Assimp::ExportProperties*) {}
...
Exporter::ExportFormatEntry gExporters[] =
{
    Exporter::ExportFormatEntry( "empty", "Empty format - no-op", "", &ExportEmpty ),

    ...
};
```
the library could be build minimally, solely for importing meshes. This exporter could potentially be used as an "unknown" format exporter.

**Comment by kimkulling** [comment]
Will be closed by https://github.com/assimp/assimp/pull/2759

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2759
