### ISSUE TITLE
aiImportFile,unable to open file

### ISSUE THREAD

**Issue by ysu341** [assimp/assimp#2713]
scene = aiImportFile(filepath,aiProcessPreset_TargetRealtime_MaxQuality);

I had try this base on(windows),is working.
Now on (ubuntu 18.04   qt5.1.1),   scene = null,   unable to open file。
the file is .stl,the  filepath  is right.
I don't why,  it's troubled me a lot.
can you help me?
thansk。

**Comment by RichardTea** [comment]
Linux filenames are case-sensitive. Perhaps you are using the wrong CaPitaliSation in your filename.

There isn't enough information in this report to offer any useful guidance, the above is a wild guess.

**Comment by ysu341** [comment]
thanks a lot,i had found my fault. 



在 2019-11-17 05:21:20，"Kim Kulling" <notifications@github.com> 写道：


Closed #2713.
