### ISSUE TITLE
glTF UV flipping and corruption in 5.x.x vs 4.x.x

### ISSUE THREAD

**Issue by ardenpm** [assimp/assimp#2718]
After switching to 5.0.0 I'm seeing the V component of UV coordindates in glTF files are getting flipped. When creating a test case to reproduce I also seem to see more general UV corruption.

I've attached a simple OBJ file with a UV test pattern. To reproduce convert to glTF using the assimp.exe program like so:

`assimp export box.obj box.gltf`

In 4.1.0 I see the correct result, like this:

![image](https://user-images.githubusercontent.com/5742686/67066561-d6b86600-f1be-11e9-9b38-87f682700d19.png)

However in 5.0.0 I am getting this:

![image](https://user-images.githubusercontent.com/5742686/67066575-e3d55500-f1be-11e9-9227-c8ae39197939.png)

I'm not sure why this one shows corruption rather than a simple flip of the V component which is what I see on more complex models.

There is explicit code for flipping the V component in the exporter, which is correct since that is required for glTF, however that code has not changed between the versions tested above and a quick look through the diffs doesn't reveal anything obvious that would cause this.

[box.zip](https://github.com/assimp/assimp/files/3742351/box.zip)

**Comment by ardenpm** [comment]
It seems my test case is actually exposing a different bug in the OBJ importer. I did a `git bisect` session and tracked that to commit 9a533d826ad6f880ded45c801d2a022f6d9e4f68 which changes the way UVs are read from OBJ files. I believe that should be filed as a separte bug. In the meantime I will now devise a new test to try and reproduce this issue so I can run another bisect and find it.

**Comment by ardenpm** [comment]
Ok, another bisect session now and I have isolated the issue to commit 3d0775eebc0f2a86b87752385782e9b90c83279f and it seems to be related to vertex joining somehow. Will dig deeper now that I have an exact commit.

**Comment by ardenpm** [comment]
This issue is that commit 3d0775eebc0f2a86b87752385782e9b90c83279f introduced a duplicate call to the exporter, so basically the whole exporter was being called twice. This seems to create issues due to the complex handling of pre-processing flags, verbose scenes and other aspects which I don't really understand. Either way I assume the exporter should be be being called twice so I will submit a pull request to remove that.

Looks like this may have came about due to mismatching indentation so it wasn't so easy to spot the duplicate line.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2782
