### ISSUE TITLE
assimpTargets.cmake issue on Linux

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#2719]
the cmake-configuration for 3rd-party consumers is somewhat broken on Linux.

I'm currently preparing the Debian packages for assimp-5.0.0, and test-compiling 3rd-party software (`ros-*`) that uses assimp/cmake now fails.

I narrowed it down to cmake to being able to find the `libassimp.so.5` file (which of course is present on the system).

- assimp's cmake configuration is installed into `/usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/`
- assimp's shared library  is installed as `/usr/lib/x86_64-linux-gnu/libassimp.so.5`

- `assimpTargets.cmake` [calculates](https://github.com/assimp/assimp/blob/v5.0.0/assimpTargets.cmake.in#L44-L48) the `_IMPORT_PREFIX` as `/usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/../../../` which in the end resolves to `/usr/lib`: https://github.com/assimp/assimp/blob/v5.0.0/assimpTargets.cmake.in#L44-L48

- for shared-lib builds on non-windows systems, a file-check is added for `${_IMPORT_PREFIX}/lib/${sharedLibraryName}`, which really resolves to `/usr/lib/lib/libassimp.so.5`: https://github.com/assimp/assimp/blob/v5.0.0/assimpTargets-release.cmake.in#L79

- since there is no `/usr/lib/lib/libassimp.so.5` file (esp. note the `/lib/lib`) , any call to `find_package(ASSIMP)` fails :-(

**Comment by umlaeute** [comment]
I don't really know much CMake, but it seems to me that the proper path to search for `libassimp.so.5` would be `ASSIMP_LIBRARY_DIRS` instead.
So for now, I will just change https://github.com/assimp/assimp/blob/v5.0.0/assimpTargets-release.cmake.in#L79 to:

~~~cmake
list(APPEND _IMPORT_CHECK_FILES_FOR_assimp::assimp "${ASSIMP_ROOT_DIR}/@ASSIMP_LIB_INSTALL_DIR@/${sharedLibraryName}" )
~~~

**Comment by umlaeute** [comment]
see https://salsa.debian.org/debian/assimp/blob/master/debian/patches/cmake.patch for the full patch.

The patch is of course a bit hack-and-slash, as we only need to care about "proper" installations.

**Comment by vmatare** [comment]
Why not just use [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) and get rid of all this hackery that breaks down on every other corner?

**Comment by kimkulling** [comment]
Is in, good luck!
