### ISSUE TITLE
CMake configuration broken for windows

### ISSUE THREAD

**Issue by jherico** [assimp/assimp#2721]
The `assimpTargets-release.cmake` and `assimpTargets-debug.cmake` configuration files generated in a windows build for a shared library configuration are broken.  

When I use the CMake find and target functions

    find_package(assimp CONFIG REQUIRED)
    target_link_libraries(${TARGET_NAME} PRIVATE assimp::assimp)

It causes the linker to use the DLL filename as the link input, not the import filename.  See image below:

![image](https://user-images.githubusercontent.com/1533642/67115097-3f3d1e00-f192-11e9-934e-050f77ae505c.png)

This in turn causes the link to fail

> 2>D:\ezvcpkg\fa7a3eaec35409d60dbc456d5229b54c192f11de\installed\x64-windows\bin\assimp-vc142-mt.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x300

I'm unable to determine why this is happening.

**Comment by kimkulling** [comment]
Ok, I will close the issue.
