### ISSUE TITLE
Assimp Documentation

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2730]
I think we need to start documenting the importer quirks better for longevity of our importers.

We can then detail the importer and exporter features in a clean manner, give code examples and hopefully help assimp users along the way.

Even a theme on the exiting docs would be a good step like the godot theme:
https://docs.godotengine.org/en/3.1/

**Comment by kimkulling** [comment]
I opened a Read-The-Docs repo for that. I tried my really best for a side-project.
