### ISSUE TITLE
Dropping suport for VS2013 compiler

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2735]
Can we please get rid of the older VS compilers, we should not support these anymore as we have in more than one case had to update code to support their issues?

For example:
- https://github.com/assimp/assimp/issues/2423
- https://github.com/assimp/assimp/issues/2678

It decreases code quality and our tests obviously can't catch the flaws in the compilers, If projects do not support modern compilation suites or tool-chains that is not our problem.

The modern VS compiler is better at handling templates etc, so I don't see any practical need to keep having to workaround it's issues when the devs can update their toolchain to fix the bugs with C++11.

**Comment by kimkulling** [comment]
I do agree with compilers older than 2013. But there is one point which are still in use of customers.

So for me VS2013 is the linit. I will drop this compiler in the next two years.
