### ISSUE TITLE
Unable to detect StingrayPBS material from FBX

### ISSUE THREAD

**Issue by DrNoodles** [assimp/assimp#2740]
The PBR workflow is a standard game technique yet the assimp support for it is incredibly difficult to use, and in my case, I can't figure it out at all.

Do you have a Maya file, or tutorial, outlining the process of correctly setting up a StingrayPBS material so that Assimp detects it?

Here's what I tried:
1. Created a mesh in Maya.
2. Applied a StingrayPBS material to the mesh.
3. Added and enabled a TEX Color Map, TEX Normal Map, TEX Roughness Map and TEX Metallic Map. 
4. The mesh draws as expected in the Maya viewport.
5. Exported the FBX.
6. Confirmed the FBX exported correctly by importing it back into a new Maya scene.
7. Imported FBX with Assimp, and iterated through all materials and all textures.
8. No textures are detected.

```
static void DumpMaterialsToConsole(const aiScene& scene)
{
	const auto dump = [](const aiMaterial& mat, aiTextureType type)
	{
		const unsigned count = mat.GetTextureCount(type);
		if (count > 0)
			std::cout << "  type:" << type << " count:" << count << std::endl;
	};

	for (unsigned i = 0; i < scene.mNumMaterials; i++)
	{
		const aiMaterial& mat = *scene.mMaterials[i];
		std::cout << "mat:" << i << " has..." << std::endl;
		dump(mat, aiTextureType_NONE);
		dump(mat, aiTextureType_DIFFUSE);
		dump(mat, aiTextureType_SPECULAR);
		dump(mat, aiTextureType_AMBIENT);
		dump(mat, aiTextureType_EMISSIVE);
		dump(mat, aiTextureType_HEIGHT);
		dump(mat, aiTextureType_NORMALS);
		dump(mat, aiTextureType_SHININESS);
		dump(mat, aiTextureType_OPACITY);
		dump(mat, aiTextureType_DISPLACEMENT);
		dump(mat, aiTextureType_LIGHTMAP);
		dump(mat, aiTextureType_REFLECTION);
		dump(mat, aiTextureType_BASE_COLOR);
		dump(mat, aiTextureType_NORMAL_CAMERA);
		dump(mat, aiTextureType_EMISSION_COLOR);
		dump(mat, aiTextureType_METALNESS);
		dump(mat, aiTextureType_DIFFUSE_ROUGHNESS);
		dump(mat, aiTextureType_AMBIENT_OCCLUSION);
		dump(mat, aiTextureType_UNKNOWN);
	}
}
```

_Originally posted by @DrNoodles in https://github.com/assimp/assimp/pull/2640#issuecomment-548649922_

**Comment by DrNoodles** [comment]
An update on this, it's still broken. 

Considering this is the new standard workflow for game art I highly recommend assimp double down on making the PBR workflow function and write some tutorials as a high priority. As it stands this library is only good for old fashioned art pipelines.

In my i've just tacked on my own PBR texture loading support separate to assimp altogether.

**Comment by ifiddynine** [comment]
I submitted a PR that fixes this here: https://github.com/assimp/assimp/pull/3293

I agree with your comment above about lack of combined workflow support, that would be really good to have.
