### ISSUE TITLE
bug on .x loading algorithm

### ISSUE THREAD

**Issue by usagi** [assimp/assimp#275]
.x file has like a this occured exception from Assimp::Importer::ReadFile.

exception: `Line 887: Semicolon expected.`

```
  SkinWeights {
   "Parent";
   0;
   ;
   ;
   1.000000,0.000000,0.000000,0.000000,
   0.000000,1.000000,0.000000,0.000000,
   0.000000,0.000000,1.000000,0.000000,
   0.000000,0.000000,0.000000,1.000000;; # <-- this is the line 887
  }
```

The bug can avoid rewrite .x file below, now:

```
  SkinWeights {
   "Parent";
   1;
   0;
   0;
   1.000000,0.000000,0.000000,0.000000,
   0.000000,1.000000,0.000000,0.000000,
   0.000000,0.000000,1.000000,0.000000,
   0.000000,0.000000,0.000000,1.000000;;
  }
```

I'm glad when you can fix assimp for this problem.

**Comment by kimkulling** [comment]
Was not able to reproduce the issue. PLease reopen when you can provide a small reproducable issue.

**Comment by naota29** [comment]
Hello,

I would like to re-open this issue as I am able to reproduce it.  Please see the attached zip which contains a .x file that reproduces the issue. 

[test.zip](https://github.com/assimp/assimp/files/9539100/test.zip)

I generated this file using the [ModelConverterX](https://www.scenerydesign.org/modelconverterx/) software.  I imported the "text.x" file that comes with the assimp repo in the assimp\test\models\X directory.  I then exported this same file from that software in the .x format.  After doing this, assimp no longer imports it, and gives me an error stating "Line 574: Semicolon expected."  

I can, however, still view this file in the ModelConvertX software and by using DirectX rendering tools.

Thank you,

Justice
