### ISSUE TITLE
Documentation needs to be updated to new format

### ISSUE THREAD

**Issue by nic-hartley** [assimp/assimp#2756]
For example:

![`@link` and `@endlink`](https://user-images.githubusercontent.com/4331760/68519932-2dffa280-0262-11ea-8601-5d6a3528d816.png)
![`<b>`](https://user-images.githubusercontent.com/4331760/68519966-5ab3ba00-0262-11ea-8717-a8ae08470df1.png)
![`#` to link functions](https://user-images.githubusercontent.com/4331760/68520001-92226680-0262-11ea-865d-f2a2598ce50c.png)

I'm not sure what the last format was, but it needs to be converted to Markdown or RST (the formats that ReadTheDocs support)

**Comment by RevoluPowered** [comment]
Good point! Yeah I am going to work on improving the docs at some point, do you think you could help us out by submitting some PRs with documentation help? :)

**Comment by kimkulling** [comment]
Is fixed.
