### ISSUE TITLE
X file importer delivers wrong node names

### ISSUE THREAD

**Issue by AdmiralPellaeon** [assimp/assimp#2763]
Hi,

I switched from assimp 4.1 to 5.0. With the new version my program didn't work right anymore. It seems that the new version doesn't provide to correct names/ids from the X file.

I use mName.data of aiNode to get the name. The first id seems correct, but later nonsense strings are delivered.

**Comment by kkulling** [comment]
Hi,

could you please provide an example which helps us to reproduce the issue?

Thanks,
Kim

**Comment by AdmiralPellaeon** [comment]
Hello Kim,

yes, attached you will find an X file and a screenshot, where you can see
that the name given by assimp differs from the name in the X file (I marked
it red in the image)



PS:

Hallo Kim,

laut Website seit ihr ja deutsche, daher wollte ich den Sachverhalt auch
nochmal schnell in deutsch tippen.
Die neue Version scheint die Knotennamen nicht richtig einzulesen. Bei der
angehangenen Dateui schneidet er wie man in dem Bild sieht vorne Buchstaben
weg. Bei einer anderen Datei (die kann ich aus Datenschutzgründen leider
nicht mitschicken) kommt gar kein richtiger String, da steht quasi nur
Müll. Daher tippe ich auf einen Zeigerfehler irgendwo.

Ich würde ja gerne selbst reindebuggen, aber die CMAKE-generierte Solution
lässt sich von meinem Hauptprogramm aus nicht debuggen, trotz das die PDB
vorhanden ist ... . Aber das ist eine andere Baustelle^^

VG



Am Do., 14. Nov. 2019 um 16:31 Uhr schrieb kkulling <
notifications@github.com>:

**Comment by kimkulling** [comment]
Sorry, I guess the file is missing :-) ...

Stimmt, bin deutsch!

**Comment by AdmiralPellaeon** [comment]
![screen](https://user-images.githubusercontent.com/11961230/68999254-7fd9a580-08be-11ea-8b7d-f41bf86a342c.jpg)
[t1.zip](https://github.com/assimp/assimp/files/3854723/t1.zip)

here are the files :)

**Comment by AdmiralPellaeon** [comment]
Are there any news regarding this issue?

**Comment by turol** [comment]
On Linux `assimp info` tells me:

```
Meshes:  (name) [vertices / bones / faces | primitive_types]
    0 (Frame_t1_inner): [96 / 0 / 51 | line]
    1 (Frame_t1_inner): [1964 / 0 / 2002 | triangle]
    2 (Frame_t1_outer): [129 / 0 / 70 | line]
    3 (Frame_t1_outer): [2206 / 0 / 2242 | triangle]

Named Materials:
    't1_inner'
    't1_outer'

Node hierarchy:
Frame_World
└╴Frame_Tool_T1
  ├╴Frame_t1_inner (mesh 0, 1)
  └╴Frame_t1_outer (mesh 2, 3)
```

Looks good to me. No issues with ASAN or UBSAN. Are you sure your program doesn't somehow corrupt the heap?

**Comment by AdmiralPellaeon** [comment]
In Debug mode, VS would recognize a corrupt heap in most cases. When using assimp 4.1.0 the all works fine, but with 5.0.0 I got these broken node names

**Comment by turol** [comment]
@AdmiralPellaeon What does `assimp info` give you, for both 4.1.0 and 5.0.0?

**Comment by AdmiralPellaeon** [comment]
OK, it seems to be a problem with the stack. I debugged into assimp and inside I have the following data for one specific child node:

0x00000203a56b51a0 {0x00000203a57d9040 {mName={length=38 data=0x00000203a57d9044 "233430002030_Arbeitsraum_PWC_f_PCS_iam" } ...}}

And after the return of "ReadFile" from the AssimpImporter teh values are the following:

0x00000203a56b51a0 {0x00000203a57d9040 {mName={length=3761406403625877542 data=0x00000203a57d9048 "30002030_Arbeitsraum_PWC_f_PCS_iam" } ...}}

The addresses of the scene object and of the child node are identical, but inside of the child node suddenly the content is broken.
I suppose it's some configuration problem, wrong defines or something like that?

**Comment by AdmiralPellaeon** [comment]
Ok, is there some new alignment stuff or similar things in assimp 5, which wasn't in version 4?
I took the size if aiScene in my program, it is 120 Byte. But within the assimp dll it is 128 byte. So the binary pattern, especially of the aiString class, is different, what leads to my problems.

**Comment by turol** [comment]
I think `mMetaData` member was added between versions 4 and 5. Looks like you've got something out of date in your program.

**Comment by AdmiralPellaeon** [comment]
I use Assimp 5 how I downloaded it from the git repository. I didn't mix assimp 4 and 5. And I only create an instance of the AssimpIMporter, set some properties and call "ReadFile", thats all:

m_importer = std::make_shared<Assimp::Importer>();
if (use_int)
{		
	m_importer->SetProgressHandler(new InterruptHandler());
}
m_importer->SetPropertyInteger(AI_CONFIG_PP_RVC_FLAGS,constants::importer_config_props);
auto p_scene = m_importer->ReadFile(file,constants::importer_read_props);

I didn't see where something of my code should be "out of date". Therefore the question if there is some alignment stuff in assimp which is new. Because my Visual studio solution has default configurations, nothing extraordinary. So I think this problem is also relevnat for other VS users.

**Comment by turol** [comment]
On 64-bit Linux the size of `aiScene` is 128 bytes. I think it should be the same on MSVC. Since `mMetaData` is 8 bytes removing it would bring `aiScene` to 120 bytes. So it looks like you're somehow using an old header instead of the current one or you have an errant `#pragma pack` somewhere.

**Comment by AdmiralPellaeon** [comment]
Ok, shame on me, I didn't know how it happend but it seems there were some old header files. I always rename the old directory to prevent undesired mixing of the directories. But after deleting all files and creating it new, it seems to work.

Thanks for your help and your patience!
