### ISSUE TITLE
Error importing file: FBX-DOM (TOK_KEY, offset 0x30ff) expected at least 3 tokens: id, name and class tag

### ISSUE THREAD

**Issue by 13704017891** [assimp/assimp#2767]

**Comment by kimkulling** [comment]
PLease provide more detaile information about you issue. Then we can try to help you here. Thanks!

**Comment by 13704017891** [comment]
FBXMaterial.cpp    shading is "unknown"   .  and There was no such issue in the previous version

**Comment by 13704017891** [comment]
@kimkulling
