### ISSUE TITLE
Most meshes are missing

### ISSUE THREAD

**Issue by 13704017891** [assimp/assimp#2768]
This model has about twenty meshes, but only two of them are read

**Comment by 13704017891** [comment]
[hulan.txt](https://github.com/assimp/assimp/files/3858301/hulan.txt)
This is an FBX file, please change the format and test

**Comment by kimkulling** [comment]
Thanks for the report. I will have a look!

**Comment by RichardTea** [comment]
I get this in both MS Paint3D and via Assimp:
![image](https://user-images.githubusercontent.com/31507749/70253806-d6c6f200-177b-11ea-84f0-d0e41daa89c7.png)

**Comment by kimkulling** [comment]
This issue seems to be outdated.
