### ISSUE TITLE
Need list of supported glTF extensions on assimp 

### ISSUE THREAD

**Issue by singhraj82** [assimp/assimp#2774]
Is there any documentation that describes the supported extensions for glTF based on the information listed here : https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md ?

I am mainly interested in knowing if MSFT_lod is supported with assimp v5.0.0 release or not?

**Comment by kimkulling** [comment]
At the moment for glTF2.0 the following extensions are supported:
- KHR_lights_punctual ( 5.0 )
- KHR_materials_pbrSpecularGlossiness ( 5.0 )
- KHR_materials_unlit ( 5.0 )
- KHR_texture_transform ( 5.1 under test )

**Comment by singhraj82** [comment]
Thank you.
