### ISSUE TITLE
Optimisation is enabled in debug build targets on Visual Studio

### ISSUE THREAD

**Issue by ardenpm** [assimp/assimp#2785]
I was having all sorts of odd issues debugging and it took me a while to work out the debug builds in Visual Studio (I tested 2013 and 2015) from solutions generated with CMake and using the 'Debug' build target have optimisation turned on, which completely breaks debugging.

Not sure if this is related to #2625. I am not very experienced with CMake so am not sure of why this occurs, a quick look through the CMake files showed options to disable optimisation for debug builds but it seems they are not being applied.

Unclear whether this affects Linux or not as I did not test there.

**Comment by RevoluPowered** [comment]
When you build in MSVC can you please do a clean rebuild and send across the build log file?

**Comment by ardenpm** [comment]
[build.log](https://github.com/assimp/assimp/files/3894061/build.log)

![image](https://user-images.githubusercontent.com/5742686/69673788-3de70580-10ef-11ea-9d00-938c42f148a0.png)

**Comment by kimkulling** [comment]
I guess this is just a bug in the debug-specific cppflags setting in the CMake-configuration.

I will check that.
