### ISSUE TITLE
[glTF 2.0] Crash when loading Draco compressed files

### ISSUE THREAD

**Issue by ardenpm** [assimp/assimp#2791]
Currently Assimp will very likely crash or encounter undefined behaviour if a glTF has Draco compression enabled and required. While Draco is not supported (hopefully at some point we'll have that see #2195), in the meantime Assimp should likely check if `KHR_draco_mesh_compression` is present in the `extensionsRequired` array.

The specification states that if only Draco data is provided (it is possible to have a file with both compressed and uncompressed data) then the extension must be listed in `extensionsRequired`. So looks like it would make sense to explicitly check for this and throw and error if encountered for now to avoid crashes.

It may be worth exposing the `extensionsRequired` array in some fashion so callers can determine for themselves for other extensiosn whether they are able to support them, since it may depend on the engine it is coming into.

**Comment by ardenpm** [comment]
Just to note, that was worded poorly, actually the specification says that if `KHR_draco_mesh_compression` is set in `extensionsRequired` then the file must contain *only* Draco data. So this basically means for a compliant file right now if it is in `extensionsRequired` is is guaranteed not to load in Assimp. So this should definitely be checked.

**Comment by kimkulling** [comment]
I guess supporting the Draco-compression is a  good idea!
