### ISSUE TITLE
 Potentially contradictory information in the documentation of aiNodeAnim.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#2793]
According to Assimp's documentation (see anim.h, line 269). The description of aiNodeAnim says the following:

>The transformation matrix computed from these values replaces the node's original transformation matrix at a specific time. This means **all keys are absolute and not relative to the bone default pose**.

From my understanding, I believe the original transformation refers to aiNode's **mTransformation**. According to (scene.h, line 110), it is said that mTransformation should be **relative to it's parent transformation**, which means local space I believe.

Unless I did not correctly read/understand the documentation, the two statements above appear to be contradictory. Please, can anyone confirm this?

Thanks.

**Note**: I did a quick verification by loading an MDL5 model using the following [project](https://github.com/ccxvii/asstools).  The model renders correctly. Inspecting the source code (assview.c lines 500 to 513), the mTransformations are replaced by transformation matrices calculated from the corresponding animated transforms, and are then concatenated with each parent's transform.

**Comment by kimkulling** [comment]
Both documentation string are true. We are using local transformations in our node hierarchy and we are using offset matrices, which describes the transformation of a specific node relative to its root to save computation time.
