### ISSUE TITLE
MSVC 2019 building error C2678

### ISSUE THREAD

**Issue by beckylum0216** [assimp/assimp#2794]
Hi Everyone,

I am having trouble trying to build my project on Clion, using MSVC 2019 version 16. The build fails on scene.h:

    //! Check whether the scene contains meshes
    //! Unless no special scene flags are set this will always be true.
    inline bool HasMeshes() const { 
        return mMeshes != NULL && mNumMeshes > 0; 
    }

With this error message:

    C2678: binary '!=': no operator found which takes a left-hand operand of type 'const 
    std::vector<double,std::allocator<_Ty>>' (or there is no acceptable conversion)
        with
        [
            _Ty=double
        ]

**Comment by kimkulling** [comment]
Which version of asset-importer-lib do you use. scene.h is using nullptr instead of NULL. And mMeshes is a raw pointer for the c-api, not anything else.

**Comment by beckylum0216** [comment]
I used assimp_5.0_release

**Comment by kimkulling** [comment]
Shall be fixed, please reopen the issue-report if you still have this issue.
