### ISSUE TITLE
Homebrew pkg-config issue assimp 5.0

### ISSUE THREAD

**Issue by ctreffs** [assimp/assimp#2804]
The current package of assimp available via homebrew seems to have an issue in it's pkg-config file.

Specifically the include path seems to be formed wrong.

I'm testing this on macOS Mojave 10.14.6 (18G2016) with HOMEBREW_VERSION: 2.2.0 and the latests formulae.

The last version of `assimp.pc` looked like this:
```sh
prefix=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0
exec_prefix=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/
libdir=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/lib
includedir=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 4.1.0
Libs: -L${libdir} -lassimp
Libs.private: -lstdc++ -lz
Cflags: -I${includedir}

```
whereas the current file looks like this:

```sh
prefix=@@HOMEBREW_CELLAR@@/assimp/5.0.0
exec_prefix=@@HOMEBREW_CELLAR@@/assimp/5.0.0/
libdir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/lib
includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/../include/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 5.0.0
Libs: -L${libdir} -lassimp
Libs.private: -lstdc++ -lz
Cflags: -I${includedir}
```

The change that causes the issue is the following line:
`includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/../include/include`
which imo should look like this:
`includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/include`

I am willing to help to resolve this issue if someone could point me in the right direction where to update what :-)

---

I created a related issue in the homebrew issue tracker: https://github.com/Homebrew/homebrew-core/issues/47405

**Comment by fxcoudert** [comment]
The change is an intentional choice by upstream: see https://github.com/assimp/assimp/commit/b506d35999edcec448b71fa3545f937b9f04dcc2

This should be fixed by `assimp`. The path they write is wrong, and not only for Homebrew, but for any install that sets `CMAKE_INSTALL_PREFIX`.

**Comment by ctreffs** [comment]
Hi,
any updates on that topic?

**Comment by kimkulling** [comment]
Yes, I found the issue. I am just trying to figure out how to fix it.

**Comment by ctreffs** [comment]
If I can be of any assistance let me know

**Comment by kimkulling** [comment]
Closed by the pull request.

**Comment by ctreffs** [comment]
Hi,

sadly with assimp 5.0.1 the problem still persists and moreover the pkg-config file provides the wrong version in the description.

```
prefix=/usr/local/Cellar/assimp/5.0.1
exec_prefix=/usr/local/Cellar/assimp/5.0.1/
libdir=/usr/local/Cellar/assimp/5.0.1/lib
includedir=/usr/local/Cellar/assimp/5.0.1/../include/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 5.0.0
Libs: -L${libdir} -lassimp
Libs.private:  -lz
Cflags: -I${includedir}

```
The `includedir` property should look like this:
 `includedir=/usr/local/Cellar/assimp/5.0.1/include`
and the package version should obviously be 5.0.1 rather than 5.0.0.
