### ISSUE TITLE
Possible failure in VertexTriangleAdjacency constructor(Quick Fix)

### ISSUE THREAD

**Issue by Jonander98** [assimp/assimp#2806]
![imagen](https://user-images.githubusercontent.com/33396880/70086895-93517400-1613-11ea-9fcd-f8a8f527fa08.png)
If the number of vertices is not given, it is not calculated properly as vertices go from [0,n) so, if we get 150 after the for loop, it means that we have 151 vertices. I don't think any code uses the class without passing the vertex count, but it could cause problems in the future.

**Comment by kimkulling** [comment]
Thanks for the investigation, this pull-request will close this one: https://github.com/assimp/assimp/pull/2867
