### ISSUE TITLE
Error while loading a specific  IFC file in both Assimp viewer and Helixtoolkit.SharpDX.Assimp

### ISSUE THREAD

**Issue by JordanOlivet** [assimp/assimp#2809]
Hello guys,

I'm using Helixtoolkit.SharpDX.Assimp (AssimpNet) in order to load IFC files and build a 3D scene.
All my IFC files are loaded fine but one (see attachment at the end of the post).

I got an exception "Error importing file: vector<T> too long".

During my investigations in Helixtoolkit code, I found that the exception occured on AssimpContext.ImportFile.

![exception](https://user-images.githubusercontent.com/46482319/70237173-d6702c00-1766-11ea-8485-dad147cc8998.png)

I thought that maybe it's only an issue with AssimpNet and not with Assimp.
So, to be sure I checked out the Assimp repository and try to load my file in the Assimp viewer.

And again, I got an exception :
![assimpviewer](https://user-images.githubusercontent.com/46482319/70237549-c1e06380-1767-11ea-96ba-9bd6faedc576.png)

And when I click "Retry" ("Recommencer" in french) the debugger stops here :

![debugger](https://user-images.githubusercontent.com/46482319/70238465-978fa580-1769-11ea-8fc0-9ed32d50ba06.png)

Someone have an idea or a clue on how to make this file loading correctly ?
Maybe I'm missing something ?
Or is it a bug ?

Thanks in advance for any response.

(I link my initial issue on Helixtoolkit repo : https://github.com/helix-toolkit/helix-toolkit/issues/1269)

[ifc_file.zip](https://github.com/assimp/assimp/files/3926812/ifc_file.zip)

**Comment by kimkulling** [comment]
I will check!

**Comment by kimkulling** [comment]
Fix is on its way.

**Comment by JordanOlivet** [comment]
Wow, what a reactivity !

Thanks a lot !

**Comment by JordanOlivet** [comment]
Just one last question @kimkulling =).

When do you think this fix will be apply to AssimpNet and available in Nuget ?

Thanks again !

**Comment by kimkulling** [comment]
I will need to release a new version.

**Comment by kkulling** [comment]
Then we need to update AssimpNet and the nuget-packages, will take some time.

**Comment by JordanOlivet** [comment]
Ok, no problem.

Thanks a lot !
