### ISSUE TITLE
 __abort_with_payload () with Xcode on macOS, most likely a dylib issue

### ISSUE THREAD

**Issue by ShuchangXu** [assimp/assimp#2812]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/19888693/70285414-61eacb00-1802-11ea-9649-f802a3e5bbae.png">

**Description:**

 Hello, I'm trying to use ASSIMP with Xcode on macOS. I built the binaries from source and have linked the `libassimp.dylib` with my project. 

However, I got this error  `__abort_with_payload ()` whenever I run my project. No further details are provided but this error is most likely caused by something wrong in dylib. I have tried to install both `Assimp 3.1.1` and `Assimp 5.0.0`, but this error occurs for both versions.

I didn't quite know how to fix this, and I sincerely hope this issue will be addressed. Thanks!

**Environment specification:**
```
macOS 10.15.1
Xcode 11.2.1
Assimp(Both 3.1.1 & 5.0.0 were tried.)
```

**Reproducing Procedure:**

1. Inside Assimp folder (i.e., `Assimp-5.0.0`, or `Assimp-3.1.1`), run the following commands:
```
mkdir build
cd build
cmake ..
make
sudo make install
```
This will generate Assimp header files inside `/usr/local/include`, and dylib file in `/usr/local/lib`.

2. In `Build Settings`, add `/usr/local/include`(non-recursive) in header search paths, and `/usr/local/lib`(non-recursive) in library search paths.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/19888693/70286110-d32b7d80-1804-11ea-9fe8-62fccc1f5bbe.png">

3. Add `libassimp.dylib` to `Frameworks and libraries`.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/19888693/70286032-86e03d80-1804-11ea-9465-444b1021c674.png">

**Comment by ShuchangXu** [comment]
Only 2 blogs were found similar to (but not same with) this problem. Here's the link for reference:

[Xcode，assimp dylib：__abort_with_payload](https://answer-id.com/48474115)
[Xcode, CMake: установка и подключение assimp dylib, ошибка __abort_with_payload](https://ru.stackoverflow.com/questions/776350/xcode-cmake-установка-и-подключение-assimp-dylib-ошибка-abort-with-payload?rq=1)

**Comment by RichardTea** [comment]
As I understand it, on macOS you _should_ embed all (non-Apple) dylibs and frameworks, and for iOS targets you **must** embed.

Try adding (all of) the 3rd-party dylibs into the "Embedded Binaries" section and removing them from "Frameworks and Libraries".

XCode seems to deliberately do exactly the wrong thing at least some of the time.

You may also need to do some magic with "install_name_tool".
- XCode is _supposed_ to handle that, but in my experience it seems to be broken every couple of updates and I end up having to manually add it to the post-build steps for reliability.

Sadly, sometimes it really does feel like Apple don't want anybody developing software for their platforms.

**Comment by kimkulling** [comment]
Maybe this post can help you as well: https://stackoverflow.com/questions/42027601/dyld-abort-with-payload-with-no-error-message
