### ISSUE TITLE
Invalid ASSIMP_Boost_VERSION in assimp-config.cmake

### ISSUE THREAD

**Issue by bchretien** [assimp/assimp#282]
While trying to build ROS's [geometric_shapes](https://github.com/ros-planning/geometric_shapes) on Arch Linux, I had the following error with assimp 3.1 (it used to work with assimp 3.0):

```text
...
-- Boost version: 1.55.0
-- Found the following Boost libraries:
-- system
-- filesystem
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:429 (message):
When requesting a specific version of Boost, you must provide at least the
major and minor version numbers, e.g., 1.34
Call Stack (most recent call first):
/usr/lib64/cmake/assimp-3.0/assimp-config.cmake:54 (find_package)
CMakeLists.txt:13 (find_package)


-- Could NOT find Boost
```
The investigation led me to assimp-config.cmake (lines 47/48), provided by Arch Linux's community package (version 3.1):

```cmake
# the boost version assimp was compiled with
set( ASSIMP_Boost_VERSION ".")
```

I guess this is supposed to be automatically set when compiling assimp, but it was apparently not (FYI, the build script for the assimp package is available [here](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/assimp), cc @svenstaro). This should be "1.55" on Arch. Still, this was also the case before, but the `if (WIN32)` check has been removed in https://github.com/assimp/assimp/commit/d49837819edbf5eab94293a6646783bab57e0a0c, so now CMake fails in:

```cmake
find_package(Boost ${ASSIMP_Boost_VERSION} EXACT COMPONENTS thread date_time)
```
I suppose a check should be added before that.

Report on Arch Linux's bug report system: https://bugs.archlinux.org/task/40491
AUR bug report for ROS: https://aur.archlinux.org/packages/ros-hydro-geometric-shapes/

**Comment by kimkulling** [comment]
Already fixed.
