### ISSUE TITLE
Large FBX File: Token list takes a long time to deallocate in Visual Studio.

### ISSUE THREAD

**Issue by andr3wmac** [assimp/assimp#283]
I'm using an FBX file which is ~10MB in size. It doesn't work in assimp however I'm using it to test error handling in the engine I've integrated assimp into. When using either release or debug mode and running the application from inside Visual Studio (confirmed in 2008, and 2012) it takes roughly ~5 minutes to delete the list of 1.5 million tokens. This is true when running assimp_view from visual studio as well. However, running either release or debug version outside of visual studio seems to handle the operation in roughly 1-2 seconds.

The line in question that takes so long to execute is:
https://github.com/assimp/assimp/blob/master/code/FBXImporter.cpp#L184

The specific file that causes the problem is not licensed to be posted on here so let me know if you need it and I can email it to you. I've tried other large models and this issue appears to be isolated to the FBX importer.

**Comment by kimkulling** [comment]
Seems to be outdated. Tried it again and performance was not too bad. Reopen if this is still an issue.
