### ISSUE TITLE
Crash on export, version 5.0.0

### ISSUE THREAD

**Issue by alessandroAM** [assimp/assimp#2831]
Hello, I'm trying to export my aiScene (which worked correctly with assimp 4.1.0); I get a crash every time that the aiScene is prepared and the export function it's called. I subclassed aiScene and the constructor looks like this:

```
customAiScene::customAiScene()
{
    mFlags = 0;
    mRootNode = NULL;
    mNumMeshes = 0;
    mMeshes = NULL;
    mNumMaterials = 0;
    mMaterials = NULL;
    mNumAnimations = 0;
    mAnimations = NULL;
    mNumTextures = 0;
    mTextures = NULL;
    mNumLights = 0;
    mLights = NULL;
    mNumCameras = 0;
    mCameras = NULL;
    mPrivate = NULL;
    exporter = new Assimp::Exporter();
    int n = exporter->GetExportFormatCount();
    for (int i = 0; i < n; i++) {
        const aiExportFormatDesc* formatDescription = exporter->GetExportFormatDescription(i);
        wxString sDesc = wxString::FromUTF8(formatDescription->description);
        wxString sExt = wxString::FromUTF8(formatDescription->fileExtension);
        wxString sID = wxString::FromUTF8(formatDescription->id);
        MyApp::showMessage(wxString::Format(wxT("export format: %s,%s,%s"), sDesc, sExt, sID), "l");
    }
}
```
Later on, after setting the data, I export the scene:

`exporter->Export(this, exportFormatDesc, filePath);`

As I said, with a assimp 4.1.0 it is working correctly (but I need FBX export hence the reason for the change). Also, DefaultLogger shows no errors or warnings of any kind.
Thanks for any help.

**Comment by turol** [comment]
Can you create a standalone, ready-to-compile test program which exhibits this bug?

**Comment by alessandroAM** [comment]
Hi turol, I'll make one and post it... Thanks

**Comment by kimkulling** [comment]
Great, thanks a lot!

**Comment by alessandroAM** [comment]
Obviously a clean app works like a charm, so nothing wrong with assimp I suppose :)
In any case, I'm attaching the VS2015 C++ solution (that works) if anybody needs a quick one to test import/export: [www.alessandromastronardi.com/downloads/assImpConsoleApplication.zip](url)
My main application that presents the issue is based on wxWidgets, so I'm now going to try and understand what causes the issue, and report.
I suppose maybe it's one of the compiler settings. Thanks for now!

**Comment by alessandroAM** [comment]
Hello, it was an error on my end, some extra face indices that weren't supposed to be there! 
Assimp 4.1.0 didn't complain and exported a working obj, while 5.0.0 would crash. Cheers.
