### ISSUE TITLE
Attempt to load bundled bvh test models triggers immediate crash

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2834]
In my implementation, the three .bvh models bundled with assimp:
    test/models/BVH/01_01.bvh
    test/models/BVH/01_03.bvh
    test/models/BVH/Boxing_Toes.bvh
all fail to load with errors e.g.
```
models/BVH/01_01.bvh:2940 - Unexpected end of file while trying to read a float
models/BVH/Boxing_Toes.bvh:3200 - Unexpected end of file while trying to read a float
models/BVH/01_03.bvh:4699 - Unexpected end of file while trying to read a float
```
Wondering if anyone else has found these models to be problematic?

**Comment by turol** [comment]
They load for me with `assimp info` on Linux. What OS and compiler are you using? Does the `assimp` tool work?

**Comment by tellypresence** [comment]
Building native lib for android using modern NDK/clang.  Since they work for you, I've probably
got a misconfigured build, so will need to investigate why the .bvh format
specifically is failing to load -- thank you

**Comment by kimkulling** [comment]
Just checked it here, worked for me on Windows. Android is currently not in our test-suite, sorry!

**Comment by tellypresence** [comment]
The 3 .bvh models load OK now, think there was a problem in my code -- apologies
