### ISSUE TITLE
Is JT supported?

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2835]
Sorry if this is a dumb question; have been going through all the test models bundled with this repo to check stability of my implementation and noticed the `JT` folder with `conrod.jt`.  But, in my case I get error "No suitable reader found for the file "test/models/JT/conrod.jt"

So, not sure if JT support
- was never implemented
- was at one time implemented, but since removed
- or (always likely) I have a misconfigured build etc. and don't get this feature

Again apologies if this is obvious, thank you

**Comment by kimkulling** [comment]
This format is currently under development.

**Comment by tellypresence** [comment]
Looks like a start was made but abandoned (https://github.com/assimp/assimp/pull/2860), just wanted to check if this feature is on the roadmap or on hold?
