### ISSUE TITLE
[obj] scene is null with given obj

### ISSUE THREAD

**Issue by elect86** [assimp/assimp#2840]
Hi,

I have the following files (`.obj` and `.mtl`) and it looks they cant be loaded properly by assimp.

Ps: our jvm assimp port crashes at `ObjFileMtlImporter::load` whenever is trying to load the diffuse color (`Kd`) because the `model.currentMaterial` is `null`

[car.zip](https://github.com/assimp/assimp/files/3977734/car.zip)

**Comment by turol** [comment]
Loads for me with `assimp info` on Linux with recent master. No errors with Valgrind either. Can you create a standalone program which exhibits the problem?

**Comment by elect86** [comment]
Shit, it works on mine too, I was passing a wrong path.. sorry for the bothering!
