### ISSUE TITLE
GLTF v2 with Sketchfab Models and Animations

### ISSUE THREAD

**Issue by Neosettler** [assimp/assimp#2844]
Greetings,

I've been experimenting with Sketchfab models that contains animations but Assimp 5.0 aiScene::HasAnimations is always false. Importing the model below into Blender shows that the animations are exporter properly from Sketchfab.

https://sketchfab.com/3d-models/ironman-arc-reactor-with-sound-d87547f21f904cfa954f4cf77a1409ac

Am I missing something?

**Comment by kimkulling** [comment]
I don't have a clue. We need to investigate,

**Comment by Neosettler** [comment]
Thank you for your response. Actually, I found that the pre-transform vertices flag did obliterate the animations so, false alarm.

**Comment by kimkulling** [comment]
Ok, I will close the issue. Thanks a lot for your update.
