### ISSUE TITLE
Add Half-Life 1 MDL file format documentation to official wiki.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#2854]
Recently, changes to add support to load Half-Life 1 MDL files have been [merged](https://github.com/assimp/assimp/pull/2838).

Additionally, I recommend that you also add the [Half-Life 1 MDL file format](https://github.com/malortie/assimp/wiki/MDL:-Half-Life-1-file-format) documentation to the wiki of the official Assimp Github.

**Comment by kimkulling** [comment]
You are completly right: see https://github.com/assimp/assimp/wiki/MDL-Half-Life-1-Format !

Thanks again for your great work!
