### ISSUE TITLE
Possible corrupt test model archive

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2857]
Having difficulty extracting
`test/models-nonbsd/AMF/3_bananas.amf.7z`

Possibly corrupt archive file?

**Comment by kimkulling** [comment]
Yes, this one is broken, thanks for the hint!

**Comment by turol** [comment]
Broken by 165f0f0548356eb071e62deb810a55f6b99b8884

**Comment by tellypresence** [comment]
Confirm the reverted archive extracts OK, thank you
