### ISSUE TITLE
.md2 "file is too small" errors

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2861]
Just wondering if anyone else is having this problem:
`test/models-nonbsd/MD2/flag.md2` loads OK, but
* `test/models-nonbsd/MD2/dolphin.md2`
* `test/models-nonbsd/MD2/horse.md2`
fail with
`File is too small` error

**Comment by kimkulling** [comment]
Same here, thanks for the report. Maybe the models are broken.

**Comment by turol** [comment]
Yet another one broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by tellypresence** [comment]
Can confirm that both
```
test/models-nonbsd/MD2/dolphin.md2
test/models-nonbsd/MD2/horse.md2
```
now load OK, thank you
