### ISSUE TITLE
Ply Exporter doesn't correctly write faces with 0 vertices

### ISSUE THREAD

**Issue by Dunni** [assimp/assimp#2864]
If a face has 0 vertices, the ply exporter doesn't write an endline after writing the number of indices. This means that the line with an empty face gets concatenated with the following line. 
This then causes the face count in the header to be inaccurate and causes a ply parser reading the exported ply file to crash unexpectedly.
I've created a PR here(#2863) that should address this issue.

**Comment by kimkulling** [comment]
Thanks for the problem-report. And thanks for the pull-request as well.

I will merge it.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2863.
