### ISSUE TITLE
IFC Importer : Can't find mesh for IfcOpeningElement node

### ISSUE THREAD

**Issue by JordanOlivet** [assimp/assimp#2869]
Hello guys,

After importing an IFC file, I would like to walk through the scene graph generated in order to read meshes.

But it appears that no IfcOpenenigElement's node possess mesh. The logical element representing the IfcOpeningElement is there but without any mesh.

Is it normal ? Or maybe I don't do something correctly ?

I searched in Assimp code if I can find any clue but I am not very good at C++ ...

Do you have any idea of how can I retrieve IfcOpeningElement geometry/mesh ?

FYI : I don't use Assimp directly. I use HelixToolkit, that uses Assimp.Net, that uses Assimp. But I think it's not a problem. If I have a way to go, I can probably adapt it for my needs.

Thanks in advance,
Jordan Olivet

**Comment by kimkulling** [comment]
The opening-elements will be used to generate holes into the mesh and cut the vertices out. Then the hole will triangulated.
At the moment I am trying to find a way to keep these information in the aiScene somehow as an option. In the past most assimp-users were only intestested in getting the render data out of the model, not the curve-information.

**Comment by JordanOlivet** [comment]
Sorry for the late response and thanks @kimkulling for yours.

I'm using Assimp in order to load an IFC file, display it but also create a 2D view of this file.
In this whole process, I can be lead to hightlight IfcOpeningElement in the 3D view or draw them in my 2D view (by user selection).

That's why I need the geometry of IfcOpeningElements.

Anyway, I hope you'll manage to keep these informations in the AiScene in order to retrieve them later.

My hopes are with you =).

Thanks,
Jordan Olivet
