### ISSUE TITLE
EmbedTexturesProcess leaks memory

### ISSUE THREAD

**Issue by mabuchner** [assimp/assimp#2874]
The `EmbedTexturesProcess` class allocates new memory for `pScene->mTextures`, but doesn't deallocate the old memory:

https://github.com/assimp/assimp/blob/7b17cb8ddb57eeafb99b5a0de83ea2fc86c7fe67/code/PostProcessing/EmbedTexturesProcess.cpp#L129

**Comment by kimkulling** [comment]
Thanks a lof for the finding, fix is on its way!
