### ISSUE TITLE
Invisible test collada models

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2888]
When I load models
```
models/Collada/earthCylindrical.dae
models/Collada/teapots.dae
```
I get no errors but both render completely invisible; no points, meshes or bounding box visible.  (this is OpenGL ES on android)

Anyone else seeing the same thing?

**Comment by SamuelTS** [comment]
Same thing here.

**Comment by turol** [comment]
These changed in a8a1ca9894a38164f3111f57fddb887b3549ea60. I don't currently have a model viewer set up with current assimp, should I just revert these files?

**Comment by tellypresence** [comment]
Downloaded https://github.com/assimp/assimp/commit/66171de915439f4f1851042a690bf4696e6b126f which is one commit before https://github.com/assimp/assimp/commit/a8a1ca9894a38164f3111f57fddb887b3549ea60

Copied those two models and retried load, same result; so had a look with diff and AFAICT,
the files in https://github.com/assimp/assimp/commit/66171de915439f4f1851042a690bf4696e6b126f are identical to what's in there now?  i.e. doesn't seem to be any point in clobbering them with versions from
 before https://github.com/assimp/assimp/commit/a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by kimkulling** [comment]
There was once a commit which brokes a lot of models. 

From my point of view not all problems which we have came from those commit. Sometimes the loader could be broken as well.

**Comment by turol** [comment]
Yes, I tried reverting all of a8a1ca9 but it actually broke some things. I've been manually reverting only those bits of it which I tested to fix something.

**Comment by kimkulling** [comment]
As far as I know not all models will have data for rendering.
