### ISSUE TITLE
Bundled COB test model load attempts fail with "Cannot parse string as real number..."

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2889]
When attempting to load model:
`models/COB/molecule_ascii.cob`
fails with the following error:
    `"Cannot parse string as real number: does not start with digit or decimal point followed by digit."`
Anyone else seeing this?

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Also getting the same error. The model has not been changed since its introduction in 4c1b5a532d042c1bf4df77759afa07905b40b6c9. @tellypresence can you bisect when it broke?

**Comment by tellypresence** [comment]
Also get the same error for
`test/models/NFF/NFF/cone.nff`
(`"Cannot parse string as real number: does not start with digit or decimal point followed by digit."`)

**Comment by turol** [comment]
@tellypresence These appear to be unrelated, please file a separate issue for the NFF model.

**Comment by tellypresence** [comment]
Some assimp bisecting for future reference:

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "molecule_ascii"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/35c506fcf863ff8e01365cb76686b2010f6bd498">35c506fc</a><br>
30 May 2021</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/COB/molecule_ascii.cobj">test/models/COB/molecule_ascii.cob</a></td><td>Load fails with error: <tt>Cannot parse string as a real number: does not start with digit or decimal point followed by digit.</tt></td></tr>
</table>

**Comment by tellypresence** [comment]
@turol Sorry for the delay (only took me 3 years:sweat_smile:) -- it used to work in early 2014

**Comment by turol** [comment]
Same, the commit does not work for me.

**Comment by tellypresence** [comment]
What build errors did you encounter?

**Comment by turol** [comment]
There were errors about things which were no longer valid in C++17 (since the default standard version has changed in later GCC) and some commit range was missing one of the config template files.

**Comment by tellypresence** [comment]
Yes, I had to patch about 12 assimp files to provide alternates for C++ constructs removed in C++17, and some of my own code (to hide assimp keywords not yet introduced in 2014)
