### ISSUE TITLE
Error loading test model: "unable to read gltf file"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2893]
When attempting to load bundled test model
`test/models/glTF2/BoxTextured-glTF-Binary/BoxTextured.glb`

I get error `Unable to read gltf file`

Is this model fully supported/expected to load correctly?

Thank you

**Comment by turol** [comment]
Can confirm, also broken by a8a1ca9894a38164f3111f57fddb887b3549ea60, will revert.

**Comment by tellypresence** [comment]
This seems to be fixed, thank you
