### ISSUE TITLE
Bundled test model .irr files load bounding box only

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2895]
The following bundled test models:
```
test/models/IRR/animMesh.irr
test/models/IRR/box.irr
test/models/IRR/dawfInCellar_ChildOfCellar.irr
test/models/IRR/dawfInCellar_SameHierarchy.irr
test/models/IRR/EpisodeI_ANewDwarf.irr
test/models/IRR/EpisodeII_TheDwarfesStrikeBack.irr
test/models/IRR/instancing.irr
test/models/IRR/multipleAnimators.irr
test/models/IRR/scenegraphAnim.irr
test/models/IRR/sphere.irr
```
load without any errors, but display only a bounding box; no points, faces, meshes etc are visible at all (and hiding the bounding box makes the models completely invisible)

Anyone else get similar odd behavior when loading these models?

**Comment by tellypresence** [comment]
Also get this problem when attempt to load
```
test/models-nonbsd/IRR/skybox.xml
```

**Comment by SamuelTS** [comment]
Same odd behavior here. Model contains 0 faces.

**Comment by tellypresence** [comment]
Closing after #5166 merged
