### ISSUE TITLE
Cryptic error loading .ms3d model: "vector"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2896]
When attempting to load bundled test model
`test/models/MS3D/Wuson.ms3d`
get error `vector` (unfortunately that's the entire error message, just the one word `vector` [sic])

Anyone else get this error?

(Note that the other .ms3d files in that folder load OK, it's just the one that fails)

**Comment by turol** [comment]
For me the error is `vector::_M_default_append`. Looks like some `std::vector` throws an exception. Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60, I will revert it.

**Comment by tellypresence** [comment]
Confirm reverted model loads OK, thank you
