### ISSUE TITLE
Error loading bundled test model .mdc file: "Invalid MDC file"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2899]
Getting error when attempting to load bundled test model file
`test/models/MDC/spider.mdc`

Error message:
`Invalid MDC file: File contains no valid mesh`

**Comment by turol** [comment]
Same error. File appears to have always been invalid. Introduced by @kimkulling at 008455b984d72e491ce89c8746439648bbab9bf8. Where did it come from? Does it load correctly in some other program?

**Comment by SamuelTS** [comment]
Same error here.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3742
