### ISSUE TITLE
Fail to load bundled test model .ogex "aiScene::mNumMeshes is 0..."

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2901]
Get error loading bundled test model
`test/models/OpenGEX/light_issue1262.ogex`

Error message is
`Validation failed: aiScene::mNumMeshes is 0.  At least one mesh must be there`

Since model file has "issue" in the name not sure if this is expected?

**Comment by turol** [comment]
Not sure about this one. It seems to have been introduced as a test for a crash bug. Now it doesn't crash but fails validation afterwards. Either the model should be made valid or the importer tweaked to fail it for lack of meshes.

**Comment by tellypresence** [comment]
Also get the same error for this model as well
`test/models/OBJ/box_UTF16BE.obj`
(same error: `Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there`)

**Comment by turol** [comment]
@tellypresence File a new issue, it's a different importer. Just because it gives the same validation error doesn't mean it's the same bug.

**Comment by kimkulling** [comment]
This is related to an issue in the OpenGEX-Parser: invalid token match. A PR is on its way.
