### ISSUE TITLE
Error loading bundled test models: "Validation failed: A node of the scenegraph is NULL"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2911]
Getting error loading certain bundled test models:
```
test/models/OpenGEX/empty_camera.ogex
test/models/RAW/WithColor.raw
test/models/RAW/WithTexture.raw
```

Error is
`Validation failed: A node of the scenegraph is NULL`

Anyone else able to confirm whether these are expected errors for these models?  Thank you

**Comment by SamuelTS** [comment]
I'm getting this other error:

`Invalid token`

for following model:

`test/models/OpenGEX/empty_camera.ogex`

And I'm getting same error as you:

`Failed to load file: Validation failed: A node of the scenegraph is NULL`

for following models:

`test/models/RAW/WithColor.raw`
`test/models/RAW/WithTexture.raw`

**Comment by turol** [comment]
RAW files were changed by a8a1ca9894a38164f3111f57fddb887b3549ea60 but appear to have been already broken before that. Can someone bisect if they ever worked?

**Comment by tellypresence** [comment]
Any updates on this?
