### ISSUE TITLE
Errors loading bundled .q3* test models: cryptic "vector" error message

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2912]
When attempting to load either of these two bundled `Q3D` test models:
```
test/models/Q3D/WusonOrange.q3o
test/models/Q3D/WusonOrange.q3s
```
Get the following cryptic error:
`vector` (this is on arm32; have observed catastrophic crashes instead on arm64 device)

My impl is C++ on android so may be platform-specific, but wanted to ask if anyone else finds these particular model files to be problematic in their implementations?  Thank you

**Comment by tellypresence** [comment]
Also get catastrophic crashes when attempting load various other bundled test models:
```
test/models/X/fromtruespace_bin32.x
```

Can anyone else confirm these?  Thank you

**Comment by SamuelTS** [comment]
I'm getting this error:

`Failed to load file: End of file or stream limit was reached`

for following models:

`test/models/Q3D/WusonOrange.q3o`
`test/models/Q3D/WusonOrange.q3s`

And I'm getting this error:

`Failed to load file: bad allocation`

for following model:

`test/models/X/fromtruespace_bin32.x`

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by tellypresence** [comment]
These two models load OK now, thank you for reverting
