### ISSUE TITLE
(fixed) Error loading bundled test model file: "ALTW chunk is too small"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2913]
Get error when attempting to load bundled test model file
```
test/models/TER/RealisticTerrain_Large.ter
```

Error message: `"ALTW chunk is too small"`

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2932

**Comment by tellypresence** [comment]
Model still fails to load, error now: `std::bad_alloc`

**Comment by tellypresence** [comment]
Reverted model loads, thank you

**Comment by kimkulling** [comment]
Thanks a lot for the feedback!
