### ISSUE TITLE
Error loading bundled test model: "Failed to determine STL storage representation"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2914]
Get error attempting to load bundled test model:
```
test/models/STL/3DSMaxExport.STL
```

Error message:
```
Failed to determine STL storage representation for <...>/models/STL/3DSMaxExport.STL
```

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2932

**Comment by tellypresence** [comment]
Confirm reverted model loads OK, thank you

**Comment by kimkulling** [comment]
Great, thanks a lot for the feedback!
