### ISSUE TITLE
Error loading bundled test model: "mesh contains no vertices"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2915]
When attempting to load bundled test model
```
test/models/STL/triangle_with_empty_solid.stl
```

getting error message:
`Validation failed: The mesh emptySolid contains no vertices`

The model name would indicate this could possibly be expected behavior, can anyone please confirm?  Want to verify whether the model should load and show anything or fail with this sort of message, thank you

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
This is expected, the unit test checks that it fails.

**Comment by tellypresence** [comment]
Ah, of course, thank you
https://github.com/assimp/assimp/blob/e899067f440c79747549772fef61abe916bd496e/test/unit/utSTLImportExport.cpp#L98
https://github.com/assimp/assimp/blob/e899067f440c79747549772fef61abe916bd496e/test/unit/utSTLImportExport.cpp#L102-L103
