### ISSUE TITLE
Bundled NFF test model load attempts fail with "Cannot parse string as real number..."

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2916]
(As requested raising separate issue from https://github.com/assimp/assimp/issues/2889)

When attempting to load model:
- [`test/models/NFF/NFF/cone.nff`](https://github.com/assimp/assimp/blob/master/test/models/NFF/NFF/cone.nff)

fails with the following error:
`"Cannot parse string as real number: does not start with digit or decimal point followed by digit."`

Anyone else seeing this?

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
File was changed in a8a1ca9894a38164f3111f57fddb887b3549ea60 but appears to have been already broken before that. Can someone bisect if it ever worked?

**Comment by tellypresence** [comment]
Some assimp bisecting for future reference:

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "cone.nff"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/NFF/NFF/cone.nff">test/models/NFF/NFF/cone.nff</a></td><td>Load error: <tt>Cannot parse string as real number: does not start with digit or decimal point followed by digit.</tt></td></tr>
</table>

**Comment by tellypresence** [comment]
@turol Sorry for the delay (only took me 3 years:sweat_smile:) -- it used to work in early 2014

**Comment by turol** [comment]
Commit [49e9ad9](https://github.com/assimp/assimp/commit/49e9ad9fa5145558f3359e36188caef058ccae39) does not work for me. It looks like this has not worked for a very long time and bisecting is not useful. Someone (else) has to go and actually debug the loader.

**Comment by tellypresence** [comment]
As indicated in #5816, this was due to a misconfigured line in the 3D model file; sanity checking against valid string-as-number was improved many years ago and that was when the misconfigured line started causing model import to fail.
