### ISSUE TITLE
Bundled XGL/ZGL test model load attempts fail with "Cannot parse string as real number..."

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2917]
When attempting to load model:
```
test/models/XGL/Spider_ascii.zgl
```
fails with the following error:
    `"Cannot parse string as real number: does not start with digit or decimal point followed by digit."`
Anyone else seeing this?

(Also affects COB (https://github.com/assimp/assimp/issues/2889), NFF (https://github.com/assimp/assimp/issues/2916) models)

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2932

**Comment by tellypresence** [comment]
Confirm reverted model loads OK, thank you
