### ISSUE TITLE
Error loading bundled test .3ds file "chunk is too large"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2919]
Getting error when attempting to load bundled test model
```
test/models-nonbsd/3DS/pyramob.3DS
```

Error is `Chunk is too large`

Anyone else seeing this?  Thank you

**Comment by SamuelTS** [comment]
Same error here.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2932

**Comment by tellypresence** [comment]
Confirm reverted model loads OK, thank you

**Comment by kimkulling** [comment]
Thanks for the feedback.
