### ISSUE TITLE
Problem loading bundled test .hmp model file: "file too small or contains invalid data"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2921]
Getting error when attempting to load bundled test model:
```
test/models-nonbsd/HMP/terrain_withtexture.hmp
```

Error message: `Invalid MDL file.  The file is too small or contains invalid data.`

(Note: message refers to `MDL` but model has `.hmp` extension)

Anyone else seeing this?

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2932

**Comment by tellypresence** [comment]
Reverted model loads OK, thank you
