### ISSUE TITLE
Error loading bundled test .lwo model: "Chunk length points behind the file"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2924]
Get error when attempting to load bundled test model file:
```
test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Chasis.lwo
```

Error message is: `LWO2: Chunk length points behind the file`

Anyone else seeing this?

**Comment by SamuelTS** [comment]
Same error here.

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by tellypresence** [comment]
Reverted model loads OK, thank you
