### ISSUE TITLE
(dupe) Error loading bundled test .pk3 model: "mIndices[0] out of range"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2926]
Getting error when attempting to load bundled test model
```
test/models-nonbsd/PK3/SGDTT3.pk3
```

Error message: `Validation failed: aiMesh::mFaces[0]::mIndices[0] is out of range`

**Comment by SamuelTS** [comment]
Same error here. BTW I think this issue is a duplicate of #2862

**Comment by tellypresence** [comment]
Apologies, dupe of https://github.com/assimp/assimp/issues/2862
