### ISSUE TITLE
Error loading bundled .x test model: "std::bad_alloc"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2929]
(originally raised in ticket https://github.com/assimp/assimp/issues/2912)

When attempting to load bundled test model:
```
test/models/X/fromtruespace_bin32.x
```

Fails with error `std::bad_alloc` (this is on arm32; have observed catastrophic crashes instead on arm64 device)

Can anyone else confirm this?  Thank you

**Comment by turol** [comment]
Broken by a8a1ca9894a38164f3111f57fddb887b3549ea60

**Comment by tellypresence** [comment]
Confirm this model loads OK now, thank you
