### ISSUE TITLE
clang++11 is complaining that the following bitwise operations are tautological

### ISSUE THREAD

**Issue by hbina** [assimp/assimp#2937]
https://github.com/assimp/assimp/blob/913dced03891ab3ca0f02d7ccf51e925e7f4af40/contrib/Open3DGC/o3dgcSC3DMCDecoder.inl#L69-L72

```bash
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/../contrib/Open3DGC/o3dgcSC3DMCDecoder.h:109:
/home/hbina/git/fatuous/thirdparty/assimp/code/../contrib/Open3DGC/o3dgcSC3DMCDecoder.inl:72:44: warning: bitwise comparison always evaluates to false [-Wtautological-bitwise-compare]
        ifs.SetIsTriangularMesh((mask & 8) == 1);
                                ~~~~~~~~~~~^~~~
/home/hbina/git/fatuous/thirdparty/assimp/code/glTF/glTFAsset.inl:960:13: note: in instantiation of member function 'o3dgc::SC3DMCDecoder<unsigned short>::DecodeHeader' requested here
        if(decoder.DecodeHeader(ifs, bstream) != o3dgc::O3DGC_OK) throw DeadlyImportError("GLTF: can not decode Open3DGC header.");
                   ^
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/glTF/glTFExporter.cpp:46:
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/glTF/glTFAssetWriter.h:55:
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/glTF/glTFAsset.h:1142:
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/glTF/glTFAsset.inl:50:
In file included from /home/hbina/git/fatuous/thirdparty/assimp/code/../contrib/Open3DGC/o3dgcSC3DMCDecoder.h:109:
/home/hbina/git/fatuous/thirdparty/assimp/code/../contrib/Open3DGC/o3dgcSC3DMCDecoder.inl:71:44: warning: bitwise comparison always evaluates to false [-Wtautological-bitwise-compare]
        ifs.SetConvex          ((mask & 4) == 1);
                                ~~~~~~~~~~~^~~~
/home/hbina/git/fatuous/thirdparty/assimp/code/../contrib/Open3DGC/o3dgcSC3DMCDecoder.inl:70:44: warning: bitwise comparison always evaluates to false [-Wtautological-bitwise-compare]
        ifs.SetSolid           ((mask & 2) == 1);
                                ~~~~~~~~~~~^~~~
3 warnings generated.
```

**Comment by turol** [comment]
Looks like a real bug. Is there a live upstream?

**Comment by hbina** [comment]
what do you mean by that?

**Comment by turol** [comment]
It's a third-party component. Quick googling only found a repository which was last updatet in 2013 and didn't look like the code we have in the tree. Is there an upstream project which is still being updated or has it been abandoned?

**Comment by hbina** [comment]
No idea, I am just using ASSIMP for my dummy project https://github.com/hbina/fatuous

**Comment by biglari** [comment]
I have done some extensive searching, and could find no upstream project. I could not find any free specifications for the format, however, I would assume the following was meant:

```
ifs.SetCCW((mask & 1) != 0);
ifs.SetSolid((mask & 2) != 0);
ifs.SetConvex((mask & 4) != 0);
ifs.SetIsTriangularMesh((mask & 8) != 0);
```

**Comment by turol** [comment]
Yes, that would be the correct fix (compare against the encoder). But if the upstream is no longer being updated should we remove the whole thing instead? What importers actually use this and are there real world users?

**Comment by RichardTea** [comment]
It's an open implementation of MPEG 3D compression format. I guess the compression format is reasonably likely to have proprietary implementations.

The only public upstreams I found on a quick search are:

- As a small of part of a larger AMD project - REST3D, not updated since 2014. (C++ and Javascript implementations, the JS implementation has exactly the same issue!)
- https://github.com/KhronosGroup/glTF/tree/mesh-compression-open3dgc/COLLADA2GLTF/extensions/o3dgc-compression

**Comment by kimkulling** [comment]
I am wondering why there any no officially releases out. THe encoder was used in the glTF1.0 format. I will check if we still need this.

**Comment by kkulling** [comment]
Fixed already by fixing all compiler warnings.
