### ISSUE TITLE
Failed to load .stp/.step aiScene::mNumMeshes = 0

### ISSUE THREAD

**Issue by rLaister** [assimp/assimp#2945]
Importer.ReadFile returns aiScene with mNumMeshes = 0 when I try to import a .stp/.step-File.
![image](https://user-images.githubusercontent.com/30234108/72968716-5b211300-3dc4-11ea-951a-f24a111ba0ea.png)

**Comment by turol** [comment]
Can you share a failing test model?

**Comment by kimkulling** [comment]
Would be great, normal stepfile loading is not fully supported at the moment. But I am trying to find time to work on this.

**Comment by rLaister** [comment]
Here is one that is failing:
https://cads-additive.box.com/s/qyiwm7jm4ql5lezu69f5i1c17lrpycmw

**Comment by rLaister** [comment]
@kimkulling could you reproduce this bug?

**Comment by kimkulling** [comment]
Yes, this kind of step-files are not supported at the moment. We need to implement that first :-).
