### ISSUE TITLE
Similar code in Assbin exporter and assimp_cmd binary dump writer.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#2950]
Both Assbin exporter and the assimp_cmd binary dump writer have code that looks almost the same. This code could be refactored.

See the following functions in [AssbinExporter.cpp](https://github.com/assimp/assimp/blob/dbee3807b3c0ceaa442bd0fb6be3661babce7d88/code/Assbin/AssbinExporter.cpp#L759) and [WriteDump.cpp](https://github.com/assimp/assimp/blob/dbee3807b3c0ceaa442bd0fb6be3661babce7d88/tools/assimp_cmd/WriteDumb.cpp#L679).

The same thing can be seen in function **WriteBinaryScene**, which appears in both files, and also look almost the same but with a few syntactic differences.

**Comment by kimkulling** [comment]
Good catch, we need to refactor this code.

**Comment by kimkulling** [comment]
Partly closed by https://github.com/assimp/assimp/pull/2967 .

Again: thanks a lot for your improvements!

**Comment by malortie** [comment]
@kimkulling You are welcome. Glad to help.
