### ISSUE TITLE
assimp_cmd binary dump writer does not write nodes metadata.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#2953]
Related to [this issue](https://github.com/assimp/assimp/issues/2950).

The following snippet from`WriteBinaryNode` in [AssbinExporter.cpp](https://github.com/assimp/assimp/blob/dbee3807b3c0ceaa442bd0fb6be3661babce7d88/code/Assbin/AssbinExporter.cpp#L370-L406) should also be in the `WriteBinaryNode` function in [WriteDump.cpp](https://github.com/assimp/assimp/blob/dbee3807b3c0ceaa442bd0fb6be3661babce7d88/tools/assimp_cmd/WriteDumb.cpp#L303)

**Comment by kimkulling** [comment]
Good catch, I need to fix that issue!

**Comment by malortie** [comment]
@kimkulling I worked on a fix to address issue https://github.com/assimp/assimp/issues/2950. I didn't submit it yet because I was waiting for PR https://github.com/assimp/assimp/pull/2958 to be merged, as the diff is huge and I want to avoid having a lot of merge conflicts.

Would you prefer that I make a draft PR so that we can look into merging it later. This would as well solve the current issue (missing metadata in dump writer). 

OR

Would you prefer to make the changes yourself, including the current issue?

What would be better suited?

**Comment by malortie** [comment]
@kimkulling [Here is the link](https://github.com/assimp/assimp/pull/2967) to the PR to address issues https://github.com/assimp/assimp/issues/2950 and https://github.com/assimp/assimp/issues/2953.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2967

Thanks a lot fro your help to improve this code!
