### ISSUE TITLE
5.0.1 is broken on the i386 architecture: typedef redefinition with different types ('long' vs '__ssize_t' (aka 'int'))

### ISSUE THREAD

**Issue by yurivict** [assimp/assimp#2954]
Log: http://beefy10.nyi.freebsd.org/data/113i386-default/524147/logs/assimp-5.0.1.log

**Comment by turol** [comment]
This is actually a problem with the bundled zip implementation and should be fixed upstream (wherever that is) and then just updated here.

**Comment by kimkulling** [comment]
So what we need to do is: define one zlib-library, use this all over the code and perform the cleanup. 

I guess with the list of open issus this one will need a while.

**Comment by randomMesh** [comment]
The bug has been fixed upstream today: https://github.com/kuba--/zip/commit/42c8ba8f7055cd280b26c80fcad1c9fc921cf8fc

**Comment by kimkulling** [comment]
Ok, thanks for the update.

**Comment by yurivict** [comment]
Could you please make a release containing the fix?

Thanks!

**Comment by rhurlin** [comment]
> Could you please make a release containing the fix?

I also would like to encourage this project to release a version 5.1. At least on FreeBSD, some very important other ports/packages depend on assimp, which do not build for month now on i386.

Any chance for a new release in the near future?  Many thanks in advance!

**Comment by AMDmi3** [comment]
A great example of that dependencies must never ever be bundled.
