### ISSUE TITLE
Similar code in Assxml exporter and assimp_cmd XML dump writer. 

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#2959]
Similar to issue https://github.com/assimp/assimp/issues/2950.

See files [AssxmlExporter.cpp](https://github.com/assimp/assimp/blob/a1fbe74e874d919aafdb64ec07c89cab86a81e59/code/Assxml/AssxmlExporter.cpp#L187) and [WriteDump.cpp](https://github.com/assimp/assimp/blob/a1fbe74e874d919aafdb64ec07c89cab86a81e59/tools/assimp_cmd/WriteDumb.cpp#L871).

**Comment by kimkulling** [comment]
Saw this as well some years agot. Hopefully I will find the time to refactor that stuff. Most of the assimpxml-stuff should get some cleanups!

**Comment by malortie** [comment]
This follows https://github.com/assimp/assimp/pull/2967.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2972
