### ISSUE TITLE
MacOS: CMAKE_INSTALL_NAME_DIR/INSTALL_NAME_DIR is deprecated

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#2961]
CMake 2.8.12 added the ability to use "@rpath" for library install names via CMAKE_MACOS_RPATH.
https://blog.kitware.com/upcoming-in-cmake-2-8-12-osx-rpath-support/

The @RPATH approach is generally recommended as it allows the consuming application to specify the loader search paths. It's also easier to swap out after-the-fact via install_name_tool as the prefix is a known string.

This was enabled by default policy (CMP0042) in CMake 3.0, which is the current minimum version.
https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042

However, setting INSTALL_NAME_DIR or CMAKE_INSTALL_NAME_DIR overrides this behaviour.
Assimp shouldn't set either of these by default.

A user requiring the old behaviour can explicitly set CMAKE_INSTALL_NAME_DIR as desired.

**Comment by RichardTea** [comment]
libIrrXML.dylib is already using @RPATH, which means libassimp currently doesn't link on macOS without the manual use of install_name_tool.

**Comment by kimkulling** [comment]
Ok, thanks for the help. I will do the review and merge the issue.
