### ISSUE TITLE
Assimp does not support gltf format with KHR_draco_mesh_compression extension.

### ISSUE THREAD

**Issue by runforu** [assimp/assimp#2963]
As the mentioned in the title, assimp does not support compressed gltf file format.

**Comment by RichardTea** [comment]
This is a duplicate of #2195 

Are you working on adding this support?

**Comment by kimkulling** [comment]
I made some basic investigations, not more.

**Comment by kimkulling** [comment]
I will close this one, let's use the other to track the feature request.
