### ISSUE TITLE
Migrate from IrrXml to PugiXml

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#2965]

**Comment by RichardTea** [comment]
Caution: PugiXml's number conversion functionality relies on the current C locale.
This functionality cannot be used by Assimp.

If possible these Pugixml functions should be explicitly disabled.

**Comment by kimkulling** [comment]
Do you mean these:
```
pugi::xml_node::to_string()
pugi::xml_node::to_double()
...
```

**Comment by RichardTea** [comment]
All the to_xxx() and set_value() that take or receive a number.
I wasn't able to find a macro that disables them, which is a bit risky as it makes it easy for people to use them by mistake.

The string accessors are safe as they are defined as UTF-8 encoding.

**Comment by kimkulling** [comment]
Assimp has the advantage of bringing its own conversion stuff, so maybe things are getting better. The reason to switch off the irrlicht stuff are some tests with the irrlich format. I saw a lof of memleaks in it. And I got some feedback from google, that most of their fuzz-finding were caused by the irrxml-lib.

I will create a Xml-Parser to provide a lib-independent xml-parser. This work is currently ongoing.

**Comment by RichardTea** [comment]
One architectural change that would be highly recommended is to have some way to auto-detect whether an input file is probably XML (or JSON), then parse XML (and JSON) formats _once_, then pass the Pugi (or RapidJson) internal representation around all the XML (or JSON) based importers to find which one can best read it.

Currently both glTF 1 and glTF 2 have to do the full RapidJSON parse before they can determine whether they can open a file that looks like JSON - and throw all that work away if they can't!

Changing to PugiXML (or any XML-DOM reader) would mean that all the Collada, AssXML and other XML-based formats would have the same problem.

It'd be very good to fix that limitation for both XML and JSON

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2966
