### ISSUE TITLE
cmake assimp::assimp from "find_package" provides dll file, not lib

### ISSUE THREAD

**Issue by ElDesalmado** [assimp/assimp#2979]
I've installed v.5.0.0.rc2 and used ```find_package(assimp)``` to link against the library, but ```assimp::assimp``` yields the dll file, not lib. 

```${ASSIMP_LIBRARIES}``` yields the correct lib filename, however it does not provide the full or relative path to the lib file, so it can not be found when building

**Comment by kimkulling** [comment]
Clsed by

**Comment by kimkulling** [comment]
Thanks for the report by the way!
