### ISSUE TITLE
Failed to build assimp with mingw

### ISSUE THREAD

**Issue by LaurentDuroisin7601** [assimp/assimp#2980]
`C:\Users\Laurent\Downloads\assimp-master\assimp-master\build>mingw32-make
[  0%] Generating zlib1rc.obj
'C:\Program' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\windres.exe: preprocessing failed.
mingw32-make[2]: *** [contrib\zlib\CMakeFiles\zlib.dir\build.make:61: contrib/zlib/zlib1rc.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:244: contrib/zlib/CMakeFiles/zlib.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2`

**Comment by VictorLamoine** [comment]
Looks like the space in the path `C:\Program Files\` is not properly parsed.
You should install minGW and try to compile in a directory that contains no "special" characters (eg: install everything in `C:/software`)

**Comment by LaurentDuroisin7601** [comment]
Ha yes cmake doesn't like space and accents on windows....

**Comment by LaurentDuroisin7601** [comment]
I have another problem now .

[  0%] Linking CXX shared library libassimp.dll
CMakeFiles\assimp.dir/objects.a(AssbinLoader.cpp.obj):AssbinLoader.cpp:(.text+0x5e5c): undefined reference to `uncompress'
CMakeFiles\assimp.dir/objects.a(BlenderLoader.cpp.obj):BlenderLoader.cpp:(.text+0xa47d): undefined reference to `inflateInit2_'
CMakeFiles\assimp.dir/objects.a(BlenderLoader.cpp.obj):BlenderLoader.cpp:(.text+0xa52f): undefined reference to `inflate'
CMakeFiles\assimp.dir/objects.a(BlenderLoader.cpp.obj):BlenderLoader.cpp:(.text+0xa5c4): undefined reference to `inflateEnd'
CMakeFiles\assimp.dir/objects.a(XGLLoader.cpp.obj):XGLLoader.cpp:(.text+0xa9bb): undefined reference to `inflateInit2_'
CMakeFiles\assimp.dir/objects.a(XGLLoader.cpp.obj):XGLLoader.cpp:(.text+0xaa7f): undefined reference to `inflate'
CMakeFiles\assimp.dir/objects.a(XGLLoader.cpp.obj):XGLLoader.cpp:(.text+0xacd4): undefined reference to `inflateEnd'
CMakeFiles\assimp.dir/objects.a(FBXParser.cpp.obj):FBXParser.cpp:(.text+0x5af): undefined reference to `inflateInit_'
CMakeFiles\assimp.dir/objects.a(FBXParser.cpp.obj):FBXParser.cpp:(.text+0x60a): undefined reference to `inflate'
CMakeFiles\assimp.dir/objects.a(FBXParser.cpp.obj):FBXParser.cpp:(.text+0x62a): undefined reference to `inflateEnd'
CMakeFiles\assimp.dir/objects.a(XFileParser.cpp.obj):XFileParser.cpp:(.text+0xac09): undefined reference to `inflateInit2_'
CMakeFiles\assimp.dir/objects.a(XFileParser.cpp.obj):XFileParser.cpp:(.text+0xad63): undefined reference to `inflate'
CMakeFiles\assimp.dir/objects.a(XFileParser.cpp.obj):XFileParser.cpp:(.text+0xad84): undefined reference to `inflateReset'
CMakeFiles\assimp.dir/objects.a(XFileParser.cpp.obj):XFileParser.cpp:(.text+0xadab): undefined reference to `inflateSetDictionary'
CMakeFiles\assimp.dir/objects.a(XFileParser.cpp.obj):XFileParser.cpp:(.text+0xadfa): undefined reference to `inflateEnd'
CMakeFiles\assimp.dir/objects.a(AssbinFileWriter.cpp.obj):AssbinFileWriter.cpp:(.text$_ZN6Assimp16AssbinFileWriter15WriteBinaryDumpEPKcS2_PNS_8IOSystemEPK7aiScene[__ZN6Assimp16AssbinFileWriter15WriteBinaryDumpEPKcS2_PNS_8IOSystemEPK7aiScene]+0x4cf): undefined reference to `compressBound'
CMakeFiles\assimp.dir/objects.a(AssbinFileWriter.cpp.obj):AssbinFileWriter.cpp:(.text$_ZN6Assimp16AssbinFileWriter15WriteBinaryDumpEPKcS2_PNS_8IOSystemEPK7aiScene[__ZN6Assimp16AssbinFileWriter15WriteBinaryDumpEPKcS2_PNS_8IOSystemEPK7aiScene]+0x513): undefined reference to `compress2'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x1985): undefined reference to `inflateInit2_'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x1a07): undefined reference to `get_crc_table'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x1f3c): undefined reference to `crc32'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x1fe3): undefined reference to `inflate'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x202b): undefined reference to `crc32'
CMakeFiles\assimp.dir/objects.a(unzip.c.obj):unzip.c:(.text+0x22ae): undefined reference to `inflateEnd'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [code\CMakeFiles\assimp.dir\build.make:3608: code/libassimp.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:249: code/CMakeFiles/assimp.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

**Comment by kimkulling** [comment]
Try to use the internal zlib version shall fix that issue. Try:

` cmake CMakeLists.txt -DASSIMP_BUILD_ZLIB=ON`

Reopen the  issue when it is still an issue!
