### ISSUE TITLE
The output of gltf is not correct.

### ISSUE THREAD

**Issue by runforu** [assimp/assimp#2982]
1. import gltf file using assimp.
2. export gltf file using assimp.
3. check the difference between exported gltf file and the original gltf file. Some parts are not in correct position and animation is not correct.

**Comment by runforu** [comment]
The test model is at https://sketchfab.com/3d-models/willy-805be6f9445e42cebdc5563b571a7b96

**Comment by runforu** [comment]
Or uploaded test gltf 3d model.
[willy.zip](https://github.com/assimp/assimp/files/4156263/willy.zip)

**Comment by runforu** [comment]
I think it is caused by animation.

**Comment by runforu** [comment]
For more information: https://github.com/KhronosGroup/glTF/issues/892

**Comment by runforu** [comment]
https://d3cw3dd2w32x2b.cloudfront.net/wp-content/uploads/2015/01/matrix-to-quat.pdf

**Comment by runforu** [comment]
Please review and merge my commit for this bug. https://github.com/assimp/assimp/pull/2995

**Comment by runforu** [comment]
Please review and merge my commit for this bug. #2995

**Comment by kimkulling** [comment]
Closed, thanks for your help.
