### ISSUE TITLE
Question: best pratices to use assimp serverless.

### ISSUE THREAD

**Issue by Aarbel** [assimp/assimp#2983]
Hi everybody.

I use assimp to transform IFC file to OBJ files. 
I'd like to use assimp serverless and trigger a conversion on demand. 
For example i didn't found any assimp lambda layers or any assimp serverless examples on aws, maybe because aws lambda is limited to 500 Mb of RAM or maybe most of assimp users still fully configure their own infrastructure.

Do you know best practices to install / use assimp serverless ? 
The best could be to use an other langage than C++ to trigger assimp conversion, like Python or execFile method in Node.js.

Thanks a lot for your advices !

Aarbel

**Comment by kimkulling** [comment]
For my üpoint of view I would recommend running assimp in a docker image. Then trigger in aws the conversion in this environment via python or a batch script.

I havn't tried this out but this was an older plan from me how to run it in such an environment.

**Comment by lokiiarora** [comment]
You could use something called a "Layer" in AWS Lambda.
You have to compile down Assimp in a docker image with base image that is similar to amazon environment like [lambci](https://hub.docker.com/r/lambci/lambda/) or [amazonlinux](https://hub.docker.com/_/amazonlinux) into a static executable and upload it in a specific format pertaining to which language you are using it for. Like mention [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).

@Aarbel I'm using layer in my current project with assimp and have a layer configured, do let me know if you need any assistance

**Comment by Aarbel** [comment]
@lokiiarora could be really great to check your layer.

I can also make it validated by AWS teams to be a standard Layer for Assimp.

**Comment by lokiiarora** [comment]
Do you need an entire setup or just the zip for the layer? @Aarbel

**Comment by Aarbel** [comment]
Both could be perfect

**Comment by lokiiarora** [comment]
Repository for building lambda layer for assimp, [here](https://github.com/Scapic/assimp-lambda-layer) .
[bin.zip](https://github.com/assimp/assimp/files/4746772/bin.zip)
