### ISSUE TITLE
Export cmake file using cmake function export

### ISSUE THREAD

**Issue by JackBoosY** [assimp/assimp#2988]
Hi guys,
I found that `targets.cmake` and `targets-debug/release.cmake` generated by assimp were generated using `configure_make`, which may cause a mismatch with the configuration in CMakeLists.txt.

So I have a question: why not use cmake `export` function to generate these files?

**Comment by psionic12** [comment]
I found that this lead to a different behavior between windows and linux. On linux, I have to manually add libz and libIrrXML, but on Windows I just use `target_link_libraries(myrenderer PRIVATE assimp::assimp)` and nothing else.

**Comment by JackBoosY** [comment]
@kimkulling Any progress?

**Comment by kimkulling** [comment]
I guess this one is fixed.
