### ISSUE TITLE
No way to detect double support in shared lib?

### ISSUE THREAD

**Issue by 3b** [assimp/assimp#2992]
I don't see any way to detect at runtime whether a shared lib was compiled with support for double floats or not, expected something from `aiGetCompileFlags` or similar.

Would be useful for use from non-C languages where parsing a C header just to detect that would be annoying, and possibly also for making sure a system lib matches expectations of a distributed binary.

**Comment by kimkulling** [comment]
You can find it on the current master. Single for floats, double for - double ;.).
