### ISSUE TITLE
assimp model viewer

### ISSUE THREAD

**Issue by skylineMax** [assimp/assimp#2999]
Is there exist a program like open3mod with the actual version of assimp?
 open3mod have a lot of issues with some model rendering and I can't realize is there a problem with open3mod only or with assimp too.

**Comment by kimkulling** [comment]
You can try the assimp-viewer which is part of the library. And I am working on my own viewer. Currently animation support is missing, material support is bad and a lot of usefule features are missing ( https://github.com/kimkulling/osre ).

I would generally recommend to use the Godot-Editor to look at your models. It uses assimp internally.
