### ISSUE TITLE
Propose to reformat all the code, the code is very messy.

### ISSUE THREAD

**Issue by runforu** [assimp/assimp#3001]
Please create a new .clang-format and use the file to format all the source code. The code is very messy, ugly and full of mix of spaces and tabs.
Please use 4 spaces to intent only because tab width is not always the same in different platform or terminal.
Please reconstruct the code structure to make the root directory clean and tidy and output generated files in a folder like "build".

Please do that, stop development, do that to make the project more professional.

**Comment by turol** [comment]
You can already do builds outside of the source tree or in any subdirectory you want. This is a standard CMake feature. +1 for reformatting and automatic style enforcement though.

**Comment by RichardTea** [comment]
There is already a clangformat, however there is no precommit hook enforcing its use so some PRs are not applying it.

I await your pull request to add this.

**Comment by kimkulling** [comment]
From my side mades sence to add an automatic reformatting for new pull-requests. But it does not makes sense to unpadte all the files by once. Doing this will cause a lot of diffes for WIP-pull-requests.

I will try to provide something for new pull requests.

**Comment by Pyr3z** [comment]
+1 Messy format, but I would also like to add that—at least in building 5.0.0 under all three compilers on my machine (MSVC, Clang, GNU)—there is an incredible number of SIMPLE-FIX warnings such as:
```
[...] warning C4267: '=': conversion from 'size_t' to 'ai_uint32', possible loss of data [...]
```
To me this reeks of a certain lack of *enforced* standards, but maybe I'm still in a uni mindset where just ONE warning of this kind is an automatic **failing** grade due to unprofessionalism. Shrug.

I'll look into forking it to squash those warnings myself, because it's aggravating to start a clean build and be met with a Big Wall of Bad :P

**Comment by runforu** [comment]
The clang-format uses tab rather than spaces, which cause display problems. I suggest using spaces for all source files. In any terminal, four spaces are of the same width, but a tab maybe shown as wide as 8 spaces or as wide as 4 spaces depending on the system or terminal.

**Comment by runforu** [comment]
When I writing code, I always format the code using clang-format. It is a good practice that the same code always in the same code format, comparing tools will tell no difference. To achieve that, a .clang-format should be used for all files and the .clang-format should be the gold rule for code formatting.

**Comment by kimkulling** [comment]
@Pyr3z I do agree, but I forget to enable the "handle warning as error policy" for the appveyor-build.

**Comment by kimkulling** [comment]
So, all warnings are eleminated, more restrickt CI-buildchain is there as well fro Windows. I will merge it today. Then I will perform the code cleanup will all the new changes.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3012
