### ISSUE TITLE
Incorrectly named Assimp .dll in UpdateAssimpLibsDebugSymbolsAndDLLs.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3004]
In the main CMakeLists.txt, at the root project, a variable named `ASSIMP_MSVC_VERSION` is used for the project UpdateAssimpLibsDebugSymbolsAndDLLs. This variable specifies the visual studio version e.g. **vc140**, **vc141**, **vc142** to use in the .dll file name.  To give an example, here is what building under a certain VC++ compiler would produce:

`Visual Studio 2015 => assimp-vc140-mtd.dll`
`Visual Studio 2017 => assimp-vc141-mtd.dll`
`Visual Studio 2019 => assimp-vc142-mtd.dll`

The following code in CMakeLists.txt shows that `ASSIMP_MSVC_VERSION` is never assigned in a value when  `MSVC_TOOLSET_VERSION` is defined. It seems that the variable `MSVC_PREFIX` was rather meant to be `ASSIMP_MSVC_VERSION`.

https://github.com/assimp/assimp/blob/58b9dcbdc713730680ddb7c340d869e978b446e2/CMakeLists.txt#L674-L684

In addition, here is a build log of project UpdateAssimpLibsDebugSymbolsAndDLLs. The process attempts to copy a .dll named `assimp--mt.dll`, which does not exist.

```
2>------ Build started: Project: UpdateAssimpLibsDebugSymbolsAndDLLs, Configuration: Debug x64 ------
2>Building Custom Rule C:/Users/marc-/Documents/GitHub/assimp/CMakeLists.txt
2>Error copying file "C:/Users/marc-/Documents/GitHub/assimp/CMakeOutput/code/Release/assimp--mt.dll" to "C:/Users/marc-/Documents/GitHub/assimp/bin64/assimp--mt.dll"
```

**Comment by kkulling** [comment]
Fix is on its way
