### ISSUE TITLE
Condition in CMakeLists.txt tests for 'MSVC15', which is an inexistent variable.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3005]
According to [CMake documentation](https://cmake.org/cmake/help/v3.8/variable/MSVC14.html), along with this [bug report](https://gitlab.kitware.com/cmake/cmake/issues/16735) (see first reply), the variable `MSVC15` does not exist.

https://github.com/assimp/assimp/blob/58b9dcbdc713730680ddb7c340d869e978b446e2/CMakeLists.txt#L681-L683

In addition, the CMake file `Windows-MSVC.cmake` contains several MSVC variable definitions, but there are no references to `MSVC15`.

```
set(MSVC10)
set(MSVC11)
set(MSVC12)
set(MSVC14)
set(MSVC60)
set(MSVC70)
set(MSVC71)
set(MSVC80)
set(MSVC90)
set(CMAKE_COMPILER_2005)
set(CMAKE_COMPILER_SUPPORTS_PDBTYPE)
```

One possible solution would be to use the same technique as used in another CMakeLists.txt, which uses the `MSVC_VERSION` to determine the compiler version for **v140** or higher.

https://github.com/assimp/assimp/blob/58b9dcbdc713730680ddb7c340d869e978b446e2/code/CMakeLists.txt#L1193-L1204

**Comment by kimkulling** [comment]
This one shall be fixed. I made a PR for that a while ago.
