### ISSUE TITLE
Remove unneeded expressions in ELSE() and ENDIF() constructs in CMakeLists.txt files.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3007]
According to the CMake FAQ, it is explained [here](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#isnt-the-expression-in-the-else-expression-confusing) that as of 2.6.0, `ELSE()`, `ENDIF()` constructs can be empty.

The lowest minimum CMake version used in CMakeLists.txt files (excluding the ones within contrib folder) is 2.6.0.

Expressions inside `ELSE()`, `ENDIF()` constructs could be removed, and potentially improve readability.

**Comment by kimkulling** [comment]
Shall be closed now.
