### ISSUE TITLE
assimp.lib in Windows Binaries 3.1.1 referencing assimp.exe

### ISSUE THREAD

**Issue by xoofx** [assimp/assimp#302]
Hi there,
When downloading the `assimp-3.1.1-win-binaries.zip` and trying to link with an application using a previous version of assimp, it seems that the `assimp.lib` provided is generated against `assimp.exe` but not with dll, generating in a runtime error when it tries to load assimp (opening assimp.lib in an hex editor and there is no mention of dll but only assimp.exe). Is this a known issue with Windows distrib?

**Comment by naavis** [comment]
http://sourceforge.net/projects/assimp/files/assimp-3.1/ The newest binary release still has this issue.

**Comment by inkadnb** [comment]
I'm also having this problem. Any news?

**Comment by Daerst** [comment]
I can confirm this problem with Assimp 3.1.1. Downgrading to 3.0 helped.

Be wary that if you use a current compiler (e.g. MSVC2013) with Assimp 3.0, you might have to use the release DLL (and rename it to Assimp32d.dll) to avoid error 0xc0150002.

**Comment by kimkulling** [comment]
Fixed in latest master
