### ISSUE TITLE
Clarification on the term inverseMeshTransform?

### ISSUE THREAD

**Issue by willmotil** [assimp/assimp#3023]
I have come across a problem which has thrown me for a huge loop this is one part of it that i can at least identify.

I have seen the term inverseMeshTransform used in examples and code.

1) Can someone define this inverseMeshTransform or at least elaborate on 2.

2) Can someone describe how i can calculate or obtain this value and were when it is to be applied?

3) Does it replace part of or is it tacked onto the transform chain from the root node at some point?

4) More then one bone offset of the same name in different meshes (see below).

My main problem atm is that a bone offset in a mesh of the same name as a transform node.
May exist in more then one mesh. Were the bone transform itself exists only in the node tree hierarchy off the root.

This is causing me great confusion, since the transform chain is cumulative from parent to child. 

I am under the impression the transform chain requires offsets when it is traversed and calculated from the rootnode on. It seems to me this will form a fully distinct set of cumulative transform results per mesh.

Which the imported assimp structural layout doesn't appear to lend itself to.

I hope the description of my difficulty's makes sense. The terminology of this is all very confusing and i have seen terms seemingly differ across posts and tutorials and even example code. Many not even address the same offsets existing in different meshes to the same named bone. The said term inverseMeshTransform doesn't seem to be in the documentaion. if it is i cannot find it.

Further id like to know the conceptual reason the transform node trees aren't in (and specific to) the meshes with the offsets. When the bone offsets can be unique to a mesh and theirfore if i understand it cause a uniquely cumulative resulting transform chain from parent to child?
The answer to this question might help me understand it all directly.

What am i mis-understanding?

**Comment by kimkulling** [comment]
Sorry, could you point out where you find it?

**Comment by willmotil** [comment]
Sorry i solved this issue and should of replied i can't remember exactly which tutorial blog i saw this term now but it turned out this was just someones bad instructions.  The closest thing i got to having anything that relates to a inverse mesh transform is blenders export of mesh animation nodes that don't actually use bones the meshes themselves are transformed. For that situation in my model program i offset every transformation node and its inverse bone node to start at one. When a model has animation with a mesh name i stick it in bone zero instead of identity and bone zero always executes.

**Comment by willmotil** [comment]
solved misinformation lead to this issue.
