### ISSUE TITLE
glTF access to extras and extensions properties

### ISSUE THREAD

**Issue by ardenpm** [assimp/assimp#3025]
glTF 2.0 allows for any node to have an _extras_ and/or _extensions_ property. These may expose data which is not directly of interest to Assimp itself but could be useful for applications using Assimp. Right now only extensions actually used by Assimp are parsed and extras properties are ignored.

It would be extremely useful if Assimp preserved this data somewhere (possibly as generic metadata). I'm not sure if there is a generic concept of metadata in Assimp, however just extending the glTF 2.0 Asset would be fine, particularly since these are fairly glTF specific properties.

**Comment by RichardTea** [comment]
Assimp does indeed have arbitrary metadata.

I am working on this, and hope to propose a PR in a couple of weeksm

**Comment by Evangel63** [comment]
#3298 implements this for Nodes via Assimp's metadata structure. I only implemented it for the ones I need, but adding others shouldn't be too difficult.

**Comment by kimkulling** [comment]
Merged, so I will close this issue.

**Comment by Futuremappermydud** [comment]
Is there any documentation on this feature?

**Comment by singhraj82** [comment]
Hi, is there any example on how to access  the node information from extension? I an able to parse the extension as shown below but where is the actual node information for Node 2 and 3 stored in metadata. I would really appreciate any hints/ideas. Thanks
```
{
                "MSFT_lod": {
                    "ids": [
                        1,
                        2,
                        3
                    ]
                }
            }
```
