### ISSUE TITLE
[Improvement] Allow developers to add search paths to the importer.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3027]
Please note that the following is only a suggestion.

### Goals and motivations

In the code, there are a few places where the importer attempts to locate resources. See the following files below.

https://github.com/assimp/assimp/blob/824a412239005521862238a54032065cf1e79eb5/code/LWS/LWSLoader.cpp#L488-L504

https://github.com/assimp/assimp/blob/824a412239005521862238a54032065cf1e79eb5/code/MD3/MD3Loader.cpp#L512-L517

Some models are split between meshes, textures, animations in different files. To give an example, MD5 has files for meshes such as MD5mesh and other files for animations such as MD5anim. Another example would be for SMD files. There are SMD mesh files and animation SMD files. Other models have external image files such as jpg, tga, etc.

Often time, all resources are in the same folder, but it could happen that developers would like to keep meshes and textures in distinct folders, for clarity. Now, imagine you have a model that was built on top of another model and uses all textures from the base model, but includes new textures as well. The developer might wish to keep both models in separate folders, but allow the inherited model to use textures from the base model, without copying textures from the base model to the inherited model folder.

The suggested feature aims to provide more flexibility, by allowing developers to tell to the importer where to search for the required resources. The importer would iterate through each search path and look for the resource until it is found, or simply return with no results. Also, this feature could help reduce "hard-coded" search paths within importers. From my point of view, it should be up to the developer to tell the importer where resources are located.

The following is an example that illustrates how this feature could be applied:

```cpp
Importer importer;

// Add a search path to a directory were Model.obj is located.
importer.AddSearchPath("C:/<path_to_directory_containing_Model_obj>/");

/* Read the file. Notice the absence of absolute path because
   we already added a search path where Model.obj is expected
   to be found. */
importer.ReadFile("Model.obj");
```

If you believe this feature could be helpful, feel free to reply and share your thoughts on this. Any comment and criticism would be appreciated. The rest of the post consists of use cases illustrating the feature.

### Use cases in code

**Note**: Several examples below use "obj" as well as "md3" for the model file format. It is important to remember that these examples are fictional use cases used to demonstrate how this feature would be used, and do **not** imply that models using the "obj" format as we know it would absolutely require the use of search paths or anything part of the feature.

#### Example 1

As a developer, I want to load a model split into several files. The model files are Model.obj and 5+ image files to use as textures. For several reasons, I want to keep resources in distinct folders. I want to specify to the importer where to find all resources for the model.

```cpp
Importer importer;

// Add a search path to the directory containing Model.obj.
importer.AddSearchPath("C:/<path_to_directory_containing_Model_obj>/");

// Add a search path to the directory containing all texture images.
importer.AddSearchPath("C:/<path_to_directory_containing_Model_obj_textures>/");

// Load the model.
importer.ReadFile("Model.obj");
```

#### Example 2

As a developer, I have 2 models - Model 1 and Model 2. Model 2 has been modelled after the first model and inherits all textures from Model 1, but also has new textures. I want to avoid copying Model 1's textures into Model 2's directory. In short, I want to reuse Model 1's textures while using Model 2's new textures as well.

```cpp
Importer importer;

/* Add a search path to the directory containing Model 2. 
   Model 2 needs to be added first because it could override
   texture files from Model 1. */
importer.AddSearchPath("C:/<path_to_directory_containing_Model_2>/");

/* Add a search path to Model 1's directory. */
importer.AddSearchPath("C:/<path_to_directory_containing_Model_1>/");

importer.ReadFile("Model2.obj");
```

#### Example 3

As a developer, I have an .md3 file and wish to tell to the importer where all shader files from the base game are located.

```cpp
Importer importer;

/* Add a search path to Model.md3's directory. */
importer.AddSearchPath("C:/<path_to_directory_containing_md3_file>/");

/* Add a search path to the game directory that contains shaders. */
importer.AddSearchPath("C:/<path_to_directory_containing_game_shader_files>/");

importer.ReadFile("Model.md3");
```

**Comment by kimkulling** [comment]
I like the idea. Thanks a lot for sharing it. Any other opinions?

**Comment by RichardTea** [comment]
I have implemented "search paths" by implementing an Assimp::IOSystem.

I believe this is the right layer for such things - especially as it allows the search to extend outside the "real" filesystem, eg binary-embedded "files".

Also, most formats do not need search paths at all, because Assimp usually doesn't actually load the texture data, usually it simply returns the texture paths for the host application to search for.

It's only a handful of formats (eg glTF, OBJ) that (can) place mesh information in a separate file (bin, mtl et al)

**Comment by malortie** [comment]
Please, correct me if I am wrong, but the addition of search paths would probably make methods `PushDirectory`, `CurrentDirectory`, `PopDirectory` no longer needed since the IOSystem implementation could search and find requested files.

**Comment by malortie** [comment]
@RichardTea 

> Assimp usually doesn't actually load the texture data, usually it simply returns the texture paths for the host application to search for.

By "Assimp", do you mean the importer or is it a different process? Please, would it be possible to show a location in the code where it returns the search path to the host application, and or enumerate which class/method does it?

Thanks for your feedback.

**Comment by willmotil** [comment]
I do this already under assimp .net i used the path class to get current application directory. 
I strip off the path from the file name when i load it and reconstitute the paths iteratively checking the default expected paths or path and subfolder paths such as /Textures/ when the file is not found.

**Comment by RichardTea** [comment]
@malortie 
> > Assimp usually doesn't actually load the texture data, usually it simply returns the texture paths for the host application to search for.
> 
> By "Assimp", do you mean the importer or is it a different process? Please, would it be possible to show a location in the code where it returns the search path to the host application, and or enumerate which class/method does it?

`aiMaterial::GetTexture()` returns the on-disk path of the texture in the `aiString *path` parameter.

This path is either an ident for 'embedded' texture data (eg FBX, Collada ZAE), or a file path.
- Note: embedded textures may be `*0` or an arbitrary string (eg FBX and Collada ZAE idents look like relative file paths)

If the texture data is embedded, the host application can then load 'embedded' texture data directly from the aiScene.mTextures array.

If the texture data is not embedded, the host application uses the provided file path to locate it somewhere on disk.

The file path may be absolute or relative, depending on how the 3D model was created.

**Comment by malortie** [comment]
@RichardTea

Thanks for the precisions. By now, I understand what you mean.

After carefully reading your answer, as well as the documentation on materials in material.h, I understand now why it would be 'unnecessary' to implement such a search paths system - as you explained, developers can simply use materials to retrieve the file path to non-embedded textures.

Plus, the idea of mounting materials; textures files; via search paths can be solved as well by using file paths retrieved from materials - Developers can build themselves a system to automatically mount resources without the need of Assimp. So far, it is fair to say that it is not pertinent to implement a search paths system.

@RichardTea, @willmotil , thanks for your feedback. As for me, I do not have anything else to suggest/add at this time. I will leave the issue open in case anyone else has suggestions.

**Comment by malortie** [comment]
@RichardTea 

You said you implemented "search paths" by implementing Assimp::IOSystem. Would you like to share more details on this? (as this could still be pertinent).

**Comment by RichardTea** [comment]
I (partially) created a custom Qt-based IOSystem implementation that acts as a 'union' filesystem across multiple locations.

I didn't use it in the end though, as it would only be useful for the model formats that spread 'core' model data (eg mesh, bones, material specs) across multiple files-on-disk, and we decided it was better to fail if the user had 'misplaced' such files rather than silently grab a (likely incorrect) version.
