### ISSUE TITLE
No way to store orthographic cameras

### ISSUE THREAD

**Issue by ardenpm** [assimp/assimp#3030]
Currently `aiCamera` does not offer enough properties to allow it to store orthographic cameras. Some importers (e.g., glTF, not sure about others) seem to try and set `mHorizontalFOV` to zero in an effort to flag the camera as orthographic, however then only the `mAspect` value is given preventing the full specification of a camera (width or height are needed at least in addition to aspect).

I would propose adding an `mOrthographicWidth` property to the `aiCamera` structure which specifies the half horizontal width (using half width since Assimp went with the half FOV convention). If `0.0` this would mean the camera is not orthographic, otherwise the value specifies the half width of the orthographic viewbox in scene units. The height if required can be then derived from the aspect.

This should not break exiting importers/exporters since the default would be `0.0` and only those imports/exporters that inspect/set the value would do anything with it. I'll create a pull request with this implemented and with the glTF2 importer updated to use it, if other formats support orthographic cameras they could be added as well later on.

Open to other suggestions but since I had to make a change to one of the core structures (`aiCamera`) I wanted to try and make the change as small as possible.

**Comment by kimkulling** [comment]
Ok, added as an inprovement. And this is a gap, right. I am just wondering if there are no other feature requests for that issue already in our list?

**Comment by ardenpm** [comment]
I did have a search through the issues before posting and couldn't find anything but I might not have hit upon the right terminology. Note I do have an open pull request for the suggested addition, however it also includes something ambiguous in glTF that I am trying to get clarified with Khronos.
