### ISSUE TITLE
Similar code in samples SimpleOpenGL and SimpleTexturedOpenGL.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3031]
The following functions are defined in both **SimpleOpenGL** and **SimpleTexturedOpenGL** samples.

- color4_to_float4
- set_float4
- apply_material
- recursive_render

**color4_to_float4** implementations are identical in both samples, except a few syntactic differences.

**set_float4** implementations are identical in both samples.

The functions **apply_material** and **recursive_render** feature similar implementations in both samples but with a few control flow and syntactic differences.

**Comment by kimkulling** [comment]
Right, techdept. If you want to help it would be really great if you could provide a small pull-request for that issue. Thanks!

**Comment by malortie** [comment]
@kimkulling 

Yes, I should be able to come up with a PR for this in the upcoming days.

**Comment by malortie** [comment]
@kimkulling 

I believe merging both samples **SimpleOpenGL** and **SimpleTexturedOpenGL** would be an appropriate way to solve the duplicated code. Both samples almost do the same thing. **SimpleTexturedOpenGL** uses the Windows API, but it could be adjusted to use FreeGlut as seen in **SimpleOpenGL**. This would allow us to have a running cross-platform textured example.

What are your thoughts on this? Please let me know.

**Comment by kimkulling** [comment]
Duplicated to https://github.com/assimp/assimp/issues/4575 .
I will close this issue.
