### ISSUE TITLE
[FATAL] SplitByBoneCountProcess::SplitMesh goes into infinite loop

### ISSUE THREAD

**Issue by Nimer-88** [assimp/assimp#3037]
When loading glTF file SplitByBoneCountProcess goes into infinite loop.

The importer flags I'm using are `aiProcess_CalcTangentSpace | aiProcess_Triangulate | aiProcess_SortByPType | aiProcess_GenNormals | aiProcess_SplitLargeMeshes | aiProcess_FlipUVs | aiProcess_RemoveComponent | aiProcess_SplitByBoneCount | aiProcess_RemoveRedundantMaterials | aiProcess_JoinIdenticalVertices`. The model that causes the infinite loop is https://sketchfab.com/3d-models/kako-059ddf8d773748a0aa32c778897e711e.

**Comment by NukeBird** [comment]
https://github.com/assimp/assimp/issues/2837

**Comment by NukeBird** [comment]
actually problem is worse, it causes memory leak too

**Comment by Nimer-88** [comment]
Note: it's highly likely that it's long standing issue in `SplitByBoneCountProcess` which mentioned glTF just unearthed. Since I added the test sample, it should be quite easy to repro.

**Comment by kimkulling** [comment]
Thanks a lot for that.

**Comment by Nimer-88** [comment]
#3038 contains the fix.

**Comment by Nimer-88** [comment]
#3039 fix for glTF2 importer causing this issue

**Comment by Nimer-88** [comment]
#3040 fix for the split by bone count process infinite loop

**Comment by NukeBird** [comment]
Wow! You did a great job, thank you!

**Comment by kimkulling** [comment]
@Nimer-88 Thanka a lot for your support. I will close it, because https://github.com/assimp/assimp/pull/3040 has closed it
