### ISSUE TITLE
General code quality

### ISSUE THREAD

**Issue by Nimer-88** [assimp/assimp#3041]
Hey guys,

I would like to start a discussion with you on the general code quality & principles in the assimp. For example, the code here tends be exception driven, yet lots of exceptions are being thrown to notify about critical failures. Having these two things in one code often leads to memory leaks. Another issue is general length and complexity of the methods in the code - 300+ lines of for loops, nested ifs and while loops on top of early returns and exceptions doesn’t really make the code approachable.

My proposition would be to use smart pointers when applicable and split many of the method into smaller, more understandable chunks.

What are your opinions on this?

**Comment by kimkulling** [comment]
Hi,

at first thanks for your feedback. And yes, we have some parts which are using long functions. 

To get rid of memory-leaks we are using the memory-sanitizer from clang. I think reworking all internal places where exceptions are used to use smart pointer instead will be a big task. And in respect to the stories, requests and issues which we currently have there are not enought ersources. And from my point of view only using smart pointer would be not a good idea. 

When the memory gets aout this is definitely an option which is already in use. Maybe you can show us your idea where and how to introduce smart-pointers?

**Comment by Nimer-88** [comment]
I was thinking about converting aiScene representation to be based on `std::unique_ptr` instead of raw pointers and seeing how it goes from there.

I would be happy to drive the effort considering available resources to you guys if you are ok with it.

If you're against converting raw pointers to smart pointers, could you please share your reasons against doing so?

**Comment by Nimer-88** [comment]
#3048 is perfect example of the issue that could be avoided if the code used smart pointers.

Having `setIOHandler(std::shared_ptr<IOSystem>)` and `std::shared_ptr<IOSystem> getIOHandler()` would make the code much simpler and safer.

**Comment by kimkulling** [comment]
Right, that is correct. You see, we have some history and the c-API has affected to code. 

Started to work on code-quality already, so I will close this issue Please open smaller issues for requests.
