### ISSUE TITLE
Issue compiling for Debug release

### ISSUE THREAD

**Issue by endevagames** [assimp/assimp#3043]
I can't for the life of me seem to link assimp as a static library. I can as a dynamic library. I've generated the project files using cmake but when I try to link assimp in debug I get:

`CL.exe exited with code 2'

When I double click on that error in Visual Studio 2019, it stops at the line
`<CL Condition="'%(ClCompile.PrecompiledHeader)' != 'Create' and '%(ClCompile.ExcludedFromBuild)'!='true' and '%(ClCompile.CompilerIteration)' == '' and @(ClCompile) != ''"`

I also get further errors such as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Sandbox.obj	Sandbox	C:\DEV\projects\ProjectIRIS\Sandbox\Assimp.lib(Importer.obj)	1	

```

and 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in Sandbox.obj	Sandbox	C:\DEV\projects\ProjectIRIS\Sandbox\Assimp.lib(Importer.obj)	1	

```

But in release, it compiles and runs perfectly. Only in debug does it fail to compile and then subsequently try to link to the release version of Assimp. Does this have something to do with a preocmpiled header?

**Comment by kimkulling** [comment]
Have you tried the following step:

`cmake --build .`

after generating the project-files? Which command line have you used to generate a debug-configuration?

**Comment by endevagames** [comment]
@kimkulling When I try to build it that way I get this one error:

```
assimp-vc142-mtd.lib(DDLNode.obj) : error LNK2001: unresolved external symbol "private: static class std::vector<class
ODDLParser::DDLNode *,class std::allocator<class ODDLParser::DDLNode *> > ODDLParser::DDLNode::s_allocatedNodes" (?s_al
locatedNodes@DDLNode@ODDLParser@@0V?$vector@PEAVDDLNode@ODDLParser@@V?$allocator@PEAVDDLNode@ODDLParser@@@std@@@std@@A)
```

I'm not sure what this ODDLParser library is and why it's unable to be linked properly. It appears to be included in the source code so not sure why it's not compiling

**Comment by RichardTea** [comment]
The issue is in your "Sandbox" project linker settings.

From the error message, it looks like the Debug build of your "Sandbox" project is attempting to link to the Release version of Assimp (likely from an earlier build)

In MSVC, you *cannot* static link a library unless both have the same version of the MSVC runtime.
This is because the debug version of many parts (esp. containers) have a different size and layout for additional error checking.

It's common to use a "d" suffix for Debug to help with this.
("mt" was also used for the multi-thread version, but _everything_ should be mt by now so it's less useful)

**Comment by endevagames** [comment]
I found the problem. I'm using VS2019 and I needed to set the compiler option /bigobj for this to work as like in this issue: (https://github.com/assimp/assimp/issues/1708). I'm using premake rather than cmake so that might be where the discrepancy lies as it seems that issue was solved, Everything is compiling in Debug mode now
