### ISSUE TITLE
Still can't complete make, while making assimp using mingw

### ISSUE THREAD

**Issue by Hirosam1** [assimp/assimp#3044]
I still have the problem mentioned by @JekaS178RUS   on #2431, is mingw64 still not supported for assimp, or am I doing something wrong? the error log is identical as JekaS178RUS 
Thanks!

**Comment by cathera** [comment]
Hi, I am having the same problem here. Have you resolved the issue?

**Comment by Hirosam1** [comment]
> Hi, I am having the same problem here. Have you resolved the issue?

I am using assimp 4.1.0, I think the fix is scheduled [here](https://github.com/assimp/assimp/projects/4#card-33458513)  so I belive we have to wait till then. :)
