### ISSUE TITLE
Importing .STEP crashes to Assimp::CalcTangentsProcess::SetupProperties()

### ISSUE THREAD

**Issue by vhelin** [assimp/assimp#3052]
This might be a useless/invalid bug report to you guys as I'm using TriLib for Unity that's using Assimp, and I cannot give you the .STEP files (4+) that are all crashing to this same method, because they are under NDA, but this is what I get every time I try to open one of our .STEP files (from multiple sources). It seems Assimp is crashing? What could be the cause of this?

Thanks!

Stack Trace of Crashed Thread 23356:
0x1EF84057 (assimp) Assimp::CalcTangentsProcess::SetupProperties
0x1EF838A4 (assimp) Assimp::CalcTangentsProcess::SetupProperties
0x1EF6945D (assimp) Assimp::BaseProcess::ExecuteOnScene
0x1EF6EA56 (assimp) Assimp::Importer::ApplyPostProcessing
0x1EF6FA8D (assimp) Assimp::Importer::ReadFile
0x1EF64E6E (assimp) aiImportFileExWithProperties
0x1DE788F0 (Assembly-CSharp) TriLib.AssimpInterop._aiImportFileEx()
0x1DE787B8 (Assembly-CSharp) TriLib.AssimpInterop.ai_ImportFileEx()
0x1DE5A738 (Assembly-CSharp) TriLib.AssetLoaderBase.ImportFile()
0x1DE5A17C (Assembly-CSharp) TriLib.AssetLoaderBase.InternalLoadFromFile()
0x0F59EDA8 (Assembly-CSharp) TriLib.AssetLoader.LoadFromFile()
0x0F599FB0 (Assembly-CSharp) TriLibLoader.Start()

**Comment by kimkulling** [comment]
Are these step-files or IFC files?

**Comment by vhelin** [comment]
STEP-files I think. I only have two IFC files on my work computer...

**Comment by kimkulling** [comment]
I guess this is caused by an invalid model. Step-files are not supported at the moment.
