### ISSUE TITLE
FBX fail to render properly in assimpview 

### ISSUE THREAD

**Issue by razor85** [assimp/assimp#306]
Following FBX fails to render properly on AssimpView using:
(Win32 Binaries for 3.1.1)

https://www.dropbox.com/s/6n3kqelyd2zk365/Newcharacters008.fbx
The model has some mistakes but Autodesk FBX Review tool shows the model and animate it properly

**Comment by kimkulling** [comment]
Deprecated because the model is gone. Sorry.
