### ISSUE TITLE
Model import error:  Chunk is too large

### ISSUE THREAD

**Issue by xin122** [assimp/assimp#3061]
I am sorry for asking this question, I see a issue and developers fix it. but this question still happened.
in my project .I use assimp 4.0.1 ,cmake and mingw to build assimp(built in windows). It occurs when i try to open a .3ds model. I try to use mingw32-make -mno-ms-bitfields ,but it doesn't work.

```
mingw32-make[2]: *** No rule to make target 'contrib/zlib/libzlibstatic.a', needed by 'code/libassimp.dll'.  Stop.
CMakeFiles\Makefile2:325: recipe for target 'code/CMakeFiles/assimp.dir/all' failed
mingw32-make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

when I run  mingw32-make -j16 before mingw32-make -mno-ms-bitfields, it can pass,but it does not work,so is there any good idea with it ? Several years age many people talks about it ,but no one can tell a good solution.

**Comment by kimkulling** [comment]
Please upgrade to assimp-5.0.1 and try it again. We make a lot of changes here and hopefully this issue s fixed already.
