### ISSUE TITLE
Can't compile CMake 3.16.5 generated assimp 5.0.1 project with xcode 11.3.1 on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by sbroumley** [assimp/assimp#3073]
Using latest cmake 3.16.5, I generated assimp 5.0.1 xcode project and load with xcode 11.3.1 on. macOS Catalina 10.15.3

Immediately upon compiling I get the follow error: 

> /Users/steve/TheMindAtWork/Development/External/assimp-5.0.1/code/Assbin/AssbinLoader.cpp:53:10: fatal error: 'Assbin/AssbinLoader.h' file not found
> #include "Assbin/AssbinLoader.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

Taking a quick look at the xcode settings, it appears all the correct include paths are there.
Has anyone else hit this issue?
thanks

**Comment by maiqingqiang** [comment]
me too

**Comment by maiqingqiang** [comment]
Using latest cmake 3.18.2, I generated assimp 5.0.1 xcode project and load with xcode 11.6 on. macOS Catalina 10.15.6

**Comment by kimkulling** [comment]
Ok, thanks for your update.
