### ISSUE TITLE
What is the best way to manage animations?

### ISSUE THREAD

**Issue by rahul-deshmane** [assimp/assimp#3080]
I have loaded a .fbx file, which contains the mesh as well as skeletal animation. I can change the animation based on numpad key press
```
	if (scene->HasAnimations())
	{
		if (scene->mAnimations[_current_anim_index]->mTicksPerSecond != 0.0)
		{
			ticks_per_second = (float)scene->mAnimations[_current_anim_index]->mTicksPerSecond;
		}
		else
		{
			ticks_per_second = 25.0f;
		}
	}
```
However, there are other soliders in my game who have the same animations. With the above approach I would have separate fbx file for each soldier. This would duplicate the animation/skeltal information.

1. I would like to keep animation files seperate from the mesh files and they apply these animations on the character depending on the context.
2. How can this be achieved. Will I have to maintain several scene objects per soldier?

**Comment by rahul-deshmane** [comment]
Thank you for replying Kim.
Yes, I do plan to make use of instancing eventually.
However, I am curious to know, how can I manage it using ASSIMP for a
single soldier, if i decide to keep skin and the animations separate.
1. Will I have to maintain a list of importers(1 for the skin and one for
"each" animation file)
2. Each importer will have it's corresponding scene. Hence I will have to
store a list of scenes as well.
3. Does Switching of animation on keyboard event means changing the scene
Is there a sample code available, somewhere for this kind of scenario?

Thanks
Rahul

**Comment by kimkulling** [comment]
The process could be like:

- Import you soldier
- Store the assimp-data (tha aiScene) into your own scene management tools
- Use this to render the data. Assimp will not provide the optimal solution for your own renderer
- Swithing animations by keys shall only switch the different animation channels of your scene representation in your scene
