### ISSUE TITLE
vertices lost in same position

### ISSUE THREAD

**Issue by Ubpa** [assimp/assimp#3081]
Assimp will make no vertices referenced by more than one face as default when loading *.obj, and we can use `aiProcess_JoinIdenticalVertices` to jont those identical vertices. But it will make vertices in same position join, and change the topology.

How to retain the original topology? I just want to get original mesh.

**Comment by Ubpa** [comment]
example
```
# 7 vertices and 3 faces
v 0 0 0
v 0 0 1
v 0 1 1
v 0 1 0
v 0 0 1
v 0 1 1
v 0 0 2
f 1 2 3
f 1 3 4
f 5 6 7
```
assimp will give me 9 vertices and 3 faces as default
if I use `aiProcess_JoinIdenticalVertices`, I will get 5 vertices and 3 faces
but I want 7 vertices and 3 faces

**Comment by kimkulling** [comment]
This is currently not supported. The OBJ-format is optimized for size, assimp is optimized for render-perforance. So our internal vertex-structure will not store the original vertex structure. 

Maybe we can think about a layer which maps the original data to the render-data. Any opinions?
