### ISSUE TITLE
Terragen importer is broken on x64 Platform

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#3093]
When trying to import the terragen-examples the loading breaks caused by the following exception:

`End of file or read limit was reached.`

**Comment by turol** [comment]
Bisected.
e8d2b840178b2b22336eb02b2535f32f3d5cc37b is first bad commit.

@kimkulling Please 
1. Don't make monster commits like this
2. Make sure all of your commits build on all platforms. I had to make a lot of local fixes during bisect because many commits were just completely broken.

**Comment by kimkulling** [comment]
That is the reason for having our CI. I am wondering why there was not red build. Which platforms have I missed?

And you are right: I will avoid these in the future, sorry for that.

**Comment by turol** [comment]
There was a test but it was commented out. You might want to check all the other tests and then that all formats have a test.
