### ISSUE TITLE
X3D importer converts polylines into polygons

### ISSUE THREAD

**Issue by mvidiassov** [assimp/assimp#3101]
Assimp (5.0.1) imports from X3D IndexedLineSet as a polygon.
How to reproduce:
`assimp export IndexedLineSet.x3d IndexedLineSet_exported.x3d`
The input file has IndexedLineSet, the output file has IndexedFaceSet.
In addition 
`assimp info IndexedLineSet.x3d `
reports two meshes. while the dump 
`assimp dump IndexedLineSet.x3d`
has only one mesh.
Files used:
[X3D_IndexedLineSet_Bug.zip](https://github.com/assimp/assimp/files/4403046/X3D_IndexedLineSet_Bug.zip)

**Comment by andre-schulz** [comment]
@kimkulling would you be interested in a PR to fix this?
