### ISSUE TITLE
GitHub "Sponsor" button is broken

### ISSUE THREAD

**Issue by jakrams** [assimp/assimp#3102]
I would expect this button to do something other than this:

![image](https://user-images.githubusercontent.com/36191331/77933407-0fe91c00-72af-11ea-9b95-aacf7876ee21.png)

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3114

**Comment by jankrassnigg** [comment]
Thanks for fixing. Clicking on the Patreon link I noticed a typo, in case you want to fix it:

![image](https://user-images.githubusercontent.com/6001174/78105336-3a42f280-73f1-11ea-9fb7-5984e34d3780.png)

**Comment by kimkulling** [comment]
Thanks fpr the hint, I just have fixed the typo.
