### ISSUE TITLE
Hard-coded /WX flag over-rides cmake option

### ISSUE THREAD

**Issue by jimfoltz** [assimp/assimp#3103]
https://github.com/assimp/assimp/blob/b6b3b39bb363cf6c6658ffe051e693bd36f08985/CMakeLists.txt#L258

Having `/WX` hard-coded here means it is always set which over-rides the `ASSIMP_WERROR` option when the compiler is `MSVC`.

**Comment by kimkulling** [comment]
Good catch, will take care.

**Comment by kimkulling** [comment]
I will enable them all the time. So no surprises from thCI anymore.

**Comment by haampie** [comment]
Hi @kimkulling, can you please disable unconditional -Werror and instead just enable it in your CI? The issue is you can't possibly know what warnings future compilers will give, and the fact is that they will produce warnings. See e.g. #4450
