### ISSUE TITLE
I want to ask. Can assimp convert obj files to COLLADA files?

### ISSUE THREAD

**Issue by simonasdmd** [assimp/assimp#3106]
I want to ask. Can assimp convert obj files to COLLADA files?

**Comment by simonasdmd** [comment]
hi~
Another question
Use this script to compile the available assimp
![image](https://user-images.githubusercontent.com/42527845/77981992-d3183600-733d-11ea-8ed7-f332b91b43c7.png)

**Comment by kimkulling** [comment]
Sure, you can use the command-line tool from assimp and export it as a Colladafile:

For instance after building assimp from master the following command started from bin/release works:

`> assimp.exe export ..\..\test\models\OBJ\spider.obj spider.dae`

The output will be located in the same folder where your command war executed.

**Comment by simonasdmd** [comment]
@kimkulling 
hi~
When I use assimp.exe, I find that when the obj file exceeds 1g, an error will be reported. The prompt is too large. But in fact, 1g obj files are very common. Is there any way to modify this?
