### ISSUE TITLE
window-cmake-android-so

### ISSUE THREAD

**Issue by mbjgit** [assimp/assimp#3107]
Hello:
https://blog.csdn.net/camellhf/java/article/details/78065622
Follow this blog，I download last assimp(5.0) zip and get "undefined reference to Assimp:DumpSecenToAssxml",So How can I resovle thie issues?
1、python H:/Android/sdk/ndk-bundle/build/tools/make_standalone_toolchain.py --arch=arm64 --stl=libc++ --api=24 --install-dir=android-toolchain-24-llvm-arm64v8a
2、![image](https://user-images.githubusercontent.com/20197609/77980272-77e44480-7339-11ea-8382-8eb14ad4d0b0.png)
3、![image](https://user-images.githubusercontent.com/20197609/77980286-816dac80-7339-11ea-81cf-b3d5590142cc.png)

**Comment by kimkulling** [comment]
Assimp:DumpSecenToAssxml <- this looks like a typo, name should be Assimp:DumpSceneToAssxml
