### ISSUE TITLE
3DMax to FBX export increases the size of the model 

### ISSUE THREAD

**Issue by liangpeng1988** [assimp/assimp#3118]
Car the Obj file size is 34MB
Using 3DMAX to export FBX binary file size is 10MB  （3dmax ---> fbx --->10MB）
Using assimp  Export FBX binary file size 39MB（Assimp ---> fbx --->39MB）
I want the size of the assimp export FBX to be 10MB
I don't know if I have made the problem clear, because my English is not good.

**Comment by kimkulling** [comment]
Just updated the title. Thanks a lot for the tip!

**Comment by kimkulling** [comment]
Just checked this. The blown model was caused by the generated triangles. One option could be to enable the optimization steps in the post-processing.
