### ISSUE TITLE
Missing animations

### ISSUE THREAD

**Issue by sagaceilo** [assimp/assimp#312]
Hello,

I'm trying to implement Assimp's animations to convert to my binary file and I found that no matter what file I'll try to import, there is no animation in Assimp scene.

I'm using regular loading postprocesses without debone.

```
    unsigned long long flags = ImporterConfig.process_chain | aiProcess_Triangulate | aiProcess_LimitBoneWeights;

    flags &= ~aiProcess_Debone;
```

and 

```
    aiPropertyStore * store = aiCreatePropertyStore();

    aiSetImportPropertyFloat( store , AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE , ImporterConfig.smooth_angle );
    aiSetImportPropertyInteger( store , AI_CONFIG_PP_ICL_PTCACHE_SIZE , ImporterConfig.cache_size );
    aiSetImportPropertyInteger( store , AI_CONFIG_PP_SLM_VERTEX_LIMIT , ImporterConfig.vertex_limit );
    aiSetImportPropertyInteger( store , AI_CONFIG_PP_SLM_TRIANGLE_LIMIT , ImporterConfig.triangle_limit );

    const aiScene * scene = aiImportFileExWithProperties( filename.c_str() , flags , NULL , store );
```

Now scene is loaded (it isn't NULL) bu the scene->HasAnimations() return always false.

Is there any special care of models with animations (some config or postprocess that I have to use). I looked at code of the viewers but nothing found like that.
I checked files in MotionBuilder, 3DsMax and Blender and every one has proper animations. Even Open3D Viewer that uses Assimp loads animations.
I'm attaching here some models to veryfy ( https://dl.dropboxusercontent.com/u/7019528/Models.zip ).

Any idea what I'm doing wrong ? Thanks for help :)

**Comment by andy83** [comment]
Can u tell me what it was? I'm having the same issue and no clue how to solve it...

**Comment by vovan4ik123** [comment]
me too have this problem. animation dissapear from scene when im want draw model. where is problem????
