### ISSUE TITLE
Sample projects and Assimp viewer unable to build due to warnings treated as errors.

### ISSUE THREAD

**Issue by malortie** [assimp/assimp#3123]
Recent changes have set warning level to **/W4**, and **/WX** (treat warnings as errors).

The following projects would fail to build because of additional warnings treated as errors:

- ~~SimpleOpenGL~~ (Fixed in https://github.com/assimp/assimp/pull/3124)
- ~~SimpleTexturedDirectx11~~ (Fixed in https://github.com/assimp/assimp/pull/3127)
- ~~SimpleTexturedOpenGL~~(Fixed in https://github.com/assimp/assimp/pull/3124)
- ~~Assimp viewer~~ (Fixed in https://github.com/assimp/assimp/pull/3129)

**Comment by kimkulling** [comment]
Thanks for the update. Why I haven't checked them? Sorry for that!

**Comment by malortie** [comment]
@kimkulling 

I currently have a fix for each sample project, as well as for the Assimp viewer. You can view these changes [here](https://github.com/malortie/assimp/commit/6b15586e192889d0fd32ca3ce50650817f83d040). I will submit PRs per project in order to keep them small and easier to review.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3124

**Comment by malortie** [comment]
@kimkulling 

Please, would it be possible to reopen the issue? I was thinking of closing the issue once all projects would have been fixed. I apologize, as I should have explained it in my previous answer.
