### ISSUE TITLE
ASSIMP_DOUBLE_PRECISION:ON warnings

### ISSUE THREAD

**Issue by dbgarlisch** [assimp/assimp#3128]
1. Do I need to be concerned about these warnings?
2. Am I really getting double precision with these truncations?
3. Do I really need double precision? Some of the grids with which we deal have a large dynamic range.

With **ASSIMP_DOUBLE_PRECISION:ON**, there are numerous truncation warnings similar to:

`...\assimp-5.0.0\code\3DS\3DSExporter.cpp(563): warning C4244: 'argument': conversion from 'const ai_real' to 'float', possible loss of data`

and

```
...\assimp-5.0.0\code\FBX\FBXExporter.cpp(2175): warning C4244: 'argument': conversion from 'const TReal' to 'const _Ty', possible loss of data
        with
        [
            TReal=ai_real
        ]
        and
        [
            _Ty=float
        ]
```

**Comment by RichardTea** [comment]
Several 3D formats only have 32bit float precision, so simply can't do double no matter what.

The casts should be made explicit to remove the warnings though.

**Comment by kimkulling** [comment]
So this is an issue :). I will try to take care.

**Comment by dbgarlisch** [comment]
Is this reopened for me to close?

**Comment by contriteobserver** [comment]
@dbgarlisch does #3683 resolve this issue?

**Comment by kimkulling** [comment]
This shall be the case, yes.
