### ISSUE TITLE
Compilation error in MinGW (ZipArchiveIOSystem.cpp)

### ISSUE THREAD

**Issue by daniilpetrov** [assimp/assimp#3144]
There is an error during the build:
> D:\NativeEngine\EngineSources\DevelopmentKits\GraphicFormats\Assimp 5.0.1\assimp-master\code\Common\ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
> D:\NativeEngine\EngineSources\DevelopmentKits\GraphicFormats\Assimp 5.0.1\assimp-master\code\Common\ZipArchiveIOSystem.cpp:161:30: error: invalid conversion from 'uLong (*)(voidpf, voidpf, void*, uLong)' {aka 'long unsigned int (*)(void*, void*, void*, long unsigned int)'} to 'read_file_func' {aka 'unsigned int (*)(void*, void*, void*, unsigned int)'} [-fpermissive]
>   161 |         mapping.zread_file = read;
>       |                              ^~~~
>       |                              |
>       |                              uLong (*)(voidpf, voidpf, void*, uLong) {aka long unsigned int (*)(void*, void*, void*, long unsigned int)}
> D:\NativeEngine\EngineSources\DevelopmentKits\GraphicFormats\Assimp 5.0.1\assimp-master\code\Common\ZipArchiveIOSystem.cpp:162:31: error: invalid conversion from 'uLong (*)(voidpf, voidpf, const void*, uLong)' {aka 'long unsigned int (*)(void*, void*, const void*, long unsigned int)'} to 'write_file_func' {aka 'unsigned int (*)(void*, void*, const void*, unsigned int)'} [-fpermissive]
>   162 |         mapping.zwrite_file = write;
>       |                               ^~~~~
>       |                               |
>       |                               uLong (*)(voidpf, voidpf, const void*, uLong) {aka long unsigned int (*)(void*, void*, const void*, long unsigned int)}
> D:\NativeEngine\EngineSources\DevelopmentKits\GraphicFormats\Assimp 5.0.1\assimp-master\code\Common\ZipArchiveIOSystem.cpp:164:30: error: invalid conversion from 'long int (*)(voidpf, voidpf, uLong, int)' {aka 'long int (*)(void*, void*, long unsigned int, int)'} to 'seek_file_func' {aka 'long int (*)(void*, void*, unsigned int, int)'} [-fpermissive]
>   164 |         mapping.zseek_file = seek;
>       |                              ^~~~
>       |                              |
>       |                              long int (*)(voidpf, voidpf, uLong, int) {aka long int (*)(void*, void*, long unsigned int, int)}
> mingw32-make[2]: *** [code\CMakeFiles\assimp.dir\build.make:175: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.obj] Error 1
> mingw32-make[2]: Leaving directory 'd:/NativeEngine/EngineSources/DevelopmentKits/GraphicFormats/Assimp 5.0.1/assimp-master'
> mingw32-make[1]: *** [CMakeFiles\Makefile2:249: code/CMakeFiles/assimp.dir/all] Error 2
> mingw32-make[1]: Leaving directory 'd:/NativeEngine/EngineSources/DevelopmentKits/GraphicFormats/Assimp 5.0.1/assimp-master'
> mingw32-make: *** [Makefile:129: all] Error 2

I changed code to this:
```
#ifdef ASSIMP_USE_HUNTER
        mapping.zopen_file = (open_file_func)open;
        mapping.zread_file = (read_file_func)read;
        mapping.zwrite_file = (write_file_func)write;
        mapping.ztell_file = (tell_file_func)tell;
        mapping.zseek_file = (seek_file_func)seek;
        mapping.zclose_file = (close_file_func)close;
        mapping.zerror_file = (error_file_func)testerror;
#else
        mapping.zopen_file = (open_file_func)open;
        mapping.zread_file = (read_file_func)read;
        mapping.zwrite_file = (write_file_func)write;
        mapping.ztell_file = (tell_file_func)tell;
        mapping.zseek_file = (seek_file_func)seek;
        mapping.zclose_file = (close_file_func)close;
        mapping.zerror_file = (error_file_func)testerror;
#endif
```
Everything was built. Is there more correct solution of this issue?

**Comment by turol** [comment]
Casting function pointers is not allowed, will result in undefined behavior and likely crash at runtime. The correct fix is to change the function type to match what is expected by the library.

**Comment by daniilpetrov** [comment]
And how is it done? I only define CMAKE_BUILD_TYPE in CMake and turn off ASSIMP_BUILD_ASSIMP_TOOLS and ASSIMP_BUILD_TESTS, and that's all. Then I try to compile and get an error. How can I build Assimp without changing your code?

**Comment by daniilpetrov** [comment]
Also it was useful to turn on HUNTER_ENABLED in CMake. What is it used for and how to avoid it?

**Comment by RichardTea** [comment]
I think the zlib was updated recently, the function signatures must have changed and these not updated to match the new signatures.

**Comment by RichardTea** [comment]
I am now reasonably sure this is a problem with include paths in your build.

The Assimp zconf.h has:
`typedef unsigned long  uLong; /* 32 bits or more */`

I suspect that your MinGW build system is mixing up headers between the Assimp zlib and another version of zlib on your build machine.

**Comment by Lord-Kamina** [comment]
Hi, I have similar errors using mxe with mingw-w64 7.0.0 and GCC 8.4.0

Attached is a build log...


[assimp_i686-w64-mingw32.log](https://github.com/assimp/assimp/files/4839883/assimp_i686-w64-mingw32.log)
