### ISSUE TITLE
Potential Bugs found by Sonarcloud, Coverity Scan and Cppcheck

### ISSUE THREAD

**Issue by qarmin** [assimp/assimp#3151]
For more bugs look at:
- Sonarcloud(online) - https://sonarcloud.io/project/issues?id=qarmin_assimp&resolved=false&types=BUG
- Cppcheck(offline) - https://gitlab.com/qarmin/assimp/-/jobs/507881326/artifacts/download

Self assignment 
https://github.com/assimp/assimp/blob/7e5a0acc48efc54d7aa7900c36cd63db1fbeec9b/code/MS3D/MS3DLoader.cpp#L183-L184
m is always rewritten
https://github.com/assimp/assimp/blob/9b694a86457070189bcb4c61eab26f6648b4d639/code/M3D/m3d.h#L4227-L4232
Missing break in switch(probably needs fall-trough) 
https://github.com/assimp/assimp/blob/f7cab11a80850c8e679b4a99d30cf63601c09900/code/FBX/FBXExportProperty.cpp#L278-L289
https://github.com/assimp/assimp/blob/f7cab11a80850c8e679b4a99d30cf63601c09900/code/3DS/3DSLoader.cpp#L277-L285
Identical branches if/else
https://github.com/assimp/assimp/blob/f7cab11a80850c8e679b4a99d30cf63601c09900/code/Importer/IFC/IFCOpenings.cpp#L1193-L1206
Strange code 
https://github.com/assimp/assimp/blob/f7cab11a80850c8e679b4a99d30cf63601c09900/code/COB/COBLoader.cpp#L929-L934

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3602
