### ISSUE TITLE
Export Example

### ISSUE THREAD

**Issue by dbgarlisch** [assimp/assimp#3159]
I am trying to export simple grid data (no normals, no materials, no UVs, etc). I only have vertices and the tri/quad/poly connectivity data.

I found this [old issue](https://github.com/assimp/assimp/issues/203) that shows rough examples. Is there a better, more _official_ code example to which you can point me that covers proper `aiScene` and `Assimp::Exporter` usage in more detail? I have not been able to find anything in assimp docs. Also, Google has failed me.

**Specific Q:**
Since I don't have vertex normals, UVs, or materials, do i still need to set the relevant scene pointers to something or can I leave them nullptr?  For example, from post:
```
scene.mMaterials = new aiMaterial*[ 1 ];
scene.mMaterials[ 0 ] = nullptr;
scene.mNumMaterials = 1;
scene.mMaterials[ 0 ] = new aiMaterial();
```

Can I set `scene.mMaterials = nullptr;`?

Thanks!

**Comment by RichardTea** [comment]
There must always be one material, as most formats explicitly require one.
It can simply be a single colour though.

**Comment by JC3** [comment]
I've added yet another example at https://github.com/assimp/assimp/issues/203#issuecomment-817188468 if it helps anybody.
