### ISSUE TITLE
The list of exporting formats

### ISSUE THREAD

**Issue by daniilpetrov** [assimp/assimp#3163]
Where can I get the full list of formats of the export function GetExportFormatDescription()?

**Comment by kimkulling** [comment]
Three places:

- When running cmake you can see the list of supported importers and exporters in the console-output
- You can find it on the readme.md on the github-project-space
- You can find it on assimp.org

**Comment by daniilpetrov** [comment]
Which formats correspond to numbers 19, 20 and 21?

**Comment by kimkulling** [comment]
19 and 20 are glFT, first version. HMB: Used to load 3D GameStudio HMP files (terrains)

**Comment by daniilpetrov** [comment]
I haven't found the list of formats anywhere. Here's what I installed according to the content of exported files:
0 – Collada DAE
1 – SDKMESH X
2 – CAD STEP
3 – Wavefront OBJ with MTL
4 – Wavefront OBJ
5 – Stereolithography STL (text)
6 – Stereolithography STL (bin)
7 – PLY (text)
8 – PLY (bin)
9 – Autodesk 3DS
10 – GLTF2
11 – GLB2
12 – GLTF
13 – GLB
14 – Assimp (bin)
15 – Assinp (XML)
16 – X3D
17 – FBX (bin)
18 – FBX (text)
19 – ???
File contents:
> 3DMOа   x^уput‘c ыCgx’т+фт“І|=CЂ‚!ѕЋи БћЃ„AвvXPHрTe5`‰H|€R|Щф~€~°82д&†M¦]-2ЄЏБб °ы у}]ѓ=ЂЖњЊL,LL¬МLЖ,М\lLЖЊјЬLј\јЖмММ\МЬЊМЖ¬М<l<мL<@ЊмLЊЬЊ Ѕ н ЅЊ н ЅњМ н ЅlL н Ѕ,Њ н Ѕ¬М нюѕ.Ж Dќ9Ї

20 – ???
Assimp::Exporter::GetErrorString() outputs:
> Assimp configured without M3D_ASCII support

21 – ???
File contents:
> PK    ВЄ–PлQ&«З   N     [Content_Types].xml…ђЫj1@ЯэЉђЧІ›mҐWЪъъCvц‚Й$$іўпDAgrrМr}фN0е)P«ЯлF+$є‰†Vп¶›к[ЇW‹ец1+a)«Vй‘9ю“н€r"’јх!y`У`"Ш=h>љжЛШ@ЊД‹Эц0;VяGЩ—t‘&tY«Я+[‚e	1єЙcФ=¤Є[¦–ї&ЏSМoheћu|иРЅщ»ьіу@s–з$w©d.Љ{Ж\ОіZњPK    ВЄ–PЉ@--   s	     3D/3DModel.model­–M‹Ы0†пы+†йЩ‘?тYв,…ІРCйЎ-=ЕV6*–e$9$эх«DіKІ,Д‰ 	iћwFЈЙXЛЗЅЄ`'Њ•єО1Еў.t)лзяz‚жшёzX*]Љ ЪZє•¬*©„=^Ы·О5џіЕV(nGJF[ЅqЈB+–•ЉЧн†®5^—Ъ–ЖЙ„Е)zi#¬nM!мСЌpјдЋCН•Исзiг‹µВэ}ТFq‡«?|'6FЧ~¬я‰ВБ7ХhгѓYІWЪ­№хЎшUЙ+Іф‡CZ&нЇbГЫК}'#(Ґm*~(tҐMЋџвС4ьжYvЎйtр/ѓXXAp‡Ж{8еO§І[?ш<;ОyњЉ=мsЊвСбђгiьяєА.ЊЮЫt0№Sж-њЁѓЇЁ‹РMОўБBє[©[P·¤{ёёoтЕЅ3~“С0u;X)хкџЖыЊъюк#QЯх¬YvЦ-ќпёхsu1‡]вy„]zlн°ЛrLљРйЎ	›м=ђ`ЂЙu`ЂY жЧЃ…"I®#IJLFМё3!fJМ¬3'fAщЉЇ3i4%&лАЊ‰™3нАМ€™іиp™tэЭЦҐ Ё2*Ѓмг`з%ЗиыНВзэ8;і¬[Y•~”N(&A0<h—ќ^«‡PK    ВЄ–PGПєҐґ        _rels/.relseOЙВ0ЅыaоvZ"bкE^¤~@H§6I*ъчNсb†ЃYЮv8ѕМ(ћва¬„"ЛAђХ®l'б^џЧ;8V«ГЌF•ш%цѓЏ‚16JиSт{ДЁ{2*fО“еKл‚Q‰ЗРЎWъЎ:ВMћo1ьr@µаµ %	Xћё®®Ў13sqi$0–ќХoOІfРБEЧ¦L;ѓec”ќZҐУ8+%жЕјяІ!§БEњjхPK[     ВЄ–PлQ&«З   N                   [Content_Types].xmlPK[     ВЄ–PЉ@--   s	               ш   3D/3DModel.modelPK[     ВЄ–PGПєҐґ                  &  _rels/.relsPK      ё   

22 – JSON for WebGL

**Comment by kimkulling** [comment]
Have you checked https://github.com/assimp/assimp/blob/master/Readme.md? Supported file-formats?

**Comment by daniilpetrov** [comment]
Do you have an exact list of formats defined by the Assimp::Exporter::GetExportFormatDescription() function? The information from link is too unclear!

**Comment by RichardTea** [comment]
The list of formats in a given Assimp build are listed by calling GetExportFormatDescription() for each index.

The "description" field in the returned struct contains the user-presentable name of the format.
21 is "The 3MF-File-Format"

Unit test "ExporterTest" demonstrates reading all the exporter descriptions

From the aiExportFormatDesc:

```
// --------------------------------------------------------------------------------
/** Describes an file format which Assimp can export to. Use #aiGetExportFormatCount() to
* learn how many export formats the current Assimp build supports and #aiGetExportFormatDescription()
* to retrieve a description of an export format option.
*/
struct aiExportFormatDesc
{
    /// a short string ID to uniquely identify the export format. Use this ID string to
    /// specify which file format you want to export to when calling #aiExportScene().
    /// Example: "dae" or "obj"
    const char* id;

    /// A short description of the file format to present to users. Useful if you want
    /// to allow the user to select an export format.
    const char* description;

    /// Recommended file extension for the exported file in lower case.
    const char* fileExtension;
};
```
