### ISSUE TITLE
Void function should not return anything

### ISSUE THREAD

**Issue by qarmin** [assimp/assimp#3179]
Don't know why compiler doesn't show error or warning when executing `return priv->mOrigImporter->GetMemoryRequirements(*in);`

Also there is unreachable code `ASSIMP_END_EXCEPTION_REGION(void);`

https://github.com/assimp/assimp/blob/dafff4da5d733c328c3077591de52842e326735d/code/Common/Assimp.cpp#L484-L497

**Comment by ThePistolKing** [comment]
Importer::GetMemoryRequirements returns void. It's perfectly legal C++ to return the void from another function like this. Also, ASSIMP_BEGIN_EXCEPTION_REGION and ASSIMP_END_EXCEPTION_REGION just expand into try and catch blocks, meaning the return statement is located in the try block, which is the normal way to do such things. So there's not really anything wrong here.

**Comment by kimkulling** [comment]
But when reading the code the expectation what will returned differs from the function prototype. So from my point of view this is not ok.

**Comment by kimkulling** [comment]
Sorry, now I understand. This one is not a bug.
