### ISSUE TITLE
Possible usage of invalid memory in clipper.cpp

### ISSUE THREAD

**Issue by qarmin** [assimp/assimp#3184]
Condition `while( isModified && m_SortedEdges )` shows that `m_SortedEdges` may be null but a little before is used `m_SortedEdges->prevInSEL = 0;` 
https://github.com/assimp/assimp/blob/455c4ceea483ea3a4762ecceb7c96c1fe8fbb69d/contrib/clipper/clipper.cpp#L2498-L2519

**Comment by hbina** [comment]
I think the code is correct, `e` is just an alias to `m_ActiveEdges`.

First, we check

https://github.com/assimp/assimp/blob/455c4ceea483ea3a4762ecceb7c96c1fe8fbb69d/contrib/clipper/clipper.cpp#L2500

Then create some super weird multiple aliases.

https://github.com/assimp/assimp/blob/455c4ceea483ea3a4762ecceb7c96c1fe8fbb69d/contrib/clipper/clipper.cpp#L2503-L2505

The entire relevant code for context.

https://github.com/assimp/assimp/blob/455c4ceea483ea3a4762ecceb7c96c1fe8fbb69d/contrib/clipper/clipper.cpp#L2498-L2519

**Comment by kimkulling** [comment]
I have updated the visible code. The nullptr-check avoids a possible nullptr-access and so the code is correct. 
@hbina Thanks for your investigation!
@qarmin MAny thanks for your review!
