### ISSUE TITLE
Android cannot find -lpthread

### ISSUE THREAD

**Issue by engineer1109** [assimp/assimp#3187]
ndk version: 20.0.5594570  

Compiled ld error.

Seems android has deleted the libpthread.so

Maybe it should be

```
IF( WIN32 )
    SET( platform_libs )
ELseif(ANDROID)
    SET( platform_libs )
ELSE()
    SET( platform_libs pthread)
ENDIF()
```

**Comment by kimkulling** [comment]
Thi issue only occurrs when Windows is the build target?

**Comment by engineer1109** [comment]
@kimkulling New Android Ndk could not find the libpthread.so.  It has been merged to the base runtime so.
