### ISSUE TITLE
Fix leak in FBXConverter

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#3190]
Just check sanitizer output to learn more about it.

**Comment by turol** [comment]
Failing test is `utFBXImporterExporter.importUnitScaleFactor`

**Comment by turol** [comment]
Leak is https://github.com/assimp/assimp/blob/08609feb54a813fd74164f6d09cc694d114428be/include/assimp/metadata.h#L317

Looks like if there already is an old value it's not freed.

**Comment by kkulling** [comment]
This one:
```
    scene->mMetaData->Set("UnitScaleFactor", factor * 2.0f);
    scene->mMetaData->Get("UnitScaleFactor", factor);

```

**Comment by turol** [comment]
Looks like you also need to always zero-initialize `mValues` on allocation or it ends up using uninitialized memory.

**Comment by kimkulling** [comment]
Right, fix is on its way.
