### ISSUE TITLE
mat->GetTexture()

### ISSUE THREAD

**Issue by waxenegger** [assimp/assimp#3199]
Hello,

I'm using assimp-3.3.1-19.fc30.src.rpm for my distro and when reading the Texture path I get an empty string when the content of the mtl is like this:

`map_Kd glass_dif.png`

When I debug I notice that the only reason I get this is that the data is prefixed by 4 '\0' characters before it actually starts so as a C_Str it's empty. Funnily enough the length info is accurrate and seems to have been calculated without this 4 char prefix.

I suppose I can work around by eliminating any leading '\0' but there are issues out there that hint at others having similar problems across various major versions.

Is there an alternative fix or a detail I'm missing?

![image](https://user-images.githubusercontent.com/1559229/80935825-c477df80-8e11-11ea-834c-9cec918343e2.png)

**Comment by kimkulling** [comment]
Have you tried to use the latest version of Asset-Importer-Lib? Version 3.3.1 is outdated. We have released 5,0,1 some months ago.

**Comment by waxenegger** [comment]
The workaround does the job but but I'll probably give the later version a try eventually. 

I figured it was kind of older, don't suppose the various distro packages are maintained by somebody from assimp, or are they? I'd be kind of neat if there was a newer package available, not that I haven't gotten libraries differently in the past or built them myself.

I thought I'd bring it up if for no other reason than it being documented in case somebody experiences the same issue.

Thanks for your comment.
