### ISSUE TITLE
Collada: Exporter discards root aiNode meshes

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#3201]
If the root aiNode transform is determined to be X-UP, Y_UP or Z_UP, all root node meshes and metadata will be discarded.

**Comment by RichardTea** [comment]
This occurs because Collada <visual_scene> nodes aren't allowed to have meshes, but can have multiple <node> children so must be considered the 'root' aiNode.
Should also create a virtual top-level node in this situation.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3205
