### ISSUE TITLE
Backward convert glTF2 to obj

### ISSUE THREAD

**Issue by SystemDiagnosticss** [assimp/assimp#3203]
Is it possible convert glTF2 to obj ?
If we have animation convert some one gltf-frame to obj ?

**Comment by kimkulling** [comment]
Aniomations are not supported in obj. But yes, you can import your glFT-file and export it as an obj-wavefront file. Just use the assimp commandline-tool for that task;

`assimp <your_file> export <your_file>.obj`

if I remember right,
