### ISSUE TITLE
GLTF2 Blendshape Import Bug: missing shapes

### ISSUE THREAD

**Issue by thomasbiang** [assimp/assimp#3206]
When I read in a standard gltf2 file from 
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube
It is supposed to be a cube with two blenshapes.

After read in, I find only one shape is there.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3207
