### ISSUE TITLE
I Want To Contribute an Enhancement to OBJ

### ISSUE THREAD

**Issue by dbgarlisch** [assimp/assimp#3217]
I posted an [issue a month ago](https://github.com/assimp/assimp/issues/3142) concerning the inflation of vertices during OBJ read. Yesterday, I spent several hours taking my first look at the assimp code in detail and stepped my way through the reading of an OBJ file into the assimp data structures using Visual Studio 2017.

I see where the point inflation is happening. I have an idea that should allow the topology to be better preserved during the read that takes into account the v, vn, and vt values.

However, I really would like to bounce these ideas off of someone that knows much more about OBJ use cases in the rendering world. My interest is strictly raw mesh data for use in the CFD world.

**Who would that rendering world contact be?**

**Comment by kimkulling** [comment]
Hi,
at first: thanks a lot for your investigations. If you want to get feedback on your solution there are two wasy to go from my point of view: 
- You can open a pull-request to sugget us how to fix your bug. Here the CI-pipeline will check if anything gets broken by your code.
- You can show in a small example your sulution here in the issue-report and we will check whether your solution will work.
