### ISSUE TITLE
Bad Merge: Duplicated source file

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#3238]
This commit duplicates the ColladaExporter.cpp source file:

https://github.com/assimp/assimp/commit/464d4cf99a30a5213696dbc6f38d84cf3005b4df

The file move was not properly merged into the source branch before merging into master

**Comment by RichardTea** [comment]
Caused by PR #3225

**Comment by kimkulling** [comment]
Thaks for the report.
