### ISSUE TITLE
CMakeListst.txt: Runtime output directory overridden

### ISSUE THREAD

**Issue by larioteo** [assimp/assimp#3239]
Hello,

I am building assimp over my own project. Today after updating the sources (master branch) I had a problem after compiling the shared library. Compilation finished successfully but the compiled library was missing in the output folder. After some research I found the problem in the main CMakeLists.txt:

\# If this is an in-source build (CMAKE_SOURCE_DIR == CMAKE_BINARY_DIR),
\# write the library/executable files to the respective directories in the
\# source tree. During an out-of-source build, however, do not litter this
\# directory, since that is probably what the user wanted to avoid.
IF ( CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR )
  SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/bin" )
  SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/lib" )
  SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/bin" )
ELSE()
  SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/lib")
  SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/bin")
  SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/bin")
ENDIF ()

The 'ELSE()'-block overriddes my global project configuration and the library is put under '"${CMAKE_CURRENT_BINARY_DIR}/bin'.

As workaround I tried disabling the 'ELSE()'-block ... result: -> It works as expected.

I don't know the background why this changes where made, neither I don't know if they are needed by critical parts. Would it be possible to remove the 'ELSE()'-block?

**Comment by kimkulling** [comment]
I guess it is just a typo. Thanks for the report.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3363
