### ISSUE TITLE
Blender UV unwrap issue

### ISSUE THREAD

**Issue by blitz-research** [assimp/assimp#325]
I'm getting the following exception when trying to import a .blend scene that contains a UV unwrapped mesh:

Number of UV faces is larger than the corresponding UV face array (#1)

This happens even with a simple 'empty scene' cube, eg: create a new scene; go into edit mode; select Mesh->UV Unwrap->Unwrap; save scene; load it and BAM! If I save the scene before UV Unwrap, it works OK.

Might be something I'm doing, but it's weird. If I export as .obj I can load it OK.

Here's the UV unwrapped scene:

http://www.monkey-x.com/mak/cube2.blend

**Comment by jgwinner** [comment]
I just ran into the same exact issue - created a cube, texture mapped it, saved, opened it with Substance Painter and got "BLEND: Number of UV faces is larger than the corresponding UV face array (#1)"

So, if it's a bug, it's still there (I realize it's been a while). It might be that a simple cube isn't setup quite right either, but although I'm not a CGI artist I don't see anything obviously wrong with it.
