### ISSUE TITLE
Unreasonable change to tmp variable

### ISSUE THREAD

**Issue by heitaoflower** [assimp/assimp#3253]
I think there is something unreasonable with tmp.
since the change to tmp only effect inside, further more the second tmp++ is really a redundent operation.

so shall need to refactor the function?

`static bool isDataDefinitionEnd(const char *tmp) {
    if (*tmp == '\\') {
        tmp++;
        if (IsLineEnd(*tmp)) {
            tmp++;
            return true;
        }
    }
    return false;
}`

**Comment by kimkulling** [comment]
Hi, were have you find the code?

**Comment by heitaoflower** [comment]
There is a static function of isDataDefinitionEnd at line 263 in file ObjFileParser.cpp.

So I hope u guys check it.

**Comment by kimkulling** [comment]
Seems to be useless, right.
