### ISSUE TITLE
Copy paste FieldFlag_Pointer flag in BlenderDNA.inl

### ISSUE THREAD

**Issue by qarmin** [assimp/assimp#3255]
```
 if ((FieldFlag_Pointer|FieldFlag_Pointer) != (f->flags & (FieldFlag_Pointer|FieldFlag_Pointer))) {
```

https://github.com/assimp/assimp/blob/a874facbbfec522ee6219ddcdeccf6d7ef0d1fe4/code/AssetLib/Blender/BlenderDNA.inl#L243

**Comment by kimkulling** [comment]
Is a sanity check. I will perform this test only in DEBUG mode.

And thanks a lot for the investigation!
