### ISSUE TITLE
Doesn't support C++17

### ISSUE THREAD

**Issue by AlecLafita** [assimp/assimp#3258]
I tried to compile it as a submodule in a project on C++17 and didn't compile. Later I tried to compile the assimp project with C++17 as well and the error persists

**Comment by turol** [comment]
What error?

**Comment by AlecLafita** [comment]
It's about this rapidjosn issue #https://github.com/Tencent/rapidjson/issues/1131 , as when compiling with VisualStudio, warnings are treated as errors.
It will be appreciated if the fix is applied directly to the assimp library instead of forcing to fix third third parties libraries issues. I've made the pull request #https://github.com/assimp/assimp/pull/3263 for it
