### ISSUE TITLE
make CMake config file relocatable

### ISSUE THREAD

**Issue by dirk-thomas** [assimp/assimp#3260]
I should have a created a separate ticket in the first place when I commented on https://github.com/assimp/assimp/pull/3126#discussion_r434741598. I am just opening this ticket for visibility and so it can be referenced.

@vmatare Please feel free to close it if your answer to the following question is no:

> would you be open to make the artifacts of assimp relocatable - by either working on necessary patches or accepting contributions towards that goal?

**Comment by vmatare** [comment]
Yes, sorry for being a bitch about it. I really needed to have this discussion and it may be a good thing we didn't clutter this issue with the messy back-and-forth.

Now I'm certainly willing to make everything relocatable, if you give me a little more context: Is it this library that should be relocatable for a specific reason or is this more of a general quest of promoting relocatability across all kinds of software installations? And if it's the latter, what is the scope of the endeavour? Do you actually aim to make all ROS dependencies relocatable? And do you realize that RedHat made an effort in that direction with *Relocatable RPMs*? I'm not an RPM user but from what I hear there's very little interest and too many technical obstacles, so they've basically given up on it. And I'd suspect the main obstacle is a general lack of interest in upstream developers to support relocatability.

**Comment by dirk-thomas** [comment]
> Is it this library that should be relocatable for a specific reason?

Yes, because it is being used by `rviz` which is a quite important package in the ROS ecosystem.

> is this more of a general quest of promoting relocatability across all kinds of software installations?

Yes, to this one too. Since platforms beside Ubuntu using Debian packages are getting more popular with ROS 2 (especially Windows) the prebuild archives we provide get more attention. At the moment the set of package we build for Windows and macOS are not huge (around 300) but I could see them grow.

We solved a lot of issues to this in the past cycle and afaik the packages we maintain should be all relocatable. For some third-party code (which we have to build to make them available on e.g. Windows) there are still outstanding issues but the majority should be in a good shape with ROS 2 Foxy.

> And do you realize that RedHat made an effort in that direction with Relocatable RPMs?

For DEBs as well as RPMs I don't mind about relocataibility much. Those packages have a set prefix and users just install them as is. I am not aware of users trying to move the prefix for those binary packages.
