### ISSUE TITLE
Building assimp with mingw32-make gives errors [71%]

### ISSUE THREAD

**Issue by 5721309** [assimp/assimp#3261]
[ 71%] Building CXX object code/CMakeFiles/assimp.dir/SMD/SMDLoader.cpp.obj
D:\MinGW\mylibs\assimp-5.0.1\code\SMD\SMDLoader.cpp: In member function 'void As
simp::SMDImporter::GetAnimationFileList(const string&, Assimp::IOSystem*, std::v
ector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::a
llocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::
allocator<char> > > >&)':
D:\MinGW\mylibs\assimp-5.0.1\code\SMD\SMDLoader.cpp:579:12: error: 'strtok_s' wa
s not declared in this scope; did you mean 'strtok_r'?
  579 |     tok1 = strtok_s(&buf[0], "\r\n", &context1);
      |            ^~~~~~~~
      |            strtok_r
code\CMakeFiles\assimp.dir\build.make:2120: recipe for target 'code/CMakeFiles/a
ssimp.dir/SMD/SMDLoader.cpp.obj' failed
mingw32-make[2]: *** [code/CMakeFiles/assimp.dir/SMD/SMDLoader.cpp.obj] Error 1
CMakeFiles\Makefile2:285: recipe for target 'code/CMakeFiles/assimp.dir/all' fai
led
mingw32-make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by Biswa96** [comment]
I can not reproduce this issue in latest master branch. Would you like to build the project now? Try to use latest mingw-w64 toolchain. Also you could use MSYS2/MinGW-w64 environment for ease.
