### ISSUE TITLE
Texture path is trimmed by 4 chars from the beginning

### ISSUE THREAD

**Issue by D-K-E** [assimp/assimp#3264]
The following outputs the path of my textures trimmed by 4 chars from the beginning in my ubuntu 16.04
```c++
unsigned int tcount = mat->GetTextureCount(type);
    for (unsigned int i = 0; i < tcount; i++) {
      aiString str;
      if (AI_SUCCESS != aiGetMaterialTexture(mat, type, i, &str)) {
        std::cout << "ERROR::ASSIMP::MATERIAL: "
                  << "Loading of material"
                  << " failed for type " << typeName << std::endl;
        throw std::invalid_argument("unable to load textures with given: "
                                    "arguments");
      }
     std::cout << str.data << std::endl;
```

I think the problem is caused from here of the `MaterialSystem.cpp`:
```c++
if( aiPTI_String == prop->mType) {
        ai_assert(prop->mDataLength>=5);

        // The string is stored as 32 but length prefix followed by zero-terminated UTF8 data
        pOut->length = static_cast<unsigned int>(*reinterpret_cast<uint32_t*>(prop->mData));

        ai_assert( pOut->length+1+4==prop->mDataLength );
        ai_assert( !prop->mData[ prop->mDataLength - 1 ] );
        memcpy(pOut->data,prop->mData+4,pOut->length+1);
```
Or from here, `aiGetMaterialTexture` function of the same file
```c++
aiGetMaterialString(mat,AI_MATKEY_TEXTURE(type,index),path)
```
The `aiGetMaterialString` seems to require 5 arguments, where as we give it 3 arguments.
I can also confirm that shared libs from release v4.1.0 do not produce this error.
I am not familiar with the api, I might be doing something wrong as well.

**Comment by DiegoAce** [comment]
I'm seeing the same problem using the 5.0.1 release. I'm only seeing it on my Mac build and not Windows. This did not occur with 4.1.0.

**Comment by DiegoAce** [comment]
Oh! This was my fault and I think I fixed it. When I updated to 5.0.1 I didn't update my includes correctly. I was still using the includes from 4.1.0. After referencing the correct includes this problem went away.

**Comment by kimkulling** [comment]
Ok, thanks a lot for the update. I will close this issue.
