### ISSUE TITLE
GCC error: bitwise comparison always evaluates to false

### ISSUE THREAD

**Issue by tobanteAudio** [assimp/assimp#3266]
Hi,

the title & shell output should have all the info needed. Build works with clang & msvc. `clang-tidy ` suggests that the [Line 214-215](https://github.com/assimp/assimp/tree/master/code/Common/SpatialSort.cpp#L214-L215) could be simplified to false.

```sh
/home/tobante/Developer/tobanteAudio/moci/3rd_party/assimp/code/Common/SpatialSort.cpp: In function ‘{anonymous}::BinFloat {anonymous}::ToBinary(const ai_real&)’:
/home/tobante/Developer/tobanteAudio/moci/3rd_party/assimp/code/Common/SpatialSort.cpp:215:34: error: bitwise comparison always evaluates to false [-Werror=tautological-compare]
  215 |     bool SignedMagnitude = ((-42 == (42 | (-0))) && (binValue & 0x80000000));
```

**Comment by kimkulling** [comment]
Thanks for the report. This issue will be fixed by https://github.com/assimp/assimp/pull/3248 . 
You can diable the -wall Flag as a workaround.
