### ISSUE TITLE
glTF2 Export seems to loop forever

### ISSUE THREAD

**Issue by JoelTrain** [assimp/assimp#3273]
I have confirmed that on this past hash: `bfedc0504550e8951c95c8a47c94f142b353f402` glTF2 export does not loop forever, and for my case the file completes the export within about a minute.

On the latest (as of writing) commit hash of `2aa6ca89bc31e9ce9524127affcbd92cf58f167e` exporting the same file seems to loop forever. I waited over an hour.

Unfortunately, I cannot upload my use case file for reproduction.

**Comment by RichardTea** [comment]
We'll need a sample file showing the issue in order to investigate this.
Can you cut down your file to remove the private data?

**Comment by kimkulling** [comment]
Please reopen when you have a file to reproduce this issue. Thanks and sorry for the bug!
