### ISSUE TITLE
Assimp does not compile if all exporters are disabled

### ISSUE THREAD

**Issue by tenry92** [assimp/assimp#3275]
It seems this has already been solved in the past, but I'm having this issue with 5.0.1 using Microsoft Visual Studio compiler (this error does NOT occur with gcc or mingw-cross compiling on Linux).

I basically do the same as in #1320. See also #2707.

Steps to reproduce:

* disable all exporters (I set ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT to OFF)
* try to compile the project
* observe following error:

```
libs\src\assimp-5.0.1\code\Common\Exporter.cpp(109): error C2466: cannot allocate an array of constant  size 0 [build\libs\src\assimp-5.0.1\code\assimp.vcxproj] 
```

**Comment by kimkulling** [comment]
I just tried to build the latest master with the following cmake command:

1. Generate the projectfiles for VS 2019:  `cmake .\CMakeLists.txt -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF`
2. Build the software: ` cmake --build .`

All build artifacts were generated.
