### ISSUE TITLE
AI_SCENE_FLAGS_INCOMPLETE on FBX Import (2012/2013)

### ISSUE THREAD

**Issue by dmitri-fm** [assimp/assimp#3283]
I get AI_SCENE_FLAGS_INCOMPLETE when loading this FBX (2012 version):
https://mega.nz/file/6o8nTZ5S#EcH0KkhAqxnYwlJjAEG64bW7Eg4B0hcpzNP1fXPEDaA

Converting them to 2013 version with Autodesk converter doesn't help - same problem appear.

**Comment by vergol** [comment]
More info on the problem:
```
Warn,  T10468: FBX-DOM: unsupported, newer format version, supported are only FBX 2011, FBX 2012 and FBX 2013, trying to read it nevertheless

Warn,  T10468: FBX-DOM (TOK_KEY, offset 0x7023e) failed to read source object for incoming Model link, ignoring

Error, T10468: FBX-Parser did not find required element "Materials"
```
Looks like the problem is that there are no materials in the model.
Can you please fix this?
The file can be opened in Blender without any problem.

**Comment by vergol** [comment]
I can fix the problem by adding
```cpp
if (HasElement(source, "Materials"))
```
before `ParseVectorDataArray` call at https://github.com/assimp/assimp/blob/f844c3397d7726477ab0fdca8efd3df56c18366b/code/AssetLib/FBX/FBXMeshGeometry.cpp#L650C9-L650C20

**Comment by dmitri-fm** [comment]
Looks like it's fixed now
https://github.com/assimp/assimp/pull/5624
