### ISSUE TITLE
Why bones with exactly zero weight, that affect zero vertices, listed at aiMesh at all ?

### ISSUE THREAD

**Issue by ivan-achlaqullah** [assimp/assimp#3285]
I'm trying to upgrade from older version of Assimp to v5.0.1, only to be surprised that `aiMesh` seems to lists `aiBone` that didn't affect any of their vertices (`mNumWeights` are exactly 0). Sometimes for each mesh it listed *all the bones* in the model, even if it obvious that only small number of them affect the mesh at all.

On old version, `aiMesh` didn't list bones that have 0 in `mNumWeighhts`.

I thought this is a bug until I started digging. I tracked down the changes to this pull request #2608 (which is v5.0.0.rc2). Now I'm confused.

Can somebody enlighten me why keeping them is a good idea?

**Comment by ObsydBT** [comment]
We use them for "attachment" nodes. For example a shield attachment on a caracters back that when the character moves swings.

**Comment by ivan-achlaqullah** [comment]
@ObsydBT Oh I see, I haven't implemented attachment yet in my app so I didn't know.

So if I only interested in skinned animation, I can freely ignore bones that have `mNumWeights=0` and only sent the relevant bones right ?
