### ISSUE TITLE
3ds export does not use opacity from material

### ISSUE THREAD

**Issue by SigveBergslien** [assimp/assimp#3291]
Using the 3ds export we were experiencing issues with transparent objects. During debugging I could not see that the 3ds exporter used Discreet3DS::CHUNK_MAT_TRANSPARENCY. To solve the issue I added the following code :

        if (mat.Get(AI_MATKEY_OPACITY, f) == AI_SUCCESS) {
            ChunkWriter chunk(writer, Discreet3DS::CHUNK_MAT_TRANSPARENCY);
            WritePercentChunk(1.0f - f);
        }

in Discreet3DSExporter::WriteMaterials

Tested locally and worked.

**Comment by kimkulling** [comment]
Thanks for the patch. I opened https://github.com/assimp/assimp/pull/3357 to try it out.
