### ISSUE TITLE
how can i change up-axis from Z-Up to Y-Up using assimp?

### ISSUE THREAD

**Issue by jlygit** [assimp/assimp#3308]
hello, all:
how can i change up-axis from Z-Up to Y-Up using assimp?

**Comment by RichardTea** [comment]
Unfortunately this question is too vague to answer.

What do you want to do with said model?

**Comment by kimkulling** [comment]
You can rotate the transformation of your scene-root-node for instance. Or you can use this post-process-step: https://github.com/assimp/assimp/blob/master/code/PostProcessing/ComputeUVMappingProcess.h
