### ISSUE TITLE
how to read custom attribute from fbx

### ISSUE THREAD

**Issue by Maria098** [assimp/assimp#3315]
Hello
I am using assimp to parse fbx file and would like to know how to read custom attribute attached to material.
I am writing fbx in another app and add the following property:

```
FbxProperty::Create(pFBXTex, FbxFloatDT, "TextureAngle", "TextureAngle").Set(angleZ);

Trying to read it with assimp but this does not work:
float angle = 0.0f; 
int res = aiGetMaterialFloat(mat, "TextureRotation", aiTextureType_DIFFUSE, 0, (float*)&angle);
if (res == AI_SUCCESS)
      qDebug() << "SUCESS angle=" << angle;
```

**Comment by kimkulling** [comment]
Your property will not be stored in the material definition. You have to get the data out of the FbxProperty set or you have to add you FbxProperty as a metadata entry.
