### ISSUE TITLE
Expected at least one object with no parent - blend importer

### ISSUE THREAD

**Issue by congard** [assimp/assimp#3316]
When I trying to import my model with 2 animations I get
`Assimp error: BLEND: Expected at least one object with no parent`

If I convert `blend` to `fbx` via Blender, then Assimp imports `fbx` model without any errors

**Steps to reproduce the behaviour:**
1. Download the attached `blend` model
2. Try to import it
3. See error

**Expected behaviour**
Import model without any error

**Additional info**
Blender 2.83 (both Linux and Windows)
Assimp 5.0.1

Models: https://drive.google.com/drive/folders/1YvkMsG9NdMnRNyLhXpeifyndIs5DZSVS?usp=sharing

**Comment by kimkulling** [comment]
We have issues with the lastest version of blender. BUt I promised to fix this issue for our next release.

Thanks a lot for the great model! Helps to work on this!

**Comment by samrrr** [comment]
https://drive.google.com/file/d/1FxlEWSbg-7ThcvulqsR0PRIMeXjqnFjU/view?usp=sharing

**Comment by jaredthirsk** [comment]
Does anyone know what version of Blender we can go back to to have things working?
