### ISSUE TITLE
Can't compile for VS10

### ISSUE THREAD

**Issue by phanemy** [assimp/assimp#3319]
I'm trying to build Assimp for Visual Studio 10, I use cmake with using Visual Studio 10 2010 Win64 compiler, everything works.
But in visual when in try to compile i get 5000+ error.

I would like to know if i'm missing something or if Assimp isn't compatible with VS10 or if it is a bug.

![image](https://user-images.githubusercontent.com/24206584/87143109-d78dac80-c2a5-11ea-8b0d-c841610f6bb9.png)

**Comment by kimkulling** [comment]
Hi,

sorry to say this but we stopped supporting VS2010 support because of incompatibilities with out C++1 support. 
You can try to use older versions, 4.1 shall work I guess.

Kim
