### ISSUE TITLE
AC file loader doesn't support triangle strips

### ISSUE THREAD

**Issue by IOBYTE** [assimp/assimp#3324]
**Describe the bug**
The AC file loader doesn't support triangle strips.  It treats all unknown surface types as polygons which produces garbage when rendered.

**To Reproduce**
Use MadView3D which uses asimp for file loading as shown here: https://www.geeks3d.com/forums/index.php/topic,6531.0.html

**Expected behavior**
Models with the .acc extension (which has triangle strips) should be rendered properly.

**Screenshots**

![Screenshot from 2020-07-13 13-35-18](https://user-images.githubusercontent.com/1819479/87335387-36555f00-c50e-11ea-99a6-42ef7d7c93dd.png)

**Desktop**
 linux, raspberry pi and windows

**Additional context**
There are 2 ways to handle this: don't advertise .acc file format support or add support for .acc triangle strips.

Here is a pull request that adds triangle strips to the AC file loader: https://github.com/assimp/assimp/pull/3320

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3320
