### ISSUE TITLE
Add USD support

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#3325]
**Is your feature request related to a problem? Please describe.**
A lot of customers are asking for USD-support

**Describe the solution you'd like**
Implement the following format to Asset-Importer-Lib: https://graphics.pixar.com/usd/docs/index.html

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ts-stevem** [comment]
Possible duplicate of https://github.com/assimp/assimp/issues/1332

**Comment by kimkulling** [comment]
We use https://github.com/assimp/assimp/issues/1332 to track this feature request.

**Comment by Track77** [comment]
Hello
As I know AssimpNet doesn't support the USD format
