### ISSUE TITLE
STEP import fails in "any" CAD

### ISSUE THREAD

**Issue by foreachthing** [assimp/assimp#3331]
**Describe the bug**
When exporting a STL to STEP (stp), I'm not able to use it in any CAD I own. Including SolidWorks and freeCAD.

**assimp**
Version 5, commit 67a710ef

**To Reproduce**
1. Convert any file to STEP
1. Open this file in SolidWorks or freeCAD

**Expected behavior**
Have a solid model (in SolidWorks) and have, at least, faces in freeCAD.
SolidWorks will just output a message that no volume was loaded - abort.
FreeCAD will just import vertices, no surface.

**Desktop**
 - OS: Win10

**Additional context**
Reduced error log from SolidWorks:
```
Reversing curve, low: 0.268448, high: -0
Reversing curve, low: 0.338667, high: -0
Reversing curve, low: 0.331851, high: 0
WARNING: Surface problem ... Invalid combination of curves on surface.
WARNING: Surface problem ... Invalid combination of curves on surface.
WARNING: Surface problem ... Invalid combination of curves on surface.
```

**Comment by kimkulling** [comment]
Step-files are currently not supported.
