### ISSUE TITLE
Building with no exporters causes a warning which fails the build in MSVC

### ISSUE THREAD

**Issue by caveman250** [assimp/assimp#3338]
When building without any exporters, MSVC will throw the following warning "code\Common\Exporter.cpp(142,74): warning C4100: 'exporters': unreferenced formal parameter". which subsequently fails the build due to the fact that assimp enables the /WX (Treat warnings as errors) flag.

**To Reproduce**
1. Configure cmake with all exporters turned off and Visual studio as the build type.
2. build

its easy enough to turn off warnings as errors, but quite annoying to have to do it every time i generate the project with cmake.

**Comment by kimkulling** [comment]
Working on that

**Comment by Naios** [comment]
Ref #3391
