### ISSUE TITLE
i try to build it on my mac with xcode, is it ok?

### ISSUE THREAD

**Issue by JerryChen12345** [assimp/assimp#3339]
[==========] 433 tests from 107 test cases ran. (15036 ms total)
[  PASSED  ] 432 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] utVersion.aiGetVersionRevisionTest

**Comment by kimkulling** [comment]
This seems to be an issue with our released version. The unittest just checks against the wrong version Id. So yes: you can use Assimp, this bug will not cause any undefined bahaviours in your application.
