### ISSUE TITLE
mtl-Readout gives wrong Illumination Model

### ISSUE THREAD

**Issue by codebaard** [assimp/assimp#3351]
When I load a Metal-Material from a mtl-file, the illumination model for this material is not read correctly. According to the file the model is supposed to be "illum 4". Instead ASSIMP returns "2".

**To Reproduce**
Create an OBJ File with attached mtl file with the following parametres:

_newmtl Metal
Ns 900.000000
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.400000
Ks 1.000000 1.000000 1.000000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 3_

**Note: mtl-spec is 0-based. Therefore mtl = assimp-1!**

Import this OBJ with Assimp and readout illum Model with:

		ai_int illumModel;
		aiMaterial->Get(AI_MATKEY_SHADING_MODEL, illumModel);
		myMaterial->illum = illumModel;

**Expected behavior**
Illum readout should be "4".

 - OS: Win10

**Comment by kimkulling** [comment]
The Obj-Wavefront Importer translates the illumination model into the Asset-Importer-specific enum for aiShadingMode_Phong, which is a 2 in this case. 
So no bug, just a misunderstanding of the data-model.

**Comment by codebaard** [comment]
Thanks for the quick Answer :-)

In the material.h file in Version 5.01 aiShadingMode_Phong resolves to 0x3 (This is a typo I guess...correct me if i'm wrong. I suppose you meant 0x2 for mode Gouraud).

Assumend that: why define the illumination model of material with high a specularity as Gouraud, when its supposed to be Phong-Blinn?* 

*which is already wrong in the first place since it really should be CookTorrance or smth in that case but thats Blenders fault, I guess.

I apologize for bothering though and really appreciate the time.

**Comment by kimkulling** [comment]
You are welcome!
