### ISSUE TITLE
minor usage documentation correction

### ISSUE THREAD

**Issue by capnramses** [assimp/assimp#3354]
**Describe the bug**
Instructions in https://assimp-docs.readthedocs.io/en/latest/usage/use_the_lib.html for the C example listing are slightly incorrect.

**Additional context**
I would have made a PR but didnt see the a repo for the web docs.

To fix:
`const aiScene* scene` -> `const struct aiScene* scene`
`nullptr` -> `NULL`

**Comment by kimkulling** [comment]
Thanks for the report, this PR will fix it: https://github.com/assimp/assimp-docs/pull/6
