### ISSUE TITLE
C2661 std::map all over the place when compiling in MSVC 2013

### ISSUE THREAD

**Issue by JernejL** [assimp/assimp#3358]
error C2661: 'std::map<Assimp::BaseImporter::ImporterUnits,double,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>::map' : no overloaded function takes 5 arguments	R:\ASSIMP\include\assimp\BaseImporter.h

This happens 114 times in BaseImporter.h, is this a bug or is assimp not build-able in msvc 2013?

**Comment by kimkulling** [comment]
Need to check, thanks for the bug-report!

**Comment by kimkulling** [comment]
We have dropped build support for VS2013 for quit a while. So for the latest version we will net be able to fix this one.
