### ISSUE TITLE
Please use CMakePackageConfigHelpers

### ISSUE THREAD

**Issue by paroj** [assimp/assimp#3365]
the current hand-written `assimp-config.cmake.in` etc. files are horribly broken:
- they do not respect "RelWithDebInfo" builds
- they do not transitively export zlib & irrxml for static builds #2796 #2453
- they are not relocatable #3260
- the target names must be kept in sync manually #3210 #2760

all of this is properly taken care of by CMake, if you let it:
- https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html
- https://cmake.org/cmake/help/latest/command/install.html#export

**Comment by kimkulling** [comment]
Thanks for the hint! I will try to optimize this.

**Comment by traversaro** [comment]
For reference in [vcpkg](https://github.com/microsoft/vcpkg) there was a PR related to this issue: https://github.com/microsoft/vcpkg/pull/13264 .
