### ISSUE TITLE
Collada import failing on empty xml tags

### ISSUE THREAD

**Issue by beckylum0216** [assimp/assimp#3367]
Assimp is generating loading errors on collada files. The readfile command is generating error on every empty xml tag. The debug message is as follows:

```Collada: ../res/model/Rocks/Rock_1.dae - Expected end of <author> element.```
 
**To Reproduce**
* The assimp library is imported from the conan.io repository. 
* Implemented the following code:
```Assimp::Importer importer;

    const aiScene *scene =
        importer.ReadFile(targetPath.c_str(), AssimpImportFlags(true, false));
```

**Expected behavior**
Loading fails during runtime with debug message.

```Collada: ../res/model/Rocks/Rock_1.dae - Expected end of <author> element.```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Assimp Version 5.0.1
 - MSVC 14.26.28801

dae would be provided on request.

**Comment by RichardTea** [comment]
This was fixed a very long time ago.

Please update to a more recent build.

PS: conan.io offers a very large number of versions, so you *must* specify exactly which version you used when reporting an issue.

**Comment by beckylum0216** [comment]
@RichardTea I am using the default settings, I am not sure which commit hash conan.io is using for its default. I will change my settings to a specific hash.

**Comment by beckylum0216** [comment]
@RichardTea I have used a specific assimp version, but assimp is still generating the error. Attached is the conaninfo.txt

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows

[requires]
    assimp/5.Y.Z
    glm/0.9.9.4
    sdl2/2.Y.Z

[options]


[full_settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows
    os_build=Windows

[full_requires]
    assimp/5.0.1:6291f7cb9be8c2d8c53809fff89c8adbb1208dec
    glm/0.9.9.4@g-truc/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    irrxml/1.2:3fb49604f9c2f729b85ba3115852006824e72cab
    libiconv/1.15:3fb49604f9c2f729b85ba3115852006824e72cab
    sdl2/2.0.10@bincrafters/stable:e00ad8bc0b74a160a9492a61277bebc5bdfa1051
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab

[full_options]
    assimp:double_precision=False
    assimp:shared=True
    assimp:with_3d=True
    assimp:with_3ds=True
    assimp:with_3ds_exporter=True
    assimp:with_3mf=True
    assimp:with_3mf_exporter=True
    assimp:with_ac=True
    assimp:with_amf=True
    assimp:with_ase=True
    assimp:with_assbin=True
    assimp:with_assbin_exporter=True
    assimp:with_assjson_exporter=True
    assimp:with_assxml_exporter=True
    assimp:with_b3d=True
    assimp:with_blend=True
    assimp:with_bvh=True
    assimp:with_cob=True
    assimp:with_collada=True
    assimp:with_collada_exporter=True
    assimp:with_csm=True
    assimp:with_dxf=True
    assimp:with_fbx=True
    assimp:with_fbx_exporter=True
    assimp:with_gltf=True
    assimp:with_gltf_exporter=True
    assimp:with_hmp=True
    assimp:with_ifc=True
    assimp:with_irr=True
    assimp:with_irrmesh=True
    assimp:with_lwo=True
    assimp:with_lws=True
    assimp:with_md2=True
    assimp:with_md3=True
    assimp:with_md5=True
    assimp:with_mdc=True
    assimp:with_mdl=True
    assimp:with_mmd=True
    assimp:with_ms3d=True
    assimp:with_ndo=True
    assimp:with_nff=True
    assimp:with_obj=True
    assimp:with_obj_exporter=True
    assimp:with_off=True
    assimp:with_ogre=True
    assimp:with_opengex=True
    assimp:with_opengex_exporter=True
    assimp:with_ply=True
    assimp:with_ply_exporter=True
    assimp:with_q3bsp=True
    assimp:with_q3d=True
    assimp:with_raw=True
    assimp:with_sib=True
    assimp:with_smd=True
    assimp:with_step=True
    assimp:with_step_exporter=True
    assimp:with_stl=True
    assimp:with_stl_exporter=True
    assimp:with_terragen=True
    assimp:with_x=True
    assimp:with_x3d=True
    assimp:with_x3d_exporter=True
    assimp:with_x_exporter=True
    assimp:with_xgl=True
    irrxml:shared=False
    libiconv:shared=False
    sdl2:directx=True
    sdl2:iconv=True
    sdl2:sdl2main=True
    sdl2:shared=False
    zlib:minizip=False
    zlib:shared=False

[recipe_hash]


[env]

```

**Comment by RichardTea** [comment]
Thanks, I don't really understand what that's trying to show.
Can you attach a sample DAE file that fails?

**Comment by beckylum0216** [comment]
@RichardTea Requested file as follows
[Rock_1.zip](https://github.com/assimp/assimp/files/5061619/Rock_1.zip)

**Comment by RichardTea** [comment]
As I thought, this does load fine in current Assimp.
I believe this issue was fixed at end of June 2019.

![image](https://user-images.githubusercontent.com/31507749/90004770-21dfc000-dc8e-11ea-841b-00f019f37811.png)

You will need to ask your upstream to roll up to a newer Assimp github commit, or to build Assimp yourself instead of importing a conan build of unknown provenance.

**Comment by beckylum0216** [comment]
@RichardTea Thank you. Think we will submodule it.
