### ISSUE TITLE
Assimp fails on Importer

### ISSUE THREAD

**Issue by beckylum0216** [assimp/assimp#3371]
I have submoduled assimp into my project, assimp configures with these warnings:

```CMake Warning (dev) at lib/assimp/CMakeLists.txt:261 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for ZLIB...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could not locate ZLIB
-- compiling zlib from sources
CMake Warning (dev) at C:/Program Files/JetBrains/CLion 2020.1.1/bin/cmake/win/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (rt) does
  not match the name of the calling package (RT).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  lib/assimp/cmake-modules/FindRT.cmake:19 (find_package_handle_standard_args)
  lib/assimp/code/CMakeLists.txt:1040 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find rt (missing: RT_LIBRARY) 
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF ASSJSON STEP
-- Disabled exporter formats:
``` 

The assimp project builds and links, but calling ``` Assimp::Importer``` crashes the program.

**To Reproduce**
initiate project on clion
submodule assimp 
configure assimp
build and run project.

**Expected behavior**
project crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Compiler: msvc:14.26.28801
 - assimp hash: ac8a8a5ad433afd2a10124774685f9db1edbe701 lib/assimp (Release3.1_RC1-7215-gac8a8a5a)

**Comment by RichardTea** [comment]
Cannot assist without stack trace.

To make a completely wild guess based on evidence whatsoever, perhaps your application is not loading the correct DLL or is using outdated headers?

**Comment by beckylum0216** [comment]
@RichardTea i am using clion to build this project the project is crashing before a stacktrace can be run

```
Couldn't launch process

Process finished with exit code 0
```

This is the only output I am getting from the IDE

**Comment by RichardTea** [comment]
This is not an Assimp issue.
Assuming it worked before when using conan, your 'main' application project is not configured properly to consume the Assimp DLL.

Most likely the DLL loader cannot find the Assimp DLLs, so terminates the process before entering main().

Make sure they are in the %PATH% of the application that is being run. Easiest is to copy them into the application output folder.
Assimp's cmake places the DLLs in $(CMAKE_BUILD_DIR)\bin\$(Configuration) by default.

I have never used clion, so cannot help you set up your project.
- Maybe check stackoverflow for help on configuring clion projects that build and consume DLLs?

**Comment by beckylum0216** [comment]
@RichardTea Thank you so much for the hint, I did not realise that assimp's CMake was placing the DLL in the top level of the build directory. The solution was to copy the DLLs into the appropriate binary directory:

```set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/src)```

Thanks.
