### ISSUE TITLE
Can I get the hierarchical structure of the imported model

### ISSUE THREAD

**Issue by LuoShiLiang** [assimp/assimp#3381]
i'm new to ASSMIP

Now , it can import/Export models，get materials/UVs/Textures and etc . More related interfaces are not familiar
My Question  is described below👇

I have a issue, is there a way to get model's hierarchical structure? 
I want to get and manipulate the hierarchical structure of the imported model at runtime, just like in Maya or 3dsMax, I can see that the hierarchical structure of the model is a tree structure and can easily edit the mesh in the structure such as hiding and reverse selection and any more. If you choose a parent and run some operations it can affect all children.
So, the first issue is how to get this "Hierarchical Structure",  is there any Samples for reference or functions ?

Hope to get your guys reply!!! (Actually i don't want to Handwriting a tree structure)

**Comment by kimkulling** [comment]
To get you right: you want to have the hierarchy of the scene?

**Comment by LuoShiLiang** [comment]
> To get you right: you want to have the hierarchy of the scene?

YES

**Comment by RichardTea** [comment]
A scene is a hierarchy of aiNode.

I suggest you take a look at the documentation, this is a core part of the API.

**Comment by LuoShiLiang** [comment]
> A scene is a hierarchy of aiNode.
> 
> I suggest you take a look at the documentation, this is a core part of the API.

Thanks ! I just started to use it, many places are not familiar yet
