### ISSUE TITLE
FBX: Regression importing animations

### ISSUE THREAD

**Issue by jankrassnigg** [assimp/assimp#3390]
**Describe the bug**

I just switched from release 5.0.1 to master (9ce0671134912fd49010d81b89ae56dc41029c39). An FBX file with skeletal animations that I use for testing was working perfectly fine before but now doesn't anymore.

I don't think I can share the model here, but if you need it to reproduce the issue, just ping me directly.

With both versions I can import the mesh just fine:

![good_mesh](https://user-images.githubusercontent.com/6001174/92274622-e2ec0580-eeed-11ea-9096-044c06409ce5.jpg)

In the old version, the node hierarchy has considerably more nodes, though. I assume that the new code merges them together, and I wouldn't be surprised if this change broke the animations.

Old skeleton (working):

![good_skeleton](https://user-images.githubusercontent.com/6001174/92274750-1595fe00-eeee-11ea-8ca0-57946048e680.png)

New skeleton (broken):

![bad_skeleton](https://user-images.githubusercontent.com/6001174/92274809-31999f80-eeee-11ea-9fb1-bee1cdc21afe.png)

Finally, here is a GIF showing an animation. The green lines visualize the bind pose, which looks correct. The pink lines are the animated pose:

![broken fbx anim](https://user-images.githubusercontent.com/6001174/92275113-c9978900-eeee-11ea-99d3-15cd338f99b1.gif)

Most of it looks good, it's not complete garbage, but every couple of joints appear to be messed up. That's what leads me to the assumption, that the optimization that was done to reduce the overall node count is missing a step to also adjust the animation matrices.

PS: I upgraded to latest assimp because I encountered several issues with GLB files, which have been fixed. So all THOSE files now work perfectly fine. Of course I can't rule out an issue in my own code, but it feels unlikely, considering that it was working with the release 5.0.1.

**Comment by Frooxius** [comment]
I can confirm that this happens as well. Was previously using an older version (roughly a few dozen commits after 5.0.1 if I remember correctly), updated to latest master: https://github.com/assimp/assimp/commit/294d4230b04636947060c4b611742fad01e9bd47

I've got videos showing the breakage on two models (first it imports with the old version of Assimp and then I restart my app to import with the new):
https://youtu.be/BZG3txkwVq0
https://youtu.be/4GzXt6tA6Vw

I can't share the models publicly either, but I can send them to you if you need them for testing.

However I fortunately managed to isolate the breaking change to this commit: https://github.com/assimp/assimp/commit/14b8d1242b0f32fef9dd8ace0a1d4e8cbd20d88c

Particularly changing FBXConverter.cpp line 658 from:

```CSharp
if (comp == TransformationComp_Rotation || comp == TransformationComp_Scaling || comp == TransformationComp_Translation) {
            continue;
        }
```

To: 

```CSharp
if (comp == TransformationComp_Rotation || comp == TransformationComp_Scaling || comp == TransformationComp_Translation ||
            comp == TransformationComp_PreRotation || comp == TransformationComp_PostRotation) {
            continue;
        }
```

I have reverted this particular change on the latest master on my fork here: https://github.com/Frooxius/assimp/commit/b6b307025a7ee19c056130f8d4c0fb61e8efb1ab

I have confirmed that this fixes the issue on my end, but I'm not sure if it breaks anything else or just generates unnecessary transformation nodes. My guess is that when those nodes are collapsed, the animation transforms aren't recomputed properly, but I don't know enough about FBX internals to do a proper fix. I hope that this info helps for anyone who does though and at least provides a workaround for now.

Here's video of the fix if necessary: https://www.youtube.com/watch?v=W4gt15RBzn4

**Comment by cpope9141** [comment]
I believe I am still seeing this issue in v5.1.5.

**Comment by jinfagang** [comment]
I believe FBX is nightmare.

**Comment by mwestphal** [comment]
Any news on this one ? It is still present here.

**Comment by tellypresence** [comment]
Looks like RenderPeople models were also working around v5.0.1 but subsequently [broke](https://github.com/assimp/assimp/issues/5449#issuecomment-2023986936)

**Comment by tellypresence** [comment]
### Bisect report
<table>
<tr><th rowspan=2>Model</th><th colspan=2>Git commit</th><th rowspan=2>Notes</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/b962af93fc2ee9cdde876e6b5d42e5ec5e427749"><tt>b962af9</tt></a><br>24 Mar 2020</td><td><a href="https://github.com/assimp/assimp/commit/14b8d1242b0f32fef9dd8ace0a1d4e8cbd20d88c"><tt>14b8d12</tt></a><br>24 Mar 2020</td></tr>
<tr><td><tt>55-rp_nathan_animated_003_walking_fbx</tt></td><td><img alt="nathan_2020-03-24_b962af9" src="https://github.com/user-attachments/assets/59a2fddd-eb25-46aa-8236-3f1d779b9c99" width=180 /></td><td><img alt="nathan_2020-03-24_14b8d12" src="https://github.com/user-attachments/assets/62894038-9a52-4ca8-874a-3f1369ed0864" width=90 /></td><td>"Nathan" had been unaffected, now completely and obviously broken</td></tr>
<tr><td><tt>22-rp_manuel_animated_001_dancing_fbx</tt></td><td><img alt="manuel_2020-03-24_b962af9" src="https://github.com/user-attachments/assets/9a8d2f01-6d1a-45c6-8933-dbd0f77fa71d" width=90 /></td><td><img alt="manuel_2020-03-24_14b8d12" src="https://github.com/user-attachments/assets/32b760af-89ec-408a-84ff-6d1033f62a7a" width=90 /></td><td>"Manuel" was already broken and appears to have also been affected by this bug</td></tr>
<tr><td><tt>35-rp_sophia_animated_003_idling_fbx</tt></td><td><img alt="sophia_2020-03-24_b962af9" src="https://github.com/user-attachments/assets/8be96b99-9a5c-4317-8bae-c93d0cc1bda9" width=90 /></td><td><img alt="sophia_2020-03-24_14b8d12" src="https://github.com/user-attachments/assets/a7cfd30e-5df4-43be-b54c-114bb8d115c0" width=90 /></td><td>"Sophia" was already broken, now artifacts are much worse</td></tr>
</table>

**Comment by tellypresence** [comment]
@jankrassnigg @Frooxius @cpope9141 @mwestphal
Please pull latest commit, rebuild and check if your models are still having problems -- also please post screenshots to track the issue either way

**Comment by sascharo** [comment]
> I believe FBX is nightmare.

Unfortunately, yes.
