### ISSUE TITLE
What is aiProcess_ForceGenNormals?

### ISSUE THREAD

**Issue by NukeBird** [assimp/assimp#3396]
This flag isn't documented. What the difference between aiProcess_ForceGenNormals and aiProcess_GenNormals?
Will aiProcess_ForceGenNormals generate normals even if they are exist?

**Comment by kimkulling** [comment]
**aiProcess_ForceGenNormals** will recalculate all normals, **aiProcess_GenNormals** shall just guarantee that normals are there.
