### ISSUE TITLE
Loading texture file embeded into a 3mf file

### ISSUE THREAD

**Issue by Xemuth** [assimp/assimp#3398]
**Assimp can't load 3mf embedded texture**
Nowaday assimp is not capable of loading texture embedded in some 3mf file. It would be really cool if he could do it !

**Example file**
if you want a 3mf object example, Find the file below
[T. rex.zip](https://github.com/assimp/assimp/files/5240569/T.rex.zip)

**Comment by tufeixp** [comment]
vote+1 for this feature
