### ISSUE TITLE
Error in importing .dae file

### ISSUE THREAD

**Issue by SaHajizadeh** [assimp/assimp#3404]
Hi,

The following error is displayed when I import the attached .dae file by this library.
Assimp.AssimpException: 'Error importing file: Collada: $$$___magic___$$$..dae - Invalid data index (6/6) in primitive specification'

what is the problem of the .dae file?

[NewProject.zip](https://github.com/assimp/assimp/files/5273636/NewProject.zip)

**Comment by Optimizer0** [comment]
I investigated the issue. This indeed is NOT a bug of Assimp. Assimp behaves as expected but the normal data indices in the .dae file are wrong. 

As a side note, if you skip loading normal data but load just positions and textures, the model loads fine.

@kimkulling Sir, I suggest closing this issue.

**Comment by kimkulling** [comment]
Hi,

ok, thanks for the report and your investigation. I will close this one for you!
