### ISSUE TITLE
[FBXImportSettings] convertToMeters is never used

### ISSUE THREAD

**Issue by adriengivry** [assimp/assimp#3408]
In `Assimp::FBX::ImporterSettings`, the `convertToMeters` setting is never used.

In order to have a correct scale for FBX imported objects, this setting should get considered.

Do note that users will have to call `importer.SetPropertyBool(AI_CONFIG_FBX_CONVERT_TO_M, true);` before `import.ReadFile(...);`

**Comment by RichardTea** [comment]
I think this setting was deprecated, replaced by a global setting that asked all formats with real size to return the result in metres.

However, I have forgotten what the new scaling setting was called.

**Comment by kimkulling** [comment]
Right, this is the case.

**Comment by Underdisc** [comment]
> I think this setting was deprecated, replaced by a global setting that asked all formats with real size to return the result in metres.
> Right, this is the case.
Which setting is this? Furthermore, should the `AI_CONFIG_FBX_CONVERT_TO_M` property be removed if it has no effect?
