### ISSUE TITLE
Model "duck.dae" from open3mod_1_0_standalone failed ?

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#341]
See https://sourceforge.net/p/assimp/discussion/817654/thread/89666b12/?limit=25#72bb for more detailed information

**Comment by acgessler** [comment]
(This is a model issue - it contains duplicate camera names. Even though this is permissible under the input format, I do not see why we should fix this on our side unless the issue becomes more severe. Disabling assimp validation passes such files easily.)
