### ISSUE TITLE
Lighting issue Unreal engine 4

### ISSUE THREAD

**Issue by SebastienTussiau** [assimp/assimp#3410]
**Describe the bug**

Lighting incorrect in Unreal engine. Seems like a normal array problem.

**Expected behavior**
The lighting is looking better on a native unreal mesh, and should look the same on the assimp mesh imported.

**Screenshots**

![Screenshot 2020-09-30 110552](https://user-images.githubusercontent.com/62241761/94794691-842a8680-03dc-11eb-9bb9-865f505fd9f6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 64bits

**Additional context**
Unreal engine

**Comment by SebastienTussiau** [comment]
[UE4Cube.txt](https://github.com/assimp/assimp/files/5311025/UE4Cube.txt)
[AssimpCubeV.txt](https://github.com/assimp/assimp/files/5311026/AssimpCubeV.txt)

Here are two text files, describing the verts, tris, and normals of one mesh from unreal, and another impoirted by assimp. Note the difference in the normals.

**Comment by Optimizer0** [comment]
Are you comparing the vertex data (verts, tris, normals) of Unreal Engine built-in cube and a separate cube model imported by assimp? In that case, these are two different meshes so having different vertex data is not surprising. Notice not only the normal are different but verts and tris are different as well. 

Or are you importing the same model file with Unreal Engine Importer and Assimp? In that case this is strange.

**Comment by SebastienTussiau** [comment]
Hello, I am importing the same model file using the Unreal importer and Assimp. But I found the issue, the problem was the export asix of Blender. Ue4 expects +x as forward axis and +z as up axis. That solved my problem of lighting.
