### ISSUE TITLE
Vertex colors incorrect converting DXF to glTF 

### ISSUE THREAD

**Issue by aarongarvey** [assimp/assimp#3411]
I'm a new user to Assimp, so I'm looking for some assistance in determining if something is wrong with Assimp, my workflow, or my source DXF file.

I have a 3D DXF file in which I require to be converted to glTF format.  Assimp performs the conversion fine without error on the command line using `assimp export test.dxf test.gltf` however when I view the resulting glTF file, the vertex colors used on the exported model do not match the original source DXF model.

The first link shows how the DXF model is viewed within Sketchfab when the DXF model is imported.
[Original DXF Colors](https://drive.google.com/file/d/19AqevoAZZpN9N6zJmHeneUjnPWotcfr8/view?usp=sharing)

The second link shows how the converted glTF model is viewer within Sketchfab (note: I get the same result when viewing the converted glTF in three.js and babylon as well)
[Converted glTF colors](https://drive.google.com/file/d/1_1bTb9cCqlpzBvIdwhZNjktcipX5lsV0/view?usp=sharing)

[Link to source DXF and glTF files](https://drive.google.com/file/d/1a-uG52MMSe2hLhU_j4VHAL46qD6L6IIV/view?usp=sharing)

Is anyone able to help steer me in the right direction on this?

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5426
