### ISSUE TITLE
SimpleTexturedDirectx11 fails to open the model

### ISSUE THREAD

**Issue by CaminoOnPc** [assimp/assimp#3414]
**Description**

Hello, i am trying to load and test SimpleTexturedDirectx11 sample before implementing assimp into my project, however whenever i try to launch the sample i get an error saying that model couldn't be loaded, after some debugging it seems that it fails here:

```
const aiScene* pScene = importer.ReadFile(filename,
		aiProcess_Triangulate |
		aiProcess_ConvertToLeftHanded);
````

I also have added _GetErrorString_ to see why exactly it is unable to open the model.

```
const char* error = importer.GetErrorString();
```

Which outputs the following:

```
"Unable to open file \"Models/myModel.fbx\"."
```

**How to reproduce**

1. Load, compile and run the [SimpleTexturedDirectx11](https://github.com/assimp/assimp/tree/master/samples/SimpleTexturedDirectx11) sample.
2. Place your model into the same folder as executable, with the default name _Models/myModel.fbx_.

**Expected behavior**

After launching the executable you should have an error saying that the model couldn't be loaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/35667100/95096281-bb7a9980-0734-11eb-95ec-73b719888fc1.png)

![image](https://user-images.githubusercontent.com/35667100/95096358-d3eab400-0734-11eb-8793-ef63079eedc4.png)

**System**

- Asimp Version: 5.0.1
- OS: Windows 10
- API: DirectX 11

**Additional context**

While assimp seems great and supports lots of formats it would be really helpful to have better documentation and more samples, as someone who is fairly new to programming it is really hard to begin integrating libraries with little to no documentation and samples into your project.

**Comment by Optimizer0** [comment]
Hello.

When run within Visual Studio, the program will look for the model in **Project Folder** not the executable folder. 
Put the Models folder in the same folder as the .cpp and .h files and it will work 

> Expected behavior
        After launching the executable you should have an error saying that the model couldn't be loaded.

True. I agree. When I wrote this sample (yes, I used "IAS" as my name back then) I was fairly new to Assimp and C++ as a whole. So my bad. I will fix it soon.

> While assimp seems great and supports lots of formats it would be really helpful to have better documentation and more samples, as someone who is fairly new to programming it is really hard to begin integrating libraries with little to no documentation and samples into your project.

I agree with this too. I'm thinking of creating a few new sample projects soon (including a skeletal animation one!). Don't worry they won't be like this one :D

**Comment by CaminoOnPc** [comment]
I tried placing the model in the project folder as you said, however, i just get another error now regarding textures, i thought it could be something to do with the model itself but i have replaced it with the custom one i just exported from blender and i still get the same error, running an executable from the folder itself without debugger results in the application crash without any messages.

![image](https://user-images.githubusercontent.com/35667100/95109187-ecfb6100-0744-11eb-8118-86ce27d38a6f.png)

Are you able to run this sample yourself with the latest version of assimp?

**Comment by Optimizer0** [comment]
I took a quick look at the code and it seems the mesh assumes there's always gonna at least a single texture be present. Which again, is bad code.

Does your fbx file have embedded textures? If not, you must the place the textures in the same folder as the model (myModel.fbx).

Also replace

```
devcon->PSSetShaderResources(0, 1, &textures[0].texture);
```

with

```
if(textures.size() > 0) devcon->PSSetShaderResources(0, 1, &textures[0].texture);
```

As a **_temporary fix_** for the above assumption situation. Now it shouldn't crash the program when there are no textures but the model will appear completely black.

**Comment by CaminoOnPc** [comment]
I tried models with both textures embedded into them and without any textures, both resulted in the same error, now when i applied your temporary fix it points towards something in _xstring_ but that's not helpful at all, i guess i will have to debug that with breakpoints and see what triggers it, but by that time i may be able to implement it in my project without sample, based on information published [here](https://assimp-docs.readthedocs.io/en/latest/usage/use_the_lib.html?highlight=directx#introduction)

![image](https://user-images.githubusercontent.com/35667100/95110992-888dd100-0747-11eb-9b2f-2955d4f13902.png)

**Comment by Optimizer0** [comment]
> I tried models with both textures embedded into them and without any textures, both resulted in the same error

That is strange. Will look into it.

**Comment by kimkulling** [comment]
You need to specify where the debugger shall run your application: https://stackoverflow.com/questions/4815423/how-do-i-set-the-working-directory-to-the-solution-directory-in-c

Now you shall be able to run the sample without copying the models. Or you can try to set the model-folder absolute.

Could you provide the model? So we can check whether there is a bug in the sample-app. Just reopen the issue then with that information. I guess the issue is caused by the fbx-importer, not by the sample app.
