### ISSUE TITLE
FBX animation doesn't play back correctly

### ISSUE THREAD

**Issue by AndrewJDR** [assimp/assimp#343]
I've found an FBX file that does not play back animation in an expected way using assimp.

Here's the FBX file in question:
http://ge.tt/api/1/files/8paQowr1/0/blob?download

Here's a video showing the incorrect playback in assimp viewer (on the left) vs. the expected playback in 3ds Max (on the right):
http://ge.tt/api/1/files/7BIgnwr1/0/blob?download

This is with the latest build of assimp as of this writing (fddae20cb).

**Comment by zhuyiif** [comment]
still can not play fbx ?

**Comment by kimkulling** [comment]
Shall be fixed now.

**Comment by AndrewJDR** [comment]
@kimkulling Which commit fixed this? Thanks!

**Comment by kkulling** [comment]
Honestly speaking: I do not know exactly. Just check the latest master. We made a lot of progress in the FBX-animation during the last monsts, so I cannot specify which commit closed the issue.
I walked through the open topics yesterday and saw this one, which shall be fixed.

If there are still issues on your side just reopen the issue!
