### ISSUE TITLE
Compile error, Visual Studio 2013 (error C2064: term does not evaluate to a function taking 1 arguments)

### ISSUE THREAD

**Issue by esp32diy** [assimp/assimp#3459]
**Describe the bug**
Error occures due to compiling on vs2013. Full log:
1>------ Build started: Project: assimp, Configuration: Release Win32 ------
1>  Exporter.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xrefwrap(283): error C2064: term does not evaluate to a function taking 1 arguments
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(228) : see reference to function template instantiation '_Ret std::_Callable_obj<int,false>::_ApplyX<_Rx,_Ty>(_Ty &&)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Rx=void *
1>  ,            _Ty=void *
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(228) : see reference to function template instantiation '_Ret std::_Callable_obj<int,false>::_ApplyX<_Rx,_Ty>(_Ty &&)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Rx=void *
1>  ,            _Ty=void *
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(226) : while compiling class template member function 'void std::_Func_impl<_MyWrapper,_Alloc,_Ret,void *>::_Do_call(void *&&)'
1>          with
1>          [
1>              _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>  ,            _Ret=void *
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(495) : see reference to class template instantiation 'std::_Func_impl<_MyWrapper,_Alloc,_Ret,void *>' being compiled
1>          with
1>          [
1>              _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>  ,            _Ret=void *
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(396) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Do_alloc<_Myimpl,_Ty,_Alloc>(_Fty &&,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>  ,            _Fty=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(396) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Do_alloc<_Myimpl,_Ty,_Alloc>(_Fty &&,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>  ,            _Fty=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(385) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Reset_alloc<_Ty,std::allocator<std::_Func_class<_Ret,void *>>>(_Fty &&,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Fty=int
1>  ,            _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(385) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Reset_alloc<_Ty,std::allocator<std::_Func_class<_Ret,void *>>>(_Fty &&,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Fty=int
1>  ,            _Alloc=std::allocator<std::_Func_class<void *,void *>>
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(671) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Reset<_Ty>(_Fty &&)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Fty=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(671) : see reference to function template instantiation 'void std::_Func_class<_Ret,void *>::_Reset<_Ty>(_Fty &&)' being compiled
1>          with
1>          [
1>              _Ret=void *
1>  ,            _Ty=int
1>  ,            _Fty=int
1>          ]
1>          D:\Projects\Singularity\SoftRender_v2\Third-party sources\assimp-master\code\Common\Exporter.cpp(598) : see reference to function template instantiation 'std::function<void *(void *)>::function<int>(_Fx &&)' being compiled
1>          with
1>          [
1>              _Fx=int
1>          ]
1>          D:\Projects\Singularity\SoftRender_v2\Third-party sources\assimp-master\code\Common\Exporter.cpp(598) : see reference to function template instantiation 'std::function<void *(void *)>::function<int>(_Fx &&)' being compiled
1>          with
1>          [
1>              _Fx=int
1>          ]
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Additional context**
You need to fix it, some of possible way is:
```
std::function<void *(void *)> ExportProperties::GetPropertyCallback(const char *szName) const {
	return GetGenericProperty<std::function<void *(void *)>>(mCallbackProperties, szName,
		[](void*) -> void* { return nullptr; }
		);
}
```

**Comment by kimkulling** [comment]
Visual Studi 2013 is no longer supported. You can switch to an older release or use a newer VS-Version.
