### ISSUE TITLE
vs2013, compile error. error C2039: 'uint32_t' : is not a member of 'std'

### ISSUE THREAD

**Issue by esp32diy** [assimp/assimp#3464]
**Describe the bug**
    catch (const DeadlyImportError& e)
    {
        if (!is64bits && (length > std::numeric_limits<std::uint32_t>::max())) {
            throw DeadlyImportError("The FBX file is invalid. This may be because the content is too big for this older version (", to_string(version), ") of the FBX format. (", e.what(), ")");
        }
        throw;
    }

**Additional context**
remove std::

**Comment by RichardTea** [comment]
VS2013 is no longer supported.
Please update your toolchain. VS2019 is recommended, unless you require XP support, in which case VS2017.
