### ISSUE TITLE
FBX read crashes

### ISSUE THREAD

**Issue by swq0553** [assimp/assimp#3467]
**Describe the bug**
the FBX file  is exported from DAZ 3D.
 Crash at 
`Document::ReadConnections()
{
...
 const std::string& type = ParseTokenAsString(GetRequiredToken(el,0));
...
}
`
the type is "PO",But it's not being processed.

**Comment by kimkulling** [comment]
Could you pleasse provide a small example?

**Comment by swq0553** [comment]
ok，try this.
[pose-test.zip](https://github.com/assimp/assimp/files/5426912/pose-test.zip)

**Comment by swq0553** [comment]
> Could you pleasse provide a small example?

is that fixed？

**Comment by tellypresence** [comment]
On recent assimp commit ([`9934a8d`](https://github.com/assimp/assimp/commit/9934a8d1cc58d9c5ddc6e0f39da0f86a7091e63b) 7 Oct 2024), unable to load model [`post-test.fbx`](https://github.com/assimp/assimp/files/5426912/pose-test.zip), import fails with error:
```
FBX-Parser (TOK_DATA, offset 0x48ef57) failed to parse ID, unexpected data type, expected L(ong) (binary)
```
