### ISSUE TITLE
Incorrect populated data while importing Collada (.dae) file with aiProcess_PopulateArmatureData flag

### ISSUE THREAD

**Issue by ZephyrL** [assimp/assimp#3468]
Hi,

I'm new to Assimp and want to use it for my program to import Collada files which contain Bone and Animation data.
I met a problem but I don't know if it's my not using it correctly or a bug, so I didn't make this a bug report.

The problem is, I use the following code to import the scene
```c
	const aiScene* scene = importer.ReadFile(ROOT_DIR + this->path, 
		//aiProcess_CalcTangentSpace |
		//aiProcess_Triangulate |
		//aiProcess_JoinIdenticalVertices |
		//aiProcess_SortByPType |
		aiProcess_PopulateArmatureData
	);
```
and I first handle the mesh data and the skeleton hierarchy, through this process I find the ``mesh->mBones[i]->mNode`` pointer is not pointing to the right place, but I bypass it with some high-complexity method and construct the hierarchy.

However, then I want to handle the bone weights of vertices and find that these data in the ``aiScene* scene`` are not available, the screenshot from my debugger is here,
![collada-problem-screenshot](https://user-images.githubusercontent.com/31087475/96559222-535cb380-12ef-11eb-9242-66f4c3025c94.png)
and it shows that either of the armature/weight/bone-node data is not accessible, but it's strange that the bone has a number of weights that seems plausible.

Before writing this issue I made the following checks:
* I'm coding on Windows 10, the project is configured for x86.
* I tried two versions of assimp.dll for the runtime, one is compiled from source from the assimp-5.0-release branch (ReleaseWithDebugInfo-x86), the other comes along with the [tutorial](https://github.com/Shot511/OpenGLSampleCmake/tree/master/dlls) that I follow to use OpenGL, both of the libraries have this issue
* The Collada file I'm using comes from [another tutorial](https://www.youtube.com/watch?v=f3Cr8Yx3GGA), the author provides both the [Blender file](https://drive.google.com/drive/folders/0B4_SgVGfVtFWVUN5MGF6SWpta00) and the [Collada model](https://github.com/TheThinMatrix/OpenGL-Animation/blob/master/Resources/res/model.dae), none of them get imported with the armature data.
* I tried to both to enable or disable the commented flags above, but this doesn't solve the problem.

* I tried to change the settings when exporting .dae file in Blender, by enabling/disabling "Arm->Deform Bones Only" and "Extra->Keep Bind Info", this doesn't help either.

As I'm not sure which step did I go wrong, or whether it's a bug or not, I'd be glad if you can provide any hint for solving this problem, thanks in advance!

**Comment by kimkulling** [comment]
Thanks for the detailed bug-report. I guess we need to check first if the armature support works in a proper way. I reworked a lot og the code used for Collada and maybe I broken some stuff.

**Comment by ZephyrL** [comment]
> Thanks for the detailed bug-report. I guess we need to check first if the armature support works in a proper way. I reworked a lot og the code used for Collada and maybe I broken some stuff.

Thank you for your reply :)
I'll also double-check my code and look into the Collada Parser part of code, I'll come back to this issue if I find something new.
