### ISSUE TITLE
Wrong SO name when building v5.0.1 from source

### ISSUE THREAD

**Issue by mcleary** [assimp/assimp#3469]
**Describe the bug**

I just built the library from source using the [latest 5.0.1 release](https://github.com/assimp/assimp/archive/v5.0.1.tar.gz) and these are the files produced from the build:

```
assimp-5.0.1/build/code$ ll -h
total 154M
drwxrwxrwx 1 thales thales 4.0K Oct 20 16:27 ./
drwxrwxrwx 1 thales thales 4.0K Oct 20 16:25 ../
drwxrwxrwx 1 thales thales 4.0K Oct 20 16:09 CMakeFiles/
-rwxrwxrwx 1 thales thales  11K Oct 20 16:25 cmake_install.cmake*
lrwxrwxrwx 1 thales thales   14 Oct 20 16:27 libassimp.so -> libassimp.so.5*
lrwxrwxrwx 1 thales thales   18 Oct 20 16:27 libassimp.so.5 -> libassimp.so.5.0.0*
-rwxrwxrwx 1 thales thales 154M Oct 20 16:27 libassimp.so.5.0.0*
```

This is the same result from tag `v5.0.1`

I know the version was fixed but the release package still produces the wrong result

**Comment by kimkulling** [comment]
You are right, this issue is in the release. Afterward  we have the latest version.

**Comment by mcleary** [comment]
Feel free to close the issue at any point as this is not super important. I just thought in informing you about this

**Comment by kimkulling** [comment]
Ok, I will close it. Thanks for your investigation!
