### ISSUE TITLE
Assimp fails on importing ifc2X3 file

### ISSUE THREAD

**Issue by 2012312055** [assimp/assimp#3472]
**Describe the bug**
Fails on importing ifc2x3 file

**To Reproduce**
Assimp::Importer import;
const aiScene* scene = import.ReadFile(path, aiProcess_Triangulate);

err "(entity #16) type error reading entity - expected argument 1 to IfcRoot to be a `IfcOwnerHistory`"

Entities using #16 in .ifc
#1=IFCPROJECT('{42B1A13A-057F-4D06-BA84-072234BAB537}',#2,'Project',$,$,'Test',$,(),#14);
#2=IFCOWNERHISTORY(#3,#6,$,$,$,$,$,1603237519);
#3=IFCPERSONANDORGANIZATION(#4,#5,$);
#4=IFCPERSON('UserID','UserLastName','UserFirstName',$,$,$,$,$);
#5=IFCORGANIZATION('OrganizationID','organizationName',$,$,$);
#6=IFCAPPLICATION(#5,'version','SDK','IFC2X3');
#7=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.,#8,#12);
#8=IFCAXIS2PLACEMENT3D(#9,#10,#11);
#9=IFCCARTESIANPOINT((0.,0.,0.));
#10=IFCDIRECTION((0.,0.,1.));
#11=IFCDIRECTION((1.,0.,0.));
#12=IFCDIRECTION((0.,1.));
#13=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*,#7,$,.MODEL_VIEW.,$);
#14=IFCUNITASSIGNMENT((#15));
#15=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#16=IFCSITE('{DC471AB6-2F88-4644-B319-2605E5A8920A}',$,'Site',$,$,#17,$,$,.ELEMENT.,$,$,$,$,$);
#17=IFCLOCALPLACEMENT($,#18);
#18=IFCAXIS2PLACEMENT3D(#19,$,$);
#19=IFCCARTESIANPOINT((0.,0.,0.));
#20=IFCRELAGGREGATES('{A82113B7-E292-4270-9188-6491AE5C2156}',$,'Aggregate0',$,#1,(#16));
#21=IFCBUILDING('{D19CDD04-0D30-4720-8780-8A847B89A2F0}',$,'Pier',$,$,#22,$,$,.ELEMENT.,$,$,$);
#22=IFCLOCALPLACEMENT($,#23);
#23=IFCAXIS2PLACEMENT3D(#24,$,$);
#24=IFCCARTESIANPOINT((0.,0.,0.));
#25=IFCDIRECTION((0.,1.,0.));
#26=IFCRELAGGREGATES('{92D78E47-9033-49F1-A2CC-62E21A90B0C4}',$,'Aggregate0',$,#16,(#21));

**Desktop (please complete the following information):**
Windows 10
VS 2019
Assimp installed via vcpkg, 2020.10.22

**Comment by kimkulling** [comment]
IFC2x3 is currently not supported, sorry for the inconveniance!
