### ISSUE TITLE
GLTF2 invalid property

### ISSUE THREAD

**Issue by thomasbiang** [assimp/assimp#3482]
**Describe the bug**
I exported a valid scene with bones in it, in format gltf2/glb2. There is many errors related unexpected property "skeletons", "jointName" and "bindShapeMatrix".

I looked into the gltf2 spec at https://github.com/KhronosGroup/glTF/tree/master/specification/2.0, there is no property named "skeletons" or "jointName" allowed.

However in Assimp https://github.com/assimp/assimp/blob/de610b8ce9626a1e4443e491f62ac09fa119584e/code/AssetLib/glTF2/glTF2AssetWriter.inl#L543
they are exported, which caused the error report.

Here is a sceenshot of reported errors from https://github.khronos.org/glTF-Validator/:

<img width="800" alt="Screen Shot 2020-11-02 at 2 09 31 PM" src="https://user-images.githubusercontent.com/37556510/97925140-bd288480-1d15-11eb-9495-0d37422039d0.png">

**Expected behavior** 
skeletons and jointName should not be in gltf2 glb2 files.

**Comment by chenxiaoliwhut** [comment]
You can find skeletons property in skins in the URL that you provided, I'm not sure if this would help you

**Comment by thomasbiang** [comment]
> You can find skeletons property in skins in the URL that you provided, I'm not sure if this would help you

Under "skin" the property should be "skeleton" with no s, not really "skeleton**s**". Plus the "skeleton**s**" here in glTF2AssetWriter is not even under "skin", they are wrongly put in node. 

jointName is also a problem.

**Comment by thomasbiang** [comment]
Here I upload a screenshot from https://github.khronos.org/glTF-Validator/ diagnosing the glb file exported by assimp
You will see unexpected properties like "skeletons", "jointName" and "bindShapeMatrix"  reported. They are all violating gltf2 specification.
 
<img width="800" alt="Screen Shot 2020-11-02 at 2 09 31 PM" src="https://user-images.githubusercontent.com/37556510/97924859-2e1b6c80-1d15-11eb-9ca2-8aa93aedc67c.png">

**Comment by kimkulling** [comment]
Thanks for the feedback. Seems to be a lot of work to do there.

**Comment by thomasbiang** [comment]
Hi @kimkulling, is there any plan for fixing this?

**Comment by kkulling** [comment]
For sure!

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3636.
