### ISSUE TITLE
Question About Compiling without Boost

### ISSUE THREAD

**Issue by AABBTree** [assimp/assimp#3483]
I am having problems with  assimp2json which uses some kind of an assimp version without Boost (https://github.com/acgessler/assimp2json/issues/23):

``
fatal error: assimp/../../code/BoostWorkaround/boost/scoped_ptr.hpp: No such file or directory
   23 | #include <assimp/../../code/BoostWorkaround/boost/scoped_ptr.hpp>
``

The link http://assimp.sourceforge.net/lib_html/install.html indicates that

``
These implementations are very limited and are not intended for use outside assimp. A compiler with full support for partial template specializations is required. To enable the workaround, put the following in your compiler's list of predefined macros:

#define ASSIMP_BUILD_BOOST_WORKAROUND
``

How can one compile/include assimp without Boost to provide these missing header files for such programs as assimp2json, where does this above-mentioned #define need to be placed in the assimp source in order to generate a complete non-Boost-based assimp include folder?

**Comment by kimkulling** [comment]
Which version do you use?

**Comment by AABBTree** [comment]
Oh, thanks, I see the problem now. I forgot to git clone assimp2json <b>recursively</b>, it uses the assimp version 3, i.e. inside assimp2json/assimp/CMakeLists.txt:

``
set (ASSIMP_VERSION_MAJOR 3)
set (ASSIMP_VERSION_MINOR 1)
set (ASSIMP_VERSION_PATCH 1) # subversion revision?
``

While the contemporary git cloned assimp is of version 5.0.1 and the Ubuntu 20.04 seems to provide 5.0.0.

So assimp2json works with version 3 while it breaks on version 5.0.0. I will close this issue now, but consider that I would not know how to use that #define ASSIMP_BUILD_BOOST_WORKAROUND, alone, Sect. "CMake: ENABLE_BOOST_WORKAROUND" at http://assimp.sourceforge.net/lib_html/install.html was not so clear/incomplete for me install instructions-wise.

**Comment by kimkulling** [comment]
We have integrated the assimp2json into the main branch. So you can directly use the latest master for that. The boos-workaround is deprecated. That is the reason for not finding the files.
