### ISSUE TITLE
Extra face in FBX file.

### ISSUE THREAD

**Issue by unvestigate** [assimp/assimp#3485]
I recently started modeling a vehicle in blender and exported it to my game engine through an FBX file. The FBX is brought into my game engine using assimp. I noticed that there is an extra face on the imported mesh, which does not appear when opening the FBX file in other applications. It is, however, visible in the assimp viewer, so it seems this is a bug in assimp. This is what the mesh looks like in blender:

![blender](https://user-images.githubusercontent.com/20167696/97906630-acdfcc00-1d4c-11eb-901f-5285d7bb0a5e.png)

And here is the same mesh in the assimp viewer:

![assimp_viewer](https://user-images.githubusercontent.com/20167696/97906751-e0225b00-1d4c-11eb-90f2-a3bd99ecde15.png)

I highlighted the extra triangle in red. I uploaded the problematic fbx file to: http://www.sourcedrive.net/assimp_fbx_problem/chassis.fbx

I am testing this with assimp master, downloaded on 2. November 2020.

**Comment by kimkulling** [comment]
Currect, there is one invalid face. You can see it much better when using wireframe view.
![image](https://user-images.githubusercontent.com/2323156/98037648-31e5e680-1e1c-11eb-914a-14a00388aa59.png)

**Comment by kimkulling** [comment]
The problem is caused by the triangulation process, not by the FBX-Parser.

**Comment by kimkulling** [comment]
So I got it, There was an extra vertex in your polygon, which has caused the extra face:
![extra_vertex](https://user-images.githubusercontent.com/2323156/100496921-5ce00380-3158-11eb-9b21-a57cb608b78b.png)

I have fixed the model and now the triangulation works fine:
https://drive.google.com/drive/folders/1Fj4mWgaVOnX9_U5Xvqi00-9fsNdbt1nu?usp=sharing

**Comment by unvestigate** [comment]
Thanks, yeah I got around the issue by cleaning up the mesh myself. However, that doesn't change the fact that most programs opened the FBX file with the additional vertex correctly, while assimp did not. So there is (or were) clearly a bug in the fbx importer at the time.

**Comment by kimkulling** [comment]
That is correct. I am currently looking for a good replacement for our hand-written triangulator for polygons. Seems to be buggy I guess :-). 
Any recommendations? Currently, I am playing around with clipper!

**Comment by kimkulling** [comment]
And the bug is not part of the FBX-parsing. All faces were imported correctly. The triangulation post-process has created your glitch. So I checked the code of if and the ear-clipping algorithm seems to cause the problem. So My plans are to find a triangulation lib for that.

**Comment by unvestigate** [comment]
I see. Thanks for checking it out, and keep up the good work!
