### ISSUE TITLE
error while making the assimp

### ISSUE THREAD

**Issue by mmahdavian** [assimp/assimp#3517]
Hi. I am trying to make your repo and I am getting this following on your master branch. I should say that I tried another commit (7acc4c6808455980bac47f3b01275fb74e0839df ) and it worked, but for some reason I wanted to test your last version too. Can you help me for fixing it?

Thank You
```
Scanning dependencies of target assimp
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseProcess.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/CApi/CInterfaceIOWrapper.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/Assimp.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseImporter.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/PostStepRegistry.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/DefaultIOStream.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/DefaultIOSystem.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o
In file included from /home/mohammad/Mohammad_ws/habitat/assimp/code/Common/ImporterRegistry.cpp:117:0:
/home/mohammad/Mohammad_ws/habitat/assimp/code/AssetLib/AC/ACLoader.h:120:34: error: enclosing class of constexpr non-static member function ‘uint8_t Assimp::AC3DImporter::Surface::GetType() const’ is not a literal type
         inline constexpr uint8_t GetType() const { return (flags & Mask); }
                                  ^
/home/mohammad/Mohammad_ws/habitat/assimp/code/AssetLib/AC/ACLoader.h:100:12: note: ‘Assimp::AC3DImporter::Surface’ is not literal because:
     struct Surface {
            ^
/home/mohammad/Mohammad_ws/habitat/assimp/code/AssetLib/AC/ACLoader.h:100:12: note:   ‘Assimp::AC3DImporter::Surface’ has a non-trivial destructor
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/Importer.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/SGSpatialSort.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/VertexTriangleAdjacency.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/SpatialSort.cpp.o
code/CMakeFiles/assimp.dir/build.make:182: recipe for target 'code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.o' failed
make[2]: *** [code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'code/CMakeFiles/assimp.dir/all' failed
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by RichardTea** [comment]
Which platform and compiler toolchain are you using?

**Comment by kimkulling** [comment]
Which compiler have you used?

**Comment by mmahdavian** [comment]
I am using cmake in ubuntu 16.04.

**Comment by gwcew** [comment]
It's true. I have the same trouble on Manjaro with cmake gcc(++) 10.2.0

**Comment by Biswa96** [comment]
What CMake command did you use to generate for a build system? I have compiled assimp latest master branch (today, as of writing) with GCC 10.2.0 in ArchLinux without any _compiler error_.

**Comment by gwcew** [comment]
> What CMake command did you use to generate for a build system? I have compiled assimp latest master branch (today, as of writing) with GCC 10.2.0 in ArchLinux without any _compiler error_.

@Biswa96, so I just using -Wpedantic flag while compilation.

**Comment by Biswa96** [comment]
Removing the `constexpr` specifier fixes this issue. But I am not sure about the reason and what the result will be after that change. This issue seems to be a [C++ standard][1] thing.

[1]: https://stackoverflow.com/a/36489493/8928481

**Comment by gwcew** [comment]
> Removing the `constexpr` specifier fixes this issue. But I am not sure about the reason and what the result will be after that change. This issue seems to be a [C++ standard](https://stackoverflow.com/a/36489493/8928481) thing.

@Biswa96 and what do you suggest to me if I want to support -Wpedantic flag and use assimp library too? :c

**Comment by gwcew** [comment]
To fix the problem you can use in your cmake config this:

target_compile_options(assimp PRIVATE -Wno-error=pedantic)

And you will get the message as a warning not as an error.

**Comment by kimkulling** [comment]
I will replace the constexpr by a simple const. This should be enough to fix the issue.

**Comment by vatsuak** [comment]
I was running into a similar issue.
```
assimp-src/code/../contrib/rapidjson/include/rapidjson/document.h:418:7: note: 'class rapidjson::GenericValue<rapidjson::UTF8<> >' declared here
  418 | class GenericValue {
      |       ^~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:2456: code/CMakeFiles/assimp.dir/glTFExporter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:178: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I had to check out to the https://github.com/assimp/assimp/commit/7acc4c6808455980bac47f3b01275fb74e0839df
and it seems like the issue was solved.
