### ISSUE TITLE
Assimp cant load .blend files.

### ISSUE THREAD

**Issue by samrrr** [assimp/assimp#3522]
Current version of assimp cant load any .blend file i have.

Need remove .blend from this page. Because assimp do NOT support blender files.
https://assimp-docs.readthedocs.io/en/latest/about/introduction.html

**To Reproduce**
1. Save dafault blender scene.
2. Try load its with assimp.

**Expected behavior**
A loaded cube.

**Screenshots**
![image](https://user-images.githubusercontent.com/18705603/101232587-7e466f80-36c3-11eb-94e8-38beebdea50f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 5.0.1

**Comment by kimkulling** [comment]
Have you used Blender > 2.80?

**Comment by congard** [comment]
Possibly duplicate of #3316

**Comment by samrrr** [comment]
I have latest blender. But when i use old files its cant load too.

**Comment by kimkulling** [comment]
Duplicate to https://github.com/assimp/assimp/issues/3407 . I will close this on.
