### ISSUE TITLE
intel ax200 cannot compile backport-iwlwifi

### ISSUE THREAD

**Issue by dominbdg** [assimp/assimp#3523]
Hi,
I'm trying to compile backport-iwlwifi with errors.
First git clone https://github.com/OSEC-pl/backports-iwlwifi.git
Second after make -j 4 i have below issue:

[make.txt](https://github.com/assimp/assimp/files/5648421/make.txt)

**Comment by kimkulling** [comment]
I guess this seems to b an issue with an outdated struct. But I guess this is not related to assimp, because this seems to be a Linux-kernel-issue.
