### ISSUE TITLE
Improving Build Instructions

### ISSUE THREAD

**Issue by Underdisc** [assimp/assimp#3551]
This is very general as I feel there are multiple areas that could be improved when it comes to building, integrating assimp, and making that process easier for others. I am not the best when it comes to building other projects, so maybe this is from lack of experience on my part, but that doesn't change the fact that I think the build instructions could be made more clear for others who aren't able to solve these problems on their own as easily.

I am using msvc2019 (142) for compiling and Ninja as the generator. I am performing builds like so.

```
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=MinSizeRel ../../../
ninja
```

What files are created by the build process and which ones are relevant is never explicitly stated. For example, after performing a build, the relevant files are split between `bin/` and `lib/`. For me the only things I am looking for are `bin/assimp-vc142-mt.dll` and `lib/assimp-vc142-mt.lib`. Here is a list of everything I am not looking for.
```
lib/assimp-vc142-mt.exp
bin/assimp.exe
bin/assimp.exe.manifest
bin/assimp-vc142-mt.dll.manifest
bin/unit.exe
bin/unit.exe.manifest
```
Maybe it's just me, but I think the files that users will likely take away and put into their own project should all just go into one output directory so users can organize it in a way that works for their project. It also wouldn't hurt if specific targets were mentioned in build docs so users don't build unnecessary things like `unit.exe`.

Also, small note, I am not sure why the files produced under msvc are named `*-mt.*` when I am pretty certain these files were created with the `/MD` option. At least, I have not received any of the warnings I would typically see when linking with libraries that are compiled with conflicting `/M*` options.

Inside of `include/assimp/` there is a file called `config.h.in`. I didn't see any build docs mention that this file should be replaced by the `inlcude/assimp/config.h` file that is created by the build process. I only figured this out because because I received a compiler error telling me that config.h didn't exist. I looked in my assimp include dir and found `config.h.in`, changed it to `config.h` and commented out the last line `#undef ASSIMP_DOUBLE_PRECISION` after getting another error. All the build process does is comment out this line before creating `config.h`.

I do not believe turning off BUILD_SHARED_LIBS works. When I do this and link with the produced lib, I get an executable that still depends on another binary. Strangely, the dialogue box says it depends on `assimp.exe` but I haven't opened up the build of my project with dependency walker to see if this is actually the case. I find it very strange that `assimp.exe` was stated as a dependency rather than a dll, but I put `assimp.exe` next to my build anyways just to see what would happen. I promptly received a segfault and I can only assume that it's from assimp.

Also, the BUILD_DOCS cmake flag doesn't seem to be in use anymore and should probably be removed from Build.md.

Just some things to think about. Feel free to close this if it's not really a concern. I am just posting something about my initial experience because I would appreciate this sort of feedback if I was on the other end of this. So I hope it's helpful. I am integrating assimp into my own project and these small bumps I have run into could have been avoided if there were accessible build docs that went into more detail about the building and integration process.

**Comment by kimkulling** [comment]
You are right. I just started to read your post, so more to come.

If you want to help to optimize the docs just check https://assimp-docs.readthedocs.io/en/latest/ or the github-project https://github.com/assimp/assimp-docs
