### ISSUE TITLE
Assimp compilation issue with mingw32

### ISSUE THREAD

**Issue by Alex533704** [assimp/assimp#3563]
Hello  I'm using mingw32  and gcc 9.2.0 on Windows 10.

I tried to compile Assimp 5.0.1 with mingw32 but an error occured:

**C:\Users\MY_NAME\Downloads\assimp-5.0.1\assimp-5.0.1\code\SMD\SMDLoader.cpp:579:12: error: 'strtok_s' was not declared in this scope; did you mean 'strtok_r'?**

Can you help me?

**Comment by kimkulling** [comment]
Yes, there is a bundle of preprocessor-definitions to detect the right compiler environment when working on Windows. In the beginning of our development we started to use a lof of VS-detection until we as that people wants to build the assimp-library with gcc on windows as well. 

We need to offer the right string tokenizer calls for this. So the issue will get fixed!

**Comment by kimkulling** [comment]
Also in https://github.com/assimp/assimp/issues/3679, I wil close this one and use the newer one because there is another compile bug description in.
