### ISSUE TITLE
DAE import regression since 3.3.1

### ISSUE THREAD

**Issue by mlfarrell** [assimp/assimp#3564]
**Describe the bug**
Importing the attached DAE file was successful on assimp-3.3.x, but now fails on the latest master - 5.0.1

**To Reproduce**
Run assimp import on the attached file - https://vertostudio.com/pub/delme/bad_dae.zip

**Expected behavior**
Successful import

**Actual behavior**
```
Unable to read the given file.
Expected different index count in <p> element.
```

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by makitsune** [comment]
I've seen the same bug too with a dae file I downloaded online. However, exporting from blender didn't have any issues.

**Comment by kimkulling** [comment]
This issue was introduced by the collada-migration to pugi_xml. I have a pull request for that.

**Comment by kimkulling** [comment]
Shall be fixed now!
