### ISSUE TITLE
COLLADA object with incorrect scaling

### ISSUE THREAD

**Issue by agerrius** [assimp/assimp#3568]
The attached COLLADA object has a RootNode after importing it with Assimp 5.0 that has a scale of 0 applied to it, which makes the object disappear.

I have narrowed the issue down to this line in the COLLADA file already:

<unit meter="0.02539999969303608" name="bla" />

If I remove some digits from the meter attribute the object loads fine.

[Test1.zip](https://github.com/assimp/assimp/files/5772406/Test1.zip)

**Comment by tellypresence** [comment]
Test1.dae model (in [Test1.zip](https://github.com/assimp/assimp/files/5772406/Test1.zip) attached above) loads and renders OK for me

**Comment by kimkulling** [comment]
Have you tried the latest master. This shoulb be fixed.

Steve M <notifications@github.com> schrieb am Di., 16. Feb. 2021, 00:09:

**Comment by agerrius** [comment]
> Have you tried the latest master. This shoulb be fixed. 

OK, I'll try the latest version.

Is there still a Windows binary of the latest version available. Before I took it from the CI server, but that link has been gone for the last half year or so. Else I would have to setup my build environment again first.

**Comment by kimkulling** [comment]
Not at the moment. You need to build the library on your own. I will add a ticket for myself as a reminder that the installer from the current master are still not available.
