### ISSUE TITLE
assimp_viewer crash with std::transform and tolower in windows RelWithDebInfo build

### ISSUE THREAD

**Issue by ddengster** [assimp/assimp#3572]
**Describe the bug**
A crash while using std::transform to convert the string to lowercase

**To Reproduce**
- generate assimp.sln via cmake with "Visual Studio 16 2019" -A x64 and launch assimp.sln and build with RelWithDebInfo.
- Load an FBX file in the assimp_viewer in BINARIES\x64\tools\assimp_view\RelWithDebInfo 

**Expected behavior**

**Screenshots**
crash in xstring
![image](https://user-images.githubusercontent.com/3326941/103788794-375ce880-507a-11eb-9372-731af3d4d941.png)

![image](https://user-images.githubusercontent.com/3326941/103788843-46439b00-507a-11eb-9dd8-f4bb6e16c431.png)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Possibly a more defensive way to handle this is to use the for loop to iterate through the string and applying tolower(), like this:
```
 for (size_t i = 0; i < shading.length(); ++i)
    shading[i] = tolower(shading[i]);
```

**Comment by RichardTea** [comment]
This is a compiler bug in MSVC v16.7 (and presumably other versions)
Looks like it was reported to Microsoft last year in October- https://developercommunity.visualstudio.com/content/problem/1223143/visual-studio-2019-c-program-crash-with-stdstring.html

It appears that the optimizer is doing bad things.

**Comment by kimkulling** [comment]
Thanks for figuing that out. Pull-request is on its way!
