### ISSUE TITLE
Assimp shouldn't build zlib at all if ASSIMP_BUILD_ZLIB is off

### ISSUE THREAD

**Issue by DatCaptainHorse** [assimp/assimp#3574]
Instead of going and building zlib from source if zlib isn't found, it should throw an error and stop the CMake generation. It makes much more sense, currently it's like: _"Hey, don't build zlib by yourself"_ and it assimp goes and does it anyways, what a chad.

**Comment by kimkulling** [comment]
Good hint, I will need to check that :-).

**Comment by feliwir** [comment]
Being able to disable ZLib would be a big requirement for us aswell. I've disabled all exporters and only enabled **OBJ** and **STL** however we still link ZLib :-/
