### ISSUE TITLE
Collada importer fails to read animations

### ISSUE THREAD

**Issue by rcane** [assimp/assimp#3584]
The commit fb20e15163fe1ac27841f8b43faab53465b320ef broke the code that reads animations in the Collada parser.

The defect is in ColladaParser.cpp in the `ColladaParser::ReadAnimation()` method. Here is the relevant part:

```cpp
void ColladaParser::ReadAnimation(XmlNode &node, Collada::Animation *pParent) {
...
    for (XmlNode &currentNode : node.children()) {
        if (currentName == "animation") {
            ...
        } else if (currentName == "source") {
            ....
        } else if (currentName == "sampler") {
            if (XmlParser::getStdStrAttribute(currentNode, "id", id)) {
                ...
            } else if (currentName == "channel") {  // <-- this is wrong, this else-if belongs one level up
               ...
            }
    }
...
}
```

This is an example of a (stripped down) `<animation>` node:

```xml
<animation id="Cube_transform_" name="Cube-Move">
      <source id="Cube_transform_-input"></source>
      <source id="Cube_transform_-output"></source>
      <source id="Cube_transform_-interpolation"></source>
      <sampler id="Cube_transform_-sampler"></sampler>
      <channel source="#Cube_transform_-sampler" target="Cube/transform"/>
</animation>
```

A `channel` node is a direct child of `animation` but the current code cannot read it at all because of the wrongly placed `else-if`.
This looks like a merge error when the code was changed to use the new xml parser. The old code did it correctly.
The fix is to simply move the else-if with the `channel` one level up.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3619
