### ISSUE TITLE
Collada parser does not read the unit value

### ISSUE THREAD

**Issue by rcane** [assimp/assimp#3599]
Commit 080322b9e2aa96f4258ecbf4efc58564b7721feb introduced a bug in the code reading the `meter` attribute of the `unit` node under the `asset` node. This means that right now any Collada file not having 'meter' as its unit will be incorrectly scaled.

The following unit definition inside a Collada file will not work as expected.
```xml
<asset>
  <unit meter="0.0254" name="inch" />
</asset>
```

This is the code in ColladaParser.cpp that has the bug:

```cpp
void ColladaParser::ReadAssetInfo(XmlNode &node) {
    if (node.empty()) {
        return;
    }

    for (XmlNode &currentNode : node.children()) {
        const std::string &currentName = currentNode.name();
        if (currentName == "unit") {
            mUnitSize = 1.f;
            XmlParser::getFloatAttribute(node, "meter", mUnitSize);  // <-- 'node' needs to be 'currentNode'
        } else if (currentName == "up_axis") {
        ...
        }
     }
}
```

**Comment by kimkulling** [comment]
Thanks for the report, the fix is on its way. This was introduced during the migration to pugixml.

**Comment by kimkulling** [comment]
Fixed, and thanks a lot for your investigations! It helped a lot!
