### ISSUE TITLE
i can import gltf2 file but it is not working in debug mode. i made a video to show. 

### ISSUE THREAD

**Issue by emrekaya413** [assimp/assimp#3605]
windows 10 64bit
ide = code blocks 64bit
compiler = mingw64 bit
assimp version = 5.0.1
i exported gltf2 (.glb) file and thanks to blender 2.9 

video youtube [link](https://www.youtube.com/watch?v=ocQsiTwebNw)

problem is in just debug mode. Or i did somethings wrong. What should be problem ?

debug mode is working without import gltf2 file.

**Comment by kimkulling** [comment]
Seems to be an issue with your build- and debugging-environment. For me, the debugger just works fine - even when I am using the gdb on Linux. 
Maybe you can try to check if all shared-object-libraries are loaded correctly. Maybe you build them without debug information or you have a mixup of release- and debug-libraries, which could cause such a mess as well?
