### ISSUE TITLE
How do I prohibit merging identical vertices

### ISSUE THREAD

**Issue by wujie-zxc** [assimp/assimp#3626]
**Describe the bug**

To build the cube, I put 24 vertices into Vertex, but the number of GLTF vertices exported becomes 8. How do I prohibit merging the same vertices ？

Can I set the last argument to this function ？ 

ASSIMP_API aiReturn aiExportSceneEx(const C_STRUCT aiScene *pScene,
        const char *pFormatId,
        const char *pFileName,
        C_STRUCT aiFileIO *pIO,
        unsigned int pPreprocessing);

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kimkulling** [comment]
The question is: what is the reason to avoid the merge? Do you have a special reason for that?

The vertices gets merged when the data used by then are the same. The JoinVerticesProcess is doing that. To Avoid that you can use post-processing chain without using that.

**Comment by kimkulling** [comment]
For instance these settings shall work for you:

```
#define aiProcessPreset_TargetRealtime_Quality_WithoutJoining ( \
    aiProcess_CalcTangentSpace              |  \
    aiProcess_GenSmoothNormals              |  \
    aiProcess_ImproveCacheLocality          |  \
    aiProcess_LimitBoneWeights              |  \
    aiProcess_RemoveRedundantMaterials      |  \
    aiProcess_SplitLargeMeshes              |  \
    aiProcess_Triangulate                   |  \
    aiProcess_GenUVCoords                   |  \
    aiProcess_SortByPType                   |  \
    aiProcess_FindDegenerates               |  \
    aiProcess_FindInvalidData               |  \
    0 )


```
