### ISSUE TITLE
How to handle an OBJ file that's missing texture coordinate component?

### ISSUE THREAD

**Issue by kizjig** [assimp/assimp#3627]
**Describe the bug**
I have an obj file that is exported without UVs from a 3rd party tool (CADSoftTools) and it doesn't contain all the face components for a face row in the raw data.

Eg:-
`f 2/1 3/1 1/1`

instead of looking like this (which is read fine by assimp):-
`f 2//1 3//1 1//1`

So normally the format for f command is `f position_id/texture_coordinates_id/normal_id`. In my example data above I have  `f position_id/normal_id`

When it is attempted to be loaded by assimp I get the following error: "Failed to load file (Invalid face indice)"

**Desktop (please complete the following information):**
 - OS: Ubuntu
- Running assimp: v4.1.0

**Is there currently anyway to load the file in assimp where it doesn't expect the uv data component and it would happily read 2 components per face indice instead of 3?**

**Comment by kimkulling** [comment]
Normally this case should be handled correctly. We need th check. Do you have a sample-model to reproduce this issue?

**Comment by kimkulling** [comment]
At this moment there is no way to reorganize the ordering of expected vertices. You could try to add an empty ( 1.0 ) dummy-texture coordinate to your model before exporting it.
