### ISSUE TITLE
Large STEP not working

### ISSUE THREAD

**Issue by Nv7-GitHub** [assimp/assimp#3631]
**Describe the bug**
I exported a STEP model from fusion 360 since OBJ exporting wasn't working. I want to export it as an OBJ. When I do `assimp export file.step file.obj`, I get the error `ERROR: Failed to load file: DXF: no data blocks loaded`.

**To Reproduce**
1. Export STEP from fusion 360
2. Try to convert it to OBJ

**Expected behavior**
I was expecting it to convert.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version: `Version 5.0 -debug -shared -st (GIT commit 754b2ba4)` (`assimp version`)

**Comment by michele-arrival** [comment]
Does a small step file work?

It looks like the step Importer has been removed with https://github.com/assimp/assimp/pull/3196

Would be interesting to know why? 

any input from @kimkulling ?

**Comment by kimkulling** [comment]
At this moment spef-file imports are not implemented.
