### ISSUE TITLE
get exception when load .STEP files

### ISSUE THREAD

**Issue by bootcap** [assimp/assimp#3632]
**Describe the bug**

I want to convert `.STEP` file into `.stl` file, here is my code:
```
import pathlib
import pyassimp

def convert_2_stl(file_name):
    try:
        scene = pyassimp.load(file_name)
        pyassimp.export(scene, pathlib.Path(file_name).stem + '.stl', file_type='stl')
        return True
    except Exception as e:
        print(e)
        return False
```
However, I always get error when loading the `.STEP` file.
When I try to use pyassimp-4.1.3, I got:
'LP_Node' object has no attribute 'meshes'
When I try to use pyassimp-4.1.4, I got:
'bytes' object has no attribute 'aketrans'

I have tried many different `.STEP` files, they all failed the same way.

Did I do anything wrong?

**Desktop:**
 - OS: [Win 10]
 - Version [python3.6, pyassimp-4.1.4 & pyassimp-4.1.3]

**Comment by michele-arrival** [comment]
did you manage to solve this?

**Comment by kimkulling** [comment]
Which kind of step-file do you want to load. Normally this one is not working because the loader is not ready. So if this is a real stepfile this behaviour is normal. 

Please reopen if you have a IFC-file.
