### ISSUE TITLE
Access to files bundled with Android Applications

### ISSUE THREAD

**Issue by contriteobserver** [assimp/assimp#3633]
**Is your feature request related to a problem? Please describe.**
Android provides a number of filesystems, one of which allows access to open and read raw files that have been bundled with the application 

**Describe the solution you'd like**
An asset IOsystem that implements an APK loader to `Assimp::DefaultIOSystem` 

**Additional context**
The Android AssetManager presents a lower-level API that permits opening and reading raw files that have been bundled with and Android APK.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3634.

Thanks a lot for your contribution!
