### ISSUE TITLE
[Animation question] mesh becomes detached when animation active

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#3637]
(Apologies, having a strange problem when animating a particular model and not sure if this is a problem with the model, a bug, or a mistake in my own code, so seeking insight/confirmation -- thank you)

When model loaded with `aiProcess_PreTransformVertices` = 1, all meshes are in the correct positions:
![wraith_pre_transform_correct_20210216_225045](https://user-images.githubusercontent.com/26958898/108589043-c8c0b980-739f-11eb-89d3-0bd30f00208a.gif)

but when loaded with animations enabled, node[0] ("jumpkit"), which normally is attached to the figure's lower back, is instead incorrectly detached and sitting in space at some fixed offset position:
![wraith_w_jumpkit_detached_20210216_224354](https://user-images.githubusercontent.com/26958898/108588940-20aaf080-739f-11eb-904c-b941a734f521.gif)

Just trying to understand whether this is a problem in the 3D model file or an oversight on my part (I read something about unanimated bones being used as attachment points but haven't explicitly done anything to deal with this case)  If anyone with animation implemented in their project can offer any insight it would be much appreciated, thank you

P.S. Model can be download from [here](https://www.cgtrader.com/free-3d-models/character/woman/wraith-cyber-ninja-apex-legends) by selecting item `gltf.zip` (will download file `uploads_files_2639757_gltf.zip`) and using file `gltf/glb/Wraith_Animated.glb`

**Comment by kimkulling** [comment]
Seems to be a bug, we need to check. Thanks for the report!

**Comment by tellypresence** [comment]
Mea culpa.  Same model, after a refactor of my code; "jump kit" now properly attached.

<img alt="wraith_animated_jumpkit_correct" src="https://user-images.githubusercontent.com/26958898/218334765-7b8e7508-60d5-4ef2-aac9-37840b3a41c4.gif" width=320>

Closing as this problem was clearly self-inflicted
