### ISSUE TITLE
X3D importer is missing

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#3647]
**Describe the bug**
During the xml-migration X3D-importer was removed. We need to reimplement it.

**To Reproduce**
Try to import a X3D-file

**Expected behavior**
Shall be imported

**Additional context**
N/A

**Comment by kimkulling** [comment]
Here the PR: https://github.com/assimp/assimp/pull/3892

**Comment by Artenuvielle** [comment]
I migrated the source code from version 5.0.1 to support pugixml. Sinc I did not want to get into conflict with your PR @kimkulling, I made my own PR: https://github.com/assimp/assimp/pull/4079.
One thing I noticed with one of my test files: while it took me 2,3s to load up a x3d file on version 5.0.1 it took me 17,8s to load that file after the migration (both tested Windows 10, VS2019, debug build).

**Comment by kimkulling** [comment]
Closed by  https://github.com/assimp/assimp/pull/4170
