### ISSUE TITLE
Assimp header file issue

### ISSUE THREAD

**Issue by Alex533704** [assimp/assimp#3648]
Hello Kim Kulling i have issues with  Assimp.

i'm using mingw32 (gcc 9.2.0)  with codeblocks.
I'm using assimp 5.0.1-4

When i  try to compile my application,i got the same error message multiple times:

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg\mingw32\include/assimp/defs.h:156:28: error: '__forceinline' does not name a type
`

**Due to the big size of the error log, i  decided to  show only  a part of the log:**

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg\mingw32\include/assimp/defs.h:156:28: error: '__forceinline' does not name a type
`

`156 | #   define AI_FORCE_INLINE __forceinline
`

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg\mingw32\include/assimp/vector3.inl:59:1: note: in expansion of macro 'AI_FORCE_INLINE'
`

` 59 | AI_FORCE_INLINE
`

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg\mingw32\include/assimp/defs.h:156:28: error: '__forceinline' does not name a type`

` 156 | #   define AI_FORCE_INLINE __forceinline
`

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg\mingw32\include/assimp/vector3.inl:71:1: note: in expansion of macro 'AI_FORCE_INLINE'`

` 71 | AI_FORCE_INLINE`

`C:\Users\MY_NAME\Documents\mingw-w64-i686-assimp-5.0.1-4-any.pkg 2\mingw32\include/assimp/defs.h:156:28: error: '__forceinline' does not name a type
`

Please Help me;

**Comment by kimkulling** [comment]
Shall be closed by this pull-request: https://github.com/assimp/assimp/pull/3649

**Comment by Alex533704** [comment]
It worked ,thank you.
