### ISSUE TITLE
GLB invisible when animated (apparent extreme scaling applied)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#3655]
.glb model loads/renders OK w/pre-transform-vertices set true
<img src="https://user-images.githubusercontent.com/26958898/108589193-a54a3e80-73a0-11eb-93e1-f4104d15d132.jpg" width=320>
Bounding box diagonal for this case is ~0.906 units

But when loaded w/pre-transform-vertices false and attempting to animate, bounding box extremely large (1e10) and model invisible.  Can anyone confirm this?

Model `Pathfinder_1k.glb` can be downloaded from [here](https://www.cgtrader.com/free-3d-models/character/sci-fi/pathfinder-v20-apex-legends) (free download, registration required)

**Comment by kimkulling** [comment]
Hi,

nice model, but I have one question: Is this related to the viewer or to the assimp-boundingbox generation?

Kim

**Comment by tellypresence** [comment]
Apologies for the confusion, what I'm trying to understand is the radically different dimensions of this particular model observed when loading with `aiProcess_PreTransformVertices` on or off.  With `aiProcess_PreTransformVertices` = 1, bones are effectively removed so animations aren't used; in this case the model renders correctly with measured bounding box diagonal roughly 1 unit.  But when loaded with `aiProcess_PreTransformVertices` = 0, the model is animated using bone deformation but the bounding box diagonal measured at animation frame 0 (i.e. ticks/running time 0) is ~1e10 units.

(One possibility is that one of the meshes becomes detached and is thrown billions of units off to the side, increasing the bounding box size to such an extent that the the actual meshes render as invisible because they're scaled down so much to fit the view); with bounding box displayed the scene just shows the empty (massive) box:
<img src="https://user-images.githubusercontent.com/26958898/108357638-0c48e580-7231-11eb-8d6e-16d959e25007.jpg" width=320>


So far I've only encountered this problem with this particular model, other models (gltf, fbx, dae etc) animate just fine e.g.
![20210218_212217](https://user-images.githubusercontent.com/26958898/108356423-76608b00-722f-11eb-87ca-1aa29b9e8719.gif)

(Just hoping to find out if someone else is able to reproduce this or not -- could very well be my own code, but weird that it doesn't happen more often if that's the case)

**Comment by tellypresence** [comment]
This must be my code.  Just checked bundled model `test/models/X/BCN_Epileptic.X` which exhibits same problem.  Will investigate on my side, sorry again for my confusion and the false alarm
![assimp_issue_3655_Screenshot_20210220-174804_CG Model Viewer](https://user-images.githubusercontent.com/26958898/108590020-b8f7a400-73a4-11eb-909a-f6599ecaea2c.jpg)

**Comment by tellypresence** [comment]
So what was happening was that the animation duration being returned from
```
aiScenePtr_->mAnimations[currentAnimation]->mChannels[0]->mPositionKeys[numPosKeys - 1].mTime;
```
was zero; this was being fed to `fmod()` for looping, and the result was `NAN` which wreaked havoc.  Gracefully handling the `NAN` fixed the problem -- animation is broken but at least the models appear properly.
