### ISSUE TITLE
Trouble building Assimp in Visual Studio from CMake subdirectory

### ISSUE THREAD

**Issue by lizardnoises** [assimp/assimp#3663]
**Describe the bug**
I have Assimp as a git submodule in my project and I'm trying to write a CMakeLists.txt that lets me build Assimp and link it with my application. Assimp builds successfully when I do an out-of-source build in the repo with the Visual Studio 16 2019 generator on Windows 10. However when I add the assimp repo as a subdirectory in CMakeLists.txt, CMake generates the VS project, but the build fails with the following errors.

```
Error   C1083   Cannot open include file: 'draco/draco_features.h': No such file or directory (compiling source file D:\projects\temp\new-meng\vendor\assimp\code\AssetLib\glTF2\glTF2Importer.cpp) assimp  D:\projects\temp\new-meng\vendor\assimp\contrib\draco\src\draco\core\macros.h   19
Error   C1083   Cannot open include file: 'draco/draco_features.h': No such file or directory (compiling source file D:\projects\temp\new-meng\vendor\assimp\code\AssetLib\glTF2\glTF2Exporter.cpp) assimp  D:\projects\temp\new-meng\vendor\assimp\contrib\draco\src\draco\core\macros.h   19
Error   LNK1104 cannot open file '..\..\lib\Debug\assimp-vc142-mtd.lib' assimp_cmd  D:\projects\temp\new-meng\build\vendor\assimp\tools\assimp_cmd\LINK 1
Error   LNK1104 cannot open file '..\lib\Debug\assimp-vc142-mtd.lib'    unit    D:\projects\temp\new-meng\build\vendor\assimp\test\LINK 1
```

**To Reproduce**
1. Create a project repo.

```
mkdir project
cd project
git init
```

2. Add Assimp as a submodule in vendor/assimp

```
git submodule add https://github.com/assimp/assimp.git vendor/assimp
```

3. Add a CMakeLists.txt file to the project with the following contents.

```cmake
cmake_minimum_required(VERSION 3.15)
project(project)

add_subdirectory(vendor/assimp)
```

4. Run CMake for an out-of-source build with the Visual Studio 16 2019 generator.

```
mkdir build
cd build
cmake -G "Visual Studio 16 2019" ..
```

5. Build the Visual Studio solution.
6. See the above errors.

**Expected behavior**
CMake generates a project for my application that includes the assimp target and successfully builds.

**Screenshots**
```
mkdir build
cd build
cmake -G "Visual Studio 16 2019" ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.28.29336.0
-- The CXX compiler identification is MSVC 19.28.29336.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared libraries enabled
-- Looking for ZLIB...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could not locate ZLIB
-- compiling zlib from sources
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Found PythonInterp: C:/Users/bassp/AppData/Local/Programs/Python/Python39/python.exe (found version "3.9.1")
--- Running combined CXX flags test, flags: /W0;/W0
--- Passed combined CXX flags test
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
-- Disabled exporter formats:
-- Configuring done
-- Generating done
-- Build files have been written to: D:/projects/temp/new-meng/build
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - CMake Version: 3.20.0-rc1
 - Assimp commit: 26ebeaea5cb92f841fc5e2da9da379718223e831

**Additional context**

I was able to build successfully by disabling the draco target with
```cmake
set(ASSIMP_BUILD_DRACO OFF CACHE BOOL "..." FORCE )
```

My [post](https://stackoverflow.com/questions/66286971/trouble-building-assimp-in-visual-studio-from-cmake-subdirectory) on StackOverflow.

**Comment by kimkulling** [comment]
Ok, thanks for the information. 

I just started to reproduce the issue with my old compiler in my company. With VS2017 it works. So this seems to be an issue for VS2019.

Kim

**Comment by kimkulling** [comment]
I have added a workaround: at the moment the draco-support is disabled as the default. At this moment I don't have an idea why the error comes up for VCS2019.

I will have to dig deeper. Thanks for your help. I am wondering why this issue ways not detected by our CI-chain.

**Comment by lizardnoises** [comment]
Ok, thanks for taking time to look into it! I have no idea what's going on, but it's interesting that the issue not reproduced with VS2017.

**Comment by RichardTea** [comment]
The problem seems to be that the `draco_features.h` file is being copied to `build/draco/`, but the generated MSVC project expects it to be in `build/vendor/assimp/draco/`

I'm not sure where those two paths come from, the upstream draco cmakelists are rather complex.

The MSVC2017 project doesn't actually build either, the apparent success appears to be an MSVC2017 UI bug.

**Comment by RichardTea** [comment]
Looked into this a bit further. There's a few options to fix this:
1. Add `${CMAKE_BINARY_DIR}` (`build` in your example) to the include path for the assimp projects.
2. Place `draco_features.h` into `build/vendor/assimp/contrib/draco/`
3. Place `draco_features.h` into `build/vendor/assimp/include/assimp/draco/`

Option 1 is simplest as it doesn't require any changes or patches to upstream, however it is polluting the folder tree of the top-level project that's consuming assimp.

I think I prefer option 2, what do you think?

**Comment by lizardnoises** [comment]
Thanks for figuring that out! I think I agree with your thoughts on option 1. It feels like it violates modularization of the library a little bit?  I don't think I have enough experience to suggest a preference between 2 and 3.

**Comment by alexanderbock** [comment]
This bug seems to be back again?

Upgraded our Assimp dependency from v5.4.3 -> v6.0.4
and getting
```
22>A:\openspace\OpenSpace\ext\ghoul\ext\assimp\contrib\draco\src\draco\core\macros.h(20,10): error C1083: Cannot open include file: 'draco/draco_features.h': No such file or directory
22>  (compiling source file '../../../../../../ext/ghoul/ext/assimp/code/AssetLib/glTF2/glTF2Importer.cpp')
```

Visual Studio 2026 (18.5.1).

Not doing anything too weird in our CMakeLists.txt (https://github.com/OpenSpace/Ghoul/blob/master/ext/CMakeLists.txt#L124)
```
  set(ASSIMP_BUILD_SHARED_LIBS OFF)
  set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
  set(ASSIMP_NO_EXPORTER ON CACHE BOOL "")
  set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "")
  set(ASSIMP_BUILD_DRACO ON CACHE BOOL "")
  set(ASSIMP_BUILD_DRACO_STATIC ON CACHE BOOL "")

  if (UNIX)
    set(ASSIMP_BUILD_MINIZIP ON CACHE BOOL "Set to have assimp build minizip" FORCE)
  endif ()

  set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)

  add_subdirectory(assimp)
  target_link_libraries(Ghoul PRIVATE assimp)
  set_target_properties(assimp PROPERTIES FOLDER "External")

  # We need to include this to be able to find the assimp/config.h file
  target_include_directories(assimp PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/ext/assimp/include")
  target_precompile_headers(assimp PRIVATE
    "$<$<COMPILE_LANGUAGE:CXX>:functional>"
    "$<$<COMPILE_LANGUAGE:CXX>:istream>"
    "$<$<COMPILE_LANGUAGE:CXX>:list>"
    "$<$<COMPILE_LANGUAGE:CXX>:locale>"
    "$<$<COMPILE_LANGUAGE:CXX>:map>"
    "$<$<COMPILE_LANGUAGE:CXX>:ostream>"
    "$<$<COMPILE_LANGUAGE:CXX>:set>"
    "$<$<COMPILE_LANGUAGE:CXX>:sstream>"
    "$<$<COMPILE_LANGUAGE:CXX>:vector>"
    "$<$<COMPILE_LANGUAGE:CXX>:tuple>"
    "$<$<COMPILE_LANGUAGE:CXX>:unordered_map>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/DefaultLogger.hpp>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/Exceptional.h>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/mesh.h>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/scene.h>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/StringUtils.h>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/types.h>"
    "$<$<COMPILE_LANGUAGE:CXX>:assimp/XmlParser.h>"
    <string.h>
  )
```

**Comment by alexanderbock** [comment]
Anyone coming across this;  for me it helped to add `${CMAKE_BINARY_DIR}` into the include search path:

```
target_include_directories(assimp PRIVATE "${CMAKE_BINARY_DIR}")
```
