### ISSUE TITLE
ai_assert failure in ArmaturePopulate post-process for simple models with no node hierarchy

### ISSUE THREAD

**Issue by vknauss** [assimp/assimp#3664]
When importing e.g. a .obj file or another simple, non-skeletal model with the aiProcess_PopulateArmatureData flag set, the program will abort on reaching `ai_assert(!node_stack.empty());` in ArmaturePopulate::BuildBoneStack (ArmaturePopulate.cpp : 173) if asserts are enabled. This is caused by ArmaturePopulate::BuildNodeList only outputting nodes with no meshes, so a scene with only nodes that have meshes will always have the node stack be empty. While of course this post-process is meaningless for such a model, it still seems like a bug to immediately throw the program instead of skipping the process and/or letting the calling code know this process can't complete. I fixed this issue locally by inserting `if (bones.empty()) return;` in ArmaturePopulate::Execute between the calls to BuildBoneList and BuildNodeList.

**Comment by kimkulling** [comment]
INdeed, this is wrong. Thanks for your investigations. I have already prepared a PR to fix that issue.

**Comment by kimkulling** [comment]
And merged!
