### ISSUE TITLE
Cannot build with MSYS2 and MinGW-w64

### ISSUE THREAD

**Issue by Picoseconds** [assimp/assimp#3666]
**Describe the bug**
I cannot build assimp using MSYS2 and MinGW-w64 with some errors.

**To Reproduce**
Steps to reproduce the behavior (in MSYS2 terminal):
1. Clone assimp
2. `git checkout 1427e67b54906419e9f83cc8625e2207fbb0fcd5`
3. `CC=/mingw64/bin/clang CXX=/mingw64/bin/clang cmake -G "MSYS Makefiles" .`
4. `CC=/mingw64/bin/clang CXX=/mingw64/bin/clang make`

**Expected behavior**
I expected a binary and successful compilation.

**Screenshots**
```
D:/compile/assimp/code\AssetLib/3DS/3DSHelper.h:325:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma warning(disable : 4315)
```
I get this error repeated a million times even though my C and C++ compiler is clang, .

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1427e67b54906419e9f83cc8625e2207fbb0fcd5 

**Additional context**
I am trying to compile the rust crate "autogenerated-assimp-sys" but I can verify it happens with just cloning that version.

**Comment by RichardTea** [comment]
This was fixed in July 2020, see this commit:
https://github.com/assimp/assimp/issues/3252

**Comment by Picoseconds** [comment]
ok
