### ISSUE TITLE
cannot find assimp-vc140-mt.lib after successful build on mac

### ISSUE THREAD

**Issue by universewill** [assimp/assimp#3668]
I build assimp on mac successfully, but cannot find assimp-vc140-mt.lib in bin folder and other folders

**Comment by kimkulling** [comment]
Hi, you are right. You will not be able to find this library named in this way. The name you have added as a reference is a name for the windows-specific name for lie lib created from VD:

`assimp-<VisualStudio-PlatformVersion>-<MultithreadedVersion>.lib`

Using MacOs the name will be something like libassimp.a

**Comment by universewill** [comment]
Thanks for answering. However,i also dont't find something like  libassimp.a.
This is my bin folder after building:
<img width="181" alt="屏幕快照 2021-02-26 上午11 16 50" src="https://user-images.githubusercontent.com/6790730/109250300-65fa7280-7824-11eb-8498-4ad1f1236df3.png">
