### ISSUE TITLE
API Docs broken ?

### ISSUE THREAD

**Issue by xoSauce** [assimp/assimp#3672]
I tried having a look at the docs on ReadTheDocs and the API section appears to be broken ?
Tried to look at master,latest,v501, v502, also tried to build locally and got the same issue.

It would appear that there needs to be an index.xml in `source/API/index.xml`.
(Unfortunately not familiar with how these docs are generated)

Am I just looking at the wrong thing ?
![api_docs](https://user-images.githubusercontent.com/5675115/109052294-5b7c9380-76d3-11eb-900c-abe317d433d0.png)

**Comment by virtualritz** [comment]
It's been like this for weeks indeed.

**Comment by kimkulling** [comment]
Hi, indeed, this is the case. I started to work on this topic but then I needed to stop and them I completly forgot to restart my work on that. I will open an issue-report in the project and fix that.

Thanks a lot for the reminder.
