### ISSUE TITLE
Compile for Mobile platform(IOS/Android)

### ISSUE THREAD

**Issue by JayChang-zhe** [assimp/assimp#3673]
**Is your feature request related to a problem? Please describe.**
Pretty frustrated when i try to use the library to compile for Android/IOS, i'm not comfortable with makefile etc, it kind plainful when try to compile for mobile

**Describe the solution you'd like**
It will be really friendly  if the teams can offer Android(.so)/IOS(.a or maybe .Framework) when the update the version, cause the environment will also changes, ex: Android, when i try to compile, i need to download Android studio, cmake,  android NDK etc, config all the environment variable, and cause the android studio is actually update a lot, so i can't find a good one to compile the older assimp version (i use 4.0.1 for example), still struggle with that
 
**Describe alternatives you've considered**
Just a suggestion, but i really think it will help all the developer that gonna to use this library on mobile, especially for the guy who not comfortable with make files etc

**Additional context**

**Comment by kimkulling** [comment]
Good point, many people have already asked for this.

**Comment by JayChang-zhe** [comment]
@kimkulling  Sorry to bother you here, i just finish compile the .a file with mac, its actually not difficult compare to .so file , just download cmake & use launch the .sh file, then it generate .a for all the architecture, this is really nice.  

Unfortunately, i just understood i need a .framework file when i try to use this library for IOS with Unreal, that's why i ask the .framework for IOS also.  Could you give me some advance for generate  .framework with this library?  I think it will also help the guys who are going to do same thing  before the team offer those file.  Thanks advance

**Comment by kimkulling** [comment]
Android is available right now: [Assimp for Android](https://kimkulling.itch.io/the-asset-importer-lib)
