### ISSUE TITLE
[Question] Static linking for ASSIMP

### ISSUE THREAD

**Issue by xoSauce** [assimp/assimp#3675]
Hello,

I was trying to get a statically linked version of assimp to slap into my project.
`-DBUILD_SHARED_LIBS=OFF` seems to not be enough to get a fully functional `.a` file.
I had to go hunting for dependencies. Both `IrrXML, zlibstatic` had to be manually accounted for and linked into my project. I am not too fussed with doing this (especially since I am working on a pet project), but I was wondering if this was the desired behaviour for linking statically ? I would have expected both IrrXML and  zlib to be added into assimp. 
Of course, one can always do (I think ?):
```
ar -x libassimp.a
ar -x libzlibstatic.a
ar -x libzIrrXML.a
ar -c libassimpFULL.a  *.o
```
to get a fully packed library, but then that's a rather manual process to be repeated whenever someone wants to update the library.

I built with the following:
`cmake -DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_ZLIB=ON CMakeLists.txt -S . -B build/`

**Comment by kimkulling** [comment]
Hi,

irrXml is deprecated when you are using the version from the latest master. And we currently have a bug with the exported zlib. So that is the reason for the other deviation you mentioned. 

Stay tuned for more happy fixes :-).

Kim

**Comment by aWilson41** [comment]
I'm curious as well as to why zlibstatic is not accounted for in assimp and users have to manually link or write find files for it. Spent a good few hours wondering why ticking BUILD_SHARED_LIBS off suddenly just breaks and dumps a ton of unresolved externals.

Is this a licensing thing? Not compiling zlibstatic into assimp.lib? Is it not feasible for some reason? Or is it just not something anyone has gotten around to yet?
