### ISSUE TITLE
Possible AMF regression

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#3678]
Extracted bundled model archive
    `test/models-nonbsd/AMF/3_bananas.amf.7z`
to
    `test/models-nonbsd/AMF/3_bananas.amf/3_bananas.amf`
but failed to load with message
```
Attribute "Millimeters" in node <unit> has incorrect value.
```
Last year this model at least loaded successfully but rendered with serious artefacts, so not sure if this is a regression or an improvement where now a problematic model is being correctly rejected.

**Comment by kimkulling** [comment]
Could be an xml-mgration issue. I will test it.

**Comment by kimkulling** [comment]
Problem is caused by an upper-/lower-case confusion of the AMF-parsing. I am currently preparing a fix for that.
