### ISSUE TITLE
Assimp build issue

### ISSUE THREAD

**Issue by Alex533704** [assimp/assimp#3679]
Hello Kim Kulling,have issues when building Assimp.
 

I'm using Assimp 5.0.1 with mingw32 (gcc  9.2.0).

During compilation there were 2  errors:

**the first error**:  `C:\Users\MY_NAME\Downloads\assimp-5.0.1\assimp-5.0.1\code\SMD\SMDLoader.cpp:579:12: error: 'strtok_s' was not declared in this scope; did you mean 'strtok_r'?`

After some research,i found out a solution for the first error.
I had to disable the SMD Loader in CMakeLists.txt

During compilation another error appeared:

**second error:**
`In file included from C:\Users\MY_NAME\Downloads\assimp-5.0.1\assimp-5.0.1\code\3MF\D3MFExporter.cpp:61:`
`c:\users\MY_NAME\downloads\assimp-5.0.1\assimp-5.0.1\contrib\zip\src\zip.h:30:15: error: conflicting declaration 'typedef long int ssize_t'`
` 30 | typedef long  ssize_t;  /* byte count or error */`

`In file included from c:\mingw\include\wchar.h:67`
`from c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\cwchar:44`
`from c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\postypes.h:40`
`from c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\iosfwd:40`
`from c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\memory:72`
`from C:\Users\MY_NAME\Downloads\assimp-5.0.1\assimp-5.0.1\code\3MF\D3MFExporter.h:44`
`from C:\Users\MY_NAME\Downloads\assimp-5.0.1\assimp-5.0.1\code\3MF\D3MFExporter.cpp:45`

`c:\mingw\include\sys\types.h:123:20: note: previous declaration as 'typedef _ssize_t ssize_t'`
`123 |   typedef _ssize_t ssize_t;`
`code\CMakeFiles\assimp.dir\build.make:2545: recipe for target 'code/CMakeFiles/assimp.dir/3MF/D3MFExporter.cpp.obj' failed`
`mingw32-make[2]: *** [code/CMakeFiles/assimp.dir/3MF/D3MFExporter.cpp.obj] Error 1`
`CMakeFiles\Makefile2:267: recipe for target 'code/CMakeFiles/assimp.dir/all' failed`
`mingw32-make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2`
`Makefile:147: recipe for target 'all' failed`
`mingw32-make: *** [all] Error 2`

Unfortunately, i don't found any solution for the second  error.
Could you help me?

**Comment by kimkulling** [comment]
The function strtok_s does not exist for gcc, only for VS.- And the preprocessor-directives to use the right function-call are not working in the right way. I guess the solution on our side will be to wrap the calls to strtok_<whatever> and add these into the importers.

As a workaround for you: you can disable the importer to get your build running again.

**Comment by kimkulling** [comment]
I will use this issue to track this one with it: https://github.com/assimp/assimp/issues/3563 .
