### ISSUE TITLE
ASSIMP_DOUBLE_PRECISION does not compile

### ISSUE THREAD

**Issue by Elmi77** [assimp/assimp#3682]
**Describe the bug**
When ASSIMP_DOUBLE_PRECISION is set via cmake, assimp no longer compiles. It causes loads of warnings which are treated as errors. When the option "Treat warnign as error" is turned off in project configuration, there are still loads of (real) errors left, mainly in PugiXML. To sum it up: assimp does not compile.

**To Reproduce**
Environment is VisualStudio 2019, cmake is used to generate project and solution files and option ASSIMP_DOUBLE_PRECISION is set in order to get higher accuracy.

**Expected behavior**
The code should compile with may be a few warnings

**Comment by contriteobserver** [comment]
Building the tip in a Linux environment, warnings are not reported, but the following fails with errors (`cannot bind non-const lvalue reference of type ‘float&’ to an rvalue of type ‘float’`) in `~/assimp/code/AssetLib/Collada/ColladaParser.cpp`:
```
git clone https://github.com/assimp/assimp.git
midir assimp/release
mkdir assimp/release
cd assimp/release
cmake -DASSIMP_DOUBLE_PRECISION=true ..
make all
```

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3683
