### ISSUE TITLE
failed to include ASSIMP/Importer.hpp and ASSIMP/postprocess.h

### ISSUE THREAD

**Issue by kacperks** [assimp/assimp#3686]
**Describe the bug**
failed to include ASSIMP/Importer.hpp and ASSIMP/postprocess.h

[Linux]
error:

Failed to open file assimp/types.hpp (Dependency of "ASSIMP/Importer.hpp")

Failed to open file assimp/config.hpp (Dependency of "ASSIMP/postprocess.h")

**Comment by kimkulling** [comment]
You need to add the include-folder from assimp to your Include path.
