### ISSUE TITLE
Semi-formalize style with automated formatting support

### ISSUE THREAD

**Issue by jdduke** [assimp/assimp#369]
I realize Assimp doesn't have a hard and fast style guide, but it might be nice to formalize some of the existing style patterns in a script/config that can be run by contributors locally to maintain a consistent look and feel.  

I've had a fantastic experience using [clang-format](http://clang.llvm.org/docs/ClangFormat.html) in the past. If we create and host a .clang-format style configuration file, other developers (and or maintainers) could hook into that quite easily (see, for example, the [ClangFormat Sublime Text package](https://sublime.wbond.net/packages/Clang%20Format)). Thoughts?

**Comment by kimkulling** [comment]
Done by CI
