### ISSUE TITLE
thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by matthewswallace** [assimp/assimp#3690]
**the bug**

- On macOS I've built assimp from cmake --build
- cd into port/iOS/
- ./build.sh

I get the following error.

```
[ 92%] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/Assjson/json_exporter.cpp.o

In file included from ~/assimp/code/Pbrt/PbrtExporter.cpp:87:
~/assimp/code/Pbrt/stb_image.h:931:1: error: thread-local storage is not supported for the
      current target
STBI_THREAD_LOCAL
^
~/assimp/code/Pbrt/stb_image.h:592:39: note: expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local
                                      ^
~/assimp/code/Pbrt/stb_image.h:1070:8: error: thread-local storage is not supported for the
      current target
static STBI_THREAD_LOCAL int stbi__vertically_flip_on_load_local, stbi__vertically_flip_on_load_set;
       ^
~/assimp/code/Pbrt/stb_image.h:592:39: note: expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local
                                      ^
~/assimp/code/Pbrt/stb_image.h:1070:8: error: thread-local storage is not supported for the
      current target
~/assimp/code/Pbrt/stb_image.h:592:39: note: expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local
[ 92%] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/Assjson/mesh_splitter.cpp.o
```

**Desktop **
 - OS: macOS 11.2.1
 - M1 mac mini 2021 computer
 - trying to compile for iOS
 
![Screen Shot 2021-03-06 at 3 24 23 PM](https://user-images.githubusercontent.com/123816/110221140-135a2f80-7e90-11eb-811f-1937a9ee4f10.png)

**Comment by RichardTea** [comment]
I'm of the opinion that the STB image loaders shouldn't be in the assimp library at all.

Formats with embedded PNG images should pass the raw image file to the application. If nothing else, PNG contains a lot of metadata that stb_image doesn't support and applications may require.

**Comment by matthewswallace** [comment]
I was able to solve the issue. The  `ports/iOS/build.sh` needed to be updated. 

Line 25 needs to be set to version 10. It was still set to version 6. `MIN_IOS_VERSION="10.0"`

I'll be issuing a pull request.

**Comment by matthewswallace** [comment]
@RichardTea I issued a pull request to fix this issue. Would you mind taking a look and let me know if you can pull that into master?

**Comment by lvalencia** [comment]
Hey I ran into this issue also, it might be helpful if this issue was left open until that PR is merged so someone else looking for a solution to this can find it more easily.
