### ISSUE TITLE
Get mVertexId, mWeight  error from bone 

### ISSUE THREAD

**Issue by walden1** [assimp/assimp#3693]
**Describe the bug**
Read the same Fbx file. I can not get the  aiVertexWeight info(mVertexId, mWeight) from the bone. 
(bone->mNumWeights > 0)
It works correctly when I use version 3.3.1, but this problem occurs when I use version 5.0.1, and the two versions get different duration time.

`
        
        m_importer.SetPropertyBool(AI_CONFIG_IMPORT_FBX_READ_WEIGHTS, true);
        m_scene = m_importer.ReadFile(fullName.c_str(), aiProcessPreset_TargetRealtime_MaxQuality);
        ......
        ......
        aiBone* bone = pMesh->mBones[i];         
        aiVertexWeight* vertWeightPair = bone->mWeights;
        for (uint32_t j = 0 ; j < bone->mNumWeights ; j++)
        {
            uint VertexID = vertWeightPair[j].mVertexId;
            float Weight = vertWeightPair[j].mWeight;
        }
`

**Screenshots**

![image](https://user-images.githubusercontent.com/20278956/110415059-248f8000-80cc-11eb-9d38-74ab8611c7bd.png)

**Desktop (please complete the following information):**
 - OS: mac os 11.2.2
 - xcode

**Comment by walden1** [comment]
sorry guys, i make a mistake.

**Comment by SnapperTT** [comment]
I'm getting the same issue, what was your mistake?

My mesh seems fine (and loads fine on linux), but when I run the same program on windows, aiBone::mWeights and aiBone::mNode are set to garbage values. The other values (mName, mOffsetMatrix, mNumWeights) are correct.

**Comment by SnapperTT** [comment]
I found my error - `ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS` was defined when building but not when compiling my program, resulting in the `aiBone` structure being different. My program compiled fine, but it was reading from the wrong memory location due to this.
