### ISSUE TITLE
Problem when compiling Debug and Release

### ISSUE THREAD

**Issue by mcleary** [assimp/assimp#37]
I found a problem building assimp. Don't know if it is in my machine. 

Steps
1. Run CMake to generate Visual Studio 10 solution
2. Open Visual Studio 10 and build assimp debug target
3. Build assimp release target.

Errors:

assimp\code\3DSLoader.cpp : error C2855: command-line option '/Z7' inconsistent with precompiled header

among others.

Seems assimp is using precompiled headers from one target in another.

**Comment by kimkulling** [comment]
Deprecated.
