### ISSUE TITLE
AMF load problems (crashes, incorrect units, invisible)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#3701]
Rebuilt with latest commit cdd0fea6e833ca082f8d846661738fd391d54a0b

Unfortunately problem reported in https://github.com/assimp/assimp/issues/3678 persists, still get error for model
    `test/models-nonbsd/AMF/3_bananas.amf/3_bananas.amf`
extracted from bundled archive
    `test/models-nonbsd/AMF/3_bananas.amf.7z`
```
Attribute "Millimeters" in node <unit> has incorrect value.
```

Additionally, the following bundled amf models crash on load:
```
test/models/AMF/test2.amf
test/models/AMF/test3.amf
test/models/AMF/test4.amf
test/models/AMF/test5.amf
test/models/AMF/test6.amf
test/models/AMF/test7.amf
test/models/AMF/test8.amf
test/models/AMF/test9.amf
```
(Crashes are catastrophic with no useful error information)

These two bundled models load OK, but appear invisible when rendered:
```
test/models/AMF/test1.amf
test/models/AMF/test_with_mat.amf
```

Also crash when attempting to load simple AMF model available [here](https://www.cgtrader.com/items/2442839/download-page) (same type of catastrophic crash with no useful information)

Can anyone else confirm this?

**Comment by kimkulling** [comment]
Hi,

all these issues were caused by the migration to pugi_xml. I am currently working on a solution. I am using this ticket for tracking: https://github.com/assimp/assimp/issues/3678

Kim

**Comment by tellypresence** [comment]
Followup: after PR https://github.com/assimp/assimp/pull/3736 merged, AMF models referenced above
- "bananas"
- crashing AMFs
- ["building"](https://www.cgtrader.com/items/2442839/download-page)

now load OK
<img src="https://user-images.githubusercontent.com/26958898/113497052-db034b00-953a-11eb-918e-0bf3dc0d9a44.jpg" width=320><img src="https://user-images.githubusercontent.com/26958898/113496903-42b89680-9539-11eb-9747-36656ef48c67.jpg" width=320>

(Something weird with the embedded texture for "bananas" but that's a separate issue)
