### ISSUE TITLE
Loading PLY file generated from SOLIDWORKS

### ISSUE THREAD

**Issue by arkeon7** [assimp/assimp#3711]
**Describe the bug**
The application crash with a bad memory access in the Triangulate process.
The faces index and numbers seems to be misinterpreted in the PLY loader.
The model is correctly loaded in Meshlab, exporting the model from Meshlab and loading the new model in assimp is working.

**To Reproduce**
1. Import the file [https://www.openspace3d.com/rsc/solidworks.ply](url)

**Expected behavior**
Should not crash

**Additional context**
Tested with the current master branch

**Comment by TinyTinni** [comment]
The attached header ends with "\r\n" while the header of "cube_binary.ply" in the test pool ends with "\n".

When you debug the attached ply file, you see that the first byte in the buffer after the header is "\n" and everything is off by 1 byte. While, when you debug "cube_binary.ply", the first byte in the buffer is after "\n".

Somehow, "\n" needs to be skipped, if we are in binary version and the previous char was "\r" in the function `PLY::DOM::ParseHeader`. But I am unsure how to do this save with the streambuffer.
