### ISSUE TITLE
Does Assimp now support to export the model file for V1.5.0 Colloada ?

### ISSUE THREAD

**Issue by ZhangDonglin12** [assimp/assimp#3714]
I am now using the Assimp.Net to transfer the .obj to .dae file. But the version for Colloada is 1.5.0

When I try to import the dae model to Blender , it shows different scalling with the same module file (default obj file and the transfered dae file)

**Comment by kimkulling** [comment]
Hi,

yes, the latest version from the assimp-master does support Collada 1.5.0. I am not sure if this is the case for the latest .Net-release. Normally you shaould be able to check this in the assembly information of the package.

To have the latest version assimp version 5.0.1 must be supported.

Kim
