### ISSUE TITLE
MTL using non-standard using "map_Kn" for normal map when most others use "norm" 

### ISSUE THREAD

**Issue by bhouston** [assimp/assimp#3726]
**Describe the bug**

The Assimp tool set uses map_Kn for normal maps for MTL files.  This is non-"standard."  Of course MTL is super old and there is no longer any "owner" of it, but the convention in the industry, which is used in Three.js, TinyObjLoader, Wikipedia as well as in the Exocortex PBR extensions for OBJ / MTL is to use "norm."

From what I can tell only Assimp uses "map_Kn" and it is leading to fragmentation with regards to OBJ / MTL parsing.  I would suggest Assimp change to preferring "norm."

**To Reproduce**

The code where "map_Kn" is specified is here:
https://github.com/assimp/assimp/blob/1279862e31e56019c5c85afe422f6dab65fc0656/code/AssetLib/Obj/ObjFileMtlImporter.cpp#L64

**Expected behavior**

The term "norm" also makes sense in that it is similar to "bump" and "disp" in naming.  The prefix "map_K" also implies that it is used for a color texture that is used in the lighting equation, when this is actually used for normal modulation.

It should follow the specification in the Wikipedia article, which has been there for many years:
https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering

TinyObjLoader uses the name "norm":
https://github.com/tinyobjloader/tinyobjloader/blob/master/tiny_obj_loader.h#L2180

Three.js also loads from "norm":
https://github.com/mrdoob/three.js/blob/a382159ab8575857bc042d314019bf45edb14117/examples/jsm/loaders/MTLLoader.js#L426

This is also the specification given in the widely referenced OBJ extensions here from 2016:

http://exocortex.com/blog/extending_wavefront_mtl_to_support_pbr

**Screenshots**

N/A

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Additional context**

If you want to be backwards compatible with existing MTL files that Assimp wrote, you could read both of these but only write "norm" going forward.  This would bring everything to the same standard while allow you to be backwards compatible.

**Comment by erich666** [comment]
I agree, this would be a good one to merge on a single standard, and I would prefer "norm" for the reasons listed.

Another problem area is "map_ns" vs. "map_Ns". [Wikipedia](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Texture_maps) capitalizes. [Tiny Obj Loader](https://github.com/tinyobjloader/tinyobjloader/blob/master/tiny_obj_loader.h#L2091) capitalizes. Three.js doesn't support map_ns in the code mentioned, but [uses lowercase](https://github.com/mrdoob/three.js/blob/a382159ab8575857bc042d314019bf45edb14117/examples/jsm/loaders/MTLLoader.js#L450) for "ns". [ASSIMP](https://github.com/assimp/assimp/blob/1279862e31e56019c5c85afe422f6dab65fc0656/code/AssetLib/Obj/ObjFileMtlImporter.cpp#L68) uses lowercase.

I don't care which is right, but it'd be nice to get consensus and stick with it. Any opinions, @bhouston ?

**Comment by kimkulling** [comment]
Fix is in the pipeline.

**Comment by kimkulling** [comment]
Fixed, I hope that helps.

**Comment by bhouston** [comment]
Thank you!  This is amazing.

**Comment by erich666** [comment]
Great, thanks!
