### ISSUE TITLE
Support for Godot MESH and SCN

### ISSUE THREAD

**Issue by nikitalita** [assimp/assimp#3732]
I'm interested in adding in support to convert Godot MESH and SCN files. 

Godot converts imported assets from their native formats (like obj, dae, fbx, etc.) to its own internal formats, which can't be opened in anything other than Godot. 

I'm currently working on a decompiler for Godot (https://github.com/nikitalita/gdsdecomp/tree/4.0-nikitalita), and I am interested in adding functionality to convert the imported assets back to their original formats.

I already have functionality to convert the packed binary files to text format without loading them, and as a result I have the ability to import and manipulate the data structures independent of version or editor context. So, I was thinking of porting that over to assimp and then just converting them to the data structures that assimp expects; I'd have to port it over to `stl`, however, as Godot uses its own internal template library.

However, I'm not quite certain where to begin. The Contributing guide is kinda sparse, but I can kind of suss out that the quality expectations for added features are rather high, as there is very high test coverage and the code is clean and lean. But I do not know what the requirements would be to get a PR for this feature accepted. I also don't really have a grasp on what the starting point is for adding support for additional formats (like, "If you want to add support for a new mesh format, look at X Y Z data structures and look at xxxx.cpp for the starting context"). If you could provide some pointers on this, I'd be grateful.

**Comment by kimkulling** [comment]
You need to start working on a class called Importer which needs to get derived from the BaseImporter class. The override the CanRead, InternReadFile methods.
A normal parsing and importing follow this algorithm:

1. Check if the file is valid for your importer (that's the method CanRead is for)
2. Import the file itself. you can use our file operations for that. If the file is compressed, Assimp supports zip and gzip
3. Start to parse the file. For this, you need to understand the internal structure. Is it XML-based, use the XML-parser. If it is string-based you can use our string-parsing tools. 
4. Transform the parsed data structures into an aiScene-Instance and store all the data you need.
5. Perform post-processing steps on the scene and check if it is fine

**Comment by nikitalita** [comment]
Thanks for the advice! This will really help me out.

> 2. Import the file itself. you can use our file operations for that. If the file is compressed, Assimp supports zip and gzip

This will likely be an issue; later versions of Godot can use zstd for resource compression. Can I add this feature?

**Comment by tellypresence** [comment]
@nikitalita Please re-open when you raise PR

**Comment by nikitalita** [comment]
Yeah, I have no desire to do this.
