### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [assimp/assimp#375]
I would like to point out that identifiers like "[`__AI_LIGHT_H_INC__`](https://github.com/assimp/assimp/blob/ae7aba36479c348cbc755c09f85a9dbff9406481/include/assimp/light.h#L46)" and "[`__AI_METADATA_H_INC__`](https://github.com/assimp/assimp/blob/fe87b092467b32104a146b43a2d93f6e219f0562/include/assimp/metadata.h#L45)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by kimkulling** [comment]
Already fixed. So I will close this issue because it is deprecated.
