### ISSUE TITLE
Question: assimp support for textures from video file formats

### ISSUE THREAD

**Issue by smokhov** [assimp/assimp#3751]
A simple question on (planned? existing?) support for dynamic texture import from various video file formats... is it available or planned to be done in any way? Thanks!

**Comment by RichardTea** [comment]
Already exists, has done forever.

Most 3D formats have a way to specify "files to use". The content of the file is unspecified, it can be a still image, animated GIF, full motion video or in several formats a URI to a supplier of video frames.

So it exists and is out of scope.

**Comment by kimkulling** [comment]
Good to know, thanks for the hint!

**Comment by smokhov** [comment]
Thank you for your replies. I think maybe it's worth it to add this info to the docs / FAQ if in the future such questions come up. :)
