### ISSUE TITLE
convert ply (with uv coordinate) to glb  with no color[i want color instead]

### ISSUE THREAD

**Issue by Yes-Jumby** [assimp/assimp#3759]
**issue 1:convert ply(with uv coordinate) to ply,ply will lose color.
issue 2:convert ply(with uv coordinate) to glb,glb will lose color**

by the way:i download the newest release 5.0.0 and use it

my ply have 2 forms:one with uv coordinate;one with xyzrgb vertex

i have read about issue about ply color,but no one help me:(

here is the model file which have a uv coordanate
[model.zip](https://github.com/assimp/assimp/files/6317296/model.zip)

here is the model file(ply with xyzrgb) which i want to converte to glb(it works well)
[ply_model_aim_toglb.zip](https://github.com/assimp/assimp/files/6323730/ply_model_aim_toglb.zip)

    follow is two ply files head:
==========num1=========
ply
format binary_little_endian 1.0
comment VCGLIB generated
comment TextureFile texture.jpg
element vertex 94880
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float texture_u
property float texture_v
element face 159706
property list uchar int vertex_indices
property list uchar float texcoord
end_header

==========num2=========
ply
format binary_big_endian 1.0
element vertex 2155617
property float x
property float y
property float z
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
element face 4305818
property list uchar int vertex_indices
end_header
========================
tips:head 2 diffuse_red_>red etc,it will work well.

**Comment by JC3** [comment]
If you want to drop the color from the file, you can do that with the postprocessor during or after import by:

1. Setting the importer's `AI_CONFIG_PP_RVC_FLAGS` property to include `aiComponent_COLORS`, then
2. Specifying the `aiProcess_RemoveComponent` flag during import or postprocessing.

For example:

    Assimp::Importer importer;
    importer.SetPropertyInteger(AI_CONFIG_PP_RVC_FLAGS, aiComponent_COLORS);
    const aiScene *scene = importer.ReadFile(filename, aiProcess_RemoveComponent);

This is all described pretty clearly in the docs, at:

- [Importer::ReadFile](http://assimp.sourceforge.net/lib_html/class_assimp_1_1_importer.html#a339882c7acb47d5b5110bbd078d870a9)
- [aiPostProcessSteps](http://assimp.sourceforge.net/lib_html/postprocess_8h.html#a64795260b95f5a4b3f3dc1be4f52e410)
- [AI_CONFIG_PP_RVC_FLAGS](http://assimp.sourceforge.net/lib_html/config_8h.html#afc0a4c00fb90c345eb38fe3f7d7c8637)
- [aiComponent](http://assimp.sourceforge.net/lib_html/config_8h.html#a97ac2ef7a3967402a223f3da2640b2b3)

**Comment by Yes-Jumby** [comment]
> If you want to drop the color from the file, you can do that with the postprocessor during or after import by:

i want to keep color but color lose when i convert ply to ply or glb(but when i convert ply with uv coordanate to obj ,it success)

here is my program:

`//import
    int removeFlags = 0;
    _pImporter->SetPropertyInteger(AI_CONFIG_PP_RVC_FLAGS, removeFlags);
    int processFlags = aiProcess_RemoveComponent | aiProcess_JoinIdenticalVertices | aiProcess_Triangulate | aiProcess_GenUVCoords;
    _pScene = _pImporter->ReadFile(_options.input, processFlags);

    if (!_pScene) {
        cout << "failed to read input file: " + _options.input<< endl;
    }
Assimp::Exporter exporter;
    Assimp::ExportProperties exportProps;
    int exportFlags = 0;

    if (_options.joinVertices) {
        if (_options.verbose) {
            cout << "Join Identical Vertices" << endl;
        }
        exportFlags |= aiProcess_JoinIdenticalVertices;
    }
    exportFlags = aiProcess_GenUVCoords;

    aiReturn result = exporter.Export(_pScene, _options.format,
        outputFilePath, exportFlags, &exportProps);`

**Comment by JC3** [comment]
@Yes-Jumby  I see.

Well, your second PLY file doesn't have vertex colors in it. It has some user-defined custom diffuse colors in it. 

In PLY files, vertex colors are named "red", "green", and "blue", not "diffuse_red", "diffuse_green", and "diffuse_blue". See http://paulbourke.net/dataformats/ply/ for example.

So you can either edit the PLY header to change the component names to standard names ("red", "green", and "blue"), or you can check the export settings in whatever program you used to generate that PLY file to see if you can tell it to use standard property names.

**Comment by Yes-Jumby** [comment]
> @Yes-Jumby I see.
> 
> Well, your second PLY file doesn't have vertex colors in it. It has some user-defined custom diffuse colors in it.
> 
> In PLY files, vertex colors are named "red", "green", and "blue", not "diffuse_red", "diffuse_green", and "diffuse_blue". See http://paulbourke.net/dataformats/ply/ for example.
> 
> So you can either edit the PLY header to change the component names to standard names ("red", "green", and "blue"), or you can check the export settings in whatever program you used to generate that PLY file to see if you can tell it to use standard property names. Depending on the situation, it may also be a good cause for a bug report for whatever program generated that PLY file, as "diffuse_*" properties do not belong in "vertex" elements. :)
> 
> That said, assimp does recognize "diffuse_*" colors, but only as part of material elements, not vertex elements. This is a pretty typical interpretation. So your third option is to add per-vertex materials to your file, but that's probably not what you want.

well ,after i change the head 2 ,it works well .[ply to ply]

but the head 1 still cannot work:([ply to ply]
ply to glb lose color too:(

**Comment by JC3** [comment]
I'm glad you got it working for file 2. I'm confused about what you want for file 1. That file doesn't contain any color information. I see texture info and UV coordinates but I don't see any colors. What are you expecting the output colors to be?

Are you trying to read the texture and assign vertex colors from the (U,V) coordinates in the texture image? If so, you'll have to do that processing yourself in your software, or in the program that produced that file. Textures, materials, vertex colors, (and face colors), are all different things, generally applied when you render the model. If you need to convert a texture or material (or face colors) to vertex colors, that's a special-case operation that you have to do yourself (i.e. load the image file, read the pixels, assign as color components to vertices). 

Is that what you mean?

**Comment by Yes-Jumby** [comment]
> read the texture and assign vertex colors from the (U,V) coordinates in the texture image

yes,this is what i want.In fact,i think vertex colors is same with texture image .because i have a depth .png and a rgb.jpg,they are same size,so there is no need for me to interpolation.thanks very much:)

**Comment by Yes-Jumby** [comment]
> I'm glad you got it working for file 2. I'm confused about what you want for file 1. That file doesn't contain any color 

here is 2 new issue：
issue 1 
[model.zip](https://github.com/assimp/assimp/files/6332878/model.zip)
:
when i converte ply with rgb color in to glb,i see glb is a little strange,i cannot figure out why.
ply display in cloudcompare:
![image](https://user-images.githubusercontent.com/51182133/115174127-42082e80-a0fb-11eb-8f5c-f517d910fd94.png)
glb converted by assimp display in https://modelviewer.dev/editor/
![image](https://user-images.githubusercontent.com/51182133/115174219-71b73680-a0fb-11eb-8e69-dcb669c4e703.png)

issue2: when i use assimp_cmd converte glb to ply,ply will lose color ,and i got ply head like this:
ply
format ascii 1.0
comment Created by Open Asset Import Library - http://assimp.sf.net (v4.1.0)
comment TextureFile *0
element vertex 3273
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 4672
property list uchar int vertex_index
end_header

what is property float s and property float t means? how could i converte a glb to a ply with color using assimp_cmd?

**Comment by JC3** [comment]
You should probably click on the "Discussions" tab and post separate questions for each of your new issues. :)

**Comment by Yes-Jumby** [comment]
> You should probably click on the "Discussions" tab and post separate questions for each of your new issues. :)

sure ,i have done it
