### ISSUE TITLE
C4D: Supporting the latest SDK

### ISSUE THREAD

**Issue by krishty** [assimp/assimp#3761]
Assimp, if built accordingly, uses Maxon’s non-free Melange SDK to import C4D files.

This SDK has been renamed from _Melange_ to _Cineware_. Namespaces and types [have been renamed](https://developers.maxon.net/?p=3533) as well.

Supporting the latest SDK is pretty easy – just replace all occurences of _melange_ with _cineware_ in the source code, and _Melange_ with _Cineware_ in the build scripts. This may, however, break the build for people still using the older Melange SDK.

I think Assimp needs a decision on whether

1. not supporting new SDKs named Cineware,
2. supporting only new Cineware SDKs and dropping Melange SDK support,
3. supporting both.

**Comment by kimkulling** [comment]
Right, for version 5.1 just supporting one C4D-SDK would be the easiest solution I guess. Does anyone depend on the Melange SDK?

**Comment by krishty** [comment]
I’ll contribute the PR for the change to Cineware then. Should I use the master or is there a dedicated 5.1 branch?

**Comment by kimkulling** [comment]
Master is the right one

**Comment by kimkulling** [comment]
Fixed
