### ISSUE TITLE
Premake5 built cannot find config.h

### ISSUE THREAD

**Issue by harshit2608** [assimp/assimp#3762]
I was building assimp with premake5 but the only problem now I have is the `include/assimp/defs.h` at line 55 cannot find 
`#include <assimp/config.h>`
I am using this premake5 [script](https://pastebin.com/ffNue6E5)
![assimp](https://user-images.githubusercontent.com/42277796/115034958-ae134880-9ee9-11eb-8ec3-fb1f94b49fcd.png)

**Comment by kimkulling** [comment]
This will be generated out of the input-file config.h.in. We have a preprocessing step in our CMake-build to generate these files. As a work-around, you can try to copy your own config.h from config.h.in and set your configuration manually. Most of the sutt in the config file is self-explained. 
If you need any help just reopen this issue-report.

**Comment by clerdson** [comment]
My problem too

**Comment by kimkulling** [comment]
There are two possible options to close this issue from my point of view:
- Prepare a premake build script and maintain it in parallel - too much work
- Generate the cmake run with lua and build the rest by using premake ( see https://stackoverflow.com/questions/78929941/how-to-build-and-use-cmake-c-libraries-with-premake )

Or you can use premake to generate the config file by yourself, config.h.in is the input file.
