### ISSUE TITLE
Numerous export -> re-import issues

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3766]
In doing some testing (assimp 5.0.1 64-bit, release build, dynamic linkage, Windows 10 64-bit, MSVC 2019) I've discovered a number of issues particularly centered around exporting models then re-importing them. I'm going to list what I've noticed here. Some of these may be bugs, some may not, some may be user error, some may be known about or fixed in the latest revision.

I apologize for cramming everything into one report, but I just wanted to mention them all in case there is something new here.

Here's the things I noticed:

- `aiGetVersionRevision()` returns 0 instead of 1 for assimp 5.0.1 (so the version is reported as 5.0.0).
- Nothing that the Step exporter wrote was able to be read by the StepFile importer. However, with validation turned off, the importer actually reported success, but the scene was empty. Also the scene flags were 0 despite it being incomplete. With validation on, it failed ("Validation failed: A node of the scenegraph is NULL"). 
- Nothing that the GL Transmission Format 1.0 ASCII exporter wrote (id="gltf") was able to be read by the GLTF importer. All produced the error "class DeadlyImportError: GLTF: Unsupported glTF version: 1.0". Additionally, unlike the other importers, even on failure here the importer did not set its "importerIndex" property. Note that glb, glb2, and gltf2 all seemed OK. Only gltf failed on re-import.
- The x3d importer set the AI_SCENE_FLAGS_ALLOW_SHARED flag in every scene. I don't think this is a problem, just pointing it out because none of the other importers tested set that. 
- Surprisingly, neither assxml nor assjson have a corresponding importer? This seems strange, since they're library-defined formats. Did I miss something? Both lead to "No suitable reader found for the file format of file..." errors on import.
- Nothing that the 3MF exporter wrote was able to be read by the 3MF importer. As with the step files, the importer still reported success with validation turned off and did not set any scene flags, despite the scene containing 0 meshes. With validation on, import failed with "Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there". Additionally, nothing that the 3MF exporter wrote was able to be read by Windows Paint 3D, which supports the format.
- The Blender 3D Importer has a newline in its name. It is the only importer with a newline. It can be problematic in GUIs.

That's the summary. Some notes / suggestions I have on that:

- The functions in version.h should probably return the correct version.
- The Step file importer should fail or at least set AI_SCENE_FLAGS_INCOMPLETE if it can't load any meshes (although really, it should be able to import files that the exporter writes).
- Same for the 3MF importer: It also should fail or at least set the appropriate scene flags if it can't load any meshes.
- The files written by the 3MF exporter couldn't be read in Windows 10's Paint 3D software either. I didn't try any other software, though.
- Even though the "importerIndex" property appears undocumented, and this is a bit of an edge case, for consistency the GLTF importer should probably set it even on failure, since the importer *is* known (GLTF). 
- "Unsupported GLTF Version: 1.0" is an odd error to get for the GLTF 1.0 importer. :) Only seems to affect ASCII format.
- There should be an importer for assxml and assjson, no?
- The newline before the URL in the Blender importer's name should be removed. It might also make sense to move the URL to the comments field instead, like many of the other importers.

---

The test application I wrote (not designed for general consumption, so please file complaints into the 🗑️, lol) can be found [here](https://github.com/JC3/ModelSplit/tree/master/generate_test_models) (it does not actually depend on Qt and should be compilable without it, there's just one source file). The program performs the following operations for every exporter:

- Export a scene with 1 mesh, then re-import it with no pp flags.
- Export a scene with 5 meshes, then re-import it with no pp flags.
- Export a scene with 1 mesh, then re-import it with data validation.
- Export a scene with 5 meshes, then re-import it with data validation.

Each scene has one or more meshes (each mesh is a basic tetrahedron) that have vertex coords, faces, and nothing else. The scene has 1 material, and 1 node. That node also has all of the meshes. It's possible that some of these failed because some required info was missing, in which case, pay no mind to those. 🤷‍♂️

It then generates a report of the import results (importer used, scene flags on import, errors, etc.), as well as a report listing *all* importers associated with a compatible exporter (which is what I was originally testing before I got sidetracked by this).

The report it generates can be found on [Google Sheets](https://docs.google.com/spreadsheets/d/1sTFfHnc7aDZLzDbOZ7TuHCmA29oIWnLbtvBmGq-FmhY/edit?usp=sharing). I'm not going to describe it because I just summarized it above.

I hope this was useful. If I can, I'll do my best to submit some actual patches (also like I said I haven't checked out the latest master yet I'm on the 5.0.1 release, so it's possible a lot of this is moot), but I'm not sure if I'll have a chance to any time soon.

**Comment by JC3** [comment]
ASCII GLTF issue appears solved in a later branch, issue #3639

**Comment by JC3** [comment]
Additional note: Neither the Windows 10 3D Viewer nor Windows 10 Paint 3D was able to open gltf or glb files produced by the version 1 exporters (export format ids "gltf" and "glb"). However, I can't say if this indicates a bug, as GLTF 1.0 support in general is very spotty across the board and it's more likely that it's just a rare format for viewers to support. This is more of an observation than an issue.

**Comment by JC3** [comment]
For reference, here is the set of models that I tried to reimport. These were all written by assimp exporters:

[test_model_data.tar.gz](https://github.com/assimp/assimp/files/6331675/test_model_data.tar.gz)

**Comment by RichardTea** [comment]
Windows 10 Paint3D does not support gltf v1, it's gltf v2 only.

Which version of assimp did you use?
The 5.0.1 release was a very long time ago, there's been a huge amount of change since then.

**Comment by JC3** [comment]
5.0.1. I keep hearing the same thing you just wrote, so what I'm going to
do is get an update and rerun these tests. I kind of figured a lot of this
has been fixed.

What's the latest stable-ish version, or should I just go for the latest on
master?

**Comment by JC3** [comment]
All right. I've updated to the latest master (cd42b99). There are still a number of similar issues, unfortunately; but it's a different set of issues. After I finish compiling a list, I will close *this* issue and create a new one for the updated version.

**Comment by JC3** [comment]
Closing this. I've decided to post the new issues I've encountered as individual issues instead of one big lazy post.

**Comment by JC3** [comment]
Man, that turned into a project. I finally finished going down the rabbit hole of issues highlighted by this test for cd42b99. Just for the sake of closure, here is the new list:

- #3777 [M3DA] Exporter is registered even when M3D_ASCII is not configured.
- #3778 [3DS,GLTF2,GLB2,GLTF,GLB,PBRT] Assertion failures in exporters when aiMesh::mPrimitiveTypes is 0.
- ~~#3780~~ Superseded by;
  - #3803 [GLB] Exporter writes incorrect length headers to files.
  - #3804 [GLB] FR for better error handling in glTF 1.0 importer.
- #3781 [PBRT] Exporter crashes when aiScene::mMetaData is null.
- #3782 [IOSystem] FR for access to error descriptions.
- #3783 [PBRT] Exporter fails due to use of incorrect output path.
- #3786 [X3D] Importer `CanRead` not selective, `ReadFile` doesn't fail; leads to unrecognized file types not causing errors.
- #3791 [STEP] Imports fail due to incorrect selection of importer.
- #3797 [BLENDER] Importer has a newline in its name.
- #3800 [STEP] IFC importer can't load the schema used by the STEP exporter.
- #3807 [GLTF] glTF 1.0 ASCII exporter and importer handle pathnames poorly, with weird consequences.
- #3810 [GLTF/GLTF2] glTF 1.0 / 2.0 ASCII importers parse asset paths incorrectly on POSIX systems.
- #3814 [X3D] Exporter writes malformed files when meshes are unnamed.
- #3815 [X3D] Importer is registered even though it isn't actually implemented.
- #3816 [3MF] Exporter skips root node, writes children, skips grandchildren.

There's still a couple of items to investigate on my todo list but, I finally made it through the main list.

Some of those were also present in the 5.0.1 Bugfix release on the releases page (which were mentioned in my original post here). I tried to give examples of application-side workarounds when possible.
