### ISSUE TITLE
Assimp builds on Windows 8.1 + Visual Studio 2013 fail

### ISSUE THREAD

**Issue by andrew-pa** [assimp/assimp#377]
The DirectX CMake finder doesn't seem to locate the DirectX headers/libs since they [Microsoft] moved them into the Windows SDK.  It's not the biggest deal, since you can just set the right vars to the paths they should be, but it's still broken.
DirectX files went from their own Program Files directory to something like C:\Program Files (x86)\Windows Kits\8.1\... 

Dependency on d3dx9 is also not working on Win8. Also something I can hack around, but should be documented. 

Thanks.

**Comment by kimkulling** [comment]
You can set ASSIMP_BUILD_ASSIMP_TOOLS to off for disabling the viewer option. And of course DirectX 9 is availabble for Windows 8.1 as well.
