### ISSUE TITLE
m3da exporter should not be registered if M3D_ASCII not configured

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3777]
Library version: master @ cd42b995
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

Currently, if M3D_ASCII support is not configured, the "m3da" exporter is still registered, but always fails with the error message "Assimp configured without M3D_ASCII support".

This is an issue because, since the exporter is registered, it will appear when enumerating supported export formats, and therefore will appear as an option in the UI of any client applications, but will always fail if chosen, possibly leading to users filing bug reports with the application developer, or just making the application look sloppy.

If the exporter cannot function without M3D_ASCII support configured, then unless M3D_ASCII support *is* configured, it should not be registered as an exporter, and should not appear in the list of exporters or be available to use.

Suggested fix: Do not register the "m3da" exporter if assimp was not compiled with the necessary configuration to support it.

**Comment by kimkulling** [comment]
Fixed by #3848
