### ISSUE TITLE
IOSystem should provide access to error descriptions

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3782]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

I am not familiar with assimp's internal architecture, so it is possible I am misinterpreting code here, but it does not appear that `IOSystem` provides any way to find out the nature of the error that caused an operation (such as `Open`) to fail.

This makes debugging a bit more difficult in certain situations.

So, if this is the case, then this is a request to propagate IO error details out of `IOSystem` when errors occur.

I was prompted to request this when debugging a vague error I encountered from the PBRT exporter that read "could not open file". I looked at the PBRT code thinking that it was not reporting error details correctly, I saw it called `IOSystem::Open`, but when I looked at `IOSystem`, I couldn't find any error reporting. 

If I misread the code here, please ignore this.

**Comment by kimkulling** [comment]
Normally you can get the last error via the API-Call aiGetErrorString
