### ISSUE TITLE
PBRT exporter can't actually export files; attempts to open wrong pathname

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3783]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

When attempting to export *anything* with the PBRT exporter, it fails with the error message (assume output filename is "path/model.pbrt":

    could not open output .pbrt file: model

Digging into this, at line 159 of PbrtExporter.cpp, I see this:

    std::unique_ptr<IOStream> outfile(mIOSystem->Open(mPath,"wt"));
    if (!outfile) {
        throw DeadlyExportError("could not open output .pbrt file: " + std::string(mFile));
    }
    outfile->Write(mOutput.str().c_str(), mOutput.str().length(), 1);

Finding it odd that it prints an error message about `mFile` but tries to open `mPath`, and seeing that both are parameters to that function (the constructor), I traced that back to line 99 in that same file:

    std::string path = DefaultIOSystem::absolutePath(std::string(pFile));
    std::string file = DefaultIOSystem::completeBaseName(std::string(pFile));

    // initialize the exporter
    PbrtExporter exporter(pScene, pIOSystem, path, file);

Here, `pFile` is the output file. Checking the description of those two IOSystem functions, I see:

    /** @brief get the complete base name of a full filepath
     * example: /tmp/archive.tar.gz -> archive.tar
     */
    static std::string completeBaseName( const std::string &path);

    /** @brief get the path of a full filepath
     * example: /tmp/archive.tar.gz -> /tmp/
     */
    static std::string absolutePath( const std::string &path);

Which means that, if the specified output file is "path/model.pbrt", then, in the PBRT exporter's constructor `mPath` is presumably "path/" and `mFile` is "model" (note: no extension). 

And since it is trying to `Open(mPath)`, that means that the PBRT exporter is attempting to open a directory when it writes the output file, and isn't actually trying to open the correct output path. Therefore, it will always fail.

This seems weird to me, as a bug like this would've made the exporter impossible to run even basic tests on.

In any case:
- It should probably be fixed to open the actual output file.
- The error messages could use a little more specificity (see #3782), and also should print the same name as the one that it attempts to open.

**Comment by JC3** [comment]
As a kludge for testing, I did find that if you want to export a pbrt file named "path/to/scene.pbrt", you can do it by appending a garbage path component to the end of the filename:

    Assimp::Exporter().Export(scene, "pbrt", "path/to/scene.pbrt/jazzhands", 0);

Ends up writing "path/to/scene.pbrt". So, there's that. I guess. 😂

**Comment by lucasc190** [comment]
I'm a little confused - this issue was closed as completed, but as far as I can tell, the bug is still present. I noticed the same thing with issue #3781.

For now, I am working around this bug by appending a slash followed by the name of the file to the path.

Yours sincerely,
Lucas Cardellini

**Comment by lijenicol** [comment]
I'm finding similar problems, just raised the issue again here: https://github.com/assimp/assimp/issues/5842
