### ISSUE TITLE
ReadFile fails to return error when importing unsupported files; also appears to fall back to X3D

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3786]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

When attempting to import a file with an unsupported extension, `Assimp::Importer::ReadFile` succeeds, runs the postprocessor, and returns an empty scene instead of failing. Additionally, the "importerIndex" property shows the index of the X3D importer. I did not attempt to verify if any code in the X3D importer was actually being used.

The expected behavior is for ReadFile to return null, with GetErrorString returning an appropriate error message.

This appears to be a regression. In the 5.0.1 Bugfix release on the releases page, attempting to load unsupported file types indeed caused ReadFile to fail, leaving "importerIndex" unset and GetErrorString returning something like "no importer found for file type" (or something like that).

[This test program](https://github.com/JC3/ModelSplit/tree/assimp-master-cd42b99/specific_tests/x3d_importer_fallback) (Qt not actually needed) demonstrates the issue. For each extension specified, it prints info about library support, and also creates a zero-length dummy file with that extension, attempts to import it, and prints info about the result. The output I'm seeing for extensions "3ds", "assjson" (which has an exporter but no importer), and "qwerty", is:

```
assimp 5.0.1 (master @ cd42b995)

Extension: "3ds"
  IsExtensionSupported:       true
  GetImporterIndex:           3
  GetImporter:                plugin=0x0000012F5897DDC0
  ->GetExtensionList:         3ds prj
  ->GetInfo->mName:           Discreet 3DS Importer
  ->GetInfo->mFileExtensions: 3ds prj
[created zero-length dummy file: dummy.3ds]
  ReadFile (pFlags=0):
    ReadFile:                 error: StreamReader: File is empty or EOF is already reached
    importerIndex:            3
    mName:                    Discreet 3DS Importer
[deleting dummy file]
---------------------------------------------------------------
Extension: "assjson"
  IsExtensionSupported:       false
  GetImporterIndex:           -1
  GetImporter:                plugin=0x0000000000000000
[created zero-length dummy file: dummy.assjson]
  ReadFile (pFlags=0):
    ReadFile:                 success
    importerIndex:            46
    mName:                    Extensible 3D(X3D) Importer
    scene->mFlags:            0x00000000
[deleting dummy file]
---------------------------------------------------------------
Extension: "qwerty"
  IsExtensionSupported:       false
  GetImporterIndex:           -1
  GetImporter:                plugin=0x0000000000000000
[created zero-length dummy file: dummy.qwerty]
  ReadFile (pFlags=0):
    ReadFile:                 success
    importerIndex:            46
    mName:                    Extensible 3D(X3D) Importer
    scene->mFlags:            0x00000000
[deleting dummy file]
---------------------------------------------------------------
```

In all cases, querying for extension support produced correct results, but ReadFile incorrectly succeeded on the unrecognized file types.

Note also that no scene flags are set in the returned scenes. Of course no scenes should be returned, but since they are, I would expect to at least see AI_SCENE_FLAGS_INCOMPLETE.

**Comment by kimkulling** [comment]
Hi,
also related to https://github.com/assimp/assimp/issues/3647. The registration code for X3D is still in. What is missing is the implementation, which is currently under development. 

Kim
