### ISSUE TITLE
Here's some more updated docs.

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3789]
I saw the assimp-docs project, but it seemed to have a bunch of extra prerequisites and I also wasn't really satisfied with the output. Also it seems weird to have it as a separate project and I'm not sure what the Python is all about.

So I just took the Doxyfile from the source tree, tweaked it a bit, and regenerated the HTML (and CHM and QCH) docs real quick. I put the updated Doxyfile and the built docs at https://github.com/JC3/AssimpDocs. See the READMEs there.

If you want to take the Doxyfile from there, replace the one in the doc folder of assimp's source tree, then drop this assimp-docs project, feel free. You can just require doxygen and build the docs back in the lib's source project. Or just ignore this. 

But it's a full, decent looking set of docs if anybody needs it, and there's no extra dependencies or build process beyond running doxygen.

See also https://github.com/assimp/assimp-docs/issues/16.

**Comment by kimkulling** [comment]
Please use the other issue for the discussion. I just want to bundle all your opinions at one place. And thats a lot for starting the discussion! :-)
