### ISSUE TITLE
aiQuaternion constructor from XYZ rotation parameter names are incorrect (and misdocumented)

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3790]
In *quaternion.h* (and therefore in documentation):

    /** Construct from euler angles */
    aiQuaterniont( TReal rotx, TReal roty, TReal rotz);

But, in *quaternion.inl*:

    // Construction from euler angles
    template<typename TReal>
    inline aiQuaterniont<TReal>::aiQuaterniont( TReal fPitch, TReal fYaw, TReal fRoll )

Since RPY corresponds to XYZ, this means, that the *actual* parameter order for the constructor is:

    aiQuaterniont(Y, Z, X)

But the header parameter names and docs make it appear to be *(X, Y, Z)*, which, in my case, lead me down a stupidly long path of debugging why my math wasn't working out, and a huge waste of time before realizing what happened.

The best solution is probably to change both to:

    aiQuaterniont( TReal roty, TReal rotz, TReal rotx);

Even though it'd still be an odd ordering (yzx, when it's xyz everywhere else), at least it'd correctly reflect what the constructor is expecting. While the ideal solution might be to change the parameter order, I'd be afraid of breaking existing code of other people who also noticed that issue. (Although it does kind of make you wonder what other subtle bugs are out in the wild now where the named parameters were assumed to be correct...)

This seems like a careless mistake to have made...

As a side note, "pitch, yaw, roll" is a rather unconventional ordering as well...

---

To be clear; the TLDR here is if anybody runs into issues with:

    aiQuaternion rotation(x, y, z);

Disregard the parameter names you saw in the docs and header, and change it to this to get correct results:

    aiQuaternion rotation(y, z, x);

**Comment by JC3** [comment]
An example of some code that behaves unexpectedly when following the parameter names / docs, and was not fun to debug:
```
static aiMatrix4x4 fromEuler (const aiVector3D &scale, const aiVector3D &rotateEuler, const aiVector3D &translate) {

#if 0
    // this isn't producing correct results?
    aiQuaternion rotate(rotateEuler.x, rotateEuler.y, rotateEuler.z);
    return aiMatrix4x4(scale, rotate, translate);
#else
    // temporary until i figure out what's going on above
    aiMatrix4x4 m_scale, m_rotate, m_translate;
    aiMatrix4x4::Scaling(scale, m_scale);
    m_rotate = aiMatrix4x4().FromEulerAnglesXYZ(rotateEuler);  // api is a bit inconsistent
    aiMatrix4x4::Translation(translate, m_translate);
    return m_translate * m_rotate * m_scale;
#endif

}
```

**Comment by kimkulling** [comment]
Good catch, I have prepared a PR to fix this one.
