### ISSUE TITLE
Blender importer has a newline in its name

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3797]
Library version: master @ cd42b99 (also present in 5.0.1 Bugfix release)
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

The name reported for the Blender importer has a newline in it. It is the only importer whose name contains a newline. The newline should be removed as it causes problems in certain [G]UIs.

Example:
```
cout << '"' << aiGetImporterDesc("blend")->mName << '"' << endl;
```

Outputs
```
"Blender 3D Importer
http://www.blender3d.org"
```

**Comment by krishty** [comment]
This is also annoying when you just want to log an exporter’s name and suddenly have a two-line log message.

**Comment by JC3** [comment]
I've submitted a PR for this in #3822, as an immediate solution while I consider #3799.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3822
