### ISSUE TITLE
Does it make sense to add a web site field to importer descriptions?

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3799]
A lot of the importers have associated websites, stored in the comment field. However, the comment field is also used for other general comments (see e.g. #3798). 

I feel like enough importers have websites that it justifies the addition of an `mWebsite` (or `mWebSite` or `mURL`?) field to `aiImporterDesc`. 

The added benefit of this is, by having a dedicated field for a website, programs now have the option of presenting the sites with special handling in their [G]UIs, or of displaying the sites without also displaying comments such as "See documentation in source code" (X3D) in their UIs.

Any thoughts? If this is a good idea I don't mind making the PR.

[Here is a Google Sheet with the current values of all the description fields for all the importers](https://docs.google.com/spreadsheets/d/1vzSUiDo-pBvB1g4D9mQ-6Px7tHXhe8y5wtBzGkL0oZI/edit?usp=sharing), as a quick reference.

There are currently 48 importers total, of which 13 have a website somewhere in their description (11 in comment field, 2 elsewhere).

**Comment by kimkulling** [comment]
Hi, 
from my point of view, this makes completely sense.

**Comment by JC3** [comment]
@kimkulling Ok; I'll submit a PR with proposed changes later. For now, I've closed #3798, since I'll just incorporate it into this patch.

**Comment by JC3** [comment]
Adding a member to the end of `aiImporterDesc` will break binary compatibility, since this builds as a shared lib. There are solutions (a couple options, actually), but I don't want to complicate things unnecessarily.

Should I care?

**Comment by JC3** [comment]
I want to double-check about binary compatibility issues. I was going to add a field to the end of `aiImporterDesc`. Two questions:

1. Is there any code in the library that *copies* data from internal `aiImporterDesc`s to application-side `aiImporterDesc`s, or is it all just passing pointer around?
2. If I add a member to the end, it could lead to issues if an application linked against this version tries to access the member in a struct returned by an older version of the lib. Do we care about keeping new apps compatible with old versions of the shared lib?

There are solutions (a couple options actually) but I don't want to complicate things if I shouldn't care.

**Comment by JC3** [comment]
I've gone ahead and re-submitted a PR (#3797) for the Blender importer name while I consider what to do about the website field.

**Comment by JC3** [comment]
Man, I thought cross-referencing issue numbers would help stay organized, but mostly I'm just confusing the hell out of myself...

**Comment by RichardTea** [comment]
Binary compatibility with the 5.0.1 release has already been broken by some of the recently merged PRs - for example PR #3859 changed the size and layout of aiMesh.

5.1.0 is a reasonable time to break binary compatibility anyway.
