### ISSUE TITLE
3DS Regression: Transformation is broken

### ISSUE THREAD

**Issue by krishty** [assimp/assimp#3802]
https://github.com/assimp/assimp/pull/3724 changed the relative transformation during 3DS import. For me, this broke several files. I can only fix them by reverting the change.

Sample file:
[19127_Robot_Parallel_Manipulatar.zip](https://github.com/assimp/assimp/files/6368651/19127_Robot_Parallel_Manipulatar.zip)

Screenshot before:
![before](https://user-images.githubusercontent.com/51880096/115940375-a3d0eb80-a4a1-11eb-9d7c-15f1e846b174.png)
after:
![after](https://user-images.githubusercontent.com/51880096/115940379-a7647280-a4a1-11eb-9e36-3cf7522b651a.png)

I have more files that show this regression, though some are under NDA. No file improved, I only see regressions.

The changelog says this change happened “in alignment with 3DS exporter”, which I presume means [this change](https://github.com/assimp/assimp/pull/3722/).

Since this aligned import and export, I fear that both are wrong now.

**Comment by Garux** [comment]
That change fixes the case i'v got
![unknown (11)](https://user-images.githubusercontent.com/1734117/116275097-f48b6180-a78b-11eb-863a-5fe192dca78c.png)
(smaller view is after the change)
But i haven't look what's actually going there, possibly wrong looking one is correct 🥨

**Comment by Garux** [comment]
Ok, if i add aiProcess_PreTransformVertices:
![image](https://user-images.githubusercontent.com/1734117/116276856-9790ab00-a78d-11eb-9e49-78a2dedb73c6.png)
(and it's also laying on the side...)
And with the change undone:
![image](https://user-images.githubusercontent.com/1734117/116277891-98760c80-a78e-11eb-845f-fa33b81a6553.png)
(also on the side, but this seems to be *alright*)

**Comment by krishty** [comment]
Thanks a lot for the testing! 👍 

Do I understand correctly:

1. change on, PreTransformVertices on: **wrong** (your 2nd pic)
2. change on, PreTransformVertices off: **OK** (1st pic, small)
3. change undone, PreTransformVertices on: **OK** (your 3rd pic)
4. change undone, PreTransformVertices off: **wrong** (1st pic, large)

Did you export the 3ds from Assimp to Blender? In this case keep in mind that the exporter may be broken, because “fixing” it is what broke the import int he first place.

I think the source code of the Blender 3ds plugin can be found at https://github.com/blender/blender-addons-contrib/blob/master/io_scene_3ds/import_3ds.py#L831 and line 831 is the matrix we’re talking about. They’re building it from elements 0–3, 3–6, 6–9, and 9–12. Before the change, Assimp did the same; after it, it’s 0–3, 10, 3–6, 11, 6–9, 12. This can’t be right.

I’ll submit a pull request to revert that. Someone needs to work out the black magic that makes the exporter work differently, though.

**Comment by Garux** [comment]
You understand it right.
My general mistake was ignoring node transforms, so when i consider them by using `PreTransformVertices`, introduced problem becomes clear.

**Comment by krishty** [comment]
@Garux , thank you very much for helping out with this one. I created a pull request to revert the change and repair the transformation on import: https://github.com/assimp/assimp/pull/3826

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3826 .
