### ISSUE TITLE
X3D exporter writes malformed files (duplicate DEF names) when mesh name is empty

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3814]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

The X3D spec defines the scope of a USE/DEF node name as the entire subtree of the node that the DEF appeared in, and requires names to be unique in that scope ([ref](https://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/concepts.html#DEFL_USESemantics)). Meaning: If a node is named with DEF, none of its children (recursively) may have the same name, i.e. a node can't have the same name as any of its ancestors.

The X3D exporter appears to use aiMesh::mName as a prefix for the node name in Shape nodes. 

When the mesh name is empty, it produces Shape nodes such as:

```
<Shape DEF='_IDX_0'>
    <Appearance DEF='_IDX_0'>
        ...
    </Appearance>
    ...
</Shape>
```

There, the Appearance node name "_IDX_0" conflicts with the Shape node name, which is forbidden.

The X3D exporter needs to use a different strategy to ensure uniqueness of node names. It should probably also be reviewed for other instances of this same issue. I only tested with very minimal scene data.

For reference, btw, X3D files can be validated at https://savage.nps.edu/X3dValidator/.

**Comment by kimkulling** [comment]
Same here, related to https://github.com/assimp/assimp/issues/3647

**Comment by JC3** [comment]
> Same here, related to #3647

Just to be sure: This is definitely related? Just double checking, because the X3D *exporter* actually seems to work OK otherwise (although I didn't do any extensive testing).

Are you just sort of reworking all of the X3D stuff together?
