### ISSUE TITLE
X3D importer does not work at all; implementation appears to have been removed (Regression). Should not be exposed as an available importer.

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3815]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

The X3D importer fails to import all files. Furthermore, it never reports any errors. On closer inspection, the whole importer appears to be mostly unimplemented placeholder code ([source](https://github.com/assimp/assimp/blob/21d7085be6b7a3c6912ce33d9931688dc1a4a6dc/code/AssetLib/X3D/X3DImporter.cpp)). 

This appears to be a regression. As far as I can tell, the X3D importer works fine in the 5.0.1 release on the releases page.

In any case, if it's no longer implemented for some reason, it shouldn't be returned in the enumeration of available importers. Also, if it *is* going to be included, it should probably return a failure status and an error message.

This also explains why `ReadFile` doesn't fail in #3786.

Suggested fix: Do not register the X3D importer until it is reimplemented.

**Comment by krishty** [comment]
Yes, this was the commit: https://github.com/assimp/assimp/commit/7e93ae4428c522dabc0778f68fd7705e034344b8#diff-2acebea8f998d4ca7f437b25c3df9481a5587529b01a0f0cf01eb25323c96bc0

**Comment by JC3** [comment]
> Yes, this was the commit: [7e93ae4](https://github.com/assimp/assimp/commit/7e93ae4428c522dabc0778f68fd7705e034344b8)

Incidentally, the 3MF importer can't load files that the 3MF exporter produces; also spits out empty scenes without returning an error. But I didn't do any digging into it yet. If it's an importer issue, I wonder if it's related to that same commit... 🤔

**Comment by krishty** [comment]
From my understanding, the root cause is https://github.com/assimp/assimp/issues/2965
- irrXML is too vulnerable, so Assimp was ported to pugixml.
- Since all XML-based importers used irrXML directly, this required the introduction of an abstraction layer.
- @kimkulling ported all importers to the new XML interface, but it seems that X3D was either forgotten or deleted by accident.
- Since the XML interface changed drastically, you cannot just restore the old X3D code; a genuine port to the new interfaces is required.

**Comment by JC3** [comment]
> It is well possible that the 3MF problems were also introduced while porting to the new XML interface. You could try checking out the previous version.

As it turns out, the 3MF importer seems fine. The 3MF exporter is the culprit on that one. The issue has also been present at least back through the 5.0.1 Bugfix release on the releases page. See #3816.

**Comment by kimkulling** [comment]
Hi,

please check https://github.com/assimp/assimp/issues/3647 . As @krishty has mentioned the old importer was removed by the port to pugixml. I migrated to this to fix a lot of security issues caused by the irrXml parser. 

Kim
