### ISSUE TITLE
aiProcess_PreTransformVertices does not behave as documented

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3820]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

The `aiProcess_PreTransformVertices` documentation states (emphasis mine):

> The output scene still contains nodes, however there is only **a root node with children, each one referencing only one mesh,** and each mesh referencing one material.

However, in reality, the flag only behaves this way if more than one material or transform is present (or something like that -- basically, if it's got more than one mesh after processing), or the scene has lights and / or cameras. If only a single material is present and there are no lights and no cameras, the postprocessor does *not* add a child node to the root for it -- instead, it puts the mesh directly in the root node:

https://github.com/assimp/assimp/blob/21d7085be6b7a3c6912ce33d9931688dc1a4a6dc/code/PostProcessing/PretransformVertices.cpp#L611-L617

This difference is significant for edge-ish cases like #3816 (where scenes imported with one material, no cameras, no lights, [e.g. most basic scenes or scenes with components removed on import] and `aiProcess_PreTransformVertices` set can't be exported to 3MF without applying the workaround there).

I don't know if this should be considered a documentation error, or an implementation error. However, while there is something to be said for having the implementation output a 100% consistent structure regardless of the material count, I'm going to think of it as a documentation error, because doing extra work sucks 😁. 

I'll submit a correction in a moment.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3821
