### ISSUE TITLE
ai_rgba2hex and ai_decimal_to_hexa are broken + 3MF exporter passes incorrect values to them anyways, writes broken materials to 3MF files.

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3830]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

This is a collection of a few issues because every time I went to get a link to the code that a bug was in, I saw another bug... 😅

Firstly, `ai_rgba2hex` is broken:

https://github.com/assimp/assimp/blob/456af8c493761be20f4f64a3d9aa497b41a518a6/include/assimp/StringUtils.h#L175-L183

It fails to pad the hex string with leading 0's, leading to incorrect results (e.g. `ai_rgba2hex(0, 0, 0, 255, false)` will just return "ff", but should return "000000ff").

Fortunately, that function is only used by the 3MF exporter. Unfortunately, the 3MF exporter contains another error which compounds the issue:

https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/code/AssetLib/3MF/D3MFExporter.cpp#L249-L258

Here, the expressions for calculating the color components have two issues:

1. `(int)((ai_real)color.r) * 255` needs to be `(int)(color.r * 255.0)` (+ 0.5 if you want to round it, or just use `std::lround`)... 
2. Also, the values aren't clamped (there is no protection against negative values, and the `if` theoretically protects the upper bound although...).

Also, `ai_decimal_to_hexa` is broken:

https://github.com/assimp/assimp/blob/456af8c493761be20f4f64a3d9aa497b41a518a6/include/assimp/StringUtils.h#L152-L164

It is templated to accept any type. However, `std::hex` only applies to integer types and has no effect on floating-point types. Also, even if you *do* pass it an integer type, it has the same leading 0 problem as above. This function is also only used by the 3MF exporter, but the exporter passes `ai_real`s to it, so...

https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/code/AssetLib/3MF/D3MFExporter.cpp#L258-L268

In that code snippet, no numbers would be converted to hexadecimal.

Also, the general logic in the 3MF exporter there is mysterious and buggy:

https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/code/AssetLib/3MF/D3MFExporter.cpp#L249-L268

It appears to be attempting to determine if the diffuse color has the range [0.0, 1.0] vs. [0, 255], so that it can scale to 255 in the former case. Issues here are:

1. It doesn't work reliably: (0, 0, 0, 1) is a perfectly valid color in both ranges, so there's no way to know which range was intended. However it's a significantly different color depending on the interpretation (almost completely transparent black vs. completely opaque black).
2. It seems weird that it needs to do this at all: The docs for `aiColor4t` state that the library uses color components in the [0.0, 1.0] range, so the `} else {` branch shouldn't be happening. Why is this logic here?

My suggestion:

- Just ditch `ai_rgba2hex` and `ai_decimal_to_hexa`. Neither of them work and only the 3MF exporter uses them, anyways. I have a hunch it won't break any application code, either -- if any app devs ever used either of those they most likely immediately noticed the issues and, if they didn't, well... this would be doing them a favor.
- Get rid of the range detection logic in the 3MF exporter. Assimp colors are supposed to be in [0.0, 1.0]. If a [0, 255] color is encountered, that's a bug that should be fixed at its source.
- Use the appropriate formatters from `iomanip`, or just go the easy route with `printf`. All three of these are equivalent (`uint8_t r, g, b, a`):

        // stringstream ss; string outstring; 
        ss << hex << setfill('0') << setw(8) << (r << 24 | g << 16 | b << 8 | a);
        ss >> outstring;
 
        // stringstream ss; string outstring;
        ss << hex << setfill('0') << setw(2) << r << setw(2) << g << setw(2) << b << setw(2) << a;
        ss >> outstring;

        // string outstring;
        char buf[9];
        snprintf(buf, sizeof(buf), "%02x%02x%02x%02x", r, g, b, a); // <- or capital X's
        outstring = buf;

The final issue here is more abstract: I don't think assimp's unit tests have adequate coverage.

I do not know if any of this is present at the `v5.0.1` tag, I didn't check. It could be.

---

## Consequences

Here is one example of a weird consequence of this:

If you import a file (any format) that has no materials, it will have the default material assigned, where diffuse is (0.6, 0.6, 0.6, 1.0).

If you then export that to a 3MF, the above issues ultimately write the diffuse color as `ai_rgba2hex(0, 0, 0, 255)` (because of the multiplication errors) when then gets written out as just "#ff" (because of the missing leading 0's). This confuses every program that reads it because it's an invalid color (Paint 3D, for example, displays the model as completely transparent except for a shadow).

If you then *import* that with assimp, the 3MF importer (correctly) fails to parse the color. However, it has already created the `aiMaterial`, so it just leaves it with no diffuse color ([source](https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/code/AssetLib/3MF/D3MFImporter.cpp#L485-L525)), but the postprocessor also doesn't add the default material (since the empty material is present).

Now, if you export *that* to a 3MF, the 3MF exporter, when encountering the material with no diffuse component, defaults to just writing "#FFFFFFFF" ([source](https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/code/AssetLib/3MF/D3MFExporter.cpp#L245-L271)).

At that point, you can import + export and it'll stay white.

This isn't actually an uncommon case. It's not unusual for an imported file to not have a material. Additionally, and unfortunately, it also seems to be not unusual for any given assimp importer to just ignore materials in the files due to some bug or another. So you get lots of scenes without materials. Then, that first time you export them to 3MF, they end up with the malformed "#ff" base material color. If you happen to load your exported file with assimp again later then export that again, it'll end up white.

Here is a visual example of the weirdness, as viewed by Paint 3D. The left image is "box.3mf" from the 3MF example model collection. The next image is the result of importing box.3mf then exporting it to a 3MF with assimp. The last image is the result of doing that again:

![image](https://user-images.githubusercontent.com/5651184/116349292-a8f1ab80-a7bd-11eb-8aea-2943ccf4f42f.png)

This is actually the issue that I was initially investigating when I found the rest of this... it was a little bit of an adventure.

**Comment by JC3** [comment]
There is a test program [here](https://github.com/JC3/ModelSplit/tree/assimp-master-cd42b99/specific_tests/suspicious_3mf_materials). Info and example output is in the readme. 

It doesn't do anything with the StringUtils stuff, though, it was initial testing when I was investigating the 3MF texture behavior.

It's not very interesting, but if it's useful then 🎉.

**Comment by kimkulling** [comment]
Thanks for the report and the great investigation.

**Comment by kimkulling** [comment]
Fix is on its way.
