### ISSUE TITLE
obj file has no material ，but aiScene read material

### ISSUE THREAD

**Issue by kingui1106** [assimp/assimp#3835]
**Describe the bug**
I use assimp_cmd read a obj info. I use the next command
> info a.obj
But aiScene has NumMaterial.

**To Reproduce**
It is my obj file
> v  -0.2583 -4.2958 4.0252
v  0.3480 -3.9487 3.7600
v  0.2024 -3.6995 4.1700
g sdsd
f 1 2 3

**Screenshots**
![image](https://user-images.githubusercontent.com/21022679/116492154-2573af80-a8ce-11eb-822c-aedc4ae00e61.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Version[ 5.0.1 release ]

**Comment by JC3** [comment]
#3832

**Comment by kingui1106** [comment]
thanks very mush. I didn't find this issue just now. I thought I didn't submit it yesterday,  so i add a new. I'm sorry
