### ISSUE TITLE
Loading dae 1.4 file produces wrong number of vertices

### ISSUE THREAD

**Issue by beckylum0216** [assimp/assimp#3854]
**Assimp importing collada/dae issue**
Assimp importer is giving me the wrong mnumvertices, auditing the number or records received through the scene struct, I have been getting the equivalent uv vertices. I am not quite sure if this is the expected behaviour of the library? The library is being compiled from source as a submodule in the application.

**To Reproduce**
1. Flags set with 
```
int flag_00 = aiProcess_Triangulate | aiProcess_JoinIdenticalVertices |
                     aiProcess_ValidateDataStructure | aiProcess_SortByPType |
                     aiProcess_FindInstances;
```
2.  the importer function call

``` 
auto scene = importer.ReadFile(path.c_str(), flag_00);
if(!scene){
    Log::Instance()->Debug("Loader", "Assimp error: " + std::string(importer.GetErrorString()));
}
```
**Expected behavior**
In the collada file I am expecting 6630 individual elements or 4240 triangle elements and 2580 uv elements. However, the stacktrace after import is 2580 elements.

**Screenshots**
![Screenshot 2021-05-03 220522](https://user-images.githubusercontent.com/11342938/116886917-40db1380-ac5c-11eb-86da-cefdb1436531.png)

![Screenshot 2021-05-03 201237](https://user-images.githubusercontent.com/11342938/116886946-489ab800-ac5c-11eb-9bfc-a4334cbe05a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - msvc 16
 - C++ standard 14

**Comment by Garux** [comment]
Looks alright for me; header declares 2210 verts; some verts are reused with varying UVs, thus 2580 unique verts after the `aiProcess_JoinIdenticalVertices`

**Comment by beckylum0216** [comment]
@Garux 

Applying the vertices with the imported faces gives me this strange blob. I have rendered this particular model on an older version of assimp and it does not give me the same result? Am I missing something?

Thanks.

![Screenshot 2021-05-05 164239](https://user-images.githubusercontent.com/11342938/117117578-4bafb880-adc2-11eb-84bc-ef99c19b48ff.png)

**Comment by Garux** [comment]
Hard to judge with the given amount of data. Does assimp_view display the model properly?

**Comment by beckylum0216** [comment]
Closing this issue, possible incorrect usage. Please update documentation.

**Comment by kkulling** [comment]
Thanks a lot for your update. Which documentation is special? It would be really great to get a hint where you were misled by our doc.  Thanks a lot in advance!

Kim
