### ISSUE TITLE
aiProcess_GenBoundingBox  Flag does not have any documentation

### ISSUE THREAD

**Issue by LouisNoailles** [assimp/assimp#3870]
The flag aiProcess_GenBoundingBox is in the code but does not appear anywhere in the documentation and seems to do nothing when activated. Did I miss something or is it a deprecated feature still roaming in code?

**Expected behavior**
I would say it should create some sort of data structure

**Desktop :**
 - OS: Ubuntu
 - Version latest

**Comment by DFYX233** [comment]
yesh,But you can press F12 to see the source code,mAABB struct in aiMesh object
