### ISSUE TITLE
Unity plugin doesn't exist on the Asset Store

### ISSUE THREAD

**Issue by aapatre** [assimp/assimp#3872]
Is the Unity plugin still available? Cause the following link in readme redirects to the Asset Store homepage:
[https://www.assetstore.unity3d.com/en/#!/content/91777](https://www.assetstore.unity3d.com/en/#!/content/91777)

**Comment by kimkulling** [comment]
Please check https://github.com/assimp/assimp/pull/3939

**Comment by kimkulling** [comment]
Ricardo has updated his trilib to version 2.0: https://ricardoreis.net/

**Comment by kimkulling** [comment]
So, the link is fixed right now. Thanks for the report.
