### ISSUE TITLE
3MF regression

### ISSUE THREAD

**Issue by krishty** [assimp/assimp#3879]
@kimkulling because I don’t know if github notifies you of review comments

Commit https://github.com/assimp/assimp/commit/ff1835499737b5a14126503dc8988ee7940ce0c8 introduced two false string comparisons; see my comments there for fixes.

Strangely, the unit tests didn’t fire, but I just checked it in the debugger and `"base" == "base"` was no longer true. It’s definitely broken.

**Comment by kimkulling** [comment]
Ok, thanks for the hint. Got it!
