### ISSUE TITLE
Something keeps writing "dna.txt"

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3886]
Something in assimp keeps writing a file named "dna.txt". I *think* it's the Blender importer.

It should not be doing this. Will investigate.

Example: [dna.txt](https://github.com/assimp/assimp/files/6427961/dna.txt)

**Comment by JC3** [comment]
Ok, so; dna.txt is created only in assimp debug builds, when ASSIMP_BUILD_DEBUG is defined; via:

https://github.com/assimp/assimp/blob/1e89c06157e33459a478e9cbf56863936a004ef5/code/AssetLib/Blender/BlenderDNA.h#L58-L60

Then:

https://github.com/assimp/assimp/blob/1e89c06157e33459a478e9cbf56863936a004ef5/code/AssetLib/Blender/BlenderDNA.h#L498-L503

Etc.

I don't know what to do about it, if anything, because:

- It's only in debug builds; that seems reasonable, but also...
- I don't want it to be generated, but also...
- I assume other people *do* want it.
- Any precompiler-based solution would have to involve setting build flags when building (because the dumping logic is in compiled source), but I don't know enough about cmake or the build system here to implement that.
- Any precompiler-based solution that can be done on the *application* build level would involve kludgy stuff, like throwing this in a header:

        #ifndef ASSIMP_BUILD_BLENDER_DEBUG_DNA
        #  define ASSIMP_BUILD_BLENDER_DEBUG_DNA 1
        #endif

        class DNA {
            ...
            static bool IsDNADumpEnabled () {
                return (0 != ASSIMP_BUILD_BLENDER_DEBUG_DNA); 
            }
            ...
         }

    And checking `IsDNADumpEnabled()` in source. Except [I'm not actually sure if this would work](https://stackoverflow.com/questions/67404388/do-i-need-to-prevent-optimizations-here). 
- Any runtime code-based solution would involve picking a default, and applications wishing to change that would have to call some Blender-specific function, which feels awkward -- unless assimp has a sort of global options concept? I suppose it could be an importer property? 
- An env var based approach is fine with me but given that I just hacked in #3834, I'm a little wary to continue that pattern. Ya know, slippery slope and all.

Or, I could just deal with the file being always written, and do nothing here. 

Or it could be the case that nobody cares about this file any more and so it can be disabled by default or always.

Any thoughts?

**Comment by krishty** [comment]
`DumpToFile();` looks like a code path you’d selectively enable during very specific debugging, but you’d never push that call into the official repo. Should be `#if 0` and whoever needs it, must enable it.

my 5 ct

**Comment by JC3** [comment]
I think so, too.

#3891, maybe? It's a little bit of a tread-lightly approach. I dunno.

**Comment by krishty** [comment]
That’s alright to me!

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/3891
