### ISSUE TITLE
Bad Allocation on large .obj-files

### ISSUE THREAD

**Issue by fkorak** [assimp/assimp#389]
Hello,

So I'm currently using assimp on a university project dealing with large models. I'm basically trying to render as large a model as I can get away with on assorted hardware, and so I'm currently trying out quite a few free assets from freebie websites. Sadly, after the files (currently mostly .obj or 3dsMax-exported .obj-files) exceed a certain size I always get a "bad allocation"-error during the readFile-call. I am particularly sad about being unable to use a 871mb-obj-file that is looking quite sweet in 3dsMax (around 4mil. vertices). 

I had a look at the source myself, but so far I see no obvious problems (The mesh-number, animation-number and so forth shouldn't overflow any integers AFAIK; My own allocation limits for RAM and VRAM/GDDR should also not be hit, and it's not hitting any 32-bit limits). Are there any hardcoded or logical limits on what assimp can handle? Or am I hitting a bug here?

Thanks in advance,
Fabian Korak

**Comment by akaltar** [comment]
I've got the same problem.

Here is the log: 

	Info,  T2404: Load D:/code/Sunshine_Engine/Release/objects/1408_vrt_v19.obj
	Info,  T2404: Found a matching importer for this file format
	Info,  T2404: Import root directory is 'D:/code/Sunshine_Engine/Release/objects\'
	Error, T2404: OBJ: No object detected to attach a new mesh instance.
	Skipping one or more lines with the same contents
	Info,  T2404: Entering post processing pipeline
	Info,  T2404: RemoveRedundantMatsProcess finished. 1 redundant and 1 unused materials
	Info,  T2404: OptimizeGraphProcess finished; Input nodes: 2953, Output nodes: 1
	Info,  T2404: OptimizeMeshesProcess finished. Input meshes: 2952, Output meshes: 36
	Error, T2404: Failed to compute tangents; need UV data in channel0
	Skipping one or more lines with the same contents
	Info,  T2404: CalcTangentsProcess finished. Tangents have been calculated
	Error, T2404: bad allocation
	Info,  T2404: Leaving post processing pipeline

And I use a much heavier post-processing:
    		importer->ReadFile( file, 
			aiProcess_CalcTangentSpace |
			aiProcess_Triangulate | 
			aiProcess_RemoveRedundantMaterials |
			aiProcess_OptimizeGraph |
			aiProcess_OptimizeMeshes |
			aiProcess_SplitLargeMeshes |
			aiProcess_JoinIdenticalVertices |
			aiProcess_ImproveCacheLocality );

Also, the bad alloc doesn't occur always, I guess my model size is just on the brink of the limit.
Its about 95MB with about 3000 smaller objects.

Total statistics from 3ds max obj exporter:
 420000 verts, 305000 normals, 311000 Tverts(whatever that means), 900000 triangles.


Using Windows 7 x64 with 8GB RAM, but app is 32bit.

**Comment by kimkulling** [comment]
Ok, I will take a look onto it. Thanks a lot for the report!

Kimmi

**Comment by NoxMortem** [comment]
Another scene assimp is not able to load is the rungholt scene with ~6M triangles.
http://graphics.cs.williams.edu/data/meshes.xml

Tried to remove all flags but only used aiProcess_SplitLargeMeshes

**Comment by acgessler** [comment]
Given Obj is a text format, we should not have 10x memory overhead reading it.

Can we do something to bring it down? At a quick glance, it seems `Face`
https://github.com/assimp/assimp/blob/master/code/ObjFileData.h#L62
is responsible. Maybe we can use the vectors during parsing, but then copy into a plain old array owned by `Face`? In case Obj only supports quads (not quite sure), we could just embed arrays with no heap allocation.

**Comment by acgessler** [comment]
Ignore previous deleted post, didn't read properly.

Are any debug builds involved? We do lots of small allocations, these blow up on debug heaps.

@open3mod
>> I am, however only able to select OpenGL/Legacy as the Render Backend in open3mod, so maybe there is also a bug there? 

I disabled the other backend before release, not ready yet. So no bug, just a non-complete feature that leaves its little signs in the UI :-)

**Comment by NoxMortem** [comment]
Yes I have noticed this with assimp as well as tinyobjloader. It looks like it breaks on debug. I am going to test it with the release version and expect it work but will report back!

**Comment by akaltar** [comment]
In my example I am using the release build and starting the exe separately(I had already noticed that the debugger slows it down by a magnitude). And also I am not hitting the memory limit. Its like 450-600MB at max, while loading the scene...   I cannot send it to you, and I don't think I can reconstruct such a complex and diverse scene synthetically.

**Comment by kimkulling** [comment]
Closed by 8b2f1085c77ba5805f3f6c3c34d3657f54e6e952

**Comment by chuan9** [comment]
@fkorak I have the same problem with you. When read the big obj file which is about 1G+, it will report: bad allocation. Do you know how to resolve it?
@NoxMortem Yeah ,your problem seems that not related with "bad allocation". It's just because the debug mode use system heap which cause the slow build but not can't load.

**Comment by chuan9** [comment]
@kimkulling Do you have try rungholt scene? when i start it from exe, it will report the same issue with my big model: 
errpr::shader::program::linking_failed
Vertex info
-----------
(0) : error C5145: must write to gl_Position

ERROR::ASSIM111P:: Unable to open file "xproject/rungholt/rungholt.obj".
It seems that loading is failed so shader cann't get the vertext data.

**Comment by kimkulling** [comment]
Which version do you use?

**Comment by chuan9** [comment]
@kimkulling Sorry for late reponse. I use assimp-3.3.1, build the 32bit lib and dll on my own. I will try to build my program on x64 and switch all libs including assimp to 64bit. Will this help solve this issue?

**Comment by chuan9** [comment]
@kimkulling I can load the big obj which is about 1.1G with 64 bit program. The real cost memory is 3G when in loading and will down to 1G when the object is rendered. BTW, if someone want to accelerate the loading speed, he should build release version which is 6x faster than debug version. Thx for your response again.

**Comment by kimkulling** [comment]
You are welcome, no problem...

**Comment by FrankBATMAN** [comment]
scene assimp is not able to load is the "San Miguel" scene
http://www.ospray.org/demos.html

**Comment by Dy111111** [comment]
I know one case, when you open too much softwares, your system memory is not enough, this error will happen.
