### ISSUE TITLE
glTF is wrong spelled to glFT.

### ISSUE THREAD

**Issue by eherozhao** [assimp/assimp#3904]
**Describe the bug**
In the introduction section of the documentation. The glTF is wrong spelled to glFT.

**To Reproduce**
1. Go to https://assimp-docs.readthedocs.io/en/latest/about/introduction.html
2. Search for 'glTF', there will be no results.
3. Search for 'glFT' and see the errors.

**Expected behavior**
Please check it out and change it.

**Screenshots**
[The introduction link](https://assimp-docs.readthedocs.io/en/latest/about/introduction.html)
<img width="1170" alt="Screen Shot 2021-05-16 at 9 48 50 AM" src="https://user-images.githubusercontent.com/36955586/118405362-743e7a80-b62c-11eb-85ed-469488f7d9bf.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 90

**Smartphone (please complete the following information):**

**Additional context**
None

**Comment by kimkulling** [comment]
Thanks for the hint. I will fix that!

**Comment by kimkulling** [comment]
Is fixed right now. Thanks for the report!
