### ISSUE TITLE
Linker Errors - Eclipse

### ISSUE THREAD

**Issue by freezeware** [assimp/assimp#393]
D:\Cpp\test\3DGameEngine\Debug/../src/rendering/mesh.cpp:257: undefined reference to `Assimp::Importer::Importer()'
D:\Cpp\test\3DGameEngine\Debug/../src/rendering/mesh.cpp:263: undefined reference to `Assimp::Importer::ReadFile(char const*, unsigned int)'
D:\Cpp\test\3DGameEngine\Debug/../src/rendering/mesh.cpp:303: undefined reference to `Assimp::Importer::~Importer()'
D:\Cpp\test\3DGameEngine\Debug/../src/rendering/mesh.cpp:303: undefined reference to `Assimp::Importer::~Importer()'

In linker i have assimp.lib linked.

**Comment by kimkulling** [comment]
Any updates? If yes: please reopen the issue.
