### ISSUE TITLE
Bug: ON in conditional statement in assimpTargets.cmake

### ISSUE THREAD

**Issue by Beatle95** [assimp/assimp#3935]
**Bug description**
In assimpTargets.cmake, generated after ```cmake --install```, on line 54 there is ```if(ON)```, and CMake throws a warning on that line, because ON in conditional statement means False. If assimp was generated with ```ASSIMP_BUILD_SHARED_LIBS ON```, this leads to an error in compile-time, because in generated solution in Linker Input section there is .dll file instead of .lib.

**To Reproduce**
1. Generate and install Assimp from sources with ```ASSIMP_BUILD_SHARED_LIBS ON```
2. Add it to project with 
```
find_package(assimp REQUIRED assimp)
...
target_link_libraries(project_name PRIVATE assimp::assimp)
```
3. Generate solution
4. Try to build solution in any configuration
5. See an error in compiler output

**Expected behavior**
Build generated project successfully. (I fixed that problem for myself by replacing ```if(ON)``` with ```if(1)``` in assimpTargets.cmake on line 54).

**Platform (please complete the following information):**
 - OS: Windows
 - Generating: Solution for Visual Studio
 - Version Asssimp: 5.0.1; CMake: 3.19.2

**Comment by trackpadpro** [comment]
Although I did not find a mention of this being mentioned in release notes, updating to 5.2.5 removed this warning for me, and the offending conditional was replaced within assimpTargets.cmake.

**Comment by kimkulling** [comment]
So I will close the issue because it is deprecated.
