### ISSUE TITLE
The source codes in releases page cannot be unzipped

### ISSUE THREAD

**Issue by Hotege** [assimp/assimp#3936]
I downloaded the source codes in releases page(5.0.1) and tried to unzip them with 7-zip and bandizip.
7-zip and bandizip told me that the files were broken.
Did I unzip them in a wrong way?
How do I unzip the source codes?
If the source codes in releases were actually broken, please update them, thanks.

**Comment by Hotege** [comment]
It wont be broken if I download them with chrome.

**Comment by kimkulling** [comment]
Same here! I will close this one. As a workaround: try to use 7zip or use the tar-ball instead.

**Comment by kimkulling** [comment]
Ah, already closed. I have choosed the wrong filter.
