### ISSUE TITLE
Generic PBR Materials Handling

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#3949]
Most modern rendering engines prefer to use one or other variant of Physically-Based Rendering (PBR)

There are two main PBR workflows in current usage, which use the following texture maps
- Metallic/Roughness
  - Base Color (ARGB with color space and gamma correction)
  - Roughness (single value)
  - Metallic (single value)

- Specular/Glossiness
  - Diffuse/Albedo (ARGB with color space and gamma correction)
  - Glossiness (single value)
  - Specular (single value)

Additionally, the provided texture maps may combine two or more of the above single-value channels into a single map, and may invert the sense (eg Smoothness = 1.0 - Roughness)

**Current Situation**
Assimp does not have a defined consistent way to encode these PBR models.
The glTFv2 importer uses its own private set of material properties, while the FBX (Maya/3DS Max) importer uses another.

Eg glTFv2 places the Base Color into aiTextureType_DIFFUSE, and all the other PBR textures under `aiTextureType_UNKNOWN`, indexed as 0 thru 5.

Worse, the application has no way of knowing which color channels are in use, or what they mean. It has to know details about how a given format encodes the data. Formats that support multiple ways of encoding PBR data have no way of passing this information on to the application.

**Proposal**
Amalgamate and clean up the existing different sets of PBR material properties as follows:

***aiShadingMode***
Add
- `aiShadingMode_PBR`

Defines that the materials uses a PBR-type shading model.

Applications that support rendering of PBR materials then use the list of provided Properties (AI_MATKEY_XXX) and Textures (aiTextureType_XXX) to determine which PBR shading model is in use.

***aiTextureFlags***
Add
- `aiTextureFlags_UseRed`
- `aiTextureFlags_UseGreen`
- `aiTextureFlags_UseBlue`

Explicitly sets which channel(s) of a texture are actually in use for the specified texture function.

Combine with:
- `aiTextureFlags_InvertRed`
- `aiTextureFlags_InvertGreen`
- `aiTextureFlags_InvertBlue`
- `aiTextureFlags_InvertAlpha`

These allow a texture channel to be explicitly flipped if needed.
Eg a Normal Map might set `aiTextureFlags_UseRed | aiTextureFlags_UseGreen | aiTextureFlags_InvertRed | aiTextureFlags_InvertGreen` to indicate that it's using the Red and Green channels, and inverts them compared to Assimps' default left-handed setting.

***AI_MATKEY_XXX***
Remove all `AI_MATKEY_USE_XXX`, these are internal format flags. Applications should use the presence of a supported `aiTextureType_XXX` as the indication that a given texture type should be used.

Move all the `AI_MATKEY_GLTF_XXX` into material.h, remove the duplicates.

***aiTextureType***
Texture "type" is complex, as some formats/renderers will use the same texture image to provide multiple channels.

I propose importing the same texture _multiple_ times, once for each purpose. The above flags then indicate to the application how each texture includes the data.
The application can then merge together the final bitmaps as appropriate for its renderer.

Examples:
- glTFv2 PBR uses a single texture to provide Metallic & Roughness. B = Metallic, G = Roughness
  - `aiTextureType_METALNESS`
  path: `my_gltf_metal_rough.png`
  flags `aiTextureFlags_UseBlue`
  - `aiTextureType_DIFFUSE_ROUGHNESS`
  path: `my_gltf_metal_rough.png`
  flags `aiTextureFlags_UseGreen`

- glTFv2 KHR_materials_pbrSpecularGlossiness uses a single texture to provide Specular & Glossiness. RGB = Specular Color, A = Glossiness
  - `aiTextureType_SPECULAR`
  path = `my_gltf_spec_gloss.png`
  flags = `aiTextureFlags_UseRed | aiTextureFlags_UseGreen | aiTextureFlags_UseBlue`
  - `aiTextureType_GLOSSINESS`
  path = `my_gltf_spec_gloss.png`
  flags = `aiTextureFlags_UseAlpha`

- FBX (both 3DS Max and Maya) appear to use separate textures for Metallic and Roughness.
  - `aiTextureType_METALNESS`
  path = `my_fbx_metal.png`
  flags = `aiTextureFlags_UseBlue`
  - `aiTextureType_DIFFUSE_ROUGHNESS`
  path = `my_fbx_rough.png`
  flags `aiTextureFlags_UseGreen`

Note: I have not yet found which channel is actually in use for the Maya PBR, so I've assumed it's done as a simple greyscale (R==G==B) and arbitrarily picked the glTFv2 channels to make it easier for a consuming application to merge them.

Some formats may pack further functions into the additional channels

An application can then note when the same file "path" is used for both, along with which color channels within the map actually encodes the specified parameter, and whether they are inverted.
It may then make any necessary transformations to convert the provided texture map(s) to that required by its renderer.

Eg Unreal Engine 4 uses Red = AO, Green = Roughness and Blue = Metallic, so a UE4 application will want to repack the textures that way after loading.

Further notes:
The fact that different 3D formats encode PBR material channels in different ways mean that a full conversion between (eg) FBX and glTF requires the ability to read and process image files to rearrange the color channels. This means that for full functionality, the assimp exporters will need to be able to read and convert at least some types of image files.

**References**
https://academy.substance3d.com/courses/the-pbr-guide-part-1
https://academy.substance3d.com/courses/the-pbr-guide-part-2
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness
Maya FBX PBR materials PR https://github.com/assimp/assimp/pull/3858

**Comment by RichardTea** [comment]
PBR may be further modified by the addition of "Clearcoat", "Sheen" and "Transmission" factors and maps.
At present these are only supported by the glTFv2 importer/exporters, however it is likely that other formats will add some level of support for this in the future.

**Comment by kimkulling** [comment]
Basic stuff is provided right now.

**Comment by KeyC0de** [comment]
Any updates on the state of how well Assimp can read PBR materials (either of the two workflows) from FBX files?
