### ISSUE TITLE
Bug: Read The Docs API-Reference is not working

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#3950]
See: https://assimp-docs.readthedocs.io/en/latest/API/API-Documentation.html

The content is missing, instead there is:

> doxygenstruct: Cannot find file: /home/docs/checkouts/readthedocs.org/user_builds/assimp-docs/checkouts/latest/source/API/index.xml

**Comment by bubba2k** [comment]
Having the same issue. Is there any other place to read the API docs in the meantime?

**Comment by kimkulling** [comment]
Fixed.
