### ISSUE TITLE
Bug: Bee.glb model loads incorrectly

### ISSUE THREAD

**Issue by thomas-olsen** [assimp/assimp#3962]
**To Reproduce**
1.  Unzip Bee.zip to retrieve Bee.glb
2. Assimp::Importer.ReadFile("Bee.glb", flags);
3. aiScene->mRootNode->mNumMeshes == 0 and aiScene->mRootNode->mMeshes==nullptr.  All nodes below the root node have mNumMeshes==0 and mMeshes==nullptr.

[Bee.zip](https://github.com/assimp/assimp/files/6689303/Bee.zip)

**Expected behavior**
I would expect aiScene->mRootNode->mNumMeshes > 0 and aiScene->mRootNode->mMeshes!=nullptr, and all child nodes should be populated.

**Screenshots**

**Platform (please complete the following information):**
 - OS: All
 - Browser N/A
 - Version 5.0.1

**Additional context**

**Comment by thomas-olsen** [comment]
@kimkulling known issue?

**Comment by kimkulling** [comment]
Let's check: https://github.com/assimp/assimp/pull/3959 This could fix the issue.

**Comment by kimkulling** [comment]
![bee](https://user-images.githubusercontent.com/2323156/123952111-d61d2e80-d9a5-11eb-923b-b5368c1abbc4.png)

Works with the latest master. So the https://github.com/assimp/assimp/pull/3959 has closed this issue.

Thanks a lot for your issue-report!

**Comment by thomas-olsen** [comment]
@kimkulling this issue is not fixed. When you load the model, look at the aiScene->mRootNode hierarchy, you will note after loading that each of the child nodes has mNumMeshes == 0 and mMeshes == NULL. This is invalid. I would expect it to be at least mNumMeshes == 1 and mMeshes to point to index 0. Make sense?
