### ISSUE TITLE
Explanation: How to translate bone transformation from global coordinate system to armature coordinate system 

### ISSUE THREAD

**Issue by n4pt1me** [assimp/assimp#3968]
Hi. I need to find out when, along with the bones for a specific mesh, there is an armature (which, like an empty node, is in the node hierarchy). Are there any ideas how this can be done, since the armature is not always created as a node (aiNode)?

I need this for my logic to translate the transformation of bones from the scene coordinates into the coordinates of the armature or the coordinates of the first bone, if the armature is not defined. As far as I studied the library, bone transformations in it are translated into scene coordinates (or global).

**Comment by kimkulling** [comment]
You can take a look into the post-process **ArmaturePopulate**. You need to check which nodes have bones and add this information to a list. Then you need to create the stack for the armature:
- Find the root node for your armature (check the post-process how to do that).
- Create the stack of nodes that belong to the armature by iterating the children nodes of the root node which are related to the armature. You can use the name of the bone to identify these node instances in the scene.

I hope that gives you some kind of a starting point.

**Comment by n4pt1me** [comment]
> 
> 
> You can take a look into the post-process **ArmaturePopulate**. You need to check which nodes have bones and add this information to a list. Then you need to create the stack for the armature:
> 
>     * Find the root node for your armature (check the post-process how to do that).
> 
>     * Create the stack of nodes that belong to the armature by iterating the children nodes of the root node which are related to the armature. You can use the name of the bone to identify these node instances in the scene.
> 
> 
> I hope that gives you some kind of a starting point.

Thank you, that's helped.

**Comment by kimkulling** [comment]
You are welcome!
