### ISSUE TITLE
Compiled V5.0.1 reports errors not in previous version.

### ISSUE THREAD

**Issue by chubun** [assimp/assimp#3978]
I downloaded and ran the Windows installer assimp 3.3.1 from assimp.org and everything worked nicely. However, that version does not export gltf2 (there are some related discussions here about -fgltf2 not working). So I downloaded the source and compiled using VS 2019. I followed the instructions on the ReadMe.md page:

    Open a command prompt
    mkdir build
    cd build
    cmake ..
    cmake --build .

However, the compiled V 5.0.1 reports many errors that the older version does not. For examples,

- Duplicate ID error:
=== Old version:
c:\temp>"d:\Program Files\Assimp\bin\x64\assimp.exe" export Tile_10.dae test.gltf
assimp export: select file format: 'gltf' (GL Transmission Format)
Launching asset import ... OK
Validating postprocessing flags ... OK
Importing file ... OK
import took approx. 0.01100 seconds

Launching asset export ... OK
Exporting file ... OK
export took approx. 0.00200 seconds

assimp export: wrote output file: test.gltf

=== V 5.0.1
c:\temp>c:\bin\assimp.exe export W:\temp\Tile_10.dae test.gltf
param = test.gltf
assimp export: select file format: 'gltf2' (GL Transmission Format v. 2)
Launching asset import ... OK
Validating postprocessing flags ... OK
Importing file ... OK
import took approx. 0.01300 seconds

Launching asset export ... OK
Failed to write file
ERROR: GLTF: two objects with the same ID exist

- Unsuported file format:
=== Old version
c:\temp>"d:\Program Files\Assimp\bin\x64\assimp.exe" export W:\temp\Tile_10_L21.mtl test.gltf
assimp export: select file format: 'gltf' (GL Transmission Format)
Launching asset import ... OK
Validating postprocessing flags ... OK
Importing file ... OK
import took approx. 0.01800 seconds

Launching asset export ... OK
Exporting file ... OK
export took approx. 0.00100 seconds

assimp export: wrote output file: test.gltf

=== Version 5.0.1
c:\temp>c:\bin\assimp.exe export W:\temp\Tile_10_L21.mtl test.gltf
param = test.gltf
assimp export: select file format: 'gltf2' (GL Transmission Format v. 2)
Launching asset import ... OK
Validating postprocessing flags ... OK
ERROR: Failed to load file: No suitable reader found for the file format of file "W:\temp\Tile_10_L21.mtl".

Maybe I miss some flags for the compiler?

**Comment by qtnemo** [comment]
Attached are the files used in the test.  Really appreciate it if anybody can check if their compiled 5.0.1 version can export these two files to gltf.
[samples.zip](https://github.com/assimp/assimp/files/6778357/samples.zip)

**Comment by RichardTea** [comment]
The `Tile_10_L21.mtl` file is not a 3D format. Assimp should not load it at all.
It's a sidecar file that is used by an OBJ file, and as there's no OBJ file, it's useless.

If a previous version of Assimp did anything with it, then that was a bug.

**Comment by RichardTea** [comment]
The DAE is rather strange.
It references a file `Tile_10_L19_0.jpg` (not present), but specifies it as being zero pixels in size which is not permitted.

The reason for the failure to export is because the glTF2Exporter is trying to export using a new root node called "defaultScene", but the original DAE already uses that name.

**Comment by qtnemo** [comment]
> The DAE is rather strange.
> It references a file `Tile_10_L19_0.jpg` (not present), but specifies it as being zero pixels in size which is not permitted.
> 
> The reason for the failure to export is because the glTF2Exporter is trying to export using a scene called "defaultScene", but the original DAE already uses that name.

We ran a batch test on a number of file formats and these were flagged with errors.  Some of the sample files are probably not very well-formed.  Your explanations make sense.  Thanks.
