### ISSUE TITLE
[ColladaImporter] [Regression] [Bug] Fail to import .dae from makehuman

### ISSUE THREAD

**Issue by VadikLeshy** [assimp/assimp#3984]
OS: Any (tested Windows x86_64 and Arch Linux x86_64)
Assimp Version: latest git; Release v5.0.1 is not affected
1. Create any character with MakeHuman
2. Export a resulting model to DAE Collada
3. ``aiImportFile("path/to/human.dae", anyPostrocessFlags)`` returns nullptr

I think this is bug of libassimp, since Blender and libassimp 5.0.1 are fine with importing the humans.

**Comment by VadikLeshy** [comment]
``aiGetErrorString()`` returns ``"Cannot parse string "?            1.00000 0.00000 0" as a real number: does not start with digit or decimal point followed by digit."``

**Comment by RichardTea** [comment]
Can you attach a sample dae?

**Comment by VadikLeshy** [comment]
[MakedHuman.zip](https://github.com/assimp/assimp/files/6759356/MakedHuman.zip)

**Comment by RichardTea** [comment]
I think I've found the trouble. MakeHuman is now exporting the node matrix as a nice formatted table:
`          <matrix sid="transform">
            1.00000 0.00000 0.00000 0.00000
            0.00000 1.00000 0.00000 0.00000
            0.00000 0.00000 1.00000 0.00000
            0.00000 0.00000 0.00000 1.00000
          </matrix>`

ColladaParser::ReadNodeTransformation() is not skipping the carriage return and whitespace before the first number.

I also found a casting error when reading UV coordinates.
