### ISSUE TITLE
Getting animation keyframes with BEZIER interpolation type from Collada

### ISSUE THREAD

**Issue by n4pt1me** [assimp/assimp#4022]
I looked at the Collada import code but didn't find anything related to the definition of the bezier interpolation type. Moreover, in the Collada file itself (.dae), you can find a line where the type of interpolation is indicated. Can you tell me the best way how I can get a set of animation keys when type of interpolation is Bezier?

**Comment by kimkulling** [comment]
You shall be able to find that data in the aiNodeAnim-INstance which are part of the aiScene-Instance-

**Comment by mick-p1982** [comment]
I'm pretty sure there's no code in the loader for nonlinear animation.

https://github.com/assimp/assimp/blob/4d7e817bd86379d722508e8a41d231cc00600d47/code/AssetLib/Collada/ColladaLoader.cpp#L1285-L1286

Based on this comment the loader outputs is likely sparse and linear.
