### ISSUE TITLE
How to use Post Processing? Includes not clear, procedure not clear.

### ISSUE THREAD

**Issue by SnapperTT** [assimp/assimp#4023]
I am using the following includes:

```
#define ASSIMP_BUILD_BOOST_WORKAROUND
#include <assimp/Importer.hpp>      // C++ importer interface
#include <assimp/scene.h>           // Output data structure
#include <assimp/postprocess.h>    // Post processing flags
```

And am attempting to resize a mesh using a `ScaleProcess` on load:

```
Assimp::Importer importer;
Assimp::ScaleProcess  SP;
SP.setScale(10.f);
importer.RegisterPPStep(&SP);
... load file as usual
```
This fails to compile due to the class `ScaleProcess` not being in the includes, and `code/PostProcessing/ScaleProcess.h` not being in the include path.

Manually adding `assimp/code` to the include path and including:
```
#include <Common/BaseProcess.h>
#include <PostProcessing/ScaleProcess.h>
```
allows my code above to compile, however it segfaults.

Calling the following after: `importer.ReadFile`
```
Assimp::ScaleProcess  SP;
SP.SetupProperties(&importer);
SP.Execute(scene);
```
will not compile as `importer.ReadFile` returns a  `const aiScene*` whereas `ScaleProcess::Execute` requires a `aiScene*`. Const casting `scene` will allow it to compile however the object is not scaled.

Please advise.

**Comment by kimkulling** [comment]
The post-process will be performed automatically. You only have to set the Post-Processing-Flag when you are calling `Importer.import()` . You can find an example in our documentation: https://assimp-docs.readthedocs.io/en/latest/usage/use_the_lib.html
