### ISSUE TITLE
Does the lib support Morph in FBX ?

### ISSUE THREAD

**Issue by CaichaoGitHub** [assimp/assimp#4028]
I want to load Morph targets from FBX model, but in code it says : 
![image](https://user-images.githubusercontent.com/12059897/129195469-94e82d10-61d9-44ef-b3ab-f23e03d7dfd7.png)
likely it only support dae format ?

Does the lib support Morph in FBX ?

How can i used it ? i did't find a example in source code ;

**Comment by kimkulling** [comment]
Just found this: void ProcessMorphAnimDatas(std::map<std::string, morphAnimData*>* morphAnimDatas, const BlendShapeChannel* bsc, const AnimationCurveNode* node);

So the answer is yes if I get this right.
