### ISSUE TITLE
Bug: cannot build because of failed static assertion

### ISSUE THREAD

**Issue by Totoooooooo** [assimp/assimp#4033]
I am trying to build Assimp with cmake and MinGW on windows 10, and when building `FBX/FBXExporter.cpp.obj` the compilation stops and shows the following error:
 `static assertion failed: TRIED TO CREATE FBX PROPERTY WITH UNSUPPORTED TYPE, CHECK YOUR PROPERTY INSTANTIATION
static_assert(std::is_void<T>::value, "TRIED TO CREATE FBX PROPERTY WITH UNSUPPORTED TYPE, CHECK YOUR PROPERTY INSTANTIATION");
                    ^~~`.
I am completely new to graphics programming and this is my first time building a library from source.
What am I doing wrong?

**Comment by kimkulling** [comment]
Could you please provide the line-number?

**Comment by Totoooooooo** [comment]
It is line 107, here is the full error code: https://pastebin.com/xAsn3dGq

**Comment by kimkulling** [comment]
This issue is already fixed on the current master. So just switch to the master or wait for the next release.
