### ISSUE TITLE
What's the meaning of preRotation , postRotation , rotation  in FBX?

### ISSUE THREAD

**Issue by CaichaoGitHub** [assimp/assimp#4035]
Hi guys 
i'm loading a fbx model  using Assimp , but i found some extension in Node Tree
in FBX converter:
![image](https://user-images.githubusercontent.com/12059897/129833647-f3499162-590a-41c5-91c8-fc74b99bd9c5.png)

in Processed Model:
![image](https://user-images.githubusercontent.com/12059897/129833405-ca5aee40-489b-4d01-9d95-c077bfb01234.png)

Would anyone explain how to handle the extension info  please?

**Comment by AndrewChan2022** [comment]
> The FBX format stores node transforms using an expanded sequence of transforms. These aiNodes represent that sequence. They are simply aiNode that have no mesh and a single child for the next stage of the FBX transform.
> 
> Either treat them the same as any other aiNode that has no mesh, or multiply the transforms together to collapse them into a single aiNode. I believe there's an FBX importer property to get assimp to do the latter.
> 
> As I understand it, FBX does this because it was originally created for motion capture, and it's useful to have the decomposed transform when working with motion capture data because it's not possible to decompose a transform matrix back into the _original_ set of rotation etc, only an _equivalent_.


I use this to collapse the node:
importer.SetPropertyBool(AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, false);
