### ISSUE TITLE
Bug: Build Failed (Windows10 | CMake | MinGW64)

### ISSUE THREAD

**Issue by ElijahGoodman** [assimp/assimp#4042]
**Build failed on stage "Linking CXX executable assimp_viewer.exe"**
Incomplete build with following settings:

**Platform and settings :**
 - Windows 10 Pro (21H1)
 - CMake 3.21.1
 - C/C++ compiler: GNU 10.3.0 (MSYS | MinGW64 or Eclipse IDE)
 - Additional CMake flags:  BUILD_SHARED_LIBS = false

**Additional explanations**
During building with "make" (after CMake generate according files) errors occurs on stage
> [ 68%] Linking CXX executable assimp_viewer.exe

Output :
> .../ld.exe: CMakeFiles/assimp_viewer.dir/objects.a(Background.cpp.obj):Background.cpp:(.text+0x1403): ***undefined reference to `D3DXCreateCubeTextureFromFileExA'***

...Similarly for other DirectX functions...

>make: *** [Makefile:136: all] Error 2
"D:/SDKs/msys64/usr/bin/make.exe all" terminated with exit code 2. Build might be incomplete.

But DIrectX SDK was installed successfully (Output of CMake generator):
>Looking for DirectX...
DirectX_PREFIX_PATH changed.
Found DirectX: D:/SDKs/DirectX_SDK/Lib/x86/d3d9.lib
DX lib dir: D:/SDKs/DirectX_SDK/Lib/x86

**Comment by kimkulling** [comment]
To work around this you need to disable the viewer tools in the CMake-Run. But yes, this is a bug!

**Comment by kimkulling** [comment]
The build with mingw is not supported for the Viewer. I will disable that.

**Comment by kimkulling** [comment]
Fixed
