### ISSUE TITLE
Bug: import IFC

### ISSUE THREAD

**Issue by wujie-zxc** [assimp/assimp#4046]
Hi  I have a problem

when I import this IFC file, The following error occurs:
**type error reading literal field - expected argument 0 to IfcProperty to be a `IfcIdentifier`"**

![9cf021d10f1ad923ecde8caca66f201](https://user-images.githubusercontent.com/62047383/130720515-352956e3-aa7b-414a-9238-9ee1840af59e.png)

[test.zip](https://github.com/assimp/assimp/files/7043358/test.zip)

**Comment by kimkulling** [comment]
Duplicated, just search for UFC-4 support.
