### ISSUE TITLE
FBX import: Rotation is missing

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#406]
When I export a mesh out of 3DS Max (FBX format 2014, binary), which is translated and rotated only the translation matrix will be read by assimp. Parent node or child node does not contain any rotation data!

Regards Marc

**Comment by promethe42** [comment]
Can you please post your sample file?

I think we have the same issue. Yet we've found a way to fix this before the epxort from 3DS Max. So we should have a pretty good idea about what's causing the issue...

**Comment by DanielNogueiraAndroid** [comment]
I think we have the same issue.

**Comment by prunoid** [comment]
I've come up against the same issue with fbx 7.4 binary animations exported from blender 2.7x.
This is very simple to reproduce with a one or two bone sample fbx and only a couple of rotation keys. Assimp provides an animation channel with a duration of 1 and no keys.
Same file using only a couple of translations instead works fine.
The issue appears to be in the ASSIMP FBX importer, as the file exported from blender can be re-imported into blender and bone rotations work OK in animation play back.

Let me know if a sample file is still reqiired.

**Comment by danke-sra** [comment]
The model you have probably uses Euler angels that are multiples of 360. When converted to quaternions, they become identity, so the rotation is lost. I tried to set those Euler values to other values and they seemed to work.

**Comment by kimkulling** [comment]
Shall be fixed now.
