### ISSUE TITLE
DataModel with shared/weak pointer

### ISSUE THREAD

**Issue by Madrich** [assimp/assimp#4066]
I'd like to start the discussion to change the aiNode Pointers to Shared pointers and have weak pointers to the parents.
Currently it is very error-prone to destroy the allocated data. Changes on existing code should be minimal.
Creating new nodes can be done using a Factory class to observe memory usage etc. and or make a out-of-core (mem) implementation. We run very often into out-of-memory issues with large projects.

Any suggestions?

**Comment by kimkulling** [comment]
You are right, that this is really error-prone. But we are using this model as the data-model in our c-API as well. So one option could be to provide a specialized C++ Datamodel.

Any opinions on that?

**Comment by Madrich** [comment]
You are right. We should make a CMake option to use the shared pointer references instead of raw pointer. Maybe for the function calls we can introduce a MACRO to distingue between Raw pointers and shared pointers?
We can setup a new branch to test everything. Do you have unit/functional tests for all file format imports?

**Comment by turol** [comment]
No, this is a lot of complexity for no benefit. The current data model is simple and C-compatible (which means compatible with everything).

**Comment by kimkulling** [comment]
I do agree. We also support a lot of c-based APIs which are not interested in any shared-pointer semantic.

I know that this is a strong argument for avoiding c++ based implementations. So from my point of view managing, all external pointers with a shared pointer make sense for the user of assimp. 

And when I have a look onto more than 330 open Bugs I don't see time to work on this feature. Feel free to provide a PR for that.
