### ISSUE TITLE
Bug: Indices not loading

### ISSUE THREAD

**Issue by Daniel-Ros** [assimp/assimp#4074]
**Describe the bug**
I am trying to load simple model with assimp ( a basic cube from blender as glft).
No errors thrown/shown after the readFile with this flags `aiProcess_Triangulate | aiProcess_JoinIdenticalVertices`
mNumFaces is ok, and gives expected resualt, but there are no faces/ Indices in those faces.
for some model it gives garbage like 300 Indices and for some empty face.
this is the code trying to load the face and I get a seg fault at the `const aiFace face = mesh->mFaces[i];` line.
```
for (uint32_t i = 0; i < mesh->mNumFaces; i++)
		{
			const aiFace face = mesh->mFaces[i];
			for (uint8_t j = 0; j < face.mNumIndices; j++)
			{
				indecies.push_back(face.mIndices[j]);
			}
		}
```

**To Reproduce**
the code was taken from learnopengl.

**Platform (please complete the following information):**
 - OS: Linux manjaro, the Assimp  libs was taken from the official repos.
 - 

**Additional context**
using the official C  sample provided I get no errors with the same files

**Comment by Daniel-Ros** [comment]
Update:  using the AUR to download and compile the binaries fixed the issue

**Comment by kimkulling** [comment]
Fine, so I will close this issue. Thanks for your update.
