### ISSUE TITLE
Replacing Boost with C++11

### ISSUE THREAD

**Issue by tylorr** [assimp/assimp#409]
I forked the repo and replaced all Boost features with c++11 ones. I did this hastily so it may not be perfect. I'm not quite happy with my choice of replacement for `boost::format`, I chose `stringstreams`. Also, I didn't bother looking for a replacement for `boost::timer` so the profiler functions are currently noops.

I'm only positing this here in case anyone was interested.

https://github.com/tylorr/assimp
https://github.com/tylorr/assimp/commit/fecbcbe5325ee5383264310bf75ada13b671bb3d

**Comment by Madrich** [comment]
I would appreciate removing boost too....

**Comment by acgessler** [comment]
Boost is not a dependency since we have our own minimal substitutes of all boost functionality needed.

**Comment by Madrich** [comment]
Ups, your are right. Wrong library i thought ;)

**Comment by mgerhardy** [comment]
+1

**Comment by rob100** [comment]
I would appreciate the usage of C++11 features in assimp too, but we have to consider backward compatibility for older compiler. The suggestion from @iSLC sounds good but needs a lot of work now and additional maintenance in the future. The only reasonable option seems to break compatibility to old compiler. But this is a tough decision to make.

**Comment by sherief** [comment]
I think this might be worth revisiting. 

I absolutely hate breaking backwards compatibility and compiler support. But Boost *is* a huge, inconvenient dependency and getting rid of it in exchange for more recent compiler requirements might be a plus. 

What data exists about the compilers people are using with assimp? Most game platforms and PC / OS X / iOS support C++11, so if a Boost dependency can be removed by using a C++11 feature that is well supported across the board should be considered. At which point should we draw the line and tag a "legacy" version that interested people can pull and fall back to while at the same time moving forward with the API and implementation?

**Comment by meshula** [comment]
+1 for C++11

**Comment by kimkulling** [comment]
+1 for C++11

**Comment by sherief** [comment]
So, shall we start working on exonerating Boost and accept pull requests to that effect?

**Comment by sherief** [comment]
OK, I'm going to begin working on this soon. Should I create a new branch under assimp/assimp so other team members can contribute?

**Comment by rob100** [comment]
I agree to break with some old compilers for the remove/reduction of the boost dependency and using C++11 features. The C++11 support is widely spread now and gives the programmer some really nice features. Because of the impact and size of this change, I would suggest to start in a branch and accept pull request for this.

**Comment by kimkulling** [comment]
Done!

**Comment by grandemk** [comment]
Hi, at http://assimp.org/main_features.html, we can read:

No external dependencies except boost(external link) (zlib and irrxml are also needed, but they're included in the repository so you don't need to bother). And there's even a workaround to compile Assimp without boost - with some minor limitations.

I think this can be updated too right ? as the dependency is gone.

**Comment by kimkulling** [comment]
Hi,

thanks for the hint. The website is outdated. At the moment an update is in progress.

You do not need boost any more to compile assimp.
