### ISSUE TITLE
Unable to load 'obj' files

### ISSUE THREAD

**Issue by polar01** [assimp/assimp#41]
Hi,

In the following zip file you will find several '.obj' file that assimp cannot read.

https://dl.dropboxusercontent.com/u/65787026/Laguna%20v1.1.zip

I got the following message :

"Error[invalid vector<T> subscript]"

I don't know what it mean !!!

**Comment by Darecjo** [comment]
I loaded an obj file that has be modeled using 3ds max but i got an error that says ASSIMP unable to open file at <directory> is there any solution for this problem ?
