### ISSUE TITLE
Multiple Animations in Fbx Files Failing

### ISSUE THREAD

**Issue by tmr9209** [assimp/assimp#411]
I have an fbx file that has multiple animations within it, yet after being loaded they are all set to the first animation. The file has the first animation 4.25 seconds, then a second and third animation melee and attack which should be about 2 seconds each. I thought it could be me loading or using only the first animation in my engine, yet the Open 3D Model Viewer has the same issue. 
![capture](https://cloud.githubusercontent.com/assets/1815425/5059727/adc26294-6cf5-11e4-8c53-aec78720eae8.PNG)

I tested the animations in the fbx converter, which had the fbx takes setup properly, so I am pretty confident that the file and animation structure is correct.

**Comment by kimkulling** [comment]
Reopen with sample file, please.
