### ISSUE TITLE
Bug: STL import is broken and returns pointers to invalid memory areas

### ISSUE THREAD

**Issue by Elmi77** [assimp/assimp#4119]
**Describe the bug**
Whe importing STL data, the resulting struct aiScene contains invalid data.
[Test.zip](https://github.com/assimp/assimp/files/7334946/Test.zip)

**To Reproduce**
Import the attached Test.stl via 

```
aiImportFile( pFile, aiProcess_CalcTangentSpace | aiProcess_Triangulate | aiProcess_JoinIdenticalVertices | aiProcess_SortByPType |
    aiProcess_OptimizeMeshes | aiProcess_OptimizeGraph);

```
The result is a struct aiScene with e.g.:
```
mNumMeshes = 1
mMeshes[0].mNumFaces = 2892
mMeshes[0].mFaces[0] which is a pointer to an invalid memory area but not to a usable

```
The behaviour is totally random, sometimes mNumMeshes is 0, sometimes mMeshes[0].mFaces is NULL, sometimes a pointer to an invalid memory area can be found in mMeshes[0].mVertices.

**Platform (please complete the following information):**
 - Windows

**Additional context**
Happens with attached file reproducible

**Comment by kimkulling** [comment]
![image](https://user-images.githubusercontent.com/2323156/137622418-d71d57f9-c7f2-4b1a-abba-e22c22e0d5f0.png)
Worked on my side. Which environment is in use?

**Comment by RichardTea** [comment]
Easiest would be to call `Logger::create()` and pass a filename and severity before calling any assimp Importers, it'll then log to that file.

See DefaultLogger.h for more details.

**Comment by kimkulling** [comment]
Please reopen, if your issue still exists.
