### ISSUE TITLE
Bug: Fails to build with GCC 11 because warnings treated as errors

### ISSUE THREAD

**Issue by turol** [assimp/assimp#4126]
Debian testing with GCC 11.2.0:

assimp/code/AssetLib/M3D/m3d.h:4267:46: error: array subscript ‘uint64_t {aka long unsigned int}[0]’ is partly outside array bounds of ‘unsigned char [4]’ [-Werror=array-bounds]
assimp/code/AssetLib/M3D/m3d.h:3097:43: note: while referencing ‘weights’

https://github.com/assimp/assimp/blob/a83db61289c2735c9426366c258051b4296d18f5/code/AssetLib/M3D/m3d.h#L4267

assimp/code/AssetLib/glTF/glTFAsset.inl:1185:29: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

https://github.com/assimp/assimp/blob/a83db61289c2735c9426366c258051b4296d18f5/code/AssetLib/glTF/glTFAsset.inl#L1185

This should be a release blocker for 5.1.0. These need to either be fixed or warnings as errors mode disabled.

**Comment by RichardTea** [comment]
The glTF "bug" is bogus and does not exist. sceneData cannot ever be of size zero.

The array is explicitly created at a size mSceneLength + 1, then the byte at mSceneLength is assigned the value zero to ensure it will always be null-terminated.

Eg in the test utglTFImportExport.importglTFFromFileTest, the sceneData is created at length 6855 bytes then the value at index 6854 is assigned.

It's plausible it's actually the next line, some of the IOStream classes will assert for zero count - that is a bug guess, as fread returns zero for zero item size or zero item count.

**Comment by RichardTea** [comment]
What would you suggest is a "sane" maximum size?

**Comment by RichardTea** [comment]
I'd recommend disabling the m3d format by default for the 5.1.0 release.
That is 3rd party code, needs checking with upstream.

**Comment by kimkulling** [comment]
I will disable it for 5.1 until we have a fix.

**Comment by turol** [comment]
You should add a way to disable warnings as errors and then disable it in releases by default. Otherwise the next new compiler will probably also fail to build because of new warnings.
