### ISSUE TITLE
Bug: Issue 28102 in oss-fuzz: assimp:assimp_fuzzer: Stack-overflow in Assimp::FileSystemFilter::Open

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#4132]
Status: New
Owner: ----
CC: kim.k...@googlemail.com 
Labels: Restrict-View-Commit ClusterFuzz Reproducible Stability-UndefinedBehaviorSanitizer Engine-libfuzzer OS-Linux Proj-assimp Reported-2020-11-30
Type: Bug

New issue 28102 by ClusterFuzz-External: assimp:assimp_fuzzer: Stack-overflow in Assimp::FileSystemFilter::Open
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28102

Detailed Report: https://oss-fuzz.com/testcase?key=5712490213933056

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_ubsan_assimp
Platform Id: linux

Crash Type: Stack-overflow
Crash Address: 0x7fff0f261ff8
Crash State:
  Assimp::FileSystemFilter::Open
  
Sanitizer: undefined (UBSAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_assimp&revision=202008080609

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5712490213933056

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public.

**Comment by RichardTea** [comment]
I had a little bandwidth to take a look at some assimp issues today, but oss-fuzz won't let me see what caused this (or any of the others).

If you're not already working on these, could you share the detailed information in some way?

**Comment by kimkulling** [comment]
You need to get access to the fozzer-database. Or I can just provide more information regarding that. I will post the detailed info here.

**Comment by kimkulling** [comment]
<html>
<body>


Info,  T0: %%% BEGIN EXTERNAL FILE %%%
--
  | Info,  T0: File: $$___magic___$$1MDL3rageON
  | Info,  T0: Load $$___magic___$$1MDL3rageON
  | Info,  T0: Found a matching importer for this file format: LightWave Scene Importer.
  | Info,  T0: Import root directory is './'
  | Info,  T0: LWS file format version is MoO
  | Info,  T0: %%% BEGIN EXTERNAL FILE %%%
  | Info,  T0: File: $$___magic___$$1MDL3rageON
  | Info,  T0: Load $$___magic___$$1MDL3rageON
  | Info,  T0: Found a matching importer for this file format: LightWave Scene Importer.
  | Info,  T0: Import root directory is './'
  | Info,  T0: LWS file format version is MoO
  | Info,  T0: %%% BEGIN EXTERNAL FILE %%%
  | Info,  T0: File: $$___magic___$$1MDL3rageON
  | Info,  T0: Load $$___magic___$$1MDL3rageON
  | Info,  T0: Found a matching importer for this file format: LightWave Scene Importer.
  | Info,  T0: Import root directory is './'
  | Info,  T0: LWS file format version is MoO
  | Info,  T0: %%% BEGIN EXTERNAL FILE %%%
  | Info,  T0: File: $$___magic___$$1MDL3rageON
  | Info,  T0: Load $$___magic___$$1MDL3rageON
  | UndefinedBehaviorSanitizer:DEADLYSIGNAL
  | ==143583==ERROR: UndefinedBehaviorSanitizer: stack-overflow on address 0x7fff0f261ff8 (pc 0x000000494e24 bp 0x7fff0f262000 sp 0x7fff0f262000 T143583)
  | #0 0x494e24 in strncmp /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerInterceptors.cpp:148
  | #1 0x514a8e in Assimp::MemoryIOSystem::Open(char const*, char const*) assimp/include/assimp/MemoryIOWrapper.h:187:19
  | #2 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #3 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #4 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #5 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #6 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #7 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #8 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #9 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #10 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #11 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #12 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #13 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #14 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #15 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #16 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #17 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #18 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #19 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #20 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #21 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #22 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #23 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #24 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #25 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #26 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #27 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #28 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #29 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #30 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #31 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #32 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #33 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #34 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #35 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #36 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #37 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #38 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #39 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #40 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #41 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #42 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #43 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #44 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #45 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #46 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #47 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #48 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #49 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #50 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #51 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #52 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #53 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #54 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #55 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #56 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #57 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #58 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #59 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #60 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #61 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #62 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #63 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #64 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #65 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #66 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #67 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #68 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #69 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #70 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #71 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33
  | #72 0x4ee2b7 in Assimp::FileSystemFilter::Open(char const*, char const*) assimp/code/Common/FileSystemFilter.h:134:33


</body>
</html>

**Comment by RichardTea** [comment]
Can you attach the input the fuzzer fed into the system?

It almost looks like this FileSystemFilter somehow wrapped _itself_, except I don't see any way for that to happen

**Comment by kimkulling** [comment]
Will close this as well.
