### ISSUE TITLE
Where can I find a precompiled libassimp.so for Android ?

### ISSUE THREAD

**Issue by agGitHub** [assimp/assimp#4135]
Hi,

I don't manage to compile this lib for Android. Steps are not clear enough and I am not an expert with CMake.

Where can I find a precompiled libassimp.so for Android ?

Thanks.

**Comment by mpcarlos87** [comment]
Hi @agGitHub did you manage to get them? I was able to build arm-v8, arm-v7, x86 and x86-64 in local with the latest release 5.2.1. I tested them against an android x86 emulator and my arm-v8 device.

I plan to create a PR with a build script and some instructions.

**Comment by moeymisrabi** [comment]
Hey @mpcarlos87 Can you please provide more information on how you built the android files?

**Comment by mpcarlos87** [comment]
Hi @moeymisrabi I can confirm I have all in my local machine but I didn't create a PR yet to clean it up. 
I will create a quick branch next week at least so you guys can build it from that branch. 

I got it building for:

- arm-v7 (not tested)
- arm-v8 (tested in real device)
- x86 (tested in emulator)
- x86_64 (tested in emulator)

It works in releases 5.2.1 and 5.2.2 and the current main branch.

I will get you the branch name as soon as it is created. Sorry for the delay but I don't have much time (work + life)

**Comment by kimkulling** [comment]
Try this: [Prebuild libs for android](https://kimkulling.itch.io/the-asset-importer-lib)
Let me know if you need some more platforms.
