### ISSUE TITLE
[Feature request] FBX File : Import each mesh separately instead of grouping them per material

### ISSUE THREAD

**Issue by DaveUltra** [assimp/assimp#4136]
I've had a hard time with the FBX SDK, and in the end, the import time was terribly slow. Then I moved on to assimp and found it absolutely awesome.
The main difference however is that the nodes I created in my FBX files are not "mirrored" in the imported `aiScene`. I noticed that when I imported a scene with two different meshes with the same material : the two objects had been merged under the same mesh, and the nodes referencing each mesh had completely arbitrary names ("mesh_0", "mesh_1"...).

So this is my problem : right now, FBX nodes are being completely ignored, and instead, assimp regroups all meshes with the same material under one bigger mesh, and creates a node for each of these grouped meshes. I'd prefer to have the same layout as my original FBX scene, where each object would be imported as a single mesh, and where each FBX node would be imported as a single `aiNode`.

I might be able to work on this feature, but it's not guaranteed since I don't have much spare time.

**Comment by RichardTea** [comment]
Set the Importer property `AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS` to false (default is true) to ask the FBX importer to collapse the node transforms.

Note that this will make importing animations a *lot* slower, so you probably don't want to do this if you're importing animations.
You can disable import of FBX animations with `AI_CONFIG_IMPORT_FBX_READ_ANIMATIONS` = false, it's probably best to set both or neither.

**Comment by DaveUltra** [comment]
Thank you, I've managed to solve my issue.
