### ISSUE TITLE
Fix aiMeshMorphAnim::mName.

### ISSUE THREAD

**Issue by Lucipetus** [assimp/assimp#4149]
**Is your feature request related to a problem? Please describe.**
aiMeshMorphAnim::mName is described in the docs to be "Name of the mesh to be animated". 
In fact, it is, at least when loading an .FBX file, the name of an FBX Model with the index of the FBX Geometry appended (see FBXConverter::ProcessMorphAnimDatas).
The aiMesh to be morphed however, gets the name of the FBX Geometry (see FBXConverter::SetupEmptyMesh), and the aiAnimMeshes also have their own totally unrelated names.
So aiMeshMorphAnim::mName is really NOT the name of any of the mesh nodes. The user can't find the target mesh with it.

**Describe the solution you'd like**
aiMeshMorphAnim::mName or a new field should properly reference the target mesh node, with the full path down the node tree.

**Describe alternatives you've considered**
At least it should have the same name as the target mesh, and let's just ignore the case if two meshes share the same name (not possible in Blender).

**Additional context**
My scene in blender:
Object: Cube.001
----└───Mesh: Cube
--------└───// Animations etc.

It'll be loaded into ASSIMP as:

```
aiScene {
     mMeshes: [
         { 
              mName: "Cube",
              mAnimMeshes: [
                  { mName: "Key 1" }
              ]
          },  
     ]
     mMeshMorphAnim: [ 
           { mName: "Cube.001*0" } 
     }
}

```
If there's more than one mesh, I'm screwed.

**Comment by Lucipetus** [comment]
I should probably have seen this earlier.

/** The number of attachment meshes. Note! Currently only works with Collada loader. */
    unsigned int mNumAnimMeshes;

    /** Attachment meshes for this mesh, for vertex-based animation.
     *  Attachment meshes carry replacement data for some of the
     *  mesh'es vertex components (usually positions, normals).
     *  Note! Currently only works with Collada loader.*/
    C_STRUCT aiAnimMesh **mAnimMeshes;

So if mAnimMeshes isn't officially working with FBX, there's little wonder aiMeshMorphAnim::mName is broken.

This should be closed. But maybe it should be someone from the dev team who can confirm this and then close the issue.

Also, aiMeshMorphAnim should be marked as "not working with FBX".

**Comment by kimkulling** [comment]
Answered!
