### ISSUE TITLE
Bug: 3ds export error

### ISSUE THREAD

**Issue by copycd** [assimp/assimp#4157]
**Describe the bug**
when i export my Scene-object to 3ds, ai_assert(false) occur error.
because aiShadingMode_PBR_BRDF of shading_mode is not processed.
so that I took care of it temporarily.

below line 320 in 3DSExporter.cpp

        if (mat.Get(AI_MATKEY_SHADING_MODEL, shading_mode) == AI_SUCCESS) {
            ChunkWriter chunk(writer, Discreet3DS::CHUNK_MAT_SHADING);

            Discreet3DS::shadetype3ds shading_mode_out;
            switch (shading_mode) {
            case aiShadingMode_Flat:
            case aiShadingMode_NoShading:
                shading_mode_out = Discreet3DS::Flat;
                break;

            case aiShadingMode_Gouraud:
            case aiShadingMode_Toon:
            case aiShadingMode_OrenNayar:
            case aiShadingMode_Minnaert:
                shading_mode_out = Discreet3DS::Gouraud;
                break;

            case aiShadingMode_Phong:
            case aiShadingMode_Blinn:
            case aiShadingMode_CookTorrance:
            case aiShadingMode_Fresnel:
            // I writed.
            case aiShadingMode_PBR_BRDF:
                shading_mode_out = Discreet3DS::Phong;
                break;

            default:
                shading_mode_out = Discreet3DS::Flat;
                ai_assert(false);
            };
            writer.PutU2(static_cast<uint16_t>(shading_mode_out));
        }

**Platform (please complete the following information):**
 - OS: [Windows 10 pro]
 - Browser [chrome]

**Additional context**

**Comment by RichardTea** [comment]
Thanks for the report. Your fix looks to be the bext option for now.
In theory a "high" Metalness probably ought to be exported Discreet3DS::Metal, however I've not found any documentation about the 3DS "metal" type.
Given how obsolete this proprietary format is, it's highly unlikely anyone will ever reverse-engineer that part if it wasn't done back in the late 1990's...
