### ISSUE TITLE
Bug: Assimp 5.1.rc1 has version set to 5.0.1

### ISSUE THREAD

**Issue by abenedik** [assimp/assimp#4161]
The Release candidate of the new Assimp version still has the version set to 5.0.1.
This prevents .Net, Python and other wrappers of the Assimp library to know that this version uses new struct layouts (see https://github.com/assimp/assimp/issues/3948)

It seems to me that the only thing to fix this is to update the version in CMakeLists.txt.
If you want I can create a PR for that.

**Comment by kimkulling** [comment]
Right, will fix that one. PR is on its way.

**Comment by krop** [comment]
https://github.com/assimp/assimp/blob/master/CMakeLists.txt#L59 wasn't updated for the 5.1.1 and .2 releases
