### ISSUE TITLE
Bug: X3D importer CanRead returns true for virtually all files

### ISSUE THREAD

**Issue by pezcode** [assimp/assimp#4177]
`X3DImporter::CanRead` uses `pFile.find_last_of(".x3d")` which returns an offset for if *any* of those characters is in the string. This means virtually all files with a dot in the name and all memory files (`$$$___magic___$$$.<hint>`) are recognized as X3D.

This was changed in https://github.com/assimp/assimp/pull/2966. The previous behaviour looks to be correct.

This by itself wouldn't be quite that tragic, but invalid X3D files lead to an assert in `X3DImporter::InternReadFile` because `.front()` is called on an empty `NodeElement_List`.

**Comment by umlaeute** [comment]
as mentioned in #4201, the `CanRead` method if thee X3DImporter does a bogus file extension check.
instead it should look like:

~~~C++
bool X3DImporter::CanRead(const std::string &pFile, IOSystem * /*pIOHandler*/, bool checkSig) const {
    if (checkSig) {
        std::string::size_type pos = pFile.rfind(".");
        if (pos != std::string::npos) {
            std::string ext=pFile.substr(pos+1);
            if ("x3d" == ext)
                return true;
        }
    }

    return false;
}
~~~

while this makes the X3DImporter at least reject files that don't have the `.x3d` extension, it still crashes on the X3D-models in the test/ folder
