### ISSUE TITLE
Bug: wrong glTF skinned attribute names

### ISSUE THREAD

**Issue by pezcode** [assimp/assimp#4178]
Assimp tries to import glTF skinning mesh attributes by the wrong names: [`"JOINT"` and `"WEIGHT"`](https://github.com/assimp/assimp/blob/05115b07b4d7ca12a52b9fd0e0534029ac8f2cb6/code/AssetLib/glTF2/glTF2Asset.inl#L181) rather than the [correct `"JOINTS"` and `"WEIGHTS"`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#skinned-mesh-attributes).

This kinda works with a single set of indices and weights, but once you have 2+ sets it breaks. With Assimp 5.0 it only imported the second set, but with 5.1. it's actually failing to import the file because of additional checks:

> GLTF: Invalid attribute in mesh: Mesh primitive: 0attrib: JOINTS_1. All indices for indexed attribute semantics must start with 0 and be continuous positive integers: TEXCOORD_0, TEXCOORD_1, etc.

What's happening is that [this piece of code](https://github.com/assimp/assimp/blob/05115b07b4d7ca12a52b9fd0e0534029ac8f2cb6/code/AssetLib/glTF2/glTF2Asset.inl#L1369) always determines the index to be 0 because it finds `"JOINT"` but expects an underscore right after and only gets `'S'`.

**To Reproduce**
1. Import https://github.com/mosra/magnum-plugins/blob/master/src/MagnumPlugins/AssimpImporter/Test/skin-multiple-sets.gltf
2. Be greeted with an error in 5.1.0, or the wrong (ie. always the last set of) bone indices/weights in 5.0.1

**Comment by philipguin** [comment]
I believe I'm also encountering this issue. Can't import a skinned model exported from Blender, don't think I'm doing anything too fancy.

Relevant assimp log output:
```
Info,  T15008: Load E:\Documents\Blender\Naomi.gltf
Debug, T15008: Assimp 5.1.1232036505 amd64 msvc shared singlethreadedsingle : 
Debug, T15008: Loading GLTF2 asset
Debug, T15008: Parsing GLTF2 JSON
Info,  T15008: Found a matching importer for this file format: glTF2 Importer.
Info,  T15008: Import root directory is 'E:\Documents\Blender\'
Debug, T15008: Reading GLTF2 file
Debug, T15008: Loading GLTF2 asset
Debug, T15008: Parsing GLTF2 JSON
Error, T15008: GLTF: Invalid attribute in mesh: Belt primitive: 0attrib: JOINTS_1. All indices for indexed attribute semantics must start with 0 and be continuous positive integers: TEXCOORD_0, TEXCOORD_1, etc.
```

The GLTF2 primitives in question (which appear to be correct):
```JSON
...
    "meshes" : [
        {
            "name" : "Belt",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2,
                        "JOINTS_0" : 3,
                        "WEIGHTS_0" : 4,
                        "JOINTS_1" : 5,
                        "WEIGHTS_1" : 6
                    },
                    "indices" : 7,
                    "material" : 0
                },
                {
                    "attributes" : {
                        "POSITION" : 8,
                        "NORMAL" : 9,
                        "TEXCOORD_0" : 10,
                        "JOINTS_0" : 11,
                        "WEIGHTS_0" : 12,
                        "JOINTS_1" : 13,
                        "WEIGHTS_1" : 14
                    },
                    "indices" : 15,
                    "material" : 1
                }
            ]
        },
...
```
