### ISSUE TITLE
Please add to the documentation how to run tests

### ISSUE THREAD

**Issue by yurivict** [assimp/assimp#4182]
Section ```Build from source``` in [Build.md](https://github.com/assimp/assimp/blob/master/Build.md) should have an example how to run tests after build.

The ```test``` target doesn't exist:
```ninja: error: unknown target 'test', did you mean 'help'?```

It would be best if tests would be run through make's target.

**Comment by kimkulling** [comment]
You can just navigate to the bin-folder and execute:

`./unit`

**Comment by kimkulling** [comment]
Deprecated.
