### ISSUE TITLE
a library should not call 'exit()'

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#4188]
it seems that contrib/Open3DGC/o3dgcArithmeticCodec.cpp will terminate the host program under some conditions, by calling `exit()`: https://github.com/assimp/assimp/blob/3db1592f7e92481426a4879d25401143e790f506/contrib/Open3DGC/o3dgcArithmeticCodec.cpp#L95-L102

typically, a host application wants to get notified of problems/errors/... so it can react appropriately.
forcing the application to shut down (without letting the application itself chose), is really rude behaviour.

**Comment by dossalab** [comment]
I believe this is related to Open3DGC library

**Comment by umlaeute** [comment]
could you elaborate?

**Comment by dossalab** [comment]
I'm not that familiar with Assimp development, but it seems like 'contrib/' directory contains sources of a couple 3rd party libraries (I guess to simplify compilation on Windows or something like that). So I think if you found an issue in one of those libraries you should notify its developers and fix it upstream.

UPD: Actually their repository looks quite abandoned (https://github.com/rbsheth/Open3DGC). So may be Assimp team maintains this library now. Better wait until someone from the actual developers will answer...

**Comment by kimkulling** [comment]
This is an external lib from goole. So we will not be able to fix that one.

**Comment by umlaeute** [comment]
> This is an external lib from Google. So we will not be able to fix that one.

if it is, could this be documented? esp. where the library originates from. because then i could file a bug-report with upstream.

in general i think the vendored libraries should be documented in a more formalized way (e.g. in `contrib/README.md`):
- where they were obtained from
- which version (or commitish)
- whether there were assimp-specific changes
- how to update the libraries
