### ISSUE TITLE
IMAGE1.bmp is really a JPEG

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#4189]
the https://github.com/assimp/assimp/blob/master/test/models/3DS/IMAGE1.bmp file is really a JPEG file.

it might be that this is intentional, in order to test images with wrong extensions (there are other files in this directory that match `*.jpg` or `*.png`, and *these* are actually invalid image files). in this case, i think it would be good to have a README that explains this.

**Comment by kimkulling** [comment]
That was deprecated test-data. I have removed it with this PR: https://github.com/assimp/assimp/pull/4212

Thanks a lot for your investigations to find this bug!
