### ISSUE TITLE
Question: How to force using IFC 4 in ifc loader

### ISSUE THREAD

**Issue by arturred** [assimp/assimp#4194]
Hi
Still having problems with opening ifc 4 files (my reported issues) I checked the sources of IFCLoader and found that only Schema_2x3::GetSchema(schema) is used. The assimp/code/AssetLib/IFC/ directory contains MACHINE-GENERATED code of IFCReaderGen2_2x3 and IFCReaderGen_4 classes. But only 2x3 is referenced. Is it possible to switch the schema and support IFC4 files? The files are generated but not used? How to fix this problem? I'm not familiar with the assimp architecture.

Regards
Artur

**Comment by kimkulling** [comment]
Hi,

we need to implement IFC5 files. UNfortunately, this is a really big task to do. So if you are interested in this you can try to implement this and I can help a little bit.

Kim
