### ISSUE TITLE
Add support for XNALara/XPS Models and MMD MikumikuDance

### ISSUE THREAD

**Issue by justanotherbug** [assimp/assimp#420]
I would like to see support for this 2 types of model 

This is a link XnaPosingStudio is a "XNA Model Viewer" and 3D posing software based on 
(and compatible to) XNALara
http://xnalaraitalia.deviantart.com/journal/XPS-10-9-8-7-6-5-4-3-2-1-0-Countdown-Preview-435451774

Opensourced Mac Os Xps Model viewer GGLara 
Currently broken in Mac OS 10.10 :-(
https://github.com/cochrane/GLLara

Blender Script for importing/exporting 
XNALara/XPS Mesh (.ascii/.mesh/.xps)
http://johnzero7.deviantart.com/journal/Blender-2-7-XPS-Tools-475948475

And also for MikuMikuDance Models
https://github.com/hkrn/MMDAI

Thank you guys for being the engine inside the android app HD Model Viewer!
 I email him this request a few months ago and is busy and can't work on this.

**Comment by acgessler** [comment]
Closing. I believe these are too rarely used to be worth the effort.

Contributions always appreciated though :-)

**Comment by cra0zy** [comment]
.xnb is compiled 3d model content for XNA / MonoGame(they are game frameworks). Unless you are taking content form a game, it's not gonna be in this format.

mmd(.pmd .pmx .vmd) is Japanese 3D anime model and animation format.
example: http://digitrevx.deviantart.com/art/BRS-MMD-model-by-Digitrevx-418311172
blender addon: https://github.com/sugiany/blender_mmd_tools/blob/master/README_en.md)

**Comment by justanotherbug** [comment]
The homepage for xnalara for the pc is here.
http://xnalaraitalia.deviantart.com/
the file name for models "Generic_Item.mesh"

New file format details here
http://junkymana.deviantart.com/journal/New-and-improved-format-for-XNALara-XPS-532612489

sample model
http://junkymana.deviantart.com/art/Layla-396930294

Open source version on the mac for this file format
https://github.com/cochrane/GLLara/
