### ISSUE TITLE
Android NDK: "Use of undeclared identifier 'Assimp'

### ISSUE THREAD

**Issue by agGitHub** [assimp/assimp#4202]
Hi,

I compiled Assimp with cmake in order to get the .so libs. I added these libs to my project, and updated my CMakeLists.txt file.

When I tadd the following lines of code to my native-lib.cpp file (these lines come from [here](https://github.com/assimp/assimp/blob/master/port/AndroidJNI/README.md)):

```
#include <assimp/port/AndroidJNI/AndroidJNIIOSystem.h>

Assimp::Importer* importer = new Assimp::Importer();
Assimp::AndroidJNIIOSystem *ioSystem = new Assimp::AndroidJNIIOSystem(app->activity);
if ( nullptr != iosSystem ) {
  importer->SetIOHandler(ioSystem);
}  
```

I get the following errors:
```
Use of undeclared identifier 'Assimp'
Unknown type name 'AndroidJNIIOSystem'
Use of undeclared identifier 'iosSystem'; did you mean 'system'?
```

Do you see how to solve these problems ?

Thanks

**Comment by RichardTea** [comment]
Probably best to ask this kind of thing on the Gitter

**Comment by kimkulling** [comment]
You need to include the Importer-Interface as well:

`#include <assimp/Importer.hpp>`
