### ISSUE TITLE
The new Assimp library do not work correctly on iOS project

### ISSUE THREAD

**Issue by HaraldBregu** [assimp/assimp#422]
How is that possible, i have the old version that work fine but it don't have FBX parser

I have this issue in the console when i run the app:

For FBX file
FBX-Parser (TOK_DATA, offset 0xe93f64) failed to parse ID, unexpected data type, expected L(ong) (binary)

For Collada file
Collada: File came out empty. Something is wrong here.

Does anyone know the reason of this problem?

**Comment by kimkulling** [comment]
Shall work now.
