### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#4221]
**Describe the bug**
 FBX loader seems to be somewhat broken. At least in the aiAnimation::mTicksPerSecond part... I will take a closer look but maybe there are any hints? Yeah, the FBX importer is definitely broken. I'm parsing https://developer.nvidia.com/orca/amazon-lumberyard-bistro I'm getting `aiAnimation::mDuration == 100000` and `aiAnimation::mTicksPerSecond == 24` which yields 4166 seconds of duration.

**To Reproduce**
N/A

**Expected behavior**
Save behaviour as before

**Platform (please complete the following information):**
All

**Comment by philipguin** [comment]
I believe this is identical to issues #4197 and #4206

**Comment by inhosens** [comment]
I'm sorry. b3e1ee3 should be reverted for the correct animation. In my side, I didn't care mticksPerSecond before.

**Comment by jankrassnigg** [comment]
Lol, I came here to report exactly this bug. Saw a weird "Bug:" bugticket and it fits exactly my problem! :D

Maybe you should rename the bugticket ;-)

For reference, I was trying out these animated meshes:
https://quaternius.com/packs/animatedmech.html

**Comment by inhosens** [comment]
Okay. I looked it through more. I think assimp's anim mTime is not #real time vlaue, but   ###a virtual ticks similar to frames. Let's revert the previous one. #4247

**Comment by kimkulling** [comment]
Shall be fixed by: https://github.com/assimp/assimp/pull/4247 Just reopen if this is still there.
