### ISSUE TITLE
There is no documentation on how to reduce the size of the static library

### ISSUE THREAD

**Issue by enci** [assimp/assimp#424]
I built the iOS version of assimp (using the /port/iOS/build.sh script) into a static fat library, but I was't expecting 128MB of fat. It has arm7, arm7, arm7s, x86_64 and i386 slices architectures, but that's still rather large. FreeType is about 2.2 MB with the same architecture slices for example.

I only need 2-3 formats out of the 40+ supported. I can't find in the documentation where the ASSIMP_BUILD_NO_<IMPORTER> should be defined and whether that will in fact reduce the size of the lib.

**Comment by mcela** [comment]
This is an old ass issue, but first in the google results, so might as well save people a few minutes of reading the `CMakeLists.txt` file. These are the cmake commands at the moment:

`cmake CMakelists.txt -DASSIMP_NO_EXPORT=ON -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_BLEND_IMPORTER=ON -DASSIMP_BUILD_FBX_IMPORTER=ON`

So `-DASSIMP_BUILD_XXXYYYZZZ_IMPORTER=ON` is what you're looking for. The list is in `CMakeLists.txt`, CTRL+F for `ADD_ASSIMP_IMPORTER`.

Btw, on linux, the default build was 133mb. Got it down to 33mb with these, and to 20mb with FBX only (which are still unfortunately huge though).
