### ISSUE TITLE
Assimp 5.1.3 fails to build with the double precision option selected.

### ISSUE THREAD

**Issue by mapaton** [assimp/assimp#4248]
Good day,

I was using CMake to build the latest 5.1.3 version on Windows 64bit (VS2017) and I found that if in CMake I choose the ASSIMP_DOUBLE_PRECISION option then try and build the library it will fail to compile the glTF2Exporter.cpp due to a float/double mismatch. See the attached compiler image for reference.

A simple work-a-round is not to compile this exporter but hopefully this is a fairly easy fix.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/24330741/145531693-198c39d8-c926-425a-bbcf-7bbc184471f6.png">

Actually further testing found another double precision compilation problem in the X3DImporter_Geometry3D.cpp:

void X3DImporter::readSphere(XmlNode &node) {
    std::string use, def;
    ai_real radius = 1;
    bool solid = true;
    X3DNodeElementBase *ne(nullptr);

    MACRO_ATTRREAD_CHECKUSEDEF_RET(node, def, use);
    XmlParser::getFloatAttribute(node, "radius", radius);
    XmlParser::getBoolAttribute(node, "solid", solid);

Note the radius in XmlParser::getFloatAttribute(node, "radius", radius)  is a double and it wants a float.  

Talk to you later,
     Mark

**Comment by PencilAmazing** [comment]
This can be fixed with a simple signature change (`float`->`ai_real`) and using the appropriate float/double readers. Problem is, that breaks a lot of tests (and who knows what else) that expect `ai_real` to be 4 bytes.

**Comment by kimkulling** [comment]
This issue is fixed.
