### ISSUE TITLE
Bug: likely m3d build error with ASSIMP_BUILD_NO_EXPORT

### ISSUE THREAD

**Issue by Garux** [assimp/assimp#4262]
M3DImporter uses M3DWrapper:
https://github.com/assimp/assimp/blob/master/code/AssetLib/M3D/M3DImporter.cpp#L190
which is disabled with ASSIMP_BUILD_NO_EXPORT:
https://github.com/assimp/assimp/blob/master/code/AssetLib/M3D/M3DWrapper.h#L51
as well as required `m3d.h` inclusion.

**Comment by kimkulling** [comment]
Sorry, which kind of issue do you see? Some output from you compiler for instance?

**Comment by Garux** [comment]
```
M3DImporter.cpp: In member function 'virtual void Assimp::M3DImporter::InternReadFile(const string&, aiScene*, Assimp::IOSystem*)':
M3DImporter.cpp:190:20: error: variable 'Assimp::M3DWrapper m3d' has initializer but incomplete type
  190 |     M3DWrapper m3d(pIOHandler, buffer);
  ```
To clarify, it's not build system of assimp used, but issue looks quite apparent for me.
So if you enable M3D and disable exporters, build must fail.

**Comment by kimkulling** [comment]
Ok, thanks a lot for the cloarification. Which version do you use? 5.1.x?

**Comment by Garux** [comment]
Using master branch of this repo.

**Comment by krishty** [comment]
This would be fixed by https://github.com/assimp/assimp/pull/4879
