### ISSUE TITLE
Bug: C API macro broken

### ISSUE THREAD

**Issue by Bubuche87** [assimp/assimp#4270]
I wrote the following text offline. Also English is not my mother tongue so there will be mistakes and grammatical errors. 

I think I found a bug in the C API. 
Version assimp-5.0.1
File material.h
Line 1443
The bug: a space between aiGetMaterialFloat and "("

This lead to my compiler understanding that macro as being the text after the space instead of  what it should be, the parameters of the macro.

Solution: remove the space.

P.s. my compiler is gcc 6.3.0 20170406

Ok, after I remove the space, I got another error: the gcc is complaining that the macro expects 5 parameters and I am only giving 3. 
I understand why: I am trying to port the obj exporter to C (and after that I'll modify it). 
And in the code they use macros such as AI_MATKEY_OPACITY, which is itself three parameters disguised as one. 
During the compilation this single parameter transforms itself into 3 parameters so the compiler does not complain for the other functions using the same mechanism. 
However, in this specific case, aiGetMaterialFloat is a macro, so the Pre-Processor (I emphase this: the Pre-Processor, not the compiler) complains about a wrong number of argument for the macro. 

The solution: don't make aiGetMaterialFloat a macro but a static inline function.

**Comment by kimkulling** [comment]
Hi, please update to the latest release 5.1.4. We have fixed this issue a while ago. 

If you still see the broken behavior in the C-API you can reopen this ticket for tracking.
