### ISSUE TITLE
undefined reference to `Assimp::Importer::~Importer()'

### ISSUE THREAD

**Issue by hiwoshixiaoyu** [assimp/assimp#4277]
I  complie on win10 .cmake + minggw9.0.0

I used it has some error
undefined reference to `Assimp::Importer::~Importer()

**Comment by kimkulling** [comment]
Which version have you tried?

**Comment by kimkulling** [comment]
This one shall be fixed in the latest bugfix release. As far as I know, the export statement for the mingw was missing. PLease reopen the issue if you still have the expected issue.
