### ISSUE TITLE
Please provide sane C API access to matrices and vectors in Assimp 4.0

### ISSUE THREAD

**Issue by devurandom** [assimp/assimp#43]
Currently aiVector3D stores its data as ```{float x,y,z;}```. This is a little bit inconvenient, but acceptable. However, aiMatrix4x4 is stored as ```{	float a1,a2,a3,a4,b1,b2,b3,b4,c1,c2,c3,c4,d1,d2,d3,d4;}```, which is just ridiculous...

Please, please, please make that a float[3] and a float[4*4] and instead provide an indexing macro like ```#define AI_M4X4(m,i,j) (m[(i)*4+(j)])```, because it leads to insane code like devurandom/lua-assimp@e2d2194092115098d304ad987c38a509a134deba.

**Comment by devurandom** [comment]
Thanks for that commit! But I think you forgot the vectors and colours?

**Comment by kimkulling** [comment]
Just pushed :-). Thanks for the hint!
