### ISSUE TITLE
Normals maps actually laoded as height maps

### ISSUE THREAD

**Issue by jose-villegas** [assimp/assimp#430]
I'm loading this model and assimp loads the bump map as a height map
https://dl.dropboxusercontent.com/u/5693654/cube.7z

Yet in the documentation it says this about height maps

<pre>
aiTextureType_HEIGHT 	
The texture is a height map.
By convention, higher gray-scale values stand for higher elevations from the base height.
</pre>

Is this the correct behavior (if not then, is there any work around?) ? Should I treat height maps as normal maps? What's the correct value for height maps then?

**Comment by acgessler** [comment]
Oftentimes importers cannot tell whether the texture being imported is actually a height vs a normal map. Oftentimes formats do not specify this (OBJ for example does not, at least not in common use).

The original distinction drawn by the materials API is thus kind of obsolete. If you have control over your art/content pipeline, establish some convention for textures and ignore the type hint (i.e. treat both equally). If you have to deal with arbitrary inputs, consider guessing by looking at the pixels and see if they're all grayscale :-)

A similar issue is with object space normal maps vs. tangent space normal maps. Luckily, the former are used so rarely.
