### ISSUE TITLE
Code comment on with aiMetadata::mValues not correct.

### ISSUE THREAD

**Issue by tomazos** [assimp/assimp#4325]
The comment above `aiMetadata::mValues` says:

```
    struct aiMetadata {

        /** Arrays of values, may not be NULL. Entries in this array may be NULL if the
          * corresponding property key has no assigned value. */
        C_STRUCT aiMetadataEntry *mValues;

```

Entries in this array are not pointers.  The entries have class type `aiMetadataEntry`.  So entries cannot be `NULL`.

Is the intention that the statement "Entries in this array may be `NULL`" refer to the `mData` member of `aiMetadataEntry` ?

If so, I don't see by what code path that the `mData` entry can be `NULL`.  Also `aiMetadata::Get` does not test for `mData` being `NULL`:

```
    template <typename T>
    inline bool Get(unsigned index, T &value) const {
        if (index >= mNumProperties) {
            return false;
        }

        if (GetAiType(value) != mValues[index].mType) {
            return false;
        }

        value = *static_cast<T *>(mValues[index].mData);

        return true;
    }

```

`Get` seems to unconditionally dereference `mData` and doesn't test it for `NULL`.  If the intention is that the API user should test for `mData` being `NULL` prior to calling `Get`, this would be a rather odd interface.

**Comment by RichardTea** [comment]
The `mValues` member itself is not permitted to be NULL, it must be an array of size `mNumProperties`

**Comment by kimkulling** [comment]
There are checks within the getters if the number of properties is less than the number of allocated instances.
