### ISSUE TITLE
gtest build does not work with mingw

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#433]
See the build output:
In file included from D:/projects/assimp/test/gtest/src/gtest/include/gtest/internal/gtest-internal.h:40:0,
                 from D:/projects/assimp/test/gtest/src/gtest/include/gtest/gtest.h:58,
                 from D:\projects\assimp\test\gtest\src\gtest\src\gtest-all.cc:39:
D:/projects/assimp/test/gtest/src/gtest/include/gtest/internal/gtest-port.h: In function 'void testing::internal::SleepMilliseconds(int)':
D:/projects/assimp/test/gtest/src/gtest/include/gtest/internal/gtest-port.h:1453:24: error: 'nanosleep' was not declared in this scope
   nanosleep(&time, NULL);
                        ^
D:/projects/assimp/test/gtest/src/gtest/include/gtest/internal/gtest-port.h: At global scope:
D:/projects/assimp/test/gtest/src/gtest/include/gtest/internal/gtest-port.h:1775:3: error: 'AutoHandle' does not name a type
   AutoHandle thread_;
   ^
In file included from D:\projects\assimp\test\gtest\src\gtest\src\gtest-all.cc:42:0:
D:/projects/assimp/test/gtest/src/gtest/src/gtest.cc: In function 'std::string testing::internal::FormatEpochTimeInMillisAsIso8601(testing::internal::TimeInMillis)':
D:/projects/assimp/test/gtest/src/gtest/src/gtest.cc:3515:41: error: 'localtime_r' was not declared in this scope
   if (localtime_r(&seconds, &time_struct) == NULL)
                                         ^
In file included from D:\projects\assimp\test\gtest\src\gtest\src\gtest-all.cc:43:0:
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc: At global scope:
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:626:3: error: 'AutoHandle' does not name a type
   AutoHandle write_handle_;
   ^
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:628:3: error: 'AutoHandle' does not name a type
   AutoHandle child_handle_;
   ^
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:633:3: error: 'AutoHandle' does not name a type
   AutoHandle event_handle_;
   ^
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc: In member function 'virtual int testing::internal::WindowsDeathTest::Wait()':
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:645:36: error: 'child_handle_' was not declared in this scope
   const HANDLE wait_handles[2] = { child_handle_.Get(), event_handle_.Get() };
                                    ^
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:645:57: error: 'event_handle_' was not declared in this scope
   const HANDLE wait_handles[2] = { child_handle_.Get(), event_handle_.Get() };
                                                         ^
D:/projects/assimp/test/gtest/src/gtest/src/gtest-death-test.cc:659:3: error: 'write_handle_' was not declared in this scope
   write_handle_.Reset();

**Comment by jdduke** [comment]
Which compiler (and MinGW distribution, if known)? I've tested with MinGW before and it seemed to work (GCC 4.9 if I recall correctly).

**Comment by kimkulling** [comment]
I tried mingw.4.8.1 with windows8.1 and II got the descriped error.

**Comment by jdduke** [comment]
Which MinGW distribution? i'm using the MinGW-w64 distribution from here: http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.1/threads-posix/sjlj/. I wonder if non-posix threading MinGW builds don't support nanosleep?

**Comment by kimkulling** [comment]
fixed.

**Comment by grashwandir** [comment]
how?????

**Comment by kimkulling** [comment]
It worked for me when I tested it last.

**Comment by grashwandir** [comment]
It works now. Gtest must have pthread disabled with mingw32 (it seems POSIX implementation is incomplete...), but maybe works with mingw64.

**Comment by kimkulling** [comment]
You are right. You must have disable the pthread support first. Sorry, I forgot that.
