### ISSUE TITLE
Please include precompiled binaries in releases

### ISSUE THREAD

**Issue by Toxic-Cookie** [assimp/assimp#4356]
**Is your feature request related to a problem? Please describe.**
It's frustrating having to build the binaries needed manually instead of just having them prebuilt and ready to use. Assimp64.dll specifically.

**Describe the solution you'd like**
The binaries to be prebuilt and available in releases.

**Describe alternatives you've considered**
I've tried to build Assimp64.dll myself but all I get is the following after having followed every step perfectly:
![image](https://user-images.githubusercontent.com/66691163/150909107-b53ba9c1-afc7-4f54-80a8-d665fd5f1f7f.png)

**Additional context**
Most Github repos do not force you to build the binaries from source. I'm appalled that I have to with this one.

**Comment by RichardTea** [comment]
It's very clear from the output that you've omitted some steps, unfortunately there's not enough information to tell which step(s).

Which compiler are you using?

assimp supports building using multiple different toolchains and versions of those compilers.

The Windows C++ dlls are (by default) named along the lines of "assimp-vc143-mt.dll", where the middle section specifies which toolchain was used for the build (vc143 means MSVC 2022) and the "mt/mtd" suffix indicates release or debug.

The application _and_ assimp must both be compiled using compatible toolchains. If not, your application **will** crash. Also, while (eg) MSVC 2017 and MSVC 2019 are ABI compatible, you still need the newer (MSVC 2019) redists installed for that to work. If you've only got the MSVC 2017 redist, your application will crash when it tries to load assimp_v142_mt.dll.

While assimp could provide some binaries for releases, it would have to be a very limited subset. Which specific Windows toolchain do you require?

**Comment by arturred** [comment]
Hi, I would be happy to get MSVC 2017 x86 and x64 binary releases. I'm tracing vcpkg and issue https://github.com/microsoft/vcpkg/pull/22993 but they also have problems building assimp.

**Comment by kimkulling** [comment]
I will not be able to fulfill this request with the time which is currently available.
