### ISSUE TITLE
Bug: v5.2.0 has a version number 5.2.0 without 'v'

### ISSUE THREAD

**Issue by wdconinc** [assimp/assimp#4357]
See also https://github.com/assimp/assimp/issues/4322 and https://github.com/assimp/assimp/tags

![image](https://user-images.githubusercontent.com/4656391/150910418-e6e182ba-3818-40e4-852a-1a6ec71e1061.png)

**Comment by andrewmcdonald-oxb** [comment]
This will cause problems when fetching revisions for our internal Conan packaging system, so it'd be great if this could be made consistent.

**Comment by wdconinc** [comment]
Same reason here: external package manager (spack).

**Comment by kimkulling** [comment]
Fixed by https://github.com/assimp/assimp/releases/tag/v5.2.1 

Sorry for the bug.
