### ISSUE TITLE
Question/Bug?: What is the mTransformation matrix supposed to store when a node represents a bone?

### ISSUE THREAD

**Issue by The0Dev** [assimp/assimp#4364]
In some sources, it's stated that the mTransformation matrix stores a local bone transformation in a bind pose. However, I found out that sometimes it stores any transformation (set by an animation)  that a bone has at the time of exporting. Is this the intended behavior (and if so is there a reason for that)?

**To Reproduce**
Export any rigged and animated mesh as .fbx from Blender

**Comment by pezcode** [comment]
`mTransformation` is just the bone's local transformation and is affected by animations. What you're probably looking for is `aiBone::mOffsetMatrix` which transforms from bind pose to local bone space.

**Comment by The0Dev** [comment]
I'm aware of aiBone::mOffsetMatrix and implemented skeletal animation with Assimp. However, I was looking for a way to get a bone's original local transformation in its bind pose. I just find it a little strange that aiNode::mTransformation is influenced by animations since if needed it's possible to calculate the same matrix transformation using aiNodeAnim structures.

**Comment by pezcode** [comment]
Is `mTransformation` actually needed if the bone transformation is animation driven? I would think that's just an artifact of the Blender exporter.

**Comment by kimkulling** [comment]
When calculation the offset matrices all transformation matrices from the several bones from the input are used. So during the import process we are having this information.

Maybe a solution could be to add an option to keep this data after the import was done.

**Comment by The0Dev** [comment]
That would be great

**Comment by kimkulling** [comment]
I am working on a new proposal to support skeletal animations. The idea will be that we will separate the animation data from the meshes. Why? Because sometimes you need to have bones without any references vertices by them. At the moment these bones will be removed by our post-processing.

By introducing this I will also add the local transformation for each bone parallel to their offset matrix.

**Comment by kimkulling** [comment]
Please follow https://github.com/assimp/assimp/issues/4015 if you are interesting in learning more.
