### ISSUE TITLE
Bug: Problem when loading .assbin meshes (no animation)

### ISSUE THREAD

**Issue by wbyates777** [assimp/assimp#4365]
When loading .assbin file (generated with this or older version  of assimp library)

ERROR::ASSIMP:: Unexpected EOF 

Was working fine with assimp @5.0.1_1 on macos Monterey 12.2

**Comment by umlaeute** [comment]
please provide a title for the bug-report (`Bug:` is not really helpful)

**Comment by wbyates777** [comment]
I did try to add a title when I submitted the issue.

I have had another go just now but…..

https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner <https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner>

I’m not a contributor so I can’t.

My title would have been

‘“problem loading .assbin files”

regards

Bill

**Comment by umlaeute** [comment]
thanks for trying :-)

however, you do not need to put a `label`¹ on the issue, but change the `title`.
to do so:
1. locate the title line
    - it is just below the various github tabs
    - it reads `Bug: #4365`
    - on the right-hand side there should be two buttons: <kbd>Edit</kbd> and <kbd>New issue</kbd>
2. click on the <kbd>Edit</kbd> button
   - the title changes into an editable textfield with the content "`Bug:`"
3.  replace *Bug:* with something of your liking, e.g. `Bug: can no longer load .assbin files`

that's how it should work.
after you've managed to change the title, you might also want to *delete* your previous post (where you explained the problem with not being a contributor) by clicking on the `...` symbol on the right of the post and hit <kbd>Deleete</kbd>. i will then delete my comments as well (as they have nothing to do with the issue itself)

¹ `label`s are additional tags associated with a ticket. e.g. this ticket has the label [`bug`](https://github.com/assimp/assimp/labels/Bug) which is fine

**Comment by RichardTea** [comment]
Can you attach sample assbin files from 'previous' and 'this' version that show the issue, and specify which versions each is from?

**Comment by kimkulling** [comment]
This could be an issue caused by the migration to pugi-xml. Some background: I spend a lot of time to use pugixml instead of irrXml, which has caused a lot of security-issues in our code.
I would really apprechiate if you could provide a simple example which can be used to reproduce this issue.

**Comment by wbyates777** [comment]
I haven’t forgotten - I have a small example in mind - will post over the weekend - I’m at work at the moment.

**Comment by wbyates777** [comment]
Here is an .assbin file generated with assimp 5.0.1_1 - Ive tested it for loading in 5.0.1_1 and it works for me.
Now when I try loading this using assimp 5.2.0 i get the error 'ERROR::ASSIMP:: Unexpected EOF'
I have included the unit test output for 5.20 - some tests fail.
The .assbin file was generated using the flags
aiProcess_Triangulate             | 
                             aiProcess_FlipUVs                  | 
                           
[assimp.test.txt](https://github.com/assimp/assimp/files/8008434/assimp.test.txt)
  aiProcess_GenNormals               | 
                             aiProcess_JoinIdenticalVertices    | 
                             aiProcess_RemoveComponent          | 
                             aiProcess_FindInvalidData          | 
                             aiProcess_PreTransformVertices | 
                             aiProcess_FindInstances            | 
                             aiProcess_OptimizeGraph            | 
                             aiProcess_ImproveCacheLocality     | 
                             aiProcess_RemoveRedundantMaterials | 
                             aiProcess_SortByPType              |
                             aiProcess_CalcTangentSpace;


The object is a yellow sphere
[assimp_prob.zip](https://github.com/assimp/assimp/files/8008428/assimp_prob.zip)
.
Happy to provide more info on request.

**Comment by wbyates777** [comment]
Ive just downloaded assimp 5.2.2 - it won't build using ASSIMP_DOUBLE_PRECISION=ON
During config I get
-- Check size of off64_t
-- Check size of off64_t - failed
and the error
assimp-master/code/AssetLib/IFC/IFCOpenings.cpp:1479:20: error: non-constant-expression cannot be narrowed from type 'ai_real' (aka 'double') to 'float' in initializer list [-Wc++11-narrowing]

When double prec is OFF the framework builds and passes all but one unit test.

The example given in my initial bug report uses double prec ON - this might be the underlying cause of the error

**Comment by wbyates777** [comment]
This bug no longer occurs in 5.2.3 when using floats. I can load .assbin files generated by assimp 1.5.0 and  assimp 5.2.3.
As noted in a more recent issue #4468  the DOUBLE build fails. I was using double and this is what I think was causing my original issue.
