### ISSUE TITLE
Bug: DefaultIOStream::FileSize() broken on 32bit systems

### ISSUE THREAD

**Issue by flixr** [assimp/assimp#4390]
**Describe the bug**
`stat` can fail on 32bit systems if not compiled with `-D_FILE_OFFSET_BITS=64`.
That could be because inode number is too large (happens on many file systems) or the file itself is too large.

This was 
* originally reported in #975
* then fixed with https://github.com/assimp/assimp/commit/ec67a1f2eae7d343e1c56a8a47bf80fdce93474c
* then commented out again with https://github.com/assimp/assimp/commit/a8e65a1e8aff4a254453f26719df95f8cacdaadf
* and finally completely removed in https://github.com/assimp/assimp/commit/417c4fcb457ab8282e8698596cba2de99c604e92

I don't know why it was apparently removed because of Android builds (cmake check for android not working)?
But for 32bit armhf this is needed for sure.

**To Reproduce**
Try reading a file with assimp on armhf (or probably any other 32bit arch) which has a inode number not representable in 32bit.
E.g. from a NFS mount or XFS file system.

**Expected behavior**
`DefaultIOStream::FileSize()` returns correct size instead of 0.

**Platform (please complete the following information):**
 - OS: Linux/armhf

**Additional context**
Might be the (or at least one) cause for autopkgtests failing for 32bit archs:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995859

**Comment by kimkulling** [comment]
FuXXX, sorry for that. This bug was introduced by myself. The fix is on its way.

**Comment by kimkulling** [comment]
Shall be fixed now.

**Comment by flixr** [comment]
actually adding the definition is still commented out...
