### ISSUE TITLE
Bug: Import a specific FBX model with assimp 5.1.6/5.2.1 will freeze the app

### ISSUE THREAD

**Issue by jianliang79** [assimp/assimp#4395]
When importing a specific FBX model with assimp 5.1.6/5.2.1, assimp will never return from Importer::ReadFile(). After some investigation I found that it seems that there is a deadloop in FBXConverter::GetRotationKeyframeList().
    The FBX model which can reproduce this issue can be downloaded from the following link:
    https://drive.google.com/file/d/10FKfIoY22yRsZI2wTzKyzNMT7HATY6f4/view?usp=sharing

    BTW: Importing this FBX model with assimp 5.0.0 works well. This seems to be a regression of assimp 5.1.x +

**Comment by kimkulling** [comment]
Thanks for the report! I will check it!

**Comment by tippesi** [comment]
I can report the same issue with assimp 5.2.2

**Comment by kimkulling** [comment]
Hm, bad! Anyway, thanks for your testing ...

**Comment by jianliang79** [comment]
The following patch can fix this issue.

@@ -3326,9 +3326,9 @@ FBXConverter::KeyFrameListList FBXConverter::GetRotationKeyframeList(const std::
                 float vc = curve->GetValues().at(1);
                 for (size_t n = 1; n < count; n++) {
                     while (std::abs(vc - vp) >= 180.0f) {
-                        float step = std::floor(float(tc - tp) / (vc - vp) * 179.0f);
+                        double step = std::floor(double(tc - tp) / std::abs(vc - vp) * 179.0f);
                         int64_t tnew = tp + int64_t(step);
-                        float vnew = vp + (vc - vp) * step / float(tc - tp);
+                        float vnew = vp + (vc - vp) * float(step / (tc - tp));
                         if (tnew >= adj_start && tnew <= adj_stop) {
                             Keys->push_back(tnew);
                             Values->push_back(vnew);

**Comment by jianliang79** [comment]
The following patch can fix this issue:


@@ -3326,9 +3326,9 @@ FBXConverter::KeyFrameListList FBXConverter::GetRotationKeyframeList(const std::
                 float vc = curve->GetValues().at(1);
                 for (size_t n = 1; n < count; n++) {
                     while (std::abs(vc - vp) >= 180.0f) {
\-                        float step = std::floor(float(tc - tp) / (vc - vp) * 179.0f);
\+                        double step = std::floor(double(tc - tp) / std::abs(vc - vp) * 179.0f);
                         int64_t tnew = tp + int64_t(step);
\-                        float vnew = vp + (vc - vp) * step / float(tc - tp);
\+                        float vnew = vp + (vc - vp) * float(step / (tc - tp));
                         if (tnew >= adj_start && tnew <= adj_stop) {
                             Keys->push_back(tnew);
                             Values->push_back(vnew);

**Comment by KerayEU** [comment]
I would love to see this fix get incorporated into codebase. 2 of MIXAMO animations are causing assimp to freeze.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/4554
