### ISSUE TITLE
Q: How to build assimp_view ?

### ISSUE THREAD

**Issue by JCash** [assimp/assimp#4401]
Hi!
I'm on a mac, and I'm trying to build the viewer, but it seems it's not built.
According to the docs, the `ASSIMP_BUILD_ASSIMP_TOOLS` is ON by default.

Any ideas how to build this tool?

**Comment by kimkulling** [comment]
You can try to run this on something similar to Wine, which simulates a Windows-Environment for Unix-based Systems. I have just checked this and there are ways to run wine.
A second option would be to run the viewer in a Virtual Machine. I am currently working on a linux-based Viewer. Maybe this would help you in the near future?

**Comment by JCash** [comment]
Ok, thanks!
I think it would be good to output a log warning at build time that the target was skipped or something.

As for running on wine, that's usually working, however, the first step is _building_ the thing :)

Yeah, I think a cross platform viewer should work well, for the users (e.g using [sokol](https://github.com/floooh/sokol) plus DearImGui).

**Comment by JCash** [comment]
Hi again!
Sorry, I'm now trying to build the viewer on windows.
But, following your build instructions, I get no viewer.

Using
* Msys2 (MINGW32_NT-6.2)
* cmake version 3.22.2

```
cd assimp
cmake CMakeLists.txt 
cmake --build .
```

```
10:01:54 /c/repos/external/assimp (master) $ find . -iname "*.exe"
./bin/Debug/assimpd.exe
./bin/Debug/unit.exe
./CMakeFiles/3.22.2/CompilerIdC/CompilerIdC.exe
./CMakeFiles/3.22.2/CompilerIdCXX/CompilerIdCXX.exe
```

**Comment by kimkulling** [comment]
You need to enable the ASSIMP_BUILD_ASSIMP_TOOLS flag:

`cmake CMakeLists.txt -DASSIMP_BUILD_ASSIMP_TOOLS =ON`

If this is not supported there will be a message. And please make sure that you have installed DX9.0. A new tool will come!
