### ISSUE TITLE
Invalid `AI_TEXTURE_TYPE_MAX` value

### ISSUE THREAD

**Issue by camden-smallwood** [assimp/assimp#4404]
**Describe the technical debt**

The `AI_TEXTURE_TYPE_MAX` macro constant is defined as an explicit alias for `aiTextureType_UNKNOWN` at [`include/assimp/material.h#L334`](https://github.com/assimp/assimp/blob/v5.2.2/include/assimp/material.h#L334), which has a constant value of `18`.

The `aiTextureType_SHEEN`, `aiTextureType_CLEARCOAT` and `aiTextureType_TRANSMISSION` enum values were added after the `aiTextureType_UNKNOWN` enum value in commit [`4a66ec25d0371f694e3aa41f3a0996c24a606651`](https://github.com/assimp/assimp/commit/4a66ec25d0371f694e3aa41f3a0996c24a606651#diff-623ebb07cd554a8797f3ea368460176a419e0182fc8049b05b7110737bee98fd).

While the `aiTextureType_UNKNOWN` variant is declared at the end of the `aiTextureType` enum at [`include/assimp/material.h#L327`](https://github.com/assimp/assimp/blob/v5.2.2/include/assimp/material.h#L327), the explicit value of `aiTextureType_UNKNOWN` (`18`) is lower than the explicit values of `aiTextureType_SHEEN` (`19`), `aiTextureType_CLEARCOAT` (`20`) and `aiTextureType_TRANSMISSION` (`21`), which prevents them from falling within a valid range of `aiTextureType` values when utilizing the `AI_TEXTURE_TYPE_MAX` constant.

Example:
```cpp
constexpr bool valid_texture_type(int value)
{
    return value >= 0 && value <= AI_TEXTURE_TYPE_MAX;
}

static_assert(valid_texture_type(aiTextureType_UNKNOWN)); // compiles
static_assert(valid_texture_type(aiTextureType_SHEEN)); // fails to compile
```

**Better solution**

Either A or B:

A.) Update the definition of the `AI_TEXTURE_TYPE_MAX` constant to be the last member of the `aiTextureType` enum, which is currently `aiTextureType_TRANSMISSION`:

```cpp
#define AI_TEXTURE_TYPE_MAX aiTextureType_TRANSMISSION
```

B.) Since the values of C and C++ enum variants implicitly start at `0` and increment by `1`, consider removing the explicit values from the variants of the `aiTextureType` enum altogether, or at least from the `aiTextureType_UNKNOWN` variant at a minimum. This will allow the `AI_TEXTURE_TYPE_MAX` constant to remain valid for future additions or redactions to the `aiTextureType` enum.

Example:
```cpp
enum aiTextureType {
    aiTextureType_NONE,
    aiTextureType_DIFFUSE,
    aiTextureType_SPECULAR,
    aiTextureType_AMBIENT,
    aiTextureType_EMISSIVE,
    aiTextureType_HEIGHT,
    aiTextureType_NORMALS,
    aiTextureType_SHININESS,
    aiTextureType_OPACITY,
    aiTextureType_DISPLACEMENT,
    aiTextureType_LIGHTMAP,
    aiTextureType_REFLECTION,
    aiTextureType_BASE_COLOR,
    aiTextureType_NORMAL_CAMERA,
    aiTextureType_EMISSION_COLOR,
    aiTextureType_METALNESS,
    aiTextureType_DIFFUSE_ROUGHNESS,
    aiTextureType_AMBIENT_OCCLUSION,
    aiTextureType_SHEEN,
    aiTextureType_CLEARCOAT,
    aiTextureType_TRANSMISSION,
    aiTextureType_UNKNOWN,
#ifndef SWIG
    _aiTextureType_Force32Bit = INT_MAX
#endif
};

#define AI_TEXTURE_TYPE_MAX aiTextureType_UNKNOWN
```

**Comment by kimkulling** [comment]
Good catch. This seems to be an artifact from the beginning of the Asset-Importer-Lib development.

One question: would this break the binary compatibility for older releases? I am not sure about this.

**Comment by RichardTea** [comment]
Any changes to the values of existing 'meaningful' public enums **will** break compiled applications.

It is generally recomended that all _public_ enums are explicitly assigned their values.
This is to ensure they cannot change by accident - whether by bad merge or well-intentioned tidy up.

The proposal above would change the value of several enums - eg aiTextureType_UNKNOWN from 18 to 21.
This would silently change the behaviour of applications as they would utilise the wrong aiTextureType.

In many ways changing an enum value is worse than crashing or refusing to dlopen!

That said, the AI_TEXTURE_TYPE_MAX macro does indeed have the wrong value and needs updating.
Anything using it to iterate texture types will drop the SHEEN, CLEARCOAT and TRANSMISSION.

**Comment by camden-smallwood** [comment]
I mostly disagree, changing an enum value is not worse than crashing. The recommendation is not required to be a *silent* change, it could be applied at the next version junction, which would be grounds for a breaking change, although agreeably inadvisable.

Those aside, I do agree with your resolution and it was left out of my recommendation, which I will update. The problem is indeed that the `AI_TEXTURE_TYPE_MAX` macro constant expands to the `aiTextureType_UNKNOWN` enum value.

It should be noted that any future changes to the `aiTextureType` enum should be sure that the definition of the `AI_TEXTURE_TYPE_MAX` macro constant correctly expands to the last member of the `aiTextureType` enum, which is currently `aiTextureType_TRANSMISSION`.
