### ISSUE TITLE
Bug: Exception when parsing OBJ with free-form curve/surface body statements

### ISSUE THREAD

**Issue by JaroslavPribyl** [assimp/assimp#4406]
**Describe the bug**
Obj files can contain rational or non-rational forms of curve or surface type (cstype), see http://paulbourke.net/dataformats/obj/ for more details.

The 'cstype' section contains a curved surface specification ended via 'end' keyword

cstype rat bspline
deg 2 2 \n
surf -1.0 2.5 -2.0 2.0 -9 -8 -7 -6 -5 -4 -3 -2 -1
parm u -1.00 -1.00 -1.00 2.50 2.50 2.50
parm v -2.00 -2.00 -2.00 -2.00 -2.00 -2.00
trim 0.0 2.0 1
end

When parsing the 'param' the ObjFileParser::parseFile throws an exception resulting in an empty scene because the 'p' char is reserved for the point statement.

**To Reproduce**
1. Place the following code snipped to particular obj file
`
cstype bspline
deg 1
curv 0 4.4342367553943109 469764 469765 469766 469767 469768 469769 469770 469771 469772 469773 469774 469775 469776 469777 469778 469779 469764
parm u 0 0 0.39203731404307385 0.77431392736273663 1.0679805170209486 1.5966388507215958 2.0325498413504901 2.1474985285004307 2.2603010199064344 2.3265611405640696 2.7831458308305455 2.9084799928898062 3.0217416168752282 3.0920040681852066 3.5571909671451176 4.0085983936902991 4.2714590158222263 4.4342367553943109 4.4342367553943109
end
`
2. import the obj file via assimp obj loader

**Expected behavior**
aiScene will be created with the cstype sections ignored (since there is no curved surface tesselator in obj import plugin)

**Comment by kimkulling** [comment]
That would be a great improvement of the obj-parsing, indeed.
