### ISSUE TITLE
Assertion failed: (tok.size() >= 5), function ReadTypedProperty, file /tmp/assimp-U0e0dT/assimp-3.1.1/code/FBXProperties.cpp, line 78.

### ISSUE THREAD

**Issue by aokman** [assimp/assimp#441]
Platform: Mac OSX 10.10, clang++, assimp-3.1.1, CodeLite

Downloaded assimp-3.1.1 through brew
1. Convert the humanoid.fbx from FBX SDK Sample to FBX 2013 binary Version using FbxConverterUI 2013.
2. Try import the resulting file in C++.

Result: Error info shown - Assertion failed: (tok.size() >= 5), function ReadTypedProperty, file /tmp/assimp-U0e0dT/assimp-3.1.1/code/FBXProperties.cpp, line 78.

**Comment by acgessler** [comment]
Can you upload the file somewhere by any chance? Thanks!

**Comment by r-lyeh** [comment]
@aokman, have you disabled RTTI by any chance? A couple of months ago, I was able to get FBX importer to work fully only when RTTI was enabled.

**Comment by acgessler** [comment]
Yes, FBX importer depends on RTTI due to `dynamic_cast`s that do require a runtime check.

Not sure this is the issue here though.

**Comment by aokman** [comment]
No, dynamic_cast works.
Please check the model: https://drive.google.com/file/d/0B_VUmdxo1JhRRnNQcHBFQ3JFTzg/view?usp=sharing

**Comment by TAMHAN** [comment]
Hello, I can confirm this issue with different models, which were exported to ASCII format via the FBX converter. Please be aware that this issue is very problematic, as the GUI does not show anything - the user can only find out about it by running mcgb from the command line.

**Comment by kimkulling** [comment]
Already fixed.
