### ISSUE TITLE
Crash on exporting of GLB file...

### ISSUE THREAD

**Issue by Honya2000** [assimp/assimp#4418]
Hello,
I have crash issue with skinned glb file re-export (import -> postprocess -> export).
Crash happens in the function: Ref<Node> FindSkeletonRootJoint(Ref<Skin> &skinRef)..
In this loop.

    do {
        startNodeRef = parentNodeRef;
        parentNodeRef = startNodeRef->parent;
    } while (!parentNodeRef->jointName.empty());

here it tryes to access parentNodeRef which is NULL.

I made a fix like this:

    do {
        startNodeRef = parentNodeRef;
        parentNodeRef = startNodeRef->parent;
    } while (parentNodeRef && !parentNodeRef->jointName.empty());

But not sure this is proper fix.

The glb file perfectly loads and animates in any GLB viewer I tried.

**Comment by Honya2000** [comment]
Ok. The fix I made - fixes the crash. But skinning works absolutely wrong in the viewer. Some stretched faces mess.
Is assimp supports skinned GLB's export at all ?

**Comment by Honya2000** [comment]
This is the link to the original glb. Can you please investigate?

https://drive.google.com/file/d/1UoX_VMlOqH5QclFdJJBRzP_XYgwWcq3H/view?usp=sharing

**Comment by kimkulling** [comment]
Hi, yes this feature shall work. Thanks for the hint.

**Comment by kimkulling** [comment]
PR is on its way: https://github.com/assimp/assimp/pull/4567
