### ISSUE TITLE
improve and describe building the documentation

### ISSUE THREAD

**Issue by waebbl** [assimp/assimp#4439]
**Is your feature request related to a problem? Please describe.**
Trying to build the documentation has a few issues:
- The Doxyfile refers to v5.0.1 and the release date of this version
- The `GENERATE_HTML` tag is set to NO, but there's no rule in the `CMakeLists.txt` file to generate the html output from the processed xml files (using breathe for example). If I run `ninja docs` from the build directory, I get `ninja: no work to do.`. Trying `cmake --build docs`, I get `Error: /var/tmp/portage/media-libs/assimp-5.2.2/work/assimp-5.2.2_build/docs is not a directory`
- If `ASSIMP_BUILD_DOCS=YES` and I try to install the package, there's an error, because the html documentation isn't build from the doxygen processed xml files and therefore no `AssimpDoc_Html` directory:
```
CMake Error at doc/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/var/tmp/portage/media-libs/assimp-5.2.2/work/assimp-5.2.2_build/doc/AssimpDoc_Html":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:77 (include)


FAILED: CMakeFiles/install.util 
cd /var/tmp/portage/media-libs/assimp-5.2.2/work/assimp-5.2.2_build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Describe the solution you'd like**
- Add rules to `doc/CMakeLists.txt` to process the doxygen xml output files into html files, i.e. using breathe or some other package for rtd output.
- Add some documentation on how to build the documentation, so package maintainers don't need to figure this out.

**Describe alternatives you've considered**
- I removed the option to build the documentation for this version in the Gentoo package.
- Release a pdf, like it was done in earlier versions (v5.0.1) and upload it to the github release page.

**Additional context**
Gentoo is source based distribution, so it's the users choice whether they want to build the documentation or not, if the option is available.

**Comment by kimkulling** [comment]
Hi,

the doxygen documentation will only be used to generate the https://assimp-docs.readthedocs.io/en/v5.1.0/ documentation.

I will do a cleanup in the documentation generation.

Kim
