### ISSUE TITLE
Resurrect ASSIMP_WERROR

### ISSUE THREAD

**Issue by haampie** [assimp/assimp#4452]
**Is your feature request related to a problem? Please describe.**

assimp always sets `-Werror`, but not all compilers are tested in CI, in particular unreleased compilers from the future with new warning messages.

**Describe the solution you'd like**

In build.md ASSIMP_WERROR is mentioned, but it has no effect. It would be great if it would disable -Werror.

**Describe alternatives you've considered**

Stripping -Werror in a compiler wrapper in package managers.

**Comment by kimkulling** [comment]
Or just add an option to enable all warnings as errors for all supported compilers?

The Werror was enabled to support a baseline of standard compilers like the latest g++ and clang++, which shall check the codebase for common patterns.

**Comment by kimkulling** [comment]
Done!
