### ISSUE TITLE
Help compiling for arm64-v8a

### ISSUE THREAD

**Issue by Keikoo** [assimp/assimp#4458]
Hi,

I'm using Assimp with UE4 on android, Everything worked with armeabi-v7a but now I need to compile for arm64-v8a. 
I tried the script in "scirpts/android_crosscompile" but I get "Could not determine machine name for compiler" for all toolchains.
I think it needs GCC but all I have in the NDK is clang. 

When using the standard CMake I manage to build the lib but the app crash at startup without any log.

Any help would be appreciated.

**Comment by mpcarlos87** [comment]
Hi @Keikoo I deployed an improvement to the script here https://github.com/assimp/assimp/pull/4454, you only need cmake and  the ndk and you should be able to build the v8a easily with it. It is not merged yet, you just need to jump to that branch and use it

**Comment by Keikoo** [comment]
Everything is working, thank you !
