### ISSUE TITLE
Discrepancies in version numbers

### ISSUE THREAD

**Issue by daniilpetrov** [assimp/assimp#4459]
Keep an eye on the version numbers, or there have been mismatches before, and now two versions in a row the library compiles with the number 5.2.0 :)

**Comment by kimkulling** [comment]
Fuxxx! Sorry for that!

**Comment by daniilpetrov** [comment]
I, too, sometimes suffer from inattention :)

**Comment by ryandesign** [comment]
I wonder why this issue is closed? It doesn't appear to have been fixed yet. CMakeLists.txt still says:
```
PROJECT(Assimp VERSION 5.2.0)
```
even though version 5.2.3 was released.
