### ISSUE TITLE
Assimp shouldn't force /MT or /MD flags in CMakeLists.txt

### ISSUE THREAD

**Issue by SirLynix** [assimp/assimp#4461]
**Describe the bug**
https://github.com/assimp/assimp/pull/4444 introduced an issue with the CMake build system, since it does force /MT or /MD flags in Release and /MTd or /MDd flags in Debug, it means you can no longer compile Assimp in Release with /MDd runtime (I know it may seems odd but you can't link a C++ /MD library with a /MDd executable, and since Assimp is doing some intensive operations I prefer to compile it in release to have optimizations).

I noticed it when upgrading the package from [xmake-repo](https://github.com/xmake-io/xmake-repo):
```
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> assimp v5.2.3 [vs_runtime:"MDd"]
please input: y (y/n/m)
y
  => download https://github.com/assimp/assimp/archive/v5.2.3.zip .. ok
  => install assimp v5.2.3 .. failed

assimp-vc143-mt.lib(Importer.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Importer.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Version.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Version.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(BaseProcess.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(BaseProcess.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(MaterialSystem.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(MaterialSystem.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(scene.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(scene.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultLogger.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultLogger.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(ScenePreprocessor.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(ScenePreprocessor.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultIOStream.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultIOStream.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Exceptional.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
error: install failed!
```

I made a [pull request](https://github.com/xmake-io/xmake-repo/pull/1088) to xmake-repo to remove https://github.com/assimp/assimp/pull/4444 part from the cmakelists and it fixed the issue.

The solutions:
I don't think we should force /MT /MD in the CMakeList at all, CMake already provides [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) which can be enabled with policy [CMP0091](https://cmake.org/cmake/help/latest/policy/CMP0091.html#policy:CMP0091) (but requires CMake 3.15).

If we want to keep this option, we should at least provide a way to disable it, maybe simply not forcing /MT nor /MTd flags if disabled.

**Comment by EYHN** [comment]
I understand that the current problem is that /MDd or /MTd cannot be used when Release configuration.
We can change the CMakeLists.txt force /MT when USE_STATIC_CRT is `ON`, and do nothing when `OFF`.

I tried using CMAKE_MSVC_RUNTIME_LIBRARY, adding the following code to CMakeLists.txt on Assimp, but it has no effect. I'm new to cmake, can you provide an example on how to use MSVC_RUNTIME_LIBRARY. 

```
cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebugDLL")
```

**Comment by SirLynix** [comment]
You can try to set it when configuring assimp (after enabling the policy).

So it's up to the author to see if upgrading the minimal CMake version to 3.15 is acceptable and the CMake `MSVC_RUNTIME_LIBRARY` works as expected (there's no CMAKE_ prefix).

If not, not setting any flag when not setting the option you added seems an acceptable fix

**Comment by kimkulling** [comment]
Shall be fixed by https://github.com/assimp/assimp/pull/4464

When you see any other issues for your own projects: let us start a separate discussion about them, please!

**Comment by SirLynix** [comment]
Thank you for the fix, I'm not sure to understand your advice however, this isn't related to my own projects, it was just not possible to compile Assimp with /MTd or /MDd in Release anymore (I only provided them for context, and xmake-repo is a C++ package manager unrelated to myself).

**Comment by SpaceIm** [comment]
> I understand that the current problem is that /MDd or /MTd cannot be used when Release configuration. Based on the current option, We can change the CMakeLists.txt force /MT when USE_STATIC_CRT is `ON`, and do nothing when `OFF`.
> 
> I tried using CMAKE_MSVC_RUNTIME_LIBRARY, adding the following code to CMakeLists.txt on Assimp, but it has no effect. I'm new to cmake, can you provide an example on how to use MSVC_RUNTIME_LIBRARY.
> 
> ```
> cmake_policy(SET CMP0091 NEW)
> set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebugDLL")
> ```

The way to use `CMAKE_MSVC_RUNTIME_LIBRARY` when cmake_minimum_required is lower than 3.15:

```
mkdir build
cd build
cmake .. -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebugDLL -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
```

This kind of vc runtime babysitting is bad practice IMOO.
