### ISSUE TITLE
Bug: C API texture loading is not working properly

### ISSUE THREAD

**Issue by dossalab** [assimp/assimp#4470]
**Describe the bug**

Trying to load a GLB file using the C API, textures doesn't load properly. Looping through available textures in the scene
```
for (size_t i = 0; i < scene->mNumTextures; i++) {
	texture = scene->mTextures[i];

	printf("w: %d\n", texture->mWidth);
	printf("h: %d\n", texture->mHeight);
}
```
gives the result:
```
w: 38933
h: 0
```

The actual data that is placed instead of the texture is just a raw PNG/JPG image, which can be confirmed by dumping it in the file and opening it:
```
uint8_t *b = (uint8_t *)texture->pcData;
for (size_t i = 0; i < texture->mWidth; i++) {
	fprintf(stderr, "%c", b[i]);
}
```

**To Reproduce**

I'm attaching a small MVP example and test GLB file produced by Blender:

[assimp-texture-load-broken.tar.gz](https://github.com/assimp/assimp/files/8373003/assimp-texture-load-broken.tar.gz)

**Expected behavior**

It's expected that the 'width' and 'height' fields contain the width and height of the image, and the pcData contains the texture data.

**Screenshots**

none

**Platform (please complete the following information):**

 - OS: Linux
 - Version  5.2 (Arch Linux repository)

**Additional context**
Actually C++ API gives the same results (no height, width is data length and raw textures)

**Comment by kimkulling** [comment]
This is just a hint that you are using anembedded texture. To store the embedded textures assimp will only store the size of the texture in the width-attribute. Together with the image type you can decode the information about the image.

You can find an eample in the assimp_viewer:
https://github.com/assimp/assimp/blob/75ab2beb062d56abfe717355ccfb574980f8f2fd/tools/assimp_view/Material.cpp#L438
