### ISSUE TITLE
new function "TextureTypeToString" should use the *ai...* namespace

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#4493]
**Describe the technical debt**

All public C-functions exported by libassimp, use a prefix `ai`.
This is nice, so for the Debian package we even use a version-script to make sure that only proper "public" symbols can be found in the library (for whatever reasons, using `-fvisibility=hidden` seems to export too many symbols; but anyhow...)

Now, with assimp-5.2.3, there's a new exported symbol `TextureTypeToString` (which is even used by the `assimp` cmdline tool), which obviously lacks the `ai`-prefix.

I figure this is because the function used to be an often-used (and re-implemented) private function, that was turned into a public function for better re-usability.

See #2964 resp #2989

**Better solution**

Rename the function to `aiTextureTypeToString` to have a name consistent with other public C-symbols.

**Desktop:**
 - OS: Debian/GNU
 - Browser: wtf
 - Version 5.2.3

**Comment by kimkulling** [comment]
This is correct, good catch!
