### ISSUE TITLE
The fuzz directory

### ISSUE THREAD

**Issue by oleg-alexandrov** [assimp/assimp#4497]
The top-level directory has a directory named "fuzz" which has just one single file, with no explanation for it. That looks like some kind of test code. Perhaps the repository would be cleaner if that directory was removed, and the file in question moved either to the source directory or to the test directory.

**Comment by kimkulling** [comment]
Good point, I am improving the documentation for this folder.

Thanks for the hint!

**Comment by oleg-alexandrov** [comment]
Thank you. It still does not make sense that a single test is kept in "fuzz", in the base directory, rather than together with the rest of the tests. 

If you start getting a few more like this then the organization will become messy. But I appreciate you documenting this.  This is a nice lib, and I am just picking at details.
