### ISSUE TITLE
Organization of header files

### ISSUE THREAD

**Issue by oleg-alexandrov** [assimp/assimp#4498]
Some header files in this repository are in include/assimp, but others are mixed in together with .cpp files in assimp/code/Common.

It appears that there is some attempt to separate headers from code, but it is half-done. Perhaps the headers from assimp/code/Common can be moved to include/assimp/Common.

**Comment by kimkulling** [comment]
No, the headers in the include folder are the public API's, which shall be used. The header files stored in the code folder are private ones.

**Comment by oleg-alexandrov** [comment]
Fair enough. It still looks a little inconsistent that some headers are grouped together and some are mixed with code. Ideally one should have include/assimp and include/assimp/private.  

But I see your point. This repo existed for a long time and what I am suggesting is a bit of an arbitrary separation.
