### ISSUE TITLE
Cannot build on Windows (VC++ 2013) - Cannot Find PThread.h

### ISSUE THREAD

**Issue by tmason101** [assimp/assimp#451]
Hello,

When attempting to build the latest interation of ASSIMP on Windows (VC++ 2013) I get a "cannot find pthread.h" message. See below.

Perhaps a "define" somewhere need to be fixed?

Thank you for your time.

	The C compiler identification is MSVC 18.0.31101.0
	The CXX compiler identification is MSVC 18.0.31101.0
	Check for working C compiler using: Visual Studio 12
	Check for working C compiler using: Visual Studio 12 -- works
	Detecting C compiler ABI info
	Detecting C compiler ABI info - done
	Check for working CXX compiler using: Visual Studio 12
	Check for working CXX compiler using: Visual Studio 12 -- works
	Detecting CXX compiler ABI info
	Detecting CXX compiler ABI info - done
	Found PkgConfig: C:/Strawberry/perl/bin/pkg-config  
	Building a non-boost version of Assimp.
	Looking for ZLIB...
	checking for module 'zzip-zlib-config'
	  package 'zzip-zlib-config' not found
	Could not locate ZLIB
	compiling zlib from souces
	CMake Error at contrib/zlib/CMakeLists.txt:6 (cmake_policy):
	  Policy "CMP0048" is not known to this version of CMake.

	Looking for sys/types.h
	Looking for sys/types.h - found
	Looking for stdint.h
	Looking for stdint.h - found
	Looking for stddef.h
	Looking for stddef.h - found
	Check size of off64_t
	Check size of off64_t - failed
	Looking for fseeko
	Looking for fseeko - not found
	Looking for unistd.h
	Looking for unistd.h - not found
	Renaming
		[...]/Documents/Visual Studio 2013/Projects/ASSIMPNEW/contrib/zlib/zconf.h
	to 'zconf.h.included' because this file is included with zlib
	but CMake generates it automatically in the build directory.
	checking for module 'minizip'
	  package 'minizip' not found
	Looking for DirectX...
	DirectX_PREFIX_PATH changed.
	Found DirectX: C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86/d3d9.lib
	DX lib dir: C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86
	Looking for include file pthread.h
	Looking for include file pthread.h - not found
	Found Threads: TRUE  
	Found Git: C:/Program Files (x86)/Git/bin/git.exe (found version "1.9.2.msysgit.0") 
	Configuring incomplete, errors occurred!
	See also "[...]/Documents/Visual Studio 2013/Projects/ASSIMPNEW/bin/CMakeFiles/CMakeOutput.log".
	See also "[...]/Documents/Visual Studio 2013/Projects/ASSIMPNEW/bin/CMakeFiles/CMakeError.log".

**Comment by kimkulling** [comment]
I am wondering who wants to use pthread here?

**Comment by acgessler** [comment]
Is your CMake version up to date? (_Policy "CMP0048" is not known to this version of CMake._). Also, did you try building with assimp view and tools disabled?

**Comment by tmason101** [comment]
@acgessler 

Updated Cmake to latest version and all is well.

Thank you for the quick response!

**Comment by mpazhani** [comment]
I am also getting the similar error while building https://github.com/alanxz/rabbitmq-c

The C compiler identification is MSVC 18.0.31101.0
Check for working C compiler using: Visual Studio 12 2013 Win64
Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Found C inline keyword: __inline
Looking for htonll
Looking for htonll - found
Looking for clock_gettime in rt
Looking for clock_gettime in rt - not found
Could NOT find POPT (missing:  POPT_INCLUDE_DIR POPT_LIBRARY) 
Could NOT find XMLTO (missing:  XMLTO_EXECUTABLE) 
Found Doxygen: E:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.9.1") 
Looking for include file pthread.h
Looking for include file pthread.h - not found
Found Threads: TRUE  
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
  suitable version "0.9.8i", minimum required is "0.9.8")
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindOpenSSL.cmake:324 (find_package_handle_standard_args)
  CMakeLists.txt:242 (find_package)

**Comment by kimkulling** [comment]
CMake is looking for OpenSSL: Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
suitable version "0.9.8i", minimum required is "0.9.8")
Call Stack (most recent call first):
...

This is not needed by assimp, maybe this is a dependency for rabbitmq-c ?

**Comment by acgessler** [comment]
I also don't think rabbitmq uses assimp, this is entirely unrelated.

**Comment by mpazhani** [comment]
I had set the OPENSSL path and that is fixed. Thank you.
