### ISSUE TITLE
Bug: ~aiFace() deletes mIndices without checking for nullptr

### ISSUE THREAD

**Issue by RobertMtx** [assimp/assimp#4515]
**Describe the bug**
This is not so much a bug, but an observation of a potential issue. In the destructor of aiFace, the mIndices member is being deleted without checking for nullptr, and it is indeed being sent to the operator delete as a null pointer. If users of your library overload operator delete and do anything with memory, this will cause them some issues.

**To Reproduce**
Find issue in file Assimp\include\assimp\mesh.h

**Expected behavior**
`If( mIndices != nullptr ) { delete [] mIndices; mIndices = nullptr; }`

Edit: After some more digging, I realized there are tons of deletions without null checks. Guess I better update my overloaded delete operator :)

**Comment by kimkulling** [comment]
HI, thanks for your bug-report. 
I do not fully agree with you. The delete-operator will check if a pointer is not nullptr before deleting this and ignore your deletion. That is true. But sometimes you want to check if the pointer is valid in the part of your code. A nullptr could be an indicator of a bug in your application. More here: https://stackoverflow.com/questions/615355/is-there-any-reason-to-check-for-a-null-pointer-before-deleting 

So my answer is: it strongly depends on the situation. 

In the situation mentioned by you, the missing test is completely fine. So we can close this ticket.

**Comment by RobertMtx** [comment]
Yeah, I looked that up after posting. Apparently it is completely okay to delete null objects. I did not realize. But I'm not sure what you were referring to as far as a bug? Do you mean assimp never intentionally deletes pointers that would be nullptr? I don't think that is true, if that's what you meant. Assimp sent a ton of nullptrs to my overloaded delete operator. But I did go ahead and check for nullptr before messing with the address, and everything is working great now. However, if assimp is not supposed to be sending nullptr to delete, then there may be some issues somewhere. Thanks!

**Comment by hassanjor** [comment]
Yea I just saw that my profiler had more deallocations than allocations which scared me a bit but it was this lol. 


If anyone is running into the same problem just add the check here and avoid deleting null to begin with
`void operator delete(void* p)
{
	if (p == nullptr)
	{
		return;
	}
	Profiler::deallocations++;
	if (dumpStaticAllocations)
	{
		std::cout << "DEALLOCATED: " << Profiler::deallocations << '\n';
		std::cout << "TOTAL POSSIBLE LEAKS: " << Profiler::allocations - Profiler::deallocations << '\n';
	}
	std::free(p);
}`
