### ISSUE TITLE
how to handle usemtl inside obj while this mal might not beeing found

### ISSUE THREAD

**Issue by jinfagang** [assimp/assimp#4518]
Some obj may have this before face:

```
usemtl lambert3SG

```

but the real mtl is in top:

```
mtllib a.mtl

```

then assimp will caused can not find texture error, how to ignore it anyway?

**Comment by kimkulling** [comment]
If I get you right there is a not existing material?

**Comment by jinfagang** [comment]
@kimkulling yes.
