### ISSUE TITLE
aiImportFile extremely slow

### ISSUE THREAD

**Issue by agGitHub** [assimp/assimp#4519]
**Describe the bug**

The following method:

ASSIMP_API const C_STRUCT aiScene *aiImportFile(
        const char *pFile,
        unsigned int pFlags);

that can be found at line 117 here:
https://github.com/assimp/assimp/blob/a2c2b64877657447fd9f0118d278de18d0c0e8f1/include/assimp/cimport.h

is extremely slow. Needs something like 2 seconds to execute on a .obj file of 50 kb (on an Android phone)

How to accelerate?

Thanks!

**Expected behavior**
It seems that it should be very quick ; a few 0.1 seconds maximum.

**Platform (please complete the following information):**
 - OS: Android 8 to 12

**Comment by turol** [comment]
Can you profile it?

**Comment by agGitHub** [comment]
@turol Thanks for your answer. May you give more details about how to profile C++ code in an Android app? And then? Will I find some ways to solve the problem? What kind of issues can it be? Thanks for your insights.

**Comment by turol** [comment]
I have no idea what kind of profiling tools exist on Android. Consult their documentation.

**Comment by agGitHub** [comment]
@turol Thanks for your answer. I have no experience with profiling tools at all, on any platform. If I manage to do some profiling, what kind of possible optimizations I can find with such a tool? Code optimization? Compiling optimizations? Memory/processor optimizations? Else? I don't understand what I can expect of such a tool. Thanks.

**Comment by turol** [comment]
Generally profiling tools can tell you what code is taking time or other resources. Anything else depends on the tool and like I said I don't know what tools Android has.

**Comment by kimkulling** [comment]
Try this: https://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake

**Comment by kimkulling** [comment]
Normally even on android the import process shall be very fast. Can you see if the CPU-load is high? Or maybe the I/O-performance is bad?

**Comment by agGitHub** [comment]
The flag -DCMAKE_BUILD_TYPE=Release solved the problem. :) Thanks !
