### ISSUE TITLE
Building gtest with VS2013 failes:

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#453]
See log below:
1>------ Neues Erstellen gestartet: Projekt: ZERO_CHECK, Konfiguration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because D:/projects/assimp/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/contrib/zlib/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/contrib/openddlparser/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/code/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/tools/assimp_view/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/tools/assimp_cmd/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/projects/assimp/test/CMakeFiles/generate.stamp is up-to-date.
2>------ Neues Erstellen gestartet: Projekt: gtest, Konfiguration: Debug Win32 ------
2>  Building Custom Rule D:/projects/assimp/test/CMakeLists.txt
2>  CMake does not need to re-run because D:\projects\assimp\test\CMakeFiles\generate.stamp is up-to-date.
2>  Creating directories for 'gtest'
2>  Performing download step (git clone) for 'gtest'
2>  -- gtest download command succeeded.  See also D:/projects/assimp/test/gtest/src/gtest-stamp/gtest-download-*.log
2>  
2>  Performing update step for 'gtest'
2>  Current branch master is up to date.
2>  No patch step for 'gtest'
2>  Performing configure step for 'gtest'
2>  CMake Error at D:/projects/assimp/test/gtest/src/gtest-stamp/gtest-configure.cmake:16 (message):
2>    Command failed: 1
2>  
2>     'C:/Program Files (x86)/CMake/bin/cmake.exe' '-DCMAKE_BUILD_TYPE=' '-Dgtest_force_shared_crt=ON' '-Dgtest_disable_pthreads:BOOL=OFF' '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=DebugLibs' '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=ReleaseLibs' '-GVisual Studio 12 2013' 'D:/projects/assimp/test/gtest/src/gtest'
2>  
2>    See also
2>  
2>      D:/projects/assimp/test/gtest/src/gtest-stamp/gtest-configure-*.log
2>  
2>  
2>  
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet.
========== Alles neu erstellen: 1 erfolgreich, 1 fehlerhaft, 0 übersprungen ==========

**Comment by jdduke** [comment]
Hmm, I've seen it fail the first time on occasion (during the gtest configure step). Building again typically pushes it through the gtest configure step, and compilation succeeds. 

I was just able to compile using Visual Studio 2012, so it's hard to say what exactly is going wrong. Does the "gtest-configure-.log" give any useful input? Does repeating the build step succeed?

**Comment by jdduke** [comment]
Download 2013 now, I'll report back on whether I can repro.

**Comment by jdduke** [comment]
Yeah, not sure what to tell you, the first build try worked like a charm with 2013.

Did you change any of the default CMake options? Which version of CMake do you have? I'm using CMake 3.0.0.

**Comment by kimkulling** [comment]
This issue was caused by a MinGWCMakeCahe file in gtest, which wasn't cleaned up correctly. Maybe we should check if this is an error or not.

**Comment by kimkulling** [comment]
Works.
