### ISSUE TITLE
Lots of crashes and hangs

### ISSUE THREAD

**Issue by turol** [assimp/assimp#454]
https://www.dropbox.com/s/ppp297aa1idfny2/assimp-bugs.zip?dl=0

Contains 837 hanging and 908 crashing testcases discovered with afl.

The crashing testcases have been minimized and should be mostly different. Tests were run on Linux with libstdc++ in debug mode and address sanitizer enabled. If using something else be aware that most of these are probably memory corruption bugs.

**Comment by turol** [comment]
OpenGEX parser wasn't in yet when I did the first fuzzing run. So I fuzzed just that one. In particular it seems very easy to make it loop indefinitely.

@kimkulling You might want to fix these while you're writing it. Also if you want to try afl yourself drop me a note and I can upload my initial test corpus.

https://www.dropbox.com/s/taf7v98tpa60xz7/ogex-crashes.zip?dl=0

**Comment by kimkulling** [comment]
Thanks a lot for the test data. I will check it!

**Comment by turol** [comment]
#488 and #523 should have fixed all of the crashes. Some of the hangs are still unresolved. So here's some more: https://www.dropbox.com/s/bgz5zlcaq787r2v/assimp-bugs2.zip?dl=0

**Comment by turol** [comment]
This has been effectively superseded by OSS-Fuzz.
