### ISSUE TITLE
Need a way to calculate the model in bind pose

### ISSUE THREAD

**Issue by LeHibou2** [assimp/assimp#4544]
Hello,

I read multiple youtube tutorials, and online docs but I can't see a way to get the original Tpose of my animated model from Assimp structures.

I get the Pose matrix just fine by multiplying the local matrix (mTransformation) from root to bone for a given frame, but I can't reproduce the position of my bones in the T pose/Bind pose/rest pose (they are the same thing in my model).

I am not even talking about skinning here: just getting back the global/local matrix of my bones in T pose. 

Not sure if this is possible right now or if it is a feature request to have the tools to get those back, but that would be great. 
If possible right now, please tell me how to get it.

**Comment by kimkulling** [comment]
You can try to use the offset-matrix of the bone. Here you shall be able to find the data you are looking for.
