### ISSUE TITLE
Need a way to access the raw inverse bind pose

### ISSUE THREAD

**Issue by LeHibou2** [assimp/assimp#4545]
Hello,

It would be nice to be able to access the raw inverse bind pose in order to retarget animations.

Thanks

**Comment by hardmode1337** [comment]
any luck with this without such update?

**Comment by LeHibou2** [comment]
I gave up with assimp and rolled my own lib..

**Comment by hardmode1337** [comment]
> I gave up with assimp and rolled my own lib..

Have you a link to this lib or a way to communicate with you on discord? Easymode#8661

**Comment by kimkulling** [comment]
If you want to use the FBX-Parser: you can try to get the data from the raw FBX data. Assimp will not offer this data at this moment, sorry,
