### ISSUE TITLE
Bug: compile error located on quaternion.h:133:5

### ISSUE THREAD

**Issue by leyaocty** [assimp/assimp#4548]
**Describe the bug**
```
# assimp
In file included from D:/Apps/msys64/mingw64/include/assimp/anim.h:55,
                 from lib\assimp\Anim.go:4:
D:/Apps/msys64/mingw64/include/assimp/quaternion.h:133:5: error: unknown type name 'ai_real'
  133 |     ai_real w, x, y, z;
      |     ^~~~~~~
```

**To Reproduce**

I'm using ***Golang*** to include the assimp lib for model loading on Ubuntu, Windows11(msys2), and MacOS(brew).
It's fine with version 5.0 on Ubuntu but both Mac and Windows are updated to version 5.2 and throw out above error while compiling. 

I compared the includes of two verisons and replaced anim.h and quaternion.h on Windows and MacOS by the Ubuntus and then both of them pass the compiling.

**Expected behavior**
Cloud you please check if there's any mistake since I'm not familiar with cpp.

Thx!

**Comment by kimkulling** [comment]
One question from my side: which golang package have you used?

**Comment by kimkulling** [comment]
Hi,

ai_real is a typedef for the float or double type used for floating point variables. Based on the cmake run this will be defined in the dedicated header ( I guess in include/assimp/defs.h ).

To help you here I will need a running build for your go-bindings. Could you please provide some GitHub-action for that and reopen the issue? 5.2 built pretty well as the CI said for that release.

Thanks,
Kim
