### ISSUE TITLE
Bug: IrrMeshLoader broken

### ISSUE THREAD

**Issue by MarkaRagnos0815** [assimp/assimp#4553]
The irrlicht mesh loader seems to be broken in many ways
1. the files in the repository are utf16LE but the loader assumes utf8 (I think this bug was introduced by pugixml)
2. the whole xml structure does not fit the code to read the xml
- it assumes to have a tag "buffer" at root level but there is a tag "mesh" 
- it does not read "standard" geomtery data correctly

- just try to import both files in folder test\models\IRRMesh\

**Comment by kimkulling** [comment]
OK, thanks for the update. I guess these issues were introduced with the redesign of XML loading.
