### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [assimp/assimp#4558]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@sudhackar) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by kimkulling** [comment]
Is on its way, thanks for the hint.

**Comment by JamieSlome** [comment]
@kimkulling - appreciate your diligence! ⚡ 

We will get the report sent over e-mail shortly :)

Just for reference, the report can be found directly here:
https://huntr.dev/bounties/67dab61b-8b13-454c-9aaa-db13add1e810/
