### ISSUE TITLE
Collada Animations: Problem with the use of matrices

### ISSUE THREAD

**Issue by TomMettam** [assimp/assimp#458]
Hi folks

Internally, Assimp uses an aiMatrix4x4 to store rotations between animation keyframes, before later decomposing into a quaternion.

Unfortunately, quaternions and rotation matrices are only appropriate for representing orientation, and not rotation.

Here is the problem:

KEYFRAME
Time index: 0.0000000
RotateZ.ANGLE:  1080

KEYFRAME
Time index: 1.0000000
RotateZ.ANGLE:  1440

Because both 1080 and 1440 are multiples of 360, a rotation matrix and a quaternion treats them as zero, and no animation occurs.

For the purposes of animation, we need to represent *rotation* and NOT just *orientation*.

In order to repair this issue, I believe that we need to stop using quaternions and the internal matrix to handle rotations in keyframes.

Instead, perhaps AxisAngle notation could be used?

Here is a test model which exhibits this problem:
https://dl.dropboxusercontent.com/u/29850039/Array%20Test%20001.zip

**Comment by biller23** [comment]
A key-frame is an orientation state at a given time.
If you specify the same angle, the orientation state is the same in the 2 key-frame.
You cannot have an animation this way.
Axis-Angle, Quaternion, and Rot-Matrix, all represent orientations. An animation is an interpolation between these orientations. 
Increase the number of key-frames.

**Comment by acgessler** [comment]
Agree, this is commonly solved by denser keyframes.

Which application generated the file?

**Comment by TomMettam** [comment]
I do agree with you in principle.

However, unfortunately we have no control over the models that users attempt to import using Assimp, and as such one should strive to be as compatible as possible with anything that may be thrown at us, right?

Axis-Angle can represent a rotation, not just an orientation, because the angle can be greater than 360 degrees. This will allow proper interpolation between the two values.

The application which exported this file is 3D Studio Max.

**Comment by acgessler** [comment]
To be lenient with importers is indeed Assimp's policy, the question is which effort it requires ..

Can you provide the file?

Also @Schrompf for the Collada import.

**Comment by TomMettam** [comment]
The file was linked to above:

https://dl.dropboxusercontent.com/u/29850039/Array%20Test%20001.zip

When animated properly, this should produce a cool spinny effect.

**Comment by acgessler** [comment]
Fixed it for Collada, please re-open if needed.

**Comment by TomMettam** [comment]
I can't confirm that this is working in the current master, with the test file provided

**Comment by nopjia** [comment]
I'm still seeing this issue with DAE import
Version 3.2.0

**Comment by kunyang-yk** [comment]
#2233

**Comment by mwestphal** [comment]
@TomMettam @acgessler : What is the actual license of `/anims_with_full_rotations_between_keys.fbx` you provided earlier and is now included in assimp ?

**Comment by TomMettam** [comment]
@mwestphal it was created by me, feel free to use it for whatever. I hereby disclaim any copyright ownership of that file.

**Comment by mwestphal** [comment]
Thanks @TomMettam !
