### ISSUE TITLE
Bug: (master branch): Build failed with [-Werror=array-compare] 

### ISSUE THREAD

**Issue by JophiMa** [assimp/assimp#4580]
**Describe` the bug**
Build fails with [-Werror=array-compare] at glTF2Exporter line 686 - if (sheen.sheenColorFactor == defaultSheenFactor)

**To Reproduce**
1. cmake CMakeLists.txt 
2. make 

**Platform (please complete the following information):**
 - OS: Arch based linux
 - Version: master branch

**Additional context**
temporary fix: replace line 686 -688 with this:

`bool tmp = false;`
`for(int i = 0; i < 3;i++){`
`    if(sheen.sheenColorFactor[i] != defaultSheenFactor[i]){`
`        tmp = true;`
`    }`
`}`
`if(!tmp){`
`    return false;`
`}`

Is this pretty / efficient? - probably not
does this work? - maybe idk
**does it build?** - yes! 

Hope this helps.

P.S. not quite sure how to format this as a patch command, feel free to add in the comments.

**Comment by Lactozilla** [comment]
Seems to have been fixed in 487a9aca2f7d97baed6e39d6ca9803aa5185862e (I ran into this as well)
