### ISSUE TITLE
Bug: scene->mRootNode->FindNode(meshName) can not find aiNode by aiMesh name

### ISSUE THREAD

**Issue by vovan4ik123-engine** [assimp/assimp#4583]
I am exporting Collada.dae from Blender.
Then load file with assimp.
File contains mesh and node with transformations for that mesh
Here is mesh id and name:
![image](https://user-images.githubusercontent.com/106265150/174638463-cdb289bc-17b2-46a9-9e28-18dba5d81177.png)

And here is node transformations id and name:
![image](https://user-images.githubusercontent.com/106265150/174638612-d972458f-a7ca-4e48-a059-f521c999eced.png)

From version 5.2 or 5.1 assimp store aiMesh name from <geometry id="..." and aiNode name from <node id="..."
But they are different. aiMesh name = "Ground1CollisionConvexMesh-mesh" with ...-mesh at the end
and aiNode name = "Ground1CollisionConvexMesh"
That mean when i use mRootNode->FindNode(meshName) it can not find transformations for mesh.

How i can find transformations for mesh in 5.2 version?

**Comment by luca-della-vedova** [comment]
Hi! For getting the transformation of meshes I usually parse nodes, if a node has meshes you can look at the node `mMeshes` and `mNumMeshes` properties, then you can read the meshes and use the node transform.
Does that make sense?

**Comment by RichardTea** [comment]
You've misunderstood the data structure. If it worked for you before then it was a lucky accident!

As per the documentation, `aiNode::FindNode(name)` looks for an `aiNode` of that name. It does not search for a mesh:

```
/** Searches for a node with a specific name, beginning at this
     *  nodes. Normally you will call this method on the root node
     *  of the scene.
     *
     *  @param name Name to search for
     *  @return nullptr or a valid Node if the search was successful.
     */
```

Meshes do _not_ have transforms, as they are often re-used multiple times within the scene.
Eg if there are a thousand balls, there would only be **one** ball `aiMesh` and a thousand `aiNodes` using it.

You build the transform hierarchy by walking the aiNode tree.
Each aiNode may have one or more child aiNodes, and may reference zero or more aiMeshes by their id.

If you are only interested in the aiNodes that use a specific aiMesh, you will need to do the following:

1. Search the aiScene->mMeshes list, for the Mesh(es) of interest. Store the indices when found.
2. Traverse the aiScene->mRootNode tree, storing the transforms as you go down the depth
   - Either postmultiplying them together to get the total transform, or storing the tree if you want to keep pivots etc
3. At each aiNode, search the aiNode->mMeshes for the indices stored in step 1.
4. When found, create your application datastructure for the transform and the instance of the Mesh.

Note that this is also much faster, as comparing two integers is much quicker than a string comparison.

**Comment by RichardTea** [comment]
Note that the Collada importer has an option to choose whether the `aiNode` name is the Collada node `id` or `name`.
By default it is the `id` as that's guaranteed unique, and some datastructures require that unique name reference.

Set the importer property `AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES` to true/nonzero if you want the `aiNodes` to use the Collada node `name` instead - beware though, as the node names may not be unique!
