### ISSUE TITLE
Problem related  to tangents and binormals

### ISSUE THREAD

**Issue by bytememofo** [assimp/assimp#46]
AssImp was throwing an exception when loading meshes because it thought that the binormal and tangent sections were missing. The following patch resolves this issue, this probably isn't the right place for this patch but I'm new to git hub and don't know the proper protocol for this type of thing. This is a patch for FBXMeshGeometry.cpp.

Putting the patch here doesn't seem to work very well becuase the patch gets interpreted as mark-up, let me know how best to submit this patch and I will.

@@ -467,7 +467,7 @@ void MeshGeometry::ReadVertexDataTangents(std::vector<aiVector3D>& tangents_out,
    const std::string& ReferenceInformationType)
 {
    ResolveVertexDataArray(tangents_out,source,MappingInformationType,ReferenceInformationType,
-       "Tangent",
-       "Tangents",
      "TangentIndex",
      vertices.size(),
      mapping_counts,
  @@ -482,7 +482,7 @@ void MeshGeometry::ReadVertexDataBinormals(std::vector<aiVector3D>& binormals_ou
  const std::string& ReferenceInformationType)
  {
    ResolveVertexDataArray(binormals_out,source,MappingInformationType,ReferenceInformationType,
-       "Binormal",
-       "Binormals",
      "BinormalIndex",
      vertices.size(),
      mapping_counts,

**Comment by kimkulling** [comment]
You can just clone our repo, create a new branch and fix it there. Or please send me a fix via gail. This version is not readable.

**Comment by kimkulling** [comment]
Hi,

any updates here. Just putting the code into code brackets would be enough for us

Kimmi

**Comment by kimkulling** [comment]
Please reopen, if still an issue.
