### ISSUE TITLE
Bug: building assimp-5.2.4 cannot find unzip.h on Fedora 36

### ISSUE THREAD

**Issue by viisautta** [assimp/assimp#4606]
[on@fedora build]$ make
[  5%] Built target zlibstatic
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:57:14: fatal error: unzip.h: No such file or directory
   57 | #    include <unzip.h>
      | 
compilation terminated.
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

HUNTER is OFF, and a lot of zips were installed as follows:
$ sudo dnf list installed | grep zip
[sudo] password for on: 
bzip2.x86_64                                         1.0.8-11.fc36                       @anaconda
bzip2-libs.x86_64                                    1.0.8-11.fc36                       @anaconda
gzip.x86_64                                          1.11-3.fc36                         @anaconda
laszip.x86_64                                        3.4.3-7.fc36                        @fedora  
libzip.x86_64                                        1.8.0-4.fc36                        @fedora  
libzip-devel.x86_64                                  1.8.0-4.fc36                        @fedora  
minizip.x86_64                                       3.0.2-6.fc36                        @fedora  
minizip-devel.x86_64                                 3.0.2-6.fc36                        @fedora  
unzip.x86_64                                         6.0-57.fc36                         @anaconda
zip.x86_64                                           3.0-32.fc36                         @anaconda
zziplib.x86_64                                       0.13.72-1.fc36                      @fedora  
zziplib-devel.x86_64                                 0.13.72-1.fc36                      @fedora  
zziplib-utils.x86_64                                 0.13.72-1.fc36                      @fedora  
[on@fedora build]$

**Comment by kimkulling** [comment]
There is a buildin unzip file. Have you tried that?

**Comment by viisautta** [comment]
ccmake .. displays as below:
...
 RT_LIBRARY                       /usr/lib64/librt.a
 ZLIB_INCLUDE_DIR                 /usr/include
 ZLIB_LIBRARY_DBG                 /usr/lib64/libz.so
 ZLIB_LIBRARY_REL                 /usr/lib64/libz.so
 pkgcfg_lib_GLUT_glut             /usr/lib64/libglut.so
 pkgcfg_lib_UNZIP_minizip         /usr/lib64/libminizip.so
 pkgcfg_lib_UNZIP_z               /usr/lib64/libz.so


After make a copy as following:
[on@fedora unzip610b]$ sudo cp unzip.h /usr/include/unzip.h

Rebuilding errors occurred:
[on@fedora build]$ make
Consolidate compiler generated dependencies of target zlibstatic
[  5%] Built target zlibstatic
Consolidate compiler generated dependencies of target assimp
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:92:12: error: ‘voidpf’ does not name a type; did you mean ‘void’?
   92 |     static voidpf open(voidpf opaque, const char *filename, int mode);
      |            ^~~~~~
      |            void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:93:12: error: ‘voidpf’ does not name a type; did you mean ‘void’?
   93 |     static voidpf opendisk(voidpf opaque, voidpf stream, uint32_t number_disk, int mode);
      |            ^~~~~~
      |            void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:94:12: error: ‘uLong’ does not name a type; did you mean ‘ulong’?
   94 |     static uLong read(voidpf opaque, voidpf stream, void *buf, uLong size);
      |            ^~~~~
      |            ulong
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:95:12: error: ‘uLong’ does not name a type; did you mean ‘ulong’?
   95 |     static uLong write(voidpf opaque, voidpf stream, const void *buf, uLong size);
      |            ^~~~~
      |            ulong
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:96:22: error: ‘voidpf’ has not been declared
   96 |     static long tell(voidpf opaque, voidpf stream);
      |                      ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:96:37: error: ‘voidpf’ has not been declared
   96 |     static long tell(voidpf opaque, voidpf stream);
      |                                     ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:97:22: error: ‘voidpf’ has not been declared
   97 |     static long seek(voidpf opaque, voidpf stream, uLong offset, int origin);
      |                      ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:97:37: error: ‘voidpf’ has not been declared
   97 |     static long seek(voidpf opaque, voidpf stream, uLong offset, int origin);
      |                                     ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:97:52: error: ‘uLong’ has not been declared
   97 |     static long seek(voidpf opaque, voidpf stream, uLong offset, int origin);
      |                                                    ^~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:98:22: error: ‘voidpf’ has not been declared
   98 |     static int close(voidpf opaque, voidpf stream);
      |                      ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:98:37: error: ‘voidpf’ has not been declared
   98 |     static int close(voidpf opaque, voidpf stream);
      |                                     ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:99:26: error: ‘voidpf’ has not been declared
   99 |     static int testerror(voidpf opaque, voidpf stream);
      |                          ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:99:41: error: ‘voidpf’ has not been declared
   99 |     static int testerror(voidpf opaque, voidpf stream);
      |                                         ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:100:12: error: ‘zlib_filefunc_def’ does not name a type
  100 |     static zlib_filefunc_def get(IOSystem *pIOHandler);
      |            ^~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:103:1: error: ‘voidpf’ does not name a type; did you mean ‘void’?
  103 | voidpf IOSystem2Unzip::open(voidpf opaque, const char *filename, int mode) {
      | ^~~~~~
      | void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:122:1: error: ‘voidpf’ does not name a type; did you mean ‘void’?
  122 | voidpf IOSystem2Unzip::opendisk(voidpf opaque, voidpf stream, uint32_t number_disk, int mode) {
      | ^~~~~~
      | void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:144:1: error: ‘uLong’ does not name a type; did you mean ‘ulong’?
  144 | uLong IOSystem2Unzip::read(voidpf /*opaque*/, voidpf stream, void *buf, uLong size) {
      | ^~~~~
      | ulong
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:150:1: error: ‘uLong’ does not name a type; did you mean ‘ulong’?
  150 | uLong IOSystem2Unzip::write(voidpf /*opaque*/, voidpf stream, const void *buf, uLong size) {
      | ^~~~~
      | ulong
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:156:6: error: ‘long int Assimp::IOSystem2Unzip::tell’ is not a static data member of ‘class Assimp::IOSystem2Unzip’
  156 | long IOSystem2Unzip::tell(voidpf /*opaque*/, voidpf stream) {
      |      ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:156:27: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  156 | long IOSystem2Unzip::tell(voidpf /*opaque*/, voidpf stream) {
      |                           ^~~~~~
      |                           void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:156:46: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  156 | long IOSystem2Unzip::tell(voidpf /*opaque*/, voidpf stream) {
      |                                              ^~~~~~
      |                                              void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:156:59: error: expression list treated as compound expression in initializer [-fpermissive]
  156 | long IOSystem2Unzip::tell(voidpf /*opaque*/, voidpf stream) {
      |                                                           ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:6: error: ‘long int Assimp::IOSystem2Unzip::seek’ is not a static data member of ‘class Assimp::IOSystem2Unzip’
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |      ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:27: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |                           ^~~~~~
      |                           void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:46: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |                                              ^~~~~~
      |                                              void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:61: error: ‘uLong’ was not declared in this scope; did you mean ‘ulong’?
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |                                                             ^~~~~
      |                                                             ulong
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:75: error: expected primary-expression before ‘int’
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |                                                                           ^~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:162:85: error: expression list treated as compound expression in initializer [-fpermissive]
  162 | long IOSystem2Unzip::seek(voidpf /*opaque*/, voidpf stream, uLong offset, int origin) {
      |                                                                                     ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:182:5: error: ‘int Assimp::IOSystem2Unzip::close’ is not a static data member of ‘class Assimp::IOSystem2Unzip’
  182 | int IOSystem2Unzip::close(voidpf opaque, voidpf stream) {
      |     ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:182:27: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  182 | int IOSystem2Unzip::close(voidpf opaque, voidpf stream) {
      |                           ^~~~~~
      |                           void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:182:42: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  182 | int IOSystem2Unzip::close(voidpf opaque, voidpf stream) {
      |                                          ^~~~~~
      |                                          void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:182:55: error: expression list treated as compound expression in initializer [-fpermissive]
  182 | int IOSystem2Unzip::close(voidpf opaque, voidpf stream) {
      |                                                       ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:191:5: error: ‘int Assimp::IOSystem2Unzip::testerror’ is not a static data member of ‘class Assimp::IOSystem2Unzip’
  191 | int IOSystem2Unzip::testerror(voidpf /*opaque*/, voidpf /*stream*/) {
      |     ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:191:31: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  191 | int IOSystem2Unzip::testerror(voidpf /*opaque*/, voidpf /*stream*/) {
      |                               ^~~~~~
      |                               void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:191:50: error: ‘voidpf’ was not declared in this scope; did you mean ‘void’?
  191 | int IOSystem2Unzip::testerror(voidpf /*opaque*/, voidpf /*stream*/) {
      |                                                  ^~~~~~
      |                                                  void
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:191:67: error: expression list treated as compound expression in initializer [-fpermissive]
  191 | int IOSystem2Unzip::testerror(voidpf /*opaque*/, voidpf /*stream*/) {
      |                                                                   ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:195:1: error: ‘zlib_filefunc_def’ does not name a type
  195 | zlib_filefunc_def IOSystem2Unzip::get(IOSystem *pIOHandler) {
      | ^~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:216:33: error: expected ‘)’ before ‘zip_handle’
  216 |     explicit ZipFileInfo(unzFile zip_handle, size_t size);
      |                         ~       ^~~~~~~~~~~
      |                                 )
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:219:45: error: ‘unzFile’ has not been declared
  219 |     ZipFile *Extract(std::string &filename, unzFile zip_handle) const;
      |                                             ^~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:223:5: error: ‘unz_file_pos_s’ does not name a type
  223 |     unz_file_pos_s m_ZipFilePos;
      |     ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:226:25: error: expected constructor, destructor, or type conversion before ‘(’ token
  226 | ZipFileInfo::ZipFileInfo(unzFile zip_handle, size_t size) :
      |                         ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:235:54: error: ‘unzFile’ has not been declared
  235 | ZipFile *ZipFileInfo::Extract(std::string &filename, unzFile zip_handle) const {
      |                                                      ^~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In member function ‘Assimp::ZipFile* Assimp::ZipFileInfo::Extract(std::string&, int) const’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:5: error: ‘unz_file_pos_s’ was not declared in this scope
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |     ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:21: error: ‘filepos’ was not declared in this scope; did you mean ‘fileno’?
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                     ^~~~~~~
      |                     fileno
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:42: error: ‘unz_file_pos_s’ does not name a type
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                          ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:57: error: expected ‘>’ before ‘*’ token
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                                         ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:57: error: expected ‘(’ before ‘*’ token
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                                         ^
      |                                                         (
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:58: error: expected primary-expression before ‘>’ token
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                                          ^
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:62: error: ‘m_ZipFilePos’ was not declared in this scope
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                                              ^~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:237:76: error: expected ‘)’ before ‘;’ token
  237 |     unz_file_pos_s *filepos = const_cast<unz_file_pos_s *>(&(m_ZipFilePos));
      |                                                                            ^
      |                                                                            )
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:238:9: error: ‘unzGoToFilePos’ was not declared in this scope
  238 |     if (unzGoToFilePos(zip_handle, filepos) != UNZ_OK)
      |         ^~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:238:48: error: ‘UNZ_OK’ was not declared in this scope
  238 |     if (unzGoToFilePos(zip_handle, filepos) != UNZ_OK)
      |                                                ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:241:9: error: ‘unzOpenCurrentFile’ was not declared in this scope
  241 |     if (unzOpenCurrentFile(zip_handle) != UNZ_OK)
      |         ^~~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:241:43: error: ‘UNZ_OK’ was not declared in this scope
  241 |     if (unzOpenCurrentFile(zip_handle) != UNZ_OK)
      |                                           ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:257:19: error: ‘unzReadCurrentFile’ was not declared in this scope
  257 |         int ret = unzReadCurrentFile(zip_handle, unzipBuffer.get(), static_cast<unsigned int>(bufferSize));
      |                   ^~~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: At global scope:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:363:5: error: ‘unzFile’ does not name a type
  363 |     unzFile m_ZipFileHandle = nullptr;
      |     ^~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In constructor ‘Assimp::ZipArchiveIOSystem::Implement::Implement(Assimp::IOSystem*, const char*, const char*)’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:374:5: error: ‘zlib_filefunc_def’ was not declared in this scope
  374 |     zlib_filefunc_def mapping = IOSystem2Unzip::get(pIOHandler);
      |     ^~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:375:5: error: ‘m_ZipFileHandle’ was not declared in this scope
  375 |     m_ZipFileHandle = unzOpen2(pFilename, &mapping);
      |     ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:375:44: error: ‘mapping’ was not declared in this scope
  375 |     m_ZipFileHandle = unzOpen2(pFilename, &mapping);
      |                                            ^~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:375:23: error: ‘unzOpen2’ was not declared in this scope
  375 |     m_ZipFileHandle = unzOpen2(pFilename, &mapping);
      |                       ^~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In destructor ‘Assimp::ZipArchiveIOSystem::Implement::~Implement()’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:379:9: error: ‘m_ZipFileHandle’ was not declared in this scope
  379 |     if (m_ZipFileHandle != nullptr) {
      |         ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:380:9: error: ‘unzClose’ was not declared in this scope; did you mean ‘Close’?
  380 |         unzClose(m_ZipFileHandle);
      |         ^~~~~~~~
      |         Close
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In member function ‘void Assimp::ZipArchiveIOSystem::Implement::MapArchive()’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:385:9: error: ‘m_ZipFileHandle’ was not declared in this scope
  385 |     if (m_ZipFileHandle == nullptr)
      |         ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:392:26: error: ‘m_ZipFileHandle’ was not declared in this scope
  392 |     if (unzGoToFirstFile(m_ZipFileHandle) != UNZ_OK)
      |                          ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:392:9: error: ‘unzGoToFirstFile’ was not declared in this scope
  392 |     if (unzGoToFirstFile(m_ZipFileHandle) != UNZ_OK)
      |         ^~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:392:46: error: ‘UNZ_OK’ was not declared in this scope
  392 |     if (unzGoToFirstFile(m_ZipFileHandle) != UNZ_OK)
      |                                              ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:398:9: error: ‘unz_file_info’ was not declared in this scope
  398 |         unz_file_info fileInfo;
      |         ^~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:400:35: error: ‘m_ZipFileHandle’ was not declared in this scope
  400 |         if (unzGetCurrentFileInfo(m_ZipFileHandle, &fileInfo, filename, FileNameSize, nullptr, 0, nullptr, 0) == UNZ_OK) {
      |                                   ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:400:53: error: ‘fileInfo’ was not declared in this scope; did you mean ‘fileno’?
  400 |         if (unzGetCurrentFileInfo(m_ZipFileHandle, &fileInfo, filename, FileNameSize, nullptr, 0, nullptr, 0) == UNZ_OK) {
      |                                                     ^~~~~~~~
      |                                                     fileno
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:400:13: error: ‘unzGetCurrentFileInfo’ was not declared in this scope
  400 |         if (unzGetCurrentFileInfo(m_ZipFileHandle, &fileInfo, filename, FileNameSize, nullptr, 0, nullptr, 0) == UNZ_OK) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:400:114: error: ‘UNZ_OK’ was not declared in this scope
  400 |         if (unzGetCurrentFileInfo(m_ZipFileHandle, &fileInfo, filename, FileNameSize, nullptr, 0, nullptr, 0) == UNZ_OK) {
      |                                                                                                                  ^~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:407:30: error: ‘m_ZipFileHandle’ was not declared in this scope
  407 |     } while (unzGoToNextFile(m_ZipFileHandle) != UNZ_END_OF_LIST_OF_FILE);
      |                              ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:407:14: error: ‘unzGoToNextFile’ was not declared in this scope
  407 |     } while (unzGoToNextFile(m_ZipFileHandle) != UNZ_END_OF_LIST_OF_FILE);
      |              ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:407:50: error: ‘UNZ_END_OF_LIST_OF_FILE’ was not declared in this scope
  407 |     } while (unzGoToNextFile(m_ZipFileHandle) != UNZ_END_OF_LIST_OF_FILE);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In member function ‘bool Assimp::ZipArchiveIOSystem::Implement::isOpen() const’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:411:13: error: ‘m_ZipFileHandle’ was not declared in this scope
  411 |     return (m_ZipFileHandle != nullptr);
      |             ^~~~~~~~~~~~~~~
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp: In member function ‘Assimp::IOStream* Assimp::ZipArchiveIOSystem::Implement::OpenFile(std::string&)’:
/home/on/Public/Devel/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:451:39: error: ‘m_ZipFileHandle’ was not declared in this scope
  451 |     return zip_file.Extract(filename, m_ZipFileHandle);
      |                                       ^~~~~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by viisautta** [comment]
It was fixed to copy contrib/unzip/*.h to /usr/include/.

**Comment by viisautta** [comment]
It was fixed.
