### ISSUE TITLE
Port to Javascript

### ISSUE THREAD

**Issue by simon-heinen** [assimp/assimp#461]
Did someone already evaluate the possibility to port assimp to pure Javascript? The idea is that the conversion could be done offline in the Webapp without a connection to the backend. Especially for model editors running in the browser this might be interesting. Any ideas about that? Are current browsers capable to load big files into memory, convert them in an acceptable time and would it be easy to crosscompile assimp to javascript?

**Comment by acgessler** [comment]
I haven't yet tried running assimp through Emscripten but we do nothing that would keep it from working.

Binary size may be an issue, you would possibly have to drop less relevant loaders.

**Comment by turol** [comment]
Many places in the code cast char pointers to other types like int or short which have higher alignment requirements. This WILL break on emscripten (and also ARM like Android and iOs). Even worse, by default it will silently return wrong results. Use either emscripten -sSAFE_HEAP=1 or clang ubsan to detect and fix these.

**Comment by acgessler** [comment]
There have been numerous fixes related to this lately (not to say that the codebase is still full of it, but it arguably won't affect the major file formats). Assimp runs nicely on Android.

**Comment by acgessler** [comment]
To conclude, it really needs someone to try it out :-) As for import performance, Assimp's postprocessing is very heavy on floating point calculations, which benefit from SSE et. al. Going through Emscripten, these *may* get accelerated through asm.js (or similar), if not this will likely become the bottleneck.

**Comment by mibamur** [comment]
should someone try do it or not? ( LLVM Emscript )

**Comment by makc** [comment]
-> #1088

**Comment by simon-heinen** [comment]
@acgessler @mibamur @turol  markc uploaded his attemp to https://github.com/makc/assimp2json
