### ISSUE TITLE
FBX skinning import problem

### ISSUE THREAD

**Issue by tek-nishi** [assimp/assimp#465]
I made test skinning animation data.

https://db.tt/idOLWICq

I made this data on Cheetah3D (OSX)
and exported Collada and FBX.

Collada data works fine. good preview.

![photo1](https://cloud.githubusercontent.com/assets/361940/6202893/6f749260-b547-11e4-9663-45b97b8312f2.PNG)

but FBX data was wrong preview.

![photo2](https://cloud.githubusercontent.com/assets/361940/6202894/75598c8a-b547-11e4-81a5-22d03b8d3197.PNG)

What's wrong?

Thank you.

**Comment by kimkulling** [comment]
Shall be fixed now. Just reopen if this issue still exists.
