### ISSUE TITLE
Bug: Issues with /WX

### ISSUE THREAD

**Issue by bartoli** [assimp/assimp#4652]
I'm trying to update to >=5.1. But i'm getting errors because of compiler warnings, even in 5.2.4.
The build environment is cmake 3.23 generating makefiles for VS2015

The current code has warnigns in this configuration, but tries to compile with /WX. Is it normal that it is here by default?

Also, running cmake with ASSIMP_WARNINGS_AS_ERRORS=OFF does not solve the issue, as the variable is not tested in all CMakeLists.txt that add /WX

Some of the warnigns are not trivial to fix, so i ended manually removing the /WX from the scripts.

The warnings/errors in VS2015 might be a duplicate of https://github.com/assimp/assimp/issues/4198

But I think, at least, ASSIMP_WARNINGS_AS_ERRORS should apply to the whole codebase?

**Comment by kimkulling** [comment]
I guess removing this complier switch will be the best method to fix this. Most of the compiler warnings are only visible at VS2015.

**Comment by kimkulling** [comment]
You are right, using Warnings as errors seems not to get applied to the whole code.
