### ISSUE TITLE
Bug: Linux blocks on ObjFileParser::getFace

### ISSUE THREAD

**Issue by Madman10K** [assimp/assimp#4653]
**Describe the bug**
Today I updated assimp on my game engine to test some stuff and the Window wasn't loading, after doing a performance profile, I found the call `libc-2.33.so __memmove_avx_unaligned_erms` took up 99% of the CPU time of the program which ultimately means that there is a problem there. So I debugged to ultimately come to the `ObjFileParser.cpp` file in the `getFace` function, at which point I looked at recent commits that modified it and it turns out that the [latest commit](https://github.com/assimp/assimp/commit/772cfdc757c6c52c260b54c3c522faa92288151e) changing line 461 from
```cpp
const int iVal(::atoi(&(*m_DataIt)));
```
to
```cpp
std::string number(&(*m_DataIt), m_DataItEnd - m_DataIt);
const int iVal(::atoi(number.c_str()));
```
is what causes the issue. Changing the line to the one before the commit results in the model loading correctly and the scene loading as expected.

After testing the models models used for a bit to check if this applies to every model that is loaded, it turns out that only 3 out of the 8 models loaded cause the issue. Models are attached below.

**To Reproduce**
1. Load the first, second or third models provided below using the following code
```cpp
Assimp::Importer importer;

const aiScene* scene = importer.ReadFile(location, aiProcess_Triangulate | aiProcess_FlipUVs | aiProcess_JoinIdenticalVertices);
```
2. Run the program

**Expected behavior**
For an Obj model to be loaded and not block on the `getFace` call, unfortunately I couldn't test on which iteration of the faces in the file it blocks due to it being too big

**Screenshots**
Results from the profiler:
![image](https://user-images.githubusercontent.com/40400590/179995689-c4251c68-182a-4b67-9c0f-85df0f0d48d6.png)

**Platform information: **
 - OS: Linux Kernel 5.16.18_p1-r1-debian-sources, Funtoo Linux 1.4
 - Compiler and toolchains: Make, gcc 9.2, CMake 3.19.7, libc-2.33
 - Compiler options: `-O3 --march=native`
 - Assimp version: Latest master

**Additional context**
The models in question: 
https://github.com/MadLadSquad/UntitledVulkanGameEngine/blob/master/Content/Engine/generic_object_sphere.obj
https://github.com/MadLadSquad/UntitledVulkanGameEngine/blob/master/Content/Engine/generic_object_torus.obj
https://github.com/MadLadSquad/UntitledVulkanGameEngine/blob/master/Content/Engine/generic_object_monkey.obj

**Comment by Madman10K** [comment]
Possibly related to/duplicate of #4657

**Comment by luk4w** [comment]
thx

**Comment by Madman10K** [comment]
Resolved by [latest commit](https://github.com/assimp/assimp/commit/dabaa7bdae1d3efc02f4323e187c8fc5988c5bb7), closing
