### ISSUE TITLE
Bug: Current master branch Assimp::Importer::ReadFile takes ages to read obj file.

### ISSUE THREAD

**Issue by TheGoozah** [assimp/assimp#4657]
Use the current master branch (on 24th July 2022), the Assimp::Importer::ReadFile takes ages to load a file. For example, an 8MB .obj file took 15 minutes to get loaded. When using an older commit (last one tested on my end SHA: e9b08f35b2d48253e915ebf70f257f7a996939b8) this loads in a second. This happens with either a static or dynamic library release build, using the default settings in cmake.

**Comment by kimkulling** [comment]
Right, there was a performance bottleneck. It is now fixed. Please try it again and if you are still unhappy with our performance just reopen this issue.
