### ISSUE TITLE
Bug: Current master branch Assimp::Importer::ReadFile load obj file does not respond

### ISSUE THREAD

**Issue by bumingbai2022** [assimp/assimp#4660]
**Describe the bug**
Use the current master branch (on 24th July 2022), the Assimp::Importer::ReadFile load obj file does not respond.
There will be no response all the time, as if it entered a dead cycle. In addition, the 32-bit version of 5.2.4 loads the obj model. The model file name contains Chinese, and an error is reported: "obj file is too small". 64 bits are normal, while 32 bits of 5.2.3 version are normal

**Comment by kimkulling** [comment]
Shall work again. There was a bug in the Obj-Parser, which had caused a high CPU load.

This one is fixed right now.
