### ISSUE TITLE
About the zlib library...

### ISSUE THREAD

**Issue by jkooooo99** [assimp/assimp#4664]
Hello, I am a newbie to everything...

I just built the Assimp by myself with Cmake and vs2019. It seems like that new version of Assimp needs both "zlibstatic.lib" and "assimp-vc140-mt.lib".

Could I  just "build" the zlibstatic.lib "inside" the "assimp-vc140-mt.lib", I remember I have used Assimp only with an "assimp-vc140-mt.lib"...So when those link errors come up, it took my whole morning to find out what is happening...

It is more straightforward, and the building instruction of the last Wiki does not explain the "new demand" very clearly...

**Comment by kimkulling** [comment]
Sure, there is an option to use the internal zlib by using cmake:

```
cd assimp-repo
cmake -DASSIMP_BUILD_ZLIB=ON CMakeLists.txt

```

**Comment by jkooooo99** [comment]
Hello, sorry to bother your again...

I tried your way to use the CMake, I used to be using the CMake GUI, and I can not find the DASSIMP_BUILD_ZLIB, I only can find `ASSIMP_BUILD_ZLIB` and `BUILD_SHARED_LIBS`...
![1](https://user-images.githubusercontent.com/81244845/181707962-0490cbc4-5141-4c2e-9a68-e77fbe63de2a.JPG)

So I directly use the cmd to type those codes `cmake -DASSIMP_BUILD_ZLIB=ON CMakeLists.txt`.

But it will generate a dynamic library...and I can not choose whether it is x32 or x64 bit...

So I tried again with `cmake -DASSIMP_BUILD_ZLIB=ON BUILD_SHARED_LIBS=OFF CMakeLists.txt`...and It did not work either...

It seems like the dynamic version of the assimp's lib does not need zlibstatic.lib but the static version must have it. Could I generate a static version library without needing zlibstatic.lib? 



Sorry for my English...

**Comment by abdoulayediak** [comment]
The ASSIMP_BUILD_ZLIB and BUILD_SHARED_LIBS that you see on the CMake GUI are the same options than 
`-DASSIMP_BUILD_ZLIB` and `-DBUILD_SHARED_LIBS` in the terminal. You can either check/uncheck their boxes in the GUI or write `cmake -DASSIMP_BUILD_ZLIB=ON -DBUILD_SHARED_LIBS=OFF CMakeLists.txt`

Note that you forgot the `-D` for the BUILD_SHARED_LIBS part.
