### ISSUE TITLE
How to have FBX Importer use axis metadata?

### ISSUE THREAD

**Issue by ngzaharias** [assimp/assimp#4667]
I'm exporting an fbx model from blender to my engine and I'm trying to have assimp import it and orientate it correctly.

Blender uses X-Right, Y-Forward, Z-Upward
My Engine uses X-Right, Y-Upward, Z-Forward

So I've marked the blender export options as:
- Forward = Z Forward
- Up = Y Up

I haven't found a post processing flag that I can set apart from aiProcess_MakeLeftHanded, but that makes -Z the Forward axis. 

I could transform vertices/normals myself inside blender or inside my engine, but I'm hoping that I've just missed a setting.

**Comment by kimkulling** [comment]
The settings will be stored in the FBX-GlobalSettings. Assimp will convert this to the metadata:

```
    mSceneOut->mMetaData->Set(0, "UpAxis", doc.GlobalSettings().UpAxis());
    mSceneOut->mMetaData->Set(1, "UpAxisSign", doc.GlobalSettings().UpAxisSign());
    mSceneOut->mMetaData->Set(2, "FrontAxis", doc.GlobalSettings().FrontAxis());
    mSceneOut->mMetaData->Set(3, "FrontAxisSign", doc.GlobalSettings().FrontAxisSign());
    mSceneOut->mMetaData->Set(4, "CoordAxis", doc.GlobalSettings().CoordAxis());
    mSceneOut->mMetaData->Set(5, "CoordAxisSign", doc.GlobalSettings().CoordAxisSign());
    mSceneOut->mMetaData->Set(6, "OriginalUpAxis", doc.GlobalSettings().OriginalUpAxis());
    mSceneOut->mMetaData->Set(7, "OriginalUpAxisSign", doc.GlobalSettings().OriginalUpAxisSign());

```

Hope that helps.
