### ISSUE TITLE
Importing certain OBJ files giving vector::_M_range_check error

### ISSUE THREAD

**Issue by Znny** [assimp/assimp#467]
I am getting an error when trying to import certain OBJ files:

Error, T0: Obj: Ignoring empty face
Skipping one or more lines with the same contents
Error, T0: vector::_M_range_check

Here are some of the files it is breaking with: https://www.dropbox.com/sh/t6cea6sbh3b97l8/AAALAAu0blXTTLO7hDfUYGWKa?dl=0 

I have tried with both the standard C and C++ methods for importing the scene and both give the same error, I have also tried turning off all post-processing with the same results.
The importer works fine with some OBJ's, so not sure what the problem is.

**Comment by Znny** [comment]
After doing a bit more research I think I may have found the issue: The OBJ files that are failing to load are using relative as opposed to absolute indices for face specification and I do not believe that the current OBJ importer takes this into consideration.

**Comment by kimkulling** [comment]
Hi,

have you tried the latest version on github? This version should be able to deal with relative indices.

Kimmi

**Comment by kimkulling** [comment]
PLease try the latest version from github ( repo ) this worked for me!

Kimmi

**Comment by Znny** [comment]
Hey Kim, you're absolutely correct, I realized this also after poking around the source code for a bit. Downloaded and compiled the latest and everything works fine, thanks! :)

**Comment by kimkulling** [comment]
You're welcome, glad to see that the solution was so easy :-).
