### ISSUE TITLE
Bug: Redundant dot in a filename 

### ISSUE THREAD

**Issue by Ksnz** [assimp/assimp#4670]
**Describe the bug**
CLI to export model adds a redundant period to an output filename when the filename param it describes has no dots

**To Reproduce**
Run `export bar.fbx foo -fglb`
Got new `foo.` file in working directory (ends with a dot)

**Expected behavior**
Got new  `foo` file in working directory, with name exact as provided in the CLI command

**Comment by kimkulling** [comment]
Right, fix is on its way.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/4674
