### ISSUE TITLE
Packed structs restrict usability

### ISSUE THREAD

**Issue by Optiligence** [assimp/assimp#468]
Is it really necessary to break alignment of `aiVector3t` in some cases? For example, you currently cannot use `emplace` with the packed vector components with gcc on Windows: 
```
cannot bind packed field '(((aiVector3D*)mesh->aiMesh::mTextureCoords[0]) + ((sizetype)(j * 12ull)))->aiVector3t<float>::x' to 'float&'
```

**Comment by acgessler** [comment]
Plenty of old loading code assumes packing. I'm sacred of an infinite amount of regressions if we changed it.

**Comment by Optiligence** [comment]
Thx for the info.
