### ISSUE TITLE
Bug: Memory leak in LWSImporter::BuildGraph

### ISSUE THREAD

**Issue by Quipyowert2** [assimp/assimp#4687]
**Describe the bug**

In LWSImporter::BuildGraph, if `src.type` is OBJECT and it has children, memory is allocated to `nd->mChildren` for one child and then initialized at [LWSLoader.cpp line 374-379](https://github.com/assimp/assimp/blob/888468e8f70d7379ac717d070244ef943e66ba41/code/AssetLib/LWS/LWSLoader.cpp#L374). At the end of the BuildGraph method, memory is allocated again for `nd->mChildren` at [LWSLoader.cpp line 447](https://github.com/assimp/assimp/blob/888468e8f70d7379ac717d070244ef943e66ba41/code/AssetLib/LWS/LWSLoader.cpp#L447) without deleting the old memory. Thus the pointer to the old allocation is lost, creating a memory leak.

This memory leak was found with CppCheck 2.8 in the assimp submodule of Qt 6, but the memory leak seems to be also present in the master branch of this repository, although the line numbers are slightly different.

The following CppCheck error doesn't say how the memory was leaked, so I had to investigate the leak myself.
```
[D:/Linux_home/nathan/src/qt5/qt3d/src/3rdparty/assimp/src/code/AssetLib/LWS/LWSLoader.cpp:452] (error) Memory leak: mChildren [memleak]
```
In the CppCheck GUI it says CWE 401 which is [Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html).

**To Reproduce**
1. Download CppCheck 2.8
2. Open Cppcheck
3. Click Edit, then Preferences, then increase the number of threads for faster analysis.
4. Click View then Toolbar, enable everything there.
5. Uncheck style (yellow circle icon) and info (lightbulb icon) messages. 
6. Click Analyze, then Directory.
7. Select the code folder of the assimp repo
8. Wait for CppCheck to analyze the repo
9. See error

**Expected behavior**

Ideally, there'd be no memory leaks in assimp, although leaks classed as still reachable by Valgrind are probably fine.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 103.0.2
 - Version assimp master (888468e8f)
 - CppCheck 2.8.

**Additional context**

**Comment by kimkulling** [comment]
If I get the code right, the children nodes will be allocated in a recursive matter. Is this a real leak? I guess we need to check this via a unittest.

**Comment by Quipyowert2** [comment]
Never mind, there's no leak. I just ran the LWS unit tests under Valgrind and it says no leaks are possible. 

`valgrind bin/unit --gtest_filter='*LWS*'`
```
==6841== HEAP SUMMARY:
==6841==     in use at exit: 0 bytes in 0 blocks
==6841==   total heap usage: 23,364 allocs, 23,364 frees, 2,645,950 bytes allocated
==6841== 
==6841== All heap blocks were freed -- no leaks are possible
==6841== 
==6841== For lists of detected and suppressed errors, rerun with: -s
==6841== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by kimkulling** [comment]
Thanks for your update!
