### ISSUE TITLE
Bug: Unable to open file

### ISSUE THREAD

**Issue by petrasvestartas** [assimp/assimp#4689]
**Describe the bug**
Unable to open file error once this code is run.
In other words I cannot import simple .obj or .ply files.
Could you tell me why?

**ERROR::ASSIMP:: Unable to open file "C:\IBOIS57\_Code\Software\CPP\CMAKE\super_build\example_glfw\build\Release\model_cylinder\model_cylinder.ply".**

```cpp
		// read file via ASSIMP
		Assimp::Importer importer;
		const aiScene* scene = importer.ReadFile(path, aiProcess_Triangulate | aiProcess_GenSmoothNormals | aiProcess_FlipUVs | aiProcess_CalcTangentSpace);
		// check for errors
		if (!scene || scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE || !scene->mRootNode) // if is Not Zero
		{
			cout << "ERROR::ASSIMP:: " << importer.GetErrorString() << endl;
			return;
		}
```

**To Reproduce**
Model
[model_cylinder.zip](https://github.com/assimp/assimp/files/9339757/model_cylinder.zip)

**Platform (please complete the following information):**
 - OS: Windows
 - Version  Latest

**Comment by kimkulling** [comment]
Works for me., file gets loaded. Maybe your path is wrong?
