### ISSUE TITLE
Bug: MD5Mesh regression with weights

### ISSUE THREAD

**Issue by marcakafoddex** [assimp/assimp#4709]
**Describe the bug**
Latest master reads md5mesh but gives wrong weight data, while an older version (tested with 5.2.0) works just fine.

**To Reproduce**
1. Clone `ogldev` from here: https://github.com/emeiri/ogldev
2. In your own project, just instantiate assimp and load the following file from that repository: `Content/boblampclean.md5mesh`
3. Inspect the scene in your favorite debugger, check the scene, then its first mesh, its first bone, and observe the amount of weights it has
4. Notice that with latest master, this is 190

**Expected behavior**
There should be 41 weights for the first bone, not 190

**Platform (please complete the following information):**
 - OS: Windows

**Additional context**
I'm trying to add assimp support to my engine. I'm using tutorial 38 from ogldev as a base for skinned meshes. They ship an older version of assimp in their repository. When you run tutorial 38, it shows the referenced md5mesh animated just fine, meaning the data is read properly by that older version of assimp.
For my own engine, I used the latest master. Reading the exact same model with the exact same loading flags gives very different (and weird) and wrong data. This seems to be a regression. When I switched to v5.2.0 of assimp, my engine worked instantly.

**Comment by marcakafoddex** [comment]
I did some digging around the other 5.2.x versions, turns out that:
- 5.2.0 works fine
- 5.2.2 works fine
- 5.2.3 works fine
- 5.2.4 does NOT work fine
- master does NOT work fine

So the bug was introduced in after the release of 5.2.3!

**Comment by pezcode** [comment]
This is most likely fixed by https://github.com/assimp/assimp/pull/4707, 5.2.5 should work

**Comment by marcakafoddex** [comment]
Released yesterday I see, I'll check it out and report back

**Comment by marcakafoddex** [comment]
Problem persists unfortunately, despite using 5.2.5

**Comment by marcakafoddex** [comment]
Can confirm this issue is fixed in 5.2.5
