### ISSUE TITLE
UINT32_MAX not defined compilation error

### ISSUE THREAD

**Issue by weshoke** [assimp/assimp#471]
assimp/code/IFCLoader.cpp:563:53: error: ‘UINT32_MAX’ was not declared in this scope
  unsigned int matid = ProcessMaterials( el.GetID(), UINT32_MAX, conv, false);

Linux 3.10.0-123.20.1.el7.x86_64 x86_64 GNU/Linux
Target: x86_64-redhat-linux
gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)

**Comment by pwnedary** [comment]
I second this; gcc version (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 and clang version 3.4 (tags/RELEASE_34/final).

**Comment by acgessler** [comment]
Travis agrees: https://travis-ci.org/assimp/assimp.

Fixing.
