### ISSUE TITLE
Bug: Unable to load valid .x file - Semicolon expected.

### ISSUE THREAD

**Issue by naota29** [assimp/assimp#4722]
Hello,

This bug is related to a previous issue reported with ID: #275.

When attempting to import the .x file in the attached zip folder, I receive an error stating "Line 574: Semicolon expected."

[test.zip](https://github.com/assimp/assimp/files/9539100/test.zip)

I generated this file using the [ModelConverterX](https://www.scenerydesign.org/modelconverterx/) software.  I imported the "test.x" file that comes with the assimp repo in the assimp\test\models\X directory.  I then exported this same file from that software in the .x format.  After doing this, assimp no longer imports it, and gives me the aforementioned error.

I can, however, still view this file in the ModelConverterX software and by using DirectX rendering tools.  

If I can provide any more info please let me know.

Thank you

**Comment by kimkulling** [comment]
This is not an issue of the asset-importer implementation. This is an error introduced by the export of the ModelConverterX. The expected delimiter for a matrix is a semicolon. And after that the used container in the file must be closed by another semicolon. 

In your test-file there is noly one semicolon and the container delimiter is missing. And this is the reason for the error message.

You can find the file format specification here: http://www.cgdev.net/axe/x-file.html.
