### ISSUE TITLE
Why are 32-bit builds missing from the Visual Studio solution?

### ISSUE THREAD

**Issue by rayment** [assimp/assimp#4749]
I cannot find any information through a preliminary online search as to why 32-bit builds in Visual Studio are disabled? Is there a reason why I cannot have my solutions built there rather than having to use MinGW?

I raise this issue as a feature request so that it may hopefully be (re?)implemented, if at the very least to have the reason for absence documented.

**Comment by kimkulling** [comment]
Most of the operation systems are using 64-bit. So there is no special reason for that. It is just that I was pretty lazy. Are you interested in 32 bit?

**Comment by rayment** [comment]
> Most of the operation systems are using 64-bit. So there is no special reason for that. It is just that I was pretty lazy. Are you interested in 32 bit?

Yes I am. I use assimp in both 32 and 64 bit builds of an application I own and when I tried to automate and build the dlls from scratch, I was surprised to see the lack of a 32-bit option.

Is this something that could be potentially added?

**Comment by kimkulling** [comment]
You can use cmake to genrate a 32bit build.

**Comment by rayment** [comment]
Wonderful! Thank you very much for implementing this.
