### ISSUE TITLE
Bug: assimp.sourceforge.net wrong redirect

### ISSUE THREAD

**Issue by BenjaminDeleze** [assimp/assimp#4750]
**Describe the bug**

1) In the wiki [main page](https://github.com/assimp/assimp/wiki), the link of Open Asset Import Library points to http://assimp.sourceforge.net/ . It seems that it should point directly to http://www.assimp.org

2) On http://assimp.sourceforge.net/, the link in: `Redirect to our new home in the web: http://www.assimp.org` actually points to http://example.com/

3) It would be better to use `https` links instead of `http` ones.

**Comment by kimkulling** [comment]
Thanks for your report. The sourceforge-side in completly outdated and will not be maintained any more.
