### ISSUE TITLE
Bug: zero symbol in XML structure with UTF8 encoding and non-ASCI characters in "collada" exporter

### ISSUE THREAD

**Issue by Let0s** [assimp/assimp#4758]
**Describe the bug**
Export in "collada" format with non-ASCI characters and UTF8 encoding can make incorrect file (with `\0` character in string inside XML structure). This file can not be imported by assimp and some online viewers, while there is `\0` symbols (maybe some other symbols too) inside it.

**To Reproduce**
1. Make export sample:
```c
  // output file name
  const char* filename = u8"D:\\TempExport\\dae\\sample.dae";
  auto scene = new aiScene();
  if (!scene->mRootNode)
      scene->mRootNode = new aiNode();
  auto root = scene->mRootNode;
  root->mName = aiString(u8"й");
  aiExportScene(scene, "collada", filename, 0);
```
2. Run sample and inspect result of export. In my case, node id is "_M`\0`".

**Expected behavior**
Expected correct file.

**Screenshots**
Part of XML structure in output file with `\0` symbol in Notepad++
![daeStruct](https://user-images.githubusercontent.com/9331480/196416565-cf26b35b-0eaa-4df0-a5ab-364ee8b7b70d.png)

**Platform (I think it does not matter):**
 - OS: Windows
 - MSVC: 2022
 - Platform toolset: v141 (Visual studio 2017)

**Additional context**
My investigation:
1. name string `u8"й"` represents as char array `[-48 'Р', -71 '№']`
2. This name string is passed as parameter to `XMLIDEncode` function in ColladaExporter.cpp file
3. In line 
https://github.com/assimp/assimp/blob/a3c209f2ca396345e658658df2b83cec7353cf1b/code/AssetLib/Collada/ColladaExporter.cpp#L109
both first and second char go to `else` branch
4. In line 
https://github.com/assimp/assimp/blob/a3c209f2ca396345e658658df2b83cec7353cf1b/code/AssetLib/Collada/ColladaExporter.cpp#L113
all the magic happens with second char ` -71 '№'`: `(*it) % XML_ID_CHARS_COUNT` returns 65, and `XML_ID_CHARS[65]` becames `\0` and is written to result of function and goes to the output file.

**Comment by Let0s** [comment]
I've got the reason. The problem is here:
https://github.com/assimp/assimp/blob/a3c209f2ca396345e658658df2b83cec7353cf1b/code/AssetLib/Collada/ColladaExporter.cpp#L94
because XML_ID_CHARS is `<all defined symbols>\0`, so last element of array is `\0` and it's index can be calculated with `(*it) % XML_ID_CHARS_COUNT`.

I think, chnage line from 
```c
    const unsigned int XML_ID_CHARS_COUNT = sizeof(XML_ID_CHARS) / sizeof(char);
```
to

```c
    const unsigned int XML_ID_CHARS_COUNT = sizeof(XML_ID_CHARS) / sizeof(char) - 1;
```
will solve this problem

I'll try to prepare my computer to make commit and pull-request (i dont know, if i can do that via browser) in few days.

**Comment by kimkulling** [comment]
Thanks for your investigations and the fix. I will close the issue-report.
