### ISSUE TITLE
Large FBX import crash

### ISSUE THREAD

**Issue by jpx** [assimp/assimp#477]
I am using Assimp 3.1 revision 3672247479.
A crash occurs while loading a large FBX file of approximately 8K meshes and 4M poly.
An exception is thrown while converting scene to assimp representation calling

```
// attach sub-nodes
ConvertNodes(model->ID(), *nodes_chain.back(), new_abs_transform);
```

from FBXConverter.cpp, line 248

Then crash seams to occur while cleaning resources, calling destructor of an aiNode in nodes_chain container, from catch { ... } statement

```
catch(std::exception&)  {
  Util::delete_fun<aiNode> deleter;
  std::for_each(nodes.begin(),nodes.end(),deleter);
  std::for_each(nodes_chain.begin(),nodes_chain.end(),deleter);
}
```

Full stacktrace is

```
aiNode::~aiNode() Line 158    C++
    [External Code] 
`Assimp::FBX::Converter::ConvertNodes'::`1'::catch$0() Line 273   C++
    [External Code] 
Assimp::FBX::Converter::ConvertNodes(unsigned __int64 id, aiNode & parent, const aiMatrix4x4t<float> & parent_transform) Line 248 C++
Assimp::FBX::Converter::ConvertRootNode() Line 162    C++
Assimp::FBX::Converter::Converter(aiScene * out, const Assimp::FBX::Document & doc) Line 111  C++
Assimp::FBX::ConvertToAssimpScene(aiScene * out, const Assimp::FBX::Document & doc) Line 2976 C++
Assimp::FBXImporter::InternReadFile(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & pFile, aiScene * pScene, Assimp::IOSystem * pIOHandler) Line 183 C++
Assimp::BaseImporter::ReadFile(const Assimp::Importer * pImp, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & pFile, Assimp::IOSystem * pIOHandler) Line 88  C++
Assimp::Importer::ReadFile(const char * _pFile, unsigned int pFlags) Line 660 C++
Assimp::Importer::ReadFileFromMemory(const void * pBuffer, unsigned __int64 pLength, unsigned int pFlags, const char * pHint) Line 504    C++
```

Are there any hint why this could happen ?

**Comment by promethe42** [comment]
It looks like the issue was related to #478 : it implied some degenerated meshes that I supposed would likely cause gigantic buffers to be allocated. Leading to a bad_alloc even with 64bits builds.

Running the test above (it's the same FBX as in #478) in debug will actually trigger the same assert.

Finally, fixing #478 fixed this.

I would recommend closing this issue and continue on #478 to assess the quality of the fix so we can make the pull request.
