### ISSUE TITLE
Include revision.h in include/

### ISSUE THREAD

**Issue by ofTheo** [assimp/assimp#4775]
**Is your feature request related to a problem? Please describe.**
Yes. Currently it is impossible to determine the assimp version being used at the preprocessor level. Especially with system install versions of libassimp-dev. This makes including new assimp features while still supporting older system level installs of assimp impossible as you can't use any of the newer features without creating linker errors. 

**Describe the solution you'd like**
Include the revision.h file in the overall includes ( once cmake has generated it ) or include `#ASSIMP_VERSION_MAJOR` etc in version.h. 

**Describe alternatives you've considered**
There are no alternatives as far as I am aware. If you are building the lib with cmake you can copy the revision.h manually over, but I would argue that it is pretty standard for most libs to have preprocessor defines for their major and minor versions included as standard. And this doesn't address any system included libassimp-dev which is common on Linux based OSs. 

**Additional context**
Related #4291

**Comment by kimkulling** [comment]
Done!
