### ISSUE TITLE
Bug:  asserthandler.h is not in include directory

### ISSUE THREAD

**Issue by runarundheim** [assimp/assimp#4779]
The assimphandler.h exist in the code\Common directory, but the rest of the api exist in the include\assimp. So when the assimp library is build with vcpkg the assimphandler.h is doesn't end up in the include directory. 
I would suggest that this file is moved into the include\assimp directory.

**Comment by MonicaLiu0311** [comment]
Is there any progress?

**Comment by kimkulling** [comment]
It is done. Just check our latest master branch.
