### ISSUE TITLE
ConvertMeshMultiMaterial assert/error

### ISSUE THREAD

**Issue by promethe42** [assimp/assimp#478]
Hello,

I'm trying to load an FBX and Converter::ConvertMeshMultiMaterial does not behave as expected:

https://github.com/assimp/assimp/blob/master/code/FBXConverter.cpp#L1031

The problem is the loop in this method clearly expect `mindices` and `faces` to have the same size. In my case they do not (I can't share the FBX file, it's under NDA). What might cause this?

As workaround, I've modified the calling function to avoid going any further if the sizes don't match:

https://github.com/assimp/assimp/blob/master/code/FBXConverter.cpp#L1031

becomes

```
std::vector<unsigned int> ConvertMeshMultiMaterial(const MeshGeometry& mesh, const Model& model, 
        const aiMatrix4x4& node_global_transform)    
    {
        const MatIndexArray& mindices = mesh.GetMaterialIndices();
        ai_assert(mindices.size());

        std::set<MatIndexArray::value_type> had;
        std::vector<unsigned int> indices;

        BOOST_FOREACH(MatIndexArray::value_type index, mindices) {
            if (had.find(index) == had.end() && mesh.GetFaceIndexCounts().size() == mindices.size()) {

                indices.push_back(ConvertMeshMultiMaterial(mesh, model, index, node_global_transform));
                had.insert(index);
            }
        }

        return indices;
    }
```

The only change is the second check in the if to make sure sizes match.

What do you think?
I'm building on WIndows 7 64bits, targeting Windows 64 bits on Visual Studio 2013.

Regards,

**Comment by acgessler** [comment]
Does this make the model load without errors?

**Comment by promethe42** [comment]
> Does this make the model load without errors?

Yes.

The only comparison point I have is a 3DS with around 15% more meshes. But I suspect those meshes have no faces (which was kind of the problem here), plus the 3DS has other artifacts such as corrupted faces (might be related?). So as far as I can tell "for now" it "looks like" the final model is not missing anything but I'm not sure at 100% yet. I'll try to confirm this tomorrow with our tech-artist.

Another issue we have is that some transforms are off in the FBX. I'll investigate and report in another issue if needed.

Regards,

**Comment by promethe42** [comment]
Want our pull request for this?

**Comment by acgessler** [comment]
Yes, please. Sorry for the delay.

**Comment by kimkulling** [comment]
Fixed.
