### ISSUE TITLE
Bug: Unable to get mesh name, returns blank string

### ISSUE THREAD

**Issue by benjysugi** [assimp/assimp#4802]
**Describe the bug**
When I try use `->mName->C_Str()` on a `aiMesh` I only get a blank string

**To Reproduce**
- Export as OBJ
- Use assimp to import
![image](https://user-images.githubusercontent.com/61796469/202797106-8f75424d-4de9-4f3c-bd37-06c440fdf053.png)

**Expected behavior**
Expected to get mesh name

**Screenshots**
![image](https://user-images.githubusercontent.com/61796469/202796979-8bd4761d-2b42-4509-982d-1026e480220b.png)

**Platform (please complete the following information):**
 - OS: Windows 10
- Version: 3.0.0 from NuGet

**Comment by benjysugi** [comment]
> This issue is already fixed. Unfortunately, you are using a real old version of the assimp-library. Currently we are using 5.2.5 . The .NET port seems to be outdated.
> 
> Can you try to update this?

This is the latest version on NuGet at the time of writing
![image](https://user-images.githubusercontent.com/61796469/203266800-1a12c205-2cf8-4c28-b950-696827fe014a.png)

**Comment by kimkulling** [comment]
Try this https://www.nuget.org/packages/AssimpNet/5.0.0-beta1

**Comment by benjysugi** [comment]
> Try this https://www.nuget.org/packages/AssimpNet/5.0.0-beta1

This is for .NET, I'm working with C++

**Comment by kimkulling** [comment]
If you work with c++ just use the source release and you should be fine. There is a hunter mirror available as well.
