### ISSUE TITLE
Bug: Unable to build from source

### ISSUE THREAD

**Issue by NikolaosSopiadis** [assimp/assimp#4811]
When I try to build it from source it fails. There are thousands of errors concerning libraries such as math.h, stdlib.h, stdio.h etc.
I have tried versions 3.3.1 and 5.2.5(latest release) and get the same results. I can build other libraries just fine, but not assimp.
I am using the latest release of MSYS2 MINGW64 (20221028) as well as the latest version of VisualStudio 2022
OS: windows 10 21H2

![errors](https://user-images.githubusercontent.com/99847949/204092089-31fbc361-be6c-4eaa-beab-4b0f82f11d4e.png)

**Comment by kimkulling** [comment]
Is your VS2022 installation ok? Which SDK is in use?

**Comment by kimkulling** [comment]
Closed as deprecated.
