### ISSUE TITLE
Bug: NullRefernceException

### ISSUE THREAD

**Issue by MrScautHD** [assimp/assimp#4812]
**Describe the bug**
![Unbenasfdasdfannt](https://user-images.githubusercontent.com/65916181/204127890-59d5e940-8e0d-47bf-b415-98731bf57b46.png)

**Platform (please complete the following information):**
 - Windows 11
 - Chrome
 - 4.1.0

**Comment by kimkulling** [comment]
Seems to be a problem with an outdated version. Any chance to update to 5.2.5?

**Comment by kimkulling** [comment]
I will close this issue. Currently, there is a new version of assimp supported for .NET.

Unfortunately, the latest version of assimp are not supported for .NET because we are lacking on developer. If anyone is interested it would be gret to get some input.

Kim
