### ISSUE TITLE
Bug: Cumulative mTransform of a node doesn't match bone's mOffsetMatrix

### ISSUE THREAD

**Issue by CatoNator** [assimp/assimp#4823]
Apologies for the old version, Github apparently posts an issue if you press enter anywhere within a bug report tab.

I'm not entirely sure if this is a bug. I'm using assimp to convert meshes from various formats to my own proprietary one, but the unusual skeletal structure in assimp is causing some strange behaviour for me.

The two values I keep around for the skeleton are the bone's Transform (aiNode->mTransform in assimp) and the Inverse Bind Matrix (aiBone->mOffsetMatrix). The inverse bind matrix seems to make the transition properly, but the transforms don't - there seems to be a lot more offset that intentional.

The final world matrix is calculated using the formula
`FinalMatrix = CurrBone->InverseBindMatrix * WorldMatrix * Model->NodeMatrix;`

In which Inverse Bind is the one detailed above, and NodeMatrix is the inverse of the root node transform (usually just identity). The world matrix is the cumulative hierarchical transform:

`WorldMatrix = ParentWorldMatrix * CurrBone->Transform;`

Here's some screenshots:

The model with no transforms applied - all bone matrices are identity:
![notransforms](https://user-images.githubusercontent.com/11560295/205295381-089aa1de-ab20-4eda-8c6c-72e2fb53deb4.png)

Only the inverse bind applied (seems to be correct)
![inversebind](https://user-images.githubusercontent.com/11560295/205295339-3253e970-ade7-4567-a7d6-807d9305d457.png)

Full cumulative transformation applied. Should be t-pose, if I'm not mistaken:
![alltransforms](https://user-images.githubusercontent.com/11560295/205296011-12deb134-d184-4c15-9342-362be86d9f35.png)

Thanks in advance.

**Comment by CatoNator** [comment]
I swear github issues are some sort form of rubber ducky problem solving, but with a level of divine intervention mixed in. I found out my matrix multiplication was all sorts of messed up. The issue has been solved, and was not a problem in assimp.

**Comment by kimkulling** [comment]
Not to worry, thanks for sharing that with us.
