### ISSUE TITLE
Trubble including assimp

### ISSUE THREAD

**Issue by FratexEn** [assimp/assimp#4827]
**Describe the bug**
I have a header file where I include Assimp files.

file.h
```
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
```

When I include this file in .cpp file I don't have any errors 
file.cpp
```
#include "file.h"
```

But when I include same .h file in the header file I get a compilation error
otherfile.h
```
#include "file.h"
```
Error
```
Cannot open include file: 'assimp/Importer.hpp': No such file or directory
```

I'm not sure if I have forgotten to do something or how to resolve this issue, but I would be thankful for any help.

**Comment by kimkulling** [comment]
You need to add the asset-importer include folders to your compiler like:

`g++ -I<folder>`

Just check your compiler how to set this up.
