### ISSUE TITLE
aiProcess_LimitBoneWeights "removes empty bones"

### ISSUE THREAD

**Issue by vergol** [assimp/assimp#4840]
Can you consider removing this part?
https://github.com/assimp/assimp/blob/de83245f4211c09e52e0298a28a8e61ccd55b0fd/code/PostProcessing/LimitBoneWeightsProcess.cpp#L173
Or at least check for AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES here?

**Comment by kimkulling** [comment]
Fixed!
