### ISSUE TITLE
Bug: Vector subscript out of range

### ISSUE THREAD

**Issue by UntitledOutput** [assimp/assimp#4849]
**Describe the bug**
I'm trying to update a library that uses assimp. It hasn't been updated since 2020. I added the updated library to my project in Visual Studio 2022, and when I build and run my project, there's an error coming from a Assimp DLL file from the latest build.

**To Reproduce**
1. Go to [this repository.](https://github.com/Gamerfiend/raylib-3D)
2. Click on '[r3d.h](https://github.com/Gamerfiend/raylib-3D/blob/master/r3d.h)'.
3. Download this file
4. Add the header file to your project, and update as needed. **You do need** [raylib](https://github.com/raysan5/raylib).
5. Build project using [Visual Studio 2022](https://visualstudio.microsoft.com/vs/)

**Expected behavior**
I expect it to run without any errors.

**Screenshots**
![2022-12-23](https://user-images.githubusercontent.com/79727016/209348835-cffd8fc5-8470-4b53-824e-4f919a527f5b.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version 11

**Additional context**
I'm using assimp to load a fbx file, since raylib doesn't support fbx files. I'm expecting the library above (r3d.h) to cast an aiScene from Assimp to a Model from Raylib.

**Comment by kimkulling** [comment]
HI, which assimp-version do you use?

**Comment by UntitledOutput** [comment]
The latest version.

**Comment by kimkulling** [comment]
Do you have an example file to reproduce the issue?

**Comment by UntitledOutput** [comment]
Such as what? The `r3d.h` file, or a main program?

**Comment by UntitledOutput** [comment]
I found the problem, for some reason FBX models that have been ran through [FBX Converter](https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives) return a vector error.
