### ISSUE TITLE
Bug: (minor) Compile warning in scene.h

### ISSUE THREAD

**Issue by shimaowo** [assimp/assimp#4854]
**Describe the bug**
There is a compiler warning about a signed/unsigned mismatch that is generated due to [this code](https://github.com/assimp/assimp/blob/master/include/assimp/scene.h#L436) in scene.h.

The function uses an int as a hacky optional value, but then returns an unsigned int in the main case. In general, this will trigger a project-level warning even if assimp files are treated as system headers.

A cast is the simple fix, a less-hacky rewrite the correct one, but since this method is effectively external-only, I wasn't sure what would be preferable.

**To Reproduce**
1. Include assimp in any project.
2. Build the project.

**Expected behavior**
Assimp doesn't build with unnecessary warnings.

**Platform (please complete the following information):**
Any

**Comment by kimkulling** [comment]
Thanks for the hint. A fix is on its way.
