### ISSUE TITLE
Bug: .PLY comments support

### ISSUE THREAD

**Issue by jonathanpokrass** [assimp/assimp#4866]
**Describe the bug**
.ply file parser fails when there is a comment after the scene definition,
 example file:
```
ply
format binary_little_endian 1.0
element vertex 1
comment Points
property float x
property float y
property float z
end_header
000000000000
```
error message:

> “ERROR: Failed to load file: Invalid .ply file: Unable to extract mesh data” 

without the comment (line 4), all is working.

**Comment by PencilAmazing** [comment]
Should assimp discard comments or attempt to preserve them? Does the internal assimp format support comments?
