### ISSUE TITLE
Clarifying minimal C++ standard

### ISSUE THREAD

**Issue by RedSkittleFox** [assimp/assimp#4869]
**Is your feature request related to a problem? Please describe.**
I've stumbled across this piece of code.
https://github.com/assimp/assimp/blob/33c32b6b3598a3464c6cae350a18384f6c759222/code/AssetLib/FBX/FBXTokenizer.h#L157
```cpp
// XXX should use C++11's unique_ptr - but assimp's need to keep working with 03
typedef const Token* TokenPtr;
typedef std::vector< TokenPtr > TokenList;
```

Is assimp actually c++03 compliant? If not, then the minimal standard version should be picked and explicitly stated. Some pieces of code could (and should) be modernized. 

**Describe the solution you'd like**
Make the minimally required c++ standard version C++11 or (preferably) C++14 and make it explicit to users and developers.

**Comment by kimkulling** [comment]
The comment is just deprecated, C++11 is the minimum.

**Comment by krishty** [comment]
A copy of the comment you removed in 2d37f49f51e022d3862f9e3e55d9353fa229a80e is still present at https://github.com/assimp/assimp/blob/master/code/AssetLib/FBX/FBXParser.h#L65
