### ISSUE TITLE
3DS export Texture not working

### ISSUE THREAD

**Issue by Madrich** [assimp/assimp#487]
I'd tried to use the new 3ds export. The mesh geometrie can be exported successfully. Using texture, the 3d file can not be opened anymore (SketchUp, Blender). Please verify ....

**Comment by acgessler** [comment]
Can you provide a sample file?

**Comment by Madrich** [comment]
Gut it via mail ?

**Comment by acgessler** [comment]
Got it. I'll have a look.

**Comment by Madrich** [comment]
Solved?

**Comment by acgessler** [comment]
I tried and the 3DS Exporter in the head version correctly exports it such that open3mod and Blender read the textures correctly.

**Comment by acgessler** [comment]
Please re-open if needed.
