### ISSUE TITLE
Bug: Assimp 5.2.5 Reader Crash on ply (Double Precision) 

### ISSUE THREAD

**Issue by Nosenzor** [assimp/assimp#4871]
**Describe the bug**
Hi Here,
I compiled assimp 5.2.5  with ASSIMP_DOUBLE_PRECISION.
Assimp crash on ReadFile on the attached file.
`Assimp::Importer importer;
    
    const aiScene* scene = importer.ReadFile(iInputFile.string(),
                                             aiProcess_OptimizeGraph |
                                               aiProcess_Triangulate |
                                               aiProcess_JoinIdenticalVertices); `

I will try to reproduce with another platform and add a comment later here.
**To Reproduce**
Compile Assim

**Expected behavior**
No Crash ;-)

**Screenshots**

**Platform (please complete the following information):**
 - OS: Mac OS 13.1
 Compiler :
 - Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0

**Additional context**
[73612.ply.zip](https://github.com/assimp/assimp/files/10391212/73612.ply.zip)

**Comment by Nosenzor** [comment]
Reproduced on MacOs 10.15.7 (intel) with Apple clang version 12.0.0 (clang-1200.0.32.29)
[libassimpd.5.dylib] Assimp::TriangulateProcess::TriangulateMesh(aiMesh*) 0x0000000106076570
[libassimpd.5.dylib] Assimp::TriangulateProcess::Execute(aiScene*) 0x0000000106075d99
[libassimpd.5.dylib] Assimp::BaseProcess::ExecuteOnScene(Assimp::Importer*) 0x0000000105fbd13e
[libassimpd.5.dylib] Assimp::Importer::ApplyPostProcessing(unsigned int) 0x0000000105fd03e3
[libassimpd.5.dylib] Assimp::Importer::ReadFile(char const*, unsigned int) 0x0000000105fcee85
it looks like an out of bound access. I don't have yet  the exact line that leads to the crash.

**Comment by Nosenzor** [comment]
Reproduced on Windows too and it gives me the line of crash : 
            // Collect all vertices of of the polygon.
            for (tmp = 0; tmp < max; ++tmp) {
                **temp_verts3d[tmp] = verts[idx[tmp]];**
            }

tmp=3
max=61
idx[tmp]=9175808

**Comment by kimkulling** [comment]
Thanks for your investigations. Seems to be not a crash anymore when using the latest master. But the importer for double precision is still not ok.

**Comment by Nosenzor** [comment]
I will update my local assimp copy with master and check that asap.
What do you mean by "But the importer for double precision is still not ok." ? I've seen in code hard-coded "float" (ie parts are not using ai_real, is it the problem you are thinking about ?

**Comment by Nosenzor** [comment]
I still have the crash even using latest master.

**Comment by TinyTinni** [comment]
It seems it has something do to with the `aiProcess_JoinIdenticalVertices` option/algorithm. Without the option, I cannot reproduce the crash. With the option, I can reproduce it.

**Comment by TinyTinni** [comment]
Ok 2nd try ;)

The PLY file has a \r\n newline again like in https://github.com/assimp/assimp/issues/3711
But the fix from the PR here https://github.com/assimp/assimp/pull/3981 vanished (the buffer erasing at 504pp.)

I couldn't figure out why it was removed, but when I reinsert it, the mesh loads again.

**Comment by Nosenzor** [comment]
Excellent news ! Thank for that. Should we close the issue, then ?

**Comment by kimkulling** [comment]
It was already closed :-).
