### ISSUE TITLE
Bug: mMethod not type safe (PR ready to merge)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#4874]
`aiMesh::mMethod` is meant to correspond to a value in `enum aiMorphingMethod` but is default initialized to zero, which is not a valid value in that enum.

As an interim improvement, convert the type of `mMethod` from `unsigned int` to `enum aiMorphingMethod` and provide a valid enum value at `0` as a clue that additional work may be required for importers other than Collada (e.g. gltf)

PR #4873 (very simple, 3 lines in 1 file) is ready to go (all checks passed) and will fix this once merged

Related: #4320

**Comment by tellypresence** [comment]
PR was merged, thank you

**Comment by kimkulling** [comment]
Right, thanks!
