### ISSUE TITLE
Accident or Intention? M3D Disabled

### ISSUE THREAD

**Issue by krishty** [assimp/assimp#4881]
M3D import/export have been disabled for over a year. In `CMakeLists.txt`, several flags for that are hard-coded and unit tests are commented out.
The commits have no issue or explanation attached. See e.g. f48731622bfa8ed7725465863d10bfde9d71e99c, fc0617280eed3fd951e1cd097d5d056fb36823e7.

I can find two open issues with M3D: https://github.com/assimp/assimp/issues/3777 and https://github.com/assimp/assimp/issues/3910.

Were these the reason to disable M3D? Or something else entirely? Any reasons against re-enabling it?

**Comment by krishty** [comment]
Found the issue: https://github.com/assimp/assimp/issues/4126#issuecomment-964247598

M3D is disabled because Assimp's copy diverged too far from the upstream version to be maintainable.

This is the very definition of tech debt, so I recommend we handle it in this issue if there is not yet another one.

**Comment by turol** [comment]
The maintainer was also extremely confrontational and unwilling to take feedback or conform to our coding standards.

**Comment by krishty** [comment]
Is there a central place where feedback and problems have been collected? Or is it just the three issues linked above?

**Comment by turol** [comment]
I think the relevant issues were #2803 and #3848

**Comment by kimkulling** [comment]
We can use this one to trace all known issues.

**Comment by bztsrc** [comment]
> The maintainer was also extremely confrontational and unwilling to take feedback or conform to our coding standards.

This isn't true at all. At first I did everything that you asked, but then you began to demand absurd things.

Your feedback was "thread_local isn't a C++ keyword", and "[magic numbers are BAD.](https://github.com/assimp/assimp/issues/2803#issuecomment-562921367)". This isn't something that you would expect from a serious programmer working on a library that is dealing with binary files. Period.

You have even criticized even the part that was written by Sean Barrett, and RichardTea made shady and [unreviewable modifications](https://github.com/assimp/assimp/pull/2805#issuecomment-562916219) and [he put outright errors into my code](https://github.com/assimp/assimp/pull/3999).

BTW, loading M3D files through Assimp requires at least twice as much memory and 1000x times more (no mistake, thousand times more) allocations than using the M3D SDK, [valgrind outputs here](https://gitlab.com/bztsrc/model3d/-/tree/master/assimp), so I've decided not to support Assimp, and I recommend everyone to avoid this bugpile.

Have a nice day,
bzt

**Comment by tellypresence** [comment]
This is an unfortunate situation, seems like both the assimp project and the M3D format stand to benefit by the combined reach (one more format that assimp can handle and more exposure for M3D).  Hope there's some way this can be resolved amicably.

In the meantime I've had to remove M3D from the list of supported formats in my app to reduce potential user confusion from `No suitable reader found` error messages:disappointed:

**Comment by bztsrc** [comment]
@tellypresence: that's okay. Assimp is very limited, painfully slow and eats up huge amount of memory. I don't want people to incorrectly associate these Assimp problems with M3D anyway. It is much better if they use the M3D SDK, which is fully featured, extremely fast and memory efficient.

(Just one example: in the M3D SDK bones are matched using the fastest possible way, O(1) indexing; while Assimp requires an inefficient O(n*m*p) node tree walk with matching strings...)

Cheers,
bzt
