### ISSUE TITLE
How to get the type of animation interpolation?

### ISSUE THREAD

**Issue by Wicked-Prick** [assimp/assimp#4890]
Good afternoon. I want to test this example with https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest different type of actions. Right now, when exiting assimp, I can't get information about the type of interpolation that should be used for each specific action. The props "proestate" is always 0. Also, I want to clarify that I use the interface [assimpjs ](https://github.com/kovacsv/assimpjs)

**Comment by Intro1997** [comment]
I also have the same question. I read the source code of [glTF2Importer.cpp](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp) and found that assimp skipped the cubic spline tangent data on [line 1317](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp#L1317) when reading animation data. In fact, assimp has read interpolation type into [Animation::Sampler](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Asset.h#L997) object. I tried to find an API to export the relevant data but I failed. It seems like assimp does not support cubic spline interpolation now? Or maybe I missed some code.

**Comment by Intro1997** [comment]
> I also have the same question. I read the source code of [glTF2Importer.cpp](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp) and found that assimp skipped the cubic spline tangent data on [line 1317](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp#L1317) when reading animation data. In fact, assimp has read interpolation type into [Animation::Sampler](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Asset.h#L997) object. I tried to find an API to export the relevant data but I failed. It seems like assimp does not support cubic spline interpolation now? Or maybe I missed some code.

Oh, I'm sorry, I had a problem using the C++ interface.

**Comment by kimkulling** [comment]
Currently the interpolation method is always linear. it is an implicite precondition you need to know.

**Comment by kimkulling** [comment]
We will add the interpolation mode to make the interface more explicite.
