### ISSUE TITLE
Improve selection of unit tests to build / run

### ISSUE THREAD

**Issue by waebbl** [assimp/assimp#4902]
**Is your feature request related to a problem? Please describe.**
While working on a workaround for issue #4286 for Gentoo Linux, I noticed that collada related unit tests start to fail. The workaround just passes `-DASSIMP_BUILD_COLLADA_{EXPORTER,IMPORTER}=OFF` to cmake to disable the collada module for possible security issues until it's fixed. The unit tests which I needed to disable can be seen in my PR for Gentoo[1].
We currently build assimp with the default settings, but it's possible, that we will provide options for the user to decide which importers / exporters or other modules they want to enable / disable, as far as the build system supports it, so a proper selection of the testing framework would be crucial.

**Describe the solution you'd like**
The unit tests should respect the options passed to cmake and build / run only those unit tests which are configured. One way to do this could be to add guards in the test/CMakeLists.txt file for all the available importers / exporters or other configurable modules and add, build and run the respective source files only if these options are set.

**Describe alternatives you've considered**
For Gentoo we have the alternative to completely disable testing, which is no usable option.

**Additional context**

[1] https://github.com/gentoo/gentoo/pull/29231/files#diff-14134a3deae6a274139822cd4358c9eb7a1675661eb820364baa837df53338ac

**Comment by kimkulling** [comment]
You can use the gtest-filer option:

`unit --gtest_filter=testname`
