### ISSUE TITLE
Bug: Issue 54900 in oss-fuzz: assimp:assimp_fuzzer: Abrt in aiMesh::~aiMesh

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#4918]
Status: New
Owner: ----
CC: kim.k...@[googlemail.com](http://googlemail.com/) 
Labels: Restrict-View-Commit ClusterFuzz Reproducible Stability-UndefinedBehaviorSanitizer Engine-libfuzzer OS-Linux Proj-assimp Reported-2023-01-07
Type: Bug

New issue 54900 by ClusterFuzz-External: assimp:assimp_fuzzer: Abrt in aiMesh::~aiMesh
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54900

Detailed Report: https://oss-fuzz.com/testcase?key=5966142718214144

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_ubsan_assimp
Platform Id: linux

Crash Type: Abrt
Crash Address: 0x053900082fb5
Crash State:
  aiMesh::~aiMesh
  std::__1::unique_ptr<aiMesh, std::__1::default_delete<aiMesh> >::reset
  std::__1::unique_ptr<aiMesh, std::__1::default_delete<aiMesh> >::~unique_ptr
  
Sanitizer: undefined (UBSAN)

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_assimp&range=202206020602:202206030600

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5966142718214144

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by turol** [comment]
Did not fix it.

**Comment by turol** [comment]
Valgrind trace:

```
Invalid write of size 8
   at 0x3B536C: Assimp::ObjFileImporter::createVertexArray(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, unsigned int, aiMesh*, unsigned int) (ObjFileImporter.cpp:501)
   by 0x3B564C: Assimp::ObjFileImporter::createTopology(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, unsigned int) (ObjFileImporter.cpp:388)
   by 0x3B6683: Assimp::ObjFileImporter::createNodes(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, aiNode*, aiScene*, std::vector<aiMesh*, std::allocator<aiMesh*> >&) (ObjFileImporter.cpp:271)
   by 0x3B68E6: Assimp::ObjFileImporter::CreateDataFromImport(Assimp::ObjFile::Model const*, aiScene*) (ObjFileImporter.cpp:192)
   by 0x3B6F7A: Assimp::ObjFileImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) (ObjFileImporter.cpp:143)
   by 0x2EC871: Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) (BaseImporter.cpp:110)
   by 0x21DFDB: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:723)
   by 0x216CF7: ReadFile (Importer.hpp:670)
   by 0x216CF7: ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Main.cpp:307)
   by 0x219ECA: Assimp_Info(char const* const*, unsigned int) (Info.cpp:344)
   by 0x21735E: main (Main.cpp:222)
 Address 0x4de7ad0 is 0 bytes after a block of size 96 alloc'd
   at 0x484220F: operator new[](unsigned long) (vg_replace_malloc.c:640)
   by 0x3B4DB3: Assimp::ObjFileImporter::createVertexArray(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, unsigned int, aiMesh*, unsigned int) (ObjFileImporter.cpp:420)
   by 0x3B564C: Assimp::ObjFileImporter::createTopology(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, unsigned int) (ObjFileImporter.cpp:388)
   by 0x3B6683: Assimp::ObjFileImporter::createNodes(Assimp::ObjFile::Model const*, Assimp::ObjFile::Object const*, aiNode*, aiScene*, std::vector<aiMesh*, std::allocator<aiMesh*> >&) (ObjFileImporter.cpp:271)
   by 0x3B68E6: Assimp::ObjFileImporter::CreateDataFromImport(Assimp::ObjFile::Model const*, aiScene*) (ObjFileImporter.cpp:192)
   by 0x3B6F7A: Assimp::ObjFileImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) (ObjFileImporter.cpp:143)
   by 0x2EC871: Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) (BaseImporter.cpp:110)
   by 0x21DFDB: Assimp::Importer::ReadFile(char const*, unsigned int) (Importer.cpp:723)
   by 0x216CF7: ReadFile (Importer.hpp:670)
   by 0x216CF7: ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Main.cpp:307)
   by 0x219ECA: Assimp_Info(char const* const*, unsigned int) (Info.cpp:344)
   by 0x21735E: main (Main.cpp:222)
```
https://github.com/assimp/assimp/blob/333f7d5ee0646882930f50108a7bd84aa9acf607/code/AssetLib/Obj/ObjFileImporter.cpp#L501

writes past end of buffer allocated at 
https://github.com/assimp/assimp/blob/333f7d5ee0646882930f50108a7bd84aa9acf607/code/AssetLib/Obj/ObjFileImporter.cpp#L420

`mNumVertices` is 8.

**Comment by kimkulling** [comment]
This issue is already fixed. I have just checked the google issue report.
