### ISSUE TITLE
AssbinImporter crash loading assbin files in release mode

### ISSUE THREAD

**Issue by aardanza** [assimp/assimp#492]
In all reading struct block, the header reading code is bad for release mode:

ai_assert( Read< uint32_t >(stream) == ASSBIN_CHUNK_AIMATERIAL);
/_uint32_t size =_/ Read<uint32_t>(stream);

With these code lines we are reading two lines in debug mode and one in release.

What about using something like thise:

if (Read< uint32_t >(stream) != ASSBIN_CHUNK_AIMATERIAL)
        throw DeadlyImportError("Magic chunk identifiers are wrong!");

**Comment by acgessler** [comment]
This clearly shows we should also add assbin files to regression.

**Comment by kimkulling** [comment]
I already fixed this behaviour. I will close this issue.
