### ISSUE TITLE
Unable to load bundled .ter files: "End of file or read limit was reached"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#4931]
Failing to load these two bundled test models:
[`test/models/TER/RealisticTerrain.ter`](https://github.com/assimp/assimp/blob/master/test/models/TER/RealisticTerrain.ter)
[`test/models/TER/RealisticTerrain_Large.ter`](https://github.com/assimp/assimp/blob/master/test/models/TER/RealisticTerrain_Large.ter)

On 64 bit, failing fast w/error message: `End of file or read limit was reached`
On 32 bit, perpetual load spinner -- doesn't crash, but never finished loading...

**Comment by tellypresence** [comment]
Apologies, this is most likely a dupe of #3093

**Comment by turol** [comment]
Duplicate.

**Comment by tellypresence** [comment]
Following merge of PR #4934 the test models again load successfully.

(Some vertex indexing issues, as can be observed from the spurious connecting lines in the screenshots, but that's probably something wrong with my OpenGL ES implementation)

<table>
<tr><th><a href="https://github.com/assimp/assimp/blob/master/test/models/TER/RealisticTerrain.ter">test/models/TER/RealisticTerrain.ter</a></th><th><a href="https://github.com/assimp/assimp/blob/master/test/models/TER/RealisticTerrain_Large.ter">test/models/TER/RealisticTerrain_Large.ter</a></th></tr>
<tr><td><img src="https://user-images.githubusercontent.com/26958898/216791359-8c57f91a-97db-49ea-bfec-830009ee8108.png" alt="realistic_terrain_Screenshot_20230204-135553" width=320</td><td><img src="https://user-images.githubusercontent.com/26958898/216791356-b0232e13-460f-426e-ba15-e4c724d4acc4.png" alt="realistic_terrain_large_Screenshot_20230204-135829" width=320</td></tr>
</table>
