### ISSUE TITLE
How to create aiTextures when creating aiScene from scratch?

### ISSUE THREAD

**Issue by jtressle** [assimp/assimp#4937]
Hi,

First off, great library! I'm wanting to create a scene with one mesh from scratch. I'm able to create a mesh with vertices, vertex normals, vertex texture coordinates, and face indices.  I'm trying to add embedded textures using aiTexture objects.  

Is there a good example how to load and embed aiTextures?  So far, I've seen this following issue, but it does not mention textures.

https://github.com/assimp/assimp/issues/203

Thanks

**Comment by kimkulling** [comment]
Thanks for the nice words. Currently, assimp is using the stb-lib for loading data. Unfortunately, this methods are currently not available via a public API. For your own you can load the data my yourself and create a texture in your scene instance. Embedded textures needs to have * as prefix.

**Comment by rlczddl** [comment]
@jtressle how to?can you post a example?
