### ISSUE TITLE
Bake Transformation

### ISSUE THREAD

**Issue by Madrich** [assimp/assimp#494]
Hi folks,
an application requires to have all transformations in a XFile the identity matrix.
I know, thats stupid. I can do this in the XFile Exporter, but maybe its better to write a new postprocessing step, to apply the chain of transformations to all coordinates and normals and provide this functionality in general.
What do you think?

**Comment by Madrich** [comment]
Or is this alrady implemented ?

aiProcess_PreTransformVertices
???

**Comment by acgessler** [comment]
Yes, `aiProcess_PreTransformVertices` does exactly this. `aiProcess_OptimizeScene` only applies it when animations are not affected and meshes not shared.
