### ISSUE TITLE
Bug:Importing the model, removing duplicates vertices is useless

### ISSUE THREAD

**Issue by kingui1106** [assimp/assimp#4942]
**Describe the bug**
Use `assimp_cmd` import model with `assimp_cmd.exe info dragon.obj` .And I get the total vertices 281552.
But I use [meshlab ](https://www.meshlab.net/)open the same obj file. I get the total vertices 50000.
Removing duplicate vertices is a little useful, but not as effective.

**ScreenShot**

1. Below is `assimp_cmd` output.

```
Memory consumption: 19698188 B
Nodes:              2
Maximum depth       2
Meshes:             1
Animations:         0
Textures (embed.):  0
Materials:          1
Cameras:            0
Lights:             0
Vertices:           281552
Faces:              100000
Bones:              0
Animation Channels: 0
Primitive Types:    triangles
Average faces/mesh  100000
Average verts/mesh  281552
Minimum point      (-7.046700 0.000000 -3.151300)
Maximum point      (7.046700 9.939900 3.151300)
Center point       (0.000000 4.969950 0.000000)

```

2. meshlab open 
![image](https://user-images.githubusercontent.com/21022679/217414367-322a7c75-4407-481f-9aaf-cadd33b59420.png)

**Platform (please complete the following information):**
 - OS: [windows 10]

**Resource file**
[dragon.obj](https://drive.google.com/file/d/1aOhW4azzptrKWfliZJPAcLVUz67BbRsl/view?usp=sharing)

**Comment by tellypresence** [comment]
Sample model, downloaded from above link and attached directly*
[dragon.zip](https://github.com/assimp/assimp/files/10686764/dragon.zip)
 (had to zip to be able to attach here)

*to reduce reliance on external storage so model more likely to still be available in a couple of years

**Comment by kimkulling** [comment]
Do you know if any optimizations are in use when using meshlab? Good to knwo that we will have some place for optimization.

**Comment by kingui1106** [comment]
The original obj file contains 50,000 non-duplicate points, and  100,000 faces.
meshlab reads the file directly without doing anything.
The following results were obtained using assimp:

1. with pFlags= 0. I get 300,000 vertices. The point is three times the face. Point is repeated.
```
const aiScene* scene = globalImporter->ReadFile(path,0);
----------------------------------------------------------------
output:
Vertices:           300000
Faces:              100000
```
 2. with `pFlags= aiProcessPreset_TargetRealtime_Quality`.  I get  281,552  vertices. It should be 50,000 points after processing.
```
const aiScene *scene = globalImporter->ReadFile(path, aiProcessPreset_TargetRealtime_Quality);
----------------------------------------------------------------
output:
Vertices:           281552
Faces:              100000
```
I didn't describe it well. Can you understand. So I think removing duplicates verticals is useless.
Thanks.
> Do you know if any optimizations are in use when using meshlab? Good to knwo that we will have some place for optimization.

**Comment by kimkulling** [comment]
We are generating vertex- and face structures optimized for the rendering. That is the reason for getting so much more vertices.
You can check this link to learn more about it: 
[Why Assimp generates so many vertices](https://www.gamedev.net/forums/topic/633306-assimp-number-of-vertices/)

I haven't checked if Meshlab shows you the vertex count of the imported model or the vertex count created on your GPU.
