### ISSUE TITLE
Regression: Bob.md5mesh

### ISSUE THREAD

**Issue by acgessler** [assimp/assimp#495]

**Comment by acgessler** [comment]
Also (probably same root cause) SimpleCube.md5mesh

**Comment by skyjake** [comment]
Is this what you're seeing, too? Seems to affect all MD5 models.
![md5_regression](https://cloud.githubusercontent.com/assets/1225742/8607411/5175644a-269b-11e5-9934-3f271153ed2e.jpg)

**Comment by kimkulling** [comment]
This issue was fixed, so I will close it. Just checked th sample model.
