### ISSUE TITLE
Bug: Possible MDL load regression

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#4953]
I remember being able to load this bundled test model a couple of years ago:
[`models-nonbsd/MDL/IDPO (Quake1)/gijoe.mdl`](https://github.com/assimp/assimp/blob/master/test/models-nonbsd/MDL/IDPO%20(Quake1)/gijoe.mdl)

In recent version of assimp, can't seem to get it to load (no error, just sits there without any apparent progress).  Is anyone able to confirm or refute?

**Comment by tellypresence** [comment]
Looks like this is a dupe of an old bug I raised a while ago.  Seems to be an intermittent problem but not easily reproduced outside of my environment

**Comment by turol** [comment]
For me it fails to load with an error message. Can you find a working commit and bisect?

**Comment by tellypresence** [comment]
Strange.  Just built latest assimp ([ad2f068](https://github.com/assimp/assimp/commit/ad2f0682e71f8debb3ee9b2d08f7d10f9832cf87)) and model loaded right up.  Previously was testing against [487c03f](https://github.com/assimp/assimp/commit/487c03f547245fafdfe90fe5d8852f972f950b3f) from 4 Feb 2023 which was having the problem.

Guess something in the last couple of weeks addressed the issue?

Render when building against [ad2f068](https://github.com/assimp/assimp/commit/ad2f0682e71f8debb3ee9b2d08f7d10f9832cf87):
<img alt="assimp_issue_4953" src="https://user-images.githubusercontent.com/26958898/220056574-8276e284-d80d-425a-a935-a9a9f6c8bc55.png" width=320>
