### ISSUE TITLE
 Import gltf-Draco fail.

### ISSUE THREAD

**Issue by raochangping** [assimp/assimp#4958]
Hi，I am learning using Assimp to import gltf。But I found a problem，when i  import gltf-Draco, it failed.
I'm using the interface below:

```
                Assimp::Importer m_importer;
                m_assImpScene = m_importer.ReadFile(fileName,
                aiProcess_Triangulate //Triangulates all faces of all meshes
                | aiProcess_GenNormals  //Generate normals for meshes
                | aiProcess_OptimizeMeshes //reduce the number of meshes
                | aiProcess_OptimizeGraph); //optimize the scene hierarchy

```
Looking forward to your reply about this question.

**Comment by FlorianBorn71** [comment]
We got signal from our customers as well that draco compression support would be useful

**Comment by raochangping** [comment]
Thank you for replying. I found a solution by adding ASSIMP_BUILD_DRACO = TRUE.
But there's another problem. The current version 1.4.1 is too early about draco(https://github.com/google/draco).  The latest version is 1.5.6. Is the project plan updated?
Looking forward to your reply about this question.  @FlorianBorn71

**Comment by raochangping** [comment]
> We got signal from our customers as well that draco compression support would be useful

Thank you for replying. I found a solution by adding ASSIMP_BUILD_DRACO = TRUE.
But there's another problem. The current version 1.4.1 is too early about draco(https://github.com/google/draco). The latest version is 1.5.6. Is the project plan updated?
Looking forward to your reply about this question. @FlorianBorn71

**Comment by FlorianBorn71** [comment]
For clarity, my team is consumer of assimp as well, I just wanted to upvote your request ;-) Unfortunately, I'm not familiar with draco at all.

**Comment by Jackie9527** [comment]
> > We got signal from our customers as well that draco compression support would be useful
> 
> Thank you for replying. I found a solution by adding ASSIMP_BUILD_DRACO = TRUE. But there's another problem. The current version 1.4.1 is too early about draco(https://github.com/google/draco). The latest version is 1.5.6. Is the project plan updated? Looking forward to your reply about this question. @FlorianBorn71

Here is a PR [4978](https://github.com/assimp/assimp/pull/4978),  ready to upgrade version of draco to 1.5.6.
Looking forward to your replay, @raochangping and @FlorianBorn71 .

**Comment by kimkulling** [comment]
This update shall be good for you: https://github.com/assimp/assimp/pull/4978
