### ISSUE TITLE
FBX Animations: Support > 360 deg steps between keyframes

### ISSUE THREAD

**Issue by acgessler** [assimp/assimp#496]
Same problem as observed with Collada in #458.

**Comment by nopjia** [comment]
Been trying to track this issue, from #458
I saw there was a commit to subsample ff4e1d9446716a676874a68b00769ddeec8a1a8f
However, it seems I'm still seeing this issue with DAE import. Version 3.2.0
Any insight here?

**Comment by kimkulling** [comment]
Shall be fixed.
