### ISSUE TITLE
still working in windows xp! :)

### ISSUE THREAD

**Issue by mgarcia-org** [assimp/assimp#4972]
> Windows 2000 or higher. AssimpView should also run on older versions, with DirectX 9 installed, but this has never been tested. If you're a proud owner of such a version and AssimpView works for you, let us know.

![assimp-capt](https://user-images.githubusercontent.com/32156626/220220178-97b91b6d-c787-4b0a-a652-feadf08a0a6b.jpg)

Viewer seems to work okay, but I haven't used any other version, so I have nothing to compare it to.
It has issues finding textures and adding new ones, but replacing works fine.

Binaries and compiler info here:
https://archive.org/details/assimp-master-build-21-jan-2023-winxp

Horse is from Truespace 7.61 beta.

**Comment by kimkulling** [comment]
Nice!
