### ISSUE TITLE
Possible regression in IRR/IRRMESH loader

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#4987]
The information here was from early stage investigation, have moved results to #5014

**Comment by turol** [comment]
Looks like the failing models are UTF-16 and one working model (instancing.irr) is UTF-8. I suspect the new xml loader doesn't handle UTF-16.

**Comment by tellypresence** [comment]
@turol Thank you, that makes sense...similar situation with OBJ loader as detailed in #2063

**Comment by tellypresence** [comment]
Closing after #5166 merged
