### ISSUE TITLE
Crash when loading bundled X3D test model

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#4988]
When attempting to load bundled test model
[`test/models-nonbsd/X3D/Chevy/ChevyTahoe.x3d`](https://github.com/assimp/assimp/blob/master/test/models-nonbsd/X3D/Chevy/ChevyTahoe.x3d)

observing catastrophic crash, no useful error messages.

Can anyone confirm?

(I thought this model used to load OK, but now struggling to find the window when it did)

A bit of bisecting
<table>
<tr><th>Assimp commit hash</th><th>Errors/notes</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/90333340d6dffcda955038e1cd458c57fc88efc8">9033334</a><br>27 Feb 2023</td><td>Catastrophic crash</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/bbcefbd0348c5407e57f9f66a16a69b61159f537">bbcefb</a><br>28 Feb 2022</td><td>Catastrophic crash</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/9b535d1c159d8501a97f4399abf78e256afb29bb">9b535d1</a><br>31 Aug 2021</td><td>"No suitable reader found for the file format of file <...>X3D/Chevy/ChevyTahoe.x3d"</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/35c506fcf863ff8e01365cb76686b2010f6bd498">35c506f</a><br>30 May 2021</td><td>"No suitable reader found for the file format of file <...>X3D/Chevy/ChevyTahoe.x3d"</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/6ab2e8d558790059b18eb62bdfd44167b9117b2e">6ab2e8d</a><br>28 Feb 2021</td><td>Loader reports "Unable to load model: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there"</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/710dbba52dee0f4ac2f1e59a1f495ed287d88372">710dbba</a><br>28 Feb 2020</td><td>Catastrophic crash</td></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/e9eda062a17b1804a05134fe69a135a996413415">e9eda06</a><br>28 Feb 2019</td><td>Catastrophic crash</td></tr>
</table>

**Comment by turol** [comment]
Does not crash for me on 64-bit Linux. No problems with Valgrind, asan or ubsan.

**Comment by tellypresence** [comment]
Apologies, was an old bug that only got triggered for certain 3D model files.
