### ISSUE TITLE
Collada importer aiBone name mismatching aiNode name with whitespaces

### ISSUE THREAD

**Issue by jpx** [assimp/assimp#499]
If node names include whitespaces, corresponding bone names get truncated.
For instance node name "Right knee" leads to a bone with name "Right".

This causes impracticable to find an aiNode corresponding to the bone using the bone name through

```
aimesh->mBones[boneId]->mName.data
```

For instance with a node and an animation like

```
<node name="Right knee" id="Right knee" sid="Right knee" type="JOINT"><matrix sid="matrix">0.990971 -0.134074 0.000000 29.437080 0.134074 0.990971 -0.000000 0.000038 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 0.000000 1.000000</matrix><extra><technique profile="FCOLLADA"><visibility>1.000000</visibility></technique></extra>
...
<animation id="Right knee-anim" name="Right knee"><animation><source id="Right knee-Matrix-animation-input"><float_array id="Right knee-Matrix-animation-input-array" count="73">...
```

corresponding aibone->mName becomes "Right".

Used version of Assimp is 3.1.1.

Follows the header of test Collada file.

```
<?xml version="1.0" encoding="utf-8"?>
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
  <asset><contributor><author></author><authoring_tool>FBX COLLADA exporter</authoring_tool><comments></comments></contributor><created>2012-07-27T13:53:11Z</created><keywords></keywords><modified>2012-07-27T13:53:11Z</modified><revision></revision><subject></subject><title></title><unit meter="0.025400" name="centimeter"></unit><up_axis>Y_UP</up_axis></asset>

```

**Comment by acgessler** [comment]
Can you provide a complete example file? Preferrably, one we can distribute with assimp's test suite once the issue is resolved.

**Comment by jpx** [comment]
Here you may find the file which allowed me to produce the issue.
https://www.dropbox.com/s/sgv1cgqqehgmv91/chara.DAE?dl=0

**Comment by kimkulling** [comment]
I guess this issue is fixed right now.
