### ISSUE TITLE
Out-of-memory for some gltf exported with "Sketchup glTF Exporter by Centaur"

### ISSUE THREAD

**Issue by FlorianBorn71** [assimp/assimp#4998]
**Describe the bug**
Assimp seems to run into exactly the same issue that is described here:
[https://github.com/KhronosGroup/UnityGLTF/issues/197](https://github.com/KhronosGroup/UnityGLTF/issues/197)

**More details after my investigation:** Gltf allows to share the attribute reference between meshes. However, function glTF2Importer::ImportMeshes does not consider this and allocates the same buffer n times. Our sample model, exported by "Sketchup glTF Exporter by Centaur", has only 2M vertices, but it's shared across ~20k mesh parts **which results in allocating 20k * 2M vertices**.

I tried to hack in the sharing, but it will not work further down in the processing pipeline. I'm leaning towards shrinking the vertex array to the actual vertices that are used by the index buffer. I think similar stuff is one by the FBX importer?

Any suggestions?

**Comment by FlorianBorn71** [comment]
I have a suggested PR open here that reduces memory footprint for the customer model **by factor 1000x** (!)

https://github.com/assimp/assimp/pull/5003

GLTF Models without shared attributes won't profit from this fix.

Let me know what you think

**Comment by FlorianBorn71** [comment]
[SharedAttributesOOM.zip](https://github.com/assimp/assimp/files/11039567/SharedAttributesOOM.zip)

The attached zip contains a repro case gltf file. Without the fix, loading through Assimp passes out after allocating a few hundred GB of memory. With the fix, loading peaks at ~170MB, so more than 1000x improvement.

This is an artificially generated model to expose the problem, but our customer had a similar real model, where the fix saves > 1000x memory.

**Comment by kimkulling** [comment]
Fixed
