### ISSUE TITLE
[COLLADA] Support for <ph> (polygons with holes)?

### ISSUE THREAD

**Issue by asmaloney** [assimp/assimp#50]
The COLLADA parser does not support the &lt;ph&gt; element.

It looks like "polygons with holes" has been added to IFC using Clipper - perhaps this could be applied to COLLADA as well?

(Might be good to update Clipper too - 5.1.6 looks like it fixes some bugs. The one included with assimp is 4.8.8.)

**Comment by gbittoun** [comment]
Hi, we are currently experiencing problems with collada exports containing ph tags, is it going to be supported ?

Regards,

**Comment by kimkulling** [comment]
Honestly speaking hard to say: I do not have enough time in the moment to implement this. the data structure is not supporting this at the moment.

**Comment by agerrius** [comment]
I have encountered this issue as well. Would it be a work around to just process the polygons (<p>) and ignore the holes (<h>) inside the <ph> element for now? For my application that would be better than an exception.

I'm trying to study the code now to see if I can add this work around.

**Comment by kimkulling** [comment]
I will add a workaround for the handling. The feature will follow in the future, hopefully...

**Comment by kimkulling** [comment]
Cannot find a good example. Please reopen with an example.

**Comment by JaumeCalm** [comment]
What happened to this? I encountered this problem as well with the latest version as of today `5.4.3`.
