### ISSUE TITLE
CMake doesn't find Visual Studio debug files

### ISSUE THREAD

**Issue by danijar** [assimp/assimp#500]
When building and installing the Assimp library statically for Visual Studio, I get the following error. The needed file is located at `<build>/code/assimp.dir/Debug/vc120.pdb`, but the install script expects it at `<build>/code/Debug/assimpd.pdb`.

```
CMake Error at code/cmake_install.cmake:97 (file):
  file INSTALL cannot find
  "D:/repository/modurale/external/assimp/build/code/Debug/assimpd.pdb".
Call Stack (most recent call first):
  cmake_install.cmake:44 (include)
```

When I manually move and rename the file it works. How can this be fixed?

**Comment by abma** [comment]
does it work when you add this to CMakeLists.txt at the beginning?

    set(CMAKE_PLATFORM_HAS_INSTALLNAME 1)

had some similar error when using "ninja" to compile/install in a different project:

https://github.com/springlobby/springlobby/commit/b936da94460ab13e07a2ba4ebc6bbdac72c84b49

**Comment by kimkulling** [comment]
Should be fixed now.
