### ISSUE TITLE
Bug: Builld error when using assimp - include/assimp/types.h:79:13: fatal error: ../contrib/utf8cpp/source/utf8.h: No such file or directory

### ISSUE THREAD

**Issue by robertosfield** [assimp/assimp#5005]
I have built assimp master from source (10th March 2023) and installed it into a local install directory and then build [vsgXchange](https://github.com/vsg-dev/vsgXchange) that uses assimp but vsgXchange now fails with the error:

```
 18%] Building CXX object src/CMakeFiles/vsgXchange.dir/openexr/openexr.cpp.o
In file included from /home/robert/Install/include/assimp/Importer.hpp:60,
                 from /home/robert/Dev/vsgXchange/src/assimp/assimp.cpp:21:
/home/robert/Install/include/assimp/types.h:79:13: fatal error: ../contrib/utf8cpp/source/utf8.h: No such file or directory
   79 | #   include "../contrib/utf8cpp/source/utf8.h"
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

The utf8.h file is not installed by assimp's make install, so while assimp builds fine with the header in the local assimp/contrib/utf8cpp/source directory when building against the install assimp library the types.h that still references the relative path to the utf8.h fails.

I haven't walked back to older versions of assimp to see when this build regression occurred, but I know the previous stable release was working fine for me.

I presume with types.h will need to remove the offending include or have the utf8.h installed along with the rest of the assimp headers.

**Comment by droettger** [comment]
Please consider raising the priority of this to showstopper. This is breaking the build for multiple products.

**Comment by Omasyo** [comment]
The issue still exists, I've not been able to work around it. All attempts for a temporary fix gives me linker error.

Is anything still being done to rectify the issue.

**Comment by klein-j** [comment]
I ran into the same issue. I think it should not be hard to adjust the install script (probably it should depend on ASSIMP_USE_HUNTER?) but I am not familiar with its inner workings.

**Comment by jtressle** [comment]
This is also causing issues when installing on MacOS Sonoma.

**Comment by ziggycross** [comment]
Bump! also running into this problem on MacOS Ventura

**Comment by nattydread69** [comment]
Bump.
 Broken on ubuntu 22.04.3

**Comment by traversaro** [comment]
I guess this was fixed by https://github.com/assimp/assimp/pull/5250 .
