### ISSUE TITLE
Warning from MS Analyser in pugixml.

### ISSUE THREAD

**Issue by Nosenzor** [assimp/assimp#5013]
**Describe the technical debt**
A clear and concise description of what the tech debt is about.
Compilation on windows 10 unsigned Visual Studio 2022 with /analyzer give this worrying warning ...

Original warning message in French so I translated it : 

assimp\contrib\pugixml\src\pugixml.cpp(4472) : warning C28182: Dereference the NULL pointer. 'dit' contains the same NULL value as 'copy'.: Lines: 4431, 4432, 4434, 4436, 4437, 4439, 4445, 4447, 4449, 4451, 4453, 4455, 4456, 4439, 4445, 4447, 4449, 4465, 4471, 4472
**Better solution**
A clear and concise description of what you would expect.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by turol** [comment]
This is 3rd party code. We should not make changes to it. You should submit this report upstream and if they fix it we will get the fixed version when we update the library.

**Comment by Nosenzor** [comment]
Would upstream issue.

**Comment by kimkulling** [comment]
Right, anyway! Thanks a lot for figuring this out!
