### ISSUE TITLE
Model file corrupted by a8a1ca9 needs to be reverted (PR ready to merge)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5018]
Binary portion of bundled model file [`test/models/PLY/pond.0.ply`](https://github.com/assimp/assimp/blob/master/test/models/PLY/pond.0.ply) appears to have been corrupted by commit [`a8a1ca9`](https://github.com/assimp/assimp/commit/a8a1ca9894a38164f3111f57fddb887b3549ea60)

Should be reverted to earlier commit, may as well use the original [`08bacc7`](https://github.com/assimp/assimp/commit/08bacc73a66075d750f033cb4c22abc83e9199d9)

Will be fixed by #5019

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5019
