### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by hYdos** [assimp/assimp#5022]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to load models for my game and I have to wait 1 model after the other compared to other solutions.

**Describe the solution you'd like**
Proper MultiThreading support so I can load models on more than one thread.

**Describe alternatives you've considered**
Using another project or waiting one model after the other.

**Additional context**
Its a major limit speed wise that I have to wait for.

**Comment by turol** [comment]
You can just create multiple assimp `Importer` instances and use them in parallel. They are (or should be) entirely independent of each other.

**Comment by hYdos** [comment]
Is this possible with the C api instead of the C++ one?
