### ISSUE TITLE
Commit 3b9d4cf (5 Oct 2020) broke both IRR/IRRMesh and X3D loaders

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5033]
IRR/IRRMesh and X3D loaders stopped working properly at commit to master [`3b9d4cf`](https://github.com/assimp/assimp/commit/3b9d4cfd280064d2db1a153d8e7c71d5abff8902) on 5 Oct 2020 (had been working in previous commit to master [`6a4c338`](https://github.com/assimp/assimp/commit/6a4c338625d75df432317f2fd00c934b09c4d611) on 29 Sep 2020)

Unfortunately commit [`3b9d4cf`](https://github.com/assimp/assimp/commit/3b9d4cfd280064d2db1a153d8e7c71d5abff8902) on 5 Oct 2020 mixed formatting changes with actual code changes so may not be easy to ascertain exactly what caused the breakage

Part of the problem was that IRR/IRRMesh stopped working for UTF16 files in 2014, and the IRR/IRRMesh test models bundled with assimp up until recently were all UTF16, so the breakage in 2020 went unnoticed

Detailed bisect timelines in #5014 (IRR/IRRMesh) and #4992 (X3D)

**Comment by kimkulling** [comment]
I am currently working on it.

**Comment by tellypresence** [comment]
Closing after #5166 merged
