### ISSUE TITLE
Bug: Corrupted stack after using aiMaterial::GetTexture() in GLTF or GLB files

### ISSUE THREAD

**Issue by theOtherMichael** [assimp/assimp#5058]
**Describe the Bug**
When using `aiMaterial::GetTexture()` in GLTF files, the stack is corrupted. The following error is generated by the Visual Studio debugger:

> Run-Time Check Failure #2: Stack around the variable 'wrapMode' was corrupted.

`wrapMode` is the name I gave to the stack variable whose address I passed to `GetTexture()`'s final output parameter, `mapMode`.

**To Reproduce**
1. Acquire any GLTF file. I have tested this with Blender files exported as GLB and with GLTF downloads from Poly Haven.
2. Compile the following program:
```cpp
#include <iostream>
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>

int main(int argc, char* argv[])
{
    if (argc < 2)
    {
        std::cerr << "Usage: Provide a path to a model file." << std::endl;
        return EXIT_FAILURE;
    }

    Assimp::Importer importer;

    const aiScene* scene = importer.ReadFile(
        argv[1], aiProcess_Triangulate | aiProcess_GenSmoothNormals | aiProcess_FlipUVs);

    if (!scene)
    {
        std::cerr << "Error loading model file! ";
        std::cerr << importer.GetErrorString() << std::endl;
        return EXIT_FAILURE;
    }

    for (unsigned int i = 0; i < scene->mNumMaterials; i++)
    {
        aiMaterial* material = scene->mMaterials[i];

        std::cout << "Material: " << material->GetName().C_Str() << "\n";

        unsigned int numDiffuseTextures =
            material->GetTextureCount(aiTextureType_DIFFUSE);

        for (unsigned int diffuseTextureIndex = 0;
             diffuseTextureIndex < numDiffuseTextures;
             diffuseTextureIndex++)
        {
            // The sixes are to confirm that each variable has changed
            aiString texturePath("666");
            aiTextureMapping mapping  = (aiTextureMapping)666;
            unsigned int uvIndex      = 666;
            ai_real blend             = 666.666f;
            aiTextureOp op            = (aiTextureOp)666;
            aiTextureMapMode wrapMode = (aiTextureMapMode)666;

            material->GetTexture(aiTextureType_DIFFUSE,
                                 diffuseTextureIndex,
                                 &texturePath,
                                 &mapping,
                                 &uvIndex,
                                 &blend,
                                 &op,
                                 &wrapMode);

            std::cout << "Diffuse texture #" << diffuseTextureIndex << ": "
                      << texturePath.C_Str() << "\n";
            std::cout << "  mapping : " << mapping << "\n";
            std::cout << "  uvIndex: " << uvIndex << "\n";
            std::cout << "  blend:" << blend << "\n";
            std::cout << "  op: " << op << "\n";
            std::cout << "  wrapMode:" << wrapMode << "\n ";
        }

        std::cout << std::endl;
    }

    return EXIT_SUCCESS;

    // Run-Time Check Failure #2: Stack around the variable 'wrapMode' was corrupted.
}
```
3. Run the program with the path to the GLTF file as the first program argument.

**Expected behavior**
For any file, the output variables passed into `GetTexture()` would be updated to representative or default values.

**Screenshots**
![image](https://user-images.githubusercontent.com/7654399/229995518-57c4f328-fc56-4ff7-a7e5-c8d2d1fe100e.png)

**Platform (please complete the following information):**
 - Windows

**Additional context**
I have noticed that, even when loading FBX files, this function fails to update `blend`, `op`, and `mapMode`. Additionally, I have noticed the following behavioral changes when opening GLTF files:
* The final output parameter, `mapMode`, receives a value _only_ in the GLTF versions of models.
* `aiScene::mNumMaterials()` is greater in the GLTF versions of models by exactly 1. The stack corruption occurs when calling this final index.

**Comment by turol** [comment]
User error 
https://github.com/assimp/assimp/blob/679eb972e62079d3669dbe36555f1a44e78eb95d/include/assimp/material.h#L799


> The parameter may be NULL but if it is a valid pointer it MUST point to an array of 3 aiTextureMapMode's (one for each axis: UVW order (=XYZ)).

**Comment by theOtherMichael** [comment]
Ugh... thank you. It didn't occur to me that this intended to be a pointer to an _array_, and I missed that line of the documentation for some reason.

Perhaps "mapModes" (plural) would be a clearer name.
