### ISSUE TITLE
5.2.5 - macOS Does not compile with error - Due to security concerns inherent in the design of sprintf - ValidateDataStructure

### ISSUE THREAD

**Issue by danoli3** [assimp/assimp#5061]
**Describe the bug**
5.2.5 does not compile on Mac 
Master does compile! 

**To Reproduce**
Compile CMake: Error: 
```
[ 24%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/ValidateDataStructure.cpp.o
assimp/code/PostProcessing/ValidateDataStructure.cpp:83:22: error: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    const int iLen = vsprintf(szBuffer, msg, args);
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:207:1: note: 'vsprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead.")
^

```

**Expected behavior**
Compiles

**Screenshots**
<img width="1147" alt="Screenshot 2023-04-14 at 2 00 30 pm" src="https://user-images.githubusercontent.com/830748/231942778-2414c1ae-9e08-4c4e-b25f-add084af0203.png">

**Platform (please complete the following information):**
 - OS: macOS
 - Version 5.2.5

**Additional context**
master does compile 

Push forward for 5.3.0 thanks

**Comment by dimitris64bit** [comment]
Can be fixed temporarily (not the best solution, because it is a bit brute-force), by adding these lines to CMakeLists.txt:

set(DEPRECATION_FLAG "-Wno-deprecated-declarations")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${DEPRECATION_FLAG}")

**Comment by kimkulling** [comment]
Replaced by a *vsnprintf* call.

**Comment by danoli3** [comment]
Thanks pros
