### ISSUE TITLE
STB Image build failures using clang++ on Windows

### ISSUE THREAD

**Issue by Shylexx** [assimp/assimp#5065]
When using Ninja + Clang++ to build assimp as a cmake project, 'unused function' warnings (promoted to errors by the assimp cmakelists) from the internal version of stb image prevent assimp from building.

**To Reproduce**
1. Have Clang installed and default compiler for Ninja
2. Create build files from a build folder with `cmake .. -G Ninja`
3. Run Ninja with `ninja`

**Expected behavior**
A clean build of assimp?

**Platform (please complete the following information):**
 - OS: Windows
 - Using assimp as a submodule in my own project
 - Clang ver: 15.0.6

**Additional context**
Exact error message contains:
```
E:/../assimp/code/../contrib\stb/stb_image.h:730:12: error: unused function 'stbi__cpuid3' [-Werror,-Wunused-function]
static int stbi__cpuid3(void)
           ^
E:/../assimp/code/../contrib\stb/stb_image.h:1068:12: error: unused function 'stbi__addints_valid' [-Werror,-Wunused-function]
static int stbi__addints_valid(int a, int b)
           ^
E:/../assimp/code/../contrib\stb/stb_image.h:1076:12: error: unused function 'stbi__mul2shorts_valid' [-Werror,-Wunused-function]
static int stbi__mul2shorts_valid(short a, short b)
```

**Comment by kimkulling** [comment]
Fixed
