### ISSUE TITLE
Bug:STB symbol table is not updated

### ISSUE THREAD

**Issue by tigert1998** [assimp/assimp#5071]
This file is not updated:
https://github.com/assimp/assimp/blob/master/code/Common/StbCommon.h#L65

If assimp is linked to an executable (also has stb installed), then these two symbols will cause a conflict: "stbi_convert_iphone_png_to_rgb_thread", "stbi_set_unpremultiply_on_load_thread". Update the symbol table will fix it.

**Comment by tigert1998** [comment]
I don't know the value of `STB_USE_HUNTER`, nor do I change it. I use the default configuration to build assimp with CMake.

**Comment by kimkulling** [comment]
Yes, this in an issue which we have intorduced by enabling implicitly linking std-lib in the assimp source. To get rid of this there are 2 ways:
1. Assimp needs to define a CMake option to enable linkage of the std lib in assimp
2. Your application is nut generaqting the linkage in your code. 

The prefix solution need an update indeed as well.

**Comment by kimkulling** [comment]
Fixed.
