### ISSUE TITLE
Bug: Assimp build issues in VS2022

### ISSUE THREAD

**Issue by juice-artur** [assimp/assimp#5080]
**Describe the bug**
When trying to assemble a pre-generated project with the help of CMake, we get a `DeadlyExportError error`: identifier not found

**To Reproduce**
1. git init .
2. git submodule add https://github.com/assimp/assimp.git external/assimp
3. Create CmakeLists.txt as here - https://gist.github.com/juice-artur/2aa62828b6832e8469d445309fe2387d
4. add main.cpp in src
5. Generate project
6. Open .sln in vs
7. try build project

**Platform (please complete the following information):**
 - OS: Windows 11

**Additional context**
CMakeLists example https://gist.github.com/juice-artur/c75a3cd2be8e2656cd5abc5ec3771632

**Comment by juice-artur** [comment]
C++  17

**Comment by kimkulling** [comment]
Can you please offer an example of how to reproduce this?
