### ISSUE TITLE
Regression - broken skeletal animation in gltf2

### ISSUE THREAD

**Issue by malytomas** [assimp/assimp#5084]
**Describe the bug**
Commit dfd70b5c10cd45ef9d80c96ee08fe4e7393520a9 broke skeletal animation of gltf2/glb model.

**Screenshots**
![good](https://user-images.githubusercontent.com/18198295/235980719-4d1f6aca-22c9-4a78-8e3c-4e76876de191.png)
![broken](https://user-images.githubusercontent.com/18198295/235980727-0aa1a0c4-3142-45d1-b638-9467728640e0.png)

**Platform (please complete the following information):**
 - OS: windows, linux

**Additional info:**
I can send the model, but privately only, due to its license.

**Comment by FlorianBorn71** [comment]
Mea culpa. @kimkulling, could you revert this PR? 
https://github.com/assimp/assimp/pull/5003
It was just a memory optimization. 
If I get access to this model, I could also have a look into fixing it.

**Comment by malytomas** [comment]
> If I get access to this model, I could also have a look into fixing it rather than reverting - I guess it's a matter of re-indexing vertex weights or similar.

I have sent you an email.

Thanks for looking into this ;)

**Comment by FlorianBorn71** [comment]
Thanks a lot for sending the model, I'll have a look if that's an easy fix

**Comment by FlorianBorn71** [comment]
Hi @malytomas !
I have a candidate PR for a proper fix:
https://github.com/assimp/assimp/pull/5090
It converted your turtle model properly.

**Comment by malytomas** [comment]
Looks good to me. Thanks ;)

**Comment by malytomas** [comment]
Closed in #5090
