### ISSUE TITLE
Bug: vertex indexing issue on certain models

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5100]
(Updated w/screenshot of formerly misbehaving model now loading correctly, after author fixed his implementation)

3D model file `korean_public_payphone_01` in 2 different formats; one renders perfectly, the other has severe vertex indexing problems.  If someone is able to compare the two might be able to figure out where the gltf model is going wrong.

([This page](https://github.com/openframeworks/openFrameworks/tree/8804b19c39302e6fcb9f4edc0f18a5b562214c7e/examples/3d/assimp3DModelLoaderExample/bin/data/Payphone) confirms the gltf came from the same polyhaven model)

Note: this problem is not specific to gltf; also known to affect certain models in at least formats '.ac', '.blend', '.gltf', '.ter' as detailed in issue https://github.com/assimp/assimp/issues/4870

<table>
<tr><th>3D model file link</th><th>Screenshot</th></tr>
<tr><td><a href="https://polyhaven.com/a/korean_public_payphone_01">polyhaven</a><br>(<tt>.blend</tt>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/dc39e881-5914-4f72-acbd-549ff4e912e4" alt="polyhaven_korean_public_payphone_01" width=240></td></tr>
<tr><td><a href="https://github.com/openframeworks/openFrameworks/blob/8804b19c39302e6fcb9f4edc0f18a5b562214c7e/examples/3d/assimp3DModelLoaderExample/bin/data/Payphone">openFrameworks</a><br>(<tt>.gltf/.bin</tt>)</td>
<td>
<table>
<tr><th>Before fix</th><th>After fix</th></tr>
<tr><td>
<img src="https://github.com/assimp/assimp/assets/26958898/51fcba3c-513a-4054-a231-c29b0454ee9a" alt="openframeworks_korean_public_payphone_01" width=240>
</td><td><img src="https://github.com/assimp/assimp/assets/26958898/15e5e369-a045-4a42-8cea-cef6db5b4838" alt="openframeworks_korean_payphone_after_fix_Screenshot_20231117-201243" width=240></td></tr>
</table>
</td></tr>
</table>

**Comment by hernot** [comment]
From your images i do assume that your surface contain texture information and texture images. Is that texture information directly encode in the files or stored in a separate file which is only loosely linked through the assumption that the order and thus indices of the vertices are invariant between storing and loading. 

Could you therefore please check if your observations could be caused  by some non desired  vertex reordering issues like the ones reported in the context feature request #5091.

**Comment by tellypresence** [comment]
Issue unrelated to textures, this is purely a geometry problem; please check the untextured models in #4870

**Comment by hernot** [comment]
Ok thanks. I do still suspect vertex reordering the cause. While in #4870 and related it is just that external data linkage is broken, in your case it seems as if vertex indices of triangles and if present texture UVS are not properly or consistently updated when vertex order is optimized. 

Just guessing (exclusion principle):
Do you run any postprocessing exempt mandatory vertex unification (assume not)? Did you check if the surfaces are fully oriented or orientable (all triangle normals point to same side of surface/patch)?

**Comment by tellypresence** [comment]
Added some debug logging to print the face indices for the first 50 faces for both models to see if there was anything obvious going on, but that doesn't seem to be the case here.

(Note that while the number of faces is the same between models, the original model has < 30k vertices while the derivative model has > 100k vertices)

Models were loaded with assimp "join identical vertices" flag set to 1.

For the correctly rendering (.blend) original model:
48,132 faces, 29,969 verts
```
face 0 indices: 0, 1, 2, 
face 1 indices: 2, 3, 0, 
face 2 indices: 4, 0, 3, 
face 3 indices: 3, 5, 4, 
face 4 indices: 6, 7, 8, 
face 5 indices: 8, 9, 6, 
face 6 indices: 10, 6, 9, 
face 7 indices: 9, 11, 10, 
face 8 indices: 12, 10, 11, 
face 9 indices: 11, 13, 12, 
face 10 indices: 14, 12, 13, 
face 11 indices: 13, 15, 14, 
face 12 indices: 16, 14, 15, 
face 13 indices: 15, 17, 16, 
face 14 indices: 18, 16, 17, 
face 15 indices: 17, 19, 18, 
face 16 indices: 20, 18, 19, 
face 17 indices: 19, 21, 20, 
face 18 indices: 22, 20, 21, 
face 19 indices: 21, 23, 22, 
face 20 indices: 2, 24, 25, 
face 21 indices: 25, 3, 2, 
face 22 indices: 24, 26, 27, 
face 23 indices: 27, 25, 24, 
face 24 indices: 28, 29, 25, 
face 25 indices: 25, 27, 28, 
face 26 indices: 29, 5, 3, 
face 27 indices: 3, 25, 29, 
face 28 indices: 30, 31, 32, 
face 29 indices: 32, 33, 30, 
face 30 indices: 31, 34, 35, 
face 31 indices: 35, 32, 31, 
face 32 indices: 36, 37, 32, 
face 33 indices: 32, 35, 36, 
face 34 indices: 37, 38, 33, 
face 35 indices: 33, 32, 37, 
face 36 indices: 39, 40, 41, 
face 37 indices: 41, 42, 39, 
face 38 indices: 40, 43, 44, 
face 39 indices: 44, 41, 40, 
face 40 indices: 45, 46, 41, 
face 41 indices: 47, 48, 45, 
face 42 indices: 46, 49, 42, 
face 43 indices: 42, 41, 46, 
face 44 indices: 8, 50, 51, 
face 45 indices: 51, 9, 8, 
face 46 indices: 50, 52, 53, 
face 47 indices: 53, 51, 50, 
face 48 indices: 54, 55, 51, 
face 49 indices: 51, 53, 54, 
```

For the incorrectly rendering (.gltf/.bin) derivative model:
48,132 faces, 101,095 verts
```
face 0 indices: 0, 1, 2, 
face 1 indices: 2, 3, 0, 
face 2 indices: 4, 5, 6, 
face 3 indices: 6, 7, 8, 
face 4 indices: 9, 10, 11, 
face 5 indices: 11, 12, 13, 
face 6 indices: 14, 13, 15, 
face 7 indices: 16, 17, 18, 
face 8 indices: 19, 14, 20, 
face 9 indices: 17, 21, 19, 
face 10 indices: 22, 23, 24, 
face 11 indices: 25, 26, 27, 
face 12 indices: 28, 22, 26, 
face 13 indices: 29, 30, 31, 
face 14 indices: 32, 28, 30, 
face 15 indices: 30, 33, 34, 
face 16 indices: 35, 36, 37, 
face 17 indices: 38, 39, 35, 
face 18 indices: 40, 41, 42, 
face 19 indices: 43, 44, 40, 
face 20 indices: 45, 46, 47, 
face 21 indices: 48, 6, 49, 
face 22 indices: 46, 50, 51, 
face 23 indices: 52, 48, 53, 
face 24 indices: 54, 55, 47, 
face 25 indices: 56, 57, 58, 
face 26 indices: 55, 59, 60, 
face 27 indices: 3, 48, 61, 
face 28 indices: 62, 63, 64, 
face 29 indices: 65, 66, 67, 
face 30 indices: 68, 69, 70, 
face 31 indices: 71, 65, 72, 
face 32 indices: 73, 74, 75, 
face 33 indices: 75, 70, 73, 
face 34 indices: 76, 77, 66, 
face 35 indices: 66, 65, 76, 
face 36 indices: 78, 79, 80, 
face 37 indices: 81, 82, 83, 
face 38 indices: 84, 85, 86, 
face 39 indices: 86, 87, 88, 
face 40 indices: 89, 90, 91, 
face 41 indices: 92, 93, 94, 
face 42 indices: 95, 96, 97, 
face 43 indices: 98, 80, 99, 
face 44 indices: 100, 101, 102, 
face 45 indices: 103, 15, 104, 
face 46 indices: 101, 105, 106, 
face 47 indices: 107, 108, 109, 
face 48 indices: 110, 111, 108, 
face 49 indices: 103, 112, 113, 
```

**Comment by hernot** [comment]
There is a bit of change but looking back at your images reordering should at max garble the texture but not the overall structure. So more likely it must be some other issue. I just saw that libassimp has two  gltf (gltf and gltf2) importers/exporters. 
So assumeably there exists at least a newer version 2 of gltf/glb which is incompatible to version 1 or even any other version of gltf/glb. So at worst on loading the wrong loader is used. As far as i read the glb files have a json style header describing the contained binary blob. Maybe libassimp is misslead by the header and thus using the version 2 while it would be a version 1 file or the file is a version 2 or newer but from the header libassimp assumes version 1.

Try to enable debug information providing some meta information which file format it thinks your file is. Than you could crosscheck with the header. If these correspond i would just for verification try to force libassimp to use the other loader. If that one would return proper surface textured as well as untextured than the error would not be on libasismp side. It would be on the side of the provider of the surfaces. In that case i would suspect that their software doesn't fill all mandatory fields properly as it supports only eg version 2 anyway and just determines file format by postfix or requires the user to select version from drop-down on saving. Carelessly written software typically doesn't care in that case to properly fill the headers and just puts something to keep loaders happy.

**Comment by tellypresence** [comment]
As is often the case, was a legacy problem in my implementation

**Comment by hernot** [comment]
Is it any error worth sharing with others so that they can avoid it from start. Or is it trivial type.
