### ISSUE TITLE
Bug: "Draco Mesh Compression Not Supported" in Assimp 5.2.5

### ISSUE THREAD

**Issue by LukasTr** [assimp/assimp#5136]
**Describe the bug**
Assimp v5.2.5 cannot load the attached GLB file, which uses Draco compression.
[glb-file-with-assimp-error.zip](https://github.com/assimp/assimp/files/11706126/glb-file-with-assimp-error.zip)

**To Reproduce**
I am trying to load the attached GLB file. It seems that Assimp 5.2.5 should already support Draco. Unfortunately, I am getting the error "Dracxo mesh compression not supported".

[This online GLB viewer](https://gltf-viewer.donmccurdy.com/) is able to load the file and can be used to verify how it should look like.

**Expected behavior**
I expect the file to load correctly.

**Platform (please complete the following information):**
- OS: Windows 11 x64
- using Assimp in C# through the StirlingLabs.AssimpNet library
- Assimp Version: 5.2.5

**Comment by kimkulling** [comment]
Thanks a lot for the report.

Have you checked that the draco compression lib support was enabled for your build.

**Comment by tellypresence** [comment]
Draco compression isn't supported out of the box, need to set an assimp CMake flag to get it to build
<img alt="assimp_5136_draco_Screenshot_20230919-124402" src="https://github.com/assimp/assimp/assets/26958898/063bf165-8be8-4d9f-b35b-e7556f8e3531" width=160>
