### ISSUE TITLE
Bug: Exported FBX with skeleton is corrupted

### ISSUE THREAD

**Issue by ronenv-ten** [assimp/assimp#5137]
When importing a .glb file (CesiumMan.glb from the glTF 2.0 samples repo) , which contains skeleton animation and exporting it to .fbx file, the output file is messed up as can be seen in the following screenshot:
<img width="998" alt="image" src="https://github.com/assimp/assimp/assets/136521194/44b8cf5e-b928-4412-89e4-0987da35fc02">

This is the result with the original .glb file:
<img width="1003" alt="image" src="https://github.com/assimp/assimp/assets/136521194/0b15aac2-f753-4778-840a-f882167e605a">

Exporting to .glb works fine.

 I use Assimp version 5.2.5 and for the import/export the pre/post processing flags were set to 0.
I also tried other Assimp versions as suggested in other bug reports related to this issue, but I had no success with them.

**Comment by gongminmin** [comment]
I do find some inconsistency between FBXConverter and FBXExporter.
1. In FBXConverter, the bone's mOffsetMatrix is directly from Transform matrix, and TransformLink matrix is not used. But in FBXExporter, the Transform is a recalculated matrix of mesh space to bone space, and TransformLink is the bone to root. The Transform matrix is different than the original mOffsetMatrix after saving. (Load fbx->Save fbx->Load fbx resulting a different mOffsetMatrix for the same bone)
2. In FBXConverter, the mTime in aiVectorKey and aiQuatKey are in ticks. In FBXExporter, they are treated as seconds.
3. In FBXConverter, the scale node is read from "Lcl Scaling". In FBXExporter it's "Lcl Scale". Could be just a typo.

For conversion between glb and fbx, one more issue is that the mTime is in millisecond when loading from glb, but ticks when loading from fbx. Is there a rule about what unit the mTime should be? @kimkulling

**Comment by JulianKnodt** [comment]
I've found that the issue is in the FBX exporter, on line 2607, it is converting radians to degrees, and I'm pretty sure that Assimp further down requires radians, but that was causing the error. I can file a PR for it when I have time, or if someone else would like to take it that's good with me.
