### ISSUE TITLE
Bug: ObjImporter generates a wrong vertex color mapping if vertex colors are partially specified

### ISSUE THREAD

**Issue by emaame** [assimp/assimp#5139]
**Describe the bug**
ObjImporter generates a wrong vertex color mapping if vertex colors partially specified (i.e., specified / omitted are mixed), such as:

```only_a_part_of_vertexcolors.obj
v  0.0  0.0  0.0
v  0.0  0.0  1.0  0.0  0.0  1.0
v  0.0  1.0  0.0
v  1.0  0.0  0.0  1.0  0.6  0.3
```

I think it is not an officially spec, however it is necessary in my case.

**Actual Vertex Colors**

```
(0.0, 0.0, 1.0, 1.0)
(1.0, 0.6, 0.3, 1.0)
uninitialized
uninitialized
```

because ObjFileParser::getTwoVectors3 assumes vertices and vertex colors have the same size.

**To Reproduce**
Remove a subset of vertex color declaration from an OBJ file then load it.

**Expected behavior**
Handle omitted vertex colors as `(0.0, 0.0, 0.0, 1.0)` or `(0.0, 0.0, 0.0, 0.0)`.
I guess `(0.0, 0.0, 0.0, 1.0)` is more similar to an explicitly declared file.

```
(0.0, 0.0, 0.0, 1.0)
(0.0, 0.0, 1.0, 1.0)
(0.0, 0.0, 0.0, 1.0)
(1.0, 0.6, 0.3, 1.0)
```

or

```
(0.0, 0.0, 0.0, 0.0)
(0.0, 0.0, 1.0, 1.0)
(0.0, 0.0, 0.0, 0.0)
(1.0, 0.6, 0.3, 1.0)
```

**Additional context**
Currently I'm going to post a PR.

**Comment by turol** [comment]
What software produces files like this?

**Comment by emaame** [comment]
I heard that exported from Cinema4D.
I'm so sorry I have no more information about it (version et. al).

(I also post here again)

**Comment by emaame** [comment]
fix PR merged
