### ISSUE TITLE
Bug: pyassimp.load(<path_to_file>) causes ValueError: invalid string pointer <some_address> in core.py, line 134, in _init obj = getarr(self,m)

### ISSUE THREAD

**Issue by Zi1mann** [assimp/assimp#5143]
**Describe the bug**
Calling `pyassimp.load(<path_to_file>)` causes `ValueError: invalid string pointer <some_address>` in 
`"<path_to_pycharm_project>\lib\site-packages\pyassimp\core.py", line 134, in _init
    obj = getattr(self, m)`

**To Reproduce**
1. set up empty pycharm project for python2.7, install pyassimp through `pip install pyassimp` (version 4.1.4) in the associated environment
2. copy assimp.dll that was build with cmake (renamed from `assimp-vc142-mtd.dll`) from the cloned assimp repository into `"<path_to_pycharm_project>\lib\site-packages\pyassimp\`
4. copy content of `sample.py` into `main.py` of pycharm project
5. copy some 3D model file such as a simple "cube.obj" or "cube.fbx" into the project directory, set filename accordingly
6. set startup parameter to something non-empty so main will initialize and run
7. run `main.py`
8. see description above

**Expected behavior**
file loads to scene

**Platform (please complete the following information):**
 - OS: Windows 11
 - Python 2.7
 - pyassimp 4.1.4
 - assimp.dll build from release/master branch of assimp repository using cmake

**Comment by umlaeute** [comment]
> Python 2.7

seriously? Python2 was sunset after years of announcements on 2020-01-01.
This was 3½ years ago.

please do not use Python2 any more in *any* project.


apart from that: pyassimp-4.1.4 from pypi is known to have serious bugs. you probably shouldn't use it (and instead use the version that is shipped with the assimp sources)

see also https://github.com/assimp/assimp/issues/3072

**Comment by Zi1mann** [comment]
Well, me moving to 2.7 was just the reaction to the disclaimer on the PyPi assimp page stating that Python 3 support was _mostly_ there but not well tested. 

I will try using the version of the plugin that is  contained in the repository.

**Comment by kimkulling** [comment]
I guess this comment is just outdated. Python 3.x is strongly recommended.
