### ISSUE TITLE
Bug: duck.dae  (and other duck related files) are wrongly licensed

### ISSUE THREAD

**Issue by mwestphal** [assimp/assimp#5144]
**Describe the bug**

The license on duck.dae is wrong and the original license is not respected.

Duck.dae is an ascii file that contains its own license, visible here:
https://github.com/assimp/assimp/blob/master/test/models/Collada/duck.dae

It is under the SCEA license https://spdx.org/licenses/SCEA.html

It is perfectly fine to redistribute this file as this license is even less restrictive than BSD-3 license, however, the license should be respected and the SCEA license should be included somewhere easier to find when cloning/downloading assimp.

I assume other related files (duck.zea and duckCM.tga) are also under this license.

This was reported on F3D project by a debian maintainer.

https://github.com/f3d-app/f3d/issues/531

**Comment by kimkulling** [comment]
The SCEA license is part of the file duck.dae .It is mentioned in the licence tags directly used in the file. So how do we need to deal with this?

**Comment by kimkulling** [comment]
Fixed.
