### ISSUE TITLE
Some bundled IRR files have problems

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5171]
#5166 fixed loading of most of the bundled UTF-8 IRR/IRRMesh test files (UTF-16 loading remains broken)

But, there are 2 bundled UTF-8 files that still fail to load:
<a href="https://github.com/assimp/assimp/blob/master/test/models-nonbsd/IRR/skybox.xml">test/models-nonbsd/IRR/skybox.xml</a> loads but has zero meshes (should report error)
<a href="https://github.com/assimp/assimp/blob/master/test/models/IRR/scenegraphAnim.irr">test/models/IRR/scenegraphAnim.irr</a> fails with <tt>Unable to load model: XML parse error while loading IRR file</tt>

Note: the skybox is known to have previously loaded OK:
<img src="https://user-images.githubusercontent.com/26958898/225816805-1676d705-9497-4586-a204-36722f3cddde.png" alt="skybox_xml_-_assimp_commit_2014-03-01_49e9ad9" width=80><img src="https://user-images.githubusercontent.com/26958898/225816802-7c761c4e-4344-4c62-9f73-dedaf3032e30.png" alt="skybox_xml_-_assimp_commit_2014-03-01_49e9ad9" width=80><img src="https://user-images.githubusercontent.com/26958898/225816799-a31dd385-d035-4abb-8bcb-f897cb345365.png" alt="skybox_xml_-_assimp_commit_2014-03-01_49e9ad9" width=80>
but not sure if `scenegraphAnim.irr` ever worked (having said that, #5166 seems to have fixed 3 models that "never worked")

Also, this file only shows a single dwarf but should show 5 dwarves:
<a href="https://github.com/assimp/assimp/blob/master/test/models/IRR/instancing.irr">test/models/IRR/instancing.irr</a> 
<img src="https://github.com/assimp/assimp/assets/26958898/e3107f69-078d-4634-829b-6ddd35d67867" alt="IRR_instancing_irr" width=80 />

Screenshots and more details in #5014 (updated after #5166 merged)

**Comment by PencilAmazing** [comment]
I thought pugixml auto translates UTF-16 into UTF-8. https://pugixml.org/docs/manual.html#loading

Are these the only UTF-8 files with issues?

**Comment by PencilAmazing** [comment]
scenegraphAnim.irr is malformed. That's why it never worked

https://github.com/assimp/assimp/blob/master/test/models/IRR/scenegraphAnim.irr#L129

**Comment by tellypresence** [comment]
@PencilAmazing Thank you for making time to validate the xml.
Fixed the typos; errors are now
<table>
<tr><th>UTF-8</th><th>UTF-16LE</th></tr>
<tr><td>Validation failed: Empty node animation channel</td><td>XML parse error while loading IRR file</td></tr>
</table>

**Comment by PencilAmazing** [comment]
So what's left is fixing UTF-16LE parsing? Which should be just reading the pugixml handbook and seeing what function to call. And instancing, and the skybox, if I'm correct.

**Comment by tellypresence** [comment]
UTF16 IRR loading was recently fixed, will close this issue and open a new one for the remaining IRR/IRRMESH models which have problems
