### ISSUE TITLE
Bug: Test.exe build failed by cmake and mingw on Windows 11

### ISSUE THREAD

**Issue by sirlis** [assimp/assimp#5189]
**Describe the bug**
Bug: Test.exe build failed by cmake and mingw on Windows 11. Unable to get unit test executable file. 

**To Reproduce**
1. Go to `cmake-gui` and set source code to the cloned assimp repo. Set build binaries folder to `./build`
2. Click on 'Configure', select `Mingw Makefiles` as generator, specify native compilers as `gcc.exe`, `g++.exe`.
3. Uncheck  'ASSIMP_WARNINGS_AS_ERRORS'.
4. Click on 'Configure', then click on 'Generate'.
5. Use powershell and goto `./build`, use `mingw32-make.exe -j24` to start.
6. See error

**Expected behavior**
Expected to get
- include/assimp/config.h (successfully generated)
- bin/libassimp-5.dll (successfully generated)
- **bin/unit.exe (failed, no file)**
- lib/libassimp.dll.a (successfully generated)

**Screenshots**
![image](https://github.com/assimp/assimp/assets/12960298/38f820db-b14e-413c-bc84-91d399c8aa48)
![image](https://github.com/assimp/assimp/assets/12960298/590784ee-7c65-4ca3-8a65-dbc92725288f)

**Platform (please complete the following information):**
- assimp 5.2.5 (currently latest)
- OS: Windows 11
- CMake 3.27.0
- gcc version 13.1.0 (x86_64-posix-seh-rev1, Built by MinGW-Builds project)
- MinGW-w64: [x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1.7z](https://github.com/niXman/mingw-builds-binaries/releases/download/13.1.0-rt_v11-rev1/x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1.7z)

**Additional context**
None.

**Comment by kimkulling** [comment]
I guess the gtest version is outdated.
