### ISSUE TITLE
travis always build shared lib

### ISSUE THREAD

**Issue by arris69** [assimp/assimp#519]
```bash
-STATIC_BUILD=$TRAVIS_STATIC_BUILD
```
makes no sense.
the cmake option that controls shared or static build of libs is: 
-DBUILD_SHARED_LIBS={ON|OFF}

**Comment by acgessler** [comment]
Added in https://github.com/assimp/assimp/commit/52f3cd0afb3cba955f173ab80cec3676acf72671,

@kimkulling can you have a look?

**Comment by acgessler** [comment]
Fixed by #528.
