### ISSUE TITLE
Bug: build issue on MacOS Sonoma 14.0

### ISSUE THREAD

**Issue by jtressle** [assimp/assimp#5197]
On MacOS Sonoma 14.0, I was unable to compile for iOS.  

The errors were:

`clang: error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]
make[3]: *** [code/CMakeFiles/assimp.dir/AssetLib/Assjson/cencode.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 92%] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/Assjson/json_exporter.cpp.o
make[2]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make[1]: *** [code/CMakeFiles/assimp.dir/rule] Error 2
make: *** [assimp] Error 2
[!] Moving built static libraries into: ./lib/iOS/arm64/
mv: rename ./lib/*.a to ./lib/iOS/arm64/*.a: No such file or directory
[+] Creating fat binaries ...
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./lib/iOS/arm64/libassimp.a (No such file or directory)
[!] Done! The fat binaries can be found at ./lib/iOS
`

I got it to compile by changing the build.sh line from this:

`export CFLAGS="-arch $1 -pipe -no-cpp-precomp -stdlib=$CPP_STD_LIB -isysroot $SDKROOT -I$SDKROOT/usr/include/ -miphoneos-version-min=$IOS_SDK_TARGET"
`

to this:

`export CFLAGS="-arch $1 -pipe -no-cpp-precomp -isysroot $SDKROOT -I$SDKROOT/usr/include/ -miphoneos-version-min=$IOS_SDK_TARGET"
`

Does removing this change the compiler from `-stdlib=libc++` to `libc++`?  Or is this a straight-forward change?

Thanks

**Comment by kimkulling** [comment]
I think this issue is caused by a misconfiguration for the cross-compiler in our CMakeFiles.txt.
