### ISSUE TITLE
Assimp Mesh Position/Center/Pivot for Gizmo

### ISSUE THREAD

**Issue by knimix** [assimp/assimp#5201]
Hi, I am currently using assimp in a small OpenGL engine. I can load and render models. Suppose a model consists of 4 cubes. In assimp I have a node with 4 meshes. I also have a gizmo which is rendered as soon as I press on a mesh. In programs like Blender, each mesh has a kind of piviot point, i.e. the centre of each of the 4 cubes. This is handy because I then just have to render my gizmo where the origin of the respective mesh is. 

The problem is that Assimp gives me a mesh position, but it is only per node. Since a node has 4 individual meshes, there are no more nodes. Apparently assimp takes a pivot point and sets it relative for all. So one cube is actually in the middle, but the others are not. Now the question is whether I can solve this somehow? It would be cool if each mesh had its own position and not just the node. 

I wonder how others have solved this. Especially with larger meshes it would be nice that not all "sub meshes" are referenced to the same point. Anyway, only if a node has several meshes and I don't have the position of these meshes.

**Comment by kimkulling** [comment]
I have solved this as follows:
- Select a node with 4 meshes
- Generate bounding bosses for all meshes.
- Calculate the center for each bounding box
- Use this center as the pivot point for the rotation.

You can use the center for placing your gismo.
