### ISSUE TITLE
Compilation error when including Assimp headers in macOS Ventura 13.3.1 (Assimp 5.2.5)

### ISSUE THREAD

**Issue by luke10x** [assimp/assimp#5203]
I have the latest version of Assimp installed (5.2.5) using Homebrew on the Apple M1 Macbook Pro.
I get a compilation error when I include `assimp/scene.h` into my C++ program.

**To reproduce**

In any C++ file:

     #include <assimp/scene.h>

Then compiling it will give an error like this:

        [ 50%] Building CXX object CMakeFiles/MatrixTransform.dir/src/main.cpp.o
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  <skipped some includes>  -isystem /opt/homebrew/include -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -MD -MT CMakeFiles/MatrixTransform.dir/src/main.cpp.o -MF CMakeFiles/MatrixTransform.dir/src/main.cpp.o.d -o CMakeFiles/MatrixTransform.dir/src/main.cpp.o -c /Users/***/src/main.cpp
        <skipped some stack>
        In file included from /opt/homebrew/include/assimp/scene.h:55:
        /opt/homebrew/include/assimp/mesh.h:915:81: error: expected ';' after expression
                    mTextureCoordsNames = new aiString *[AI_MAX_NUMBER_OF_TEXTURECOORDS] {};

**Expected behavior**
I expect to compile it successfully

**Platform (please complete the following information):**
- Assimp: stable 5.2.5 (bottled), HEAD
- Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- Operating System: macOS Ventura 13.3.1

**Comment by kimkulling** [comment]
Thanks for the bug report! One question from my side: Which compiler have you used.
