### ISSUE TITLE
Can b3dm format data be parsed by assimp? Or do you need to write your own api?

### ISSUE THREAD

**Issue by 99zhu** [assimp/assimp#5206]
**Describe the technical debt**
I tried ReadFile, but got an error
![image](https://github.com/assimp/assimp/assets/127181262/7bcfc74c-f380-4289-a307-cb64e7200005)

**Better solution**
A clear and concise description of what you would expect.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by turol** [comment]
Can you share a test model?

**Comment by kimkulling** [comment]
Is this a blitzbasic file? If yes: just rename it to b3d.
