### ISSUE TITLE
Bug:vs2019 compile error

### ISSUE THREAD

**Issue by aolixin** [assimp/assimp#5214]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 compress2，函数 "public: void __cdecl Assimp::AssbinFileWriter::WriteBinaryDump(char const *,char const *,class Assimp::IOSystem *,struct aiScene const *)" (?WriteBinaryDump@AssbinFileWriter@Assimp@@QEAAXPEBD0PEAVIOSystem@2@PEBUaiScene@@@Z) 中引用了该符号	assimp	F:\document\visualPlugin\assimp-5.1.6\build\code\AssbinFileWriter.obj	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 compressBound，函数 "public: void __cdecl Assimp::AssbinFileWriter::WriteBinaryDump(char const *,char const *,class Assimp::IOSystem *,struct aiScene const *)" (?WriteBinaryDump@AssbinFileWriter@Assimp@@QEAAXPEBD0PEAVIOSystem@2@PEBUaiScene@@@Z) 中引用了该符号	assimp	F:\document\visualPlugin\assimp-5.1.6\build\code\AssbinFileWriter.obj	1

**Comment by kimkulling** [comment]
This issue is fixed in v5.2.5.
