### ISSUE TITLE
Bug: targetNames lost during GLTF export

### ISSUE THREAD

**Issue by vpzomtrrfrt** [assimp/assimp#5217]
**Describe the bug**
Reexporting a GLTF model appears to not preserve `targetNames`.

**To Reproduce**
1. Download a GLTF model containing `targetNames`, for example [MorphStressTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/4ca06672ce15d6a27bfb5cf14459bc52fd9044d1/2.0/MorphStressTest)
2. See that the file contains `targetNames`:
```
           "extras" : {
                "targetNames" : [
                    "Key 1",
                    "Key 2",
                    "Key 3",
                    "Key 4",
                    "Key 5",
                    "Key 6",
                    "Key 7",
                    "Key 8"
                ]
            },
```
3. Run `assimp export MorphStressTest.gltf /tmp/MorphStressTest-reexported.gltf`
4. The resulting file is missing `targetNames`

**Expected behavior**
The `targetNames` should be preserved when converting from GLTF to GLTF

**Platform (please complete the following information):**
 - OS: Arch Linux
 - Version 5.2.5 and e673d1fd

**Comment by vpzomtrrfrt** [comment]
Seems like this is part of ExportProperties, so I guess the user is supposed to set this in there. However:
- Why wouldn't this be default behaviour?
- ExportProperties doesn't appear to be accessible from the C API

**Comment by kimkulling** [comment]
You need to enable this feature.Then the target names shall be exported as well. If this is not the case: please reopen the issue.
