### ISSUE TITLE
Public C++ headers no longer work under 5.3.0

### ISSUE THREAD

**Issue by Bo98** [assimp/assimp#5247]
**Describe the bug**
Public headers of assimp 5.3.0 reference internal relative-path headers that are not installed. This reference was added in #4986.

**To Reproduce**
1. Build and install assimp 5.3.0: `make install`/`cmake --install`.
2. Compile this simple program:
```cpp
#include <assimp/Importer.hpp>
int main() {
  Assimp::Importer importer;
  return 0;
}
```

**Expected behavior**
The compile succeeds

**Actual behavior**
```console
In file included from test.cpp:1:
In file included from /usr/local/include/assimp/Importer.hpp:60:
/usr/local/include/assimp/types.h:79:13: fatal error: '../contrib/utf8cpp/source/utf8.h' file not found
#   include "../contrib/utf8cpp/source/utf8.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Platform (please complete the following information):**
 - OS: macOS 13

**Comment by yurivict** [comment]
Same problem on FreeBSD. "../contrib/utf8cpp/source/utf8.h" isn't installed by assimp.

**Comment by MehdiChinoune** [comment]
Why not supporting an external utf8cpp?

**Comment by Osyotr** [comment]
It doesn't look like <utf8.h> from `types.h` is used anywhere outside of samples, so it could be removed:
```diff
--- a/include/assimp/types.h
+++ b/include/assimp/types.h
@@ -73,8 +73,8 @@

 #ifdef __cplusplus

-#ifdef ASSIMP_USE_HUNTER
-#   include <utf8.h>
+#if 1
+//#   include <utf8.h>
 #else
 #   include "../contrib/utf8cpp/source/utf8.h"
 #endif
```
