### ISSUE TITLE
Gltf/glb export an unlimited number of skinning bones per vertex

### ISSUE THREAD

**Issue by fvbj** [assimp/assimp#5261]
According to the GLTF 2.0 Specification vertex attributes for skinning are defined as JOINTS_0 and WEIGHTS_0 data, see section 3.7.3.3. (https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#skinned-mesh-attributes)
Although the Assimp gltf/glb importer supports importing all skinning attributes, the Assimp export to gltf/glb supports only four bones per vertex, JOINTS_0 and WEIGHTS_0.

The pull request (https://github.com/assimp/assimp/pull/5243) solves this issue and exports all weights and joints of the corresponding vertex. The required number of JOINTS_n and WEIGHTS_n groups are exported. At the same time, the joints are sorted in descending order according to their weight. 

The extension is enabled by AI_CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX flag. The default behavior uses only the first four vertex bones with the largest weight. 
This extension also fixes the current implementation of gltf/glb export where the four bones with the highest weight are not always saved correctly.

**Comment by kimkulling** [comment]
Solved by your PR.
