### ISSUE TITLE
Missing normals transform on PretransformVertices.

### ISSUE THREAD

**Issue by sagaceilo** [assimp/assimp#5276]
Are we missing mNormals being transformed with aiMatrix3x3 m ? Or Im not seing a big picture. I'm investigating issue with FBX file not applying correctly transform for normals (both bitangents and tangents are rotated correctly). And that seems to be weirdly looking like this lack of normals modified here.

https://github.com/assimp/assimp/blob/2a347014f3ce8d597ecb0208213c8028229987e1/code/PostProcessing/PretransformVertices.cpp#L325

removing that line with (following code) fixes issue.
```
            for (unsigned int i = 0; i < mesh->mNumVertices; ++i) {
                mesh->mNormals[i] = (m * mesh->mNormals[i]).Normalize();
            }
```

**Comment by kimkulling** [comment]
You re right, I will fix the issue.

**Comment by sagaceilo** [comment]
Great, thanks! 😎👍
