### ISSUE TITLE
FBX or BVH animation?

### ISSUE THREAD

**Issue by seghier** [assimp/assimp#5283]
Hi, i use AssimpNet vesion 5.0.0 beta
I want to know how we can import specific frames or all frames from bvh, fbx if possible?
And if that possible , is there any example code in c#?

```
AssimpContext importer = new AssimpContext();
string outputPath = System.IO.Path.GetTempFileName();
outputPath = System.IO.Path.ChangeExtension(outputPath, "obj");
importer.ConvertFromFileToFile(filename, PostProcessSteps.ValidateDataStructure,outputPath, "obj", PostProcessSteps.ValidateDataStructure);
```

**Comment by kimkulling** [comment]
Hi, 
what exactly is your understanding of a frame? What you can access is availabe in th aiScene datastructure. What is not in is not available right now. So if you need one or more specific data structure you can add a new feature request.

Interesting fact is that 5.0.0 is outdated. Is it possible to access the latest version?

Kim

**Comment by seghier** [comment]
Thanks @kimkulling 
How to use the latest version in visual studio? 
is it available as nuget package?
