### ISSUE TITLE
Bug: Improper Texture data in vrm/gltf2.0 files

### ISSUE THREAD

**Issue by Futuremappermydud** [assimp/assimp#5288]
**Describe the bug**
When attempting to load and export textures from vrm(gltf2.0 w/ extensions) they have garbage data. There is also an incorrect number of textures. 

**To Reproduce**

reference model: https://cdn.discordapp.com/attachments/1163420557623185482/1164652833770057788/ava.vrm
sample code 
```
int main()
{
    Assimp::Importer importer;

    const aiScene* scene = importer.ReadFile("C:/Users/Owens/OneDrive/Desktop/ava.vrm", aiProcess_Triangulate | aiProcess_LimitBoneWeights);

    std::cout << scene->mNumTextures << "\n";
    for (size_t i = 0; i < scene->mNumTextures; i++)
    {
        auto tex = scene->mTextures[i];
        std::cout << tex->mWidth << "x" << tex->mHeight << "\n";

        std::ofstream fout;
        fout.open("C:/Users/Owens/OneDrive/Desktop/" + std::to_string(i) + ".png", std::ios::binary | std::ios::out);
        fout.write((char*)&tex->pcData, tex->mWidth);

        fout.close();
    }
    return 0;
}
```

**Expected behavior**
There should be a little over 10 or so textures I believe(instead of the 6 I get here) and the textures should contain proper texture data. 
TinyGLTF is able to properly represent these images with a proper count.

**Screenshots**

**Platform (please complete the following information):**
 - OS: windows, android
 - Versio: 5.3.1

**Additional context**

**Comment by stephengold** [comment]
The `assimp` command confirms there are only 6 embedded textures in the model. However, those 6 textures are referenced a total of 16 times:

```console
$ bin/assimp info ava.vrm
Launching asset import ...           OK
Validating postprocessing flags ...  OK
100 %Importing file ...                   OK 
   import took approx. 0.26898 seconds

Memory consumption: 4836057 B
Nodes:              171
Maximum depth       15
Meshes:             8
Animations:         0
Textures (embed.):  6
```
... redacted ...
```console
Texture Refs:
    '*0'
    '*2'
    '*1'
    '*0'
    '*0'
    '*2'
    '*1'
    '*0'
    '*3'
    '*5'
    '*4'
    '*3'
    '*3'
    '*5'
    '*4'
    '*3'
```

+ Those 10+ textures you expected, were any of them duplicates?

I extracted the 6 textures in "ava.vrm" using `assimp extract ava.vrm` and all 6 were viewable using standard tools. To me, they looked like plausible texture images, though of course I'm not familiar with the model.

**Comment by Futuremappermydud** [comment]
Oh that's likely why. Though when I tried writing them using the code above they contained data unrelated to textures...

**Comment by stephengold** [comment]
Also: Assimp does not store embedded texture images in PNG format, so writing the raw image to a ,png file doesn't produce a valid file.

Near as I can tell, the actual format of embedded textures is R8G8B8A8, but don't quote me on that!

**Comment by Futuremappermydud** [comment]
https://assimp.sourceforge.net/lib_html/structai_texture.html I read here that if the height is 0 then it's a png or jpg? guess i'll try reading like that. Thanks!

**Comment by stephengold** [comment]
I think that's right:
* an array of texels if `mHeight > 0`
* a compressed image if `mHeight == 0`.

Note that the SourceForge documentation is from v3.0 whereas the latest release is v5.2.5 . Make sure the documentation you use matches the software you use!

Also, let us know when this issue is solved to your satisfaction.

**Comment by Futuremappermydud** [comment]
Okay yeah. I took the image writing code from the assimp extract tool and that works.

Seems my issue was a combination of textures being duplicates in tinygltf and improperly writing the file. Why it didn't write properly? I don't know but the code from the tool works perfectly. 

Thanks!

**Comment by stephengold** [comment]
@Futuremappermydud I'm glad you got it working.
