### ISSUE TITLE
Bug: invalid pointer while importing an animated FBX model

### ISSUE THREAD

**Issue by stephengold** [assimp/assimp#5289]
**Describe the bug**
While importing the free "Black Dragon with Idle Animation" model (in its original FBX v7.4 format from Sketchfab), Assimp prints "free(): invalid pointer" to  `stderr` and aborts.

**To Reproduce**
1. Register a (free) account at the Sketchfab.com website and log in.
2. Browse to https://sketchfab.com/3d-models/black-dragon-with-idle-animation-fb0053a2e59b43868e934c239bf4eb36#download
3. Click on the blue "Download" button to the right of "fbx Original format".
4. Unzip the downloaded file.
5. Load the FBX file using `aiImportFile(filename, aiProcess_Triangulate)`

**Expected behavior**
`aiImportFile()` should return a valid and complete data structure.

**Screenshots**
With verbose logging enabled, the following messages are printed to the console:
```console
Info,  T0: Load Models/Issue/source/ef2da8ba53194e35a4be77969cff3949.fbx.fbx
Debug, T0: Assimp 5.2.0 amd64 gcc shared singlethreadedsingle : 
Info,  T0: Found a matching importer for this file format: Autodesk FBX Importer.
Info,  T0: Import root directory is 'Models/Issue/source/'
Debug, T0: Reading FBX file
Debug, T0: Tokenizing binary FBX file
Debug, T0: FBX version: 7400
Debug, T0: Parsing FBX tokens
Debug, T0: Creating FBX Document
Debug, T0: FBX Version: 7400
Warn,  T0: FBX-DOM (TOK_KEY, offset 0x28c0c7) encountered duplicate object id, ignoring first occurrence
free(): invalid pointer
```

**Platform**
 - OS: Mint Linux
 - Browser: Firefox
 - Version: LWJGL v3.3.3, which was built from Assimp commit 59b12344 (13 September 2023)

**Additional context**
The test data are licensed Creative Commons Attribution-NonCommercial. I'm unsure whether it's appropriate to upload here. If it is, let me know, and I'll do so.

**Comment by stephengold** [comment]
It appears this issue is a regression. I successfully imported the same model using LWJGL v3.3.2, which was built from Assimp commit 6832aa2 (24 March 2023). Some change between March and September caused this issue.

**Comment by turol** [comment]
Can you bisect it?

**Comment by stephengold** [comment]
Perhaps. Does this repository contain a console application to import a model?

**Comment by turol** [comment]
The `assimp` tool has `info` command which will load a model and print some information about it.

**Comment by stephengold** [comment]
What `cmake` command(s) should I use to build the `info` command for an x64 Linux?

**Comment by stephengold** [comment]
Progress at my end...
1. edited "MakeLists.txt" to build supplementary tools:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -85,7 +85,7 @@ OPTION( ASSIMP_NO_EXPORT
 )
 OPTION( ASSIMP_BUILD_ASSIMP_TOOLS
   "If the supplementary tools for Assimp are built in addition to the library."
-  OFF
+  ON
 )
 OPTION ( ASSIMP_BUILD_SAMPLES
   "If the official samples are built as well (needs Glut)."
```

2. `cmake CmakeLists.txt`
3. `cmake --build . -j 4`

So far, so good. Now where do I find the `assimp` tool binary? (I expect to find it in the `bin` directory, but it's not there.)

**Comment by turol** [comment]
You should set it from command line
```
cmake -DASSIMP_BUILD_ASSIMP_TOOLS=On
```
because having local changes interferes with bisect.

Also you should not be building directly in source directory. Create a separate `build` directory under it and run from there
```
cmake -DASSIMP_BUILD_ASSIMP_TOOLS=On ..
```
If you did it successfully there should be an `assimp` binary under directory `bin`.

**Comment by stephengold** [comment]
At Git hash 0c4d5909 the command `bin/assimp info issue5289.fbx` completes normally.
At Git hash 18b6cffe the command `bin/assimp info issue5289.fbx` dumps core.
Therefore, the regression was introduced into the "master" branch on 16 May 2023, by pull request #5096 .

Next I'd like to build a DEBUG version of the `assimp` binary. How would I do that?

**Comment by turol** [comment]
> Next I'd like to build a DEBUG version of the `assimp` binary, so I can analyze the resulting coredump. How would I do that?

The standard CMake way: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by stephengold** [comment]
Here's the relevant portion of the stack trace, generated at Git hash c44e3427:

```console
#6  0x00007ffff69c9cfc in malloc_printerr (str=str@entry=0x7ffff6b02764 "free(): invalid pointer")
    at ./malloc/malloc.c:5664
#7  0x00007ffff69cba44 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0)
    at ./malloc/malloc.c:4439
#8  0x00007ffff69ce453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007ffff77ebf2d in Assimp::FBX::Document::ReadObjects (this=0x7fffffffc9b0)
    at ../code/AssetLib/FBX/FBXDocument.cpp:393
#10 0x00007ffff77eaaf9 in Assimp::FBX::Document::Document (this=0x7fffffffc9b0, parser=..., 
    settings=...) at ../code/AssetLib/FBX/FBXDocument.cpp:263
#11 0x00007ffff779c9c0 in Assimp::FBXImporter::InternReadFile (this=0x55555559e110, 
    pFile="issue5289.fbx", pScene=0x5555555a0df0, pIOHandler=0x7fffffffcb90)
    at ../code/AssetLib/FBX/FBXImporter.cpp:170
#12 0x00007ffff724d255 in Assimp::BaseImporter::ReadFile (this=0x55555559e110, pImp=0x7fffffffd810, 
    pFile="issue5289.fbx", pIOHandler=0x55555559b640)
    at ../code/Common/BaseImporter.cpp:135
#13 0x00007ffff726695a in Assimp::Importer::ReadFile (this=0x7fffffffd810, _pFile=0x7fffffffd310 "issue5289.fbx", pFlags=3645131) at ../code/Common/Importer.cpp:709
#14 0x000055555557560c in Assimp::Importer::ReadFile (this=0x7fffffffd810, pFile="issue5289.fbx", pFlags=3645131) at ../include/assimp/Importer.hpp:670
#15 0x000055555557404c in ImportModel (imp=..., path="issue5289.fbx") at ../tools/assimp_cmd/Main.cpp:307
```

I hope that helps someone resolve this issue.

**Comment by turol** [comment]
Can you run it with Valgrind or ASAN for more detail? In particular this looks like a double free. I'd like to see where the first one was.

**Comment by stephengold** [comment]
I've never used Valgrind or ASAN before (just like I'd never used cmake before last week). But if you provide detailed instructions, I will try to follow them.

**Comment by turol** [comment]
For Valgrind consult the manual: https://valgrind.org/docs/manual/quick-start.html
For ASAN build with `ASSIMP_ASAN` cmake option.

**Comment by stephengold** [comment]
I used ASAN, and here is the output:
```console
$ bin/assimp info source/issue5289.fbx 
Launching asset import ...           OK
Validating postprocessing flags ...  OK
=================================================================
==13188==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7f1839358440 in thread T0
    #0 0x7f183fb4d24f in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x7f183ec24d77 in Assimp::FBX::Document::ReadObjects() /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXDocument.cpp:393
    #2 0x7f183ec21f17 in Assimp::FBX::Document::Document(Assimp::FBX::Parser&, Assimp::FBX::ImportSettings const&) /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXDocument.cpp:263
    #3 0x7f183eb692db in Assimp::FBXImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXImporter.cpp:170
    #4 0x7f183dfbf861 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) /home/sgold/NetBeansProjects/ext/assimp/code/Common/BaseImporter.cpp:135
    #5 0x7f183dffaa76 in Assimp::Importer::ReadFile(char const*, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/code/Common/Importer.cpp:709
    #6 0x55b7f596ded1 in Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/include/assimp/Importer.hpp:670
    #7 0x55b7f596b355 in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:307
    #8 0x55b7f59767a3 in Assimp_Info(char const* const*, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Info.cpp:344
    #9 0x55b7f596adc1 in main /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:222
    #10 0x7f183d53cd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0x7f183d53ce3f in __libc_start_main_impl ../csu/libc-start.c:392
    #12 0x55b7f59425c4 in _start (/home/sgold/NetBeansProjects/ext/assimp/build/bin/assimp+0x185c4)

0x7f1839358440 is located 1457216 bytes inside of 4194304-byte region [0x7f18391f4800,0x7f18395f4800)
allocated by thread T0 here:
    #0 0x7f183fb4c357 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x7f183eb7abff in Assimp::StackAllocator::Allocate(unsigned long) /home/sgold/NetBeansProjects/ext/assimp/code/Common/StackAllocator.inl:60
    #2 0x7f183ec99bf0 in ReadScope /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:389
    #3 0x7f183ec9a0a0 in ReadScope /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:411
    #4 0x7f183ec9ac35 in Assimp::FBX::TokenizeBinary(std::vector<Assimp::FBX::Token const*, std::allocator<Assimp::FBX::Token const*> >&, char const*, unsigned long, Assimp::StackAllocator&) /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:467
    #5 0x7f183eb69239 in Assimp::FBXImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/FBX/FBXImporter.cpp:160
    #6 0x7f183dfbf861 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) /home/sgold/NetBeansProjects/ext/assimp/code/Common/BaseImporter.cpp:135
    #7 0x7f183dffaa76 in Assimp::Importer::ReadFile(char const*, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/code/Common/Importer.cpp:709
    #8 0x55b7f596ded1 in Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/include/assimp/Importer.hpp:670
    #9 0x55b7f596b355 in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:307
    #10 0x55b7f59767a3 in Assimp_Info(char const* const*, unsigned int) /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Info.cpp:344
    #11 0x55b7f596adc1 in main /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:222
    #12 0x7f183d53cd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: bad-free ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172 in operator delete(void*, unsigned long)
==13188==ABORTING
$
```

I hope that's helpful.

**Comment by turol** [comment]
This appears to be a case of mismatching allocators. @FlorianBorn71 This was caused by your PR, can you fix?

**Comment by FlorianBorn71** [comment]
Hi, Florian here, author of the PR that broke it. 
Sorry for the inconvenience and thanks for listing detailed repro steps! 
I'm able to reproduce the bug myself with the Sketchfab model and I'm going to root cause it now. I'll keep you posted.

Florian

**Comment by FlorianBorn71** [comment]
The good news is, it's obviously a simple oversight in the following line:
file: \code\AssetLib\FBX\FBXDocument.cpp
line: 393

this part:

        if(foundObject != objects.end()) {
            DOMWarning("encountered duplicate object id, ignoring first occurrence",el.second);
            // delete foundObject->second; // OLD
            delete_LazyObject(foundObject->second); // NEW
        }


With that change, the model imports for me. 
@stephengold, if you want you can try this locally. Of course I will also create a proper PR for this change.

**Comment by FlorianBorn71** [comment]
Here is the PR:
https://github.com/assimp/assimp/pull/5305

**Comment by FlorianBorn71** [comment]
Would be great to have an fbx that has duplicated animation IDs. Any ide where to get a file? I figure it's hard to produce one with assimp.

**Comment by stephengold** [comment]
> Any ide where to get a file?

Did you try downloading the file from Sketchfab as documented above?

**Comment by FlorianBorn71** [comment]
> Did you try downloading the file from Sketchfab as documented above?
@stephengold, yes, this is how I reproduced the bug (thanks!). However it's not very practical to submit this model as a Unit test (both because of size and legal reasons)

**Comment by stephengold** [comment]
I'm not much of 3-D a modeller myself, nor am I aware of any other models that trigger this issue. If I find one I'll mention it here.

**Comment by turol** [comment]
I ran the model through afl minimizer. It didn't get significantly smaller. Attached in zip file.

**Comment by turol** [comment]
[minimized-inv-free.zip](https://github.com/assimp/assimp/files/13377024/minimized-inv-free.zip)

**Comment by stephengold** [comment]
I found another free FBX model at Sketchfab that can trigger this bug:

https://sketchfab.com/3d-models/martial-artist-249523d834814cb1bf379b827da60bfc#download

**Comment by stephengold** [comment]
Thank you @FlorianBorn71 for the fix and @kimkulling for integrating it.
