### ISSUE TITLE
Assimp.Net and VS2010... Weird problem...

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#530]
I'm facing a very strange error in my VS2010 project that uses c# + OpenTK + Assimp.net (The packages of the last 2 are from NuGet, so I suppose them updated to their latest version)
When I try to iterate the vector3 of the UV coordinates using:
model.Meshes[n].GetTextureCoords(0)[i]
I get the following error:
error CS1061: 'Assimp.Mesh' does not contain a definition for 'GetTextureCoords' and no extension method 'GetTextureCoords' accepting a first argument of type 'Assimp.Mesh' could be found (are you missing a using directive or an assembly reference?)
I don't understand why! Can someone please help me?
AssimpNet is correctly referenced (I'm able to load and visualize any 3D model correctly if I comment the UV part)
And in the using part:
using System;
using System.Collections.Generic;
using System.IO;                //Required by Assimp-net
using System.Reflection;        //Required by Assimp-net
using System.Windows;
using System.Windows.Interop;
using System.Windows.Media;
using OpenTK;
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL;
using OpenTK.Platform;
using Assimp;                   //Required by Assimp-net
using Assimp.Configs;           //Required by Assimp-net
I also tried to change the order of the "using"s... or to remove some of them to see if there was some sort of namespace clashing but without any success.

**Comment by kimkulling** [comment]
See: https://sourceforge.net/p/assimp/discussion/817654/thread/0ec748e3/?limit=25

**Comment by acgessler** [comment]
It's `Mesh.TextureCoordinateChannels`.
