### ISSUE TITLE
Bug: gcc7.3, vs, cmake build error

### ISSUE THREAD

**Issue by sdragonx** [assimp/assimp#5317]
In file included from T:/assimp-5.3.1/code/Common/StbCommon.h:114:0,
                 from T:\assimp-5.3.1\code\Common\Assimp.cpp:1293:
T:/assimp-5.3.1/contrib/stb/stb_image.h: In function 'int stbi__parse_png_file(stbi__png*, int, int)':
T:/assimp-5.3.1/contrib/stb/stb_image.h:4893:45: error: '*((void*)& tc16 +4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
          if (p[0] == tc[0] && p[1] == tc[1] && p[2] == tc[2])
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
T:/assimp-5.3.1/contrib/stb/stb_image.h:5027:17: note: '*((void*)& tc16 +4)' was declared here
    stbi__uint16 tc16[3];
                 ^~~~
T:/assimp-5.3.1/contrib/stb/stb_image.h:4893:28: error: '*((void*)& tc16 +2)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
          if (p[0] == tc[0] && p[1] == tc[1] && p[2] == tc[2])
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
T:/assimp-5.3.1/contrib/stb/stb_image.h:5027:17: note: '*((void*)& tc16 +2)' was declared here
    stbi__uint16 tc16[3];
                 ^~~~
T:/assimp-5.3.1/contrib/stb/stb_image.h:4893:10: error: 'tc16' may be used uninitialized in this function [-Werror=maybe-uninitialized]
          if (p[0] == tc[0] && p[1] == tc[1] && p[2] == tc[2])
          ^~
T:/assimp-5.3.1/contrib/stb/stb_image.h:5027:17: note: 'tc16' was declared here
    stbi__uint16 tc16[3];

**Comment by sdragonx** [comment]
use the stb_image.h 2.26 (assimp 5.25) ok.

**Comment by sdragonx** [comment]
t:\assimp-5.3.1\code\common\StackAllocator.inl(59): error C2039: “max”: 不是“std”的成员 (编译源文件 T:\assimp-5.3.1\code\AssetLib
\FBX\FBXParser.cpp) [T:\build_dir\vc2017_x86\code\assimp.vcxproj]
  E:\microsoft\vs2017\VC\Tools\MSVC\14.10.25017\include\unordered_set(14): note: 参见“std”的声明 (编译源文件 T:\assimp-5.3.1\code
  \AssetLib\FBX\FBXParser.cpp)
t:\assimp-5.3.1\code\common\StackAllocator.inl(59): error C2039: “min”: 不是“std”的成员 (编译源文件 T:\assimp-5.3.1\code\AssetLib
\FBX\FBXParser.cpp) [T:\build_dir\vc2017_x86\code\assimp.vcxproj]

#define NOMINMAX          <---------------
#include <windows.h>

or
#ifdef min
#undef min
#undef max
#endif

**Comment by kimkulling** [comment]
Thanks for the report. As you have mentioned this issue was already fixed by an update.
