### ISSUE TITLE
VC compile error: std::min std::max is undefined

### ISSUE THREAD

**Issue by sdragonx** [assimp/assimp#5326]
```
assimp-5.3.1\code\common\StackAllocator.inl(59): error C3861: "min": unable to find identifier (source assimp-5.3.1\code\AssetLib\FBX\FBXParser.cpp) 
assimp-5.3.1\code\common\StackAllocator.inl(59): error C3861: "max": unable to find identifier (source assimp-5.3.1\code\AssetLib\FBX\FBXParser.cpp) 

assimp-5.3.1\code\common\StackAllocator.inl(59): error C2039: "max": Not a member of 'std' (source assimp-5.3.1\code\AssetLib\FBX\FBXUtil.cpp) 
assimp-5.3.1\code\common\StackAllocator.inl(59): error C2039: "min": Not a member of 'std' (source assimp-5.3.1\code\AssetLib\FBX\FBXUtil.cpp) 
```

CMakeLists.txt:

144 IF (WIN32)
145   # Use subset of Windows.h
146   ADD_DEFINITIONS( -DWIN32_LEAN_AND_MEAN )
147   ADD_DEFINITIONS( -DNOMINMAX) # adding this doesn't work...

T:\assimp-5.3.1\code\Common\StackAllocator.h
line 50:
`#include <algorithm>		// std::min std::max`

......--!

**Comment by sdragonx** [comment]
VC compilation error in version 5.2x+

**Comment by kimkulling** [comment]
This issue is closed in the latest version. Would it be an option for you to upgrade to it?

**Comment by kimkulling** [comment]
If I get the content in linked issue right this issue is not existing any more. I will close it. Please reopen it if the issue still exists,
