### ISSUE TITLE
Bug :fail to export the scene ,which is read from fbx file

### ISSUE THREAD

**Issue by hongjunnan** [assimp/assimp#5334]
code:
*******************************************************************
Assimp::Importer importer;
Assimp::Exporter exporter;
const aiScene* scene = importer.ReadFile(path, 0);
exporter.Export(scene, "fbx", save_path + "/1.fbx");
***************************************************************

the bug:
i read fbx file and export the scene without any opration, but i cant get the same data if i read the exported file

**Comment by kimkulling** [comment]
PLease add more information like an example or the set of data that is missing. With this description, I cannot help you.
Reopen the issue when you have the data.

**Comment by hongjunnan** [comment]
<img width="323" alt="1" src="https://github.com/assimp/assimp/assets/78413373/9851be24-99ee-42cb-8e81-9aefcc8f9547">
<img width="365" alt="2" src="https://github.com/assimp/assimp/assets/78413373/beab4f60-208e-43f9-a3bb-2bbca0e14f37">

As seen, the first picture is the animation data i read from the fbx file
and i export the scene and then read the exported file, i get animation data shown in the second picture.
like  mDuration, mTicksSecond and in each channels,the positionkeys array size reduce from 3832 to 32,though the array data 
is right.
just like the animation data is cutted.

**Comment by hongjunnan** [comment]
hello?
i want to know did this problem can solve ?
or whats wrong with this pro.
