### ISSUE TITLE
"precompiled headers" slows down compilation

### ISSUE THREAD

**Issue by abma** [assimp/assimp#534]
its not used propably. imo PCH should be removed, because:
- it pulls in a lot of unused code
- it slows down static code analyze 
- if a single header is changed, the whole code needs to be recompiled.

imo in total it doesn't safe any compilation time.

are there any thoughts about how to handle pch? imo its mostly a windows/msvc feature...

in theory there could be a cmake/macro setting added which allows to disable the usage of PCH but this would require to maintain both settings.

i personally would remove PCH as "everything depends on everything" is bad style.

**Comment by acgessler** [comment]
I agree. PCH was added a long time ago and used with the old, hand-maintained VS solutions. CMake does not enable it.

`AssimpPCH.h` should be replaced by only the minimum set of includes necessary for each file.

**Comment by turol** [comment]
Better way would be to rip out your current PCH implementation and replace it with https://github.com/sakra/cotire which should do the whole thing automatically and be invisible to the user.
