### ISSUE TITLE
3D preview

### ISSUE THREAD

**Issue by kaihekaihe** [assimp/assimp#5369]
Our company has encountered some issues while previewing 3D files. We are now issuing a project requirement, and we are looking for experienced individuals or companies. We are willing to pay for solutions:
Able to render Maya/Max files with V-Ray materials on the web or desktop. Alternatively, capable of replacing V-Ray materials with standard materials and ensuring proper texture mapping.
Familiar with the implementation principles of textures in Maya/Max, FBX, GLB, etc., and capable of identifying and resolving issues where textures cannot be applied.
In-depth understanding of Maya/Max files, capable of identifying issues based on engine script exceptions.
Compatibility issues with Arnold rendering in different versions, capable of resolving or bypassing errors caused by version incompatibility.
Contact Information:
Phone: (086) 17780614757
Email: [846964144@qq.com](mailto:846964144@qq.com)

**Comment by tellypresence** [comment]
Not sure this is an appropriate forum for your employment post.  What are the acceptance criteria for closing this issue?

**Comment by kimkulling** [comment]
I am not sure if I get it right: you are looking for some developers who are able to solve your issue?

**Comment by kimkulling** [comment]
I will close this one.
