### ISSUE TITLE
travis build ANDROID=1 doesn't show an error when an error occours

### ISSUE THREAD

**Issue by abma** [assimp/assimp#537]
see https://travis-ci.org/assimp/assimp/jobs/58683564

ndk-jni:
     [exec] Current OS is Linux
     [exec] Executing '/home/travis/build/assimp/assimp/android-ndk-r8e/ndk-build' with arguments:
     [exec] 'all'
     [exec] 'NDK_PROJECT_PATH=/home/travis/build/assimp/assimp/workspaces/Android-NDK'

...

  [exec] 3 errors generated.
     [exec] make: **\* [/home/travis/build/assimp/assimp/workspaces/Android-NDK/obj/local/armeabi-v7a/objs/assimp_static/code/BlenderLoader.o] Error 1
     [exec] Result: 2
BUILD SUCCESSFUL
Total time: 37 seconds

**Comment by kimkulling** [comment]
Deprecated.
