### ISSUE TITLE
Bug: ASSIMP_BUILD_ZLIB switch is ON, while it should be OFF as stated in Build.md

### ISSUE THREAD

**Issue by kcrif** [assimp/assimp#5381]
From Build.md
ASSIMP_BUILD_ZLIB (default OFF): Build our own zlib.

While in CMakeList.txt
IF (WIN32)
  OPTION( ASSIMP_BUILD_ZLIB
    "Build your own zlib"
    ON
  )
ELSE()
  OPTION( ASSIMP_BUILD_ZLIB
    "Build your own zlib"
    ON
  )
ENDIF()

I guess this is the reason, why the build of assimp 5.3.1 via vcpkg in manifest mode fails. See also #5340

**Comment by kimkulling** [comment]
You are right. I will close this for the referenced PR. Thanks for your investigations.
