### ISSUE TITLE
Bug: possibly dangling reference to a temporary [-Werror=dangling-reference]

### ISSUE THREAD

**Issue by SamuelZy810** [assimp/assimp#5383]
The error occurs while compiling, 

C:/Users/samue/Desktop/assimp/code/AssetLib/FBX/FBXParser.cpp:670:20: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  670 |     const Element& a = GetRequiredElement(scope,"a",&el);
      |  

I am using gcc compiler (version 13).

Is there any branch that fixex this error or possibly any compiler that has no problem compiling this library?

**Comment by turol** [comment]
Duplicate of https://github.com/assimp/assimp/issues/5145
