### ISSUE TITLE
include definitions coding style

### ISSUE THREAD

**Issue by arris69** [assimp/assimp#539]
replace 
```C
#include "../include/assimp/<whatever>" 
```
with 
```C
#include "assimp/<whatever>"
```
?

**Comment by acgessler** [comment]
Sounds good to me.

Also, let's order them: system includes first, then assimp public headers, then assimp internal headers.

**Comment by acgessler** [comment]
Note that it should be `#include <assimp/...>` though since it's not a relative path anymore, so we shouldn't suggest this.

**Comment by kimkulling** [comment]
Makes the build sometimes faster, because <> has less folder to look for included files. +1 from me too.

**Comment by kimkulling** [comment]
One thing I observed: a lot of our private headers are not working standalone. We should fix this as well.

**Comment by arris69** [comment]
<> has more folders to check (at least for gcc on linux). 
"" always just checks from projects parent folder (if you start to call gcc from there):
```bash
 LANG=C gcc --verbose -ICommandlineIncludePath -I. ctest.c
```
```gcc
#include "..." search starts here:
#include <...> search starts here:
 CommandlineIncludePath
 .
 /usr/lib/gcc/i486-slackware-linux/4.8.2/include
 /usr/local/include
 /usr/lib/gcc/i486-slackware-linux/4.8.2/include-fixed
 /usr/include
```

**Comment by acgessler** [comment]
"" falls back to <> if it does not find it locally. Now, if we include headers as assimp/... then they're found only by looking at include paths. <> should be faster since it omits looking at the relative folder.

**Comment by arris69** [comment]
but if you put a header in assimp/... then this one should be used and not one from gcc's hosts folders.
btw. if its not found in <package_source_includes>assimp/ then already smthg. goes wrong.

for an application like assimp_cmd/assimp_view or users app i agree, includes should be <assimp/...>
but not for code/ folder in the assimp sources.

just my 2cent :-)

**Comment by abma** [comment]
-> using "" should be faster as it searches the realtive path first. usally include directories contain multiple paths. also when arguing about "what is faster" it should be benchmarked. very likely no difference will be found because folder accesses are cached pretty well by os and looking for files will take like 0.001 second vs. 10 seconds to compile it. imo just skip the argument about speed in this case.

why do you want to use angle brackets in internal assimp files?

https://stackoverflow.com/questions/3162030/difference-between-angle-bracket-and-double-quotes-while-including-heade

we want the local files from assimp used here and not the system headers. <> is meant for system headers... why add a hack and use <> for files which are not in system?

imo it comes to the point: what is better to maintain / read / less confusing?

**Comment by acgessler** [comment]
The point about accidentally using system headers is a good one. Maybe it is safer to stick with the ../include/assimp folders. It's not a problem for us to ensure that CMake sets the include path, but there are some alternative build systems still around.

WRT "" vs <>: for code in ./code, accessing assimp/ is only ever found if ../include is in the include path. Thus "" and <> have the same effect, but "" suggests that the headers would be found without looking at include paths, which IMHO sends the wrong message. Speed of lookup should be totally irrelevant indeed.

**Comment by arris69** [comment]
nice to see the question "what is better to maintain / read / less confusing?" and "what do other projects?"
for speed the <> builds really 20 seconds faster than the "" version.
but in clear coded projects i always just noticed local includes with quotes and no relative upperfolder path entries.
and i suggest also to reduction to 2 include folders (<assimp_src>/include and <assimp_contrib>) then use includes for irlicht unzip etc. with the subfolder part under contrib/ in the sources.
if the boost headers are also assimp specific then the headers were better placed under contrib.

btw. i'll try to resolve the merge conflicts, the < vs. " question can easy fixed by sed.

**Comment by kimkulling** [comment]
The point about acidentally using system headers instead of assimp-specific ones cannot happen, because we would use the assimp-prefix in the include-statement: include <assimp/mesh.h>

And I saw both styles in different OS-projects: OpenSceneGraph for instance is using the <> style.

**Comment by acgessler** [comment]
No, accidentally using headers of an already installed assimp.

**Comment by kimkulling** [comment]
OK, this is an issue, you are right!

**Comment by arris69** [comment]
it's not possible accidentally use wrong headers if it happens it's gross negligence?
independed from " or < -I pathes are checked before systems include folders so if wrong header is used then your source refers to an "outdated" header what you deleted from the project sources without to check for its usage.

**Comment by abma** [comment]
as contributor _imo_  #include "assimp/<whatever>" looks cleanest and should be most flexible.

**Comment by kimkulling** [comment]
Fixed.
