### ISSUE TITLE
[enhancement] portable DLL directory

### ISSUE THREAD

**Issue by Tcll** [assimp/assimp#540]
load dll from '/pyassimp/DLLS/assimp.dll'

implementation derived from PyOpenGL

```
DLL_DIRECTORY = os.path.join( os.path.dirname( OpenGL.__file__ ), 'DLLS' )

fullName = None
try:
    fullName = util.find_library( name )
    if fullName is not None:
        name = fullName
    elif os.path.isfile( os.path.join( DLL_DIRECTORY, name + '.dll' )):
        name = os.path.join( DLL_DIRECTORY, name + '.dll' )
except Exception, err:
    log.info( '''Failed on util.find_library( %r ): %s''', name, err )
    # Should the call fail, we just try to load the base filename...
    pass
```

for more info, look in /OpenGL/platform/ctypesloader.py

**Comment by Tcll** [comment]
here's something I've done to make things more portable:

    import sys
    DLL_DIRECTORY = os.path.join( os.path.dirname( sys.modules['pyassimp'].__file__ ), 'DLLS' )

**Comment by Tcll** [comment]
did something better, this is all that was needed:

    import sys
    additional_dirs, ext_whitelist = [
        os.path.dirname( sys.modules['pyassimp'].__file__ ).replace('\\','/')+'/DLLS/'
        ],[]

contains:

    >>> 
    ['/media/tcll/copy/UMC_v3.0a/libs/pyassimp/DLLS/']

though I'm on linux, so shouldn't the other 2 usr/ directories be in there as well?? >.>
(the output is printed after that testing)

**Comment by acgessler** [comment]
Sounds nice, would you make it into a Pull Request?

**Comment by Tcll** [comment]
I can try >.>
never done it before though... heh
