### ISSUE TITLE
Bug: Dockerfile missing RUN apt install zlib1g-dev 

### ISSUE THREAD

**Issue by limor666** [assimp/assimp#5403]
**Describe the bug**
I wanted to create a docker image using the Dockerfile in the top level of the project
Tried running : docker build .
Got error about missing zlib
I resolved the problem by adding a line 8 to Dockerfile: RUN apt install zlib1g-dev 

**Platform (please complete the following information):**
 - Ubuntu 22.04

**Comment by kimkulling** [comment]
I have prepared a PR, thanks for your feedback.
