### ISSUE TITLE
run postprocessing on imported scene

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#5416]
i wonder whether it would be possible/practical/useful to run postprocessing steps on an already imported scene.

as of now, we have to specify the postprocessing when loading a model, but i find that i would sometimes like to run them on previously imported models (ideally getting a new `aiScene`).

**Comment by kimkulling** [comment]
Of course you can appli the postprocessing steps afterwards onto you scene. There is a dedicated API-call you can use for this:

`aiApplyPostProcessing(const aiScene *pScene, unsigned int pFlags);`

Hope that helps.
Kim
