### ISSUE TITLE
How to compile static libraries and compile with arm's compilation toolchain

### ISSUE THREAD

**Issue by yanxiaodongRain** [assimp/assimp#5424]
How to compile static libraries and compile with arm's compilation toolchain

**Comment by seanth** [comment]
I just compiled on an ARM mac this evening using:

cmake -S . -B build -G Ninja -DASSIMP_BUILD_TESTS=OFF, -DASSIMP_BUILD_ASSIMP_TOOLS=ON; cmake --build build

**Comment by yanxiaodongRain** [comment]
thanks for your reply
I want to specify your own arm cross-compilation toolchain address, such as/home/tujz/depository/lichee/out/t507 / demo2.0 / longan/buildroot/host/aarch64-buildroot-linux-gnu/. Because it needs to be ported to the T5 board to run

**Comment by turol** [comment]
Consult the CMake manual https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html
