### ISSUE TITLE
Bug: SEGV when trying to access aiMaterial->mNumProperties

### ISSUE THREAD

**Issue by TheBoneJarmer** [assimp/assimp#5429]
**Describe the bug**
Like the title says, when I try to access the `mNumProperties` field of an `aiMaterial` instance, the program crashes because of a segmentation fault. The instance itself has an address though.

**To Reproduce**
```c++
aiScene* scene = ...

for (int i=0; i<scene->mNumMaterials; i++) {
    aiMaterial* mat = scene->mMaterials[i];
    unsigned int num_props = mat->mNumProperties; // Crash
}
```

**Expected behavior**
No crash

**Screenshots**

**Platform (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 21 (not sure)

**Additional context**

**Comment by stephengold** [comment]
In order to reproduce this, the team is going to need more info, probably a copy of the model you loaded.

**Comment by kimkulling** [comment]
Do fully agree, at least we will need your model. Just reopen the issue if you have added it.
