### ISSUE TITLE
Bug: Doesn't compile with zlib-ng

### ISSUE THREAD

**Issue by theoparis** [assimp/assimp#5430]
**Describe the bug**

Assimp doesn't compile with [zlib-ng](https://github.com/zlib-ng/zlib-ng) because of the legacy symbols such as `ulong` and `voidpf`. zlib-ng is a fork of zlib that uses various patches (from CloudFlare and Intel) to improve performance.

**To Reproduce**

Build assimp with a zlib-ng cmake build with `-DZLIB_COMPAT=ON`.

**Expected behavior**

Successful build.

**Screenshots**

![image](https://github.com/assimp/assimp/assets/11761863/1074e552-de0e-450b-ae16-160d5812fccf)

**Platform (please complete the following information):**
 - OS: Gentoo Linux
 - Assimp version: 5.2.5

**Additional context**

According to [zlib-ng's zconf.h.in](https://github.com/zlib-ng/zlib-ng/blob/develop/zconf.h.in#L123), these are legacy symbols.

**Comment by theoparis** [comment]
Additionally it seems like the errors are due to not including zlib.h.

**Comment by kimkulling** [comment]
PR is on its way.
