### ISSUE TITLE
Bug: DXF conversion assigns incorrect colors

### ISSUE THREAD

**Issue by seanth** [assimp/assimp#5443]
**Describe the bug**
When using assimp to convert from DXF, incorrect colours are given to 3dfaces

**To Reproduce**

1. Install assimp
2. run the command 'assimp export .dxf .obj for a file that defines colours in the 3dfaces in the dxf file
3. visualize the resulting .obj

**Expected behavior**
Colours in the output file should approximate those in the input file

**Screenshots**
DXF as seen in Sketchup
<img width="1220" alt="Screenshot 2024-01-26 at 15 42 36" src="https://github.com/assimp/assimp/assets/371465/5d60a5b3-cf5d-42a3-9668-1af0ee313783">

Resulting .obj as made by assimp using pr #5426 
<img width="820" alt="Screenshot 2024-01-26 at 15 49 47" src="https://github.com/assimp/assimp/assets/371465/2fef94f1-db2d-4832-a60a-d0a6425e4404">

**Platform (please complete the following information):**
OS: Mac OS 12.6 and 13.5.1
Browser: not applicable
Version: Version 5.3 -shared -st, using the fix for incorrect insertion placement (pr #5426 )

**Comment by seanth** [comment]
Appears to be the same problem as reported in issue #3411. The problem is that AIC table in the DXFLoader.cpp is incorrect, so the index given in the DXF file gets matched to an incorrect colour.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5426
