### ISSUE TITLE
Bug: Identity matrix check problem

### ISSUE THREAD

**Issue by fvbj** [assimp/assimp#5455]
**Describe the bug**
After exporting to GLB/GLTF format, some node transforms are set as identity. This is because the matrices are compared in the aiMatrix4x4t::IsIdentity() method to a large epsilon 10e-3 threshold. This method is also used in other calls and it would be better to set epsilon as a call parameter. The default value handles backward compatibility of legacy code.
links to similar issues: #3702, #2589

**To Reproduce**
m = aiMatrix4x4(1.001f, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
m.IsIdentity() // will incorrectly return the true value

**Expected behavior**
The method performs the comparison according to the specified epsilon

Solved by https://github.com/assimp/assimp/pull/5445

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5445
