### ISSUE TITLE
MacOS compilation error: error: unknown type name 'constexpr' constexpr ai_real ai_epsilon = (ai_real) 1e-6;

### ISSUE THREAD

**Issue by Zhuofan-Zhang** [assimp/assimp#5460]
I have tried to compile from the source code and import the library as an external library using add directory.
And it's giving me errors like below.
<img width="758" alt="image" src="https://github.com/assimp/assimp/assets/67167576/dc6e39cd-eef5-425e-a517-fbfe7778f0b3">

**Comment by turol** [comment]
`constexpr` has been a thing since C++11. You have somehow set the wrong C++ standard version in your project.
