### ISSUE TITLE
Bug: segmentation fault while removing redundant materials

### ISSUE THREAD

**Issue by stephengold** [assimp/assimp#5461]
**Describe the bug**
While testing PR #5451 (the fix for issue #5438) I got a segmentation violation during post-processing. I reported this at #5438 on 1 February 2024, but since there's been no response (and the issue is closed and I don't have permission to re-open it) I'm filing a new issue.

**To Reproduce**
1. Build the `assimp` command from source code recent enough to include PR #5451.

2. Unzip the "Running.gltf" file from the following archive:
[test.zip](https://github.com/assimp/assimp/files/14058247/test.zip)

3. Execute the following command:
    `bin/assimp info Running.gltf -rrm`

**Expected behavior**
Since the test model is animation-only (contains no meshes) all its materials are redundant. Removing redundant materials should produce a model with no materials. The post-processor should not crash!

**Screenshots**
```console
$ bin/assimp info ~/Downloads/Running.gltf -rrm
param = -rrm
Launching asset import ...           OK
Validating postprocessing flags ...  OK
100 %Importing file ...                   OK 
   import took approx. 0.01244 seconds

Segmentation fault (core dumped)
$ bin/assimp version
------------------------------------------------------ 
Open Asset Import Library ("Assimp", https://github.com/assimp/assimp) 
 -- Commandline toolchain --
------------------------------------------------------ 

Version 5.3 -debug -shared -st (GIT commit ff5b0ae5)

$ 
```

**Platform (please complete the following information):**
 - OS: Linux Mint 21.3 (x86_64, 5.15 kernel)
 - Browser: Firefox
 - Version: Assimp built from GIT commit ff5b0ae5 (8 February 2024)

**Additional context**
N/A

**Comment by stephengold** [comment]
Address sanitizer output is available from #5438

**Comment by stephengold** [comment]
Correction: the crash does not occur during post-processing. It occurs while calculating the scene's memory usage.

https://github.com/assimp/assimp/blob/ff5b0ae575082fcd10b9c887390c321a110d2051/code/Common/Importer.cpp#L1268

Using GDB, I set a breakpoint at code/Common/Importer.cpp line 1268, and saw that `mScene->mNumMaterials` is 1. I believe it should've been set to zero in `RemoveRedundantMatsProcess::Execute()`.

Stepping through `RemoveRedundantMatsProcess::Execute()`, I see it return from line 161:

https://github.com/assimp/assimp/blob/ff5b0ae575082fcd10b9c887390c321a110d2051/code/PostProcessing/RemoveRedundantMaterials.cpp#L159-L162

At that point, `mMaterials[i]` has been set to `nullptr`, but `mNumMaterials` has not been updated---it is still 1. That explains the segmentation violation.

**Comment by stephengold** [comment]
I could easily write a PR to solve this issue, but after what happened with #5438 I've decided to wait for an explicit PR request and not submit unsolicited code.

**Comment by kimkulling** [comment]
Hi, would be great if you could prepare a PR for this issue.

Thanks!

**Comment by stephengold** [comment]
Since #5467 is integrated, I believe this issue is solved and can be closed.
