### ISSUE TITLE
License missing for pyassimp

### ISSUE THREAD

**Issue by Tobias-Fischer** [assimp/assimp#5463]
Dear @severin-lemaignan,

I can see that you are listed as the author of PyAssimp. The setup.py lists ISC as the license. Unfortunately, a license file is missing. As I'd like to package pyassimp on conda-forge, it would be great if you could add a license file.

Many thanks,
Tobi

**Comment by severin-lemaignan** [comment]
Hi Tobi,
I've just create the PR, hopefully will be merged soon.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5465

**Comment by Tobias-Fischer** [comment]
Thanks all :)
conda-forge PR FYI: https://github.com/conda-forge/staged-recipes/pull/25413
