### ISSUE TITLE
raise AssimpError("assimp library not found")

### ISSUE THREAD

**Issue by liujf69** [assimp/assimp#5481]
I followed the steps below to install pyassimp in Centos, but I got the following bug while importing pyassimp:
![image](https://github.com/assimp/assimp/assets/50939145/10aa4e90-335c-4cc7-812c-55a0c9f1e0f3)

```
git clone https://github.com/Microsoft/vcpkg.git
set(VCPKG_LIBRARY_LINKAGE dynamic)
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install assimp
pip install pyassimp
```

I tried copying the compiled dynamic library to the folder corresponding to helper.py, but the above error still occurred.
![image](https://github.com/assimp/assimp/assets/50939145/fdd30d5a-b933-4798-b81b-deb8dddee125)

I don't know how to install and use pyassimp correctly in centos system.

**Comment by kimkulling** [comment]
To fix this you can try to add the folder where your so file is located to the environment variable *LD_LIBRARY_PATH* by:

`export LD_LIBRARY_PATH=<path_to_your_folder_with_assimp_so>`

If this does not work you should check if the 64-bit version of assimp is installed:

`file <your_assimp_so>`

The output shall contain something like **64-bit so** 

Hope that will help you.

**Comment by kimkulling** [comment]
No new post so I think this issue is not active any more.
