### ISSUE TITLE
Bug: Parsed mesh has invalid name

### ISSUE THREAD

**Issue by lyzirving** [assimp/assimp#5508]
**Describe the bug**
platform: windows
ide: visual studio 2022
assimp version: 5.3.1

i am loading a gltf, but the all the mesh's names are garbled characters, as the following pic shows:
![image](https://github.com/assimp/assimp/assets/31678071/3708b384-bc06-4b13-859d-7bcb99d02cc4)

i have searched for google, but can't find any solution,  i am realy glad to see you could help me with it.
here is the gltf:
[Car.zip](https://github.com/assimp/assimp/files/14652677/Car.zip)

**Comment by tellypresence** [comment]
Here's an example with "garbled characters"
<img src="https://github.com/assimp/assimp/assets/26958898/692caa01-f5d1-482c-85ce-529730ed7c67" width=320/>

**Comment by lyzirving** [comment]
@tellypresence 
i am sorry i didn't notice that.
Any way, thanks a lot.
