### ISSUE TITLE
Quick Request: Updated Binary Release

### ISSUE THREAD

**Issue by mcmonkey4eva** [assimp/assimp#551]
I need the fixes that allow loading Blender 2.7 .blend files, and I absolutely cannot compile AssImp. (DirectX SDK won't install properly to start...)

Could I get a copy of the 32-bit Assimp.dll with the latest patches?
Perhaps it's even time for an official release of version 3.2 or 3.1.2 or whatever - it's been almost a year now since the last release, and it seems like .blend support would be a pretty major patch, not to mention all the other things that were fixed since then.

**Comment by g-pechorin** [comment]
Sorry if this sounds like DIY stores trying to make your problem fit their branded solution ...

I wonder if "DirectX SDK won't install properly to start..." is the stupid "[s1023 error](https://support.microsoft.com/en-us/kb/2728613)"
* C++ 2010 Redistributable packages are already installed on your computer
* DirectX SDK tries to install these itself and doesn't receive "new package installed"
	* since they're already installed
* The DirectX SDK installation gives up

The recommend solution (which I've used at least three times) is to remove these specific Redistributable packages then run the installer which will install these on its own. [The knowledge base article](https://support.microsoft.com/en-us/kb/2728613) suggests these two commands

	MsiExec.exe /passive /X{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
	MsiExec.exe /passive /X{1D8E6291-B0D5-35EC-8441-6616F567A0F7}

I know that it's not what you wanted, (pre-built binaries) but maybe it gets you closer to what you need?

(In my experience, CMake tries to dynamically link the CRT anyway which is "real fun" when co-workers don't have the same versions installed)

**Comment by acgessler** [comment]
+1 for new release.

You do not need the DirectX SDK to install Assimp unless you also need AssimpView. Just turn off building the tools in CMake and DX should no longer be a dependency, let me know if it is.

If you need a viewer, plase try open3mod instead: github.com/acgessler/open3mod (it should also be built against assimp after the blender 2.7 fixes, so you could take the binaries from there!)

**Comment by mcmonkey4eva** [comment]
Oh... disabling tools makes it a lot easier.
Thank you.
Now... how do I get a DLL out of this? I made VC10 project files via CMake, and compiled it in Visual C++ 2010... and the closest I get is `assimp-vc100-mtd.dll` which is too large and does not have the appropriate entry points.

**Comment by acgessler** [comment]
Try a release build. It should produce `assimp-vc100-md.dll`, which should have the entry points you expect.

**Comment by mcmonkey4eva** [comment]
Hooray! Thank you! That... mostly works, mostly!

![Image](https://i.imgur.com/smhVIl5.png)
it seems to have dropped a few faces though? I'm definitely using `Triangulate` when importing it, so I'm out of guesses as to why it would do that.
It's also not animating.
