### ISSUE TITLE
Bug: Export OBJ `JoinIdenticalVertices = false` not respected

### ISSUE THREAD

**Issue by JulianKnodt** [assimp/assimp#5513]
**Describe the bug**
When exporting an OBJ file with `JoinIdenticalVertices = false`, it will still merge vertices.
This is because it does not consider the face index at all when exporting the mesh.
Instead, the index can be added to the `vertexData` struct if and only if `JoinIdenticalVertices = false` (and the comparator should also be updated).

**Expected behavior**
Should not merge identical vertices iff their index is not the same.

**Comment by kimkulling** [comment]
Are the vertices merged during the import?

**Comment by JulianKnodt** [comment]
Currently the vertices are not merged during import, only export.
