### ISSUE TITLE
include header file fail

### ISSUE THREAD

**Issue by JoJoBizarreAdventure** [assimp/assimp#5517]
I import assimp v5.3.1 as a submodule. Then use similar cmake as below:

    add_subdirectory(assimp)
    function(link_assimp target_name)
        target_link_libraries(${target_name} PRIVATE assimp)
    endfunction()

When I use link_assimp later, something wrong happend. 
![image](https://github.com/assimp/assimp/assets/64888038/f6110bd1-7a92-4ef0-b1b1-adc892f6ab58)

As the image showed, header file including work normally in source file but fail in the header.

I have tried to use forward declaration  to avoid this, but it's hard to deal with enum type like aiTextureType. 

I test all these things under win11 with visual studio toolchain in Clion.

I wonder if there is some smart tricks for fixing. Please give me some advice.

**Comment by JoJoBizarreAdventure** [comment]
The situation is just similar to this one - https://github.com/assimp/assimp/issues/4827

But the include directory should be already linked with target_link_libraries. So confusing...

**Comment by JoJoBizarreAdventure** [comment]
Oh! I got an answer.  Update the previous code like this will work:
```
add_library(assimp_header INTERFACE)
target_include_directories(assimp_header
        INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR}/assimp/include)
function(link_assimp target_name)
    target_link_libraries(${target_name} PRIVATE assimp)
    target_link_libraries(${target_name} INTERFACE assimp_header)
endfunction()
```
Adding INTERFACE library will help with including. I check few repo for this ( like eigen,),  all of these having similar design.

I wonder maybe assimp need one either.

**Comment by kimkulling** [comment]
Thanks for your update. I will close the issue.
