### ISSUE TITLE
Evaluate feasibility of USD implementation via "tinyusdz" project

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5520]
[Update] superseded by #5547 

I was playing around with integrating [`tinyusdz`](https://github.com/syoyo/tinyusdz) for USD (usd/usda/usdc/usdz) model loading.

(Have raised PR #5522 in case anyone is interested in testing)

Note: this report is based on `dev` (main) branch of `tinyusdz` project

## Summary
Not sure `tinyusdz` project is ready for adoption.

In cases where the models successfully load, basic geometry looks good.  But, many USD model files available for download use "composition" (are "unflattened"); these models will fail to load using `tinyusdz`.  This is mentioned in e.g.
- `tinyusdz` [issue 62](https://github.com/syoyo/tinyusdz/issues/62)
- `tinyusdz` [issue 102](https://github.com/syoyo/tinyusdz/issues/102)

And I'm struggling to get at UVs, animations etc.  It seems like the project hasn't yet implemented full representation for OpenGL/Vulkan rendering.

#### Materials
Able to at least access colors for materials, and meshes are able to pick up their corresponding material (check "brainstem" model screenshots below; this model has about 59 meshes, and each mesh has its own material)

#### Geometry
Was able to load some models in `.usda`, `.usdc`, and `.usdz` format and normals look OK:
<table>
<tr><th>Model</th><th>Screenshot</th><th>Debug normals<br>(Red = X, Green = Y, Blue = Z)</th></tr>
<tr><td> <a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/BrainStem/BrainStem.usdz"><tt>BrainStem.usdz</tt></a><br>(<a href="https://github.com/usd-wg/assets">usd-wg/assets</a>)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/84aeed09-77b5-471d-be38-b165bbc7e870" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/c81c0ba2-7137-4604-b556-f4be29451f5c" alt="" width=90/></td></tr>
<tr><td> <a href="https://github.com/syoyo/tinyusdz/blob/dev/models/suzanne.usdc"><tt>suzanne.usdc</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/6deda458-c4db-48ff-b6bf-22d6cafbf0ae" alt="suzanne usdc_loaded_via_tinyusdz_Screenshot_20240330-101420" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/a6c3a99a-f09c-4251-980d-196fb701bb8a" alt="assimp-issue-5520_tinyusdz_suzanne_normals_look_ok" width=90/></td></tr>
<tr><td> <a href="https://github.com/syoyo/tinyusdz/files/13725770/Furriers_guild_chest_in_Myslenice.zip"><tt>Furriers_guild_chest_in_Myslenice.usdz</tt></a><br>(<tt>tinyusdz</tt> <a href="https://github.com/syoyo/tinyusdz/issues/109">issue 109</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/a15bd3b5-ccd0-428e-8c9c-9b4175a53c5f" alt="furriers_chest" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/11d41120-5210-4e4b-959c-76fd803db2fe" alt="furriers_chest_normals" width=90/></td></tr>
<tr><td> <a href="https://github.com/syoyo/tinyusdz/files/14047718/untitled.usdz.zip"><tt>untitled.usdz</tt></a><br>(<tt>tinyusdz</tt> <a href="https://github.com/syoyo/tinyusdz/issues/115">issue 115</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/dfd0ce97-b1f9-4f10-961f-bc02f7bf2a40" alt="assimp-issue-5520_tinyusdz_issue_115_model" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/4cdb7759-eccd-43be-adb2-dd1ce2c26860" alt="assimp-issue-5520_tinyusdz_issue_115_model_normals_ok" width=90/></td></tr>
<tr><td> <a href="https://github.com/syoyo/tinyusdz/files/13885625/Netsuke_-_Shoki_capturing_an_oni.zip"><tt>Netsuke_-_Shoki_capturing_an_oni.usdz</tt></a><br>(<tt>tinyusdz</tt> <a href="https://github.com/syoyo/tinyusdz/issues/116">issue 116</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/b74cd4bf-13d8-4398-b838-fe9abdd765c4" alt="assimp-issue-5520_tinyusdz_issue_116_model" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/ca68034c-db81-43b2-8fbf-79b616f7fb7e" alt="assimp-issue-5520_tinyusdz_issue_116_model_normals_ok" width=90/></td></tr>
<tr><td> <a href="https://developer.apple.com/augmented-reality/quick-look/models/drummertoy/toy_drummer_idle.usdz"><tt>toy_drummer_idle.usdz</tt></a><br>(<a href="https://developer.apple.com/augmented-reality/quick-look/">developer.apple.com</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/ddaabaa9-ba2c-4c0a-bb5c-2a8e9c6f86e3" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/af33462f-de97-4a3e-aea6-cb1ddc07c22a" alt="" width=90/></td></tr>
<tr><td> <a href="https://developer.apple.com/augmented-reality/quick-look/models/toycar/toy_car.usdz"><tt>toy_car.usdz</tt></a><br>(<a href="https://developer.apple.com/augmented-reality/quick-look/">developer.apple.com</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/04786e8f-dd7d-4005-ac0a-37c33b7f6497" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/88f76d94-cb82-487f-bdbe-c7b46190956d" alt="" width=90/></td></tr>
<tr><td> <a href="https://developer.apple.com/augmented-reality/quick-look/models/vintagerobot2k/robot_walk_idle.usdz"><tt>robot_walk_idle.usdz</tt></a><br>(<a href="https://developer.apple.com/augmented-reality/quick-look/">developer.apple.com</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/8386c547-b4b0-48a3-94c0-a97ef3a30f5c" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/a94b36b8-fa25-4bf4-9871-eaf9c23a6566" alt="" width=90/></td></tr>
<tr><td> <a href="https://developer.apple.com/augmented-reality/quick-look/models/stratocaster/fender_stratocaster.usdz"><tt>fender_stratocaster.usdz</tt></a><br>(<a href="https://developer.apple.com/augmented-reality/quick-look/">developer.apple.com</a>)</td><td><img src="https://github.com/assimp/assimp/assets/26958898/23440da6-a741-42ae-9ee4-3c94c9a2be34" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/59d8ab7d-4667-4a55-8f78-65b4f694931e" alt="" width=90/></td></tr>
<tr><td> <a href="https://sketchfab.com/3d-models/compsognathus-762fd4e099b640aeb6e3341aec042cea"><tt>compsognathus.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/e93c30ac-6013-4a1d-8b9d-f78d8c7cdaa8" alt="" width=90/></td><td><img src="https://github.com/assimp/assimp/assets/26958898/65dba5d7-d3c7-4eb6-a0eb-7f82a4d1a994" alt="" width=90/></td></tr>
</table>

#### USD-WG models
_*Note: these models load OK on `rendermesh-refactor` branch, so expect will be fixed soon*_
Vehicle models under `geo` folders for [`usd-wg`](https://github.com/usd-wg/assets/tree/main/full_assets) crashed app when attempting load, probably worth investigating:
<table>
<tr><th>Crashing model</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/4wd/geo/4wdGeo.usd"><tt>4wdGeo.usd</tt></a></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/ambulance/geo/ambulanceGeo.usd"><tt>ambulanceGeo.usd</tt></a></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/formula/geo/formulaGeo.usda"><tt>formulaGeo.usda</tt></a></td></tr>
</table>

#### Pixar models
<table>
<tr><th>Model set</th><th>Crashing model</th></tr>
<tr><td rowspan=2><a href="https://openusd.org/release/dl_kitchen_set.html">Kitchen Set</a></td><td><tt>assets/CeilingLight/CeilingLight.geom.usd</tt></td></tr>
<tr><td><tt>assets/Stove/Stove.geom.usd</tt></td></tr>
<tr><td rowspan=2><a href="https://openusd.org/release/dl_usdskel_examples.html">UsdSkel Examples</a></td><td><tt>HumanFemale/assets/HumanFemale.low_payload.usd</tt></td></tr>
<tr><td><tt>HumanFemale/assets/HumanFemale.medium_payload.usd</tt></td></tr>
</table>

#### Official Apple sample models
Of the 15 sample models on Apple's landing page, only the 4 in the table above load; the other 11 fail with `Validation failed: A node of the scene-graph is nullptr`

#### Official Pixar sample models
Can't load [Pixar sample models](https://openusd.org/release/dl_downloads.html)
- [Kitchen Set](https://openusd.org/release/dl_kitchen_set.html) (mentioned in `tinyusdz` issues [25](https://github.com/syoyo/tinyusdz/issues/25), [102](https://github.com/syoyo/tinyusdz/issues/102))
AFAICT none of the dozens of assets loads; here's examples of the errors for the `Bottle` asset:
<table>
<tr><th>Model</th><th>Error(s)</th></tr>
<tr><td><a href="https://openusd.org/release/dl_kitchen_set.html"><tt>Kitchen_set/assets/Bottle/Bottle.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_kitchen_set.html"><tt>Kitchen_set/assets/Bottle/Bottle.geom.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_kitchen_set.html"><tt>Kitchen_set/assets/Bottle/Bottle_payload.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
</table>

- [City Set](https://openusd.org/release/dl_city_set.html) (fails w/`nullptr`)
<table>
<tr><th>Model</th><th>Error(s)</th></tr>
<tr><td><a href="https://openusd.org/release/dl_city_set.html"><tt>PointInstancedMedCity/PointInstancedMedCity.usd</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
</table>

- [UsdSkel Examples](https://openusd.org/release/dl_usdskel_examples.html) (mentioned in `tinyusdz` issues [25](https://github.com/syoyo/tinyusdz/issues/25), [62](https://github.com/syoyo/tinyusdz/issues/62))
<table>
<tr><th>Model</th><th>Error(s)</th></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.full.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.medium.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.low.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.full.blendshapes.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.medium.blendshapes.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://openusd.org/release/dl_usdskel_examples.html"><tt>modelHumanFemale.low.blendshapes.usd</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
</table>

#### USD-WG models
Couldn't get any of the [`usd-wg`](https://github.com/usd-wg/assets/tree/main/full_assets) models to load, either `nullptr` or `0 meshes` errors for all:
<table>
<tr><th>Model</th><th>Error(s)</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/CarbonFrameBike/CarbonFrameBike.usdz"><tt>CarbonFrameBike.usdz</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/ElephantWithMonochord/SoC-ElephantWithMonochord.usdc"><tt>SoC-ElephantWithMonochord.usdc</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/ElephantWithMonochord/SoC-ElephantWithMonochord_thumbnail.usda"><tt>SoC-ElephantWithMonochord_thumbnail.usda</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/McUsd/McUsd.usda"><tt>McUsd.usda</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/McUsd/McUsd.usdz"><tt>McUsd.usdz</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/McUsd/McUsd_10cm.usda"><tt>McUsd_10cm.usda</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/McUsd/McUsd_10cm.usdz"><tt>McUsd_10cm.usdz</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/OpenChessSet/chess_set.usda"><tt>chess_set.usda</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there</tt></td></tr>
</table>

#### CGTrader models
Unable to load these models (possibly "unflattened" structure prevents `tinyusdz` from handling them properly?)
<table>
<tr><th>Model</th><th>Error(s)</th></tr>
<tr><td><a href="https://www.cgtrader.com/items/898927/download-page"><tt>rock.usd</tt></a><br>(from <tt>tinyusdz</tt> <a href="https://github.com/syoyo/tinyusdz/issues/62">issue 62</a>)</a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://www.cgtrader.com/items/2639757/download-page"><tt>wraith.usdc</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
<tr><td><a href="https://www.cgtrader.com/items/2639757/download-page"><tt>wraith.usdz</tt></a></td><td><tt>Validation failed: A node of the scene-graph is nullptr</tt></td></tr>
</table>

#### Normals
Having some trouble with normals (which are "face varying" rather than per-vertex) for other models, e.g.
textured cube normals completely insane (Red = X axis, Green = Y axis, Blue = Z axis)
<img src="https://github.com/assimp/assimp/assets/26958898/b1d756d6-1da3-49bf-9958-38ac8e950077" alt="assimp-issue-5520_tinyusdz_cube_normals_insane" width=90/>

#### UVs
Having some trouble with UVs, which are also "face varying" rather than per-vertex
With checkerboard texture applied, cube and plane are incorrect
<img src="https://github.com/assimp/assimp/assets/26958898/ff9ff13a-5321-4fbb-9ee7-bc2895133c72" alt="assimp-issue-5520_tinyusdz_plane_checkerboard" width=90/><img src="https://github.com/assimp/assimp/assets/26958898/9c128d4c-35f5-47a4-ae0f-6507ab35b3ac" alt="assimp-issue-5520_tinyusdz_plane_texture" width=90/><img src="https://github.com/assimp/assimp/assets/26958898/d21733d4-9270-4749-a457-bc7d227c09d8" alt="assimp-issue-5520_tinyusdz_cube_checkerboard" width=90/>

### Hints
Temporarily rename .usdz file to *.usdz.zip, can then extract textures (pending embedded texture support)

**Comment by kimkulling** [comment]
Looks fine for me. We can try to optimize the loader for the detected issues. Could you provide a PR to test it?

**Comment by tellypresence** [comment]
PR #5522
