### ISSUE TITLE
Question: choose material/material file when loading scene

### ISSUE THREAD

**Issue by KleberPF** [assimp/assimp#5524]
Sorry if this is a dumb question, I don't know much about 3D formats. Currently I'm loading an OBJ model with `ReadFile` and everything works fine, but I would like to be able to render this same model with different materials without having to duplicate the model. So I would have one file with vertex information and some .mtl files (one .mtl file with a bunch of material descriptions would also be fine), and I would just choose a material when loading the model. From what I've searched, there's no support for anything like this using OBJ at least. Is there any way to load a model this way with Assimp? My best option for now seems to be loading the OBJ file into a buffer in memory, replacing the material name and passing the buffer to `ReadFileFromMemory`.

**Comment by tellypresence** [comment]
What rendering implementation are you using (OpenGL etc)?  For example in OpenGL, you'd parse the `.mtl` file for texture paths, and would need to load those separately, bind to texture objects etc as usual -- so you could override texture paths there (and leave the `.obj`/`.mtl` files alone).

Would expect there'd be similar seams in other rendering flows (WebGL, vulkan etc) where you'd be able to replace the requested textures, and could bubble all the way up to the UI so the user could select from available options (if that was in scope for your project and under your control)

**Comment by KleberPF** [comment]
I am using OpenGL.

> assimp would parse the .mtl file for texture paths, and the paths would be in the aiScene object

So instead of doing `scene->mMaterials[mesh->mMaterialIndex]` to get the material I loop through all materials in `scene->mMaterials` and load the textures from all materials in the scene?

**Comment by KleberPF** [comment]
I am using OpenGL.

> assimp would parse the .mtl file for texture paths, and the paths would be in the aiScene object

So instead of doing `scene->mMaterials[mesh->mMaterialIndex]` to get the material I loop through all materials in `scene->mMaterials` and load the textures from all materials in the scene? And then pick one of the materials when rendering a mesh? I guess this would work, but if I understood correctly, I would have to modify the .obj file for every new material added. Is there any way to process material files separately from the .obj (maybe there's a problem not knowing which faces to apply the material to, but I would be fine with all faces by default) so I don't have to change the model file constantly?

**Comment by kimkulling** [comment]
There are two supported ways to change the materials. In code you just can select a different material by changing the material index of the mesh. And you can create a new mtl-file and reference this in your obj-model. There is a statement which describes the materiallib to load: **mtllib** .

But you must guarantee that all textures are there.
