### ISSUE TITLE
Alpha masked materials?

### ISSUE THREAD

**Issue by UltraEngine** [assimp/assimp#5529]
Does assimp have a material key to indicate that alpha masking/discard should be used, rather than blending? glTF materials do have the AI_MATKEY_GLTF_ALPHAMODE key, which is set to "MASK" when alpha discard is to be used.

Is there another key that is more general-purpose, for use with FBX or other files?

**Comment by kimkulling** [comment]
You can try **aiTextureType_OPACITY** .
