### ISSUE TITLE
Visual Studio 2013 Win64 Static Library Won't Link

### ISSUE THREAD

**Issue by takfuruya** [assimp/assimp#553]
1) Download master branch
2) Open CMake GUI, configure with BUILD_SHARED_LIBS unchecked
3) Open and build project with Visual Studio 2013 Community (produces assimp-vc120-mtd.lib)
4) Open my project and link to it (set VC++ Directories>Library Directories to above library location, set Linker>Input>Additional Dependencies to the above library file, set VC++ Directories>Include Directories to assimp header file path, and add #include<assimp/Importer> etc)

This produces several "error LNK2001 unresolved external symbol ..."
This was done in Windows 7.

Using the dynamic library instead (i.e. leaving BUILD_SHARED_LIBS checked in step 2) works.

**Comment by rob100** [comment]
Unlike the dynamic library, the static library does not contain the additional dependencies. Please post the complete error message with the name of the missing symbols.

**Comment by kimkulling** [comment]
Tried x64 platform with static lib generation and both works.

**Comment by kimkulling** [comment]
Please reopen when still there.
