### ISSUE TITLE
Bug: FBX number of bones quadrupled

### ISSUE THREAD

**Issue by UltraEngine** [assimp/assimp#5534]
It appears that the FBX loader quadruples the number of bones in the model. This will have a strong negative impact on rendering performance.

![image png 0376435ce64edae91cbf6d82dc9ca898](https://github.com/FlaxEngine/FlaxEngine/assets/64279130/120766ca-2292-45cc-bfc2-f73c9c094d1c)

For comparison, this is what our FBX converter produces:
![bones](https://github.com/FlaxEngine/FlaxEngine/assets/64279130/c1f6a8ee-274c-4e01-9435-03878afdbc07)

**Comment by tellypresence** [comment]
Please add link to model file(s) for investigation

**Comment by UltraEngine** [comment]
Apparently, there is a PRESERVE_PIVOTS_... setting to resolve this, but that introduces problems of its own.
