### ISSUE TITLE
[USD] Support load .usd/.usda/.usdc/.usdz models via "tinyusdz" project

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5547]
### Updates
[`tinyusdz`](https://github.com/syoyo/tinyusdz) `rendermesh-refactor` branch was merged into main (`dev`) branch

### Overview
Evaluate [`tinyusdz`](https://github.com/syoyo/tinyusdz) project for feasibility

Use PR #5628 for testing

Several features are working reasonably well at least on some test models
- [x] vertices
- [x] faces
- [x] normals 
- [x] UVs
- [x] material colors
- [x] material textures
- [x] embedded textures

Partially working
- [x] blend shapes (morph meshes) detection: able to extract blendshapes in some rudimentary models

What's not working yet
- [ ] rig/bones support
- [ ] skeletal/skinned animations
- [ ] blend shape animations
- [ ] node-only animations (for testing will need USD format model similar to node-only [MotionCaptureROM.ase](https://github.com/assimp/assimp/blob/master/test/models/ASE/MotionCaptureROM.ase))
- [ ] reliable blend shape detection aside from a few rudimentary models

Other problems
- [ ] "Composition" (layered/hierarchical models) not supported yet (this means many USD models encountered "in the wild" will fail to load)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
### Models which load and render with problems

#### Apple
_Note: as of mid-2025, the [Apple AR page](https://developer.apple.com/augmented-reality/quick-look) has had many models added and removed_

<table>
<tr><th>Model</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/drummertoy/toy_drummer.usdz"><tt>toy_drummer.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/a6ed2ecd-7b0a-4d76-a1b9-307bc37720cf" alt="apple_toy_drummer" width=90></td><td>Mostly correct but incorrect UVs on drum, drumsticks and winding key</td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/stratocaster/fender_stratocaster.usdz"><tt>fender_stratocaster.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/980e5b64-edb4-427a-ac79-b0441bf7c36b" width=90><img src="https://github.com/syoyo/tinyusdz/assets/26958898/587b23f9-9cff-4c40-adc6-968c3c8a12d4" width=90><img src="https://github.com/syoyo/tinyusdz/assets/26958898/bdb00404-7f63-4eaf-8790-90e0231e9329" width=90></td><td>UVs incorrect (may be a problem in the model itself)</td></tr>
</table>

**Comment by tellypresence** [comment]
### Models which load and render well

#### Apple
_Note: as of mid-2025, the [Apple AR page](https://developer.apple.com/augmented-reality/quick-look) has had many models added and removed, most of the links below no longer work_

13 of the 15 demo models load and render OK

<table>
<tr><th>Model</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/biplane/toy_biplane_realistic.usdz"><tt>toy_biplane_realistic.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/0f8d1d70-6c7b-4a95-883a-7c6547f08734" width=180></td><td>(Only started working in recent commit)</td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/vintagerobot2k/robot.usdz"><tt>robot.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/fd32cf3a-4ec4-4107-acc0-b79ff54a7d5f" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/toycar/toy_car.usdz"><tt>toy_car.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/ed1edf2d-3053-41b8-96a9-b7df77f63153" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/teapot/teapot.usdz"><tt>teapot.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/297da35e-d888-45fe-b372-70269285100b" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/pancakes/pancakes_photogrammetry.usdz"><tt>pancakes_photogrammetry.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/24a57d98-b8d7-4038-8d5a-1baf73e5a25f" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/tulip/flower_tulip.usdz"><tt>flower_tulip.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/dd834b7b-6cf7-4664-8a53-083ea5c89139" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/gramophone/gramophone.usdz"><tt>gramophone.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/57198887-c598-47d4-8265-8066e53b9e4f" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/nike-air-force/sneaker_airforce.usdz"><tt>sneaker_airforce.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/92778000-dfc6-45ea-9287-69050e0758ed" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/nike-pegasus/sneaker_pegasustrail.usdz"><tt>sneaker_pegasustrail.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/5433983c-f3bc-4063-9310-a69cb5be245f" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/retrotv/tv_retro.usdz"><tt>tv_retro.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/bfa8718f-216f-4ec7-90cd-bcc3631bae5a" width=90><img src="https://github.com/syoyo/tinyusdz/assets/26958898/82e9ff3c-c494-4108-a3d0-832d45243f7a" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/redchair/chair_swan.usdz"><tt>chair_swan.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/148d7b83-0ba9-45ea-a99c-9f954adce830" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/wateringcan/wateringcan.usdz"><tt>wateringcan.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/57a9e197-6810-461f-85cb-447e355a2195" width=90></td><td></td></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/cupandsaucer/cup_saucer_set.usdz"><tt>cup_saucer_set.usdz</tt></a><br>(broken link)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/69c42ba8-1107-4fa1-a02e-b40beb8f12c3" width=90></td><td></td></tr>
</table>

#### Polyhaven

Test models with `.exr` textures
<table>
<tr><th>Model</th><th>Screenshot(s)</th><th>Notes</th></tr>
<tr><td><a href="https://github.com/minami110/usd-polyhaven/blob/main/horse_statue_01/horse_statue_01.geo.usdc"><tt>horse_statue_01.geo.usdc</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/2cbd7c8d-5d7f-4508-be31-4d7474f3070d" width=90 /></td><td></td></tr>
<tr><td><a href="https://github.com/minami110/usd-polyhaven/blob/main/carved_wooden_elephant/carved_wooden_elephant.geo.usdc"><tt>carved_wooden_elephant.geo.usdc</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/9b356715-506f-47fd-a7f5-f899926dd339" width=90 /></td><td></td></tr>
<tr><td><a href="https://github.com/minami110/usd-polyhaven/blob/main/sofa_03/sofa_03.geo.usdc"><tt>sofa_03.geo.usdc</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/d8d041b9-fec9-424b-9260-f7fb8ffe2e87" width=180 /></td><td></td></tr>
</table>

#### Sketchfab

<table>
<tr><th>Model</th><th>Screenshot(s)</th><th>Notes</th></tr>
<tr><td><a href="https://sketchfab.com/3d-models/creature-monster-3d-by-oscar-creativo-03bff460ebdc4103b42a14d56131db78"><tt>CREATURE MONSTER 3D</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/9cd265af-8b87-4c03-a98a-912d5c1d1e3d" width=90 /></td><td></td></tr>
<tr><td><a href="https://sketchfab.com/3d-models/furriers-guild-chest-in-myslenice-097a56d1796b40dca05f4c8f14066635"><tt>Furriers' guild chest in Myślenice</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/a99cd5d3-97b1-4412-804c-a57de1bb756f" width=180 /></td><td></td></tr>
<tr><td><a href="https://sketchfab.com/3d-models/netsuke-shoki-capturing-an-oni-350423d0c7d045a7bd89b1814772399d"><tt>Netsuke - Shoki capturing an oni</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/473e1863-7f39-47f9-8c66-e70139c92487" width=90 />
</td><td></td></tr>
<tr><td><a href="https://sketchfab.com/3d-models/compsognathus-762fd4e099b640aeb6e3341aec042cea"><tt>compsognathus.usdz</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/5432c849-cbc2-4c8e-94c6-c5d9bcd54186" width=90 /></td><td></td></tr>
</table>

#### usd-wg full assets

<table>
<tr><th>Model</th><th>Screenshot(s)</th><th>Notes</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/UsdCookie/UsdCookie.usdz"><tt>UsdCookie.usdz</tt></a></td><td><img src="https://github.com/user-attachments/assets/9e967e68-e013-4c0a-9c9c-d761b3f17117" width=90 /></td><td></td></tr>
</table>

#### usd-wg test assets

<table>
<tr><th>Model</th><th>Screenshot(s)</th><th>Notes</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/BrainStem/BrainStem.usdz"><tt>BrainStem.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/e2e859ba-9b49-4743-b43e-00c0aa5b3575" width=180 /></td><td></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/CesiumMan/CesiumMan.usdz"><tt>CesiumMan.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/10dfd0e5-aae9-414a-9183-a071ac71144a" width=90 /></td><td></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/DamagedHelmet/DamagedHelmet.usdz"><tt>DamagedHelmet.usdz</tt></a></td><td><img src="https://github.com/assimp/assimp/assets/26958898/12d033bc-9a48-4b74-87a4-1dcec9393bf3" width=180 /></td><td></td></tr>
</table>

**Comment by AMZN-Gene** [comment]
> ## Bones/skeletons/skinning
> I'm struggling to understand how to convert the data from `tinyusdz` render scene into skeletons. It appears that vertex weights are a per-mesh, rather than per-bone, attribute, but my understanding is that each bone should provide its own set of vertex weights. Anyway I can't seem to discover where those values would be provided.

Curious, is there more info, or a GHI, for the issues ran into around animation? I'm interesting in getting animation working and would like to know what paths to avoid, and maybe were to look next.
