### ISSUE TITLE
[New Feature Request]NIF Format/file suppport

### ISSUE THREAD

**Issue by qige023** [assimp/assimp#555]
NIF format is using by  NetImmerse/GameBryo engine.  Many famous game like Oblivion, Skyrim, Fallout 3 has used it as mesh and animation storage.
see http://niftools.sourceforge.net/wiki/NifTools
Many artists has build wonderful model using NIF format, see http://skyrim.nexusmods.com/..
So there are many NIF's model I want to import into assimp . But Sadly, it doesn't support yet.

The NifTools project has provide source code of NIFLIB in https://github.com/amorilia/niflib  which can read NIF format's structure.

Can this has a hope to accomplish, or if I have time, I would like to have a try.

**Comment by uq1** [comment]
I would love to see this too. Even if just for static models.

**Comment by kimkulling** [comment]
Another request here: https://github.com/assimp/assimp/issues/3474 We will use the newer one to track the request.

**Comment by cj2000** [comment]
Great idea there is even some existing API for C++, so posibly it can be integrated into assimp.

**Comment by tellypresence** [comment]
> see http://niftools.sourceforge.net/wiki/NifTools 

Migrated away from sourceforge ca 2017, new page: https://www.niftools.org/
