### ISSUE TITLE
Bug: OBJ - load material throw exception when material has user-defined description

### ISSUE THREAD

**Issue by plainliu** [assimp/assimp#5554]
**Describe the bug**
ReadFile() throw exption and return nullptr when load obj.

**To Reproduce**
There are lines in .mtl like:
```
Pccns 1-1
Prfl 0
...
``` 
when `ObjFileMtlImporter::load()` parse `Pccns 1-1`, first match char 'P', then match char 'c', then get next word "cns" in getFloatValue to parse

deadly error
```
Cannot parse string "cns" as a real number: does not start with digit or decimal point followed by digit.
Cannot parse string "fl" as a real number: does not start with digit or decimal point followed by digit.
```
**Expected behavior**
The mtl file is created by a modified js OBJExporter, skip the line when parse failed

**Comment by GitHubDragonFly** [comment]
@plainliu those MTL lines almost look like coming from the custom OBJ Exporter that I have in my repository.

If you are interested then take a look at customized Assimp I have made in my [updates](https://github.com/GitHubDragonFly/assimp/tree/updates) branch, especially the [ObjFileMtlImporter.cpp](https://github.com/GitHubDragonFly/assimp/blob/updates/code/AssetLib/Obj/ObjFileMtlImporter.cpp) file but don't limit your research to that file only.

My [ASSIMP Viewer](https://githubdragonfly.github.io/viewers/templates/ASSIMP%20Viewer.html) should be able to load your MTL + OBJ + Textures files.

**Comment by kimkulling** [comment]
Are these any kind of standard material definitions?

**Comment by plainliu** [comment]
@GitHubDragonFly I tried to import my obj use [updates](https://github.com/GitHubDragonFly/assimp/tree/updates) branch, it still load failed. the branch parsed P-c-c not only P-c, so "cns" error become "ns" error.
[OBJ Viewer](https://githubdragonfly.github.io/viewers/templates/OBJ%20Viewer.html)  can load my obj, I dont know why.

and I have some other questions
- if updates branch can use, will the changes merge to this repo in the future? we may use new assimp version
- if the mtl description can not parse, should skip it instead of importer returning nullptr ? there will more description in the future,  mtl loading failure may not Influence mesh loading
- [updates](https://github.com/GitHubDragonFly/assimp/tree/updates) branch compile failed C4061 ( using msvc )

**Comment by plainliu** [comment]
@kimkulling  where can I get those special extensions? if not use them, importer return nullptr still is a question, I have fixed it on my local repo but not perfect way, and report the question here expecting fix it in this repo~~

**Comment by plainliu** [comment]
@GitHubDragonFly Thanks, changes in function `ObjFileMtlImporter::load()` is what I what.  also need skip `\t`.

I tried compile `updates` branch, function `getNumComponentsInDataDefinition` has errors
-  compiled failed :  `SkipSpaces`& `SkipToken` params error
- function error: `SkipSpaces` use `mEnd`, and `tmp` skip space failed,  `IsNumeric` only checked first space char, so isNum is false

**Comment by GitHubDragonFly** [comment]
@plainliu maybe try compiling again.

I just updated `ParsingUtils.h` file and, even though it is a mix of old and new code, the `updates` branch did compile for me by using emscripten and mingw.

Would you also be able to actually test loading your OBJ+MTL+Texture files in my current [ASSIMP Viewer](https://githubdragonfly.github.io/viewers/templates/ASSIMP%20Viewer.html) just so I know whether it is working properly with your model.

**Comment by plainliu** [comment]
@GitHubDragonFly The `updates` branch compile & load my obj successfully now. [ASSIMP Viewer](https://githubdragonfly.github.io/viewers/templates/ASSIMP%20Viewer.html) loaded successfully too.

**Comment by GitHubDragonFly** [comment]
@plainliu thank you for testing.

Here is some more info about the `updates` branch just so you are aware:

- There is another topic in this forum that is related to OBJ + MTL showcasing some other features, which you can see [here](https://github.com/assimp/assimp/issues/5254)
- For a test, here is what else you could try:
  - create a copy of your OBJ model
  - modify your MTL file to match entries mentioned in this [document](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/OBJ_MTL_PBR.md)
  - load it in my ASSIMP VIewer - you should be able to see effects such as sheen / clearcoat / iridescence / transmission / thickness / attenuation if they are present in your model
  - you might eventually try modifying all the OBJ library files to actually process your original MTL entries

Here is [another topic](https://github.com/assimp/assimp/issues/5177) in this forum that has some other info.
