### ISSUE TITLE
IOS开发 ，导出fbx格式

### ISSUE THREAD

**Issue by liumanfang** [assimp/assimp#5567]
我用assimp这个库成功实现了导出fbx格式的文件，并且在Blender上能够正确导入这个fbx查看模型，但是在别的3d软件上导入失败
请问是什么原因导致的，能如何解决

**Comment by turol** [comment]
Please use english. Google translated your message:

 > I used the assimp library to successfully export the fbx file, and I was able to import the fbx view model correctly on Blender, but the import failed on other 3d software What is the cause and how can I solve it?

What "other 3D software"? If it loads correctly in Blender it's probably their bug. If it's specific to some model please share it.

**Comment by liumanfang** [comment]
我实现的FBX文件带有动画节点，但是在UE中导入这个FBX文件只有模型，没有动画，在3ds Max上导入这个fbx文件就是动画对不上，只有在Blender上是完全符合的，这个fbx文件通过Blender再导出后就能正常在UE，3ds Max等这些软件正确导入

**Comment by liumanfang** [comment]
添加动画的代码：
// 创建 Assimp 的导入器和导出器
       Assimp::Importer importer;
       Assimp::Exporter exporter;
    //获取iOS应用程序中名为"Untitled10.fbx"的文件的完整路径
    NSString *sceneFilePath = [[NSBundle mainBundle] pathForResource:@"model" ofType:@"fbx"];
    //使用导入器 importer 读取 FBX 文件，并进行三角化和 UV 翻转处理，结果保存在 scene 中。
    const aiScene *scene = importer.ReadFile([sceneFilePath UTF8String], aiProcess_Triangulate | aiProcess_FlipUVs);
       if (!scene) {
           NSLog(@"Failed to load OBJ file.");
           return;
       }
    //创建一个场景的副本 exportedScene，以便于添加动画。
    aiScene* exportedScene = new aiScene(*scene); // 创建副本
       if (!exportedScene) {
           NSLog(@"Failed to load exported FBX file.");
           return;
       }
   
       // 查找名为 "cube12" 的节点
       aiNode* cubeNode = exportedScene->mRootNode->FindNode("cube12");
       if (!cubeNode) {
           NSLog(@"Cube node not found in FBX scene.");
           return;
       }

    // 创建一个新的动画通道 animation，并设置其名称为 "CubeAnimation"。
    aiAnimation* animation = new aiAnimation();
    animation->mName = aiString("CubeAnimation");

    // 创建动画通道的轨迹 nodeAnim，并设置其作用的节点名称为 "cube12"。
    aiNodeAnim* nodeAnim = new aiNodeAnim();
    nodeAnim->mNodeName = aiString("cube12"); // 设置动画作用的节点名称
    nodeAnim->mNumPositionKeys = (unsigned int)_cameraTransforms.count; // 假设有3个关键帧
    nodeAnim->mNumRotationKeys = (unsigned int)_cameraTransforms.count; // 假设有3个关键帧

    // 设置动画通道的位置关键帧和旋转关键帧的数量，并分配内存
    nodeAnim->mPositionKeys = new aiVectorKey[self.cameraTransforms.count];
    nodeAnim->mRotationKeys = new aiQuatKey[self.cameraTransforms.count];
   
    for (int i = 0; i < self.cameraTransforms.count; ++i) {
        NSDictionary *transformData = self.cameraTransforms[i];
        aiVector3D positionKey;
        positionKey.x = [transformData[@"x"] floatValue]*100;
        positionKey.y = [transformData[@"y"] floatValue]*100;
        positionKey.z = [transformData[@"z"] floatValue]*100; // 从字典中读取 z 值
        //NSLog(@"positionKey.z:%f",positionKey.z);
       
        aiQuaternion rotationKey;
        rotationKey.x = [transformData[@"rotation.X"] floatValue];;
        rotationKey.y = [transformData[@"rotation.Y"] floatValue];;
        rotationKey.z = [transformData[@"rotation.Z"] floatValue];;
        rotationKey.w = [transformData[@"rotation.W"] floatValue];;
     
        // 添加位置和旋转关键帧
        float time = i / 24.0; // 计算关键帧时间
        nodeAnim->mPositionKeys[i].mTime = time; // 关键帧时间
        nodeAnim->mPositionKeys[i].mValue = positionKey; // 位置关键帧值
        nodeAnim->mRotationKeys[i].mTime = time; // 关键帧时间
        nodeAnim->mRotationKeys[i].mValue = rotationKey; // 旋转关键帧值
    }
    // 将动画通道附加到场景中的根节点
    animation->mNumChannels = 1;
    animation->mChannels = new aiNodeAnim*[1];
    animation->mChannels[0] = nodeAnim;
    // 将动画添加到场景中
    exportedScene->mNumAnimations = 1;
    exportedScene->mAnimations = new aiAnimation*[1];
    exportedScene->mAnimations[0] = animation;
// 导出到FBX文件
    aiReturn result = exporter.Export(exportedScene, "fbx", [filePath UTF8String]);
    
  在使用https://www.autodesk.com/products/fbx/fbx-review查看fbx时
Fbx工作也缺失了动画，是我添加动画节点的代码部分哪里出错了吗？

**Comment by liumanfang** [comment]
> 请使用英语。谷歌翻译了你的信息：> 请使用英语。谷歌翻译了你的信息：>> > 我使用assimp库成功导出fbx文件，我能够在Blender上正确导入fbx视图模型，但其他3D软件上导入失败，原因是，我该如何解决？>> 什么“其他3D软件”？在Blender中正确加载，那是他们的错误。如果它特定于某个模型，请分享它。>> > 我使用assimp库成功导出fbx文件，我能够在Blender上正确导入fbx视图模型，但其他3D软件上导入失败，原因是，我该如何解决？>> 什么“其他3D软件”？在Blender中正确加载，那是他们的错误。如果它特定于某个模型，请分享它。
能帮我分析一下吗

**Comment by tellypresence** [comment]
@liumanfang Please use English in future
