### ISSUE TITLE
ObjFileMtlImporter.cpp breaking on displacement map

### ISSUE THREAD

**Issue by k0rmarun** [assimp/assimp#557]
Importing am Obj + Material with displacement map returns error "The string 'isp' cannot be converted into a value".

Reason: ObjFileMtlImporter.cpp:165 filter for 'd' as alpha transparence
ToFix: Check for strings defined in ObjFileMtlImporter.cpp instead of single characters

**Comment by LegalizeAdulthood** [comment]
Wavefront obj files don't define displacement maps, this appears to be some proprietary extension.  According to [the specification](http://www.cs.utah.edu/~boulos/cs3505/obj_spec.pdf), the only commands beginning with `d` are:

`deg` - degree of free-form curve/surface attributes
`d_interp` - sets dissolve interpolation on or off

**Comment by LegalizeAdulthood** [comment]
Best reference I can find for `.mtl` syntax: http://people.cs.clemson.edu/~dhouse/courses/405/docs/brief-mtl-file-format.html

This doesn't describe a bunch of the commands that assimp is parsing, all of which appear to be extensions.

Wavefront OBJ is an old enough format that things like displacement maps are additions that different tools have hacked onto the format without necessarily agreeing on how these additions should be interpreted.

**Comment by kimkulling** [comment]
OPs, thanks for this issue report! I will take a look!
