### ISSUE TITLE
Bug:The crash occurred when the ifc file was imported

### ISSUE THREAD

**Issue by wangyaozu** [assimp/assimp#5588]
[site.ifc.zip](https://github.com/assimp/assimp/files/15399577/site.ifc.zip)

![image](https://github.com/assimp/assimp/assets/24237635/5dbfec13-3e2f-4a95-a77c-a87ad03a5d4a)
![image](https://github.com/assimp/assimp/assets/24237635/728b4cd5-ee4b-4c6d-aacc-0ec65ae1de65)

**Comment by kimkulling** [comment]
This file is an IFC4 file. Currently the Asset-Importer-Lib only supports the schema 2x3. I will make the error message more verbose to make the issue visible.
