### ISSUE TITLE
Bug: Importing Collada file fails with "Error importing model: Cannot parse string"

### ISSUE THREAD

**Issue by shambhupatil** [assimp/assimp#5591]
**Describe the bug**
Trying to load a .dae file fails with `Error importing model: Cannot parse string "  0.0 0.0 0.0 1.0  " as a real number: does not start with digit or decimal point followed by digit.`

**To Reproduce**
1. Load [library_animation_clips.dae](https://drive.google.com/file/d/1_lFaOKivbPnzPX7ydp8Uz56bZIRu_z49/view?usp=sharing) file.
2. See the error.

**Expected behavior**
Loads file

**Platform**
 - OS: Windows 11

**Additional context**
Maybe because fast_atof.h cannot convert string to float if there's a space in the beginning.

**Comment by kimkulling** [comment]
Fixed, thanks for the report.
