### ISSUE TITLE
Bug: There may be an out-of-bound access of the variable m_DataIt (static analysis report)

### ISSUE THREAD

**Issue by megumin9** [assimp/assimp#5602]
**Describe the bug**
  In the file code/AssetLib/Obj/ObjFileParser.cpp, line 792, if the while loop is ended because m_Datait is equal to m_DataItEnd, then in line 796, the access of the variable m_Datait is out-of-bound. Is it need to add a check here？

 ```
while (m_DataIt != m_DataItEnd && !IsSpaceOrNewLine(*m_DataIt)) {
        ++m_DataIt;
    }
    std::string strObjectName(pStart, &(*m_DataIt));
```

**Comment by turol** [comment]
No, the string constructor takes a pair of iterators (pointers in this case). The second is one past the end and is not dereferenced. It's okay but some debug versions of STL complain about it (MSVC did at some point).

In this case at least it could probably be using a pair of iterators without the complicated dereference and addressof operators.
