### ISSUE TITLE
Bug: There may be a dead loop in the file code/PostProcessing/TextureTransform.cpp( static analysis report).

### ISSUE THREAD

**Issue by megumin9** [assimp/assimp#5603]
**Describe the bug**
In file code/PostProcessing/TextureTransform.cpp, line 395. There is a while loop, the condition of the loop is t is not equal to (*it).lockedPos. But, the result of the condition will not be changed regardless of how the loop proceeds. Is the condition is t != (*it2).lockedPos in fact?

   `                while (t != (*it).lockedPos)
                      ++it2;`

**Comment by kimkulling** [comment]
Yes, I do agree. The variable t does not get increased at all. So the result will be 0 in any case.
