### ISSUE TITLE
Bug: gcc 14.1.1 wont build types.h 

### ISSUE THREAD

**Issue by CitroenGames** [assimp/assimp#5622]
when using gcc 14.1.1 it wont build correctly because it thinks that it might be not initialized

`assimp-5.4.1/include/assimp/types.h:347:54: error: ‘<anonymous>’ may be used uninitialized [-Werror=maybe-uninitialized]
  347 |         return (length == other.length && 0 == memcmp(data, other.data, length));
`

OS Manjaro 24.0.2
GCC 14.1.1

**Comment by kimkulling** [comment]
Any idea how to fix that?

**Comment by CitroenGames** [comment]
Welp I'm new to GCC so I have no idea 😂

**Comment by kimkulling** [comment]
Will try something.
