### ISSUE TITLE
Bug: Collada uv channel numbers are ignored.

### ISSUE THREAD

**Issue by StepanHrbek** [assimp/assimp#5631]
**Describe the bug**
Collada file can specify uv channel number but Assimp ignores it.
For example <bind_vertex_input semantic="CHANNEL1" input_semantic="TEXCOORD" input_set="0"/> describes channel with string "CHANNEL1" and number 0, where the string is used only when parsing file, and the number should be propagated into aiScene unchanged. Assimp reads the number, but then forgets it.

**To Reproduce**
1. Import any .dae with at least one textured mesh and non trivial value in input_set=, it could look like <bind_vertex_input semantic="CHANNEL1" input_semantic="TEXCOORD" input_set="5"/> 
2. After import, query uv channel number with aimaterial->Get(_AI_MATKEY_UVWSRC_BASE, ...) and see that it's not 5.

**Expected behavior**
Assimp should not ignore the number in input_set=.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5630

**Comment by tellypresence** [comment]
Please attach a demo .dae model file which had been affected by this problem, to make it easier to check if this fix gets broken in future

**Comment by StepanHrbek** [comment]
https://github.com/StepanHrbek/LightsprintSDK/blob/main/data/scenes/koupelna/koupelna4.dae contains material with set="0" and set="1" and mesh with input_set="0" input_set="1".
It means material wants uv channels 0,  1 and mesh contains uv channel 0, 1.

Before #5631, Assimp imported mesh with 0, 1 but material with 1, 2, so texturing is broken.
#5631 fix makes Assimp import both with 0, 1.
