### ISSUE TITLE
Add editor config support

### ISSUE THREAD

**Issue by LegalizeAdulthood** [assimp/assimp#564]
As per the discussion of pull request https://github.com/assimp/assimp/pull/562, add a `.editorconfig` file to describe whitespace conventions in the codebase.  The currently proposed contents are:

````
[*.{h,hpp,c,cpp}{,.in}]
# Unix-style newlines with a newline ending every file
end_of_line = lf
insert_final_newline = true

# 4 space indentation
indent_style = space
indent_size = 4

trim_trailing_whitespace = true
````

**Comment by LegalizeAdulthood** [comment]
We need to add the conventions for `CMakeLists.txt` as well.

**Comment by LegalizeAdulthood** [comment]
Add conventions for `*.py` files in regression test suite.

**Comment by abma** [comment]
its possible to enforce line-endings in git:
