### ISSUE TITLE
Bug: FBX - Skinned Mesh Imports With Wrong Transforms

### ISSUE THREAD

**Issue by lxw404** [assimp/assimp#5642]
## Describe the bug
Currently FBX models with skinned meshes will be imported with invalid transforms due to this change: https://github.com/assimp/assimp/pull/5349 which did not revert this change: https://github.com/assimp/assimp/commit/8a1dc87b4ca.

This results in the pose calculating against invalid absolute transforms.

## To Reproduce
Import a skinned FBX mesh away from the origin of the scene such as this test one:
[zan.fbx.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13877779/zan.fbx.zip)

## Expected behavior
The skinned mesh should import without pose distortion.

## Screenshots

**Blender With Armature**
 Left            |  Front
:-------------------------:|:-------------------------:
![blender_InwUAfCIYr](https://github.com/assimp/assimp/assets/52231149/3471b761-d803-441a-ab36-387567211ac2) | ![blender_2R9L6Ra3pD](https://github.com/assimp/assimp/assets/52231149/f6bfe9ef-4a30-4106-8cbe-4edc8ec42e70)

**Current behavior**
 Left            |  Front
:-------------------------:|:-------------------------:
![Resonite_z5ogi1cqZN](https://github.com/assimp/assimp/assets/52231149/eed3e714-b793-4787-89b8-4fde8f0a4c82)  |  ![Resonite_0x4TgoYrX2](https://github.com/assimp/assimp/assets/52231149/fb0271dc-963b-4d5c-b620-406e10f1e71e)

**Fixed behavior:**
Left            |  Front
:-------------------------:|:-------------------------:
![Resonite_Ch2lVFIbqZ](https://github.com/assimp/assimp/assets/52231149/248da659-edf2-47c3-989a-330dad4ea7b0) | ![Resonite_2MUYL1UySv](https://github.com/assimp/assimp/assets/52231149/aa51bf73-0b59-424d-b687-979c23094316)

## Platform (please complete the following information):
 - Windows 10

**Comment by lxw404** [comment]
I believe https://github.com/assimp/assimp/issues/5449 is related to this and should be fixed by: https://github.com/assimp/assimp/pull/5643.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5643

**Comment by lxw404** [comment]
@kimkulling This is still an issue in current master due to: https://github.com/assimp/assimp/pull/5643 not being merged.
