### ISSUE TITLE
Dangerus AI_DEG_TO_RAD/AI_RAD_TO_DEG definition

### ISSUE THREAD

**Issue by wise86-android** [assimp/assimp#568]
the macro are define as:

```
#define macro(x) (x*delta)
```

so if they are apply to an expression like a+b they multiply only the last value..
this happen in the ColladaLodaer file with the expression:

```
AI_DEG_TO_RAD (std::acos(std::pow(0.1f,1.f/srcLight->mFalloffExponent))+srcLight->mFalloffAngle);
```

I don't know what the formua does maybe is correct as it is since mFalloffAngle is in degree (and is the only value that is converted in radians) and the acos results in radians, and you want the radians as results.. 

any way i think that is better define the macro as 

```
#define macro(x) ((x)*delta)
```

Thanks

**Comment by LegalizeAdulthood** [comment]
Instead of using a macro, I'd recommend using an inline function.

**Comment by kimkulling** [comment]
This one is for the c-stuff, buf I do agree, an inline fuction would do this better even for pure c.

**Comment by kimkulling** [comment]
Brackets are inside the macros.
