### ISSUE TITLE
Collada files lack reasonable texture coordinates

### ISSUE THREAD

**Issue by mcmonkey4eva** [assimp/assimp#569]
So I have this character in Blender
![CharHD](https://i.imgur.com/6Eqclzw.png)

and when I load him into the scene

![Charuwotm8](https://i.imgur.com/gqM0nmx.png)

It looks like the texture coordinates on the jacket are way off... all I do when loading them is reading them off the input... for each vertex, `Vector3D texCoord = mesh.TextureCoordinateChannels[0][i];`
From there, the texture coordinates get added to an array, which then gets upload to OpenGL.

Am I doing something wrong here? Perhaps `[0]` isn't the best initial indexer? (Though I do believe all texture coordinate sets line up exactly the same) (Also 0 should be the diffuse anyway)

The file definitely /has/ texture coordinates, that /are/ loaded by assimp: `mesh.HasTextureCoords(0);` returns true.

EDIT: It loads fine in Open3Mod... so what am I doing wrong?

**Comment by mcmonkey4eva** [comment]
Fixed my own issue by searching the Open3Mod source code for forever... the Y coordinate of the texcoord is flipped from what it should be, Open3Mod does `1 - uvw.Y` and similar when dealing with the texture coordinates. Matching that in my code fixed it :D

**Comment by acgessler** [comment]
UV Y is flipped between OpenGl and Direct3D. Assimp adopts one convention (see docs) and flips it depending on flags. Further, plenty of image loaders mess up the Y axis as well (observed for TGA and BMP).

So, it's a mess. Glad you solved it.
