### ISSUE TITLE
Bug: 3DSExporter cannot be built without 3DSImporter

### ISSUE THREAD

**Issue by Fiskmans** [assimp/assimp#5706]
**Describe the bug**
[code/AssetLib/3DS/3DSExporter.cpp](../tree/master/code/AssetLib/3DS/3DSExporter.cpp#L158) uses the class `DeadlyExportError` from [include/assimp/Exceptional.h](../tree/master/include/assimp/Exceptional.h#L107-L113)
which is included through the chain: 
* [code/AssetLib/3DS/3DSExporter.cpp](../tree/master/code/AssetLib/3DS/3DSExporter.cpp#L48)
  * [code/AssetLib/3DS/3DSLoader.h](../tree/master/code/AssetLib/3DS/3DSLoader.h#L51) (this resolves to an empty file when `ASSIMP_BUILD_NO_3DS_IMPORTER` is defined)
    * [include/assimp/BaseImporter.h](../tree/master/include/assimp/BaseImporter.h#L52)

**To Reproduce**
1. cmake -DASSIMP_BUILD_3DS_IMPORTER=false
2. build
3. Observe that 3DSExporter.cpp fails to compile

**Expected behavior**

The project should do one of the following
* Compile `3DS Exporter` without `3DS Importer`
* or In some way notify the user if `3DS Exporter` is enabled and `3DS Importer` is not

**Platform (please complete the following information):**
 - OS: Win10 && gcp's default compute engine os (debian?)
 - Version 48c3a0e

**Comment by kimkulling** [comment]
Fixed.
