### ISSUE TITLE
The repo has a tag named "master" that collides with the branch named "master"

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#5708]
**Describe the technical debt**
The git repo contains a tag `master` in the git repo, and also a branch `master`.

https://github.com/assimp/assimp/tree/master
https://github.com/assimp/assimp/releases/tag/master

While this is permitted by git, the name collision causes difficulty when using some git tools.
Most git scripting assumes that branches and tags never have the same names.

The tag itself appears to be an orphan.

**Better solution**
A branch should be created there and the `master` tag deleted.

I think it was created by mistake, possibly by a merge that was intended to merge into the `master` _branch_ but ended up creating a `master` _tag_

**Comment by kimkulling** [comment]
Ok, I will try to fix this.

**Comment by kimkulling** [comment]
Shall be fixed.
