### ISSUE TITLE
ASSBIN comments seem incorrect

### ISSUE THREAD

**Issue by g-pechorin** [assimp/assimp#576]
Documentation of `.assbin` seems to be out of date / incorrect / misinformed

I would like to (politely) submit a patch to correct this

[Pull Request](https://github.com/assimp/assimp/pull/575)
[Issue](https://github.com/assimp/assimp/issues/576)
[Travis](https://travis-ci.org/assimp/assimp/builds/64743988)

* corrected note saying that the header was 500 bytes long (512 bytes are written and the number 512 is given elsewhere)
* altered confusing language about how long the chunks are ("length of chunk" implies the number includes the chunk-header. chunk-data-length less so, and reflects the fact that the number written doesn't include the chunk-header)
* removed mistake about how texture coordinates are encoded (the last release, and the current master, both [write texture coordinates as 3 float components](https://github.com/assimp/assimp/blob/master/tools/assimp_cmd/WriteDumb.cpp#L409) regardless of what they actually are)

**Comment by acgessler** [comment]
Thanks for noticing and fixing!

Assbin in general is quite old and nowhere really used (appearently until now) except for assimp's regression test suite.
