### ISSUE TITLE
not-git (and "nested" builds)

### ISSUE THREAD

**Issue by g-pechorin** [assimp/assimp#578]
I want to build assimp on my computer (without command-line git) and nest assimp inside of "another" CMake workspace. [This patch](https://github.com/assimp/assimp/pull/577);
* wraps the git requiring things in `if(GIT_FOUND)`
  * the docs don't say I need git to compile assimp
* changes some `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR`
  * [travis seems to like this](https://travis-ci.org/assimp/assimp/builds/64788112)
* surrounds the CRT warning macro with an `#ifndef` to prevent re-definition warnings
  * I heard you like to avoid warnings - so I reduced warnings about your warnings
* corrected misc amd64 warnings about assigning `size_t` to `uint32_t`
  * there are a lot of these - 293 left - would fixing more of them be well received?

[Pull Request](https://github.com/assimp/assimp/pull/577)
[Issue](https://github.com/assimp/assimp/issues/578)
[Travis seems to like this](https://travis-ci.org/assimp/assimp/builds/64788112)

**Comment by kimkulling** [comment]
Already merged!
