### ISSUE TITLE
SDK: Please update the SDK Binaries!!!! (Among other things...)

### ISSUE THREAD

**Issue by hl2jeep** [assimp/assimp#5795]
The SDK binaries are extremely out-of-date and completely neglected, I really benefit from the SDK for bulk model conversion via command line, but the outdated current SDK has many gripes.

The FBX exporter is completely broken, producing unreadable files in everything i tried it in.

GLB export is extremely slow on large models.

There are no build instructions for how to build the SDK or command line tool, all i've been able to do so far is compile the viewer tool, but it crashes trying to load the visual for the models.
The documentation for assimp_cmd is so egregiously out of date that most of the parameters are now down to guesswork!

I can't substitute the conversion feature of assimp with anything else, everything else either has texture issues or can't handle large files.

so i ask that at bare minimum, update the documentation and add build instructions for just assimp_cmd

**Comment by kimkulling** [comment]
I have updated the build instructions: https://github.com/assimp/assimp/pull/5796

Updating the prebuild stuff on itchi.io is on my list. Unfortunately the list gets longer and longer. This is just a side project next to family and day-time job. 

So please try to start with building the stuff by yourself. I will try to prepare the updated sdk.

**Comment by hl2jeep** [comment]
Thank you very much! This will help me with my projects

**Comment by kimkulling** [comment]
Please check: https://kimkulling.itch.io/the-asset-importer-lib
