### ISSUE TITLE
Bug: Importer does not set `pimpl->mException` when `ASSIMP_CATCH_GLOBAL_EXCEPTIONS` is defined

### ISSUE THREAD

**Issue by mischmit** [assimp/assimp#5809]
When an exception is thrown from e.g., within an IOSystem, one may want to access that from outside Assimp.

This is possible in Debug builds via `importer.GetException()`.

However, in a Release build, `ASSIMP_CATCH_GLOBAL_EXCEPTIONS` is defined and therefor, such exceptions are swallowed in https://github.com/assimp/assimp/blob/9934a8d1cc58d9c5ddc6e0f39da0f86a7091e63b/code/Common/Importer.cpp#L766-L778 .

Here, only `pimpl->mErrorString` is updated but `pimpl->mException`

**To Reproduce**

- Implement an IOSystem that throws an exception in `open`
- Use that IOSystem in an importer and call ReadFile

**Expected behavior**
- The exception should be stored in the exception pointer that is returned by `importer.GetException()`

**Platform (please complete the following information):**
any Release build

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5810
