### ISSUE TITLE
Bug: No Assimp Viewer Even when DirectX Installed

### ISSUE THREAD

**Issue by AMZN-Gene** [assimp/assimp#5820]
Assimp viewer isn't available even though DirectX is installed.
https://github.com/assimp/assimp/blob/ce0a50ec21bfa4bb2535a4fbd87b67feadc0cea0/CMakeLists.txt#L753-L758

**To Reproduce**
1. Install [WindowsSDK ](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/) which includes DirectX
2. Run `cmake CMakeLists.txt -DASSIMP_BUILD_ASSIMP_TOOLS=ON`
3. Notice there's no warning about Assimp View failing to generate
4. Open Assimp.sln
5. Look in solution explorer Notice Assimp Viewer doesn't exist

**Expected behavior**
Assimp Viewer project should exist in the solution explorer
![image](https://github.com/user-attachments/assets/aea6f7c6-59e5-484e-ac90-94e3ceef3acd)

Also, if the viewer project fails to generate, there should be a cmake warning

**Platform (please complete the following information):**
 - OS: Windows
Master branch October 09 2024
9934a8d1cc58d9c5ddc6e0f39da0f86a7091e63b

**Work Around**
Deleting the check for DirectX allows me to build assimp viewer
![image](https://github.com/user-attachments/assets/8bd6caa6-7b11-4f07-bb82-43f156d10188)

**Comment by turol** [comment]
Working as intended, you need to specifically ask for it.
```
cmake -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_ASSIMP_VIEW=ON
```

**Comment by AMZN-Gene** [comment]
> Working as intended, you need to specifically ask for it.
> 
> ```
> cmake -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_ASSIMP_VIEW=ON
> ```

This line in cmake assigns ASSIMP_BUILD_ASSIMP_VIEW to ${DirectX_FOUND}, so if ${DirectX_FOUND} is OFF, then ASSIMP_BUILD_ASSIMP_VIEW  will be marked "OFF" won't it?
https://github.com/assimp/assimp/blob/ce0a50ec21bfa4bb2535a4fbd87b67feadc0cea0/CMakeLists.txt#L755

**Comment by AMZN-Gene** [comment]
ASSIMP_BUILD_ASSIMP_VIEW also isn't included in the "All Available Options" list. If it's meant to be there, we should add it.
https://github.com/assimp/assimp/blob/ce0a50ec21bfa4bb2535a4fbd87b67feadc0cea0/CMakeLists.txt#L76-L159
