### ISSUE TITLE
Bug: compilation error.

### ISSUE THREAD

**Issue by Ornito** [assimp/assimp#5827]
Hi!
I'm trying to compile assimp on windows 10 with mingw10 32 bits but I get this compilation error.

C:\Users\Laurent et Christian\assimp-assimp-8b9ed34\code\Common\DefaultIOStream.cpp:160:24: error: aggregate 'Assimp::DefaultIOStream::FileSize() const::_stat32 fileStat' has incomplete type and cannot be defined
  160 |         struct _stat32 fileStat;
      |                        ^~~~~~~~
C:\Users\Laurent et Christian\assimp-assimp-8b9ed34\code\Common\DefaultIOStream.cpp:162:19: error: '_fstat32' was not declared in this scope; did you mean '_stat32'?
  162 |         int err = _fstat32(_fileno(mFile), &fileStat);
      |                   ^~~~~~~~
      |                   _stat32

**Comment by Ornito** [comment]
I had to replace _stat32 by _stat and _fstat32 now it compile.

**Comment by tellypresence** [comment]
Good to hear it's working for you, is it OK to close this issue?

**Comment by kimkulling** [comment]
This will fix the build issue, but open a new one. FStat needs the file handle,
