### ISSUE TITLE
Assimp x64, how can i get?

### ISSUE THREAD

**Issue by Maslik78** [assimp/assimp#583]
Hey, I enjoy your library , but I did not get to build x64 version always get the error module machine type 'x64' conflicts with target machine type 'X86' assimp. All settings in VisualStudio checked , all right , but why is not built . Excuse me , if not to write the question .

**Comment by kimkulling** [comment]
I guess x64 ( lowercase ) against X64 (uppercase ).

**Comment by anshole** [comment]
I'm having same issue as well.

**Comment by kimkulling** [comment]
Sounds bad, I will check!

**Comment by kimkulling** [comment]
Have you generated your solution with CMake? And sorry, I didn't saw that you have x86 against x64. Visual Studio needs to have x64 libs from Asset Importer Lib as well. As far as I know we don't have a pre-build package for that configuraton so you should do this on your own.

**Comment by kimkulling** [comment]
Any updates?

**Comment by sahilagnihotri** [comment]
You can generate the x86 project using Cmake. Then go in configuration manager in Visual Studio and make new configuration, in option you can copy it using x86. Change output name and intermediate paths in properties of the project. Same goes you have to change the machine target from x86 to x64. It should do the trick.

**Comment by ChristophLGDV** [comment]
I have the same problem.
I replaced all appropriate places with "$(Platform)\$(Configuration)" and tracked down any x86.

Hiwever, building the project assimp still fails to link.
Is there som typical specific I am missing?

**Comment by ChristophLGDV** [comment]
I checked the assimp.vcxproj file and found under

  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">

the 
    <Link>
      <AdditionalOptions> /machine:X86 %(AdditionalOptions)</AdditionalOptions>

tag.

Might that be the culprit?
Deleting the tags makes other errors

**Comment by ChristophLGDV** [comment]
No this actually solved it! 

this guy had the same problem:
http://stackoverflow.com/questions/2849517/linking-problem-fatal-error-lnk1112-module-machine-type-x64-conflicts-with-t

**Comment by IanNorris** [comment]
When you click Configure for the first time in a new build destination it will present you with a list of 'generators' (such as Visual Studio 14 2015). Scroll down a bit and select the Win64 version.

Apparently CMake doesn't support generating project files with both platforms in it so I just ran CMake twice to two separate binary folders.

**Comment by kimkulling** [comment]
You can find a small doc here: http://kimkulling.de/?p=15

**Comment by diegoalejandrogomez** [comment]
Hi, after changing the  dropdown to X64, you should change the following configuration (at least with visual studio)
![image](https://cloud.githubusercontent.com/assets/6940618/22484594/ef7096e4-e7e0-11e6-9053-bb8d5bc3fea8.png)

**Comment by nishanth-sundharesan** [comment]
If I changed the settings manually like how **diegoalejandrogomez** mentioned above. Visual Studio is not generating the .dll files. I instead changed the CMake configuration to Win64 while generating Visual Studio files. Visual Studio then outputs the .dll & .lib files upon building.

![image](https://cloud.githubusercontent.com/assets/23176029/26806105/1e9650fa-4a1d-11e7-8c6d-164caf457721.png)

**Comment by kimkulling** [comment]
HAve you checked http://kimkulling.de/2016/05/02/build-asset-importer-lib-for-64bit-with-visual-studio-from-source-repo/ ?
