### ISSUE TITLE
Bug: M3D voxel-based models unsupported (attempting import fails due to zero meshes detected)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5834]
(Note: .m3d format has been deprecated, but the importer still works for some models so reporting problems for future reference)

### Overview
Latest M3D project supports voxels, but our old `m3d.h` header file doesn't contain this code.  Need to surgically update our version of the header to support voxel-based models

### Models which fail to load

Error reports reflect assimp 20 Oct 2024 commit [`e4ef891`](https://github.com/assimp/assimp/commit/e4ef89182d0ae696c1014d1fcfdc860650f7a93d)

<table>
<tr><th>Category</th><th>Model</th><th>Error message</th></tr>
<tr><td rowspan=1>Geometry</td><td><a href="https://bztsrc.gitlab.io/model3d/models/notre.m3d"><tt>Notre Dame</tt></a></td><td><tt>Validation failed: aiScene::mNumMeshes is 0.  At least one mesh must be there</tt></td></tr>
</table>

### Models which load OK
Models without textures, bones or animations, tend to have more success...
<table>
<tr><th>Category</th><th>Model</th><th>Screenshot</th></tr>
<tr><td rowspan=1>Animal</td><td><a href="https://bztsrc.gitlab.io/model3d/models/dragon_vrip_res3.m3d"><tt>Stanford Dragon</tt></a></td><td><img src="https://github.com/user-attachments/assets/3cb8a8c9-87ad-4258-bbee-fcaaaee5d029" alt="m3d_dragon" width=180 /></td></tr>
</table>

**Comment by tellypresence** [comment]
@bztsrc Wondering if the version of the "Notre Dame" .m3d model available for download from your website somehow became corrupted?  Most of the models indicate errors with textures or bones, rather than zero meshes  -- if you wouldn't mind please having a look when you have time it would be very helpful, thank you

**Comment by bztsrc** [comment]
Dear Steve,

Assimp developers put outright errors in my C++ wrapper class code and
later they have used that as an excuse to remove M3D from Assimp. Therefore
it has been not updated for a loooooong time in Assimp. The Notre Dame
model in question is not corrupted, it's just simply doesn't have any
meshes as it contains voxels instead (you can verify this with the on-line
Model3D validator <https://bztsrc.gitlab.io/model3d/validator/> or with the
m3dconv command line tool).

Now the M3D SDK has the capability to convert voxels into triangle mesh on
load automatically and transparently (check it out in the on-line Model3D
viewer <https://bztsrc.gitlab.io/model3d/viewer/>, it will take for a while
because that Notre Dame model has over half a million voxels, but it works).

So no corrupted model file and no bug here, it's just that the m3d.h file
in the Assimp repo is extremely ancient plus the C++ wrapper was sabotaged.

**Comment by tellypresence** [comment]
@bztsrc That's useful information about the voxels; I accidentally discovered that the model was OK when I brought in new code from `m3d.h` and was able to render
<table>
<tr><th>Model</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/notre.m3d"><tt>Notre Dame</tt></a></td><td><img src="https://github.com/user-attachments/assets/88c101c9-9b3f-4a62-977b-b572d4eee0e2" alt="m3d_notre_dame" width=90 ></td><td></td></tr>
</table>

**Comment by tellypresence** [comment]
#5841 is about all I'm able to do for this -- it fixes loading of voxel-based models, but the code is flagged as needed refactoring in the Sonar Cloud [results](https://sonarcloud.io/dashboard?id=assimp_assimp&pullRequest=5841), so the PR can't be merged as-is unfortunately.  Some of the critical problems involve multiple nesting, would be better if someone with more knowledge of how the code works unwound those in order to get the code to pass the checks

**Comment by turol** [comment]
The sonarcloud check seems somewhat overzealous. On the other hand there's no need to check the pointers for `NULL` since it's safe to pass that to `free`.

**Comment by tellypresence** [comment]
@turol Since M3D format is opt-in (disabled by default), and the new code was copied verbatim from the author's repository, wondering if it would be okay to ignore Sonar Cloud checks for this PR?

**Comment by turol** [comment]
That's @kimkulling decision since he added the check.

**Comment by tellypresence** [comment]
Built assimp at 2019 git commit which saw the final fixes for M3D loading.  In [this comment](https://github.com/assimp/assimp/issues/5859#issuecomment-2457755896) it can be observed that animated M3D models never fully worked in assimp.  Because the original author of the M3D format has clearly stated they will not be maintaining M3D format support in assimp, there seems to be little point in restoring M3D support to that partially working state.  The associated PR #5841 worked and can be reopened should the situation change in future.
