### ISSUE TITLE
Bug: M3D model import failures due to bone problems

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5837]
(Note: .m3d format has been deprecated, but the importer still works for some models so reporting problems for future reference)

### Overview
Rigged and animated .m3d model files fail to load in assimp

### Troubleshooting
Tried updating to latest code and enabling bones and animations:
- Updated with latest source files from external repo in [`assimp/code/M3D`](https://gitlab.com/bztsrc/model3d/-/tree/master/assimp/code/M3D)
- Disabled `#define M3D_NOWEIGHTS` and `#define M3D_NOANIMATION` in [`code/AssetLib/M3D/M3DImporter.cpp`](https://github.com/assimp/assimp/blob/master/code/AssetLib/M3D/M3DImporter.cpp)

This didn't help, the rigged and animated 3D model files still fail to load with the same errors.

### Questions
Does anyone know if .m3d model animations ever worked when integrated in assimp?

#### Models which fail to load
Error reports reflect assimp 20 Oct 2024 commit [`e4ef891`](https://github.com/assimp/assimp/commit/e4ef89182d0ae696c1014d1fcfdc860650f7a93d)

<table>
<tr><th>Category</th><th>Model</th><th>Error message</th></tr>

<tr><td rowspan=2>Animal</td><td><a href="https://bztsrc.gitlab.io/model3d/models/bat.m3d"><tt>Bat</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node joint4 (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/seagull.m3d"><tt>Seagull</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node joint4 (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td rowspan=3>Character</td><td><a href="https://bztsrc.gitlab.io/model3d/models/aliveai_character.m3d"><tt>Voxelhuman</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node Bone (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/lara.m3d"><tt>Lara</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node LARA_LEFT_FOOT_BONE (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/swat.m3d"><tt>SWAT</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node Head (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td rowspan=2>From gitlab repo</td><td><a href="https://gitlab.com/bztsrc/model3d/-/blob/master/models/CesiumMan.m3d"><tt>CesiumMan</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node Skeleton_neck_joint_2 (aiNode::mNumChildren is 0)</tt></td></tr>
<tr><td><a href="https://gitlab.com/bztsrc/model3d/-/blob/master/models/mobs_dwarves_character.m3d"><tt>mobs_dwarves_character</tt></a></td><td><tt>Validation failed: aiNode::mChildren is not nullptr for empty node Head (aiNode::mNumChildren is 0)</tt></td></tr>
</table>

#### Models which load OK
Screenshots reflect assimp 20 Oct 2024 commit [`e4ef891`](https://github.com/assimp/assimp/commit/e4ef89182d0ae696c1014d1fcfdc860650f7a93d)

Character model without textures, bones or animations loads OK
<table>
<tr><th>Category</th><th>Model</th><th>Screenshot</th></tr>
<tr><td rowspan=1>Character</td><td><a href="https://bztsrc.gitlab.io/model3d/models/r2d2.m3d"><tt>R2-D2</tt></a></td><td><img src="https://github.com/user-attachments/assets/291bacca-9911-4d66-921e-bb22cad60d67" alt="m3d_r2d2" width=180 /></td></tr>
</table>

**Comment by tellypresence** [comment]
@bztsrc Do you happen to remember if rigged and animated models were ever able to successfully load when M3D was integrated into assimp?  I've tried updating to the latest code from your project, and enabling the `#defines` to enable M3D weights and animations as outlined above, but those files still fail to load with the same errors.  Any background information or insight you might have would be very much appreciated, would be nice to at least get M3D support back to where it was a few years ago -- thank you

**Comment by bztsrc** [comment]
First, thank you for your efforts!

What I remember is that bat, seagull, and mobs_dwarves_character was
definitely working. I've used assview <https://github.com/ccxvii/asstools>
(with the latest Assimp back then) to check if the models were imported
properly and can be displayed like any other Assimp models. BTW,
mobs_dwarves_character was converted using Assimp as well, original file
here
<https://gitlab.com/bztsrc/model3d/-/blob/master/models/mobs_dwarves_character.b3d>
(what I mean by this is, the b3d model and the m3d model had the same
Assimp node structure after importing in my test. Not sure if this still
stands, the b3d importer might have changed as well).

Lara and SWAT are definitely much newer models, never been tested with
Assimp.

It could be also useful to convert the binary models into ASCII models with
m3dconv. This is much like .obj files, but also store the skeleton in a human
readable
<https://gitlab.com/bztsrc/model3d/-/blob/master/docs/a3d_format.md>
format. You should see how many children joint4 or LARA_LEFT_FOOT_BONE for
example has (the test suggests that Assimp read in zero for some reason).
The "Bones" block lists the bones, first line starts from index 0, then the
"Vertex" block uses those indices.

**Comment by tellypresence** [comment]
I can't even load the `.b3d` files for comparison, those fail with error
```
aliveal_character.b3d: Validation failed: aiNodeAnim::mPosiionKeys[123].mTime (124.00000) is larger than aiAnimation::mDuration (which is 123.00000)
mobs_dwarves_character.b3d: Validation failed: aiNodeAnim::mPosiionKeys[220].mTime (221.00000) is larger than aiAnimation::mDuration (which is 220.00000)
```

**Comment by tellypresence** [comment]
Rigged/animated models "sort of" worked as of 12 Feb 2020 assimp commit [`58b9dcb`](https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2) "Merge pull request https://github.com/assimp/assimp/pull/2973 from bztsrc/master"

Original author has made clear M3D/assimp integration problems will not be addressed, so this issue is moot; restoring to the previous state would still have severe artifacts and so not worth the effort, closing

**Comment by tellypresence** [comment]
Feedback from the original author below, in case there's useful information for future reference in the event someone else wants to investigate

> First, thank you for your efforts! 

>What I remember is that bat, seagull, and mobs_dwarves_character was definitely working. I've used assview <https://github.com/ccxvii/asstools> (with the latest Assimp back then) to check if the models were imported properly and can be displayed like any other Assimp models. BTW, mobs_dwarves_character was converted using Assimp as well, 
original file here 
    <https://gitlab.com/bztsrc/model3d/-/blob/master/models/mobs_dwarves_character.b3d> 

> (what I mean by this is, the b3d model and the m3d model had the same Assimp node structure after importing in my test. Not sure if this still stands, the b3d importer might have changed as well). 

>Lara and SWAT are definitely much newer models, never been tested with Assimp. 

>It could be also useful to convert the binary models into ASCII models with m3dconv. This is much like .obj files, but also store the skeleton in a human readable 
<https://gitlab.com/bztsrc/model3d/-/blob/master/docs/a3d_format.md> format. 

>You should see how many children joint4 or LARA_LEFT_FOOT_BONE for example has (the test suggests that Assimp read in zero for some reason). The "Bones" block lists the bones, first line starts from index 0, then the "Vertex" block uses those indices.
