### ISSUE TITLE
How to merge two scenes?

### ISSUE THREAD

**Issue by wellingtonex** [assimp/assimp#584]
Hello,

I need to merge two scenes. Anyone there ever had to do that?
The method void SceneCombiner :: MergeScenes (aiScene ** _dest, std :: vector <aiScene *> & src,
unsigned int flags) seem to do what I want, however is not exposed in the dll. This method could not be exposed in the dll? 
Can anyone help me?

Thanks.

**Comment by kimkulling** [comment]
We need to check that!

**Comment by Aspirisha** [comment]
Good day, everyone.

I am just curious is `SceneCombiner` usable now from outside assimp sources? I don't see any include file containing it in exported includes directory (I mean, there is no one in include/assimp/)

**Comment by xaioxw** [comment]
when I‘m use SceneCombiner :: MergeScenes (aiScene ** _dest, std :: vector <aiScene *> & src,
unsigned int flags) to test IT，There were a lot of crashes
