### ISSUE TITLE
Bug: M3D unable to locate stb_image functions

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5847]
### Summary
(updated)
`m3d.h` is attempting to directly use private implementation details of `stb_image.h` which will not be available since `STB_IMAGE_IMPLEMENTATION` is defined elsewhere.

Loading textured `.m3d` models fails because the central implementation of `stb_image` provided by [`code/Common/Assimp.cpp`](https://github.com/assimp/assimp/blob/master/code/Common/Assimp.cpp) can't be located.

This problem is the direct cause of issue
- #5836 

#### Must ensure only a single implementation created for header-only lib `stb_image`
As instructed in [`contrib/stb/stb_image.h`](https://github.com/assimp/assimp/blob/master/contrib/stb/stb_image.h):
```
   Do this:
      #define STB_IMAGE_IMPLEMENTATION
   before you include this file in *one* C or C++ file to create the implementation.

   // i.e. it should look like this:
   #include ...
   #define STB_IMAGE_IMPLEMENTATION
   #include "stb_image.h"
```
This is to ensure there's only a single implementation created for the header-only `stb_image` library.

Because assimp has multiple modules supporting various model formats, any of which might use `stb_image`, and assimp itself might be part of an even larger project, things were set up so that `stb_image` in assimp is only implemented once, and won't conflict with other external projects also using `stb_image`.  Source file [`code/Common/Assimp.cpp`](https://github.com/assimp/assimp/blob/master/code/Common/Assimp.cpp) is the designated location where the line critical line `#define STB_IMAGE_IMPLEMENTATION` is added:
```
#define STB_IMAGE_IMPLEMENTATION
#include "Common/StbCommon.h"
```

[`code/Common/StbCommon.h`](https://github.com/assimp/assimp/blob/master/code/Common/StbCommon.h) in turn prefixes the various `stb_*` functions to avoid conflicts with other external project that also use `stb_image`:
```
#define stbi_convert_iphone_png_to_rgb assimp_stbi_convert_iphone_png_to_rgb
#define stbi_convert_iphone_png_to_rgb_thread assimp_stbi_convert_iphone_png_to_rgb_thread
...
#define stbi_zlib_decode_noheader_buffer assimp_stbi_zlib_decode_noheader_buffer
#define stbi_zlib_decode_noheader_malloc assimp_stbi_zlib_decode_noheader_malloc
```

So in theory everything should be all set to go for any assimp submodules using `stb_image`; currently there are 2
- `M3D`
- `PBRT` 

#### Opt-in to build `M3D`
Enable at least the `M3D` importer by turning on CMake option:
```
option(ASSIMP_BUILD_M3D_IMPORTER "" on)
```

#### Demonstrate failing case
With `M3D` importer enabled via CMake option as explained above, build assimp as usual and attempt to load textured `M3D` model e.g. [`viper.m3d`](https://bztsrc.gitlab.io/model3d/models/viper.m3d); expect to observe model load fail with error `Validation failed: aiTexture::pcData is nullptr`

#### Demonstrate workaround hack
Now add the `stb_image` `#define` in file [`code/AssetLib/M3D/M3DImporter.cpp`](https://github.com/assimp/assimp/blob/master/code/AssetLib/M3D/M3DImporter.cpp):
```
#define STB_IMAGE_IMPLEMENTATION // <<< Add this line
#include "M3DWrapper.h"
```
Rebuild assimp and attempt to load the textured `M3D` model, this time expect success.

### Related issues/PRs

- Issue #2753 (fixed by PR #2766)
- Issue #3855 (fixed by PR #3889)
- PR #3985
- Issue #4467 (fixed by PR #4478)
- Issue #4489 (fixed by PR #4991)

### Investigation
Can anyone verify that this used to work, or have any insight as to why `M3D` isn't locating `stb_image` provided by `Assimp.cpp`?

**Comment by turol** [comment]
Looks like it only parses the embedded image if `STBI__PNG_TYPE` is defined which only happens when `STB_IMAGE_IMPLEMENTATION` is defined. It then calls `stbi__png_load` which is supposed to be internal to stb_image.

https://github.com/assimp/assimp/blob/53d4663f298ffa629505072fc01a5219c2b42b3e/code/AssetLib/M3D/m3d.h#L979

**Comment by tellypresence** [comment]
@turol Thank you, no I think I understand what's going on.

What appears to be happening is that `m3d.h` is using internal implementation details of `stb_image.h` that are not part of the public header.

To verify, try removing the `STBI__PNG_TYPE` guards in `m3d.h`, will observe build failure with errors e.g.
```
error: unknown type name 'stbi__context'
```

So there's an implicit expectation that the entire implementation will be exposed when `m3d.h` is included, which will not be the case with assimp's designated single definition of `STB_IMAGE_IMPLEMENTATION`

**Comment by tellypresence** [comment]
@turol Please review #5848 when you have time, this creates a wrapper function in the proper scope to expose internal `sbi_image` function to get M3D textured models working without a major overhaul -- thank you

**Comment by tellypresence** [comment]
Built assimp at 2019 git commit which saw the final fixes for M3D loading.  In [this comment](https://github.com/assimp/assimp/issues/5859#issuecomment-2457755896) it can be observed that animated M3D models never fully worked in assimp.  Because the original author of the M3D format has clearly stated they will not be maintaining M3D format support in assimp, there seems to be little point in restoring M3D support to that partially working state.  The associated PR #5848 worked and can be reopened should the situation change in future.
