### ISSUE TITLE
[Epic] Rejuvenate M3D model loading

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5859]
Goal: restore the ability for users to opt-in for M3D model support, and be able to load as many available [sample models](https://bztsrc.gitlab.io/model3d/#models) as possible.

- [x] #5835
   Enable users to easily opt-in via CMake options rather than having to patch assimp CMake scripts to override hardcoded `#define`s
   With this change users can load basic M3D models, **_excluding_** those that are
     - textured
     - rigged/animated
     - voxel-based

- [x] #5848
   Support loading textured M3D models

- [x] #5841 
   Support loading voxel-based M3D models

- [x] #5837 
   Support loading rigged/animated M3D models
   Rigged/animated models "sort of" worked as of
   - 12 Feb 2020 assimp commit [`58b9dcb`](https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2) "Merge pull request https://github.com/assimp/assimp/pull/2973 from bztsrc/master"

   Orginal author will not be fixing this (comments below), so not worth the effort on assimp side to restore to what was at best the partially working state of 12 Feb 2020 commit [`58b9dcb`](https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2)
   

- [x] #5843
   The "elephant" sample M3D model fails to load.
   The download page says the model is untextured, but even with the patch in place to allow loading textured models, the model still fails to load for apparent texture-related reasons.

   "Elephant" model was not working as of the final M3D PR:
   - 12 Feb 2020 assimp commit [`58b9dcb`](https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2) "Merge pull request https://github.com/assimp/assimp/pull/2973 from bztsrc/master"

   Orginal author will not be fixing this (comments below); this model _never worked_ and so nothing to be done on assimp side.

**Comment by tellypresence** [comment]
@bztsrc I think I've taken this effort as far as I can.  At this stage, if a couple of PRs get merged, users will be able to load all of your sample models except 
- the rigged/animated ones
- the elephant

If you're able to spend a few hours some weekend to try to fix the problems with those models, can get to a state where users can load 100% of your sample models via assimp.  Not sure whether you're still actively maintaining the M3D format, but if so please consider addressing these issues to expand your user base -- thank you

**Comment by bztsrc** [comment]
Thank you so much for your efforts!

On Sun, 3 Nov 2024 at 02:05, Steve M ***@***.***> wrote:

> @bztsrc <https://github.com/bztsrc> I think I've taken this effort as far
> as I can. At this stage, if a couple of PRs get merged, users will be able
> to load all of your sample models except
>
>    - the rigged/animated ones
>    - the elephant
>
> If you're able to spend a few hours some weekend to try to fix the
> problems with those models,
>

Frankly I'm not really interested. There are no problems with the M3D
models, they are the same models as before, which were working and they are
still working with all the other M3D applications.

can get to a state where users can load 100% of your sample models via
> assimp. Not sure whether you're still actively maintaining the M3D format,
>

Well, I'm actively maintaining the M3D code base, but the M3D format and
the in-memory structure that the SDK uses hasn't changed from the very
beginning, it is as stable as it can be. Nothing has changed on the M3D
side as long as Assimp concerned.


> but if so please consider addressing these issues to expand your user base
> -- thank you
>

I'm sorry, but I'm the M3D developer and not an Assimp developer. As I've
said, the M3D SDK's API and in-memory format hasn't changed, and it used to
work in Assimp but if not any more then the problem is on the Assimp side
for sure, and I'm not willing to spend time with that because the Assimp
devs were total j**ks (except kimkulling, he was always nice and
professional).

I wrote a detailed description
<https://gitlab.com/bztsrc/model3d/-/tree/master/assimp#model-with-skeletons>
on how the M3D in-memory structure should be mapped to Assimp in-memory
nodes, also here is my Assimp wrapper
<https://gitlab.com/bztsrc/model3d/-/blob/master/assimp/code/M3D/M3DImporter.cpp>
code (with lots of comments and explanations) that used to work with rigged
models and with the elephant too. I'm afraid that's all the help I can
provide for Assimp integration.

Cheers,
bzt

**Comment by tellypresence** [comment]
@bztsrc Thank you for your response.

I wanted to check whether the code did in fact work at one point so went back in time to the commit where you introduced M3D to assimp:
 - 4 Nov 4 2019 assimp commit [`308db73`](https://github.com/assimp/assimp/commit/308db73d0b3c2d1870cd3e465eaa283692a4cf23) "Merge pull request https://github.com/assimp/assimp/pull/2736 from bztsrc/master"

Then built assimp and retried loading the sample models

## Summary
- most of the models cause catastrophic crash on load, including the "elephant" model
- two (non-textured) rigged/animated models worked at that point

## Details
Most sample models cause catastrophic crash on load, including (but not limited to) anything with textures.  2 rigged/animated models were able to load and appear to animate OK, though the "swat" model seems to have insane bone count, and the bone check indicates an incorrect number of meshes, so possibly there was a problem with converting from M3D to assimp skeleton in the code at that commit.

The "elephant" model is among the ones that crash, so based on this test it appears that the elephant never worked.

## Screenshots

### Models that loaded OK
<table>
<tr><th>Model</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/teapot.m3d"><tt>teapot.m3d</tt></a></td><td><img alt="teapot_m3d" src="https://github.com/user-attachments/assets/ac5ea7b8-161f-477c-a9a9-c90fdb3cb53e" width=90 ></td><td></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/madmax.m3d"><tt>madmax.m3d</tt></a></td><td><img alt="madmax_m3d" src="https://github.com/user-attachments/assets/dea4e923-7bdb-41b1-869e-dd7e97810cb5" width=90 ></td><td></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/r2d2.m3d"><tt>r2d2.m3d</tt></a></td><td><img alt="r2d2_m3d" src="https://github.com/user-attachments/assets/1ddc158d-6cd2-4788-b6ce-6ca0ef4d9a8c" width=90 ></td><td></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/swat.m3d"><tt>swat.m3d</tt></a></td><td><img alt="swat_m3d" src="https://github.com/user-attachments/assets/9e8ff818-7de5-45d5-9557-0882971c0b43" width=90 ></td><td>Model has 4 meshes<br>Model has 24 animations<br>Model indicates it has 47,120 bones in 760 meshes (despite only having 4 meshes)<br>(Because of massive bone count, implementation can't keep up and model appears fragmented)</td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/aliveai_character.m3d"><tt>aliveai_character.m3d</tt></a></td><td><img alt="aliveai_character_m3d" src="https://github.com/user-attachments/assets/3fc8f84d-ccfd-4460-9ea1-aab9a2ad2918" width=90 ></td><td>Model has 1 mesh<br>Model has 1 animation<br>Model indicates it has 6 bones in 1 mesh (seems reasonable)</td></tr>

</table>

### Models that crash on load
All these models caused catastrophic crash on import attempt:
<table>
<tr><th>Model</th></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/bat.m3d"><tt>bat.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/dragon_vrip_res3.m3d"><tt>dragon_vrip_res3.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/elephant.m3d"><tt>Elephant</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/seagull.m3d"><tt>seagull.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/atat.m3d"><tt>atat.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/batmobile.m3d"><tt>batmobile.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/cessna.m3d"><tt>cessna.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/fishboat.m3d"><tt>fishboat.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/castle.m3d"><tt>castle.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/medieval.m3d"><tt>medieval.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/bender.m3d"><tt>bender.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/gandalf.m3d"><tt>gandalf.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/lara.m3d"><tt>lara.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/wolfzoid.m3d"><tt>wolfzoid.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/yoda.m3d"><tt>yoda.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/awing.m3d"><tt>awing.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/birdofprey.m3d"><tt>birdofprey.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/viper.m3d"><tt>viper.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/enterprise.m3d"><tt>enterprise.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/mfalcon.m3d"><tt>mfalcon.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/alkesh.m3d"><tt>alkesh.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/tie.m3d"><tt>tie.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/vaderstie.m3d"><tt>vaderstie.m3d</tt></a></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/xwing.m3d"><tt>xwing.m3d</tt></a></td></tr>

</table>

Do you recall if there were fixes made to address the crashing and weird bone problems?  If so please let me know and I can try again at that specific git commit, would be great to establish if there was a commit where things were working so we can figure out where things broke -- thank you

**Comment by tellypresence** [comment]
@bztsrc So it looks like the final PR for M3D was 
 - 12 Feb 2020 assimp commit [`58b9dcb`](https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2) "Merge pull request https://github.com/assimp/assimp/pull/2973 from bztsrc/master"

Built assimp at this commit and retried loading the sample models

## Summary
- most of the models load OK at this commit
- "elephant" model (and "CesiumMan") failed to load (and it seems clear these models never worked in assimp at all)
- Most of the rigged/animated models loaded and animated, but some had animation artifacts

## Details
Textured models were mostly working at this commit.  Rigged/animated models were able to load, but while "Lara" appeared to animate correctly and have reasonable bone count, "bat" and "seagull" had severe animation artifacts, and "swat" still has insane bone count.

The "elephant" (and "CesiumMan") models fail to load, and I must conclude these models never worked in assimp at all.

## Screenshots

### Models that load OK
<table>
<tr><th colspan=3>12 Feb 2020 assimp commit <a href="https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2"><tt>58b9dcb</tt></a></th></tr>
<tr><th>Model</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/bat.m3d"><tt>bat.m3d</tt></a></td><td><img alt="bat_m3d" src="https://github.com/user-attachments/assets/65d84235-0618-47ef-bad5-dd83c1e61eaa" width=90 ></td><td>Obvious animation artifacts</td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/seagull.m3d"><tt>seagull.m3d</tt></a></td><td><img alt="seagull_m3d" src="https://github.com/user-attachments/assets/e8713f29-3c67-42a6-9882-987b5e6b5711" width=90 ></td><td>Obvious animation artifacts</td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/lara.m3d"><tt>lara.m3d</tt></a></td><td><img alt="lara_m3d" src="https://github.com/user-attachments/assets/e1b01e54-5406-4f98-a44a-68bb32a32542" width=90 ></td><td>Model has 1 mesh<br>Model has 313 animations<br>Model indicates it has 15 bones in 1 mesh (seems correct)</td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/swat.m3d"><tt>swat.m3d</tt></a></td><td><img alt="swat_m3d" src="https://github.com/user-attachments/assets/652a3a8e-1fec-45e1-abbc-437b9db3dbf5" width=90 ></td><td>Model has 4 meshes<br>Model has 24 animations<br>Model indicates it has 47,120 bones in 760 meshes (despite only having 4 meshes)<br>(Because of massive bone count, implementation can't keep up and model appears fragmented)</td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/batmobile.m3d"><tt>batmobile.m3d</tt></a></td><td><img alt="batmobile_m3d" src="https://github.com/user-attachments/assets/2b01ab28-1d3a-496d-9c9a-2c2de1c113d0" width=90 ></td><td></td></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/tie.m3d"><tt>tie.m3d</tt></a></td><td><img alt="tie_m3d" src="https://github.com/user-attachments/assets/1dfad972-7591-49d1-b8ce-f3cf3abb6cf5" width=90 ></td><td></td></tr>

</table>


### Models that fail to load
<table>
<tr><th colspan=2>12 Feb 2020 assimp commit <a href="https://github.com/assimp/assimp/commit/58b9dcbdc713730680ddb7c340d869e978b446e2"><tt>58b9dcb</tt></a></th></tr>
<tr><th>Models failing to load</th><th>Notes</th></tr>
<tr><td><a href="https://bztsrc.gitlab.io/model3d/models/elephant.m3d"><tt>Elephant</tt></a></td><td><tt>Validation failed: aiTexture::pcData is NULL</tt></td></tr>
<tr><td><a href="https://gitlab.com/bztsrc/model3d/-/blob/master/models/CesiumMan.m3d?ref_type=heads"><tt>CesiumMan.m3d</tt></a></td><td><tt>Validation failed: aiTexture::pcData is NULL</tt></td></tr>


</table>

So you were correct that most of the models loaded at one point, except that "elephant" and "CesiumMan" models clearly never worked in assimp.
Also, as of the final M3D PR, there were obvious problems with skeletal animations.

**Comment by tellypresence** [comment]
Feedback from the original author below, in case there's useful information for future reference in the event someone else wants to investigate 

> Thank you so much for your efforts!

>> assimp. Not sure whether you're still actively maintaining the M3D format,

> Well, I'm actively maintaining the M3D code base, but the M3D format and the in-memory structure that the SDK uses hasn't changed from the very beginning, it is as stable as it can be. Nothing has changed on the M3D side as long as Assimp concerned.
>> but if so please consider addressing these issues to expand your user base -- thank you

> I'm sorry, but I'm the M3D developer and not an Assimp developer. As I've said, the M3D SDK's API and in-memory format hasn't changed, and it used to work in Assimp but if not any more then the problem is on the Assimp side for sure, and I'm not willing to spend time with that because the Assimp devs were total j**ks (except kimkulling, he was always nice and professional). 

>I wrote a detailed description <https://gitlab.com/bztsrc/model3d/-/tree/master/assimp#model-with-skeletons> on how the M3D in-memory structure should be mapped to Assimp in-memory nodes, also here is my Assimp wrapper <https://gitlab.com/bztsrc/model3d/-/blob/master/assimp/code/M3D/M3DImporter.cpp> code (with lots of comments and explanations) that used to work with rigged models and with the elephant too. 

>I'm afraid that's all the help I can provide for Assimp integration.

>Cheers, bzt

**Comment by tellypresence** [comment]
Built assimp at 2019 git commit which saw the final fixes for M3D loading.  In [this comment](https://github.com/assimp/assimp/issues/5859#issuecomment-2457755896) it can be observed that animated M3D models never fully worked in assimp.  Because the original author of the M3D format has clearly stated they will not be maintaining M3D format support in assimp, there seems to be little point in restoring M3D support to that partially working state.  The associated PRs #5841 and #5848 worked and can be reopened should the situation change in future.
