### ISSUE TITLE
Need access to SceneCombiner.h and ScenePrivate.h and other headers in the "assimp/code" folder

### ISSUE THREAD

**Issue by pxds** [assimp/assimp#586]
Hi,

I've compiled assimp, but i those two .h aren't included in the build output directory and it would be very useful if i could use them. 

Is there any way i can access those headers without copy and pasting manually into the build directory? What's the point of the code folder if it isn't possible to include them after the build?

Thanks.

**Comment by kimkulling** [comment]
Seems that we wanted to have them private. Let's check if we can change that.

**Comment by kimkulling** [comment]
Are you using the binaries? If not: just add the sources of Asset-Importer-Lib and add assimp/code to your include path. Now you can use them. 
And for which use case do you want to use these headers?

Thanks in advance!

**Comment by TripleSnail** [comment]
I need only SceneCombiner. 

I tried adding these lines to assimp_cmd  (which includes both directories you mentioned):

```
#include <SceneCombiner.h>
// ...
aiScene* sceneCopy = nullptr;
Assimp::SceneCombiner::CopyScene(&sceneCopy, nullptr, true);
```

but I get linker errors:

> /home/abc/xyz/assimp/tools/assimp_cmd/Main.cpp:230: undefined reference to `Assimp::SceneCombiner::CopyScene(aiScene**, aiScene const*, bool)'
> collect2: error: ld returned 1 exit status

I'd like to make a small utility to combine models into a bigger one.

This is how assimp_cmd includes those directories:

```
INCLUDE_DIRECTORIES(
  ${Assimp_SOURCE_DIR}/include
  ${Assimp_SOURCE_DIR}/code
)
```

**Comment by TripleSnail** [comment]
After adding `ASSIMP_API` to SceneCombiner class, moving SceneCombiner.h to `PUBLIC_HEADERS` in code/CMakeLists.txt and doing a clean compile, I was able to use SceneCombiner.
