### ISSUE TITLE
Animation channels not matching node names.

### ISSUE THREAD

**Issue by sagaceilo** [assimp/assimp#5865]
Hello,
I updated assimp to latest after couple months and got my animations broken. After investigation I found that  
animation->mChannels[i]->mNodeName contains sufixes like "_$AssimpFbx$_Rotation", "_$AssimpFbx$_Translation" and "_$AssimpFbx$_Scaling". 
They used to be just **node name** with position, rotation and scale key frame. But now it creates separate channels with just one type filled with data and leaving single key entry in other. In other words:

Hips_$AssimpFbx$_Rotation
 - 111 rotation keys, 1 pos and scale key
Hips_$AssimpFbx$_Translation
- 111 pos keys, 1 rot and scale key

End even when reading just those valid keys animation seems broken, like missing channels or something :/ Is there a way to keep channels being created "old" way ?
Thanks!

**Comment by sagaceilo** [comment]
I found its related with https://github.com/assimp/assimp/blob/e06b80f6b086e8a7b50b44dbd728604ec6522f68/code/AssetLib/FBX/FBXImportSettings.h#L141C7-L141C8
But changing `importer->SetPropertyBool( AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, false );` seems to have o effect.

**Comment by tellypresence** [comment]
@sagaceilo Please share a download link for a sample 3D model file to reproduce the problem, thank you
