### ISSUE TITLE
Bug: Broken C compilation aiGetMaterialFloat() and aiGetMaterialInteger() should be static inline

### ISSUE THREAD

**Issue by jerstlouis** [assimp/assimp#5875]
**Describe the bug**
The public functions `aiGetMaterialInteger()` and `aiGetMaterialFloat()` are declared as `inline` rather than `static inline`.

This breaks compilation of C programs (unresolved external symbols) when linking against the library.

**To Reproduce**
Try to build a C sample using these functions.

**Expected behavior**
Compiling C programs using assimp should not break in published releases (this made it to the Arch Linux repos).
These functions should be declared `static inline`.

**Platform (please complete the following information):**
 - Arch derived distros

**Additional context**
Perhaps sample C programs regression tests are needed to avoid such breakages?

Thank you!

**Comment by kimkulling** [comment]
Thanks for the report. PR is in CI.
