### ISSUE TITLE
travis build doesn't fail when unit tests fail

### ISSUE THREAD

**Issue by LegalizeAdulthood** [assimp/assimp#589]
The travis script is hiding the result status of the test executables:

```
    cmake -G "Unix Makefiles" -DASSIMP_ENABLE_BOOST_WORKAROUND=YES -DASSIMP_NO_EXPORT=$TRAVIS_NO_EXPORT -DBUILD_SHARED_LIBS=$SHARED_BUILD ;
    make ;
    sudo make install ;
    sudo ldconfig ;
    cd test/unit ;
    ../../bin/unit ;
    cd ../regression ;
    chmod 755 run.py ;
    ./run.py ;
    chmod 755 result_checker.py ;
    ./result_checker.py;
```

If `../../bin/unit` fails, the travis build doesn't fail.
If `./run.py` fails, the travis build doesn't fail.
If `./result_checker.py` fails, the travis build doesn't fail (I think; the whole thing is inside an `if` and I'm not sure if the last command on an `if`/`else` shell command bubbles out.

There's a failing unit test on master because the test assumes that `/home/wise` exists for exporting a file.  This has probably been hiding in master for some time now because travis has been passing.

**Comment by kimkulling** [comment]
Should be fixed by 72bbbcac520bedd4a7b541bb49216e7ba7b23bed

**Comment by LegalizeAdulthood** [comment]
That just changes the `run.py` script; the problem is with the `.travis.yml` file shell commands.  From the way I understand travis and `sh`, if the command `../../bin/unit` fails, the script keeps executing, it doesn't bubble out the failure to travis.  It needs to be something more like this:

```
    cmake -G "Unix Makefiles" -DASSIMP_ENABLE_BOOST_WORKAROUND=YES -DASSIMP_NO_EXPORT=$TRAVIS_NO_EXPORT -DBUILD_SHARED_LIBS=$SHARED_BUILD ;
    make && sudo make install && sudo ldconfig && (cd test/unit; ../../bin/unit) && (cd ../regression;  chmod 755 run.py; ./run.py) && chmod 755 result_checker.py && ./result_checker.py
```

The giant run-on line is kind of annoying, but I don't think you can have line continuations in the `.travis.yml` file.  I ended up creating a `.travis.sh` script to do my build allowing me access to bash functions and whatever else I wanted without the restrictions imposed by travis for executing shell commands directly from the `.travis.yml` file.

**Comment by LegalizeAdulthood** [comment]
[here](https://travis-ci.org/assimp/assimp/jobs/68912014) is an example of a build that passes travis, but has failing unit tests.

**Comment by Silmathoron** [comment]
I am experiencing a similar problem: [this build](https://travis-ci.org/Silmathoron/NNGT/jobs/173536493) finished with status 0 though one test failed in each matrix element.
Is this because of coverage?

**Comment by kimkulling** [comment]
No problem!
