### ISSUE TITLE
Bug/Feature Request: GLTF export tangent/bitangent

### ISSUE THREAD

**Issue by JulianKnodt** [assimp/assimp#5897]
**Is your feature request related to a problem? Please describe.**
It appears tangents are not exported when exporting a GLTF file

**Describe the solution you'd like**
There seems to be some support for export, but it doesn't seem to actually be used.

**Describe alternatives you've considered**
It seems like it's not a perfect round-trip if importing/exporting gltf files because of this and `JoinIdenticalVertices`

**Additional context**
N/A

**Comment by kimkulling** [comment]
And another fix by https://github.com/assimp/assimp/pull/6322
