### ISSUE TITLE
Bug: Compile error if ASSIMP_DOUBLE_PRECISION enable

### ISSUE THREAD

**Issue by hankarun** [assimp/assimp#5901]
**Describe the bug**
When ASSIMP_DOUBLE_PRECISION is set to TRUE, compiler error happens in the material header file.

**To Reproduce**
Just enable the variable.

**Expected behavior**
It needs to compile

**Platform (please complete the following information):**
 - OS: Windos Visual Studio 2022
 - Version: master and 5.4.3

**Additional context**
There are some missing ai_real definitions in the material function definitions.
Related #5850

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5902
