### ISSUE TITLE
[Regression] Bug in PR 5802 causing CI "ubuntu-latest-g++-build-and-test" check failures

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5929]
PR #5802 (merged 18 Nov 2024, commit [`41cc2f6`](https://github.com/assimp/assimp/commit/41cc2f66a4c3f89b0885f3fbcc49ff981147e161)) introduced bug in line 1643 of [`glTF2Importer.cpp`](https://github.com/assimp/assimp/blame/master/code/AssetLib/glTF2/glTF2Importer.cpp)

Other PRs will now fail `ubuntu-latest-g++-build-and-test` check due to error e.g.
```
  Error: /home/runner/work/assimp/assimp/code/AssetLib/glTF2/glTF2Importer.cpp:1643:28: 
      error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ 
          output may be truncated copying between 0 and 3 bytes from a string of length 3 [-Werror=stringop-truncation]
   1643 |                     strncpy(tex->achFormatHint, ext, len);
        |                            ^
  cc1plus: all warnings being treated as errors
```

Sample CI errors can be viewed [here](https://github.com/assimp/assimp/actions/runs/12402209985/job/34623261357?pr=5830) and [here](https://github.com/assimp/assimp/actions/runs/12402318384/job/34623593570?pr=5857#logs)

**Comment by kimkulling** [comment]
https://github.com/assimp/assimp/pull/5931/
