### ISSUE TITLE
Bug: every commit has red "X" since 29 Oct 2024

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5930]
Every commit to assimp since 29 Oct 2024 shows a red "X" indicating CI failure (last green checkmark was 24 Oct 2024)

CI should be adjusted to ensure that if PRs pass pre-commit checks, they don't fail CI checks when merged

**Comment by kimkulling** [comment]
That is correct. This is caused by the quality guard from SonarCube. The build is still green, and all tests are fine, but the quality gate is red.
