### ISSUE TITLE
Support static analysis in travis build

### ISSUE THREAD

**Issue by LegalizeAdulthood** [assimp/assimp#595]
I see that we have a coverity build status button on the README, although it always says "pending" whenever I view the page.

I'm building a patch that follows the method I outlined in a [blog post](https://legalizeadulthood.wordpress.com/2014/12/07/adding-static-analysis-to-your-c-github-repository/) for adding cppcheck and clang static analysis to the travis build.  I have the cppcheck build passing at level warning and am working on the issues identified by clang.

This issue is a placeholder for opening discussion on static analysis.

**Comment by kimkulling** [comment]
Is fixed: https://scan.coverity.com/projects/5607
