### ISSUE TITLE
Should travis build fail if source files have wrong whitespace policy?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [assimp/assimp#605]
Now that we have `.editorconfig`, we have an explicit statement of the whitespace policy on the code.

However, nothing is enforcing this on pull requests except manual checking.  This means we can drift back into random whitespace without paying careful attention to whitespace in pull requests by hand.  (Boring and tedious -- isn't this what computers are for?)

Should we enhance the travis build to fail if the source code has whitespace that violates the policy specified in `.editorconfig`?  Mostly, I'm thinking presence of tab characters, wrong newline character and trailing whitespace.  It's probably too annoying to try and write code to check the indent level.

**Comment by kimkulling** [comment]
Duplicate to https://github.com/assimp/assimp/issues/543.

**Comment by LegalizeAdulthood** [comment]
That handles the line endings, does it also handle tabs and trailing whitespace?

**Comment by kimkulling** [comment]
Really good question, let's investigate it!

**Comment by LegalizeAdulthood** [comment]
Looks like we might be able to get everything we want with [core.whitespace](http://git-scm.com/docs/git-config)

**Comment by kimkulling** [comment]
Ok, so we don't need this issue any more.
