### ISSUE TITLE
Line endings violate .gitattributes

### ISSUE THREAD

**Issue by danijar** [assimp/assimp#611]
According to the `.gitattributes`, source code files should have Unix line endings.

```
# Declare files that will always have LF line endings on checkout.
*.cpp text eol=lf
*.h text eol=lf
*.c text eol=lf
*.hpp text eol=lf
*.txt text eol=lf
*.cmake text eol=lf
*.sh text eol=lf
```

When we look at the `code` folder, there is only one file with Windows line endings, which is a MinGW file so I think that is okay.

```bash
$ ls code | wc -l
337
$ egrep -l $'\r'\$ code/* | wc -l
grep: code/BoostWorkaround: Is a directory
grep: code/res: Is a directory
1
```

However, in the `code/BoostWorkaround/boost/` folder, all of the files have Windows line endings. It seems like they existed before the `.gitattributes` and have never been converted.

```bash
$ ls code/BoostWorkaround/boost/ | wc -l
15
$ egrep -l $'\r'\$ code/BoostWorkaround/boost/* | wc -l
grep: code/BoostWorkaround/boost/math: Is a directory
grep: code/BoostWorkaround/boost/tuple: Is a directory
13
```

This is a problem, since after cloning the repository on Linux, the whole [working directory is marked as modified][1]. Therefore, you cannot check out a branch or commit. In my own application, I use CMake's `ExternalProject_Add` to automatically clone and build Assimp. This failed due to the whitespace issue.

```
Cloning into 'source'...
error: Your local changes to the following files would be overwritten by 
checkout:
    code/BoostWorkaround/boost/format.hpp
    code/BoostWorkaround/boost/shared_ptr.hpp
    code/BoostWorkaround/boost/timer.hpp
    contrib/irrXML/irrXML.cpp
    doc/dox.h
    samples/SimpleOpenGL/Sample_SimpleOpenGL.c
    scripts/IFCImporter/entitylist.txt
Please, commit your changes or stash them before you can switch branches.
Aborting
CMake Error at temp/Assimp-gitclone.cmake:49 (message):
  Failed to checkout tag: 'dca3f09'
```

This is how the line endings can be converted to Unix style.

```bash
find -iregex '.*\.\(cpp\|h\|c\|hpp\|txt\|cmake\|sh\)$' -exec sed -i 's/\r//' {} \;
```

I filed a [pull request that applies this patch][2].

[1]: http://stackoverflow.com/a/10363472/1079110
[2]: https://github.com/assimp/assimp/pull/612

**Comment by LegalizeAdulthood** [comment]
I noticed this too when applying `.editorconfig` changes to the code, but wasn't sure about the origin of these "boost workaround" files.

**Comment by danijar** [comment]
@LegalizeAdulthood Do you have some time to checkout my pull request and see if it solves the `.editorconfig` problems as well?

**Comment by LegalizeAdulthood** [comment]
The `.editorconfig` situation is more suggestive, while the `.gitattributes` is more prescriptive.

That is, **if** you have an editor config plugin for your editor, it will observe the rules in the `.editorconfig` file.  However, you could still violate the whitespace rules if you don't have an editor that observes the suggestions in the `.editorconfig` file.

The `.gitattributes` approach **enforces** these whitespace rules through git itself, so as you observed, you get modified files on checkout solely because git enforced `.gitattributes`.

I haven't reviewed the diff, but if it's just whitespace changes and it makes git happy, then go for it :smile_cat:

**Comment by danijar** [comment]
I see. It works for me and I can confirm that with the fix there are no uncommitted changes after cloning anymore. I just ran the Unix command above. If you want to validate the changes, you could use this command to compute the hash of the repository for my pull request and after you manually run the command above.

```bash
find . -type f -not -path ./.git/* -exec md5sum {} \; | md5sum
```

Could you merge the pull request, please?

**Comment by danijar** [comment]
@LegalizeAdulthood Is there anything keeping this from being merged? [Link to the pull request](https://github.com/assimp/assimp/pull/612).

**Comment by LegalizeAdulthood** [comment]
LGTM, but I am just a contributor like you :smile_cat:

**Comment by danijar** [comment]
Thanks, so I might ask @kimkulling. Could you have a look, please?

**Comment by kimkulling** [comment]
Sure I will try!

**Comment by kimkulling** [comment]
Just fixed.
