### ISSUE TITLE
 855 commits to master since last release

### ISSUE THREAD

**Issue by tedivm** [assimp/assimp#616]
Could we potentially get a new release soon?

**Comment by kimkulling** [comment]
Yes, I am rying to find time for finalizing my work for OpenGEX, but maybe we can do a minor release before.

**Comment by tedivm** [comment]
Thanks, that would be fantastic. I'm currently building off of master but that makes me somewhat nervous in a production environment.

**Comment by kimkulling** [comment]
Release will come soon, I promise :-)

**Comment by kimkulling** [comment]
Fixed! :-)
