### ISSUE TITLE
PLY importer bug for unknown property

### ISSUE THREAD

**Issue by dibenedetto** [assimp/assimp#617]
Whenever a property in the header of a PLY asset is not recognized, the token parser does not advance the pointer properly to the number of occurrences, causing string-to-int to report zero, thus failing at gathering properties and at calculating proper byte offsets.

The problem is in PlyParser.cpp, lines 378 to 387:

```
// parse the semantic of the element
const char* szCur = pCur;
pOut->eSemantic = PLY::Element::ParseSemantic(pCur,&pCur);
if (PLY::EEST_INVALID == pOut->eSemantic)
{
    // if the exact semantic can't be determined, just store
    // the original string identifier
    uintptr_t iDiff = (uintptr_t)pCur - (uintptr_t)szCur;
    pOut->szName = std::string(szCur,iDiff);
}
```

pCur is not moved by PLY::Element::ParseSemantic, iDiff is thus zero (-> no string copied), and trying to get the number of element occurrences fails (line 392, pOut->NumOccur = strtoul10(pCur,&pCur);) because it is strtoul10 is fed with the element name. lot of other logical errors due to wrong parsing occurs in cascade.

I temporary fixed it by advancing to the next space:

```
if (PLY::EEST_INVALID == pOut->eSemantic)
{
    // skip element name
    if (pCur != 0) while ((*pCur != '\0') && (*pCur != ' ') && (*pCur != '\t')) ++pCur;
    // if the exact semantic can't be determined, just store
    ...
}
```

m.

**Comment by kimkulling** [comment]
Thanks for reporting it, we will take care.

**Comment by kimkulling** [comment]
This one is already fixed.
