### ISSUE TITLE
Does assimp-config.cmake only find Debug libraries?

### ISSUE THREAD

**Issue by danijar** [assimp/assimp#620]
The [current `assimp-config.cmake.in`][1] appends the [debug library suffix][2] to the Assimp library regardless of the current configuration.

```
set( ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES}@CMAKE_DEBUG_POSTFIX@)
```

When using Assimp in my project in Release mode, `find_package()` reports success but the linker cannot find `libassimpd.so` since the correct file is called `listassimp.so`. Am I mistaken or is this a bug?

[1]: https://github.com/assimp/assimp/blob/4e8f7fb8027c177ca3dbc2213aba752ae927f260/assimp-config.cmake.in
[2]: http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_DEBUG_POSTFIX.html

**Comment by danijar** [comment]
Here is a workaround I'm using now.

```cmake
if (CMAKE_BUILD_TYPE STREQUAL "Release")
    string(REGEX REPLACE "d$" "" ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES})
    set(ASSIMP_LIBRARIES "${ASSIMP_LIBRARIES}" CACHE INTERNAL "" FORCE)
endif()
```

**Comment by kimkulling** [comment]
Thanks for the report. I need to check.

**Comment by kimkulling** [comment]
Debug postfix will always set to d, even if release build is enabled. I will fix that.

**Comment by danijar** [comment]
Thanks, let me know if you need help. I can do a pull request in the next days if you like.
