### ISSUE TITLE
NullFunctionError: Attempt to call an undefined function glutGet, check for bool(glutGet) before calling

### ISSUE THREAD

**Issue by mjs513** [assimp/assimp#622]
I am receiving the above error using the 3d_viewer.py script running under python 2.7.  I am using a custom model but that seems to load fine.  Below is the entire message I am receiving. I am real newbie to this and just started down the path with opengl so ....

INFO:pyassimp:Loading model:cassini.obj...
INFO:pyassimp:Done.
INFO:pyassimp:  meshes: 306
INFO:pyassimp:  total faces: 20188
INFO:pyassimp:  materials: 12
INFO:pyassimp:  bounding box:[-25.464899063110352, -31.921199798583984, -56.958000183105469] - [25.911199569702148, 27.676599502563477, 10.562000274658203]
INFO:pyassimp:Ready for 3D rendering!

Traceback (most recent call last):
  File "C:\Users\CyberMerln\Desktop\PyAssimp\scripts\3d_viewer.py", line 405, in <module>
    app = PyAssimp3DViewer(model = 'cassini.obj', w = 1024, h = 768, fov = 75)
  File "C:\Users\CyberMerln\Desktop\PyAssimp\scripts\3d_viewer.py", line 81, in __init__
    self.last_fps_time = glutGet(GLUT_ELAPSED_TIME)
  File "C:\Python27\lib\site-packages\OpenGL\platform\baseplatform.py", line 384, in __call__
    self.__name__, self.__name__,
NullFunctionError: Attempt to call an undefined function glutGet, check for bool(glutGet) before calling

If I comment all code with ref to gluGet I receive a further error - not sure if it is related:

INFO:pyassimp:Loading model:cassini.obj...
INFO:pyassimp:Done.
INFO:pyassimp:  meshes: 306
INFO:pyassimp:  total faces: 20188
INFO:pyassimp:  materials: 12
INFO:pyassimp:  bounding box:[-25.464899063110352, -31.921199798583984, -56.958000183105469] - [25.911199569702148, 27.676599502563477, 10.562000274658203]
INFO:pyassimp:Ready for 3D rendering!
INFO:pyassimp:Switched to camera <Default camera>

Traceback (most recent call last):
  File "C:/Users/CyberMerln/Desktop/PyAssimp/scripts/3d_viewer1", line 409, in <module>
    app.render()
  File "C:/Users/CyberMerln/Desktop/PyAssimp/scripts/3d_viewer1", line 277, in render
    self.recursive_render(self.scene.rootnode, shader)
  File "C:/Users/CyberMerln/Desktop/PyAssimp/scripts/3d_viewer1", line 332, in recursive_render
    self.recursive_render(child, shader)
  File "C:/Users/CyberMerln/Desktop/PyAssimp/scripts/3d_viewer1", line 320, in recursive_render
    glDrawElements(GL_TRIANGLES, len(mesh.faces) * 3, GL_UNSIGNED_INT, None)
  File "C:\Python27\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "C:\Python27\lib\site-packages\OpenGL\wrapper.py", line 764, in wrapperCall
    result = self.wrappedOperation( *cArguments )
WindowsError: exception: access violation reading 0xF26A26A0

Any help would be appreciated.

Thanks Mike

**Comment by kimkulling** [comment]
Does your glut-binding supports glutGet? The first look says to me that the function pointer to this function is noll. You can check that via: bool(glutGet) as you can see in your call stack.

**Comment by mjs513** [comment]
I added the bool(glutGet) and it did return false which is rather funny since I do have pyopengl installed which I would think supported glutGet.  With that said I did a little research and glutInit(sys.argv) or glutInit() should be added to the sample sketch (also matches the sphere.py example in PyOpenGL.  Based on the same site I found the glutInit(sys.argv) they also recommended adding the freeglut.dll to the same directory as the script if you received a '_base_glutInit' TypeError .  I incorporated this into the script and the glutGet error went away but still have the:
File "C:\Python27\lib\site-packages\OpenGL\wrapper.py", line 764, in wrapperCall
 result = self.wrappedOperation( *cArguments )
 WindowsError: exception: access violation reading 0xF26A26A0 

By the way, this got the sphere.py example working as well. 

Thanks for your help.  Do you think I should open a different issue to get that resolved?

**Comment by kimkulling** [comment]
Thanks for the feedback. I will try to fix the descriped issues. So you don't have to add another issue.

Kimmi

**Comment by mjs513** [comment]
Thanks Kimmi appreciate the support.  Think the issues seems to be the minute the number of meshes is greater than 1 the script blows up with glDrawElements.  I have models that I have tested that have any from 3 to 306 meshes.  If you want them I can post them someplace.

Thanks
Mike
