### ISSUE TITLE
Export bugs

### ISSUE THREAD

**Issue by JLouis-B** [assimp/assimp#626]
Hi,
I have loaded the file TestWuson.X in the Assimp viewer and tried to export it in some formats :
- When I export it to assbin or assxml, it seems to be good at the export, but when I try to load the file that I have just exported, in the viewer, I got error messages (for one something like "A node has no valid parent" and "aiScene::mNumMesh is 0" for the other)
- When I try to export in the DirectX format, I have a crash during the export.

Also, just a minor bug in the viewer, when I load the assets, the assxml files are not shown in the explorer with the "ASSIMP assets" filter.

I have also tried with Open3Dmod 1.1, and I have similar problems.
Works well with the other exporters that I have tested (obj and Collada).

Thanks in advance.

**Comment by acgessler** [comment]
We should look into the X export crash.

**Comment by JLouis-B** [comment]
The X export crash is fixed by PR #735

**Comment by kimkulling** [comment]
Fixed.
