### ISSUE TITLE
[question] New importer crash

### ISSUE THREAD

**Issue by DeXP** [assimp/assimp#628]
I'm wrigting new importer. I have a *.PMD file. If I'll write faces directly to OBJ I'll get something like this:
...
f 6/6 5/5 4/4
f 13/13 4/4 14/14
f 5/5 14/14 4/4
f 13/13 16/16 4/4
f 17/17 4/4 16/16
...
The vertex 4 used in 5 different triangles. But if I create 5 ASSIMP faces with use of this vertex I get this error:
aiMesh::mVertices[4] is referenced twice - second time by aiMesh::mFaces[2]::mIndices[0]
How can I fix this?

**Comment by kimkulling** [comment]
The data is optimized for rendering. The easiiest way to fix this is to create 2 vertices.

**Comment by DeXP** [comment]
@kimkulling, do you mean, use each vertice in faces list only once? And If vertex was used in 5 triangles, than create 5 vertices with the same coordinates?

How to do it differently? Than way the vertex overhead will be 3-5 times...

**Comment by kimkulling** [comment]
This is caused by the fact, that the different vertices are optimized for rendering. So when you want to render 3 trianges, which are sharing the same position but with 3 different texture coordinates you need to create 3 different vertices. That is the reason for this high number of vertices.
