### ISSUE TITLE
Mis-merge on 14-03-2015

### ISSUE THREAD

**Issue by TomMettam** [assimp/assimp#630]
Att: @acgessler 

It appears that there was a mis-merge on 14-03-2015 (SHA-1: c59878e427911315d5ef9b75c0c8ccfe551c6944) which overwrote your fix for issue #458.

**Comment by abma** [comment]
more specific, this code:

https://github.com/assimp/assimp/commit/ff4e1d9446716a676874a68b00769ddeec8a1a8f

is missing here:

https://github.com/assimp/assimp/blob/master/code/ColladaLoader.cpp#L1164

**Comment by acgessler** [comment]
Thanks for noticing. I am on vacation until Oct5, will have a look then.

@kimkulling for an earlier fix.
