### ISSUE TITLE
Option -fPIC is used even when shared library is disabled

### ISSUE THREAD

**Issue by turol** [assimp/assimp#634]
When shared library is disabled (with -DBUILD_SHARED_LIBS=0 option to CMake) it still adds -fPIC option (generate position independent code). While this is not strictly incorrect it is inefficient since among other things it wastes one register on 32-bit x86 which really doesn't have any to spare.

This is a Linux-only problem since Windows doesn't use PIC.

Probably in top-level CMakeLists.txt the condition on line 65 needs to change but I'm not entirely sure how.

**Comment by abma** [comment]
this could work:

if (CMAKE_SIZEOF_VOID_P EQUAL 8) # 64 bit
    Set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
endif()

**Comment by turol** [comment]
That adds the -fPIC option on 64-bit. It is the opposite of what we want. We want to remove it when we're 32-bit and not building a shared library. I don't have access to enough test platforms to make this change myself without risking breaking things.

**Comment by abma** [comment]
the opposite would be to add it on 32 bit, wtf?

**Comment by abma** [comment]
code wise opposite:

    if (NOT CMAKE_SIZEOF_VOID_P EQUAL 8) # 32 bit
        Set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
    endif()

**Comment by turol** [comment]
Let me clarify: -fPIC is currently added. Even when not necessary. I would like it removed.

**Comment by abma** [comment]
replace this line:
https://github.com/assimp/assimp/blob/master/CMakeLists.txt#L66

with the code i suggested. then you are pretty close to what you want.

**Comment by turol** [comment]
No, that won't do. We want (need in fact) -fPIC when building SHARED libraries but not when building STATIC libraries.

Also there's an "else" with some msvc options. I don't have msvc so I can't test my modifications won't break it.

**Comment by abma** [comment]
then

    if (NOT CMAKE_SIZEOF_VOID_P EQUAL 8 AND BUILD_SHARED_LIBS)
       Set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
    endif()

**Comment by abma** [comment]
also you didn't understand what i wrote. line 66 is

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC") 

this line must be replaced, nothing else.

**Comment by turol** [comment]
Hmm, almost but not quite. We don't want to check pointer size since when we need -fPIC we need it on both, just on 64-bit it's not quite the performance disaster it's on 32. I'll try that and send a pull request. Will you test it on msvc and mingw?

Also anyone know what os x wants and how this works in there?

**Comment by turol** [comment]
Looks like you beat me to it.

**Comment by abma** [comment]
https://github.com/assimp/assimp/pull/651

-fPIC isn't needed on 32 bit afaik.

**Comment by turol** [comment]
http://stackoverflow.com/questions/17900463/create-so-files-on-linux-without-using-pic-position-independent-code-x86-32b

Not "required" in that it will work without -fPIC but your memory usage and loading time will go way up. Probably best not merge that.

**Comment by abma** [comment]
this makes me think the addition of fPIC that should be configureable:

compiling 32bit with fPIC makes the code runs at most 5-10% slower according to the answer there.

**Comment by turol** [comment]
At least the [Debian policy manual](https://www.debian.org/doc/debian-policy/ch-files.html#fr84) states that -fPIC must be the default everywhere unless there's a very good and documented reason for it. If you want to make it configurable then it should default to on.

**Comment by abma** [comment]
> While this is not strictly incorrect it is inefficient since among other things it wastes one register on 32-bit x86 which really doesn't have any to spare.

vs. 
> At least the Debian policy manual states that -fPIC must be the default everywhere unless there's a very good and documented reason for it. If you want to make it configurable then it should default to on.

and the next response is, that -fPIC must not be used on 32 bit because of policy rule #23 of fedora?

what do you finally suggest?

**Comment by turol** [comment]
Do you have a link to the fedora policy?

**Comment by abma** [comment]
sorry, that was sarcasm :)
