### ISSUE TITLE
Broken code/cmakelist.txt on OSX

### ISSUE THREAD

**Issue by FengLinqing** [assimp/assimp#642]
"cmake -DCMAKE_BUILD_TYPE=Release ../assimp" gives me error on OSX 10.10.5:

-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Building a non-boost version of Assimp.
-- Looking for ZLIB...
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found ZLIB: optimized;/Users/feng/miniconda3/lib/libz.dylib;debug;/Users/feng/miniconda3/lib/libz.dylib
CMake Error at code/CMakeLists.txt:660 (SET_TARGET_PROPERTIES):
  set_target_properties Can not find target to add properties to: assimp

-- Enabled formats: 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SMD STL TERRAGEN 3D X
-- Disabled formats:
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found Git: /usr/local/bin/git (found version "2.5.0") 
-- Configuring incomplete, errors occurred!

This can be fixed by removing line 659-663 from code/cmakelist.txt:
if (APPLE)
  SET_TARGET_PROPERTIES( assimp PROPERTIES
    INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}"
  )
endif()

**Comment by acgessler** [comment]
Fixed by #645, please re-open if the issue persists.
