### ISSUE TITLE
Error importing obj with degenerate optimization flag

### ISSUE THREAD

**Issue by sahilagnihotri** [assimp/assimp#646]
Hei ,

I was trying to import this obj file.It gives error: Mesh is empty after removal of degenrated primitives. I had an issue with double precision before that i fixed myself. The file works fine in all the obj loaders and my very basic obj parser but fails in assimp. Any clues ?

My importer settings : 
Assimp::Importer importer;

```
importer.SetPropertyInteger(AI_CONFIG_PP_SLM_TRIANGLE_LIMIT, 65535);
importer.SetPropertyInteger(AI_CONFIG_PP_SLM_VERTEX_LIMIT, AI_SLM_DEFAULT_MAX_VERTICES);
importer.SetPropertyInteger(AI_CONFIG_PP_FD_REMOVE, 1);
importer.SetPropertyInteger(AI_CONFIG_PP_RVC_FLAGS,
    (options.discardNormals?aiComponent_NORMALS:0) |
    aiComponent_TANGENTS_AND_BITANGENTS |
    aiComponent_COLORS |
    aiComponent_LIGHTS |
    aiComponent_CAMERAS
    );
```

My reader flags:
    unsigned int readerFlags = 
        (options.discardNormals?0:aiProcess_GenNormals) |
        aiProcess_Triangulate |
        aiProcess_JoinIdenticalVertices |
        aiProcess_SortByPType |
        aiProcess_RemoveRedundantMaterials |
        aiProcess_FindDegenerates |
        aiProcess_GenUVCoords |
        aiProcess_TransformUVCoords |
        aiProcess_RemoveComponent |
        fileTypeDependentOptions;

test-data : http://mmap.myvr.net/test-data/test.zip
Thanks and Regards,
Sahil Agnihotri

**Comment by kimkulling** [comment]
YaiProcess_FindDegenerates ou can try to avoid using aiProcess_FindDegenerates. This process will look for degenerated meshes and the process tells you that after doing this one mesh is completly empty.

**Comment by sahilagnihotri** [comment]
Hi,
I know i can do that but thing is i am using it as only for optimization big dataset file. If you try to open the file in any viewer you can see the mesh. So is it a bug in finding degenerates ?

**Comment by kimkulling** [comment]
Maybe. Sometimes the parameter for degenerative triangle are not so clear.

**Comment by kimkulling** [comment]
I am not sure if we supporting here some variants already. We mustcheck if we have some open issue here.

**Comment by sahilagnihotri** [comment]
The attached file is a perfect test file as it has some degenerate triangles in begining which is like index 1 2 2 so should be marked as degenerative triangle but even if there is one such one in file. It says : Mesh is empty after removal of degenrated primitives. So error is in logic, which doesnt match with what the documentation says :P So maybe we should decide what should be correct behaviour :)

**Comment by kimkulling** [comment]
I will investigate it!

**Comment by kimkulling** [comment]
Works now.

**Comment by anandvsingh** [comment]
Can you tell me how to access Importer settings, I am getting this error **LINK : fatal error LNK1189: library limit of 65535 objects exceeded                                                                                           [%fakepath%\dependencies\assimp-3.3.1\code\assimp.vcxproj]**
