### ISSUE TITLE
IFC: Controlling the tessellation level via the API or directly in the code

### ISSUE THREAD

**Issue by handegar** [assimp/assimp#649]
I have messed around in `code/IFCCurve.cpp` and `code/IFCGeometry.cpp` trying to reduce the tessellation level when processing IFC-pipes and other parametric shapes. But alas, I have yet to succeed in reducing the number of triangles generated.

How is this actually controlled in the code, and could it be possible to add an API point/method for controlling this? I am happy to help if someone could give me some pointers on where to start digging.

**Comment by kimkulling** [comment]
At the moment there is no easy way to modify this parameter. If you still need it we need to figure out if we can use another configuration option for the IFC-loader to set the parameter before starting the tesselation.

**Comment by kimkulling** [comment]
Please reopen the issue if you are still looking for a solution. Just for me as a remarker and getting a notification.

And I am really sorry for the late response.
