### ISSUE TITLE
Undefined references in codeblocks on windows

### ISSUE THREAD

**Issue by Korpen** [assimp/assimp#650]
Downloaded the latest source from here, generated a codeblocks workspace with CMake, compiled that workspace with codeblocks/MinGW and got a libassimp.dll and a libassimp.dll.a. I included libassimp.dll.a in my codeblocks OpenGL application as well as putting the libassimp.dll with my application executable.

When compiling the OpenGL application I'm getting undefined references from the Importer class. Undefined referencesd include:
Assimp::Importer::Readfile(const char*, unsiged int)
Assimp::Importer
Assimp::~Importer
etc...

I've tried rebuilding assimp, changing the order in which libraries are included in the OpenGL application but it has not worked.

Is this because I'm doing something wrong or becuase assimp doesn't play well with MinGW/GCC? I've googled the issue but all I get is that it is a linker errors but the only solutions given there is to build it yourself and to link the right file in the right order but I still get the error.

**Comment by abma** [comment]
the automatic tests use gcc, so it basicly should work. what flags do you use to link to assimp?

**Comment by kimkulling** [comment]
Did you add the rght path to the lib as well? Flags or a screenshot would be useful.

Kimmi

**Comment by kimkulling** [comment]
Checked this again and work for me. Please reopen if this issuei is still there.
