### ISSUE TITLE
Fbx parser not work when fbx file contains "PP" type connections

### ISSUE THREAD

**Issue by oguna** [assimp/assimp#652]
I tried to parse StereoCamera.fbx (in Autodesk FBXSDK sample files), but parsing failed.

I found the cause. It contains "PP" type connections.
For example,

```
    C: "OO",786204432,784757920
    C: "OP",487083904,785243760, "RightCamera"
    C: "OP",487085712,785243760, "LeftCamera"
    C: "OP",786203536,487085712, "FilmOffsetX"
    C: "PP",785243760, "FilmWidth",487085712, "FilmWid
```

Now, `Assimp::Document::ReadConnections()` (FBXDocument.cpp) can parse "OP" or "OO" types connection, but "PP" type conenctions cannot be parsed.

**Comment by otgerp** [comment]
Solved: now they are ignored, so the parsing does not fail anymore.

**Comment by kimkulling** [comment]
Great, I will close this issue.
