### ISSUE TITLE
Can't use with vs2015 universal apps

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#653]
With universal apps (specifically the dx12 template in vs2015) assimp won’t work. Can anyone else confirm this? I have tried a blank universal app template as well and it won’t work. It runs fine with a win32 project though.

Check http://sourceforge.net/p/assimp/discussion/817654/thread/e4592ba3/?limit=25#6ffc

**Comment by kimkulling** [comment]
Try this out. Hopefully it helps:
http://codingadventures.me/2015/07/21/deploying-assimp-to-android-using-visual-studio-and-android-ndk/

**Comment by TAMHAN** [comment]
Hello Folks,
sorry to chime in here, but this error also occurs.

I created a somewhat complex app which actually USES Assimp, and get the following error both on Debug and Release:
'SUS3DApp1.exe' (Win32): Loaded 'D:\DevelopmentFiles\6c43d50b-5fce-4ef4-be43-638b989ef78aVS.Release_x64.TAMHAN\SUS3DApp1.exe'. Symbols loaded.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\kernel32legacy.dll'. Cannot find or open the PDB file.
'SUS3DApp1.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
The thread 0x8 has exited with code -1073741515 (0xc0000135).
The thread 0x6b0 has exited with code -1073741515 (0xc0000135).
The program '[4312] SUS3DApp1.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

IMHO, basic programs succeed in release mode and fail in debug mode as VS2015 strips away not actively used DLLs when creating a Release build...so if there is no actual example code using assimp, the release app looks like it would be working.

Tam

**Comment by kimkulling** [comment]
Have your placed all dependend libs in your execution path? And is your working directory during the debug run configured correctly? This is a typical sign that some dependend dlls could not be loaded because they could not be found.

**Comment by TAMHAN** [comment]
Hello Folks,
I simply downloaded the assimp package from NuGet in the first try.

In the second attempt, I tried it with a hand compiled version of the 
library but also failed...

Tam

**Comment by gsantopaolo** [comment]
hi, any chance to see assimp on uwp anytime soon or to get any understandable workaround?

**Comment by kimkulling** [comment]
I hope so. I haven't work on this issue until now. Do you have some kind of simple project to reproduce your issue. This would help a lot!

**Comment by gsantopaolo** [comment]
just download and try [this uwp project](https://github.com/gsantopaolo/AssimpUWP) It is a newly created project where I added the Assimp.Net nuget package reference. 
Go to MainPage.xaml.cs ln 28 and 29.
You will notice that the reference seems correctly added but the library is not accessible...

**Comment by alezz94** [comment]
Hey guys,
did you find any solution to this error?

**Comment by mrjfalk** [comment]
I also tried to use Assimp.NET for my UWP C# project, but got the same result as you. From what I understand dynamically loading DLL's is not supported in UWP (see [this question](https://social.msdn.microsoft.com/Forums/en-US/2c479f72-c3c8-41be-a052-db6f898deddc/uwploading-external-dll?forum=wpdevelop) for example)

I've successfully been able to compile Assimp (except 2 loads) as a Windows Runtime Component (x86, x64, and ARM), and I've also wrapped a parts of the library in C++/CX ref classes, so they are accessible from C# in UWP as well and use the UWP file API. So I can confirm this is a way to get it working in UWP.

If there is an interest I will probably open source this code sometime in the future.

**Comment by kimkulling** [comment]
This would be really great for all the user. I will try to recompile assimp I guess to get a better understanding.

**Comment by ranveeraggarwal** [comment]
Hello, do we have a way of making assimp work with UWP now? 
I am trying to load a mesh onto a Hololens (using a C++ Universal Windows template). Has this been tried before? If not, I will post a link if and when I am able to. But first, I need to get assimp working with a Universal app.
