### ISSUE TITLE
Quaternions should be normalised in the animations

### ISSUE THREAD

**Issue by JLouis-B** [assimp/assimp#654]
Hi,

Assimp has a bug with some animations, you can find the description of the bug, test case model and fix here : 
http://irrlicht.sourceforge.net/forum/viewtopic.php?f=7&t=48908
It's a report for the DirectX loader of the Irrlicht engine, but there is exactly the same bug in Assimp.
You can find a test case model on the topic, and you can see that the animation doesn't work correctly in Assimp viewer/Open3Dmod, but works well with the viewer of the Direct SDK.

**Comment by kimkulling** [comment]
Shall be fixed.
