### ISSUE TITLE
How to Hello Word

### ISSUE THREAD

**Issue by elect86** [assimp/assimp#657]
I'm using Netbeans and I am not really an expert in C/C++ language, but at least I managed to clone it and compile it successfully ^^

I am trying to create a small Hello Word program in order to debug better Assimp to port it to [java](https://github.com/elect86/jAssimp).

I imported the `assimp\include` and wrote the simplest main

The problem is that I get this error on the [Importer instantiation](https://github.com/elect86/Test/blob/master/main.cpp#L19):
```
:Importer::Importer()'

 relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Assimp::Importer::Importer()'
----
```

What is the problem?

**Comment by kimkulling** [comment]
You need to link against assimp library for fix this issue ( -L<path_to_lib> -lassimp ).
