### ISSUE TITLE
Cameras and lights and aiNode->mTransformation

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#658]
I have noticed that when it comes to import a camera or a light, its
position and direction are encoded within the transformation matrix, which
is good for child nodes.
So aiLight->mPosition is always (0, 0, 0) and similarly aiLight->mDirection
is (0, 0, -1). I could test only Collada files exported through 3D Studio
Max. Is it true in general, even for other formats or modelling programs?

Check https://sourceforge.net/p/assimp/discussion/817654/thread/79f55300/?limit=25#5471

**Comment by promethe42** [comment]
Related to #643 I think.

**Comment by kimkulling** [comment]
OK, duplicated. Thanks for the hint.

**Comment by vd3d** [comment]
I have post something on StackOverflow... seems nobody leave here ?

http://stackoverflow.com/questions/35536994/assimp-import-camera
