### ISSUE TITLE
DLL search path cannot be explicitely updated.

### ISSUE THREAD

**Issue by Tcll** [assimp/assimp#661]
the common way I've found (experimenting with freetype-py in collaboration with the devs) to use a custom DLL search path (which is better than my last suggestion of including the dll with pyassimp) is to update os.environ['PATH'] with the custom directory like so:

```
import os
DLL_directory = os.path.sep.join( ( os.getcwd(), 'DLLS','' ) ) # the '' dynamically adds an extra \ or / like other directories
os.environ['PATH'] = os.pathsep.join((os.environ['PATH'],DLL_directory))

import pyassimp
```

I can't seem to fix this one as easy as I did with my last suggestion...

**Comment by Tcll** [comment]
ok, the dll wouldn't even work in the CWD... just found out why and fixed:

helper.py
```
def search_library():
    """Loads the assimp-Library.
    
    result (load-function, release-function)    
    exception AssimpError if no library is found
    
        """
    #this path
    folder = os.getcwd() #os.path.dirname(__file__)
```
---snip---

so I got that much working...

the problem is Wine and __file__
(unless you guys wanted it to search pyassimp instead of the CWD)

>>> os.path.dirname(__file__)
\home\tcll\Desktop\modern 3D viewer\pyassimp
>>> os.getcwd()
Z:\home\tcll\Desktop\modern 3D viewer

**Comment by kimkulling** [comment]
You can use a special script to start your application, which adds the dll path to the PATH before starting the python-app.

**Comment by Tcll** [comment]
Read the first comment

**Comment by kimkulling** [comment]
Ah, thanks a lot for the hint.

**Comment by meshula** [comment]
In a plain old windows command shell, I couldn't make the cwd method work, even if running in the same directory as the DLL. I had a look at helper.py and saw the bit about dirname(__file__)... Accordingly, I copied the assimp and zlib dll's to C:\Python27\lib\site-packages\pyassimp where the scripts are installed and now pyassimp works. I'm not sure if this is a terrible solution in general, but it works for my set up.
