### ISSUE TITLE
[port] GLFW modern 3D viewer

### ISSUE THREAD

**Issue by Tcll** [assimp/assimp#662]
note: my dev-group is currently still testing this, but I don't recommend this for a PR or anything...

https://copy.com/uRZUHfk6i9gXMxt4
tested using python27 x86 on Wine.

improvements:
- runs at 73-75FPS (my refresh rate) where it was 61-72FPS with SDL.
- added a tk file-open dialog when not loading from the command line.
- optimized event codes to event handler functions (processed per event rather than per frame)

although the code is still very disgusting:
- everything's still wrapped in a class
- uses numpy
- could be optimized alot better
- left dirty port-comments and removed code

also, it's missing fullscreen support, but at least you can make it resizable now without having the GL context deleted :)
(I hate SDL with a passion)

if you'd like to download, I'd recommend improving it before adding it to the examples.
(you can also wait for me to improve it before downloading, it'll update as I edit) ;)

**Comment by Tcll** [comment]
update:
- slightly optimized from my last edit.
- removed dirty port-code
- restructured code to be more GLFW-like rather than contained in a class
- cleaned up the code and combined many functions into classified base-functions

not finished yet though, I can still do alot more cleanup and still need to segregate the modules:
from:
`from OpenGL.GL import *`
to:
`from OpenGL import GL`

note: ^ this is a very good practise, especially when writing example-code.
but even still, it helps to classify code, which is very useful in keeping track of code.

for example:
`def load_model(path, postprocess = aiProcessPreset_TargetRealtime_MaxQuality):`
it would tell you where `aiProcessPreset_TargetRealtime_MaxQuality` comes from.

**Comment by Tcll** [comment]
update:
- removed most numpy code (2 mat() calls left) (used `array.array('f')` for the vbo)
- added resize event and glViewport() calls
- removed filthy glFrustum and replaced it with gluPerspective (re-enabled more like)
- improved zoom and strafe speed

removal of numpy is important!

all that's left:
c = (-1 * numpy.mat([r[:3] for r in m[:3]]) * numpy.mat(m[3][:3]).T)

it currently runs a little slower due to 2D matrix indexing because `sum( buffer, [] )` and `numpy.array()` are not very good friends.
(I can fix that once numpy is removed completely)

**Comment by Tcll** [comment]
update:

- removed numpy

pyassimp requires numpy though, so I'm patching it to be as smart as pyopengl.
**you will NOT need numpy to run this example**

I mean what I say, numpy is a cancer and has everyone fooled.
numpy.array() is not much faster (if at all) than list()

I've tested this on a file data importer and manager I wrote...
for that, it was actually slower than list()
array.array('B') is the fastest array for that purpose.

and for this example viewer, for the vbo, I'd put money down (if I had any) that array.array('f') is faster.
(it's certainly faster than list())

**Comment by Tcll** [comment]
update:

- added transpose function

for pyassimp:

- removed numpy (not really, it will return numpy arrays if you have numpy, otherwize it will return lists)
- added a matrix inversion function and matrix multiplication arithmatic directly to helper.py

I will submit a PR here soon.

the viewer now runs topping out at 77 FPS for the test model, though it's a little more choppy, bottoming at 72 FPS (needs optimization)

OT:
does pyassimp support tri-fans, quad-strips, and polygons??
if not, model exports will be much larger than imports of the same format.

**Comment by kimkulling** [comment]
Could you create a pull request for that, please? The link is dead at the moment. And sorry for the delayed answer, I am a little bit busy.

**Comment by Tcll** [comment]
sorry for the dead link, there was a small mishap with the sync on a bad network which messed up everything before I lost internet...

I've updated the source far beyond my previous edits anyways...
but currently though, I've removed numpy checks in favor of array.array, meaning (due to PyOpenGL) it will break if you have numpy installed.

I should also mention, from some old info I've ran on for a long time, I've removed the ARB VBO support and did things manually with basic GL array support.
(I've grown up knowing ARB support to be pretty bad, despite the fact most games use it)
^ although the same can be said for SDL vs GLFW... heh

I'll be sure to post an update when I'm able to ;)
heck, it controls a little more like Minecraft now ;)
(also fixed up the aspect ratio (NEVER use int values for W/H))

**Comment by Tcll** [comment]
not entirely sure a pull request would be good here...
I've done quite a bit to the code (first to clarify and restructure, next to improve performance).

I'd recommend you test my works first before making any sort of updates.
https://www.dropbox.com/s/nw7ki6bc0hokkug/modern%203D%20viewer.zip?dl=0
I've also included "Tcll.txt" which contains info about my programming prefs, which may cause issues when you test in a non-portable environment.
(I'm not sure if I've made test-edits to pyassimp, so be careful when removing that)

also, the copy link won't be returning...
sadly, the service has been discontinued -.-
so yea, I'm stuck with the Gov't-infested DropBox service until I can find something more secure again...

**Comment by Tcll** [comment]
slight update (major performance improvement) to the above source:
https://www.dropbox.com/s/z8a8v3urgr2dtdr/3d_viewer.py?dl=0
not fully finished, but most of the major frame stuff has been taken care of.

also made the original numpy.array method a little more performative, so it's closer to the array.array method's performance.

**Comment by kimkulling** [comment]
What do you think: you could create your own repository and we will add a link showing to it? If this would be ok for you: just reopen the issue.

With best regards,
Kim
