### ISSUE TITLE
Error importing an OpenGEX file exported from Blender

### ISSUE THREAD

**Issue by IkerGimenez** [assimp/assimp#665]
While trying to import an OpenGEX file using the C API, the following error occured:

![asssimperror](https://cloud.githubusercontent.com/assets/6117986/10176994/953578ea-66ac-11e5-9311-42db232f7723.png)

I don't know if it's the file's fault or the importer, I have not tried with another file. Built from d06945f17e616b2fa633aa85c02ff03c0c01e14a this commit.

**Comment by IkerGimenez** [comment]
The importer seems to have a problem with my MaterialRef structure for some reason:

GeometryNode $node2
{
	Name {string {"Plane"}}
	ObjectRef {ref {$geometry1}}
	MaterialRef (index = 0) {ref {$material1}}

	Transform
	{
		float[16]
		{
			{1.0, 0.0, 0.0, 0.0,
			 0.0, 1.0, 0.0, 0.0,
			 0.0, 0.0, 1.0, 0.0,
			 0.0, 0.0, 0.0, 1.0}
		}
	}
}

The console prints out the following right after MaterialRef:

Error:Invalid token 0, ) expected.
Error:Invalid token ), { expected.'

So I think (index = 0) is not being parsed correctly for some reason...

**Comment by IkerGimenez** [comment]
It also fails to read a light object's properties... 

     LightObject $light1 (type = "point", shadow = false)		// Point
     {
	     Color (attrib = "light") {float[3] {{1.0, 1.0, 1.0}}}

	     Atten (curve = "inverse_square")
	     {
		     Param (attrib = "scale") {float {5.0}}
	     }
     }

**Comment by kimkulling** [comment]
Please try again with the latest version of Asset Importer Lib. I just uploaded the latest version of the openddl-parser, where this bug is already fixed.
