### ISSUE TITLE
New importer for glTF

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#673]
See https://github.com/KhronosGroup/glTF/blob/master/specification/README.md

**Comment by vinjn** [comment]
+1

**Comment by acgessler** [comment]
+1, also helps drive adoption of glTF. Maybe we can reach out to them and see if they're interested in helping out.

**Comment by vinjn** [comment]
There is a related discussion - https://github.com/KhronosGroup/glTF/issues/456

**Comment by petr-stety-stetka** [comment]
+1

**Comment by OtgerRP** [comment]
I had made a glTF loader in C++ for my own needs. I could adapt and add it, if there's not already work being done on it.

**Comment by kimkulling** [comment]
We have one ( please check the following pull request to learn more about the implementation: https://github.com/assimp/assimp/pull/697 )

Kimmi
