### ISSUE TITLE
Changing mNum* member variables from unsigned int to size_t

### ISSUE THREAD

**Issue by sherief** [assimp/assimp#68]
Assimp tends to use std::vector<>s and other containers with size_t sizes internally, and size_t seems to closely match the platform's limits on 32-bit and 64-bit platforms. Storing size_t variables in member variables like aiScene's mNumMeshes is one of the major sources for compiler warnings in the codebase. 

Can you consider moving the mNum* member variables to size_t? In addition to the potential future-proofing for really large data sets possible on 64-bit systems a lot of potential conversion-related bugs and corresponding compiler warnings can be removed. 

I wouldn't mind doing the majority of the work, but I need to make sure it would potentially be accepted into the mainline branch before I proceed.

**Comment by rob100** [comment]
Usage of size_t would be really nice. There are about 300 warnings with Visual Studio based on this.
The branch is nearly 2 years old, I guess there will be no more commits from sherief?
I could offer my help with this issue. The question is: Is it better to start over? I guess merging the old branch would be really painful.

**Comment by sherief** [comment]
I started working on something else at the time, but any changes to fix this issue would be welcome. Merging old branches won't be fun.

**Comment by turol** [comment]
Note that since int and size_t are different sizes on 64-bit this change breaks the ABI. On Linux this means you should bump the soname of the shared library. On windows things will probably just break. So if you end up doing this you should bump major version to 4.0.

**Comment by sherief** [comment]
Good point, thanks for the heads up.

**Comment by kimkulling** [comment]
Deprecated
