### ISSUE TITLE
Building for android: Documentation is missing

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#684]
We need to document how to use AssetImporterLib for android!

**Comment by jeannekamikaze** [comment]
I have written a quick reference on compiling C/C++ libs for Android that can be reached here:

http://shellblade.net/android-cpp.html

The page is more of a central repository of links to other pages than a self-contained manual, but should nevertheless help.

In this other post, I explain how to write a custom IOSystem and IOStream to read assets from an application's APK file:

http://shellblade.net/android-assimp.html

**Comment by kimkulling** [comment]
See: https://github.com/assimp/assimp/blob/master/port/AndroidJNI/README.md
