### ISSUE TITLE
matrix4x4 operator[] is broken

### ISSUE THREAD

**Issue by mintar** [assimp/assimp#685]
The operator[] of matrix4x4 gives me nonsense values, probably from uninitialized memory. According to the comment in [matrix4x4.inl:243](https://github.com/assimp/assimp/blob/c318d648ff73aa2e32b783709d69740ac3e8c072/include/assimp/matrix4x4.inl#L243), that's a known problem.

Code snippet that reproduces the problem:

    aiMatrix4x4 transform = node->mTransformation;

    std::cout <<  "  BROKEN: " << std::endl
              << std::fixed
              << "[ " << *transform[0]  << " \t" << *transform[1]  << " \t" << *transform[2]  << " \t" << *transform[3]  << std::endl
              << "  " << *transform[4]  << " \t" << *transform[5]  << " \t" << *transform[6]  << " \t" << *transform[7]  << std::endl
              << "  " << *transform[8]  << " \t" << *transform[9]  << " \t" << *transform[10] << " \t" << *transform[11] << std::endl
              << "  " << *transform[12] << " \t" << *transform[13] << " \t" << *transform[14] << " \t" << *transform[15] << " ]" << std::endl<std::endl;

    std::cout << "  WORKING:" << std::endl
              << std::fixed
              << "[ " << transform.a1 << " \t" << transform.a2 << " \t" << transform.a3 << " \t" << transform.a4 << std::endl
              << "  " << transform.b1 << " \t" << transform.b2 << " \t" << transform.b3 << " \t" << transform.b4 << std::endl
              << "  " << transform.c1 << " \t" << transform.c2 << " \t" << transform.c3 << " \t" << transform.c4 << std::endl
              << "  " << transform.d1 << " \t" << transform.d2 << " \t" << transform.d3 << " \t" << transform.d4 << " ]" << std::endl;

Output:

      BROKEN:
    [ 1.000000 	0.000000 	0.000000 	0.000000
      -6383549033750467933401407029248.000000 	-6383573212266860225984901152768.000000 	-322887.250000 	-322887.281250
      -322889.093750 	-6444387016696754531989320630272.000000 	-322887.250000 	0.000000
      0.000000 	0.000000 	0.000000 	0.000000 ]
    
      WORKING:
    [ 1.000000 	0.000000 	0.000000 	0.000000
      0.000000 	1.000000 	0.000000 	0.000000
      0.000000 	0.000000 	1.000000 	0.000000
      0.000000 	0.000000 	0.000000 	1.000000 ]

**Comment by mintar** [comment]
Some system information:

    distribution:     Ubuntu 14.04.3 LTS
    assimp version:   3.0~dfsg-2 (from official Ubuntu repos)
    gcc:              4.8.4
    CMAKE_BUILD_TYPE: Debug
    kernel:           3.16.0-52-generic (x86_64)

**Comment by kimkulling** [comment]
Thanks a lot for the report, I will fix that issue!

**Comment by kimkulling** [comment]
Checked this: the []-operator will return a pointer showing to the first entry of the row of the matrix. I added a test to show this.
You can use it as following:
```
TEST_F( utMatrix4x4Test, indexOperatorTest ) {
    aiMatrix4x4 m;
    float *a0 = m[ 0 ];
    EXPECT_FLOAT_EQ( 1.0f, *a0 );
    float *a1 = a0+1;
    EXPECT_FLOAT_EQ( 0.0f, *a1 );
    float *a2 = a0 + 2;
    EXPECT_FLOAT_EQ( 0.0f, *a2 );
    float *a3 = a0 + 3;
    EXPECT_FLOAT_EQ( 0.0f, *a3 );

    float *a4 = m[ 1 ];
    EXPECT_FLOAT_EQ( 0.0f, *a4 );
    float *a5 = a4 + 1;
    EXPECT_FLOAT_EQ( 1.0f, *a5 );
    float *a6 = a4 + 2;
    EXPECT_FLOAT_EQ( 0.0f, *a6 );
    float *a7 = a4 + 3;
    EXPECT_FLOAT_EQ( 0.0f, *a7 );

    float *a8 = m[ 2 ];
    EXPECT_FLOAT_EQ( 0.0f, *a8 );
    float *a9 = a8 + 1;
    EXPECT_FLOAT_EQ( 0.0f, *a9 );
    float *a10 = a8 + 2;
    EXPECT_FLOAT_EQ( 1.0f, *a10 );
    float *a11 = a8 + 3;
    EXPECT_FLOAT_EQ( 0.0f, *a11 );

    float *a12 = m[ 3 ];
    EXPECT_FLOAT_EQ( 0.0f, *a12 );
    float *a13 = a12 + 1;
    EXPECT_FLOAT_EQ( 0.0f, *a13 );
    float *a14 = a12 + 2;
    EXPECT_FLOAT_EQ( 0.0f, *a14 );
    float *a15 = a12 + 3;
    EXPECT_FLOAT_EQ( 1.0f, *a15 );
}
```

**Comment by mintar** [comment]
Ah, so the bug was on my side. Thanks for checking!

**Comment by kimkulling** [comment]
You will get a NULL in case of a misuse.
