### ISSUE TITLE
FBX Mesh is not loaded correctly if UVIndex includes -1 values

### ISSUE THREAD

**Issue by dankex** [assimp/assimp#695]
The following element in a node "Geometry: 1079556377056, "Geometry::", "Mesh" {" is not processed correctly. When this LayerElementUV element is present in a mesh, the mesh is omitted totally, and the node has no mesh. It can be seen from both the dump file and the loaded model.

```
       LayerElementUV: 0 {
            Version: 101
            Name: "map1"
            MappingInformationType: "ByPolygonVertex"
            ReferenceInformationType: "IndexToDirect"
            UV: *516 {
                a:  ................
            }
            UVIndex: *512 {
                a:  ................
            }
        }
```

The issue happens when UVIndex include the value -1. The same file can be imported with FBX review.

**Comment by rickomax** [comment]
I've fixed this in code. I'll make a pull-request later.
Thank you!

**Comment by kimkulling** [comment]
Fixes were merged, I will close the issue-
