### ISSUE TITLE
readFileFromMemory 100 char limit?

### ISSUE THREAD

**Issue by mrath** [assimp/assimp#698]
I just lost quite a bit of time finding out why my meshes weren't imported in MoveIt! for ROS (which uses assimp), and tracked the error down to Importer::ReadFileFromMemory. 

For some reason, it is checked that the file path to load is no longer than 100 characters. Is this a feature of assimp, is there a reason for the limit, or could it be changed to, say, 200?

Check occurs here: https://github.com/assimp/assimp/blob/master/code/Importer.cpp#L494

**Comment by kimkulling** [comment]
Sould work now.
