### ISSUE TITLE
Migrate completely away from SourceForge?

### ISSUE THREAD

**Issue by erlend-sh** [assimp/assimp#700]
Given [SourceForge's less-than-stellar reputation](http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/) (many adblockers now warn about adware when visiting any sourceforge.org domain), combined with the fact that all Assimp activity occurs on GitHub nowadays, it seems to me it would make a lot of sense to move all Assimp resources in their entirety over to GitHub.

I'm mostly talking about moving the http://assimp.sourceforge.net/ over to a GitHub domain like assimp-web.github.io or assimp.org, and updating the contents to point to the appropriate places on github.com/assimp/assimp.

Putting some redirect notices up on http://sourceforge.net/projects/assimp/ wouldn't hurt either.

---

**Update:**

Yeah, Sourceforge doesn't seem to be a domain you want to associate yourself with these days:

https://news.ycombinator.com/item?id=10668546

**Comment by LegalizeAdulthood** [comment]
Any reason not to just host the web pages from sourceforge as github pages at http://assimp.github.io/ ?

**Comment by erlend-sh** [comment]
I thought that's what was happening already, in https://github.com/assimp/assimp-web

Just that it's still pointing to the old SourceForge domain, instead of a github.io one, or just plain assimp.org (which @kimkulling told me he bought today ;) )

**Comment by acgessler** [comment]
The git repo is basically just a copy. It may not even be the very latest up to date version of the website, but it certainly works as a starting point and future location.

**Comment by kimkulling** [comment]
Sould be fixed now, please report any issues here!

**Comment by kimkulling** [comment]
Checkout http://www.assimp.org

**Comment by erlend-sh** [comment]
:+1: :fireworks:
