### ISSUE TITLE
Is there a way to use custom IOSystem in Jassimp?

### ISSUE THREAD

**Issue by dankex** [assimp/assimp#711]
I know AndroidJNI can load files from android asset manager, but it is written in C++ and only works for Android native applications. I would be nice if custome IOSystem can be used for Jassimp as well.

**Comment by kimkulling** [comment]
Sure, you could check the following issue report. There you can find a good way how to define your own IOSystem: https://github.com/assimp/assimp/issues/822

**Comment by danke-sra** [comment]
Thanks. That is a good example.

**Comment by dankex** [comment]
Thanks. That is a good example.
