### ISSUE TITLE
Building glTFExporter.cpp.o error  Mac OS X 10.11.2.  Does not compile with most recent version of rapidjson either, so there's probably an issue with assimp's use of rapidjson, or rapidjson needs to be extended?

### ISSUE THREAD

**Issue by coderextreme** [assimp/assimp#723]
[ 71%] Building CXX object code/CMakeFiles/assimp.dir/glTFExporter.cpp.o
In file included from /Users/johncarlson/Source/assimp/code/glTFExporter.cpp:61:
In file included from /Users/johncarlson/Source/assimp/code/glTFAssetWriter.h:51:
In file included from /Users/johncarlson/Source/assimp/code/glTFAsset.h:59:
/usr/local/include/rapidjson/document.h:1065:22: error: call to constructor of
      'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is ambiguous
        GenericValue v(value);
                     ^ ~~~~~
/usr/local/include/rapidjson/document.h:1136:16: note: in instantiation of
      function template specialization
      'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
      >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
/Users/johncarlson/Source/assimp/code/glTFAssetWriter.inl:108:13: note: in
      instantiation of function template specialization
      'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
      >::AddMember<unsigned long>' requested here
        obj.AddMember("byteLength", b.byteLength, w.mAl);
            ^
/usr/local/include/rapidjson/document.h:510:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_(), flags_(kN...
             ^
/usr/local/include/rapidjson/document.h:517:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_(), flag...
             ^
/usr/local/include/rapidjson/document.h:524:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_(), fla...
             ^
/usr/local/include/rapidjson/document.h:538:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_(), fl...
             ^
/usr/local/include/rapidjson/document.h:549:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_(), flags_...
             ^
1 error generated.
make[2]: *** [code/CMakeFiles/assimp.dir/glTFExporter.cpp.o] Error 1
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2

**Comment by coderextreme** [comment]
Please provide a GenericValue constructor with parameter size_t in include/rapidjson/document.h, if possible.  Thanks!

**Comment by kimkulling** [comment]
We will try :-).

**Comment by coderextreme** [comment]
I am not sure why you want to use size_t for byteLength.  Seems really system dependent, but I can the advantages.

John

**Comment by coderextreme** [comment]
I've got a patch that copies the uint64_t constructor to an unsigned long constructor.  I can issue a pull request, since all unit tests pass, but I'm not sure if they code is being tested, and  I'm not sure if the code is right, since it's been a long time since I programmed C or C++

**Comment by coderextreme** [comment]
Pull request issued.

**Comment by Polytonic** [comment]
This change seems to have broken assimp for me under Mac OSX 10.11.2. I rolled back to 9409ce3 and things seem to be working there. 

```
.../assimp/code/ ../contrib/rapidjson/include/rapidjson/document.h:561:14: error: 
      constructor cannot be redeclared
    explicit GenericValue( size_t u ) RAPIDJSON_NOEXCEPT : data_(), flags_( kNumberUintFlag ) {
             ^
.../assimp/code/../contrib/rapidjson/include/rapidjson/document.h:550:14: note: 
      previous declaration is here
    explicit GenericValue(unsigned long u64) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberUint64Flag) {
```

Compiler:
```
$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

**Comment by coderextreme** [comment]
Can someone figure out an #ifdef?  Thanks!

**Comment by joelteply** [comment]
use this:

#if defined(__APPLE__)
    //! Constructor for unsigned long value.
    explicit GenericValue(unsigned long u64) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberUint64Flag) {
        data_.n.u64 = u64;
        if (!(u64 & RAPIDJSON_UINT64_C2(0x80000000, 0x00000000)))
            flags_ |= kInt64Flag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x00000000)))
            flags_ |= kUintFlag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
            flags_ |= kIntFlag;
    }

#elif !defined(__x86_64__) && !defined(__arm64__)
    //! Constructor for size_t value.
    explicit GenericValue( size_t u ) RAPIDJSON_NOEXCEPT : data_(), flags_( kNumberUintFlag ) {
        data_.n.u64 = u;
        if ( !( u&0x80000000 ) )
            flags_ |= kIntFlag|kInt64Flag;
    }
#endif

**Comment by joelteply** [comment]
note the use of #elif instead of what was there before
