### ISSUE TITLE
STL regression tests are broken

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#724]
Please check https://travis-ci.org/assimp/assimp/jobs/97420704 and search for [FAILURE]. We need to update the suites I guess.

**Comment by acgessler** [comment]
I guess it might be more sensible to disable the explicit regression failures for now.

It would be nice to have some kind of a GUI to approve changes when a PR is made.

**Comment by kimkulling** [comment]
Do agree, something Smalltalk would be enough

Alexander Gessler <notifications@github.com> schrieb am Sa., 19. Dez. 2015
23:38:

**Comment by acgessler** [comment]
Or, we enforce that people update the regression tests. It's not very hard to do, you just run the script and commit the result and add it to the PR.

**Comment by kimkulling** [comment]
Strongly depends. Worked quite a while to bring it up ...

Alexander Gessler <notifications@github.com> schrieb am So., 20. Dez. 2015
15:54:

**Comment by acgessler** [comment]
I wonder if we can get this added to Travis: the Travis build would execute the regression test suite, determine the list of changed files, re-generate the them, create a commit and push it up into the branch. This will trigger a re-execution of that branch, which should pass. The commit description would include the list of files changed.

Pushing code from within Travis should be no problem. However, getting credentials for the Github account that sent the PR is troublesome.

What we could do:
 - Create a new github account and add it to the assimp repository.
 - We can pass the password for the account into Travis using "encrypted" environment variables (see http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci)
 - When Travis runs, we can obtain credentials for the Github account.
 - We create a new branch on the main assimp repository that mirrors the pull request.
 - We push a commit that updates the regression test suite onto that branch.

Then we just merge the new branch (and close the old PR with a reference to the new branch).

I'll have a look into whether this is feasible. Any thoughts?

**Comment by kimkulling** [comment]
I do not think that ths is a good idea. We need people to do the regression tests and validate their results. But at the moment this is not so easy. The tools are available but it took me 1 hour to run them last time.
Let's use the regression test suite to validae our results. But lets work on the workflow first, please!

**Comment by acgessler** [comment]
That's what I am proposing: when I send a PR that changes the output of the regression test suite, I will automatically get a modified version that lists the changes for me to review. That modified version is a regular branch that we can merge. If we merge it, we approve the changes, else we reject.

**Comment by kimkulling** [comment]
Ah, misunderstanding on my side. That sounds right for me.

**Comment by kimkulling** [comment]
Seems to be fixed.
