### ISSUE TITLE
Opacity bug when exporting

### ISSUE THREAD

**Issue by lepalom** [assimp/assimp#727]
Here is attached an example using assimp 3.2. We use the linux version. To compile it run:

g++ assimp.cpp -o assimp-ex `pkg-config --libs assimp`

The program creates an scene with on red triangle and random opacity. Then, we export the scene to ALL  the available formats that can Assimp. 

After, we read the exported file and show if when we import it we obtain the same opacity value. We have this result:

......
[collada] I expected opacity 0.0826949 but found 0.917305
[x] I could not read opacity property
[stp] Error at importing from scene.stp: No suitable reader found for the
file format of file "scene.stp".
[obj] I expected opacity 0.0826949 but found 1
[stl] I could not read opacity property
[stlb] I could not read opacity property
[ply] I could not read opacity property
[plyb] I could not read opacity property
[3ds] I expected opacity 0.0826949 but found 1
[assbin] OK!
[assxml] I expected opacity 0.0826949 but found 1

The main error for us is that, for collada,  we export an opacity with value X and we read (1-X)
Attached the file example.

[asssimp.cpp.zip](https://github.com/assimp/assimp/files/68213/asssimp.cpp.zip)

**Comment by kimkulling** [comment]
Thanks a lot for the report and sorry for my ate response. We will investigate this issue. This defects sounds suspicious. Maybe some kind of post processing? We will see.

**Comment by kimkulling** [comment]
Have you tried to look via a debugger inside of your opacity value generated by your program. For me it looks suspicious that there are so much 1.0 values which is normally the default value for opacity in our material.

**Comment by kimkulling** [comment]
I created a untitest from your code to reproduce the issue.

**Comment by jiangcaiyang** [comment]
Hi, in Assimp 3.2, with aiProcess_CalcTangentSpace | aiProcess_Triangulate | aiProcess_JoinIdenticalVertices | aiProcess_SortByPType, the opacity information are lost, some dae files ( file produced by assimp export ) defaults to 1, some dae files ( originally exported by FBX COLLADA exporter ) are read as 0. So the result is suspicious, however, V 3.0 does not cause this problem.

**Comment by kimkulling** [comment]
Fixed.
