### ISSUE TITLE
OpenGEX exporter, #ifndef's #endif's problems

### ISSUE THREAD

**Issue by GameCy** [assimp/assimp#730]
1. 
The OpenGEXExporter.cpp file is missing ifndef defines  (to exclude from compilation)
#ifndef ASSIMP_BUILD_NO_EXPORT
#ifndef ASSIMP_BUILD_NO_OPENGEX_EXPORTER
........
endif
endif

2.
OpenGEXExporter.h is using 
#ifndef ASSIMP_BUILD_NO_OPENGEX_IMPORTER  
but it should  be
#ifndef ASSIMP_BUILD_NO_OPENGEX_EXPORTER

**Comment by kimkulling** [comment]
Should be fixed now
