### ISSUE TITLE
AssetImporter cannot import DAE file with skeleton animation

### ISSUE THREAD

**Issue by yushli** [assimp/assimp#731]
Details can be found in the following link:
https://github.com/urho3d/Urho3D/issues/1118

**Comment by yushli** [comment]
More investigation shows that the offsetMatrix of the bones generated by importing DAE file are pretty big.
like
{
"name": "Bip01_x0020_Spine",
"parentIndex": 3,
"initialPosition": [0.14604699611663818, 0.0053820000030100346, -0.000018000000636675395],
"initialRotation": [0.9979892373085022, 0.06218252331018448, 0.011717814020812511, -0.0036811514291912317],
"initialScale": [0.9999997019767761, 1.0000004768371582, 0.9999998807907104],
"offsetMatrix": [58196376, 58196376, -58196376, 58196376, 76122608, 76122608, -76122608, 76122608, 73262576, 73262576, -73262576, 73262576],
"collisionMask": 3,
"collision_sphere_radius": 410201216,
"collision_box": [0, 0, 0, 197914752, 258878448, 249152032]
}

Is it possible that some overflow/underflow happens when calculating the offsetMatrix?

https://github.com/urho3d/Urho3D/files/73092/Models_plainText.zip

**Comment by kimkulling** [comment]
Good question, started to look onto it.

**Comment by kimkulling** [comment]
The file is called mdl.json, are the files dae?

**Comment by yushli** [comment]
the dae file is at https://github.com/urho3d/Urho3D/files/72421/youguge.dae.zip

Urho3D's AssetImporter proceses this dae file and generates the models binary. I wrote a util to dump the model binary into this mdl.json for debugging purpose. You can find other relative files such as the texture files at https://github.com/urho3d/Urho3D/issues/1118

**Comment by kimkulling** [comment]
Ah, now I understand. I will installiert Urho3D as well I guess.

yushli <notifications@github.com> schrieb am Fr., 8. Jan. 2016 03:17:

**Comment by yushli** [comment]
the source code for Urho3D's AssetImporter is here: https://github.com/urho3d/Urho3D/blob/master/Source/Tools/AssetImporter/AssetImporter.cpp
Basically it is just a wrapper around assimp and transform the output result of assimp into its custom formats.

**Comment by ongamex** [comment]
So guys what is happening with this issue?

 I'm kind of scared to updated because it works fine for me(haven't tested the models in this issue) on revision(5c890c1a90a28eedb5b9836037c3808d2a87097d).

**Comment by ongamex** [comment]
Just to confirm it no longer works for me on revision 98ba2d23103546ad5770e706fb5993a183eaefa5
 (currently master).

**Comment by kimkulling** [comment]
Good sign that we have a quality issue at the moment. Has anyone else time for looking onto this issue?

**Comment by kimkulling** [comment]
I added this issue onto my assimp-todo list ( see: https://trello.com/b/BPJYY1KA/assetimporterlib ). At the moment I need another tool to get more focused who is actually blocked.

**Comment by kimkulling** [comment]
Please try the latest master. I found https://github.com/assimp/assimp/issues/458, which descripses wrong handling of animations with angle> 360. For the last release I merged this fix out. I guess this could cause your isse. 
If this is the case i need to test aganst an overflow.

**Comment by yushli** [comment]
I suppose you mean uncomment ColladaLoader.cpp line 1177 to 1191. I tried this but the generated mdl file is the same. That may not be the reason that causes this issue.

**Comment by kimkulling** [comment]
Ok, thanks for trying it. I will continue my investigations.

**Comment by yushli** [comment]
If I can be of any help please let me know. Currently I am reading assimp's source code to try to have a basic understanding of this issue. But the source code is quite complex. You guys are amazing at implementing such a complex tool that handles some many formats. Look forward to your final solution.

**Comment by kimkulling** [comment]
Me too. I am trying to understand what ongoing in this issue at the moment. Thanks for your help.

**Comment by kimkulling** [comment]
The dae-file does not contain any animation. Tere is no animation library in the file.

**Comment by kimkulling** [comment]
Is this one somehow related to https://github.com/urho3d/Urho3D/issues/1227?

**Comment by yushli** [comment]
https://github.com/urho3d/Urho3D/issues/1227 solves different issue. I may explain the issue more clearly:

1. the dae contains some static model and one animated model. 
2. the animated model contains skeleton information.
3. the dae is process by assimp then convert into urho3d's custom format by urho3d's assetimporter, which is wrapper tool around assimp,directly using assimp's parsing output.
4. the static model loads successfully.
5. the animated model loads into urho3d, but can not be displayed.(The skeleton is loaded and used).
6. if the animated model is loaded as static model, that is, not using the skeleton information, it can be displayed. That means, the skeleton information is wrong.
7. I dump the urho3d's custom format and find that the bones of the skeleton contain offsetMatrix with extreme large ints, looks like overflow/underflow. 
"offsetMatrix": [58196376, 58196376, -58196376, 58196376, 76122608, 76122608, -76122608, 76122608, 73262576, 73262576, -73262576, 73262576],
"collisionMask": 3,
"collision_sphere_radius": 410201216,
"collision_box": [0, 0, 0, 197914752, 258878448, 249152032]

This overflow/under may cause by assimp or by urho3d's wrapper around assimp, I don't know exactly where it happens.

**Comment by kimkulling** [comment]
After looking into the Collada file ( youguge.dae ):
- There is no animated model in this file you attached to this issue:
  + I looked for an **animation_library** section or an **animation_clip_library** section, but there is none
- There is one reference to a **skeleton** in the section **library_visual_scenes**:
 L3193: <skeleton>#_-78478</skeleton>

**Comment by yushli** [comment]
AnimatedModel in Urho3D means a model with skeleton information. It does not contains the actual animation clip information. The model in question is _x0032_179a0f8.obj. 
The code that process dae and generate urho3d's custom mdl file is 
https://github.com/urho3d/Urho3D/blob/master/Source/Tools/AssetImporter/AssetImporter.cpp 
line 850 BuildAndSaveModel. 
The offsetmatrix of each bone is incorrectly calculated in this funciton.

**Comment by kimkulling** [comment]
Shall work as far as I know.
