### ISSUE TITLE
assimp.org website down

### ISSUE THREAD

**Issue by 0x2A** [assimp/assimp#733]
Seems like the assimp.org website is down. All I can see is a strato default error message.

**Comment by kimkulling** [comment]
You are right. An older CMS system on the webspace was sending spam mails. So my provider closed the side temporary. I already fixed the security issues and asked for switch it online again.

**Comment by urzds** [comment]
It is happening again.

**Comment by kimkulling** [comment]
Still not online again. I am in discussion with my provider to get all
installed malware. UNfortunately they are not really fast in answering
questions.
