### ISSUE TITLE
Stack corruption in DefaultLogger

### ISSUE THREAD

**Issue by vk2gpu** [assimp/assimp#737]
Just got stack corruption when importing an MD5Mesh that has a very large commandline string.

Code that triggered it is: https://github.com/assimp/assimp/blob/master/code/DefaultLogger.cpp#L257

All of these functions should be using snprintf/sprintf_s to ensure that they don't cause any stack corruption.

**Comment by neilogd** [comment]
This would still be an issue for all the other logging functions that use sprintf. Perhaps worth fixing across the board?
