### ISSUE TITLE
error: undefined reference to 'aiScene::~aiScene()' on Android when using delete myAiScene;

### ISSUE THREAD

**Issue by danielesegato** [assimp/assimp#74]
Hi,

I've compiled assimp using the tutorial here:
http://jazzyjester.wordpress.com/2013/02/02/test

Actually with a little modification that I detailed on a comments of that article; but I can reproduce with the precompiled library of that guide too.

My code do something like this:

```c++
aiScene* currentScene = importer.GetOrphanedScene();

then later I have:
delete currentScene;
```
And I get this error:
/home/mastro/usr/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs-debug/FrameMarkers/assimp.o: in function DoTheSceneProcessing(aiScene*):jni/assimp.cpp:22: error: undefined reference to 'aiScene::~aiScene()'
collect2: ld returned 1 exit status

on delete currentScene;

Seems like the deconstructor aiScene::~aiScene is not linked in the libassimp.so library

Is this a bug?

**Comment by kimkulling** [comment]
Deprecated!
