### ISSUE TITLE
Missing UTF-8 support for MTL

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#742]
It doesn't seems that the OBJ / MTL importer support UTF-8. I was reading a MTL file where one of the texture paths had a Norwegian character in it and it got converted to a unknown symbol during the importer process. I am using the newest version, Assimp 3.2.
"mosaic_grønn.jpg"
gets converted to:
"mosaic_gr�nn.jpg"

**Comment by kimkulling** [comment]
I am not sure if obj shall support UTF-8? I will check and thanks a lot for the hint!

**Comment by kimkulling** [comment]
Do you have a small example to reproduce this issue? Normally this should work.

**Comment by fredrik955** [comment]
Hi,
Sends you the files attached. After looking into it one more time I see
that this wasn't a problem with Assimp, beacuse the MTL file and texture
filename also had a UTF-8 issue.
Thank you for your help

**Comment by kimkulling** [comment]
So we can close this issue? If not: just reopen it again, please :-). 
Thanks, Kimmi
