### ISSUE TITLE
"C3861: 'snprintf': identifier not found" with VS2013 and prior

### ISSUE THREAD

**Issue by tipito2** [assimp/assimp#743]
Suggested workaround:
http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010

**Comment by kimkulling** [comment]
Oh my gosh, working on a fix!

**Comment by 0x2A** [comment]
How about putting this in a global header file, like gzip is doing:
    #if defined(_MSC_VER) && _MSC_VER < 1900
    #define snprintf _snprintf
    #else
    #include <stdio.h> //sprintf
    #endif

**Comment by kimkulling** [comment]
Sure you can do that. But I dealt with a lot of issues n different platforms caused by minimal differences of the behaviour of snprintf  ( this inckudes VS2010 or VxWorks-Diab ). I just introduces ai_snprintf instead.

**Comment by eftales** [comment]
Since you are using vs2013, there is a short solution.
```
#if defined(_MSC_VER) && _MSC_VER < 1900
#define snprintf sprintf_s
#endif
```
