### ISSUE TITLE
Update vertices

### ISSUE THREAD

**Issue by Celli119** [assimp/assimp#744]
Is there any method to modify the vertices coordinates (mVertices) of a mesh ?

**Comment by kimkulling** [comment]
You can do that on your own or you can check our post-processing steps. Any special thing you want to do in special which comes to your mind? ;-)

**Comment by Celli119** [comment]
Yes, I actually I thought about a method which update the normals as soon as you change the vertices.

**Comment by kimkulling** [comment]
Just to make clear that I get your usecase correctly: you want to import a model, create new vertices / modify some extisting vertices and run a post-process to generate the new normals, right?

**Comment by Celli119** [comment]
Right, exactly.

**Comment by kimkulling** [comment]
I guess I have to modify our API a little bit to support this. I will check.

**Comment by Celli119** [comment]
Great !

**Comment by kimkulling** [comment]
You can use *aiApplyPostProcessing* after doing an import.
