### ISSUE TITLE
error LNK2019: unresolved external symbol "_vai_snprintf" in function "_gzvprintf"

### ISSUE THREAD

**Issue by 0x2A** [assimp/assimp#745]
looks like the struggle with snprintf isn't over yet :-1: 
function vai_snprintf seems to be not defined but used in gzwrite.c (line 354 and 357). I can't find this function anywhere else.

Edit: Ok seems like it has something to do with my project setup since when I create a sln with cmake it does compile successfully. But still I can't find any definition of vai_snprintf. I also get `warning C4013: 'vai_snprintf' undefined` when compiling the cmake generated project files.

**Comment by kimkulling** [comment]
Please try again, merge error.
