### ISSUE TITLE
Findassimp.cmake not installed

### ISSUE THREAD

**Issue by jvgomez** [assimp/assimp#747]
Hi, I have installed libassimp3 (3.0~dfsg-2) and the corresponding libassimp-dev in my Ubuntu 14.04 OS. None of these packages installed the findassimp.cmake file. Is there any reason for this? Additionally, is there any reason why this module is not included in the CMake source?

Thanks.

**Comment by kimkulling** [comment]
3.0 is an old evrsion. Have you tried 3.2 or is this version not available at the moment?

**Comment by jvgomez** [comment]
I keep my computer updated, so I guess it is not available for my distro yet.

**Comment by kimkulling** [comment]
Hm, try this one: https://packages.debian.org/source/sid/graphics/assimp
