### ISSUE TITLE
Segmentation Fault on corrupted MTL file

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#751]
Assimp 3.2 crashed when I tried to read an OBJ+MTL file. I later discovered that the MTL file was corrupted. I hope Assimp can give a error message when the MTL file is corrupted and not crash. It will be nice to get an error message, and that the importer can continue without reading the MTL file if it is invalid.

Here is the crashing model: https://drive.google.com/file/d/0B3PusJzfuPY0cFhyZy1UUFpvY3M/view?usp=sharing

**Comment by kimkulling** [comment]
Thanks for the file, I will check that. And I do agree, a crash is not an option.

**Comment by kimkulling** [comment]
This issue shall be fixed with the latest version of AssetImporterLib from our master-branch. Could you please check it and report if the error still occurrs. I get an error message: "Unknown texture type" and everything will be loaded as expected.

**Comment by fredrik955** [comment]
Thank you Kim! I am using Assimp a lot and will continue to report. Assimp
is a awesome library that has made my life so much easier.
