### ISSUE TITLE
command line > change up-axis

### ISSUE THREAD

**Issue by digitaledge** [assimp/assimp#752]
Sorry for asking it here, but  i did not find a documentation about the command line tool.

Is it actually possible to load a skeleton animated collada file with assimp, then flip the up axis from z to y and export back to collada?

If yes, what command/flags should i use?

Cheers 
Hen

**Comment by kimkulling** [comment]
No, but this would be a really interesting use case for a new release.

**Comment by kimkulling** [comment]
I guess a post-processing step for this would be better.
