### ISSUE TITLE
FBX: "After optimizing the scene graph, no data remains"

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#754]
I tried to open a FBX file with Assimp 3.2 (GIT commit c2a046) and had enabled these aiProcess_Triangulate | aiProcess_GenUVCoords | aiProcess_GenSmoothNormals | aiProcess_OptimizeMeshes | aiProcess_OptimizeGraph | aiProcess_FindInvalidData | aiProcess_FixInfacingNormals
and I get the error message described in the title.
The FBX file contains a mesh, and I am able to open it in several different 3D softwares.

**Comment by kimkulling** [comment]
Do you have the model, so we can try to reproduce the issue? Log output would also be useful.

**Comment by fredrik955** [comment]
Hi kim,

Here you have the file: [https://storage.googleapis.com/assimp_model_error/no_data_remains.fbx](https://storage.googleapis.com/assimp_model_error/no_data_remains.fbx)

Log: `Assimp error message: After optimizing the scene graph, no data remains`

**Comment by kimkulling** [comment]
Thanks!

**Comment by kimkulling** [comment]
Some stuff come first:
Warn,  T18728: FBX-DOM: unsupported, newer format version, supported are only FBX 2011, FBX 2012 and FBX 2013, trying to read it nevertheless
Info,  T18728: FBX: ignoring empty AnimationStack (using IK?): Take 001
Error, T18728: FBX-Parser did not find required element "BinormalIndex"
Warn,  T18728: FBX-DOM (TOK_KEY, offset 0x9d351) failed to read source object for incoming Model link, ignoring

**Comment by kimkulling** [comment]
Should be fixed now!

**Comment by fredrik955** [comment]
Hi again,

I pulled from git and recompiled assimp but I can't see that the problem is solved. Just take a look on this file:
https://storage.googleapis.com/assimp_model_error/no_data_remains2.fbx

**Comment by kimkulling** [comment]
Have you tried latest master? I tried it and I can see your Humbee model rendered by our viewer.

**Comment by kimkulling** [comment]
I will try to use exactly your preprocessing steps, maybe I did something wrong there.

**Comment by kimkulling** [comment]
I guess this one shall be fixed ´. Please reopen if this issue still exists.

**Comment by Jennilein1991** [comment]
I get this error, when loading a empty gltf file (with no mesh inside). Is this then supported to throw this error? Would be nice if assimp could just return a empty gameobject :D
