### ISSUE TITLE
OBJ: vertex normal index out of range

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#755]
Sometimes when I import a OBJ file to Assimp 3.2 I get this message "vertex normal index out of range" and Assimp stops the import process. Shouldn't Assimp just continue importing the model and ignore the normals?
Here is an example: https://drive.google.com/file/d/0B3PusJzfuPY0emE4Z3RpT2xlclE/view?usp=sharing

**Comment by kimkulling** [comment]
The issue is cause by a false handled \. I will try to fix it.And you are right: one invalid index should not break the whole model.

**Comment by fredrik955** [comment]
Hi kimkulling,
Is there any progression on the issue?

**Comment by kimkulling** [comment]
Yes, you can reformat your obj-file by not breaking lines with \. Then it works. At the moment this line break feature with using \ is not supported.

**Comment by fredrik955** [comment]
Thamk you.

**Comment by karyon** [comment]
i do get the same error when loading the san miguel object from here: http://graphics.cs.williams.edu/data/meshes.xml although there are no backslashes in that file. any help would be greatly appreciated.

**Comment by karyon** [comment]
my case seems to be legit, at one point a vertex references normal -178213 although the file contained only 178212 normals up to that point.

**Comment by kimkulling** [comment]
Sounds like a bad cast r an overflow.

**Comment by corporateshark** [comment]
Gentlemen, is there any progress on this issue?

**Comment by kimkulling** [comment]
I am currently working on this overflow.

**Comment by kimkulling** [comment]
Works with latest master.
