### ISSUE TITLE
OBJ import takes forever

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#759]
When I try to import this file: https://drive.google.com/file/d/0B3PusJzfuPY0Wkc0cGwtb053ejQ/view?usp=sharing
with Assimp 3.2 it will never finish the import script.
I use these flags: aiProcess_Triangulate | aiProcess_GenUVCoords | aiProcess_GenSmoothNormals | aiProcess_OptimizeMeshes | aiProcess_OptimizeGraph | aiProcess_FindInvalidData | aiProcess_FixInfacingNormals

**Comment by kimkulling** [comment]
The link is dead, sorry.

**Comment by andrewparlane** [comment]
Are you building from the trunk or a particular release?

What platform?

I added changes for better progress reporting in OBJ imports, but that's
only on the trunk as of yet. If you are using the trunk it could be that,
can you try going back to the last stable release and testing there?

**Comment by fredrik955** [comment]
Hi,
The link is not dead. It says "No preview", but you can see the download button in top center of the screen.
I am using this version: Version 3.2 -debug -noboost -shared -st (GIT commit c2a046)
I am using Ubuntu 14.04.3 LTS.

**Comment by andrewparlane** [comment]
[image: Inline images 1]

Looks pretty dead. here.

Fine if you're using a release rather than the trunk, my changes aren't the
issue. If you can get the link working, I / we'll have a look.

**Comment by fredrik955** [comment]
Here is a new link:
https://storage.googleapis.com/assimp_model_error/forever.obj

**Comment by andrewparlane** [comment]
Well, that file seems to be 102MB, which is probably clue enough as to why
it's taking so long. I'm importing a 1.5MB .obj and it takes about 5s,
assuming we can linearly scale up, a 102MB one should take about 5m40s.

Try sticking a progress bar in there, or at least something that outputs
progress percent, and see how it's going.

I'm not entirely sure how you generated a .obj that big, either you have a
very complicated model, or it got exported incorrectly.

**Comment by fredrik955** [comment]
Thank you for the reply. Did the import process ever finish on your
computer? I can open the OBJ file in Meshlab in less than 20 sec. Is it
possible to speed up the OBJ importer?

**Comment by andrewparlane** [comment]
it's still downloading ATM. I'm currently living in Bolivia, and the
internet is a little on the slow side. Currently looking at your other seg
fault issue.

**Comment by andrewparlane** [comment]
I can't seem to locate commit: c2a046 It's possibly ambiguous.

Can you provide the full hash?

**Comment by andrewparlane** [comment]
OK, so (still would like the full hash, as I can't repro your seg fault
bug).

This .obj does indeed take forever. It is running, and so will eventually
finish, but not for a while. The problem (or at least the first) is in
objFileImporter.cpp:InternReadFile() It iterates through the buffer and
tries to remove backslashes followed by newlines. If you open you .obj in a
text editor and search for \, you'll find a bunch of them. They seem to
occur when you have exported a quad intstead of triangle.

So the code goes through the entire buffer checking for '\', removing it,
then removing all immediate consecutive '\r' and '\n' chars. Your .obj uses
\r\n for new lines. So we are doing 3 erases every time we find a '\'.

The std::vector::erase function has a complexity of O(n), ie. for a 102MB
file, very slow.

This hunt for backslashes takes approx 1/6th of the total import + post
process time (at least for my file), and I have no backslashes. So I've
been wandering about this. However never had much of a reason to bother
changing it.

The ideal solution would be to parse and skip these chars in the actually
parsing stage, therefore not having to do any erases.

Another option would be to use a STL container that had O(1) complexity for
removing items in the middle (ie. a list).

As a quick test I removed the \\\r\n in notepad++ and then the file import
took 4 minutes, and the entire thing about 5.5 minutes (my initial
estimate). Unfortunately it then failed with "bad allocation". So I'll look
into that as well.

Andy

**Comment by andrewparlane** [comment]
OK, created a pull request that should fix this.

See:
https://github.com/assimp/assimp/pull/760

You will need to cherry-pick both this commit and
https://github.com/assimp/assimp/commit/1632f1fbb908d34f012b41be7883b63fd5199a0a
(the latter first, ortherwise the new commit won't apply).

Look into the git cherry-pick command if you don't know it already.

**Comment by andrewparlane** [comment]
Oops, compile fail, second attempt:
https://github.com/assimp/assimp/pull/761

**Comment by andrewparlane** [comment]
OK, made a different pull request with a better fix, it has been merged now.

So Fredrik995, you can either work off the master branch, or you can try
cherry picking my commits back to v3.2.

Finally it's still going to be pretty slow, if you look at the FAQ:
http://assimp.sourceforge.net/FAQ.html there's a "Why is it so slow?"
question, you can probably speed it up a fair bit more using that. However
I doubt you'll get it down to 20s (no idea how meshLab does it so quick).
One other option would be to split it into multiple .obj files and use
multiple threads to load it quicker, then combine it in your app.

Hope that helps.

Andy

**Comment by fredrik955** [comment]
Thank you guys!
Keep up the good work you are doing.

**Comment by kimkulling** [comment]
The base performance of AssetIMporterLib is one of my biggest concerns at the moment.

**Comment by andrewparlane** [comment]
If you send me some details about why it's slow, then I'll have a think
about what can be done to speed it up.

In my looking into OBJ importing, I haven't noticed anything particularly
slow outside of whiespace removal and parsing itself, both of which are in
the derived class.

**Comment by kimkulling** [comment]
Dublicate to #944
