### ISSUE TITLE
Crash with JoinVerticesProcess

### ISSUE THREAD

**Issue by JLouis-B** [assimp/assimp#762]
Hi,
I use the trunk version of Assimp, and I got a crash in the Assimp viewer when I export some files with it.
According to the debugger, it crash in Assimp::JoinVerticesProcess::ProcessMesh(aiMesh*, unsigned int)

Not sure if it's related, but I have this crash with all the animated meshes that I have tested, and it works fine with the static meshes that I have tested.
You can reproduce this issue with Testwuson.x from Assimp when you load it in the viewer and you try to export it.

I hadn't this problem with my previous build of Assimp (made approximately a month ago)

**Comment by kimkulling** [comment]
Do you have a sample which we can use to reproduce the issue, please?

Kimmi

**Comment by JLouis-B** [comment]
You can reproduce the issue with "Testwuson.x" from the test models of Assimp.

**Comment by kimkulling** [comment]
The problem is, that the X-Fileparser detects invalid data sets in the animation definitions. So the data definition gets invalid for some bones ( number of  bone vertex weights in the bone is greater than 0, but the pointer showing to the array with bone vertex weights is NULL caused by this parser issue ).

Have you ever tired to use these data? And do you know which version worked? We need to start our regression tests suite again to detect these issues earlier!

**Comment by kimkulling** [comment]
I will push a test to avoid the crash as a workaround.

**Comment by JLouis-B** [comment]
Thanks for your investigations on the issue.

I have pull the repo and rebuild Assimp, the problem persist.
The bug can also be reproduced with a B3D model :
https://github.com/zaki/irrlicht/blob/master/media/ninja.b3d

I'm not sure to understand what do you mean by "tired to use these data"
The previous version of Assimp that I have tested was a trunk version in december, I don't know exactly when.
But now I'm not 100% sure to have tested precisely this model during my previous tests, maybe just different models.

**Comment by kimkulling** [comment]
Typo: have you ever tried ...

**Comment by JLouis-B** [comment]
Ok, sorry but I still don't understand exactly what do you mean by "tried to use these data" (tested this model ?)

Do you need any other information ?

**Comment by kimkulling** [comment]
Tested on latest version. No crash any more.
