### ISSUE TITLE
Order of evaluation bug in ObjFileParser.cpp, getFace, incorrect aiPrimitiveType

### ISSUE THREAD

**Issue by Flayer** [assimp/assimp#769]
Hello, just want to say thank you this awesome tool, currently using it for my game engine =)

I encountered an error though, when starting my engine with the latest Assimp (clone), and after searching for a while I pin-pointed the error to *ObjFilerParser.cpp:182*.
This bug was introduced in a recent commit: https://github.com/assimp/assimp/blame/9969167c2a81a3460362a8319809f8c094c0d725/code/ObjFileParser.cpp#L182

The problem lies within this function call:
```c
getFace(*helperIt == 'f' ? aiPrimitiveType_POLYGON : (*helperIt == 'l'
                    ? aiPrimitiveType_LINE : aiPrimitiveType_POINT), ++helperIt, helperItEnd);
```
the statement
```c
getFace(..., ++helperIt, ...);
```
will be evaluated before
```c
getFace(*helperIt == 'f' ? aiPrimitiveType_POLYGON : (*helperIt == 'l'
                    ? aiPrimitiveType_LINE : aiPrimitiveType_POINT), ..., ...);
```
thus causing the type to be aiPrimitiveType_POINT even if the current character is 'f' (aiPrimitiveType_POLYGON).

To verify this one can move the ternary statement and store the result in a temporary just before the function call, everything should work as expected then.

I'm using GCC 5.2.1 on Ubuntu 15.10 x86_x64

I apologize if I sound too harsh/direct, this is my first issue report and english is not my native tounge.

**Comment by andrewparlane** [comment]
good spot,

My bad.

Pull request to follow shortly.

Your English was perfect and polite, thank you for the report.

**Comment by kimkulling** [comment]
I reverted the last pull request. I got too much issues with VS2015 on my side. I do not fully understand what went wrong. My bad, more testing next time before accepting it.

**Comment by Flayer** [comment]
Cool, glad I could help =)
