### ISSUE TITLE
Retrieve UnitScaleFactor and OriginalUnitScaleFactor from FBX files

### ISSUE THREAD

**Issue by Noxalus** [assimp/assimp#774]
Hello everyone :)

I need to get some unit properties, but when I try to retrieve these values, I always obtain the default one.

``` cpp
// [FBXImporter.cpp => InternReadFile function]

// take the raw parse-tree and convert it to a FBX DOM
Document doc(parser,settings);

// convert the FBX DOM to aiScene
ConvertToAssimpScene(pScene,doc);

auto globalSettings = doc.GlobalSettings();
auto unitScaleFactorTest = globalSettings.UnitScaleFactor();
auto originalUnitScaleFactorTest = globalSettings.OriginalUnitScaleFactor();
```

However, with the VS debugger, I can see that the value of these properties is not the default one and if I try to retrieve them like that, I get the proper values:

``` cpp
auto globalSettings = doc.GlobalSettings();
auto unitScaleFactor = globalSettings.Props().Get("UnitScaleFactor")->As<TypedProperty<float>>()->Value();
auto originalUnitScaleFactor = globalSettings.Props().Get("OriginalUnitScaleFactor")->As<TypedProperty<float>>()->Value();
```

Please notice that I used _float_ type, and not _double_ as specified in the [FBXDocument.h](https://github.com/assimp/assimp/blob/master/code/FBXDocument.h#L1310) file. Beside, if I change the type in the macro call, it works like expected (calling the getters of global settings).

``` cpp
fbx_simple_property(UnitScaleFactor, float, 1)
fbx_simple_property(OriginalUnitScaleFactor, float, 1)
```

Am I the only one with this problem?

**Comment by kimkulling** [comment]
At the moment: seems to be yes :-). Thanks for the report.

**Comment by bolabola** [comment]
This problem still exists.
