### ISSUE TITLE
FBX importer doesn't use meters as unit basis

### ISSUE THREAD

**Issue by Noxalus** [assimp/assimp#775]
Hello everyone :)

I've done many tests with FBX importer using multiple files physically scaled, with different units, and I figured out that the FBX importer use centimeters as base unit, not meters.

If you create a cube of 1m3, export it as FBX and load it with ASSIMP FBX importer, it will have a size of 100 meters.

I've done my test using 3DS Max and Blender, the problem is always the same. Exporting the same files as Collada (DAE), there is no unit issue (still using ASSIMP to load the file).

Is there any reason for that ?

Scaling the root transform according to the data parsed and stored in **UnitScaleFactor** property, I finally get the behaviour that I expected:

``` cpp
// [FBXImporter.cpp => InternReadFile function]

// FBX base unit is in centimeters, we need to convert it into meters
auto globalSettings = doc.GlobalSettings();
auto unitScaleFactor = globalSettings.UnitScaleFactor();

auto unitSize = unitScaleFactor / 100.f;

pScene->mRootNode->mTransformation *= aiMatrix4x4(unitSize, 0, 0, 0,
    0, unitSize, 0, 0,
    0, 0, unitSize, 0,
    0, 0, 0, 1);
```

Is there anybody with the same problem?

**Comment by sagaceilo** [comment]
Yes, same here. Resolved it on the assets side, so articts just need to remember to export using proper scaling. I cound't find any in-file info about used size metrics so I could scale model from cm to meters. Root matrix of scene also doesn't contain any usefull info neither the properties build in the file (nodes properties).
Funny fact, that when static meshes are kinda ok (exported in proper scale by artist), animated ones aren't :D

**Comment by Noxalus** [comment]
If I understand, the info that you were looking for is into `doc.GlobalSettings().UnitScaleFactor()`? Artists shouldn't have to apply a specific scale to fix this problem, we should fix it into ASSIMP instead!

**Comment by kimkulling** [comment]
I do agree. But first I have to figure out how we can fix this issue.

**Comment by sagaceilo** [comment]
There are also BoneSpace matrices when you loading skinning and animation key values. All that seems to be in [cm], so just scaling scene's root is not enought in my opinion (it need's to be veryfied).

**Comment by kimkulling** [comment]
We can see the same issue with cameras. For instance instead of x=12.07 we get 1210.

**Comment by kimkulling** [comment]
See #807

**Comment by kimkulling** [comment]
So after investigating this issue deeper I guess we have to rescale all positions by 0.01f. I am not sure where this factor comes from.

**Comment by kimkulling** [comment]
You can use the rescale-post-process to work around this issue. We introduced it in 4.1.0 to solve issues like this.

**Comment by AmanKataria94** [comment]
How to we use it? I can only find a aiProcess_GlobalScale flag.

**Comment by kimkulling** [comment]
You can import the fbx-scene and you will get the ScaleUnitFactor from the metadata of the file. And this can be used for the rescale. Here you can find an example how to read-out the value:
https://www.patreon.com/posts/fbx-is-supported-16563714

**Comment by AmanKataria94** [comment]
Ah right, yes I tried this as well but it seems to always retrieve 1. I took a look at the ascii version of the .fbx and it has unitScaleFactor set to 10000. I downloaded yesterdays build and am using the aiImportFile() method to get the scene which i think wraps the functionality used in the example you provided. I think i'm not alone in this looking at the latest comments on issue #774 . Thanks for the speedy reply though!

**Comment by kimkulling** [comment]
Ok, then I have to check if this value will be imported correctly. The first fix just provided a version where the existing import function was used. Could you please provide a link to your example. Would be great.Th
anks a lot!

**Comment by kimkulling** [comment]
Shall be fixed now.

**Comment by sagaceilo** [comment]
Yup, works like a charm !!(https://i.imgur.com/QwSyans.png meter and
centimeter unit base box)

sob., 24 lut 2018, 15:58 użytkownik Kim Kulling <notifications@github.com>
napisał:
