### ISSUE TITLE
Feature request: measure accuracy progress handler

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#776]
turol  kimmi: idea: progress handler profiler
20:39:44    turol  a simple program (or a new mode to assimp tool)
20:39:49    turol  which sets a progress handler
20:40:11    turol  which saves the current high-res timestamp and the progress% to a buffer
20:40:32    turol  at the save the buffer as (x,y) pairs and do a linear regression
20:40:44    turol  plot point and regression line on a graph
20:41:03    turol  lets you see how accurate the progress handling really is

**Comment by andrewparlane** [comment]
You could just add a printf with a timestamp and the progress to your
progress handler, then plot it in excel or whatever graphing tool you want
to use?

**Comment by kimkulling** [comment]
Done!
