### ISSUE TITLE
Obj file import may neglect last face

### ISSUE THREAD

**Issue by a-day-old-bagel** [assimp/assimp#777]
If you try to import an obj file without an extra empty line at the end, the last line (usually a face-specifier) is neglected.  Probably due to a regex somewhere requiring a newline character at the end of each line.
Adding an extra empty line at the end of the obj file will fix this.
This might be correct behavior, I'm not sure - I just thought I'd mention it.

**Comment by rproepp** [comment]
I ran into the same problem. Even when I load the test/models/OBJ/box_without_lineending.obj file added in 1550191, I don't get triangles for the face defined by the last line in the file.
Looking at the code, `ObjFileParser::parseFile` uses `IOStreamBuffer<T>::getNextDataLine` to parse the file line by line in a while loop. But `getNextDataLine` always returns `false` for the final line of the file.
