### ISSUE TITLE
AMD Tootle

### ISSUE THREAD

**Issue by sagaceilo** [assimp/assimp#780]
As you may now, AMD released sources for many its technologies. One of those is Tootle, that optimizes triangle reordering taking care of vertex cache (as Assimp does already) AND overdraw optimization. It basicaly pushes outside triangles of the meshes to be rendered first.

https://github.com/GPUOpen-Tools/amd-tootle

Hope you will find that usefull. It would be great to see this as new posprocess in Assimp :)

**Comment by sherief** [comment]
I'm very interested in having it as part of assimp, but I'm not sure what the legal framework is. @kimkulling / @acgessler, can someone help?

**Comment by kimkulling** [comment]
I guess we will not do this. If anyone maybe interested in just provide a pull request!
