### ISSUE TITLE
FBX animation import failed

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#782]
File: [https://storage.googleapis.com/assimp_model_error/animation_failed.FBX](https://storage.googleapis.com/assimp_model_error/animation_failed.FBX)

Log:
`void Assimp::FBX::Converter::GenerateNodeAnimations(std::vector<aiNodeAnim*>&, const string&, const std::vector<const Assimp::FBX::AnimationCurveNode*>&, const LayerMap&, int64_t, int64_t, double&, double&): Assertion `node->Target() == target' failed.`

**Comment by kimkulling** [comment]
The spec says: reading the spec: 
If you create an animation curve node by calling FbxAnimCurveNode::CreateTypedCurveNode, you must specify a FBX property of the data type you need, ...

In your model this is not the case, some links to the references are missing. So the assert is right.

The question is, if we need to break down the import in debug every time or would it be enough when assimp works in strict mode. Opinions?

**Comment by kimkulling** [comment]
Check http://help.autodesk.com/view/FBX/2016/ENU/?guid=__files_GUID_386BAD6A_82F9_4148_BD5F_3FE2E90A87D0_htm

**Comment by ElArtista** [comment]
Well, i've reproduced the same issue with a model that seemed to work pretty well in official FBXReview and AssimpViewer release build. I also believe that a warning could have been better.

**Comment by kimkulling** [comment]
I do agree

**Comment by sidshekar** [comment]
Hi, so I am getting this error while plying the player animation. I am not sure what is causing this problem. What would I have to do to get around this issue please?
