### ISSUE TITLE
X3D support

### ISSUE THREAD

**Issue by kankaristo** [assimp/assimp#784]
The [wishlist](http://www.assimp.org/wishlist.txt) lists VRML as a format that may get support in the future.

VRML has been superseded by [X3D](https://en.wikipedia.org/wiki/X3D), so instead of (maybe) adding support for VRML, X3D support should probably be added instead.

X3D is "widely" used for 3D on websites (widely in quotes, because 3D on the web is still pretty rare).

X3D is just XML, so it should be pretty easy to parse. It's also an open format, so specifications should be readily available.

I'm creating this issue mostly just so I can see if/when this gets implemented. So just another wishlist item. :smile:

**Comment by bot3d** [comment]
Most X3D loaders are GPL or LGPL. But there is a new one with permissive license: https://github.com/cybergarage/CyberX3D4CC

Would be a great addition for assimp.

**Comment by smalcom** [comment]
https://github.com/assimp/assimp/pull/1014

**Comment by kimkulling** [comment]
Merged, so iffue fixed.
