### ISSUE TITLE
glTF importer crash

### ISSUE THREAD

**Issue by turol** [assimp/assimp#785]
On linux, 64-bit release with debug info

assimp info test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Segmentation fault

backtrace from gdb:
0  0x00007ffff71ea59c in std::string::assign(char const*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
1  0x00007ffff7b9c8ea in assign (
    __s=0x42925f "collada2gltf@ceec062e3d5793f2f249f53cbd843aee382ad40b", 
    this=0x7fffffffc680) at /usr/include/c++/4.7/bits/basic_string.h:1128
2  operator= (
    __s=0x42925f "collada2gltf@ceec062e3d5793f2f249f53cbd843aee382ad40b", 
    this=0x7fffffffc680) at /usr/include/c++/4.7/bits/basic_string.h:552
3  Read (out=
    <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, val=...) at assimp/code/glTFAsset.inl:78
4  glTF::(anonymous namespace)::ReadMember<std::basic_string<char> > (
    obj=..., id=id@entry=0x7ffff7bf95d8 "generator", out=
    <error reading variable: Cannot access memory at address 0xffffffffffffffe8>) at assimp/code/glTFAsset.inl:96
5  0x00007ffff7ba0ed4 in glTF::AssetMetadata::Read (
    this=this@entry=0x7fffffffc678, doc=...)
    at assimp/code/glTFAsset.inl:826
6  0x00007ffff7baf01b in glTF::Asset::Load (this=this@entry=0x7fffffffc5f0, 
    pFile="test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf", 
    isBinary=<optimized out>) at assimp/code/glTFAsset.inl:944
7  0x00007ffff7b9e9b7 in Assimp::glTFImporter::InternReadFile (this=0x426390, 
    pFile="test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf", 
    pScene=0x4278c0, pIOHandler=<optimized out>)
    at assimp/code/glTFImporter.cpp:604
8  0x00007ffff781ca51 in Assimp::BaseImporter::ReadFile (this=0x426390, 
    pImp=<optimized out>, pFile=
    "test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf", 
    pIOHandler=<optimized out>)
    at assimp/code/BaseImporter.cpp:97
9  0x00007ffff782911f in Assimp::Importer::ReadFile (this=0x7fffffffdd60, 
    _pFile=<optimized out>, pFlags=3645131)
    at assimp/code/Importer.cpp:668
10 0x00000000004139c5 in ReadFile (pFlags=<optimized out>, pFile=
    "test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf", 
    this=<optimized out>)
    at assimp/include/assimp/Importer.hpp:647
11 ImportModel (imp=..., path=
    "test/models/glTF/CesiumMilkTruck/CesiumMilkTruck.gltf")
    at assimp/tools/assimp_cmd/Main.cpp:288
12 0x000000000041a7e5 in Assimp_Info (params=0x7fffffffe2b8, num=1)
    at assimp/tools/assimp_cmd/Info.cpp:237
13 0x000000000041485f in main (argc=3, argv=0x7fffffffe2a8)
    at assimp/tools/assimp_cmd/Main.cpp:205

**Comment by kimkulling** [comment]
Closed by 11e52dc
