### ISSUE TITLE
OpenGEX: assertion failure

### ISSUE THREAD

**Issue by turol** [assimp/assimp#786]
On Linux, 64-bit debug version

assimpd info test/models/OpenGEX/Example.ogex
Launching asset import ...           OK
Validating postprocessing flags ...  OK
assimpd: assimp/contrib/openddlparser/code/Value.cpp:154: ODDLParser::int32 ODDLParser::Value::getInt32(): Assertion `ddl_int32 == m_type' failed.
Aborted

backtrace from gdb:

4  0x00007ffff7a47388 in ODDLParser::Value::getInt32 (this=0x4418d0) at assimp/contrib/openddlparser/code/Value.cpp:154
5  0x00007ffff773a827 in Assimp::OpenGEX::OpenGEXImporter::handleIndexArrayNode (this=0x436fa0, node=0x441870, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:717
6  0x00007ffff7738cfe in Assimp::OpenGEX::OpenGEXImporter::handleNodes (this=0x436fa0, node=0x43cd10, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:336
7  0x00007ffff7739dd1 in Assimp::OpenGEX::OpenGEXImporter::handleMeshNode (this=0x436fa0, node=0x43cd10, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:568
8  0x00007ffff7738cb0 in Assimp::OpenGEX::OpenGEXImporter::handleNodes (this=0x436fa0, node=0x43caf0, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:328
9  0x00007ffff77398ab in Assimp::OpenGEX::OpenGEXImporter::handleGeometryObject (this=0x436fa0, node=0x43caf0, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:478
10 0x00007ffff7738c62 in Assimp::OpenGEX::OpenGEXImporter::handleNodes (this=0x436fa0, node=0x43acf0, pScene=0x4388e0) at assimp/code/OpenGEXImporter.cpp:320
11 0x00007ffff77389b9 in Assimp::OpenGEX::OpenGEXImporter::InternReadFile (this=0x436fa0, filename="test/models/OpenGEX/Example.ogex", pScene=0x4388e0, pIOHandler=0x7fffffffd4a0) at assimp/code/OpenGEXImporter.cpp:266
12 0x00007ffff751314a in Assimp::BaseImporter::ReadFile (this=0x436fa0, pImp=0x7fffffffe150, pFile="test/models/OpenGEX/Example.ogex", pIOHandler=0x436270) at assimp/code/BaseImporter.cpp:97
13 0x00007ffff752408f in Assimp::Importer::ReadFile (this=0x7fffffffe150, _pFile=0x437ce8 "test/models/OpenGEX/Example.ogex", pFlags=3645131) at assimp/code/Importer.cpp:668
14 0x000000000041ef56 in Assimp::Importer::ReadFile (this=0x7fffffffe150, pFile="test/models/OpenGEX/Example.ogex", pFlags=3645131) at assimp/include/assimp/Importer.hpp:647
15 0x000000000041ddc9 in ImportModel (imp=..., path="test/models/OpenGEX/Example.ogex") at assimp/tools/assimp_cmd/Main.cpp:288
16 0x0000000000425d63 in Assimp_Info (params=0x7fffffffe2c8, num=1) at assimp/tools/assimp_cmd/Info.cpp:237
17 0x000000000041db1f in main (argc=3, argv=0x7fffffffe2b8) at assimp/tools/assimp_cmd/Main.cpp:205

**Comment by kimkulling** [comment]
Which model have you used?
