### ISSUE TITLE
Update contrib/clipper lib

### ISSUE THREAD

**Issue by asmaloney** [assimp/assimp#788]
Currently assimp includes [Clipper](http://www.angusj.com/delphi/clipper.php) 4.8.8 from August 2012 for the IFC loader.

The latest version is 6.2.1 from October 2014 and it contains [many fixes and improvements](http://sourceforge.net/p/polyclipping/code/HEAD/tree/trunk/README).

**Comment by kimkulling** [comment]
I already Tool a looks onto it, Unfortunately they change the Interface.

Andy Maloney <notifications@github.com> schrieb am Sa., 6. Feb. 2016 12:46:

**Comment by asmaloney** [comment]
Sorry, but I'm not sure I understand.  They changed it in a way that makes it impossible to work with?

**Comment by kimkulling** [comment]
No, the effort to migrate it is really big, so I will need some time to do it.

**Comment by asmaloney** [comment]
Oh, I see - thank you Kim!

**Comment by acgessler** [comment]
I also tried migrating a while ago, the interface changed a lot and I never got it to reproduce the original results (note that the Ifc importer is pretty hard to verify --- Kimmi, I have a set of a couple of hundred test models if you're interested)

**Comment by kimkulling** [comment]
Yes, I am definitely interested to do that :-).

**Comment by opoplawski** [comment]
This would be helpful for Fedora packaging as well. We prefer to use system versions of libraries if possible, but the system polyclipping is incompatible.
