### ISSUE TITLE
Crash when importing an FBX - with repro case

### ISSUE THREAD

**Issue by vd3d** [assimp/assimp#801]
Hi,

When I try to import this FBX I got a crash from Assimp :

You can download this free file here:
http://www.turbosquid.com/FullPreview/Index.cfm/ID/655500

**Comment by mesilliac** [comment]
The fbx version of this file is older than assimp supports. Currently assimp fails to import rather than crashing, with an error message about the file format version.

**Comment by kimkulling** [comment]
Now the error message is there. But we cannot import this older version of FBX. Would be great to convert it to a newer version.
