### ISSUE TITLE
Emissive Texture loading missing in OBJLoader

### ISSUE THREAD

**Issue by jakubkulaga-hdpmedia** [assimp/assimp#804]
There is no reading of map_Ke attribute in ObjFileMtlImporter (emissive texture).

As reference: http://cgkit.sourceforge.net/doc2/objmaterial.html
Take a look into: void ObjFileMtlImporter::getTexture()

**Comment by kimkulling** [comment]
Ok, thanks for the hint. i will take care!

**Comment by kimkulling** [comment]
Fixed by 99f00834ec79cfa73f2ee8265e99ab1f475c05b2
