### ISSUE TITLE
OBJ string to float overflow

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#805]
I got this error message when I tried to import an OBJ file into Assimp:
Converting the string "0000000.000000" into a value resulted in overflow.

Failed model: https://storage.googleapis.com/assimp_model_error/obj_overflow_string.obj

Using Assimp 3.2, git commit "bac6067"

**Comment by kimkulling** [comment]
Thanks for the report, I will take care!

**Comment by kimkulling** [comment]
Î guess the exception is right. One teture coordinate is broken:
vt 6801492219015629700000000000.000000 0.000000 7633856535286233300000000000.000000
