### ISSUE TITLE
Vertex colours support for Obj

### ISSUE THREAD

**Issue by sahilagnihotri** [assimp/assimp#809]
It seems that in the outer hirearchy we have vertex colours but in objparser we use getVector3 if the line starts with v. So even if there are vertex colours we discard them

**Comment by kimkulling** [comment]
I see, the obj format supports some more surprises for me: http://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files

Thanks for the hint, I will fix that issue.

**Comment by sahilagnihotri** [comment]
You are welcome :) Another suggestion in formats where vertex colors doesnt exists, we give zero since that is default value which can sometimes give illusion that might not exist in file. Perhaps -1 or smthng else is a better defaullt maybe ? then you can have a compare againt that and know that ok its not that the library didnt read it from file, format doesnt support it.

**Comment by kimkulling** [comment]
Fixed by  886cea2.

**Comment by aybe** [comment]
Could you upgrade the OBJ exporter to also write vertex colors when there are any ?

Thank you !
