### ISSUE TITLE
AndroidJNIIOSystem.h 

### ISSUE THREAD

**Issue by JCLengeling** [assimp/assimp#810]
The AndroidJNIIOSystem.h in the  file is no longer available in the assimp/port/AndroidJNI/
directory on the master branch; older versions can be found in the history though

**Comment by kimkulling** [comment]
It not located here: https://github.com/assimp/assimp/tree/master/include/assimp/port/AndroidJNI

**Comment by JCLengeling** [comment]
Aah srry thx
