### ISSUE TITLE
Memory leak when using Assimp

### ISSUE THREAD

**Issue by Styxsz** [assimp/assimp#815]
This is a reopen of this: 
https://github.com/assimp/assimp/issues/708

---

So I've made a simple OpenGL application using Assimp for the model loading and I've noticed that my application is leaking some memory at startup.

I've tracked down the leaks a bit with several tools like:

The standard visual studio leak detector which outputs a bunch of leaks of this form:
{170} normal block at 0x00C84B58, 8 bytes long.
 Data: < 9      > CC 39 D9 01 00 00 00 00 
{169} normal block at 0x00C84D50, 8 bytes long.
 Data: <\9      > 5C 39 D9 01 00 00 00 00 
{168} normal block at 0x00C84AE8, 8 bytes long.
 Data: < ;      > 1C 3B D9 01 00 00 00 00 
2."Deleaker" which detects about 600 leaks with "no source file" which (i assume) basically means the memory leak isn't in my written code.

3."Dr Memory" which detected about 100 "INVALID HEAP ARGUMENT" leaks e.g:

Error #1: INVALID HEAP ARGUMENT to free 0x01063250 # 0 replace_operator_delete_nothrow [d:\drmemory_package\common\alloc_replace.c:2935]

 1 assimp-vc130-mtd.dll!std::_Deallocate<> [c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0:138]

 2 assimp-vc130-mtd.dll!std::allocator<>::deallocate [c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0:640]

 3 assimp-vc130-mtd.dll!std::_Wrap_alloc<>::deallocate [c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0:911]

 4 assimp-vc130-mtd.dll!std::_Vector_alloc<>::_Free_proxy [c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector:590]

 5 assimp-vc130-mtd.dll!std::_Vector_alloc<>::~_Vector_alloc<> [c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector:552]

 6 assimp-vc130-mtd.dll!std::vector<>::~vector<> [c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector:976](and so on)

And Dr Memory actually describes every single leak that im getting with "assimp-vc...."

Something I've noticed while trying to track the leak down:
If I use the standard Visual Studio leak detector (_CrtDumpMemoryLeaks()) in an empty main function (note that I still link to all my libraries and include their headers etc.) it shows the exact same leaks as if I would run my program normally.

So I'm assuming that there is a bug in Assimp or it's a false positive that I maybe should just ignore?
I would appreciate any help regarding on how to deal with it.

Also some other things on what compiler / assimp version I'm using:

Visual Studio Community 2015
I tried an unstable Assimp release (3.2) and the latest stable release (3.1.1) and the latest Github version (as of 04 March 2016).
Windows 10 x64

**Comment by kimkulling** [comment]
At first thanks a lot for your report. No code means that deleaker cannot resolve via gdb where the source code from assimp is stored. Are all gdb's in place and have you configured the path to the source directory?

**Comment by kimkulling** [comment]
We are checking this with clang ( which is part of our CI ) and the issue got fixed.
