### ISSUE TITLE
Wrong normals when importing .blend

### ISSUE THREAD

**Issue by Enhex** [assimp/assimp#816]
Exporting from Blender to .dae/.fbx and then importing the .dae/.fbx gives a correct result:
![](http://i.imgur.com/IVE9VKo.jpg)
![](http://i.imgur.com/Ccpnmss.jpg)

Importing the .blend file directly gives wrong normals:
![](http://i.imgur.com/gBCXxvA.jpg)
![](http://i.imgur.com/wadD2Fh.png)

It seems to happen when "Auto Smooth" is enabled for the mesh in Blender, and the model has sharp edges (Mark Sharp).

**Comment by kimkulling** [comment]
Which options were enabled?

**Comment by Enhex** [comment]
The model has Sharp Edges (Mark Sharp) in Blender.

**Comment by stephengold** [comment]
Considering the discussion at https://github.com/assimp/assimp/issues/5348 perhaps this issue should be closed.
