### ISSUE TITLE
gltf export problems

### ISSUE THREAD

**Issue by ftrastour** [assimp/assimp#818]
Assimp application failed to create gltf files:
- with some models, the application crash,

[crash.zip](https://github.com/assimp/assimp/files/165413/crash.zip)

- with some others the application generates invalid gltf files with only : 
{
    "asset": {
        "version": 1,
        "generator": "Open Asset Import Library (assimp v3.2.160146130)"
    },
    "scene": "defaultScene"
}

[empty_gltf.zip](https://github.com/assimp/assimp/files/165403/empty_gltf.zip)

The assimp application used for test is from latest team builds (from artifacts) - x86.
Same problems appear with cygwin build of master.

Note that both models load well in assimp_viewer.

**Comment by kimkulling** [comment]
Thank you very much for the report, we will take a look.

**Comment by kimkulling** [comment]
Closed by 11e52dc
