### ISSUE TITLE
Conversion from STL to Collada generates invalid XML

### ISSUE THREAD

**Issue by IgorGee** [assimp/assimp#823]
Within the generated .dae file on line 83 (always?), it contains the following tag:

```
  <node id="<STL_BINARY>" name="<STL_BINARY>">
```

This is not valid XML and proves to be troublesome when passing it through other conversion libraries.
The left angle bracket and right angle bracket should be \&lt; and \&gt; respectively.

```
  <node id="&lt;STL_BINARY&gt;" name="&lt;STL_BINARY&gt;">
```

**Comment by kimkulling** [comment]
Ok, thanks for the report.

**Comment by gkjohnson** [comment]
Is this the only line that needs to be changed?

https://github.com/assimp/assimp/blob/master/code/STLLoader.cpp#L447

I was just bit by this and would expect assimp to output valid xml when writing a Collada file. If that's the only change that needs to be made I'm happy to make a PR!
