### ISSUE TITLE
Crash when freeing the progresshandler

### ISSUE THREAD

**Issue by bartoli** [assimp/assimp#831]
I get crashes in my application, because the pointer to progress handler i pass is a pointer to the class in which i create the Importer object (the object that manages the progress of my task and has acces to my GUI's progress bar). So when my import method goes out of scope, Importer is being destroyed, and tries to destroy the object i am currently in when deleting the progress handler.
Even when not in this case, there could still be issues if the ProgressHandler object was not allocated with the same runtime library as the library.

I worked around it by setting the progresshandler to NULL just before destruction, but it's not something i should have to do.

The library seems to have it's own custom heap. Couldn't it check if the pointer is owned by this heap, and otherwise not free it or something like that?

**Comment by kimkulling** [comment]
Do you have a small example, which descripes your use case a little bit more in detail?

**Comment by bartoli** [comment]
My code is not strippable, so i can't provide a small example immediately.

More details :
I implement a class in my app to import some formats.
That class has interface methods to access the progress bar of the associated user interface, and to detect if the task has been canceled. So i also derived the class from ProgressHandler and overloaded **bool Update(float percentage)**, to update my task's progress, or stop the importing code if there was a request to stop.
Importing code that uses assimp is in that class's run() method. Importer object lifetime is the scope of that run() method
So at the end of the import, when the Importer object was deleted, it tried deleting the pointer to the progress handler, which happens to be the class in which i am, since i am in the scalar destructor of the end() of the run() method of the same class. So the crash occurs in Importer destructor

**Comment by kimkulling** [comment]
Seems to be an ownership issue on your side. The importer owns the progress handler and will release it. You need to deal with this behaviour, I guess.
