### ISSUE TITLE
PLY import doesn't support textures?

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#836]
Here is a ply file with texture: https://storage.googleapis.com/assimp_model_error/Half%20body%20test.zip

I can't see that Assimp is importing texture / UV info from the file...

**Comment by kimkulling** [comment]
I just checked your model and it does not contain a material definition. When adding this to the model it should work.

Kimmi

**Comment by fredrik955** [comment]
But maybe it should not require that? If you open the file in Meshlab, it recognize the texture file through the comment. And the texture coordinates is represented in the file and shouldn't be wasted during the import process...

That's my opinion :)

**Comment by fredrik955** [comment]
I read through the PLYParser code and found a mistake:

When reading this header:
ply
format ascii 1.0
comment VCGLIB generated
comment TextureFile model_texture.jpg
element vertex 25466
property float x
property float y
property float z
property float nx
property float ny
property float nz
property int flags
element face 50944
property list uchar int vertex_indices
property int flags
property list uchar float t
end_header

Assimp doesn't support texture coordinates to be listed inside "face" and not in "vertex".
