### ISSUE TITLE
Simple nullptr issues (easy fix)

### ISSUE THREAD

**Issue by cpyburn** [assimp/assimp#840]
(Universal Windows Project)
![untitled](https://cloud.githubusercontent.com/assets/17934438/14146901/318f866e-f64e-11e5-9186-9b91355296dd.png)

**Comment by sherief** [comment]
Can you contribute a pull request?

**Comment by kimkulling** [comment]
I guess I can fix that one.

**Comment by kimkulling** [comment]
Fixed by f2d5921252187966af977c2822362f1c7667c753 and a2d9cbef7e1ed1b5655262edb7daabeabc00a43a .

Thanks a lot for the report!
