### ISSUE TITLE
exporting point clouds fails

### ISSUE THREAD

**Issue by simonschmeisser** [assimp/assimp#842]
Hi

I'm trying to export a simple point cloud ( just xyz points, nothing else ) using assimp

```
std::vector<XYZ> &points = m_pointMaps[0];

aiScene scene;
scene.mRootNode = new aiNode();

scene.mMeshes = new aiMesh*[ 1 ];
scene.mMeshes[ 0 ] = nullptr;
scene.mNumMeshes = 1;

scene.mMaterials = new aiMaterial*[ 1 ];
scene.mMaterials[ 0 ] = nullptr;
scene.mNumMaterials = 1;

scene.mMaterials[ 0 ] = new aiMaterial();

scene.mMeshes[ 0 ] = new aiMesh();    
scene.mMeshes[ 0 ]->mMaterialIndex = 0;

scene.mRootNode->mMeshes = new unsigned int[ 1 ];
scene.mRootNode->mMeshes[ 0 ] = 0;
scene.mRootNode->mNumMeshes = 1;

auto pMesh = scene.mMeshes[ 0 ];

long numValidPoints = points.size() - sumCutPixels;

pMesh->mVertices = new aiVector3D[ numValidPoints ];
pMesh->mNumVertices = numValidPoints;

int i = 0;
for (XYZ &p : points)
{
    if (isnan(p.x) or isnan(p.y) or isnan(p.z))
        continue;

    pMesh->mVertices[i] = aiVector3D(p.x, p.y, p.z);
    ++i;
}

Assimp::Exporter mAiExporter;
mAiExporter.Export(&scene, "stl", "/home/ros/testExport.stl");

std::cout << mAiExporter.GetErrorString() << std::endl;
```

Am I doing anything stupid or is this just not handled by assimp?

Edit: I mean besides omitting the output:
No output meshes: all meshes are orphaned and are not referenced by any nodes

**Comment by kimkulling** [comment]
Could you please show the log? Maybe some postpocessing steps has removed your points because there were no faces.

**Comment by simonschmeisser** [comment]
Ok, so I enabled the log by adding:

    Assimp::DefaultLogger::create(ASSIMP_DEFAULT_LOG_NAME, Assimp::Logger::VERBOSE);
    Assimp::DefaultLogger::get()->attachStream(Assimp::LogStream::createDefaultStream(aiDefaultLogStream_STDOUT), Assimp::Logger::Debugging);

And now get the following output:
Debug, T0: PretransformVerticesProcess begin
No output meshes: all meshes are orphaned and are not referenced by any nodes

Is that helpful to you?

**Comment by kimkulling** [comment]
I guess you need to adress the node via a face. As far as I know only triangle primitives are currently supported. So maybe that is the reason. We need to check.

**Comment by simonschmeisser** [comment]
@kimkulling has anything happened on this front in the mean time?

**Comment by kkulling** [comment]
No, but I am a little bit frustrated by another defect and I will take care of this to find some motivation.

**Comment by kimkulling** [comment]
Experimental solution merged to master, see https://github.com/assimp/assimp/pull/1935
