### ISSUE TITLE
Crash when loading MTL/OBJ + (fix / workaround)

### ISSUE THREAD

**Issue by shadd3** [assimp/assimp#844]
Hi,
Within the function
void ObjFileMtlImporter::getTexture()

void ObjFileMtlImporter::getTexture() {
    aiString *out( NULL );
    int clampIndex = -1;
.........
    } else if(!ASSIMP_strincmp( pPtr, ReflectionTexture.c_str(), ReflectionTexture.size() ) ) {
        // Reflection texture(s)
        //Do nothing here          <======  (the out pointer is not assigned)
    } else if (!ASSIMP_strincmp( pPtr, DisplacementTexture.c_str(), DisplacementTexture.size() ) ) {
        // Displacement texture
.........
//if (nullptr != out)         <======  (possible FIX)
	out->Set( texture );  <====== (CRASH nullptr)
}

Best regards
Shadd

**Comment by kimkulling** [comment]
In the latest master I see this check against a NULL-ptr:
```cpp
if ( NULL!=out ) {
        out->Set( texture );
    }
```

**Comment by shadd3** [comment]
Effectively, I was using the 3.2 Release
Thanks,
