### ISSUE TITLE
No handling of bad_alloc in OBJ export

### ISSUE THREAD

**Issue by bartoli** [assimp/assimp#845]
When exporting a scene to an obj file (output OBJ file is 53MB), i occasionally get bad_alloc exceptions in void ObjExporter :: WriteGeometryFile() during some append to mOutput, when a resize() of the buffer fails.
In that case, nothing is handled and my whole appliction crashes. Would it be possible to catch the bad_alloc here and in WriteMaterialFile(), then propagate the error so that Exporter::export returns aiReturn_OUTOFMEMORY instead of making it all crash?

**Comment by kimkulling** [comment]
Closed by 8b2f1085c77ba5805f3f6c3c34d3657f54e6e952
