### ISSUE TITLE
No textures in fbx exported from revit.

### ISSUE THREAD

**Issue by gev29** [assimp/assimp#852]
I'm using the latest version of Assimp and 3.0 version of Assimp.Net. After importing an fbx file (**which contains embedded textures and was exported from revit**), all the materials/textures were lost.

```
AssimpImporter importer = new AssimpImporter();
Scene model = importer.ImportFile(path + '/' + modelName, PostProcessSteps.None);
```

`model.TextureCount` gives 0.

any help is appreciated.

**Comment by kimkulling** [comment]
Embedded texture support in FBX shall be fixed now on latest master.
