### ISSUE TITLE
Android.mk and Application.mk are notre compatible with  ndk r11c

### ISSUE THREAD

**Issue by vlj** [assimp/assimp#853]
With ndk r11c on Windows x86_64 I can't build assimp with ndk-build. 
It looks like stlport doesn't have some template like unique  ptr.
Using c++11 stl implementation allows to go further but the build still fails. 

I can't post a build log at will do tomorrow.

**Comment by vlj** [comment]
With gnustl_static and stlport_static :
https://gist.github.com/vlj/8dda74fba0f446f17fb511e877156b36

std::shared_ptr and std::unique_ptr are not available.

With c++11_static and "APP_CPPFLAGS += -frtti" parameter it go further, I'm having trouble with  "revision.h" not being properly generated.

**Comment by vlj** [comment]
Android build doesn't find the rapidjson repo :
https://gist.github.com/vlj/2974575ee32a08f741626aa560eb9044

**Comment by kimkulling** [comment]
Works for me with the latest version of our CMake-build. Could you please check this issue again and reopen this issue if it is still there? We eabled C++11 support and this should help.
