### ISSUE TITLE
Build fails on MinGW-w64 (gcc 5.3.0) due to missing -std=c++11 flag

### ISSUE THREAD

**Issue by Squareys** [assimp/assimp#855]
Hello everybody!

I am compiling on MinGW-w64 with gcc 5.3.0 32bit, Windows 10 64bit. It turns out that building assimp fails with the following message:

```
C:/MinGW/i686-w64-mingw32/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
```

This seems to be a result of MinGW being forgotten in [this](https://github.com/assimp/assimp/commit/b573676a1b69f8cc16bd644b269134cc754edede) commit.

After you fix that you will find a new error:
```
[ 93%] Building CXX object code/CMakeFiles/assimp.dir/__/contrib/clipper/clipper.cpp.obj
In file included from C:\Users\Squareys\repos\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:35:0:
C:/Users/Squareys/repos/assimp/contrib/poly2tri/poly2tri/common/utils.h:43:29: error: 'M_PI' was not declared in this scope
 const double PI_3div4 = 3 * M_PI / 4;
                             ^
C:\Users\Squareys\repos\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc: In member function 'void p2t::Sweep::FillAdvancingFront(p2t::SweepContext&, p2t::Node&)':
C:\Users\Squareys\repos\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:234:17: error: 'M_PI_2' was not declared in this scope
     if (angle > M_PI_2 || angle < -M_PI_2) break;
                 ^
C:\Users\Squareys\repos\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:244:17: error: 'M_PI_2' was not declared in this scope
     if (angle > M_PI_2 || angle < -M_PI_2) break;
                 ^
code\CMakeFiles\assimp.dir\build.make:4012: recipe for target 'code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/sweep.cc.obj' failed
mingw32-make[2]: *** [code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/sweep.cc.obj] Error 1
```
Which I did not have time to look into in greater detail yet.

Thank you for maintaining this project!

Regards,
Jonathan (Squareys).

**Comment by Squareys** [comment]
The error refers to [poly2tri/poly2tri/sweep/sweep.cc#L234](https://github.com/assimp/assimp/blob/master/contrib/poly2tri/poly2tri/sweep/sweep.cc#L234) at which  `M_PI_2` should actually be defined, since `<math.h>` is included via [poly2tri/common/utils.h](https://github.com/assimp/assimp/blob/master/contrib/poly2tri/poly2tri/common/utils.h). I cannot find out why it is not. Any ideas?

**Comment by kimkulling** [comment]
Hopefully c++11 support for mingw is enabled now. Thanks a lot for the report!

**Comment by Squareys** [comment]
@kimkulling Thanks, it is indeed! The other issue still remains, though.

**Comment by Squareys** [comment]
It turns out `M_PI` is not in the C++ standard as of C++99 [(Also see this stackoverflow for more information)](http://stackoverflow.com/questions/29264462/m-pi-not-available-with-gcc-std-c11-but-with-std-gnu11). Therefore you should probably define it yourself.

I have prepared a pullrequest.

**Comment by kimkulling** [comment]
Merged

**Comment by Squareys** [comment]
Everything compiles now! Thanks :)
