### ISSUE TITLE
Building with xcode

### ISSUE THREAD

**Issue by smekadin** [assimp/assimp#856]
Hello!
I am trying to build assimp on os x with xcode but when i open the xcode 6 workspace and try to build it, i get this error and i dont know how to fix it. I also tried to generate project using Cmake but i get "Command /bin/sh failed with exit code 2". What is this?

**Comment by kimkulling** [comment]
Do you have some more informaton from the cmake run? Maybe you can provide us the complete output in your shell?

Thanks a lot and thanks a lot as well for the report!

**Comment by kimkulling** [comment]
Any updates?

**Comment by kimkulling** [comment]
Should be fixed now.

**Comment by YiYinYinguu** [comment]
Have you solved this problem? I also had this question.
