### ISSUE TITLE
Assimp failes to compile on some linux systems (gnu_dev_major).

### ISSUE THREAD

**Issue by ciechowoj** [assimp/assimp#857]
Errors:

    In file included from /home/wojciech/assimp/code/./../include/assimp/ai_assert.h:45:0,
                     from /home/wojciech/assimp/code/GenericProperty.h:45,
                     from /home/wojciech/assimp/code/BaseProcess.h:48,
                     from /home/wojciech/assimp/code/ProcessHelper.h:52,
                     from /home/wojciech/assimp/code/AssxmlExporter.cpp:45:
    /home/wojciech/assimp/code/AssxmlExporter.cpp: In function ‘int Assimp::AssxmlExport::ioprintf(Assimp::IOStream*, const char*, ...)’:
    /home/wojciech/assimp/code/AssxmlExporter.cpp:81:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         ai_assert( nSize < Size );
                            ^
    /home/wojciech/assimp/code/AssxmlExporter.cpp:81:5: note: in expansion of macro ‘ai_assert’
         ai_assert( nSize < Size );
         ^
    /home/wojciech/assimp/code/AssxmlExporter.cpp:76:12: warning: unused variable ‘len’ [-Wunused-variable]
         size_t len( strlen( format ) );
                ^
    /home/wojciech/assimp/code/AssxmlExporter.cpp: In function ‘void Assimp::AssxmlExport::WriteDump(const aiScene*, Assimp::IOStream*, bool)’:
    /home/wojciech/assimp/code/AssxmlExporter.cpp:203:35: error: ‘major’ was not declared in this scope
         ioprintf( io, header.c_str(), major, minor, rev, curtime, scene->mFlags, 0 );
                                       ^
    /home/wojciech/assimp/code/AssxmlExporter.cpp:203:42: error: ‘minor’ was not declared in this scope
         ioprintf( io, header.c_str(), major, minor, rev, curtime, scene->mFlags, 0 );
                                              ^
    make[2]: *** [code/CMakeFiles/assimp.dir/AssxmlExporter.cpp.o] Error 1
    make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
    make: *** [all] Error 2

Caused by following code in `assimp/code/AssxmlExporter.cpp`:

     const unsigned int major( aiGetVersionMajor() );
     const unsigned int minor( aiGetVersionMinor() );
     const unsigned int rev( aiGetVersionRevision() );
     const char *curtime( asctime( p ) );
     ioprintf( io, header.c_str(), major, minor, rev, curtime, scene->mFlags, 0 );

Reason: similar to [this](http://stackoverflow.com/questions/22240973/major-and-minor-macros-defined-in-sys-sysmacros-h-pulled-in-by-iterator).

**Comment by kimkulling** [comment]
Thanks for the report, I was not aware that there are any system-specific macros in lower-case letters. Hopefully this issue should be fixed now.

**Comment by ciechowoj** [comment]
Thanks, that solves the problem.
