### ISSUE TITLE
IOE Error

### ISSUE THREAD

**Issue by swethmandava** [assimp/assimp#866]
Downloaded pyassimp through pip. I get the following error now. Can't figure what the problem is

IOError: Failed to interpret file '/home/swetha/catkin_ws/src/planning_inspection/rr_planning_inspection/models/polygonal_prism.dae' as a pickle

**Comment by kimkulling** [comment]
I wounder why pip tries to validate before installing. I will try to reproduce this issuue.

**Comment by kimkulling** [comment]
Tried it again and the issue seems to be gone. I will close this one. Please reopen if you stll see this bad behaviour of pip.
