### ISSUE TITLE
Animation doesn't work for scenes with duplicate names

### ISSUE THREAD

**Issue by nopjia** [assimp/assimp#869]
Both `aiNodeAnim` and `aiMeshAnim` both refer to their target node/mesh using the name. This doesn't work in the case where names are not unique, and unique names are not required. Instead, it should be using the index number to refer to the corresponding node/mesh.

**Comment by kimkulling** [comment]
Sounds logic, just a fix is needed. Thanks a lot for the report and investigation.

**Comment by nopjia** [comment]
Great. Be sure to mention this PR or me when the fix is in. Will do a workaround for the time being.
Thanks again for your active commitment and all your work!

**Comment by nopjia** [comment]
Hm. Just realized that while this works well for meshes, it doesn't work for nodes, since nodes are stored in a tree structure as opposed to a list, and thus they do not have an associated index number.

I have limited knowledge of assimp importers, but would it be possible to reference via actual pointer? In any case, we'd need some other unique way to reference nodes.

**Comment by smokesugar** [comment]
I am having this issue too. Has it been fixed?

**Comment by kimkulling** [comment]
The name is the reference you need. The name stored in the node is corresponding to the name stores in the meshes.
