### ISSUE TITLE
Collada importer ignores library_animation_clips.

### ISSUE THREAD

**Issue by sherief** [assimp/assimp#87]
Just what it says on the can. See Collada Spec 1.4 page 48. A sample file can be found at https://dl.dropboxusercontent.com/u/24735880/TurbochiFromXSI.dae .

**Comment by kimkulling** [comment]
The link is dead. Could you please provide a workinng one? Sorry for the late answer!

**Comment by sherief** [comment]
Haha no worries, I'll get a copy of that file soon.

**Comment by kimkulling** [comment]
any updates :-)?

**Comment by sherief** [comment]
Attached.
[TurbochiFromXSI.dae.zip](https://github.com/assimp/assimp/files/644832/TurbochiFromXSI.dae.zip)

**Comment by kimkulling** [comment]
Thanks!

sherief <notifications@github.com> schrieb am So., 11. Dez. 2016, 23:02:

**Comment by kimkulling** [comment]
This feature is supported in the latest version.
