### ISSUE TITLE
Expected different index count in <p> element

### ISSUE THREAD

**Issue by lukes3315** [assimp/assimp#870]
Hey guys,
I've been downloading models from 3dwarehouse in the collada format, which is supported by ofAssimpLoader, all the models I download get loaded well in the Mac OS X's preview.
But with your stuff it never works, it always throws:
[ error ] ofxAssimpModelLoader: loadModel(): Collada: /private/var/mobile/Containers/Bundle/Application/myapp.app/model.dae - Expected different index count in <p> element.

Thanks,
Lucas.

**Comment by kimkulling** [comment]
Do you have a small model to reproduce this issue? And thank you very much for the report.

**Comment by lukes3315** [comment]
You will find the test model attached.

Let me know how it goes, thanks!
[model.dae.zip](https://github.com/assimp/assimp/files/248037/model.dae.zip)

**Comment by kimkulling** [comment]
This is an issue in the model. For instance there is a lne definition like this:
```
<lines count="391" material="Material4">
  <input offset="0" semantic="VERTEX" source="#ID135" />
  <p>9 11 56 57 226 225</p>
</lines>

```
There are only 6 indices stored, but the count says 391. So this warning is correct. Seems to be an issue with the used exporter.

**Comment by lukes3315** [comment]
It should at least display the model right, it doesn't, whereas Mac OS X's preview
displays it properly.

**Comment by kimkulling** [comment]
On my machine I can see the model. Even the import will not be stopped. We are internally fixing the index count, print one warning and then go ahead.

**Comment by jinfagang** [comment]
@kimkulling 26 years later,  that model still can not be loaded. The macOS's fault preview load this .dae perfectly.

So it the file's problem?
