### ISSUE TITLE
64 bit static and dynamic library building?

### ISSUE THREAD

**Issue by iUltimateLP** [assimp/assimp#871]
Hey, great work here!
I need AssImp in a static 64 bit library (.lib) and in a dynamic 64 bit library (.dll), but I don't know how to build it, cause the configuration isn't there. Can anyone help me?
Thanks :)

**Comment by kimkulling** [comment]
At the moment I do not see an opton to enable this via cmake. So what you can so is generate the project-files for VS and enable 64bit manually.

**Comment by iUltimateLP** [comment]
In the precompiled binary set, there are 64 bit binaries.. Could you explain to me how to enable 64bit manually?

**Comment by kimkulling** [comment]
You can do this in Visual Studio, Project settings -> Linker -> Advanced -> Target compiter -> machine X64

**Comment by iUltimateLP** [comment]
I changed the Target machine to X64, but the dll is still the same size than before.. Seems strange

**Comment by kimkulling** [comment]
Have you done a clean build? An where is the dll located?

**Comment by iUltimateLP** [comment]
The new DLL is located where the old one was aswell: assimp/bin/Debug/assimp-vc140-mt.dll

**Comment by amc522** [comment]
You can generate an x64 bit Visual Studio project using `cmake . -G"Visual Studio 14 Win64"`

**Comment by kimkulling** [comment]
Ok, thanks a lot for the tipp. I created a blog-post how to do this here: http://kimkulling.de/?p=15

**Comment by iUltimateLP** [comment]
Nice, Thanks!

**Comment by DrNoodles** [comment]
@kimkulling your link above is dead. Here's a working one to your blog:
http://kimkulling.de/2016/05/02/build-asset-importer-lib-for-64bit-with-visual-studio-from-source-repo/
