### ISSUE TITLE
Reduce number of vertices/triangles using pyassimp

### ISSUE THREAD

**Issue by swethmandava** [assimp/assimp#872]
Hey, is there anyway I can set the limit for maximum number of triangles in the mesh?

As I'm performing tsp, number of triangles is very critical and I would like to reduce them as much as possible,

Thanks,
Swetha

**Comment by kimkulling** [comment]
You can use **SplitLargeMeshesProcess_Triangle** to split the meshes. Defining an upper limit for triangle is possible via **OptimizeMeshesProcess** via the property **AI_CONFIG_PP_SLM_TRIANGLE_LIMIT**.
