### ISSUE TITLE
Print mesh.normals leads to null pointer access

### ISSUE THREAD

**Issue by swethmandava** [assimp/assimp#874]
/usr/lib/python2.7/dist-packages/pyassimp/pyassimp.pyc in **str**(self)
     71 
     72     def **str**(self):
---> 73         return str([x for x in self])
     74 
     75     def **repr**(self):

/usr/lib/python2.7/dist-packages/pyassimp/pyassimp.pyc in next(self)
     53             c = self.count
     54             self.count += 1
---> 55             return self._GetData(c)
     56 
     57     def __getitem__(self, index):

/usr/lib/python2.7/dist-packages/pyassimp/pyassimp.pyc in _GetData(self, index)
     38             item = getattr(self.instance, self.dataName)[self.i][index]
     39         else:
---> 40             item = getattr(self.instance, self.dataName)[index]
     41         if hasattr(item, 'contents'):
     42             return item.contents._init()

ValueError: NULL pointer access

A few of the collada files that I have been working on give out this error of null pointer access when using pyassimp. I can't figure why this occurs. Previous exports from sketch up worked fine.

**Comment by kimkulling** [comment]
Which version of assetimporterlib is in use?
