### ISSUE TITLE
glTF Support: 

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#883]
Many test models (e.g., 2CylinderEngine) and also the model in the repository appear to have their hierarchy imported incorrectly and/or textures flipped.

See for instance:

http://i.imgur.com/RIQ9uS6.png

**Comment by smalcom** [comment]
in last version everything is fine

![gltf_motor](https://cloud.githubusercontent.com/assets/19540675/17292472/f737374e-57f2-11e6-9a07-cc27f98fcf94.png)
