### ISSUE TITLE
model distortion on fbx import

### ISSUE THREAD

**Issue by jdicksen** [assimp/assimp#884]
I want to use some animated .blend files in my game. Since assimp can't import animations from .blend files I'm converting them with blender 2.77 to .fbx file format. Opening the resulting file with open3dmod (v1.1 latest) gives a correct looking bind position but heavy distortions on animations. To ensure its not the model I tested it with the Autodesk FBX Converter 2013.3 (viewer included) which plays undistorted animations. Further I tried all different fbx file versions (2013, 2012, 2011 etc), which gives all the same result. Additionally the Win10 3D builder plays the attack animation without problems.

Using assimp 3.2 library in my own code gives the same distorted animations.

testmodel: http://opengameart.org/content/animated-knight-walk-edit
[open3dmod bindposition](http://i.imgur.com/EkVHgB6.jpg)
[open3dmod animated](http://i.imgur.com/LAowpjz.jpg)
[fbx viewer animated](http://i.imgur.com/N73su2D.jpg)

**Comment by kimkulling** [comment]
Please try to use the latest master. We fixed a lot of issues right there.
