### ISSUE TITLE
Disabling IRR causes undefined reference to `Assimp::IRRMeshImporter::IRRMeshImporter()'

### ISSUE THREAD

**Issue by fire** [assimp/assimp#887]
Setting ASSIMP_BUILD_IRR_IMPORTER to off causes assimp to not compile.

See https://github.com/urho3d/Urho3D/issues/1362

**Comment by kimkulling** [comment]
You mean ASSIMP_BUILD_NO_IRRMESH_IMPORTER? Thanks for the report, I will fix it!
