### ISSUE TITLE
Too many warnings: anonymous structs are a GNU extension 

### ISSUE THREAD

**Issue by Martinfx** [assimp/assimp#888]
Hi, I compiled assimp, compilation was ok but i have too many warnings.
I have compiler clang version 3.8.0-svn262614-1~exp1 (branches/release_38) and Linux ubutnu 14.04

```
warning: anonymous structs are a GNU extension [-Wgnu-anonymous-struct]
warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
...
```

Here is compilation file.
[warn.zip](https://github.com/assimp/assimp/files/265212/warn.zip)

**Comment by kimkulling** [comment]
Fixed
