### ISSUE TITLE
std::to_string do not exist on android NDK with GCC 4.9

### ISSUE THREAD

**Issue by arkeon7** [assimp/assimp#892]
std::to_string do not exist on android NDK with GCC 4.9, so several impoter / exporters do not build anymore

**Comment by kimkulling** [comment]
Could you please check you compiler call? It should contain a line with the following flag: 
`std=c++11`
Background: you need c++11 enabled and I am not sure if we took all needed versions of gcc in account when enabling this feature. Normally std::to_string is provided by g++4.9 ( as far as I know).

**Comment by arkeon7** [comment]
Yes I already use std=c++11.
std::to_string and std::strtof do not exist but std::strtod is known and working.

it seems to be a limitation of android NDK with gcc.

**Comment by chenming5828** [comment]
SO am I .
error: 'to_string' is not a member of 'std'

**Comment by kimkulling** [comment]
Could you please send me a build log?

**Comment by chenming5828** [comment]
[putty.txt](https://github.com/assimp/assimp/files/281514/putty.txt)
Here is my build log.

**Comment by chenming5828** [comment]
still the error std::to_string do not exist
to_string mybe define in std namespace.

**Comment by jdduke** [comment]
FWIW, std::to_string is in fact supported by the NDK, but it requires use of the LLVM libc++ runtime (see also https://developer.android.com/ndk/guides/cpp-support.html#cs).

**Comment by arkeon7** [comment]
Yes but the NDK 10e still on gcc.
GCC on NDK is only deprecated since the last version.
Nvidia tegra pack still use NDK 10e by the way.

**Comment by jdduke** [comment]
You should be able to use libc++ with both gcc and clang.
