### ISSUE TITLE
glTF: wrong usage of memcmp?

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#893]
kimmi: code/glTFAsset.inl:291:13: warning: ignoring return value 
5:14:28 PMturol      of function declared with pure attribute [-Wunused-value] 
5:14:28 PMturol            memcmp(dataURI.data, this->mData.get(), dataURI.dataLength); 
5:14:36 PMturoli think you meant "memcpy"

**Comment by turol** [comment]
Because kimkulling fails at pasting: 
```
code/glTFAsset.inl:291:13: warning: ignoring return value of function declared with pure attribute [-Wunused-value]
memcmp(dataURI.data, this->mData.get(), dataURI.dataLength);

```
@otgerrogla your code.

**Comment by otgerrogla** [comment]
Yeah, sorry, it was a typo!
