### ISSUE TITLE
Sanitized FBX bone imports

### ISSUE THREAD

**Issue by kewur** [assimp/assimp#894]
Was trying to construct the bone hierarchy (using Unity) from the nodes hierarchy with the FBX importer and I noticed that there are some unnecessary nodes in the hierarchy with the names appended with the"_$AssimpFBX$ magic string. As far as I can tell these nodes just contain information about the transforms for a specific node. But obviously I don't want these in my real skeleton hierarchy (even though they probably would still work if I constructed the skeleton with these nodes). Also would make the code look clenaner if I take them out.

I'm planning to do a "sanitation" loop to get rid of these nodes and passing their transforms down to a real node. But I was hoping that I wouldn't have to do this, so my question is:

Is there an option somewhere I can set so that it never exports node hierarchy with these "dummy" nodes?

Edit: I'm also guessing the sole purpose of these nodes are to preserve the bind frame of the improted model? But I can't be sure.

**Comment by kimkulling** [comment]
I just checked the code. At the moment not post-process checks for these kinds of generated bones. Maybe we need to check for them.

**Comment by yushroom** [comment]
Same problem. I imported the fbx model into Unity and Maya to have a check. But can not find these "dummy" nodes. It seems that Assimp inserted these nodes for some reasons.

**Comment by Lumak** [comment]
This issue was fixed in Urho3D AssetImporter code for FBX files: https://github.com/urho3d/Urho3D/blob/master/Source/Tools/AssetImporter/AssetImporter.cpp

assimp already handles suppressing pivot nodes via AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS set to false.  It's the animation process that's missing to do the same.

**Comment by yushroom** [comment]
@Lumak
It works. Thanks.

**Comment by yangyanzhe** [comment]
@Lumak @yushroom 
I didn't quite understand how to handle it. Where to set AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS? Or does it mean using Urho3D AssetImporter instead?

**Comment by sanonz** [comment]
Is this problem solved?
