### ISSUE TITLE
How to use the mColors of a aiMesh

### ISSUE THREAD

**Issue by JasonWinston** [assimp/assimp#897]
It seems that the mColors,member of a aiMesh,is useless.What is the difference between "mColors" and   
"pOut" obtained through "aiMaterial::Get (const char *pKey, unsigned int type, unsigned int idx, Type &pOut)".

**Comment by smalcom** [comment]
aiMaterial is used when you set material of object e.g. thru GL_COLOR_MATERIAL. And also use lighting and other stuff. mColors is used when you do not use materials and said above and point color for vertices or faces thru glColor.
