### ISSUE TITLE
SMD Import Texture Garbage at end of String

### ISSUE THREAD

**Issue by Spirrwell** [assimp/assimp#899]
Hi there, there seems to be an issue with the SMD importer pertaining to texture strings.

When calling GetTexture:

pMaterial->GetTexture(aiTextureType_DIFFUSE, 0, &Path, NULL, NULL, NULL, NULL, NULL) == AI_SUCCESS

The path seems to have some sort of garbage at the end of the string and for some reason won't load a texture unless I copy it to an std::string and do stringName.pop_back(). I think it may be an issue with not NULL terminating the string or something to that effect.

When I try to print the name to the console with anything else that I'm printing with it, the name kind of gets overwritten.

Anyway, it seems like a simple fix, but I just can't read some of the C style code you got to understand what's going on. If I figure it out, I'll do a pull request.

If you need an example model and texture, here you go:

https://drive.google.com/file/d/0B0a1deqARl2MRmlTd1lTUGNpVnM/view?usp=sharing

**Comment by turol** [comment]
The file has windows-style "\r\n" line endings. Looks like the parser doesn't correctly strip the "\r". Converting the file to unix-style line endings should work around this bug. The proper fix would be to either fix the parser or convert the line endings after load before starting the parse.

**Comment by Spirrwell** [comment]
Hm, I just tried in Notepad++ to do an EOL conversion to Unix\Mac, but nothing changed on importing.

**Comment by turol** [comment]
Here changing it to unix-style removed the "\r" but now it left the "\n". Looks like the parser needs some work. Line 1026 in SMDLoader.cpp looks like a likely culprit.

**Comment by Spirrwell** [comment]
Ah yes, I just did a test with the strings.

fullPath.erase(std::remove(fullPath.begin(), fullPath.end(), '\n'), fullPath.end());
fullPath.erase(std::remove(fullPath.begin(), fullPath.end(), '\r'), fullPath.end());

Fixed it temporarily for me, but yes, that does seem to be the bug.

**Comment by turol** [comment]
This:
`std::string(szLast,(uintptr_t)szCurrent-(uintptr_t)szLast)
`
is not clean code. std::string also has a constructor which takes a pair of iterators. This might fix the issue:

`std::string(szLast, szCurrent - 1)
`

I haven't run regression tests on that so no idea if it breaks something else

**Comment by Spirrwell** [comment]
I'll sync my Git and give that a try.

**Comment by Spirrwell** [comment]
While that compiles and works, it's still left with the /r problem on Windows line endings and /n problem on Linux line endings Does that have to do with that while loop there? It seems to do a check, but it's confusing how it works.

**Comment by turol** [comment]
It's looking for the first space or newline character. It should then cut the texture name to that. I think the post-increment might be screwing something up.

**Comment by Spirrwell** [comment]
Yep, I changed it to 
while (!IsSpaceOrNewLine(*++szCurrent)); 

instead of :

while (!IsSpaceOrNewLine(*szCurrent++));

Seems to work.
