### ISSUE TITLE
Can't import model on OS X 10.11

### ISSUE THREAD

**Issue by AntiMoron** [assimp/assimp#901]
```obj-c++

#import <Foundation/Foundation.h>
#include<assimp/scene.h>
#include<assimp/Importer.hpp>
#include<assimp/postprocess.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSString* modelPath = @"model/figure.FBX";
        Assimp::Importer modelImporter;
        NSLog(@"Read Model File : %s", modelPath.UTF8String);
        const aiScene* scene = modelImporter.ReadFile(modelPath.UTF8String, aiProcessPreset_TargetRealtime_MaxQuality);
        if(!scene)
        {
            NSLog(@"%s", modelImporter.GetErrorString());
            return -1;
        }
        
    }
    return 0;
}
```

Gets such outputs:

```Unable to open file "figure.FBX".```

**Comment by kimkulling** [comment]
Have you tried to load it via an absolute path?

**Comment by AntiMoron** [comment]
@kimkulling  Yes, I've tried that.  I just used ```~``` to hide my personal infos.

**Comment by AntiMoron** [comment]
BTW, I've tried with ```FBXSDK 2015```. 
It seems find to read the scene.
But still need assimp. FBX SDK is still harder to use on comparation with assimp.

**Comment by kimkulling** [comment]
Unfortunately I do not have a iMac to reproduce the issue. So what you need to answer:
- Have you build AssetImporterLib on your own, if yes is FBX support included
- Can you debug to the place where the loading will be started: do you have an "File-Not-Found" or a "No Access"-issue
- Any other things which are suspicious?

**Comment by AntiMoron** [comment]
- Yes, I built ```libassimp.a     libzlibstatic.a``` on my macbook. If these two libs are 'AssetImporterLib'.
- I used absolute path for file parsing. And tested with FBX SDK 2015 which seems fine. So I guess neither "File-Not-Found" nor "Access Permission" should be the issue.
- Nope. I don't have any clue. I'll check assimp code later.

**Comment by AntiMoron** [comment]
@kimkulling  Hi, it's been days and I get an obj model file which sizes 3MB.

When try to open it with SimpleAssimpViewX (the sample project cmake generates), it always fail.
And I try to log out the error message it complains:
 ```SimpleAssimpViewX[65668:5287914] : OBJ-file is too small.```
After I check into [assimp code](https://github.com/assimp/assimp/blob/6b243230b29d14e778563f2855164f172a00ca77/code/ObjFileImporter.cpp). I found that the ObjMinSize is 16 bytes. The code that trigger this exception is as follows.

```c++
void ObjFileImporter::InternReadFile( const std::string &file, aiScene* pScene, IOSystem* pIOHandler) {
    // Read file into memory
    static const std::string mode = "rb";
    std::unique_ptr<IOStream> fileStream( pIOHandler->Open( file, mode));
    if( !fileStream.get() ) {
        throw DeadlyImportError( "Failed to open file " + file + "." );
    }

    // Get the file-size and validate it, throwing an exception when fails
    size_t fileSize = fileStream->FileSize();
    if( fileSize < ObjMinSize ) {
        throw DeadlyImportError( "OBJ-file is too small.");
    }
```

I guess there's something wrong with the implementation for OS X. If so, it's no wonder FBX files can't be imported correctly.

**Comment by AntiMoron** [comment]
I modified [this code](https://github.com/assimp/assimp/blob/6b243230b29d14e778563f2855164f172a00ca77/code/DefaultIOStream.cpp) locally just to add some logs.

```c++
size_t DefaultIOStream::FileSize() const
{
    std::printf("Default IO Stream!\n");
    if (! mFile || mFilename.empty()) {
        return 0;
    }

    if (SIZE_MAX == cachedSize) {
#if defined _WIN32 && !defined __GNUC__
        struct __stat64 fileStat;
        int err = _stat64(  mFilename.c_str(), &fileStat );
        if (0 != err)
            return 0;
        cachedSize = (size_t) (fileStat.st_size);
#else
        std::printf("non-win: %s\n", mFilename.c_str());
        struct stat fileStat;
        int err = stat(mFilename.c_str(), &fileStat );
        if (0 != err)
            return 0;
        cachedSize = (size_t) (fileStat.st_size);
        std::printf("Cached Size: %zu\n", cachedSize);
#endif
    }
    return cachedSize;
}
```

And what was printed is as follows when executing SimpleAssimpViewX :

```
Default IO Stream!
non-win: /Users/AntiMoron/Downloads/55z27frcahz4-P911GT/Porsche_911_GT2.obj
Cached Size: 0
2016-05-30 15:10:53.123 SimpleAssimpViewX[69644:5430969] 失败: OBJ-file is too small.
```

So I have a version 2 implementation for  ```DefaultIOStream::FileSize``` which just simply specify the exact size of the model file that being tested.

```c++
size_t DefaultIOStream::FileSize() const
{
    std::printf("Default IO Stream!\n");
    if (! mFile || mFilename.empty()) {
        return 0;
    }

    if (SIZE_MAX == cachedSize) {
#if defined _WIN32 && !defined __GNUC__
        struct __stat64 fileStat;
        int err = _stat64(  mFilename.c_str(), &fileStat );
        if (0 != err)
            return 0;
        cachedSize = (size_t) (fileStat.st_size);
#else
 // [!!!] Just simply specify the exact size of the model file that being tested.
        cachedSize = 2984537;
        std::printf("Cached Size: %zu\n", cachedSize);
#endif
    }
    return cachedSize;
}
```

Then It works fine now.
<img width="466" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6587734/15642440/fe849424-2679-11e6-9896-ac92e641f260.png">

**Comment by AntiMoron** [comment]
But!!!

This code works fine!!

```c++
#include <iostream>
#include <sys/types.h>
#include <sys/stat.h>
using namespace std;

int main(int argc, char* argv[]) 
{
    if(argc != 2) 
    {
        cout << "Should be: executable + filePath" << endl;
        return -1;
    }
    struct stat fileStat;
    int err = stat(argv[1], &fileStat);
    if (0 != err)
        return 0;
    unsigned long long cachedSize = (size_t) (fileStat.st_size);
    cout << "File size : " << cachedSize << endl;
    return 0;
}
```

``` 
g++ test.cpp -o t
./t /Users/AntiMoron/Downloads/55z27frcahz4-P911GT/Porsche_911_GT2.obj
```

And that's how I get the size of the model file.

**Comment by AntiMoron** [comment]
Same method as how I succeeded the obj model, the FBX succeeds, too.

**Comment by AntiMoron** [comment]
It is ```DefaultIOStream::FileSize```'s always returning 0 that cause importing problem.

**Comment by kimkulling** [comment]
Have you open your file already?

**Comment by AntiMoron** [comment]
Nope. I tried to handle the file on Windows OS.

**Comment by kimkulling** [comment]
So you are working on which operation system? I tried to reproduce the issue and without knowing this detail it is a little bit difficult :-).

**Comment by AntiMoron** [comment]
@kimkulling  OSX 10.11.5 

Compiler Info:
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix

**Comment by kimkulling** [comment]
I added your working code for the size stat query and added a unittest for it. Hopefully the issue is gone now.
If not, please reopen. And thanks a lot for your help!

**Comment by Darecjo** [comment]
i still have the same issue any solutions ??
