### ISSUE TITLE
Use cmake's FindGTest instad of custom AddGTest.cmake

### ISSUE THREAD

**Issue by Delwin9999** [assimp/assimp#902]
CMake has a built in FindGTest that will allow the uncoupling of GTest from Assimp.  You can keep the download of the repo if it's not found but if there's one on the system it would be nice to use that one.

**Comment by kimkulling** [comment]
Sounds good, I don't like the lookup diuring the build. Thanks for the hint!

**Comment by kimkulling** [comment]
I just added the gtest-source to our repo again. Much easier. Maybe we can look if any gtest-version is installed before using our buildin-version.
