### ISSUE TITLE
D3MFImporter.cpp cannot compile with pre-C++11 compliant compilers

### ISSUE THREAD

**Issue by MattGuerrette** [assimp/assimp#904]
Attempting to compile Assimp with Visual Studio 2012 throws an error in D3MFImporter.cpp
because it is using `std::strtof` which is not implemented in the standard that ships with that compiler toolkit.

**Comment by chenming5828** [comment]
yes,I also meet this error.std::strtof when I compile with NDK

**Comment by kimkulling** [comment]
OK, I guess we need to add an implementation for these functions as well. Thanks for the report!

**Comment by kimkulling** [comment]
Solution is in the pipeline.
