### ISSUE TITLE
CMake generation issues with zlib

### ISSUE THREAD

**Issue by sherief** [assimp/assimp#905]
I tried to generate VC2015 projects for assimp and generation failed with this error:

CMake Error at contrib/zlib/CMakeLists.txt:194 (add_library):
  Cannot find source file:

```
contrib/masmx64/gvmat64.asm
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: zlibstatic

The asm code indeed isn't in the version of zlib packaged with assimp, but the main zlib repo has it at https://github.com/madler/zlib/tree/master/contrib/masmx64

Any idea why we're missing this? Am I configuring something incorrectly perhaps? The generated project files build fine but fail to link due to missing zlib static library.

**Comment by kimkulling** [comment]
This seems to be a special feature of zlib we missed. I guess we need to add these files as well. Thanks for the report.

**Comment by sherief** [comment]
Any chance we could get this fixed soon? Windows builds are broken as of now.

**Comment by BartSiwek** [comment]
Same here. May I suggest reverting the 7207e5117cb3883206fd5b2d432ffc80fce9baaa, fixing it off the master branch and committing again when it not longer breaks builds?

**Comment by sherief** [comment]
I think that should be done, yeah. And in the future, we need some sort of gating to make sure this never happens again. Breaking the build on Windows is a Big Deal.

**Comment by BartSiwek** [comment]
So I did try it myself and it depends a bit how you pull it in.
If you clone, generate the solution and build that seems to be working.
For me - I use Assimp as an ExternalProject in cmake. This scenario is broken.

**Comment by sherief** [comment]
Still an issue with the latest CMake and top-of-tree code as of the time of writing.

**Comment by MauriceH1** [comment]
Still having this issue, Not sure what's going on with it.

**Comment by kimkulling** [comment]
Damned, so in this case our 64bit build is broken.

**Comment by MauriceH1** [comment]
That is indeed what it looks like,

Will do some more testing this evening, hope this issue can get resolved for once and for all!

If you need more info on how I got to the error feel free to message me!
