### ISSUE TITLE
Wrong animation import from FBX file

### ISSUE THREAD

**Issue by ongamex** [assimp/assimp#906]
I've downloaded this model(it's free):
https://www.cgtrader.com/free-3d-models/character-people/fantasy/golem-legion-green-wow
and converted it to *.FBX file via 3ds Max 2016.

The bone transformations (or the hierarchy or something like that) is wrong.
The animation works fine when re imported in 3ds Max.
 it doesn't with Open 3D Model Viewer, and my own skinning implementation.

I'm at master on commit 814d2e7821a5fb34d67e95cfd106d6e7d40ace66 (the latest changes currently).

I'm not sure if posting broken models helps you or not.

**Comment by kimkulling** [comment]
I heard about a lot of broken animations by using the fbx-importer. Hopefully I get the ideas of the author and can help you fast.

**Comment by mesilliac** [comment]
likely fixed by #1806

**Comment by kimkulling** [comment]
Shall be fixed now. Please reopen when issue still exists. I was not able to get the model because hey asked me to pay for it ^^.
