### ISSUE TITLE
Building for x86_64 

### ISSUE THREAD

**Issue by DFGU** [assimp/assimp#913]
Hi there, 
Thank you so much for your work.

I am having some trouble figuring out how to build a OSX static library for x86_64 architecture.
I can build the library statically, but I recieve the following error: 
  `Undefined symbols for architecture x86_64:`

I can not find any online resources that have helped. Any advice you could provide would be greatly appreciated.

Thank you,
David

**Comment by kimkulling** [comment]
Hi,

thanks for the report. Unfortunately I don't have a Mac to debug stuff like this. Could you please post the names of the unresolved symbols. Hopefully I could help you with some more information.

**Comment by kimkulling** [comment]
Should be fixed now.
