### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#914]
Hi,

I sometimes get this OBJ parser error message:
"Converting the string "000000000000000000.00000000" into a value resulted in overflow.".

Is it possible to make a solution for this issue?

**Comment by kimkulling** [comment]
Do you know which exporter will create these kinds of tupels? Because that this value produces an overflow is correct from my point of view.

**Comment by fredrik955** [comment]
I don't know which exporter this was from...
So you don't think it should be treated as 0 even though it contains unnecessary many zeroes?

**Comment by kimkulling** [comment]
For me this value looks like an error. So from my point fo view this behavious is correct.
