### ISSUE TITLE
Triangulate process assertion

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#915]
Hi,

I tried to run this model through the triangulation process: [https://storage.googleapis.com/assimp_model_error/Triangulate_failed.dxf](https://storage.googleapis.com/assimp_model_error/Triangulate_failed.dxf)

But I got this error message: "/assimp/assimp/code/TriangulateProcess.cpp:158: bool Assimp::TriangulateProcess::TriangulateMesh(aiMesh*): Assertion `numOut != pMesh->mNumFaces' failed.
Aborted (core dumped)"

**Comment by kimkulling** [comment]
Interesting, with the latest master I got:

                    ReportError("aiMesh::mFaces[%i] is a POINT but aiMesh::mPrimtiveTypes "
                        "does not report the POINT flag",i);

Which version do you use? And how have you created this model?

**Comment by fredrik955** [comment]
I am using version 3.2.0

**Comment by kimkulling** [comment]
I guess we fixed this issue. PLease reopen when it is still there.
