### ISSUE TITLE
Cmake install bug  on Mac OSX

### ISSUE THREAD

**Issue by leoshine** [assimp/assimp#918]
In code/CMakeLists.txt:
    Line 752 use undefined variable ${LIB_INSTALL_DIR}.  
    This will cause runtime error:  (due to execute wrong command with install_name_tool)
-----------------------------------------------------
dyld: Library not loaded: *******/assimp-3.2/install//libassimp.3.dylib
  Referenced from: *******/assimp-3.2/install/bin/./assimp
  Reason: image not found
Trace/BPT trap: 5

-----------------------------------------------------

[-- Remedy --]

Orignal:
------------------------------------------------------
751  if (APPLE)
752   SET_TARGET_PROPERTIES( assimp PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}")
753  endif()

------------------------------------------------------

Should be changed to:
------------------------------------------------------
751  if (APPLE)
752   SET_TARGET_PROPERTIES( assimp PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/${ASSIMP_LIB_INSTALL_DIR}")
753  endif()

------------------------------------------------------

**Comment by kimkulling** [comment]
Thanks for the report. Could you please prepare a pull request? I don't have any Macs here to test it. Would be great.
