### ISSUE TITLE
FBX importer lost UV.

### ISSUE THREAD

**Issue by tek-nishi** [assimp/assimp#920]
I exported this FBX data with **[Cheetah3D](http://www.cheetah3d.com)**.
(FBX version7.4.0 binary)

**[TEST DATA](https://www.dropbox.com/s/xs4wgiorx11ae6a/test_data.zip?dl=0)**

Load by assimp 3.2, lost UV datas.

Blender import this data normaly.

**Comment by kimkulling** [comment]
As far as I know we fixed this issue already. Please reopen if the issue is still there.
