### ISSUE TITLE
Segmentation Fault on Blender import

### ISSUE THREAD

**Issue by BugGambit** [assimp/assimp#925]
Hi,

I tried to import this file: https://storage.googleapis.com/assimp_model_error/blender_segmentation_fault.blend

With this code:
`importer.SetPropertyFloat(AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE, 45.0f);
importer.SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_LINE | aiPrimitiveType_POINT); //SET THIS TO REMOVE POINTS AND LINES -> HAVE ONLY TRIANGLES

scene = importer.ReadFile(
  filename,
  aiProcess_Triangulate           |
  aiProcess_GenUVCoords           |
  aiProcess_GenSmoothNormals      |
  aiProcess_OptimizeMeshes        |
  aiProcess_OptimizeGraph         |
  aiProcess_FindInvalidData       |
  aiProcess_FixInfacingNormals    |
  aiProcess_JoinIdenticalVertices |
  aiProcess_SortByPType
);`

And got this: Segmentation fault (core dumped)

I am using version 3.2.0

**Comment by kimkulling** [comment]
Fixed right now. See https://github.com/assimp/assimp/pull/4193
