### ISSUE TITLE
ASSIMP_{BIN,INCLUDE,LIB}_INSTALL_DIR variables are used not correcty

### ISSUE THREAD

**Issue by radix-platform** [assimp/assimp#938]
If we set one or all of `ASSIMP_{BIN|INCLUDE|LIB}_INSTALL_DIR` variables like follow:

```
$ cmake -DASSIMP_LIB_INSTALL_DIR=lib32 ..
```

then **CMake** will add `${CMAKE_CURRENT_BINARIES_DIR}` value between `CMAKE_INSTALL_PREFIX` and `ASSIMP_*_INSTALL_DIR` in the generated **cmake_install.cmake** file. So if our build directory equal to `/home/user/prog/build` then libraries will be installed into `${DESTDIR}/home/user/prog/build/usr/lib32` directory.

To fix this issue I can suggest following patch:

```
--- assimp-3.2-orig/CMakeLists.txt	2015-11-03 21:47:37.000000000 +0300
+++ assimp-3.2/CMakeLists.txt	2016-07-06 14:42:59.944796851 +0300
@@ -91,11 +91,11 @@
 ENDIF ( CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR )
 
 # Cache these to allow the user to override them manually.
-SET( ASSIMP_LIB_INSTALL_DIR "lib" CACHE PATH
+SET( ASSIMP_LIB_INSTALL_DIR "lib" CACHE STRING
   "Path the built library files are installed to." )
-SET( ASSIMP_INCLUDE_INSTALL_DIR "include" CACHE PATH
+SET( ASSIMP_INCLUDE_INSTALL_DIR "include" CACHE STRING
   "Path the header files are installed to." )
-SET( ASSIMP_BIN_INSTALL_DIR "bin" CACHE PATH
+SET( ASSIMP_BIN_INSTALL_DIR "bin" CACHE STRING
   "Path the tool executables are installed to." )
 
 IF (CMAKE_BUILD_TYPE STREQUAL "Release")

```

Also in the **assimp.pc** file the exec_prefix defined not correctly and this issue can be fixed by following patch:

```
diff -b --unified -Nr assimp-3.2-orig/assimp.pc.in assimp-3.2/assimp.pc.in
--- assimp-3.2-orig/assimp.pc.in	2015-11-03 21:47:37.000000000 +0300
+++ assimp-3.2/assimp.pc.in	2016-07-06 14:42:59.944796851 +0300
@@ -1,5 +1,5 @@
 prefix=@CMAKE_INSTALL_PREFIX@
-exec_prefix=@CMAKE_INSTALL_PREFIX@/@ASSIMP_BIN_INSTALL_DIR@
+exec_prefix=@CMAKE_INSTALL_PREFIX@
 libdir=@CMAKE_INSTALL_PREFIX@/@ASSIMP_LIB_INSTALL_DIR@
 includedir=@CMAKE_INSTALL_PREFIX@/@ASSIMP_INCLUDE_INSTALL_DIR@/assimp

```

**Comment by kimkulling** [comment]
Great finding. I will try to bring that in.

**Comment by radix-platform** [comment]
Thanks a lot for your work.

**Comment by skylian** [comment]
@radix-platform, is the last line of your patch to assimp.pc above intended or a bug? Shouldn't it be
"includedir=@CMAKE_INSTALL_PREFIX@/@ASSIMP_INCLUDE_INSTALL_DIR@"?

**Comment by radix-platform** [comment]
It depends on your course code. For example in the code/3DSExporter.cpp I see that

#include <assimp/IOSystem.hpp>
#include <assimp/DefaultLogger.hpp>
#include <assimp/Exporter.hpp>

assimp assume that include files are placed in the /usr/include/assimp directory.

We have to check real value of ASSIMP_INCLUDE_INSTALL_DIR variable.

At least in 2016 I use this patch as is without any problems.

**Comment by radix-platform** [comment]
Please look at code/CMakeLists.txt where ASSIMP_INCLUDE_INSTALL_DIR assumes that the real include dir is @ASSIMP_INCLUDE_INSTALL_DIR@/assimp !
