### ISSUE TITLE
Large model issues

### ISSUE THREAD

**Issue by samsinsane** [assimp/assimp#944]
I'm trying to import a relatively large model, it's 8 million vertices and 380MB in OBJ format and 130MB in FBX format. The memory consumption from assimp is quite excessive, at its peak it was around 29GB before settling down to 11GB. This process took over an hour due to my laptop only having 8GB of physical RAM.

I've managed to narrow this issue down to the mini-allocations that occur all throughout the code for the `aiFace` struct. I replaced this with one big allocation (similar to what is done in the "Improve Cache Locality" processing step) and this reduced the peak memory footprint to 1.7GB and loaded in under 16 seconds.

Unfortunately, my solution is very hacky and I've only made this change to the FBX importer and the main culprits in the post processing step. Currently my solution makes the assumption that the different file importers will never do mini-allocations for the indices but this isn't very intuitive nor is it possible to prevent this from occurring.

I think the best solution would be to have another array in the `aiMesh` struct for the indices, and change the `aiFace` struct to have an index into that array instead of a pointer. Unless there's a better or preferred solution to this problem?

I'm also more than happy to make the changes to get this working.

**Comment by kimkulling** [comment]
I saw this issue as well. So having a pool for doing these allocations will be a great idea. I guess we already have an issue in our database to adress this topic but I was never able to work on this.
 My thoughts were as following:
- Prepare a pool for faces and indices.
- Replace the allocs in the code by using this pool allocator
- Maybe make this solution configurable if someone wants to assign his own customized allocator

What do you think?

**Comment by samsinsane** [comment]
I have already started on the solution I suggested above, the pool allocator sounds good but it would be rather inconsistent to have it only apply to faces and indices. Additionally, it would need to be an externally facing API to allow users writing their own importers to allocate faces and indices without crashing when they are deleted.

Unfortunately, the amount of time I can dedicate to this is quite limited and I don't think I'd be able to implement all of this. If my solution isn't acceptable, we can probably use it locally until you guys have a chance to address the mini-allocations issue with your preferred solution. :)

**Comment by r-chris** [comment]
@samsinsane would you be able to fork and push your current changes onto a branch on github somewhere? I would be very interested to hear more about memory issues (and how to fix them) for large models. @kimkulling recently merged optional support for double precision, which (when enabled) could increase the memory requirements even further - so anything we can do to keep it down would make sense to look at for me as well.

**Comment by samsinsane** [comment]
@r-chris I've opened a PR for these changes. Sorry it took so long, been pretty busy at work.

**Comment by acgessler** [comment]
Are we sure the excess memory consumption happens in release builds as well? It's quite normal for debug heaps to have lots of overhead.

Years ago we tried replacing assimp's allocations with an arena allocator, which would just chop of pieces from large pages of ram, which were all freed together with the model. There was no significant decrease in RAM consumption and no significant performance improvements.

**Comment by kimkulling** [comment]
Yes this is a fact.

**Comment by kimkulling** [comment]
I am currently working on a separate repo for regression- and performance tests. I think we should prepare some stress-tests there. So then it should be much easier to work on measurements than working on guesses.

**Comment by kimkulling** [comment]
Closed by 8b2f1085c77ba5805f3f6c3c34d3657f54e6e952
