### ISSUE TITLE
Assimp 3.2 put downloadable windows/os binaries on site?

### ISSUE THREAD

**Issue by ddengster** [assimp/assimp#945]
As per title.

**Comment by kimkulling** [comment]
Thanks for the hint, I will take care.

**Comment by kimkulling** [comment]
I think it will be a good idea to make the latest master build from travis available as well.

**Comment by ddengster** [comment]
Hm, 8 months and still nothing? :(

**Comment by kimkulling** [comment]
Not really, forget to do it. Sorry! I will see if I can prepare it this week.

**Comment by kimkulling** [comment]
See https://github.com/assimp/assimp/releases/tag/v3.3.1
