### ISSUE TITLE
Unable to load maya exported fbx file and convert to .x

### ISSUE THREAD

**Issue by akshaysrin** [assimp/assimp#950]
Hi I have a maya binary with animation.  I exported it from maya to fbx.  Now using assimp I am trying to convert it to .x to be used with XNA Game Studio for Visual Studio 2015.  However it is failed to read the fbx file.  I am attaching the maya binary file and the fbx file.

[3HeadedDog_Attack.zip](https://github.com/assimp/assimp/files/368372/3HeadedDog_Attack.zip)

**Comment by kimkulling** [comment]
The model contains two bones with the same name. Asset-Impoter-Lib needs unique names to ensure, the we can assign them correcly.
When renaming the bone it should work.

Kim

**Comment by kimkulling** [comment]
This issue is fixed now.
