### ISSUE TITLE
Blender import generates countless (handled) exceptions, causes long import times

### ISSUE THREAD

**Issue by TrianglesPCT** [assimp/assimp#955]
Importing most .blends causes 1000's of lines like this to be spit out in vs2015.

Exception thrown at 0x00007FFC13725BF8 in Cloud.exe: Microsoft C++ exception: Assimp::Blender::Error at memory location 0x00000093AB899E00.
Exception thrown at 0x00007FFC13725BF8 in Cloud.exe: Microsoft C++ exception: Assimp::Blender::Error at memory location 0x00000093AB899E00.

 I've stepped through the code, and it seems to be intentional that it works this way, but unfortunately   importing takes much longer than it could, presumably because of all the exceptions being thrown.

**Comment by kimkulling** [comment]
Ok, we will have a look onto this issue.

**Comment by vexe** [comment]
This is still happening in the current version of Assimp as well.

**Comment by kimkulling** [comment]
Just took another view onto the issue. At the moment this is a sign that a feature is not imlemented. So from my point of view it should stay this way until we have it implemented properly.
