### ISSUE TITLE
Lots of warnings due to inconsistent use of various types

### ISSUE THREAD

**Issue by adishavit** [assimp/assimp#957]
Building the lib creates lots and lots (hundreds) of conversion loss warnings like: 
`conversion from 'size_t' to 'unsigned int', possible loss of data` (on MSVC).
There are two flavors:
1. Conversion of initialization from `double` or `float` to `ai_real`.
2. An inconsistent use and mixing of: `size_t`, `int`, `unsigned int`, `unsigned long`.

Some  of the warnings can be placated with a casts or changing local variable types, but this issue might require a more systematic approach. 
This is probably caused by some of the following:
1.  Being able to redefine `ai_real`;
2.  64-bit vs 32-bit builds, which changes what `size_t` is;  
3.  Different implementers using different conventions.

**Comment by Sailsman63** [comment]
I get a bunch of similar warnings on GCC. I'd need to redirect them to a file to track the lot. I'm also seeing warnings for unused variables. GCC is even fussing about 'misleading indentation' in some cases. I'm not really a C/C++ programmer, so I can't evaluate what's really an issue and what's a false alarm.

**Comment by kimkulling** [comment]
Closed by c849e0108da68ceddac58c299d590a33ee4314de
