### ISSUE TITLE
Reusing assimp on different OSX machine

### ISSUE THREAD

**Issue by Davelis** [assimp/assimp#959]
Hi,
I have built assimp on my macbook but i want to deploy it as part of a framework to other OSX users. So i have created CMake files which include among other things (e.g. libraries) the .dylib files and the headers which were built by CMake and Assimp. 
The problem is that the end-user creates with the help of CMake the xcode project file , opens it and builds the executable but when he tries to run it he get's a runtime error which has mypath where i built assimp (e.g. Users/..../assimp3-1-1-build/) reference to libassimpd.3.dylib "Image not found" .

Are all users supposed to build assimp on the system before use? Is there any solution to this?

Thanks in advance.

**Comment by sakrist** [comment]
It's usually linking mistake not related to library. 
I recommend you rebuild library as static.

**Comment by Davelis** [comment]
Hi, 
i already compiled it with the static lib flag set to true on CMake but it still produced .dylib files where you would expect .a one's. 
Do you know why this happens?

**Comment by sakrist** [comment]
how you configure cmake?

Here is my version
`cmake CMakeLists.txt -G 'Unix Makefiles' -DMACOSX_DEPLOYMENT_TARGET=10.9  -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9`

then `make`
