### ISSUE TITLE
Export file format with Bones and Animation

### ISSUE THREAD

**Issue by codetiger** [assimp/assimp#961]
We are planning to add Assimp to our project (iOS & Android App). In our scenario, Export is as important as Import, as we are building a 3d animation tool for mobile platforms. I see that Collada export is not complete (Animation info is missing). Let me know if there is any other file format that is 100% complete on both Export and Import. 

Otherwise, I am willing to contribute to Assimp in adding Export support for Collada. Let me know if there is already someone working on it.

**Comment by kimkulling** [comment]
The x-fileformat should be ready I guess.

Kim

Harishankar Narayanan <notifications@github.com> schrieb am Mi., 3. Aug.
2016, 12:26:

**Comment by longht89** [comment]
Hi Harishankar and Kim,

I has same this issue.

Do we have any news about your project, Harishankar? Is it running correctly?

At the moment, i has used Maya to build 3D Model. Can i use it to export x-fileformat?

Thank you

**Comment by codetiger** [comment]
Hi, Our project has a unique scenario, we needed a binary format to keep the size as small as possible and loading speed as optimal as possible. So we ended up writing our own format in binary. However, we are using this library to load different formats which are working perfect.

**Comment by longht89** [comment]
Hi Harishankar and Kim,
I'm sorry, this is my bad. This library is perfect.
Thank you for your support.

**Comment by kimkulling** [comment]
Thanks for the compliment, we are doing our really best.

Gondra B Huynh <notifications@github.com> schrieb am Mi., 24. Aug. 2016 um
13:20 Uhr:
