### ISSUE TITLE
Memory leak when filtering primitive types

### ISSUE THREAD

**Issue by rconde01** [assimp/assimp#962]
If you set up assimp to filter a primitive type:

`import->SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_POINT | aiPrimitiveType_LINE);`

and a model contains a mesh containing only one of those primitive types, you get a memory leak. The offending code is in SortByPTypeProcess.cpp. It should be:

---snip-- line 183

```
            if (!(configRemoveMeshes & mesh->mPrimitiveTypes))
            {
                *meshIdx = (unsigned int) outMeshes.size();
                outMeshes.push_back(mesh);
            }
            else
            {
               // the mesh was filtered...delete it
               delete mesh;
               bAnyChanges = true;
            }
```

where the original is:

```
            if (!(configRemoveMeshes & mesh->mPrimitiveTypes))
            {
                *meshIdx = (unsigned int) outMeshes.size();
                outMeshes.push_back(mesh);
            }
            else bAnyChanges = true;
```

Let me know if you need a pull request.

**Comment by kimkulling** [comment]
Thanks for the Report!

rconde01 <notifications@github.com> schrieb am Mi., 3. Aug. 2016, 23:44:

**Comment by kimkulling** [comment]
Shall be fixed now.
