### ISSUE TITLE
Feature-request: Command line export progress

### ISSUE THREAD

**Issue by deargonaut** [assimp/assimp#963]
_What a wonderful program you've created!!_

What I am missing though (except the lack of SolidWorks import possibility (#830)), is the possibility to view/read the progress of converting a model in command line.

As I am using the command-line for convert models to STL through a website this would be an awesome feature.

Thanks in advance!

**Comment by kimkulling** [comment]
Good idea, let's put this on trello!

deargonaut <notifications@github.com> schrieb am Fr., 5. Aug. 2016, 10:13:
