### ISSUE TITLE
two options to assimp_cmd are not documented

### ISSUE THREAD

**Issue by waldyrious** [assimp/assimp#966]
Namely `-tuv` (`--transform-uv-coords`) and `-fid` (`--find-invalid-data`). They should be described in doc/dox_cmd.h along with the other options.

If a brief description is provided (or I'm pointed to existing documentation describing them), I can make a PR adding them to dox_cmd.h :)

**Comment by kimkulling** [comment]
You are right, thanks for the report!

Waldir Pimenta <notifications@github.com> schrieb am Mo., 8. Aug. 2016,
12:48:
