### ISSUE TITLE
properly support system-installed unzip.h

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#967]
for the Debian package, the utility libraries already present in Debian are stripped from the assimp sources, e.g. `contrib/unzip/` (due to Debian policy)

unfortunately this breaks the builds, since several files have an `#include <contrib/unzip/unzip.h>` line:
- `code/IFCLoader.cpp`
- `code/Q3BSPZipArchive.h`
- `code/D3MFImporter.cpp`
- `code/D3MFOpcPackage.cpp`

a very simple fix would be to:
- add `contrib/unzip/` to the include-paths
- replace the  `#include <contrib/unzip/unzip.h>` with  `#include <unzip.h>`

this would allow the Debian package to drop some patches.

**Comment by kimkulling** [comment]
Thanks for the report, I will have a look. As far as I know the
contrib/unzip folder is already part of our include pathes ...

umläute <notifications@github.com> schrieb am Mo., 8. Aug. 2016, 16:56:

**Comment by umlaeute** [comment]
i have to admit that i haven't checked whether this is already part of the include paths...

**Comment by andyli** [comment]
This has not been done yet: replace the `#include <contrib/unzip/unzip.h>` with `#include <unzip.h>`

**Comment by umlaeute** [comment]
pinging @kimkulling
@andyli is right_ for Debian I (still, as of *4.0.1*) replace all the `<contrib/unzip/unzip.h>` with a simple `<unzip.h>`.

however, i haven't tested this on anything but Debian which uses the system provided unzip.h, so I'm reluctant to submit a patch myself.

**Comment by monkemon** [comment]
i used the quickstart guide to build from scratch


```
tom@shitbox ~/A/a/build (master)> ninja                                                    26-07-13
[1/102] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCLoader.cpp.o
FAILED: [code=1] code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCLoader.cpp.o
/usr/bin/c++ -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_M3D_EXPORTER -DASSIMP_BUILD_NO_M3D_IMPORTER -DASSIMP_BUILD_NO_USD_IMPORTER -DASSIMP_BUILD_NO_VRML_IMPORTER -DASSIMP_IMPORTER_GLTF_USE_OPEN3DGC=1 -DMINIZ_USE_UNALIGNED_LOADS_AND_STORES=0 -DOPENDDLPARSER_BUILD -DRAPIDJSON_HAS_STDSTRING=1 -DRAPIDJSON_NOMEMBERITERATORCLASS -Dassimp_EXPORTS -I/home/tom/Apps/assimp/build/include -I/home/tom/Apps/assimp/build -I/home/tom/Apps/assimp/include -I/home/tom/Apps/assimp/code -I/home/tom/Apps/assimp/. -I/home/tom/Apps/assimp/contrib/zlib -I/home/tom/Apps/assimp/build/contrib/zlib -I/home/tom/Apps/assimp/code/../contrib/pugixml/src -I/home/tom/Apps/assimp/code/../contrib/utf8cpp/source -I/home/tom/Apps/assimp/code/../contrib/rapidjson/include -I/home/tom/Apps/assimp/code/../contrib -I/home/tom/Apps/assimp/code/../contrib/openddlparser/include -I/home/tom/Apps/assimp/code/../include -I/home/tom/Apps/assimp/build/code/../include -fvisibility=hidden -fno-strict-aliasing -Wall  -O3 -DNDEBUG -std=gnu++17 -fPIC -Wno-dangling-reference -Wall -Werror -MD -MT code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCLoader.cpp.o -MF code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCLoader.cpp.o.d -o code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCLoader.cpp.o -c /home/tom/Apps/assimp/code/AssetLib/IFC/IFCLoader.cpp
/home/tom/Apps/assimp/code/AssetLib/IFC/IFCLoader.cpp:56:10: fatal error: unzip.h: No such file or directory
   56 | #include <unzip.h>
      |          ^~~~~~~~~
compilation terminated.
[14/102] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCReaderGen1_2x3.cpp.o
ninja: build stopped: subcommand failed.
```
mhm nice fix


had to manually fix ZipArchiveIOSystem, as well as IFCLoader.
I had to MANUALLY fix it. off the clock. in my free time. just to build the library.

I'm on CachyOS, had to revert from 
`#include <unzip.h>` to `#    include <contrib/unzip/unzip.h>`

then it works.

**Comment by umlaeute** [comment]
while I agree that this is somewhat urgent, I'm baffled by the following sentence: 

>  I had to MANUALLY fix it. off the clock. in my free time. just to build the library.

so what is it that you want?
are you seriously suggesting that the assimp maintainers should *MANUALLY fix it. off the clock. in their free time. just so you don't have to*?

you probably should ask for a refund.

/me is angry

**Comment by monkemon** [comment]
@umlaeute i am sorry. Yesterday i had long day at work and i wanted to code a little. Got frustrated.

I don't know where the source of this issue comes from, i bet if i'd been on ubuntu or some normal distro, it would probably work, but i like to torture myself with some weird ones XD

The issue was resolved on my end, and i've noticed it should have been fixed since 2017. Well. CachyOS has surprises. XD 


PS: 
where to ask for refund?

**Comment by umlaeute** [comment]
> where to ask for refund?

obviously there, where you paid for it.
