### ISSUE TITLE
Endless importing of model

### ISSUE THREAD

**Issue by BugGambit** [assimp/assimp#971]
Hi,

I tried to import this file: [Link](https://storage.googleapis.com/assimp_model_error/importing_forever.obj)

And the Assimp importer never finished or crashed.

My importer code is:

``` c++
importer.SetPropertyFloat(AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE, 45.0f);
importer.SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_LINE | aiPrimitiveType_POINT); //SET THIS TO REMOVE POINTS AND LINES -> HAVE ONLY TRIANGLES
scene = importer.ReadFile(
  filename,
  aiProcess_Triangulate           |
  aiProcess_GenUVCoords           |
  aiProcess_GenSmoothNormals      |
  aiProcess_OptimizeMeshes        |
  aiProcess_OptimizeGraph         |
  aiProcess_FixInfacingNormals    |
  aiProcess_JoinIdenticalVertices |
  aiProcess_SortByPType
);
```

**Comment by smalcom** [comment]
~3.6 millions vertices. May be loading is just slow?
"aiProcess_GenSmoothNormals      |
  aiProcess_OptimizeMeshes        |
  aiProcess_OptimizeGraph         |
  aiProcess_FixInfacingNormals    |
  aiProcess_JoinIdenticalVertices |
  aiProcess_SortByPType"
is a "slowing flags" and... python ;) .

On my PC loading of the model with your set of flags is taking 19 seconds.

> [20:48:53] Info,  T0: Load /home/smalcom/importing_forever.obj
> [20:48:53] Debug, T0: Assimp 3.3.125349247 amd64 gcc debug shared singlethreaded
> [20:48:53] Info,  T0: Found a matching importer for this file format: Wavefront Object Importer.
> [20:48:53] Info,  T0: Import root directory is '/home/smalcom/'
> [20:48:55] Error, T0: OBJ: Unable to locate material file BallHandNewSculpt2.mtl
> [20:48:55] Info,  T0: OBJ: Opening fallback material file /home/smalcom/importing_forever.mtl
> [20:48:55] Error, T0: OBJ: Unable to locate fallback material file BallHandNewSculpt2.mtl
> [20:48:55] Error, T0: OBJ: failed to locate material orig_01_-_Default, skipping
> [20:48:55] Skipping one or more lines with the same contents
> [20:48:55] Error, T0: OBJ: failed to locate material orig_01___Default.001, skipping
> [20:48:55] Error, T0: OBJ: failed to locate material orig_01___Default, skipping
> [20:48:55] Error, T0: OBJ: failed to locate material geo_bod2:blinn1SG, skipping
> [20:48:58] Error, T0: OBJ: failed to locate material orig_01_-_Default, skipping
> [20:49:02] Info,  T0: Entering post processing pipeline
> [20:49:02] Debug, T0: OptimizeGraphProcess begin
> [20:49:02] Info,  T0: OptimizeGraphProcess finished; Input nodes: 7, Output nodes: 1
> [20:49:02] Debug, T0: GenUVCoordsProcess begin
> [20:49:02] Debug, T0: GenUVCoordsProcess finished
> [20:49:02] Debug, T0: TriangulateProcess begin
> [20:49:02] Debug, T0: Dropping triangle with area 0
> [20:49:02] Skipping one or more lines with the same contents
> [20:49:03] Info,  T0: TriangulateProcess finished. All polygons have been triangulated.
> [20:49:03] Debug, T0: SortByPTypeProcess begin
> [20:49:03] Info,  T0: Points: 0, Lines: 0, Triangles: 6, Polygons: 0 (Meshes, X = removed)
> [20:49:03] Debug, T0: SortByPTypeProcess finished
> [20:49:03] Debug, T0: OptimizeMeshesProcess begin
> [20:49:03] Info,  T0: OptimizeMeshesProcess finished. Input meshes: 6, Output meshes: 1
> [20:49:03] Debug, T0: FixInfacingNormalsProcess begin
> [20:49:03] Debug, T0: FixInfacingNormalsProcess finished. No changes to the scene.
> [20:49:03] Debug, T0: Generate spatially-sorted vertex cache
> [20:49:06] Debug, T0: GenVertexNormalsProcess begin
> [20:49:07] Info,  T0: GenVertexNormalsProcess finished. Vertex normals have been calculated
> [20:49:07] Debug, T0: JoinVerticesProcess begin
> [20:49:12] Debug, T0: Mesh 0 (unnamed) | Verts in: 3606188 out: 903409 | ~74.9484%
> [20:49:12] Info,  T0: JoinVerticesProcess finished | Verts in: 3606188 out: 903409 | ~74.9%
> [20:49:12] Info,  T0: Leaving post processing pipeline
> [20:49:12] Info,  T0: Import done: /home/smalcom/importing_forever.obj
> [20:49:12] Info,  T0: No textures for import.
> [20:49:12] Info,  T0: Scene is ready for rendering.

Also (from valgrind):
> 1,900,573,142 bytes allocated
How many RAM you have? If you are using 32-bit OS then i have bad news for you ))

**Comment by r-chris** [comment]
May be related to: https://github.com/assimp/assimp/issues/944

**Comment by kimkulling** [comment]
You could try out the pull request related to aiFace alloc changes.

Chris <notifications@github.com> schrieb am Di., 16. Aug. 2016, 07:54:

**Comment by kimkulling** [comment]
Duplicate to #944
