### ISSUE TITLE
Layered textures with FBX file

### ISSUE THREAD

**Issue by roshanch** [assimp/assimp#973]
If we have multiple textures with layered textures, it skips all the textures except the last one. As the following piece of code:

```
void LayeredTexture::fillTexture(const Document& doc)

{

    const std::vector<const Connection*>& conns = doc.GetConnectionsByDestinationSequenced(ID());
    for(size_t i = 0; i < conns.size();++i)
    {
       const Connection* con = conns.at(i);
        const Object* const ob = con->SourceObject();
        if(!ob) {
            DOMWarning("failed to read source object for texture link, ignoring",&element);
            continue;
        }
        const Texture* const tex = dynamic_cast<const Texture*>(ob);
        texture = tex;
    }

}
```

if file has cons.size() more than 1 that means it has multiple textures, it overwrites previous ones and always returns last texture. It is FBXMaterial.cpp

**Comment by kimkulling** [comment]
Interesting, thanks for the hint.

**Comment by roshanch** [comment]
@kimkulling #983 fixes this.

**Comment by kimkulling** [comment]
Thanks a lot, merged!

roshanch <notifications@github.com> schrieb am Mo., 15. Aug. 2016, 19:02:
