### ISSUE TITLE
[FR] Supported standard

### ISSUE THREAD

**Issue by smalcom** [assimp/assimp#981]
I aws tried to build assimp-git on CentOS6 and got result which you can see on screenshot.
May be is better to point policy about language standard for project? For example C++03 or C++11, or even newer.
And make back port for released version.
Because at now project has strange requirements: part of them require C++xx feature and part can be built with old compiler. assimp-3.1 can be built on CentOS6 (gcc-4.7).

**Comment by kimkulling** [comment]
Maybe this is one task we need to adress. I am surprised to see how much older compilers are still in use.

**Comment by smalcom** [comment]
> Maybe this is one task we need to adress. 

Understood))
So, i can to adapt source code to new standard step-by-step. All i need is proclaimed rule as "Assimp use C++11". For MSVS is a MSVS15 version, for gcc is a gcc-4.8 version.
