### ISSUE TITLE
C++11 Features and MSVC2010

### ISSUE THREAD

**Issue by DarioSamo** [assimp/assimp#992]
Hello.

One of my projects that relies on assimp is currently locked down to MSVC 2010 due to needing an specific version of a certain closed source library. I've been unable to compile any further updates to Assimp since around April due to this, and there's no way to enable these features on this compiler other than updating to VS2012.

Does assimp's codebase rely on C++11 features a lot more lately or could I do a few compiler fallbacks? I understand if you'd rather not due to having to leave macros all around the codebase for this.

One of the problematic commits for example:
https://github.com/assimp/assimp/commit/18843fe5e1e94f10c38d1b4e0bc899d543892240

**Comment by kimkulling** [comment]
Could you please post your log? I guess we can try to find some workarounds.

**Comment by DarioSamo** [comment]
Here's the log: http://pastebin.com/fmrNXB3W

The problematic lines are the replacement of the boost for_each loops with the C++11 ranged for loops. The obvious fallback would be to use the far more verbose version of the loops, but I understand if it's not in the plans since it'd make it harder to read.

**Comment by smalcom** [comment]
Let me remind same question about it https://github.com/assimp/assimp/issues/981

**Comment by kimkulling** [comment]
Will not be fixed, much too much work.
