### ISSUE TITLE
Objects need to be fixed before printing

### ISSUE THREAD

**Issue by Brucewayne01** [assimp/assimp#993]
When I convert STL to OBJ files, I need to repair ( I use windows 3D builder ) them before printing , How to get fixed OBJ files with assimp ?

**Comment by kimkulling** [comment]
Could you please explain, what you mean with repairing? Do you have to fix degenerated triangles, look for holes etc.?

**Comment by Brucewayne01** [comment]
I don't know exactly what does 3D builder but I think that is fixing degenrated triangles and looking for holes , when I open the file with 3D builder, it suggests me to fix the OBJ file , and when I do it the file size decreases and it is ready for printing 

This is an example of a file converted with assimp 

[Final.txt](https://github.com/assimp/assimp/files/444528/Final.txt)

and the same file fixed with windows 3D builder

[Final-fixed.txt](https://github.com/assimp/assimp/files/444531/Final-fixed.txt)

Can I do it with assimp ?

**Comment by kimkulling** [comment]
Looks for me like removed faces + vertices done by 3D-builder. And yes, you
can do that with assimp as well. For instance you could
use JoinVerticesProcess in the post-processing.

Kim

Brucewayne01 <notifications@github.com> schrieb am Di., 30. Aug. 2016 um
12:04 Uhr:

**Comment by Brucewayne01** [comment]
Thank you, but I don't get the same result , the file still can be repaired when I open it with 3D builder. 
[final-assimp.txt](https://github.com/assimp/assimp/files/454530/final-assimp.txt)
