### ISSUE TITLE
FBXMeshGeometry assertion failure

### ISSUE THREAD

**Issue by jwwalker** [assimp/assimp#994]
I don't know whether an assertion failure always indicates a program bug in Assimp, but anyway I got this:

> Assertion failed: (count != 0), function ToOutputVertexIndex, file /open-source/assimp/code/FBXMeshGeometry.cpp, line 245.

on the FBX version of [this free model](http://tf3dm.com/download-page.php?url=black-dragon-rigged-and-game-ready-92023).

**Comment by kimkulling** [comment]
This is an expectation of the developer. We will check that.

**Comment by kimkulling** [comment]
Which version do you use? Latest master: dae.-model works

**Comment by jwwalker** [comment]
Latest master of assimp.  You are correct that the dae model works, but as I said, the fbx model gives an assertion failure.

**Comment by kimkulling** [comment]
Ops, sorry. My mistake!

James Walker <notifications@github.com> schrieb am Di., 6. Sep. 2016, 18:35:

**Comment by kimkulling** [comment]
Got it, when tryingo to translate a temporary vertex-index to its corresponding output vertex assimp checks if there is an output vertex. If not, the assertion happens. 
I guess this is could happen when working with some kind of buggy models, so I will make the test a little bit less strict.
